### ISSUE TITLE
HARDFORK - Precision on VESTS is insufficient for long-term use.

### ISSUE THREAD

**Issue by revflash** [steemit/steem#1]
The VESTS symbol has a precision of 0.000001 which will be unable to accurately represent the result of converting 0.001 STEEM to VESTS once the ratio of `total_vesting_fund_steem` to `total_vesting_shares` reaches 1000. Rounding errors start having an impact much sooner.

We estimate that rounding errors will become an issue in as little as 6 months.  

The solution is to increase the precision of VESTS by a factor of 1000000.  It can be achieved by instantaneously multiplying all VESTS on the network by 1M on the hard-fork block and thereafter require the higher precision version of VESTS for all `withdraw_vesting` operations.

Values that need to be multiplied include:
1. global_property_object::total_vesting_shares
2. account::vesting_shares
3. account::vesting_withdraw_rate

Additionally all places that use vesting_shares to derive additional computations which includes:
1. bandwidth measurement
2. reward shares
3. witness voting

In all of these places, the additional precision required for VESTS is not nearly as relevant because they all depend upon % of total VESTS rather than absolute vests. So long as the calculated rshares retains the same magnitude of precision before and after the hard fork it should have relatively little impact.

Short Term Impact
-------------------------
If left unchanged then converting small amounts of STEEM to VESTS will result in increasingly large rounding errors. This will have the largest impact on:

1. block producers and miners converting 1.000 STEEM at a time to VESTS
2. content producers and curators earning small amounts of STEEM that get converted to VESTS

Questions to Ponder
----------------------------

### How long will a precision of .000000000001 be sufficient for VESTS?

Rounding errors start having a measurable impact once the ratio of total_vesting_fund_steem to total_vesting_shares crosses 1M.  This should happen once the STEEM supply crosses 1,000,000,000,000.000.  The STEEM supply grows at about 500,000,000 STEEM per year initially and in the long term grows by 113% per year. This means that in as little as 10 years the STEEM supply could reach a point where VESTS precision is in trouble.

### How will JavaScript represent total_vesting_shares? 

1,000,000.000000000000 VESTS will require 2^60 bits which cannot be represented as an integer in JS (limit 2^53). This means it will have to be approximated in JS causing rounding errors in the user interface.

### Should we implement a reverse-stock-split?

A reverse stock split will require the following:
   1. a block interval that is long enough to iterate over all accounts and update all balances 
   2. support from all exchanges
   3. an update of all price feeds
   4. individuals with an odd balance will lose .001 STEEM.  
   5. an update of price history to reflect the split.

The reverse-stock-split is the only long-term sustainable solution otherwise the number of bits required to represent balances will grow by 1.13 bits per year.  The network needs 39 bits after 1 year, crosses 53 bits within just 10 years and outgrows 64 bits in less than 20 years.

The protocol as a whole can remain valid (not requiring changes to transaction structure) so long as users transact in STEEM amounts less than 64 bits.  This maximum transaction size will shrink to 1% of all STEEM in less than 5 years after the 64 bit limit is hit. 

Other options include:
1. adopting some deterministic floating point - will still introduce rounding errors
2. adopting 256 bit integers should allow the network to live for 100+ years

In the interest of keeping all numbers on a "human scale" implementing a 4:1 reverse-stock-split every 4 years should should keep all numbers within a friendly territory until the market has changed enough to justify an entire protocol upgrade. It has the added benefit of giving us over 3 years to implement.

**Comment by revflash** [comment]
There is another option that could be implemented with relatively little impact on all existing code:

Implement a 1:1000000 stock split on VESTS. Under this model all that is necessary is an update to: 
1. global_property_object::total_vesting_shares
2. account::vesting_shares
3. account::vesting_withdraw_rate

This would have the impact of devaluing any pending votes, but that isn't terribly relevant at this point in time.

**Comment by xeroc** [comment]
If I recall correctly, the Ethereum-Mist wallet is also using JavaScript even though Ethereum has 18 decimal places. They overcome the calculation issues by using [BigNumber.JS](https://github.com/MikeMcl/bignumber.js/) 

See here: https://github.com/ethereum/wiki/wiki/JavaScript-API#a-note-on-big-numbers-in-web3js

**Comment by abitmore** [comment]
@revflash looks like the rounding issue has taken effects already? With Current rate 31:1, new miners are now unable to convert STEEM to VESTS due to available bandwidth = 0.
```
  "vesting_shares": "0.031210 VESTS",
  "vesting_withdraw_rate": "0.000000 VESTS",
  "next_vesting_withdrawal": "1969-12-31T23:59:59",
  "withdrawn": 0,
  "to_withdraw": 0,
  "proxied_vsf_votes": 0,
  "average_bandwidth": 0,
  "lifetime_bandwidth": 0,
  "last_bandwidth_update": "1970-01-01T00:00:00",
  "average_market_bandwidth": 0,
  "last_market_bandwidth_update": "1970-01-01T00:00:00",
  "last_post": "1970-01-01T00:00:00"
```
