### ISSUE TITLE
Unbalanced Curation Rewards

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#101]
![image](https://cloud.githubusercontent.com/assets/347290/16165333/385ac2d2-34b1-11e6-925b-195966132501.png)

**Comment by clayop** [comment]
This is really persuading. I like it and want to see the details on Steemit.

**Comment by bytemaster** [comment]
![image](https://cloud.githubusercontent.com/assets/347290/16247247/dcf19f1e-37d6-11e6-9efb-a99c01cc8332.png)

**Comment by bytemaster** [comment]
![image](https://cloud.githubusercontent.com/assets/347290/16247953/590a0354-37da-11e6-8c45-65ea02bb6bf3.png)

**Comment by mvandeberg** [comment]
New curves implemented and merged. Details explained in the following blog posts...

https://steemit.com/steemit/@steemitblog/overhaul-of-curation-rewards
https://steemit.com/steem/@steemitblog/latest-curation-reward-solution
