### ISSUE TITLE
API active_votes request

### ISSUE THREAD

**Issue by feruzm** [steemit/steem#1011]
Can you guys add `active_votes` to `get_content_replies` API?

As of now, `get_content_replies` returns object that has `active_votes` empty array, doesn't have data in it.

Following can be added:
`result.active_votes = get_active_votes( author, permlink );`
around this line 
https://github.com/steemit/steem/blob/5fb8e8f827f73d80847b98bb7bdebae7361289c6/libraries/app/database_api.cpp#L1185

**Comment by mvandeberg** [comment]
This can easily be obtained in the new `database_api`.
