### ISSUE TITLE
Feature Request: Remove the limitation that people can only reply once every 20 seconds.

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#1012]
Now people can only reply once every 20 seconds. It's very annoying.

**Comment by merej99** [comment]
Annoying yes, but slows down the "Nice post" spammy comments IMHO

Would rather love to see better comment rewards for comments over 100 characters long.

**Comment by TimCliff** [comment]
once per block (similar to the voting limit) might be a good compromise.

**Comment by mvandeberg** [comment]
Closed in #2019
