### ISSUE TITLE
steemd RPC JSON output is incorrectly formatted

### ISSUE THREAD

**Issue by l0k1-smirenski** [steemit/steem#1014]
Here is block 1 as output by the query get_block ( 1 ):

```json
{'extensions': [],
 'previous': '0000000000000000000000000000000000000000',
 'timestamp': '2016-03-24T16:05:00',
 'transaction_merkle_root': '0000000000000000000000000000000000000000',
 'transactions': [],
 'witness': 'initminer',
 'witness_signature': '204f8ad56a8f5cf722a02b035a61b500aa59b9519b2c33c77a80c0a714680a5a5a7a340d909d19996613c5e4ae92146b9add8a7a663eef37d837ef881477313043'}
```

I used markdown code highlighting specifically to show that it is all incorrectly formatted. The strings for values and keys should be surrounded by double quotes, inside the strings escaped as `\"`. To import it into python data structures it first has to be processed using a complex series of substring substitutions before the json module will accept the input.

In fact, it gets even worse, as I have discovered looking at more snippets containing string values from a post:

```json
 'Without any further ado, here is '
'the python script, it depends on '
"`piston-lib`'s module `pistonapi` "
'from @xeroc.\n'
```

I suspect it's going to take at least 10 lines of code to process every line of the output to correct it.

**Comment by Gandalf-the-Grey** [comment]
Not true.
How you got that broken output?
For both `cli_wallet` and `curl` it works perfectly fine.
Returns VALID JSON (RFC 4627)
Checked on block 1 and 10000000.

**Comment by l0k1-smirenski** [comment]
I got it from piston-lib. So the issue is in Piston then??? Ok, close the issue then, I will try that with curl.

**Comment by l0k1-smirenski** [comment]
I have confirmed that what you say is correct. Thankyou.

**Comment by xeroc** [comment]
This is the output of `pprint.pprint` .. if you use `print(json.dumps(x))` instead, it should be proper JSON
