### ISSUE TITLE
Unnecessary assignment of _db in evaluators

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1023]
In [evaluator.hpp:36-39](https://github.com/steemit/steem/blob/master/libraries/chain/include/steemit/chain/evaluator.hpp#L36-#L39) the evaluator has `_db` defined as protected and `db()` returns `_db`.

All evaluators have a line `database& _db = db();` which needlessly redefines `_db` in the local scope. This line can be removed.

If keeping `_db` safe is important then `evaluator::_db` should be made private and `evaluator::db()` inlined.

**Comment by theoreticalbts** [comment]
I don't like having the `db()` accessor, we should just have it access the member variable.
