### ISSUE TITLE
boost 1.58 issues & doc needs to be updated

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1030]
Building latest with Boost 1.58 did not work on Ubuntu. @mvandeberg suggested the minimum may need to be 1.59 instead.

**Comment by Gandalf-the-Grey** [comment]
https://github.com/steemit/steem/pull/1034

**Comment by pfunks** [comment]
Boost 1.58 is in the Ubuntu 16.04 APT repo. Since boost takes forever to build, that's been pretty convenient.

**Comment by mvandeberg** [comment]
The error on 14.04 is gcc, not with Boost. The requirements are Boost 1.58 and gcc 4.9. 16.04 is compatible on both fronts out of box.
