### ISSUE TITLE
Possible multiplication overflow while processing withdraw (develop branch)

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#106]
Possible issues on [this line](https://github.com/steemit/steem/blob/309766f7a3126e821bc8a3635be0b3b7d32e84e4/libraries/chain/database.cpp#L1550) and [this line](https://github.com/steemit/steem/blob/309766f7a3126e821bc8a3635be0b3b7d32e84e4/libraries/chain/database.cpp#L1577).

By the way I thought there will be rounding issues (which would cause addition overflow), but it turned out not to be the case.

**Comment by mvandeberg** [comment]
Is this a non-issue then?

**Comment by abitmore** [comment]
Multiplication overflow exists. Try power down with `steemit` account.

**Comment by abitmore** [comment]
Account `steemit` currently has `255430823626.923818 VESTS`, if vest 100% to another account, every week the result of `to_withdraw * percent` is `24,560,656,117,973,444,038` which is more than 64 bit.

**Comment by mvandeberg** [comment]
You are correct. It would appear the withdraw rate is just barely over the max before overflow.
