### ISSUE TITLE
labels/tags in non-english unicode do not have lowercase

### ISSUE THREAD

**Issue by themusicgod1** [steemit/steem#1066]
Attempting to create a post entirely in, say, [simplified?] chinese unicode, say "场", fails because I need to enter in a tag  "Use only lowercase letters, digits and one dash".  This means nothing in some non-english languages.

**Comment by mvandeberg** [comment]
This is a condenser issue, not a steemd issue. I have forwarded the problem on to them.

**Comment by themusicgod1** [comment]
link?

**Comment by mvandeberg** [comment]
I sent it to them internally as I was not sure if it was a duplicate issue or not.

**Comment by themusicgod1** [comment]
Internally where?  Where does one go to follow this up?

**Comment by roadscape** [comment]
@themusicgod1: discussion continues at https://github.com/steemit/condenser/issues/1366
