### ISSUE TITLE
Prefix configuration constants with STEEMIT_

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1069]
Many `#define` names don't have `STEEMIT_` prefix.  Here is a list:

- `VIRTUAL_SCHEDULE_LAP_LENGTH`
- `DEFINE_EVALUATOR`
- `DEFINE_PLUGIN_EVALUATOR`
- `DEFAULT_VALUE_VECTOR`
- `LOAD_VALUE_SET`
- `*_SPACE_ID`
- `*_PLUGIN_NAME`
- `DECLARE_OPERATION_TYPE`
- `DEFINE_OPERATION_TYPE`

I think we'll make an exception for `*_SYMBOL` macros and leave them as-is, since there are plenty of places in the code where a longer name for those symbols would make code hard to read.

**Comment by mvandeberg** [comment]
This is a subest of the changes described in #1268

**Comment by mvandeberg** [comment]
I misread the issue. Reopening. But it is still related.

**Comment by mvandeberg** [comment]
Considering the change in #1268, these should be prefixed `STEEM_`

**Comment by Kiwonik** [comment]
1. One symbol from the list - DEFAULT_VALUE_VECTOR - is missing (probably removed earlier).
2. The symbol STEEMIT_PRIVATE_MESSAGE_COP_ID is defined, but used nowhere.
3. There are several symbols that are not present on the list, that may need prefixing with STEEM_ (e.g. RESERVE_RATIO_..., FC_REFLECT...).

**Comment by mvandeberg** [comment]
`FC_*` should remain that way. They are defined in a dependency.
