### ISSUE TITLE
Tag plugin shouldn't sort tags alphabetically.

### ISSUE THREAD

**Issue by NateBrune** [steemit/steem#1087]
https://github.com/steemit/steem/blob/master/libraries/plugins/tags/tags_plugin.cpp#L103-L144

This function parses the metadata of comments, stores all tags into `meta`, and then updates the first five tags in `meta`. The problem is that currently, `meta` is alphabetically sorted. If a user sets their tags in the order of ["z","y","x"."c","b","a"], then currently "z" will be dropped even though the user specified that tag first.

**Comment by mvandeberg** [comment]
Tags are now handled by hivemind. No changes will be made to their implementation in steemd.

@roadscape to close if this issue needs to be copied to the hivemind repo, or if it is a non-issue.
