### ISSUE TITLE
Able to down-vote a post which disabled voting?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#109]
According to [this code](https://github.com/steemit/steem/blob/825c31af0c0d11a8d8d707306caaae540c9d885b/libraries/chain/steem_evaluator.cpp#L624):
```
if( o.weight > 0 ) FC_ASSERT( comment.allow_votes );
```
it won't check `comment.allow_votes` when `o.weight < 0`

**Comment by mvandeberg** [comment]
Posts with 0 net_rshares are still shown. Negative are hidden on the UI. Being able to downvote spam is an important part of moderation. Disabling votes is a way for spammers to prevent their spam from being hidden.
