### ISSUE TITLE
Pages are always gzip-compressed, even when Accept-encoding is not set

### ISSUE THREAD

**Issue by ProgVal** [steemit/steem#1091]
Hi,

I hope this is the right place for posting this bug report.

The web server at https://steemit.com/ always sends content with gzip compression, even when Accept-encoding is not set.
To notice it, try getting the content of the website with a client that does not support gzip decompression, eg. `curl https://steemit.com`. You will see gzip content as the output.

**Comment by mvandeberg** [comment]
[Condenser](https://github.com/steemit/condenser) is the repo for steemit.com. This repo is only for blockchain related issues.

**Comment by ProgVal** [comment]
Ok, thanks. I opened a new issue at https://github.com/steemit/condenser/issues/1406
