### ISSUE TITLE
Issue with lazy deleting votes

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#110]
With [this code](https://github.com/steemit/steem/blob/309766f7a3126e821bc8a3635be0b3b7d32e84e4/libraries/chain/database.cpp#L1830-L1833):
```
         modify( cur_vote, [&]( comment_vote_object& cvo )
         {
            cvo.num_changes = -1;
         });
```
`comment_vote` objects won't get removed after a payout.

What if there is a second payout (when someone voted on the post again)? I can image that old votes still hang there and will be paid one more time, since `num_changes` has been checked [here](https://github.com/steemit/steem/blob/309766f7a3126e821bc8a3635be0b3b7d32e84e4/libraries/chain/database.cpp#L1737-L1751).

**Comment by mvandeberg** [comment]
Our intent was to only have curation rewards on the first payout. The current code does not do this. Making necessary changes.
