### ISSUE TITLE
Allow Power Ups if account has zero SP

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#1116]
Currently if an account Powers Down, it is not allowed to transact. In order to be able to transfer Powered Down STEEM out of the account, it would need at least some SP. Allowing the user to Power Up some STEEM would give them the ability to use the account again, without needing to get help from another account.

Related to https://github.com/steemit/condenser/issues/1263

**Comment by mvandeberg** [comment]
We have some plans in the work to address this very awkward situation.

**Comment by TimCliff** [comment]
Ok, I'll close the issue then. Thanks!
