### ISSUE TITLE
Initial account creation failed

### ISSUE THREAD

**Issue by pixelstitch** [steemit/steem#1117]
G'day guys,
Yesterday i signed up for my business name 'pixelstitch'...
It was approved and a link was sent to me.
When continuing with the password and account creation i get the following error.

pixelstitch

Couldn't create account. Server returned the following error:
10 assert_exception: Assert Exception creator.vesting_shares - creator.delegated_vesting_shares - asset( creator.to_withdraw - creator.withdrawn, VESTS_SYMBOL ) >= o.delegation: Insufficient vesting shares to delegate to new account. {"creator.vesting_shares":"4696505703.664181 VESTS","creator.delegated_vesting_shares":"4696263000.000000 VESTS","required":"301000.000000 VESTS"} th_a steem_evaluator.cpp:206 do_apply {"op":["account_create_with_delegation",{"fee":"1.000 STEEM","delegation":"301000.000000 VESTS","creator":"steem","new_account_name":"pixelstitch","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72a66WdwKR1dotcNnSqxBeGkeAJMvDJHG8GZDLQXfEy8M8h5YS",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ZNvWtVDBu6npfhSVtoqPJGk6L95RXnfKhmKEfn7b2tAgcGKfW",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7cQTEWSYwJE15sVWAy9tmEqyrF4xKfaTPg61ez1oDsNDtvBKat",1]]},"memo_key":"STM7HnmUCthbBVoVXM6HxFXLGiB269wd5KsEV4Cp9LFKcTzKTCeKs","json_metadata":"","extensions":[]}]} th_a database.cpp:2990 _apply_transaction {"trx":{"ref_block_num":28687,"ref_block_prefix":2188310397,"expiration":"2017-05-18T00:16:45","operations":[["account_create_with_delegation",{"fee":"1.000 STEEM","delegation":"301000.000000 VESTS","creator":"steem","new_account_name":"pixelstitch","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72a66WdwKR1dotcNnSqxBeGkeAJMvDJHG8GZDLQXfEy8M8h5YS",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ZNvWtVDBu6npfhSVtoqPJGk6L95RXnfKhmKEfn7b2tAgcGKfW",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7cQTEWSYwJE15sVWAy9tmEqyrF4xKfaTPg61ez1oDsNDtvBKat",1]]},"memo_key":"STM7HnmUCthbBVoVXM6HxFXLGiB269wd5KsEV4Cp9LFKcTzKTCeKs","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["207cbeae1a8bfdc51bc84d8d01c95515b30db867748b65884aa316f412614456bf08ed2dd3d40ba9fcce719021e580cd6dcc468f4a0dd167afa938f67faf1a6710"]}} th_a database.cpp:2994 _apply_transaction {"trx":{"ref_block_num":28687,"ref_block_prefix":2188310397,"expiration":"2017-05-18T00:16:45","operations":[["account_create_with_delegation",{"fee":"1.000 STEEM","delegation":"301000.000000 VESTS","creator":"steem","new_account_name":"pixelstitch","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72a66WdwKR1dotcNnSqxBeGkeAJMvDJHG8GZDLQXfEy8M8h5YS",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ZNvWtVDBu6npfhSVtoqPJGk6L95RXnfKhmKEfn7b2tAgcGKfW",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7cQTEWSYwJE15sVWAy9tmEqyrF4xKfaTPg61ez1oDsNDtvBKat",1]]},"memo_key":"STM7HnmUCthbBVoVXM6HxFXLGiB269wd5KsEV4Cp9LFKcTzKTCeKs","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["207cbeae1a8bfdc51bc84d8d01c95515b30db867748b65884aa316f412614456bf08ed2dd3d40ba9fcce719021e580cd6dcc468f4a0dd167afa938f67faf1a6710"]}} th_a database.cpp:735 push_transaction {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":28687,"ref_block_prefix":2188310397,"expiration":"2017-05-18T00:16:45","operations":[["account_create_with_delegation",{"fee":"1.000 STEEM","delegation":"301000.000000 VESTS","creator":"steem","new_account_name":"pixelstitch","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72a66WdwKR1dotcNnSqxBeGkeAJMvDJHG8GZDLQXfEy8M8h5YS",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ZNvWtVDBu6npfhSVtoqPJGk6L95RXnfKhmKEfn7b2tAgcGKfW",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7cQTEWSYwJE15sVWAy9tmEqyrF4xKfaTPg61ez1oDsNDtvBKat",1]]},"memo_key":"STM7HnmUCthbBVoVXM6HxFXLGiB269wd5KsEV4Cp9LFKcTzKTCeKs","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["207cbeae1a8bfdc51bc84d8d01c95515b30db867748b65884aa316f412614456bf08ed2dd3d40ba9fcce719021e580cd6dcc468f4a0dd167afa938f67faf1a6710"]}]]} th_a websocket_api.cpp:124 on_message (see err.payload for the full error payload)

**Comment by mvandeberg** [comment]
This is not a Steem blockchain issue, but is related to our faucet. We are aware. I am closing this issue.
