### ISSUE TITLE
They are break steem community. we should discuss a solution.

### ISSUE THREAD

**Issue by soosgit** [steemit/steem#1122]
it looks like someone is a bad programmer and @yougotflagged doesn't work as it should. Same thing for @steemservices and @thebotkiller.

Steem has many powerful bots belongs to indivisual? 
one same time many very powerful accounts are downvote my aritlce without any comments.

can i keep activity in steem?

they will continus downvote to my future articles.

see more detail below article. 
[Can you explain downvote reason? why did you downvote without any comment? i want feedback to improve my posting.](https://steemit.com/steemit/@ludorum/can-you-explain-downvote-reason-why-did-you-downvote-without-any-comment-i-want-feedback-to-improve-my-posting)

**Comment by TimCliff** [comment]
@soosgit - it is a good discussion to have, but it is not something to open a GitHub issue for. Please read the guidelines for contributing before opening issues. @sneak to close.
