### ISSUE TITLE
Reward Curves Incorrect

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1124]
The reward curve logic is wrong.

https://github.com/steemit/steem/blob/steem-prerelease-v0.19.0/libraries/chain/util/reward.cpp#L86-#L90

Should be

``` c++
case linear:
   result = rshares;
   break;
case square_root:
   result = approx_sqrt( rshares );
   break;
```

**Comment by theoreticalbts** [comment]
Still doesn't look right.
