### ISSUE TITLE
Invisible header overlaps scrollbar

### ISSUE THREAD

**Issue by gruppler** [steemit/steem#1134]
When viewing a post as a modal overlay, there's an invisible DIV with the class "PostsList__post_top_overlay" that overlaps the top part of the scrollbar.

**Comment by Tadasu85** [comment]
This is a condenser issue not a steem blockchain issue. See this repo for condenser issues. https://github.com/steemit/condenser

**Comment by mvandeberg** [comment]
Tadasu85 is correct. Closing this
