### ISSUE TITLE
New posts cause purging of old blog_objects yet reblogs do not

### ISSUE THREAD

**Issue by arhag** [steemit/steem#1137]
I believe the problem within the follow plugin described in this issue is the reason behind [this issue](https://github.com/steemit/condenser/issues/1445) posted in the condenser repository.

A new top-level post [creates](https://github.com/steemit/steem/blob/v0.19.0rc1/libraries/plugins/follow/follow_plugin.cpp#L244-L249) a new `blog_object` as intended but also [purges](https://github.com/steemit/steem/blob/v0.19.0rc1/libraries/plugins/follow/follow_plugin.cpp#L254-L258) old `blog_object`s to limit the size of the blog entries (per account) to `max_feed_size` (default of 500).

However, while a `reblog_operation` also [creates](https://github.com/steemit/steem/blob/v0.19.0rc1/libraries/plugins/follow/follow_evaluators.cpp#L141-L147) a new `blog_object` as intended, it does not do any purging of the blog entries in the rest of that function.

This asymmetry in behavior does not make sense, so I suspect it is just a bug. Either both should be purging to limit the number of blog entries per account to some finite number such as 500 to save memory, or neither of them should do any purging, thus allowing the entire sequence of all top-level posts + reblogs to be available in chronological order for each user. I would prefer the latter if memory considerations allow, so that the entire history of a user's blog can be scrolled through on steemit.com.

Should the choice be to limit the size of blog entries instead, there is at least no reason why steemit.com cannot expose an interface to allow the user to scroll through the entire history of any user's top-level posts (not including reblogs) like they currently can with comments since the `comment_object`s need to be stored in the database anyway, so there aren't any memory advantages in that case. In fact, such a tab on steemit.com to just view an account's top-level posts without the reblogs is already a desired feature in the community, and considering the same code currently used to display comments with just some very minor tweaks can be used for this purpose, I am surprised why this feature doesn't exist already.

**Comment by mvandeberg** [comment]
The intent behind the follow plugin was to only track the blog for so long. Reblogging not purging old `blog_objects` is a bug. The toolset we are developing for communities also smooths a few of the rough edges of the follow plugin. I will see if the new toolset will work this way or not.

**Comment by mvandeberg** [comment]
Blogs are now handled by hivemind. No changes will be made to their implementation in steemd.

@roadscape to close if this issue needs to be copied to the hivemind repo, or if it is a non-issue.
