### ISSUE TITLE
My tagged posting is invisible in 'created/tag'

### ISSUE THREAD

**Issue by ydlee1227** [steemit/steem#1139]
I've posted article with tag 'golf'
But it is invisible in www.steemit.com/created/golf.
Is there any algorithms for removing articles from tag?
Following is my article which is tagged 'golf'
https://steemit.com/kr/@coinmaker/why-i-love-golf

It doesn't appear in golf tag.
https://steemit.com/created/golf

Thank you for your help in advance.

**Comment by TimCliff** [comment]
Looks like the same issue as https://github.com/steemit/steem/issues/781

**Comment by mvandeberg** [comment]
Tags are now handled by hivemind. No changes will be made to their implementation in steemd.

@roadscape to close if this issue needs to be copied to the hivemind repo, or if it is a non-issue.
