### ISSUE TITLE
Fix Warnings

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1147]
For obvious reasons, we should attempt to remove all warnings from build process. Additionally, we should replace all TODO comments with `#warning` directives so that they are more visible and we can clean up code more reliably.

**Comment by mvandeberg** [comment]
Rather than `#warning` directives, we should use `#pragma message` so that the TODOs are visible while building but we could still fail the build on warnings in the future.

**Comment by vogel76** [comment]
Please try to define some helper macro, ie like this:
```
#define MSG(x) __FILE__ "(" _STRING( __LINE__ ) "): " x
```
to be used together with `#pragma message` to make printed message potentially 'clickable' format in the IDEs used at development.
