### ISSUE TITLE
Possible unintended behavior at first payout

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#115]
[This check](https://github.com/steemit/steem/blob/e343e5f80d6ad682be7a9191fe3eb5ec62271d30/libraries/chain/database.cpp#L2075) would perhaps return true at first payout.

**Comment by mvandeberg** [comment]
Updated July 4th payout and distribution changes to use the hard fork logic. The voting between for hardforks provides the requisite time to guarantee current pending payouts use the current distribution.
