### ISSUE TITLE
Re-implement plugin manifest code generator using Python + jinja2

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1157]
The current plugin manifest code generator in `libraries/manifest` uses `CMake` to enumerate plugins like [this](https://github.com/steemit/steem/blob/d04a62953c3b9ec9aab8ba8051848d8d1da18f0c/libraries/plugins/CMakeLists.txt) and output generated code like [this](https://github.com/steemit/steem/blob/d04a62953c3b9ec9aab8ba8051848d8d1da18f0c/libraries/manifest/CMakeLists.txt#L13-L16).  This code generation is not flexible enough to allow plugins to provide index extensions.

This ticket is to reimplement the CMake-based code generation using Python and the `jinja2` template engine.

**Comment by mvandeberg** [comment]
Merged
