### ISSUE TITLE
Bandwidth limit exceeded

### ISSUE THREAD

**Issue by kurtr** [steemit/steem#1158]
Hi,

I just logged in for the first time in a few months. On my account I seem to have powered down to 0 steem power. When I try to withdraw my available steem I get the message _"kurtrohlandt bandwidth limit exeeded. Please wait to transact or power up STEEM."_.

My understanding is that this is due to me having 0 steem power, however I receive the same message when trying to power up.
![screenshot from 2017-06-06 12-03-43](https://cloud.githubusercontent.com/assets/1468721/26824063/36f38a30-4ab0-11e7-9e87-b8146fa356fd.png)

**Comment by kurtr** [comment]
OK I had to use btc to buy sp before it would allow me to withdraw. Still makes no sense that you cannot powerup using steem in this position

**Comment by mvandeberg** [comment]
We have changes in the works to address this problem.

**Comment by sneak** [comment]
Yes, this is an unfortunate side effect of powering down completely.  I'm glad to hear you got your issue resolved, and we will be fixing this issue in our next major release. :)

**Comment by josiah14** [comment]
Just an informational note, this issue is preventing me from completing the sign-up process.  Supposedly, I should have gotten some free Steem with sign-up, so maybe this issue ties to that mechanism?

**Comment by looksfarwoman** [comment]
I'm new to Steemit and getting a bandwidth exceeded message. I've made rookie mistakes, like transferring my Steem' to savings. I have no cryptocurrency, except for a little etherium on Coinbase. I'm effectively locked out and can't find out how to fix this. Please help as I'm having Steemit withdrawal.

**Comment by TimCliff** [comment]
If the network is experiencing heavy usage, users with low amounts of Steem Power may be rate limited for short periods of time. Try again in an hour or two, and hopefully it will be letting the transactions through again.

**Comment by looksfarwoman** [comment]
Thank you so much. Fingers crossed (patience is not one of my virtues LOL).
I'll see how it goes over the next few hours.

**Comment by josiah14** [comment]
I was able to compete signup since my last comment on here. Thanks, all!
