### ISSUE TITLE
Add block to free memory message

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1179]
When getting a free memory message live, you know the block number, but when reindexing there is only a range. It would be nice to have exact block numbers so we can accurately track memory usage over time.

A reindex does show us free memory every 100k blocks, but the extra data points would be nice.

**Comment by vogel76** [comment]
Could you point us to some place in the code related to free memory messaging to have some startpoint for further analysis ?

**Comment by mvandeberg** [comment]
In database.cpp anywhere `get_free_memory` is called.

**Comment by mariusztrela** [comment]
"...there is only a range"
What do you mean by saying 'range'?
There is only info abouts blocks:  "double( cur_block_num * 100 ) / last_block_num << "%   " << cur_block_num << " of " << last_block_num"

"...extra data points would be nice"
What points? Do you want to remove 'if( cur_block_num % 100000 == 0 )' condition ?

**Comment by mvandeberg** [comment]
I wrote the original message poorly.

On reindex we get free memory every 100000 blocks. It would be nice on the generic "Free memory is now" messages to have the head block num.

**Comment by mvandeberg** [comment]
Earlier blocks we have more data points because memory is not used quickly. Now, 100k can eat up 6-7Gb. It would be nice to have those block numbers to better track our memory growth.

**Comment by mariusztrela** [comment]
Done, but this issue is not assigned to any project.
