### ISSUE TITLE
Delegating VESTS behavior

### ISSUE THREAD

**Issue by 4Ykw** [steemit/steem#1182]
I have two questions in regards to VESTS:

1. Recently I have [delegated VESTS (13k) to the user msg768](https://steemdb.com/block/12670656) and he claimed to have "lost" his previous 105 "delegated" STEEM POWER from his account. The only delegated STEEM POWER he had after my delegation was from my 13k VESTS. I then attempt to [send another](https://steemdb.com/block/12671295) 221k VESTS and it resets the previous 13k VESTS. Along the process, the VESTS I have been delegated were also reduced from the amounts I delegated. His this the intended behaviour?

2. Where in the blockchain I can see the revoke messages from either the situation above (in case it was a revoke) or for when we revoke someone's delegated SP.

Thanks for all the hard work.

**Comment by TimCliff** [comment]
The revoked SP was originally delegated from the steem account. They revoked it in this block, which can be seen under the steemd.com account history. It was more of a coincidence that it happened about a day before you delegated the 13k, which probably made it seem like the one erased the other if you compared the amounts between the two days. They were independent transactions though, and the 105 SP was removed before you delegated any to the account.

https://steemd.com/tx/06c30f3c7eb3edc6a31d69b4e79f335af3cf0002

**Comment by 4Ykw** [comment]
Thanks for that. I see.

Last questions...

3. Is there a way to check the amount of delegated received vests of a user at a specific block without having to roll over all transaction since user creation?

4. What is the algorithm for steam to revoke or re-delegate a new vests number?

Cheers

**Comment by TimCliff** [comment]
Sorry, but the GitHub repository is not the appropriate place for these discussions. Please ask for help from the users in #help of Steemit.chat.

**Comment by 4Ykw** [comment]
Understood.

**Comment by sneak** [comment]
FYI our de-delegation script removed all but 5SP of delegation for almost everyone - but if they had at least 5SP otherwise it removed our entire delegation. You may have triggered this with your second delegation.
