### ISSUE TITLE
newplugin.py : Move applied_block registration from plugin_startup() to plugin_initialize()

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1183]
Usually when you do things on a per-block basis, you want it to occur on reindex as well, which means the registration for the `applied_block` handler needs to occur in `plugin_initialize()`.

**Comment by theoreticalbts** [comment]
`newplugin.py` is broken by `appbase` #1311.

I haven't written any code for this, so I'm removing my assignment.

**Comment by mvandeberg** [comment]
Closing, obsoleted by #1311
