### ISSUE TITLE
Need a way to use the market_history_api...

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#119]
Unable to access the history API by adding it to the config:
```
enable-plugin = witness account_history tags follow market_history
public-api = database_api login_api network_broadcast_api follow_api market_history_api
```
We did a work-around and added this:
`wild_access.allowed_apis.push_back( "market_history_api" );`

**Comment by mvandeberg** [comment]
I don't believe this is an issue anymore?

**Comment by theoreticalbts** [comment]
Closing ticket due to age and lack of comments.
