### ISSUE TITLE
Deadlock with multiple readers

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1191]
Running steemd with multiple read processes can deadlock. The exact scenario is interesting in that the readers hand trying to acquire the shared lock and the writer hangs trying to release the exclusive lock. It appears that our use case may be undefined. While we aren't needing any recursive locking, we don't avoid it either and that may cause undefined behavior.

Instead, I have written a naive but well defined read/write mutex. It is slightly slower, but still competitive with the boost implementation. This will get us immediate gains with parallel readers. The implementation should be optimized in the future when we have some more time.

**Comment by theoreticalbts** [comment]
It needs some comments to describe the implementation.  Here are some of the things I don't understand from looking at the code, that need to be documented:

- Modifying `_readers` is sometimes protected by `_write_mutex` and sometimes not.  Why?
- The `lock()` implementation calls `write_mutex.lock()` but doesn't free it when it checks the readers.  Could this lead to deadlock?
- Why `cond_lock`?  Shouldn't you be using `_write_mutex` instead?

**Comment by mvandeberg** [comment]
- Requiring readers to lock `_write_mutex` first prevents writer starvation. `_readers` is an atomic so that when readers release the lock they can do so without actually having to touch a mutex.
- `_write_mutex` must remain locked or else the writer hasn't actually acquired the lock.
- The condition releases the lock and re-acquires it when it is notified. If we used `_write_mutex` then it would be possible for another reader to come in, acquire `_write_mutex` and there will never be progress for the writer to acquire the lock. This design significantly favors the writer because we cannot have the chain state lag.

**Comment by mvandeberg** [comment]
There is still some buggy behavior on dev that needs to be worked out.

**Comment by mvandeberg** [comment]
We are moving away from multi-process parallelism to in process parallelism described in #1265.

This issue is outdated.
