### ISSUE TITLE
Full API

### ISSUE THREAD

**Issue by Hunternnm** [steemit/steem#1199]
Hello! There is an idea to write a small application for a steemit, but I can not find a full description of the api. For example, I can not find how to follow a user or stop following, record upvote, view received transfers, perform transfers. Tell me where all this information can be found?

**Comment by testzcrypto** [comment]
For JS: https://github.com/steemit/steem-js
For Python: https://steemit.com/chainsquad/@chainsquad/python-steem-rebranding-to-piston-libpiston-cli

As example you can use existing Steem open source applications:
https://github.com/eSteemApp/esteem
https://github.com/aaroncox/vessel
https://github.com/aaroncox/chainbb
https://github.com/busyorg/busy

**Comment by surfyogi** [comment]
API Examples:

https://steemit.github.io/devportal/#introductionwelcome


API Explorers:

http://steemroll.io/api-explorer/
https://esteemapp.github.io/steemapi/


Example app:

http://www.snapsteem.com/


Block Explorer:

https://steemd.com/@your_account-name-here

**Comment by Hunternnm** [comment]
I use PHP and send post requests to https://steemd.steemit.com/. I do not use JS - I do not know this language well. Everything that is mentioned here http://steemroll.io/api-explorer/ - works. But I did not find the above methods(follow, upvote, etc).

**Comment by Tadasu85** [comment]
This is a third party tool being developed by a well known steem user check it out, it will likely fit your needs https://github.com/lukestokes/php-steem-tools
