### ISSUE TITLE
https://steemvoter.com/ CORS BYPASS

### ISSUE THREAD

**Issue by zubairkhan930** [steemit/steem#1204]
https://steemvoter.com/ 
Access is allowed from all origins ..
Access-Control-Allow-Origin	"*"
Which is Pretty Dangerous

**Comment by Gandalf-the-Grey** [comment]
While you are right that setting Access Control Allow Origin to "*" is a very bad idea, this repository has nothing to do with steemvoter site. You might want to contact with `@thecryptodrive` on Steem.
