### ISSUE TITLE
Sign Up: Verification email doesn't arrive

### ISSUE THREAD

**Issue by hodlclub** [steemit/steem#1209]
Hi.
Trying to signup on Steemit since already 6 weeks. Unfortunatelly the registration verrifcation email that i should receive after the phone varification does not arrive. Tried severeal times with several email adresses. Also cleared cookies. Siply everything i could think of. Nope, no reaction.
Anyone knows what to do or having the same issues?

**Comment by emanueltns** [comment]
I have the same issue. Could you please help me with that? Thank you!

**Comment by rokaslit6** [comment]
Hi, i am having the exact same issue as hodlclub had before. Is there a way i can get contacted with support/steemit team to get my verification through? Thank you

**Comment by TimCliff** [comment]
@rokaslit6 - please ask for help in the #help channel of Steemit chat.

**Comment by 1tttan1** [comment]
I'm having the same issue. Even no mention of how much I have to wait. Please help!

**Comment by TimCliff** [comment]
please ask for help in the #help channel of Steemit chat
