### ISSUE TITLE
My edit to this comment is displaying as a diff patch

### ISSUE THREAD

**Issue by dnotestein** [steemit/steem#1210]
https://steemit.com/blocktrades/@freebornangel/hello-blocktrades#@blocktrades/re-freebornangel-hello-blocktrades-20170622t031002673z

**Comment by mvandeberg** [comment]
Obviously something went wrong, but there is no record of the original comment in the blockchain. This is not a blockchain issue.

**Comment by arhag** [comment]
> This is not a blockchain issue.

I don't fully agree with that.

The elegant solution would be to track a 32-bit generation number with each `comment_object` (starting at 0 and incremented with each edit) and allow `comment_operation` to require a precondition of it being a certain generation (and if that precondition fails the entire transaction is rejected as invalid). New comments would set this number to 0, while edits would set it to 1 greater than the existing generation of the comment being edited. 

While I imagine this as ideally being part of consensus, it technically could be implemented with a soft-fork. Too bad `comment_operation` does not have an extensions field. But a standard could allow setting that prescribed generation number as a field in the `json_metadata` which the witness soft-fork could respect.

With such a feature properly used by the UIs, there is no concern of improperly applied patches to post/comment content, even if two edits are being made to the same comment at the same time with separate clients.
