### ISSUE TITLE
Navigation issue on Steemit.com

### ISSUE THREAD

**Issue by Autonomy117** [steemit/steem#1212]
Hi I really like this new community it's Awesome and I want to help make it a better place. So here is a small easy to correct issue that you could fix.

Bug "Navigation": When I "the user" click on a post and is navigated to that post is fine as am still on steemit.com, However when I open a post that has a link inside it that navigates away from steemit.com and I click on that link and is navigated away from my current steemit.com page within the same tab is the issue.

Fix: Could you set the navigation for links within posts that navigates away from the steemit.com community to be opened in a new tab ?

I know this is easy to "click on open link in new tab" and I did fixed it on my system however others may be having the same issue and come on its an easy fix.

What's my problem: Oh I warned you guys in my introductory post that if I spot anything I'd let you know by posting about it and If I didn't spot something I simply wouldn't be me, finding solutions to stuff is my thing. Also I wanted to keep my word " I had to"

https://steemit.com/steem/@autonomy117/a-message-to-steemit-com-developers

**Comment by mvandeberg** [comment]
This repo is for blockchain based issues. Your suggestion is for the website, which is the [condenser](https://github.com/steemit/condenser) repo. Please open your issue there.
