### ISSUE TITLE
get_tags_used_by_author always returns an empty array

### ISSUE THREAD

**Issue by jnordberg** [steemit/steem#1214]
`get_tags_used_by_author` in the `database_api` returns `[]` for every user I've tried.

**Comment by mvandeberg** [comment]
This functionality was added in January in a PR that had nothing to do with this functionality. AFAIK, steemit.com does not rely on this API call and it has probably always been broken. We are moving away from the tags plugin to return this information. As far as I am concerned, the API call should never had existed and should be removed.

**Comment by jnordberg** [comment]
Okay. Should I consider the entire `get_tags_by_*` API deprecated as well? If so, what should I use instead?

P.S. It would be _really_ helpful to have a proper API documentation, are there any plans for that? :)

**Comment by mvandeberg** [comment]
Many of the `get_tags_by_*`API calls work. We are migrating many of these non-consensus orderings outside of steemd. We are currently working on a developer portal that will contain documentation and examples on how to use the steemd API and our microservices. It is discussed in the 2017 Steemit Roadmap https://steem.io/2017roadmap.pdf

**Comment by jnordberg** [comment]
Okay, but of a bummer but I guess it makes sense for steemd not to be this giant monolith doing everything. Awesome to hear that you're working on the docs! Are you still on target? Q2 ends in a couple of days :)

**Comment by roadscape** [comment]
@jnordberg essentially, a lot of indexes/APIs will be moved from backend and put into an SQL-driven middleware. Progress: https://github.com/steemit/hivemind

I believe still on target.
