### ISSUE TITLE
Power Down date set to 1969

### ISSUE THREAD

**Issue by PixelNoob** [steemit/steem#1218]
After the fork the power down date was set to year 1969, the user did not change his vesting period.

![bug](https://user-images.githubusercontent.com/16233552/27560040-17809be0-5a99-11e7-9148-af6fa2830259.png)

More info on this post: https://steemit.com/steem/@chitty/possible-power-down-bug

**Comment by PixelNoob** [comment]
It seems this happens after getting 13 power-downs, still the 1969 year is kind of consfusing.

**Comment by sneak** [comment]
That is the datetime for epoch zero - not a bug. He had completed powering down so his next powerdown date value was zero.

**Comment by mvandeberg** [comment]
We sort times as unsigned 32 bit integers. The largest of those is 0xffffffff. The UNIX standard for timestamps is a signed 32 bit integer. 0xffffffff as a signed integer is -1. 1970-01-01 00:00:00 is the linux epoch. 1969-12-31 23:59:59 is -1. 

When we set the withdraw time to 0xffffffff it makes it so we can sort by next vesting withdrawal and all accounts that do not have active withdrawals will be at the back of the queue.

**Comment by 4Ykw** [comment]
amazing how standards are not really helpful sometimes!
