### ISSUE TITLE
Replies with replies can't be deleted

### ISSUE THREAD

**Issue by 4Ykw** [steemit/steem#1219]
Not sure if for it to be possible I have to first delete all the child replies, so the father reply can also be deleted?

Is that the case or it is not implemented due to the nature of the blockchain?

Cheers

**Comment by mvandeberg** [comment]
There are a number of restrictions we have placed on deleting of comments.

- The comment cannot have replies.
- The comment cannot have been paid.
- The comment cannot have positive net rshares (positive net votes).

These restrictions exist to retain referential integrity of discussions and preserve voting rights from stake.

If the entire ancestry of a reply satisfies this requirement at the time of deletion you can delete them.

**Comment by 4Ykw** [comment]
Thanks
