### ISSUE TITLE
Increase warning level on low shared mem

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1223]
Currently, shared mem free space is reported every gigabyte. However, running out of shared memory fails differently depending on the circumstances. Starting at 100 MB free, we should spam a warning message every block so that node operators are made well aware when they ran of of memory.

**Comment by 4Ykw** [comment]
There is a large amount of memory that is going to stack too... I have around 10GB of an unreported stack for steemd.

I foresee this will be a big problem soon with user increase. Can we make a change based on last recent changed memory changes... or something like that. Memory should be used for active stuff!

**Comment by mvandeberg** [comment]
Steemd should not be using that much for stack. I have observed it in the 10s of MB for non memory mapped. The point of using a memory mapped file is the OS can use a paged default scheme and only keep the active set in RAM.

**Comment by 4Ykw** [comment]
Sorry, you right, I am not sure. I just realised that it can be something else. I am using a docker. I will have to confirm the origin of the non-mapped memory. Then I will get back to you with proof.

**Comment by 4Ykw** [comment]
Well.. in Docker is even smaller... the rest is mapped virtual memory.
```
13:   runsv /etc/service/steemd
0000000000400000     24K r-x-- runsv
0000000000605000      4K r---- runsv
0000000000606000      4K rw--- runsv
00007f21b7222000   1788K r-x-- libc-2.23.so
00007f21b73e1000   2048K ----- libc-2.23.so
00007f21b75e1000     16K r---- libc-2.23.so
00007f21b75e5000      8K rw--- libc-2.23.so
00007f21b75e7000     16K rw---   [ anon ]
00007f21b75eb000    152K r-x-- ld-2.23.so
00007f21b7806000     12K rw---   [ anon ]
00007f21b780e000      8K rw---   [ anon ]
00007f21b7810000      4K r---- ld-2.23.so
00007f21b7811000      4K rw--- ld-2.23.so
00007f21b7812000      4K rw---   [ anon ]
00007fffbcb4f000    132K rw---   [ stack ]
00007fffbcb97000      8K r----   [ anon ]
00007fffbcb99000      8K r-x--   [ anon ]
ffffffffff600000      4K r-x--   [ anon ]
 total             4244K
```

Is there a way to page out (deliberately) the least used mapped regions? or this will not be of any advantage?

**Comment by mvandeberg** [comment]
It is up to the OS to determine what needs to be paged in and out. If you have the RAM available, it makes sense to have as much paged in as you can at any one time. If you start running other applications that need the memory, the OS should start paging things out.

**Comment by 4Ykw** [comment]
Yep I know that. I was trying to get a quick understanding of if you need all mapped virtual memory all the time... or if you are usually running on a portion of it... so it could be as fast as 90% when compared with running all in memory. Would be wise to allow a better IO handling of this... there are multiple ways to accelerate this and allow much cheaper resources to run witnesses... if most of what is running in shared memory can be in fact distributed. Can we make this MPI capable? for example? For witnesses it would simplify the hardware requirements a lot.. plus it could bring another group of features since the number of cards and CPU's also can scale...

**Comment by mvandeberg** [comment]
We do not need all of it all of the time but we could need any of it at any time. the correct place for the abstraction is at the filesystem level rather than creating our own MPI caching layer.

**Comment by 4Ykw** [comment]
Right. Ok. Thank for all. I am done with this one.
