### ISSUE TITLE
Adjust account history filter

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1228]
https://github.com/steemit/steem/blob/14597976f02ed9d37f415a45ad6bc5ed6fdeb4ec/contrib/fullnode.config.ini currently shows: `history-whitelist-ops = transfer_operation transfer_to_vesting_operation withdraw_vesting_operation interest_operation transfer_to_savings_operation transfer_from_savings_operation cancel_transfer_from_savings_operation escrow_transfer_operation escrow_approve_operation escrow_dispute_operation escrow_release_operation fill_convert_request_operation fill_order_operation claim_reward_balance_operation`

In addition to these, we'll need author reward and curation rewards tracked by default.

**Comment by mvandeberg** [comment]
I am adding a few more. The list is:

```
transfer_operation
transfer_to_vesting_operation 
withdraw_vesting_operation 
interest_operation 
transfer_to_savings_operation 
transfer_from_savings_operation 
cancel_transfer_from_savings_operation 
escrow_transfer_operation 
escrow_approve_operation 
escrow_dispute_operation 
escrow_release_operation 
fill_convert_request_operation 
fill_order_operation 
claim_reward_balance_operation 
author_reward_operation 
curation_reward_operation 
fill_vesting_withdraw_operation 
fill_transfer_from_savings_operation 
delegate_vesting_shares_operation 
return_vesting_delegation_operation 
comment_benefactor_reward_operation
```
