### ISSUE TITLE
Issues in 0.8.0 (by @arhag)

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#123]
1. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R191
So authors can disable replies whenever they want?

2. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R231
Assertion message should say once every 5 minutes.

3. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R235
So comments cannot disable comment replies?

4. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R272
Why does a top-level post automatically have a cashout time set 24 hours in the future even if it has no votes?

5. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R528
Are you not concerned about this being used as a multiplier for DOS attacks? Maybe there should be a limit to the number of `withdraw_vesting_destination_object` allowed per `from_account`?

6. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R773
I don't get why there is a negative sign here. Also does theoretical's math still work if upvotes are updated?

7. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-04f6af9cdbf180a31ccdbf6335b8f240R703
This new method of updating cashout time is concerning. Someone can delay payout indefinitely.
Now comments are no longer independent in terms of cashout ability. They are tied to the top-level post. But the really bad part of this change is that the delay forever attack is possible again. The reason for limits on the number of vote updates was to prevent such an attack. But because new votes (or updates) for comments to a top-level post now delay the cashout time of the top-level post, this attack is possible again since there is no limit to the number of comments a top-level post can have.

8. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-778ae4a84a14457ed12b22337048d2bfR1696
Don't you mean:
 ```
fc::uint128_t total_rshares( c.children_rshares2 - calculate_vshares( c.net_rshares.value ) );
 ```

9. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-778ae4a84a14457ed12b22337048d2bfR1707
Don't you mean:
 ```
auto claim = ( ( calculate_vshares( cur.net_rshares.value ) * max_rewards.value ) / total_rshares ).to_uint64();
 ```

10. https://github.com/steemit/steem/compare/v0.5.0...v0.8.0?diff=split&name=v0.8.0#diff-778ae4a84a14457ed12b22337048d2bfR1871
This code isn't written very well. In theory `current` should only be top-level posts. 
But if it was ever a comment, maybe because of some bug in some other part of the code, it would cause an infinite loop.

**Comment by mvandeberg** [comment]
1. 3.  Dan and I discussed this, and yes. Disabling replies is a moderation feature for the author of a root comment. All replies inherit reply permissions of the root and implicitly place themselves under the authority of the root.

**Comment by mvandeberg** [comment]
To expand on 10.

As noted, the outer loop should only loop through root comments. All children are supposed to have a cashout time of max int. If that breaks and a comment gets in to the loop, we will still iterate over all comments with the same root comment, at some point the child in question, and comment_cashout_helper sets cashout_time to max int for all comments, children included. This changes the state of the index, and prevents and infinite loop. If children and not properly linked to their root, we have a lot of other problems regarding payouts. Currently, the field is set on creation and never modified.

**Comment by arhag** [comment]
> If that breaks and a comment gets in to the loop, we will still iterate over all comments with the same root comment, at some point the child in question, and comment_cashout_helper sets cashout_time to max int for all comments, children included. 

No it wouldn't. If `current` were ever to be a reply comment for some reason, then `itr` would be set to one of the possible comments (or the root post) in the discussion thread that `current` belongs to. Regardless of what `itr` was set to, `itr->root_comment` will always be the root post of that discussion thread, which is not `current` in this case. Therefore the `itr->root_comment == current->id` condition is not satisfied and the inner while loop is skipped. Then `current` is reset with `current = cidx.begin();` which just repeats the process over again.

This problem could be avoided if you were to replace
```
while( itr != com_by_root.end() && itr->root_comment == current->id )
```
with
```
while( itr != com_by_root.end() && itr->root_comment == current->root_comment )
```

**Comment by abitmore** [comment]
9) Will [this patched code](https://github.com/steemit/steem/blob/477dbc6f5e256251936692c41e721559b5c1a766/libraries/chain/database.cpp#L1678) cause multiplication overflow ?

**Comment by mvandeberg** [comment]
It is possible, though not likely. 128 bit * 64 bit / 128 bit. I can change it to 256 bit multiplication to be safe.

**Comment by abitmore** [comment]
7) with [this code](https://github.com/steemit/steem/blob/3707ba6e76bf382c775b45eddf796e800fdbf542/libraries/chain/steem_evaluator.cpp#L740-L743) and [this code](https://github.com/steemit/steem/blob/3707ba6e76bf382c775b45eddf796e800fdbf542/libraries/chain/steem_evaluator.cpp#L875-L878), `cashout_time` will always be `fc::time_point_sec::maximum()`, and `max_cashout_time` will  likely overflow.
