### ISSUE TITLE
Is "select_tags" and "filter_tags" params supposed to work?

### ISSUE THREAD

**Issue by bonustrack** [steemit/steem#1233]
On Golos blockchain there is a `filter_tags` parameter for `get_discussions_by_*` API methods. I can see the implementation on Steem too along with `select_tags` and `select_author`params here: https://github.com/steemit/steem/blob/76d904fcdfe6d6075b64d019ed0754b6a47c39d0/libraries/app/include/steemit/app/database_api.hpp#L91-L93

I have trouble making these parameters working, its not filtering tag or author. Here is a code from @xymor to test it https://fiddle.jshell.net/h9jej56j/7/
Can you confirm what is the state of this feature?

**Comment by recrypto** [comment]
Any thoughts on this please? I'm also experiencing this issue as well.

**Comment by mvandeberg** [comment]
If it is not working then we do not intend to fix it. We are moving away from these API calls in steemd itself in favor of serving this information via external services.

**Comment by yashwanth2804** [comment]
can you please   list any  those external services @mvandeberg  to use
