### ISSUE TITLE
npm postinstall Error: ENOENT

### ISSUE THREAD

**Issue by shroomist** [steemit/steem#1234]
latest releases, after `0.5.18` are giving me the following error:

`Running post install.js
Error running postinstall script { Error: ENOENT: no such file or directory, unlink '/Users/mystic/work/react/mysteem/node_modules/steem/index.js'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at Object.<anonymous> (/Users/mystic/work/react/mysteem/node_modules/steem/scripts/post-install.js:14:16)`
`npm -v
5.0.4`
`node -v
v8.0.0`
0.5.18 installs well

**Comment by mvandeberg** [comment]
This is the wrong repo for this issue. I believe you are looking for https://github.com/steemit/steem-js
