### ISSUE TITLE
Post HF19, all accounts should have the vote slider

### ISSUE THREAD

**Issue by l0k1-smirenski** [steemit/steem#1236]
From a post back in May by @sykochika ( https://steemit.com/steem-help/@sykochica/what-s-this-slider-bar-and-vote-power-percentage-what-s-the-difference )

Once a user reaches 1 MilliVest (which right now equates to 482.398 Steem Power), they will gain access to the vote slider bar. This lets you determine how much of a vote you want to give a person. Since we have a limited number of full (100%) votes a days without it effecting our voting power, sometimes we want to give a partial votes to more people.

This is why small accounts are now voting less, and only at 100% Since even 480 SP now gives a reward of around 40 cents, this is functionality that should be available to all accounts, or, at least, it should be lowered to at least 100SP, if not blanket enabled.

**Comment by mvandeberg** [comment]
This is a Condenser feature. Closing this because it is not the correct repo for this issue.
