### ISSUE TITLE
Increase p2p net cache

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1242]
https://github.com/steemit/steem/blob/master/libraries/net/include/graphene/net/config.hpp#L69

5 blocks was set in Bitshares to match wallet expiration. Steem-js uses 60 second expiration. Cache time should be increased to 20 blocks to match.

**Comment by theoreticalbts** [comment]
It seems very strange to me that the correct behavior of anything in the p2p code would be dependent on the default value of transaction expiration produced by any wallet.

There might be some dependence on expiration -- for example, pruning transactions from p2p inventories that are provably not includable in the blockchain.  But this kind of logic would either need to use the maximum possible transaction allowed by the blockchain, or would need to inspect the transaction and dynamically determine its expiration.

So I took a while to try to read and understand what the message caching code is actually doing.

It seems this cache is a lookaside cache for messages that have recently been broadcast.  Basically, the p2p code's algorithm is, advertise ID's of items you have to all peers, then interested peers will initiate request / response to fetch items they don't yet possess.

This cache is where items are placed after advertising, so subsequent requests for a recently advertised item will not have to hit the delegate.  However, the delegate acts as a backing store for the cache, so cache misses will be serviced by the delegate.  Therefore, increasing the cache size increases the hit rate.

So the ideal time-based cache expiration policy has nothing to do with transaction expiration time (the comment above this constant notwithstanding, it should really be deleted).  Rather, it has to do with how quickly p2p nodes tend to request an item after it is advertised.

The question we should ask is whether real peers tend to issue fetch requests for advertised items more than 15 seconds after the item was advertised.  When I think about the question in these terms, it seems like 1 minute is safer than 15 seconds.

**Comment by theoreticalbts** [comment]
There's an associated log message:

```
p2p        node.cpp:1149                 fetch_items_loop     ] Unable to fetch item {"item_type":1000,"item_hash":"6eb3667603d2afb06ecda49d3bbc8b3ffb828b4f"} before its likely expiration time, removing it from our list of items to fetch
```

**Comment by abitmore** [comment]
When the network is busy, a long post can still get lost due to expiration, although it will be kept in the mempool longer.
