### ISSUE TITLE
Phone number verification problem

### ISSUE THREAD

**Issue by mymemoir** [steemit/steem#1245]
I signed up to steemit.com. But when I enter my phone number, i get a message saying, "this number is already in use."  

I know for sure my number hasn't been used to register on Steemit before.

Please let me know what to do.

My steemit ID: mymemoir

Thank you!

Rama

**Comment by budwig** [comment]
I had the exact problem yesterday.

**Comment by mymemoir** [comment]
Did you find any solution?

**Comment by mymemoir** [comment]
I think Steemit would do well to have a helpline of some sort.

**Comment by andrarchy** [comment]
Hi Rama, your account had not yet been approved. You should now have received an email with an approval link that will allow you to sign in. My apologies for the wait, due to high demand we have a waitlist of a few days.

- Community Liaison, Steemit Inc.

**Comment by edesonmercy123** [comment]
even my own 
please help me

**Comment by edesonmercy123** [comment]
my ray id 94Ced433ffco3c2
help me please
