### ISSUE TITLE
Rename STEEMIT_RECENT_RSHARES_DECAY_RATE constants to DECAY_TIME

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1247]
The connotation of "decay rate" is that a higher number means it decays faster.  This number is an amount of time, more like a decay time constant, so let's rename it to match what it actually does.

**Comment by Kiwonik** [comment]
Considering #1268 the prefix shall be changed (to STEEM_) too.

**Comment by Kiwonik** [comment]
A change is begin discussed to use SMT_ prefix rather than STEEM_. However no issue has been created so far.

**Comment by Kiwonik** [comment]
Should STEEMIT_MAX_RATION_DECAY_RATE also be renamed? Or even removed (not used anywhere)?

**Comment by mvandeberg** [comment]
No, do not use SMT prefix. Rename STEEMIT_MAX_RATION_DECAY_RATE to STEEM_MAX_RATIO_DECAY_TIME.
