### ISSUE TITLE
Create config constant for vote_power_reserve_rate

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1252]
Currently the DGPO field `vote_power_reserve_rate` is initialized to `40` and reset to `10` in a hardfork.  These numbers `40` and `10` should be replaced with `#define` definitions in `config.hpp`.

**Comment by vogel76** [comment]
Proposed constant names:
#define STEEMIT_INITIAL_VOTE_POWER_RATE (40)
#define STEEMIT_REDUCED_VOTE_POWER_RATE (10)
Please let me know if any opposites...

**Comment by vogel76** [comment]
According to issue:
https://github.com/steemit/steem/issues/1069
constant names shall be prefixed using STEEM_.

**Comment by Kiwonik** [comment]
Rebased the branch to master. Also the base in PR is set to master.
