### ISSUE TITLE
Bandwidth Exeeded

### ISSUE THREAD

**Issue by mike1968mi** [steemit/steem#1256]
My account has exceeded its bandwidth and I can't redeem rewards, powerup or transfer so what am I supposed to do?

**Comment by TimCliff** [comment]
Please ask for help in the Steemit chat #help channel, and someone should respond within 25 hours. Be sure to include your account name so they can review your account.

@sneak to close.

**Comment by Jolly-Pirate** [comment]
There are many users experiencing this issue lately.

**Comment by mike1968mi** [comment]
I have plenty of Steem and Steem Power so I don't understand this. I am trying to power up but I can't even do that. Its like my whole account is locked.

**Comment by mike1968mi** [comment]
I have 109.696 STEEM POWER and I can't do anything with my account.

**Comment by mvandeberg** [comment]
What is your account name?
