### ISSUE TITLE
Refactor for Parallel API Requests

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1265]
We want to refactor our plugins to use appbase and modularize our API stack. This will move us away from the single threaded limitations of FC cooperative multitasking. Using Boost threading and ASIO, we will be able to run each API request in a dedicated thread to parallelize API processing.

This is a huge problem currently as we are regularly requesting data that is not in cache. The single threaded nature of FC cooperative multitasking means that the entire process waits on a cache miss.

This refactor will also make the jsonrpc code separate from the websocket code, potentially allowing us to support different rpc and endpoint specs in the future without less effort.

**Comment by mvandeberg** [comment]
This closes #842

With the proposed changes we will not need to multi-process approach to parallelism.

**Comment by theoreticalbts** [comment]
This may make it easier to be JSON compliant.  Please see if #216 #66 are related

**Comment by mvandeberg** [comment]
Both are fixed in the code I have written so far.

**Comment by andybets** [comment]
Hello @mvandeberg. Has moving comment body to separate object reduced the RAM required for a full RPC node? or is it significantly reduced with the SKIP_BY_TX_ID option?

I'm considering running one to support my services, but looking at costs.

Thanks for any further information.

**Comment by mvandeberg** [comment]
No, this is simply reducing execution time of syncing a node and pushing blocks when live. It does not have an impact of the size of the state file.

SKIP_BY_TX_ID does save some space but primarily reduces reindex time of a node significantly.

**Comment by andybets** [comment]
Ok. Thanks for letting me know.
