### ISSUE TITLE
STEEM Dollars vanish when converting to STEEM

### ISSUE THREAD

**Issue by jamesashton** [steemit/steem#1271]
I transferred a small amount of STEEM Dollars, selecting the 'Convert to STEEM' drop down item on the menu that appears next to the STEEM Dollars balance. 
The STEEM dollar balance is now $0.000  but there is no evidence of the original funds anywhere. 

Ideally it would show some sort of 'Pending' status, or it would write an entry to the History. Or preferably both. 

It did say it would take 1-3 days for the transaction to complete. Which is fine, but I can have forgotten about this in 3 days, so there should be some indication that the transaction is in progress.

**Comment by mvandeberg** [comment]
Everything is working properly on the blockchain. This, however, is a display issue and belongs in the [Condesner](https://github.com/steemit/condenser) repo.
