### ISSUE TITLE
Update account with multiple key_auths fail with "Missing Active Authority"

### ISSUE THREAD

**Issue by bonustrack** [steemit/steem#1272]
I tried to add a second key inside `key_auths` array of an account. For some reason it failing with `Error: 3010000 tx_missing_active_auth: missing required active authority Missing Active Authority hellosteem`.

Adding an username on `account_auths` is working, updating a key inside `key_auths` array is also working, all using same active WIF to create a signature. But when i try to add a second key, it's failing.

Here is the tx i'm sending to the blockchain:
```
{
  "ref_block_num": 32426,
  "ref_block_prefix": 2495366551,
  "expiration": "2017-07-18T15:59:06",
  "operations": [["account_update", {
    "account": "hellosteem",
    "posting": {
      "weight_threshold": 1,
      "account_auths": [["busy.app", 1], ["fabien", 1], ["steem", 1], ["steemit", 1]],
      "key_auths": [["STM88CPfhCmeEzCnvC1Cjc3DNd1DTjkMcmihih8SSxmm4LBqRq5Y9", 1], ["STM6PiQjjEoF6N2hDfzSMLUw4qLebjQuyk9nnLBppNaZvX5qUkh8A", 1]]
      },
      "memo_key": "STM5bGSQZNZqUuxxuRpJs2P662ouCLMdnwtP36MvUX453Bn5ePvr5",
      "json_metadata": "{}"
    }]],
  "extensions": [],
  "signatures":
 ["1f7a97ee781a15557ebdf97fa37712893dd0e4cfec72cd44cf9daea2da3913061a03e9e1a11c27d83018eeb0d2f7d6958d84c8006b890323d8fe15bff14bb6700e"]
  }]]
}
```

I tried with 3 differents accounts using Steem.js but always got the same error. Any idea what is wrong?

**Comment by abitmore** [comment]
Perhaps a serialization issue. Accounts and keys should be sorted correctly. Currently keys are converted to addresses before sorting.

**Comment by bonustrack** [comment]
Thank you Abit, you the boss 🥇 I've reversed the sorting of public_key in Steem.js serializer and it worked out!
