### ISSUE TITLE
Steem Testnet

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1278]
Requirements for Steem Testnet

- Start with a large initial supply of 1,000,000,000.000 STEEM (verify this will not cause 64 bit overflow)
- On block 1, each hardfork with a date in the past should be automatically applied.
- If witnesses are not reporting a price feed, assume they are reporting 1 SBD/STEEM.\

All payouts will be on a shorter timescale and should already be configured that way for unit tests. Check other time based constants and shorted them if needed. This is to allow thorough and repeated testing of the various systems in real time. The chain id should not be set to `chain_id_type()`.

How the test net will work:

The init miner key is publicly known. Whoever starts the test net should transfer some of those funds to a privately controlled account (preferably linked to a faucet). Others can create accounts from the init miner account with whatever funds are left on the account.

STEEM on the testnet has the symbol TESTS.
SBD on the testnet has the symbol TBD.
VESTS are still VESTS.

**Comment by theoreticalbts** [comment]
You should be able to handle the initial supply by setting `STEEMIT_INIT_SUPPLY` thanks to [this community-generated PR](https://github.com/steemit/steem/pull/1253).

I don't think it is good to have special testnet semantics for the price feed.  First of all, some unit tests (and potentially some tests performed on an actual testnet) should be testing what happens if there is no price feed -- adding special semantics will break those tests.

If you want price feeds on your testnet, you should publish them yourself via the normal mechanism.

**Comment by theoreticalbts** [comment]
As well as code in steemd itself, there should be Python scripts for spinning up a testnet and handling things like automatically creating accounts for faucets / witnesses, causing the faucet (or some large VB you control) to vote for witness(es) you want, publishing feeds (if desired), generating dummy accounts/content/transactions/upvotes/trading or importing (perhaps some subset of) that from mainnet, etc.

Those scripts should probably live in a separate repo.  `debug_generate_blocks` API call may be useful.

**Comment by mvandeberg** [comment]
The motivation behind having some default price feed mechanism is that there are several placers in the code that use the existence of the price feed as a milestone in the startup of the blockchain. Having an inconsistent price feed could lead to problems. Really though, those critical sections should be fixed so that losing the price feed does not harm the blockchain.

**Comment by sneak** [comment]
> Those scripts should probably live in a separate repo.

I would like all testnet-related code to remain in the `steem` repo.

**Comment by sneak** [comment]
I think there should be two testnet code paths - one for running a local set of nodes (or single node), but also support for a build that supports a *public*, longer-lived testnet.  There will be different HF dates for the testnet and the mainnet, so that our HFs can be rolled out on the public testnet in advance of mainnet.

**Comment by mvandeberg** [comment]
The hardcoded hardfork dates are the dates witnesses will vote for by default. The protocol itself is dynamic and designed to support a variety of dates for the same hardfork. It is trivial to trigger a hardfork on the testnet early.

**Comment by vogel76** [comment]
Could we see any example of python scripts operating on blockchain ? Probably you have some already.

**Comment by mvandeberg** [comment]
https://github.com/steemit/steem-python is our official tool. @NateBrune Has some experience with it. If you have any specific questions, he can help.

I would start with the c++ side.

Start the chain with a lot of STEEM in init_miner and apply all hardforks on genesis. If built with `BUILD_STEEM_TESTNET`, `init_miner`'s private key is defined in `config.hpp`. 

At that point, we can do any additional setup through any scripting environment with support for Steem. Likely Steem Python is easiest.

**Comment by vogel76** [comment]
Could you elaborate more how it should be started ? Does we have to add some configuration option like 'BUILD_SMT_TESTNET' similary to 'BUILD_STEEM_TESTNET'. How we should start at C++ side ? I suppose the man difference between requested testnet and the blockchain built during chain_tests execution (also performing some smt_operation tests) will be interactions between SMT operations automatically triggerred, what is (probably) impossible by poor unit tests.

**Comment by mvandeberg** [comment]
Use BUILD_STEEM_TESTNET, this is not a testnet specifically for SMTs. Although it will be used for that.

We use BUILD_STEEM_TESTNET for unit tests so that we can easily change some `#define`s so the tests execute faster. The big thing it does is change the init miner key and the chain id. This will prevent the testnet from operating with the mainnet.

Look into `init_genesis` to see all of the things that are set at genesis. We probably want to have a json genesis file for setting chain_id, init_miner key, geneis_time, etc.

**Comment by mariusztrela** [comment]
A few questions:

1) "On block 1, each hardfork with a date in the past should be automatically applied."
'init_hardforks' + 'process_hardforks', is exactly what do you want?

2) Do we have to add second preprocessor directive, i.e: BUILD_STEEM_TESTNET_TOTAL ?

for example:

#ifdef BUILD_STEEM_TESTNET

	#ifdef BUILD_STEEM_TESTNET_TOTAL
		//here set consts for new testnet, for example: shorter timescales
	#else
		//here set consts for old testnet
	#endif


#endif

**Comment by theoreticalbts** [comment]
1. Looks like `init_hardforks` is called in `database::open()`, and `process_hardforks()` is part of per-block processing.  I think you want to do what `database_fixture` does, which is `set_hardfork( STEEMIT_BLOCKCHAIN_VERSION.minor() )` -- @mvandeberg any thoughts?

2. I don't think so.  My idea is, let's try to have the same set of constants for the unit tests and for the testnet.  If we come up with specific obstacles which prevent this from working, *then* we can introduce a new set of constants (or maybe some other solution to the problem, e.g. moving constants to the DB and initializing them in a genesis file).

- Do you have specific constant(s) in `config.hpp` in mind?  If not, then the answer to (2) is no.
- Can the constant(s) be changed in the existing testnet definition, and the unit tests still pass and without taking too long to run?  If so, then the answer to (2) is no, just change them.
- Can the unit tests easily be adapted to the new constant(s) without taking too long to run?  If not, then the answer to (2) is yes, we need to have different set of constants for the testnet and the unit tests.

**Comment by mvandeberg** [comment]
Theoretical pretty much said what I was going to say.

The point of smaller constants in terms of the test net is to get through more payout cycles, vesting withdrawals, etc. on the test net. More testing of critical code paths with less time.

**Comment by mvandeberg** [comment]
I have not tested this method on a local testnet, but something like this is what I was thinking.

**Comment by mvandeberg** [comment]
@mariusztrela The next step is to enable a remote reset of the test net.

All of the following needs to be done in `#ifdef IS_TEST_NET`.
Create a custom operation `testnet_reset`.
It should require the posting key of `initminer`.
Look at the follow plugin on how to make a custom op and evaluator. It is similar to normal operations but registration is a little different.

The tricky part is that the op should reset the blockchain back to genesis without steemd quitting. The trick is that this will be caught within the block processing stack. It will probably need to set a flag that can get caught outside this stack.

In order to reset the blockchain you will have to do the following:

- Delete all undo history
- Delete all database objects
- Reset chainbase commit to 0
- Call `init_genesis`

The remaining challenge is observing how the p2p code reacts to such a scenario. It is not designed for this behavior. Get this implemented and then we'll see how broken the p2p code is and fix it then.

**Comment by mariusztrela** [comment]
Do I need new plugin for `testnet_reset' operation? I suppose so, because as I saw in `follow` plugin, declaration of evaluator requires any plugin ( STEEM_DEFINE_PLUGIN_EVALUATOR )

And question: How is difference between regular evaluator and custom evaluator? I see such custom evaluators in 2 plugins: `follow` and `witness`

**Comment by mvandeberg** [comment]
We have the macro labelled as `STEEM_DEFINE_PLUGIN_EVALUATOR`. It should probably be named `STEEM_DEFINE_CUSTOM_EVALUATOR`, but don't worry about changing it. Just use those as example of how to make a custom op. This is an operation that does not need to be defined in the consensus logic, but can still be handled using our evaluator logic.

I would create `testnet.hpp` and `testnet.cpp` in `steem/chain` that contains this custom logic.

**Comment by theoreticalbts** [comment]
A custom operation is an operation that puts a JSON or binary blob on the blockchain.  As far as the blockchain is concerned, it is a no-op.

However, plugins or external services can build their own state from custom operations.

A good example is the ability to follow another user.  This functionality is purely a way of organizing the UI, it has no effect on anything "important."  In other words, following does not affect [1] consensus level data like balances, reward payments or emissions.

Historically, state for custom operations has mostly been tracked by plugins.  But eventually we want to move away from plugins and interpret custom operations using external services written in Python or JS.

[1] Following does *indirectly* effect balances, for example, a user is more likely to see posts from people they follow.  And therefore more likely to upvote such posts.  Which does increase the rewards of posters who manage to get followers.  But this indirect effect is just an observation about how users choose to vote.  So from the perspective of the consensus code, the follow doesn't mean anything, only the upvote does.

**Comment by youkaicountry** [comment]
Move discussion to #1677
