### ISSUE TITLE
get_trenfings_tags bug

### ISSUE THREAD

**Issue by jakubzieba** [steemit/steem#1279]
Hi, I trying to fetch  all trending tags using {"id":54,"method":"get_trending_tags","params":[startTag,limit]}. But for example when i try execute {"id":54,"method":"get_trending_tags","params":["i506",200]} i got error

RECEIVED: {"id":54,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n!ec: websocket send failed: A payload contained invalid data\n {\"msg\":\"A payload contained invalid data\"}\n th_a websocket.cpp:164 send_message\n\n {\"call.method\":\"get_trending_tags\",\"call.params\":[\"i506\",200]}\n th_a websocket_api.cpp:124 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"websocket.cpp","line":164,"method":"send_message","hostname":"","thread_name":"th_a","timestamp":"2017-07-28T11:42:06"},"format":"!ec: websocket send failed: ${msg}","data":{"msg":"A payload contained invalid data"}},{"context":{"level":"warn","file":"websocket_api.cpp","line":124,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-07-28T11:42:06"},"format":"","data":{"call.method":"get_trending_tags","call.params":["i506",200]}}]}}}

but if i change limit to 128 ({"id":54,"method":"get_trending_tags","params":["i506",128]}) everything is ok. It looks like steemd tried to return the number of results set by the limit but results are not there and return error.

**Comment by jakubzieba** [comment]
Any suggestions ?

**Comment by youkaicountry** [comment]
Won't fix.
