### ISSUE TITLE
Question about money transaction mistake

### ISSUE THREAD

**Issue by borishaifa** [steemit/steem#1284]
Hi, guys! I know  - all specialists in Steemit are here. So, my question is described here.  https://steemit.com/steemet/@borishaifa/what-to-do-guys-i-have-made-a-mistake-with-steem Could you advise anything in such a situation?

**Comment by mvandeberg** [comment]
Unfortunately, once the funds are sent, we have no power to undo the transfer.

**Comment by borishaifa** [comment]
OK, I understand the policy of Steemit in that, but the man is ready (by his words to send the money back) but he can not get into account. Is there in Steemit anyone who can solve the issue? It is not FBI or Mossad - it is just a social network, guys.  We should have any solution to such situation - it is natural for real specialists. Thank you for understanding.

**Comment by sneak** [comment]
It's not policy; we are technically *unable* to do so.  The steem blockchain is not a centralized service.

It's not our decision; it's out of our hands.

**Comment by borishaifa** [comment]
Ok, I see, no problems. Anyway, I will leave this place https://steemit.com/steemit/@borishaifa/thank-you-steemit-for-fuck-israel-transaction

**Comment by TimCliff** [comment]
I replied to your post, but just so the info is here as well - you are not understanding how this works. Nobody other than the person who you sent the funds to had the ability to return them to you. It is not a lack of support or customer service, it is an inability to do it based on the blockchain rules.
