### ISSUE TITLE
"Transaction broadcast error." when you put more than one spaces between 2 TAGS !!!

### ISSUE THREAD

**Issue by liondani** [steemit/steem#129]
![git1](https://cloud.githubusercontent.com/assets/6908400/16450772/9f4d5bbc-3e07-11e6-8e00-feda06ecc53c.png)

**Comment by abitmore** [comment]
This should be a bug of steemit.com. Submit here: https://github.com/steemit/steemit.com/issues.

**Comment by BixBixBix** [comment]
I am pretty sure i ran into this problem but i did not have more than one space between tags.

[](https://steemit.com/steemit/@bix/how-i-posted-the-same-post-3-times-in-a-row-transaction-broadcast-error-typeerror-network-request-failed)

You can actually see it in my screen shots - only one space.
