### ISSUE TITLE
Problems installing steemit.com on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by abidoon** [steemit/steem#1291]
Problems installing steemit.com

The error came while running the command npm install. 
I am following instructions given here https://hub.docker.com/r/steemit/steemit.com/

Log file output follows:
`
134982 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

134983 verbose stack Error: steem@0.6.1 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`

134983 verbose stack Exit status 1

134983 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)

134983 verbose stack     at emitTwo (events.js:106:13)

134983 verbose stack     at EventEmitter.emit (events.js:191:7)

134983 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)

134983 verbose stack     at emitTwo (events.js:106:13)

134983 verbose stack     at ChildProcess.emit (events.js:191:7)

134983 verbose stack     at maybeClose (internal/child_process.js:891:16)

134983 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

134984 verbose pkgid steem@0.6.1

134985 verbose cwd /opt/steemit.com

134986 error Linux 4.4.0-1022-aws

134987 error argv "/root/.nvm/versions/node/v6.11.2/bin/node" "/root/.nvm/versions/node/v6.11.2/bin/npm" "install"

134988 error node v6.11.2

134989 error npm  v3.10.10

134990 error code ELIFECYCLE

134991 error steem@0.6.1 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`

134991 error Exit status 1

134992 error Failed at the steem@0.6.1 postinstall script 'postinstall-build lib && cross-env scripts/post-install.js'.

134992 error Make sure you have the latest version of node.js and npm installed.

134992 error If you do, this is most likely a problem with the steem package,

134992 error not with npm itself.

134992 error Tell the author that this fails on your system:

134992 error     postinstall-build lib && cross-env scripts/post-install.js

134992 error You can get information on how to open an issue for this project with:
134992 error     npm bugs steem
134992 error Or if that isn't available, you can get their info via:
134992 error     npm owner ls steem
134992 error There is likely additional logging output above.

134993 verbose exit [ 1, true ]
`

**Comment by mvandeberg** [comment]
This should go in [github.com/steemit/condenser](github.com/steemit/condenser).

**Comment by abidoon** [comment]
Apologies.
