### ISSUE TITLE
p2p user agent should not be configurable

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1295]
There is a config option to set the p2p user agent. This should not be runtime configurable.

**Comment by vogel76** [comment]
Which value shall be used as default one (for user_agent member) when `p2p-user-agent` option will be removed ?

**Comment by mvandeberg** [comment]
`Steem Reference Implementation`. Graphene is an outdated name and our implementation of the p2p code now differs slightly from Graphene.
