### ISSUE TITLE
Verify wallet config file semantics are preserved

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1298]
Check what the wallet config file semantics are in `latest` and confirm they are the same in `master`

**Comment by theoreticalbts** [comment]
What exactly does this mean?

**Comment by mvandeberg** [comment]
The cli wallet has a config file. I did not explicitly change anything about that config file. Regardless, we should check the config options for the wallet and verify it works the same in appbase as it does in production.

**Comment by mvandeberg** [comment]
This shows the only change to cli wallet config options in appbase. https://github.com/steemit/steem/commit/2a4c5537eef469f321e9729054d030fdde75b06f#diff-bed27691e10f616dbe58639522d28af8

Considering we removed the login API, I believe these changes are acceptable. Everything else should work as expected.
