### ISSUE TITLE
Sanitize witness hardfork versions

### ISSUE THREAD

**Issue by arhag** [steemit/steem#130]
A witness can submit any value they wish for the hardfork version and time. Particularly, they can submit a hardfork version whose first 16-bits (release number) is not zero, which gets stored in the witness object anyway. This then causes problems with the cli_wallet when it tries to `get_witness` of a witness that has such an improper hardfork version.

I suggest that steemd first sanitize the witness-submitted hardfork version beforing saving it to the database such that its release number is always 0. That process would occur here: https://github.com/steemit/steem/blob/v0.8.2/libraries/chain/database.cpp#L2534

We could also have stricter checks on the user submitted hardfork version and time, and if those checks fail, the witness object wouldn't be modified at all.

**Comment by abitmore** [comment]
Currently block 2727879 probably contains invalid hard fork version & time voting data, which causes a "block doesn't exist" issue while replaying.

By the way, `get_block` API doesn't return the hard fork voting data?

**Comment by arhag** [comment]
@abitmore: 2727879 doesn't contain the invalid hard fork version. Block number 2726331 does. I believe that is the first block steempty created after downgrading to v0.5.0. I can't verify for sure because the CLI wallet currently throws the `( hv.v_num & 0x0000FFFF ) == 0` assertion error.

**Comment by abitmore** [comment]
Yes I was wrong. This is 2726331 which has hardfork voting extensions inside:
```
{"id":1,"result":{"previous":"002999ba30e9d7af144a05a5341e66458166e004","timestamp":"2016-06-28T07:37:39","witness":"steempty","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[[1,"0.5.0"],[2,{"hf_version":"0.0.489","hf_time":"1971-04-18T04:59:36"}]],"witness_signature":"1f1b480eb0680a9ecc1690ea2db5467be5baaa3eea941d0c788db20f43d511aeb974629acda350eafbfa22037451d0f39fbc28723658591caa1d5eb4b55fa1a08d","transactions":[]}}
```

This is 2727879:
```
{"id":1,"result":{"previous":"00299fc61dbb3998ef8e568b109fa1a07c482f5b","timestamp":"2016-06-28T08:55:09","witness":"steempty","transaction_merkle_root":"55d40000265ba3ff24f6ff0b09366502ed8be587","extensions":[],"witness_signature":"2053400dfa4334b062cbfbbb3fcdf1a1bb856381292e4ceab0dda9f307a852f006504e55e0e40688916812d2ca26ceacac1d097a16e5e242b237cdf21859936738","transactions":[{"ref_block_num":40902,"ref_block_prefix":2553920285,"expiration":"2016-06-28T08:55:15","operations":[["comment",{"parent_author":"tuck-fheman","parent_permlink":"steemit-three-times-a-day-for-a-healthy-smile","author":"omarb","permlink":"re-tuck-fheman-steemit-three-times-a-day-for-a-healthy-smile-20160628t085452510z","title":"","body":"Haha, awesome idea.","json_metadata":"{\"tags\":[\"steem-marketing\"]}"}]],"extensions":[],"signatures":["1f65706e53764ff7ffd0e7d7192ff54671d4e3ad18cdb3735e0872bd9c6fba727719129d069bd9a7f0d49fd6f115899e358df146f0831a8cf30d18684a79fd1336"]}]}}
```
I can't reproduce the "block doesn't exist" issue from my data dir. From slack conversation there are at least 5 witnesses encountered that issue. If we can find the data, we can try to reproduce and analyse.
