### ISSUE TITLE
Appbase remove static asserts

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1307]
Static asserts in appbase should throw boost exceptions on failure.

**Comment by vogel76** [comment]
I don't see any static_assert's under appbase directory. There are some in libraries/chain, libraries/net but probably unrelated to this task. Could you point me where they shall be removed from ?

**Comment by mvandeberg** [comment]
I think the asserts I was thinking of were plain `assert`. static_asserts are fine. We just don't want steemd to quit unexpectedly from a regular `assert`. Everywhere else we use FC_ASSERT, but we don't want to make FC a dependency of Appbase.

**Comment by mvandeberg** [comment]
Change `assert`s to throw boost exceptions so we can shut down steemd safely.
