### ISSUE TITLE
Plugin impl namespace

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1314]
Check for consistency of plugin impls existing in detail namespace.

**Comment by vogel76** [comment]
Could you explain what do you mean by consistency check ? Do you mean a check for 'impl' (bridge pattern) in each plugin ?

**Comment by mvandeberg** [comment]
Manually inspect each plugin and refactor the 'impl' class of each plugin into detail sub-namespace. The witness plugin is correct if you want an example.
