### ISSUE TITLE
API object naming

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1318]
Check that API object naming is consistent.

`api_*_object` for a DB object that would be returned in an API.

**Comment by mvandeberg** [comment]
This is different than the return types defined to for API methods.

This is a soft semantic to quickly identify an object that is intended to live within the memory mapped segment (and uses the mmap allocator) vs one that is safe for default allocation. api objects are safe for default allocation.

**Comment by mkochanowicz** [comment]
I need more clarification:
1. Does it concern database_api or also all others apis?
2. Check for every api_*_object is really safe for default alloc? (it is already done in all apis)
3. Rename all other objects returned by apis to be in form api_*_object (typedef'ed or defined)?

**Comment by mvandeberg** [comment]
Any object that exists in the database that is returned as part of an API should follow this naming scheme. Currently, all of the objects (or typedefs) have proper memory allocation.

They used to be called `*_api_obj`. I liked `api_*_object` better, so I renamed them in this refactor but want to be sure I got them all.

**Comment by mvandeberg** [comment]
> If the private message plugin was the only place where this was a problem, then I am inclined to simply close the issue without a merge. The private message plugin has never been used in production and is really only sticking around because I have been too lazy to delete it.
