### ISSUE TITLE
get_block API

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1322]
Previously, we had a config option to disable `get_block` in the database_api. Instead of having an option specifically for this call, it should have its own API and can be enabled like any other plugin.

**Comment by abitmore** [comment]
Will this break API compatibility? Other apps may rely on this API.

**Comment by mvandeberg** [comment]
It will be exposed in the Condenser API as it currently exists, but live in a new API for the future.

**Comment by vogel76** [comment]
Do you propose to create new plugin and API ie called 'blockchain_ops' containing given 'get_block' function ?
Does 'condenser_api::get_block' and database_api::get_block shall be removed then ?

**Comment by mariusztrela** [comment]
I made new plugin locally ( I haven't committed yet ). Everything works...
I mean, when I call:
{"jsonrpc": "2.0", "method": "call", "params": ["database_ext_api","get_block", {"block_num":600} ], "id": 1}
and I get proper data...

But, I have question:

What should be name of new plugin/api? I propose: 
 - plugin:	database_ext_api_plugin
 - api:		database_ext_api

**Comment by mvandeberg** [comment]
`block_api` and `block_api_plugin`.
