### ISSUE TITLE
Remove "readonly" node.

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1328]
Readonly nodes are a thing of the past because they did not work. The parallel API refactor replaces the functionality read only nodes were designed for. Remove the config option for readonly nodes and all readonly semantics from the database and chainbase.

**Comment by mkochanowicz** [comment]
readonly node semantics removed I believe.
Are there any other changes required? Like scripts, config files?

[https://github.com/steemit/steem/tree/1328-remove-readonly-node](url)

**Comment by mvandeberg** [comment]
@jredbeard Can you update the paas scripts to remove read only node as an option?

**Comment by mkochanowicz** [comment]
#1429
