### ISSUE TITLE
Implement edit scripts for debug_node

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#133]
An "edit script" is a JSON list of edits made to the database with the debug_node plugin.  Creating such a script allows the debug state to be portable, and enables an entire p2p testnet of debug_node to exist (create the script on one node, then copy it and configure it to all other nodes).

**Comment by theoreticalbts** [comment]
This still needs merged.

**Comment by mvandeberg** [comment]
I imagine there is a good amount of code rot on this branch. Can this be closed or should it be backlogged?

**Comment by mvandeberg** [comment]
Closing. If we need it later we will create a new issue.
