### ISSUE TITLE
JSON rpc error ID default initialization

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1334]
The jsonrpc error object id needs default initialization. It should be set to 0 so that if an error occurs in such a way that the id is not set we can quickly identify it as breaking the jsonrpc spec (0 is not a valid error id value).

**Comment by vogel76** [comment]
Not sure what here should be done - would you like to eliminate fc::optional from json_rpc_response::error and by default initialize 'error' structure to data having 'code' member set to 0 ?

**Comment by mvandeberg** [comment]
Yes, the `code` field.
