### ISSUE TITLE
jsonrpc catch( ... )

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1336]
Just in case there is an exception that we did not account for (an unhandled boost exception, for example) this would catch it and return a valid jsonrpc result.

**Comment by vogel76** [comment]
I suppose you have in mind try/catch blocks inside `json_rpc_plugin_impl::rpc`. If so, what response shall be produced for these unknown exceptions ? Does JSON_RPC_SERVER_ERROR status is what we need ?
I also propose to reduce number of try catch blocks and extract common ones to the top of the function.

**Comment by mvandeberg** [comment]
Yes, catch in `json_rpc_plugin_impl::rpc`.

If there are multiple catches of the same exception that return the same JSON_RPC error code, move those to the top of the function.

The function that exists conforms to spec, from my testing.

The catch( ... ) should return a JSON_RPC_SERVER_ERROR.
