### ISSUE TITLE
Internal error: static_variant tag is invalid.

### ISSUE THREAD

**Issue by tchap** [steemit/steem#134]
Sent a `SIGINT` to `steemd` when it was processing some RPC endpoint `get_block` requests, got

```
1734246ms th_a       database.cpp:608              _push_block          ] Failed to push new block:
10 assert_exception: Assert Exception
Internal error: static_variant tag is invalid.
    {}
    th_a  static_variant.hpp:134 apply
```

The process than hung without crashing, establishing a new WebSocket connection and sending additional commands lead to no reply.

`steemd` version `0.8.4`

**Comment by abitmore** [comment]
Possible related to #130 and https://github.com/steemit/steem/commit/14797888f842591542e0e9f1c11dc8b04c59f83e

**Comment by theoreticalbts** [comment]
Closing due to age, SIGINT handling has since been improved.
