### ISSUE TITLE
Chain API

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1340]
We should create a chain api that can push blocks and transactions.

**Comment by mvandeberg** [comment]
Two api calls should be `push_block` and `push_transaction`. Exceptions thrown during those calls should be caught by the API and returned as a valid response rather than as a jsonrpc error.

Return type is probably a struct with a `bool success`, and `optional< string > error`;

**Comment by vogel76** [comment]
This new API shall be part of  new module under plugin/apis/chain_api or part of chain plugin ?

**Comment by mvandeberg** [comment]
plugins/apis/chain_api

**Comment by mkochanowicz** [comment]
Need info how new api/api_plugin could/should be tested in dev env.

**Comment by mkochanowicz** [comment]
#1441
