### ISSUE TITLE
Define replay/resync semantics

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1343]
We need to define the replay/resync semantics between the webserver and chain plugin and enforce them in the plugins. Note: neither plugin has a strict dependency on the other which allows appbase to load them in any order.

Potentially, the chain plugin could have a signal that starts the websocket plugin.

**Comment by mvandeberg** [comment]
There are a number of weird edge cases. None of them should cause major problems, but may return confusing errors if an API is called before the chain plugin can start. I think making the chain plugin an optional dependency of the webserver plugin makes the most sense. If the chain plugin is loaded, then then the webserver will wait for the chain plugin to be live.

**Comment by theoreticalbts** [comment]
I think we decided at some point that in order to avoid locking on replay, the RPC server should be unavailable during replay.  So there's no socket based progress indicator for a replaying node, you'd have to listen to the logs for that.

**Comment by mvandeberg** [comment]
This is how steemd currently works. Keeping existing behavior is good enough for now.
