### ISSUE TITLE
Webserver thread pool size should be configurable

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1347]
The thread pool size should be runtime configurable via the config file.

**Comment by mkochanowicz** [comment]
Need to confirm propositions:
1. webserver-thread-pool-size name for option. Public description: "Number of threads used to handle queries" (don't know how describe it better for external user).
2. Threads are created in ctor with WEBSERVER_THREAD_POOL_SIZE value - it should be deffered until we know thread pool size option value.
3. Default value for the option (if not specified) is WEBSERVER_THREAD_POOL_SIZE.

Questions:
1. Is there need to update other files containing webserver-<option> with this new option?
2. What about min/max values for the option?

**Comment by mvandeberg** [comment]
You can eliminate the WEBSERVER_THREAD_POOL_SIZE macro when setting the default value in the config file. That also answers question 1. If a default value is set, it will populate new config files properly, or be used if the option is absent.

Min value: >0
Max value: 2^32 -1? If the user wants to max out threads, then why not. Won't help them at all. 
Parse the value as a uint32_t and ensure it isn't 0.

**Comment by mkochanowicz** [comment]
#1377
