### ISSUE TITLE
Database fixture init db to nullptr

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1349]
The database fixture under normal conditions should successfully set the database pointer. Set the default value to nullptr, and perform a nullptr check after assignment, failing the test on failure.

**Comment by mariusztrela** [comment]
I have a few questions:

=========================================
a) "Set the default value to nullptr"
It seems clear:

//BEFORE
struct database_fixture {
   chain::database* db;
   
//AFTER
struct database_fixture {
   chain::database* db = nullptr;
=========================================
b) "perform a nullptr check after assignment, failing the test on failure"

We have 4 assignments:

 - 2 assignments in constructors: clean_database_fixture, live_database_fixture
 - 2 assignments in tests:

1)
BOOST_AUTO_TEST_CASE( mh_test )
...
db = &appbase::app().get_plugin< steemit::plugins::chain::chain_plugin >().db();
...

2)

BOOST_FIXTURE_TEST_CASE( hardfork_test, database_fixture )
...
db = &appbase::app().get_plugin< steemit::plugins::chain::chain_plugin >().db();
...



I suppose, that after these assignments we should add:
BOOST_REQUIRE( db );
=========================================
But we have:
&appbase::app().get_plugin< steemit::plugins::chain::chain_plugin >().db()

Calling 'db()' returns reference, so we never will have 'nullptr' in our variable 'db'.
Could you more explain this case?

**Comment by mvandeberg** [comment]
You are correct, we should never have `nullptr` assigned after calling `db()`. This check is to be as cautious as possible and to fail fast if something were to be broken.

**Comment by vogel76** [comment]
I'd like ask what in case when database::open will throw an exception - does db member shall stay filled ? maybe it shall be set back to nullptr ?
Also maybe it would be better to unify somehow setting db pointer and its opening process in single method present in database_fixture ?

**Comment by mvandeberg** [comment]
database::open would only throw exceptions and fail if there was a problem opening and mapping the database.

This issue is not about testing the semantics of database::open and more about best practices when using pointers. We do not think it should ever be set to an invalid pointer, but it is better to be safe and fail in a predictable way.
