### ISSUE TITLE
Operation filtering via get_account_history

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem#1359]
Originally I mentioned [this idea in a somewhat unrelated issue here](https://github.com/steemit/steem/issues/146#issuecomment-244833519).

Currently to filter operations from an accounts history, one is required to make recursive requests to the API and perform the filtering within their own application. The steem-python library does this currently, but steem-js does not. 

As an example, a user has 10,000 operations within their account history, 10 of them being `transfer` operations every 1000 operations. In order to retrieve all 10 transfers, you currently have to make 5 recursive calls to `get_account_history`. This returns all 10,000 operations to the client, consuming bandwidth, only to them get discarded as the filtering then occurs. 

I'd like to see this filtering added on the steemd API to avoid unnecessary data transfer and avoid having to filter within the client itself, either as a string or preferably as an array allowing a list of operation types.

The implementation could be something like this:

`get_account_history jesta -1 10 ['transfer', 'vesting_withdraw', 'vesting_deposit']`

Originally when I made this request, it was for projects like SteemStats, but recently this issue has resurfaced for me while working on [Vessel](https://github.com/aaroncox/vessel). 

I can't provide a wallet transaction history for accounts (like most wallets do) because generally the account history itself is clogged up with various other operations. One solution would be to add a middleware layer, save those specific transactions in a database and reserve them... but then anyone using the service would be reliant upon my servers and the maintenance of them. The goal with Vessel is to make it's only server dependency a steemd node so that users could run their own.

**Comment by mvandeberg** [comment]
The challenge with a call like this is that given a particular filtering, an op might be extremely rare. Because we want deterministic run times for all API calls, the limit would need to be the number of ops looked at, not the number returned. So it is possible a call might return no ops, even though there is a dense transaction history. So long as those semantics are documented, would that be a problem for your implementation?

**Comment by theoreticalbts** [comment]
The real solution here is to add an extra index which indexes by `(account_name, op_type, op_num)` and then merge these for all the op types required.  There might even be an algorithm to merge N sorted collections into one somewhere in stdlib or boost.

**Comment by mvandeberg** [comment]
That is a bit more of a refactor to the account history plugin than updating the API. Not opposed to doing it, but it is not an immediate priority for us. If you want to update the plugin yourself and make a PR, we would be happy to review and merge, otherwise, we'll get to it when we have time.

**Comment by aaroncox** [comment]
It would be a decent step forward to have it implemented with a limit, but it wouldn't be ideal in every situation (probably edge cases).

I can imagine a situation where a malicious actor spammed thousands of downvotes on an account, clogging up their account history, which would limit how far back their history could go. Using the whitelist ops filtering on a steemd instance to only have transfer related operations would alleviate this for the Vessel use case, but users would be reliant upon those specific servers at that point.

I appreciate the thought put forward from you guys on this issue.

**Comment by mvandeberg** [comment]
The limit would be on the number of ops returned via the API call, not the limit in history.

**Comment by mvandeberg** [comment]
Bandwidth rate limiting should prevent their history from becoming too large.

**Comment by aaroncox** [comment]
Oh, then absolutely yes. 

I assume the `from` and `limit` fields would then allow recursive calls against the filtered history beyond that limit as it does now?

**Comment by mvandeberg** [comment]
Not recursive calls, but paginated calls, yes. Semantically, if the call returns no ops then you would want to call on `from - limit` for the next call. We may need to implement semantics to convert -1000 to be the most recent op num - 1000 so that if the first 1000 ops don't contain the filtered ops you could still query the next 1000.

**Comment by aaroncox** [comment]
Alright sorry - I misunderstood that then. The undesired effects of requesting 100 results and returning less (sometimes none) is what I'd really like to avoid. 

Many web interfaces load X results, and paginate by X results. Loading X results, and returning less than X isn't an ideal situation. It's confusing to have each set of paginated results returning something besides X. 

I understand from the conversation that it isn't an easy request to fill due to how things are built, but having that as an end goal would be fantastic for any UI built around the APIs.

**Comment by youkaicountry** [comment]
This should be fixed elsewhere, perhaps in RocksDB implementation or an outside application.
