### ISSUE TITLE
Looking at a SteemIt Wallet Crashes my Browser

### ISSUE THREAD

**Issue by Siko91** [steemit/steem#1368]
On my desktop, I am using Firefox 44.0.2 on Windows 8.1. (I do not want to update my browser)
On my phone, I also use Firefox, but it is the newest version for Android.

On both devices I have problems when looking at the wallet page of steemIt profiles.

On my computer, the browser sometimes crashes.
On my phone - it freezes and asks me if I want to stop some slow JavaScript, or let it run.

Basically - one of the scripts on that page is probably not performing well.

**Comment by mvandeberg** [comment]
This repo is for the Steem blockchain, not Steemit.com. Please file this issue here: https://github.com/steemit/condenser
