### ISSUE TITLE
Remove unnecessary tags plugin indices.

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1371]
The tags plugin still takes up a significant amount of reindex time. Most of which is spent in boost multi index containers. We should remove unnecessary indices.

I am defining an unnecessary index as one that is either: 

A) Not used anywhere
B) Outdated and not required for Condenser

Those that I have identified are:

`by_parent_net_rshares` - Not used anywhere
`by_parent_active` - Active indices are no longer used in Condenser
`by_author_parent_created` - Not used anywhere

Potentially:
`by_net_rshares` - Condenser uses `by_reward_fund_net_rshares` for post and comment rewards. Combining the results of both gives `by_net_rshares`. @roadscape Thoughts?

**Comment by mvandeberg** [comment]
For the following objects, these indices are not used.

`author_tags_stats_object` : `by_author_tag_rewards`,`by_tag_rewards_author`

The entire `peer_stats_object`

**Comment by roadscape** [comment]
What's the difference between `by_net_rshares` and `by_reward_fund_net_rshares`?

**Comment by mvandeberg** [comment]
`by_net_rshares` is everything. `by_reward_fund_net_rshares` breaks up between comments and posts. Even though they are the same reward fund. It powers the `/payout` and `/payout_comments` routes in `get_state`.

**Comment by roadscape** [comment]
Since there's only a single fund, it seems safe to roll into a single `by_net_rshares`. Wouldn't API results be identical? Or would this necessitate merging `/payout` and `/payout_comments`?

**Comment by mvandeberg** [comment]
I am proposing removing `by_net_rshares` because while we do have an API call for it, it is not used anywhere and anyone that wants the same results can call `get_comment_discussions_by_payout` and `get_post_discussions_by_payout` and combine the results. This would have 0 impact on Condenser.

**Comment by roadscape** [comment]
Let's drop it then. Hive already has this data if it's needed down the line.
