### ISSUE TITLE
Invalidate curators and beneficiaries when max_accepted_payout is zero

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1379]
The `max_accepted_payout` cap is applied before the curator / beneficiary logic (which is skipped when rewards are zero).  Thus, it doesn't really make sense for a user to specify curators / beneficiaries to be paid when `max_accepted_payout` is zero.

So let's require that `allow_curation_rewards` is `false` and forbid `comment_payout_beneficiaries` to be specified when `max_accepted_payout` is zero.

**Comment by youkaicountry** [comment]
Won't fix.
