### ISSUE TITLE
Advisory votes shouldn't update voting power

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1380]
A vote is considered to be *advisory* if one of the following is true:

- The voter's vesting STEEM balance (including delegation) is zero.
- The post has a zero `max_accepted_payout`.

Advisory votes should not decrease voting power.

**Comment by TimCliff** [comment]
Does this mean when a user votes on a post with payout declined, that it will not use any of their voting power to cast the vote, or is it something different?

**Comment by roadscape** [comment]
Regarding second case: if a post has zero `max_accepted_payout`, it seems like vote power should still be burned because posts are ranked by rshares.

**Comment by theoreticalbts** [comment]
@TimCliff Yes, that's the intent here.

@roadscape Ranking's not bound by consensus rules; steemit.com (and third-party UI's) are free to rank posts however they want.  Since the *only* consequence of advisory vote is ranking, this means UI's are free to address any abuse of advisory votes in any way they see fit.

For example, you could have separate rankings of normal posts and declined-payout posts, and then merge those two rankings any way you want.  For example, if the top posts become dominated by declined-payout posts, then a UI could limit the number of declined-payout posts that appear, or move them lower down the feed.  These could be sitewide settings, or even per-user preferences.

I don't think we'll have any problems with advisory votes being abused.  But obviously this is just my own prediction / opinion.  Ultimately the question, "Will people abuse 'free' voting for declined-payout posts?" can only be answered by implementing it and observing actual user behavior.

**Comment by roadscape** [comment]
I don't think there's a need to split the UI into different classes of posts. Also, given limitations of historical steemd data, `rshares` are a very useful way of keeping track of aggregate vote strength **plus** voting power _at the time of the vote_. There is simply no substitution for it if we want to keep the same behavior.

**Comment by roadscape** [comment]
I suppose as a hack "declined payout" posts could just set `max_accepted_payout` to `0.01` to trigger rshares collection while not being eligible for payout...

**Comment by theoreticalbts** [comment]
So the intent here is for `rshares` and other consequences of upvotes to remain the same as currently.  Currently the following happens for a post is like this:

- (1) Fields on the post, e.g. `net_rshares`, `abs_rshares`, etc., are updated
- (2) The upvoting account's remaining voting power is decreased according to how much they used up.
- (3) When the post's payout time arrives, payouts are directed accordingly, by reading the fields which were increased (decreased) by each vote's step (1).

The current declined-payout implementation simply skips step (3).

The change being discussed in this ticket is, for declined-payout posts, skip step (2).  But step (1) would still happen in the code.  Even though it would no longer matter to consensus for declined-payout posts, since there would be no step (3) that ever read the values that were written in step (1).

> rshares are a very useful way of keeping track of [stuff]

You'd still be able to query the `rshares` field via API, use existing query API's that depend on sorting as you do currently, or get other useful information out of `rshares`.

> I don't think there's a need to split the UI into different classes of posts

For the immediate future, I don't think we would.  For the long-term future, we'd only need to do this if we had problems with people started abusing "free" upvotes of declined-payout posts.  I don't think that we'll have such problems.

I'm simply pointing out that if I'm wrong and there *are* issues with abuse, we have options to fix the problem.

FWIW, "split the UI" is a misleading way of putting what I'm proposing.  The fix I'm proposing is, if people tend to upvote declined-payout posts more than they "should," we can simply apply a 25% penalty to the `rshares` field (or whatever field we're sorting on) for declined-payout posts.  This is a single multiplication -- it can live in `steemd`, but it could also conceivably live outside `steemd` in `jussi`.

**Comment by roadscape** [comment]
To back up a bit: what's the purpose of advisory votes? What are we gaining?

On the front-end side what we have considered is "reactions" to posts implemented using custom_json. Once we have these, I think they will be more useful and engaging than no-op votes anyway. E.g. a UI could have 5 reactions: 🔼, ⬇️, 😀, 😍, 😡. The first two would result in a vote_operation but the others would use custom_json. So if the concern is UI feedback this should cover it. If a user is for some reason not eligible for up/downvote, they can still signal sentiment, but we'll disable/hide the consensus vote option.

> The change being discussed in this ticket is, for declined-payout posts, skip step (2). But step (1) would still happen in the code. Even though it would no longer matter to consensus for declined-payout posts, since there would be no step (3) that ever read the values that were written in step (1).

Ok, I had assumed step 1 would be skipped as well. However:

 - 100% downvotes or upvotes on any (all) declined_payout posts become free
 - `rshares` on declined_payout posts *will no longer be the same units*
 - we could implement a scaling factor but the incentives have completely changed (different units)
 - reputation score becomes more gameable and/or complex

**Comment by youkaicountry** [comment]
Closing in favor of #2798.
