### ISSUE TITLE
Undo Session 15% of reindex

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1383]
We do not need undo states for blocks on reindex, but we still need it for custom json ops because a plugin may reject the op. We had been discussing making evaluators specify read and write access. Doing the write access on the custom json evaluators would allow us to create undo sessions only on the indices that we will be modifying, saving significant overhead.

**Comment by mvandeberg** [comment]
The market history multi index types take 1.5% of reindex and the plugin does not have a custom json ops.

**Comment by youkaicountry** [comment]
Broken out into #2799 and #2800.
