### ISSUE TITLE
steemd quits with exception when doing --replay-blockchain with no blocks in block log

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1386]
Following sequence of events:

- Start a node on an empty datadir without any seed nodes
- Quit (Ctrl+C)
- Restart the node with `--replay-blockchain`

You'll see "unknown exception" message due to [this assert](https://github.com/steemit/steem/blob/7f45ed699ab9d0415cf6653911d3f02814c416b9/libraries/chain/database.cpp#L157).  We need to catch this exception and display it properly.

**Comment by mvandeberg** [comment]
We need to add a case for `fc::exception` [here](https://github.com/steemit/steem/blob/master/programs/steemd/main.cpp#L97-L104), which all steem exceptions extend.
