### ISSUE TITLE
Add option to copy index file during replay for later reuse

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1389]
This ticket is inspired by https://github.com/bitshares/bitshares-core/pull/339/files

The problem we want to solve is the "my node crashed and my state file is corrupt" problem.  The way to solve this Properly is to add snapshot capability to `chainbase`.

But a hack which gets us 80% of the benefit for 10% of the work is to simply save an extra state file when replaying, then check for this state file and copy state from it on startup.

This requires us to decide in advance when to save the state.  The solution the BitShares issue arrived at is to simply save the state an arbitrary 10,000 blocks before the end of the index.

We can get rid of this arbitrary choice with the following approach:

- Replay all blocks
- Undo to LIB
- Save state
- Redo

**Comment by youkaicountry** [comment]
Won't fix.
