### ISSUE TITLE
Get new steemd config file options working with cli_wallet

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1390]
Figure out what new config file settings are needed to run `cli_wallet` and document them.  Better yet, make these settings the default when generating a config file.

Related: #1297, possibly #1298.

**Comment by mvandeberg** [comment]
Our supported mode of operation is in docker. Those images work already. We cannot make a default config that works with the cli wallet without modifying appbase (the plugin option belongs to appbase and is application agnostic).

Instead, documenting where out example configs and seed nodes are should be sufficient for a user choosing to run a custom config.
