### ISSUE TITLE
Default-initialize curve_id fields

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1391]
`curve_id` fields aren't initialized [here](https://github.com/steemit/steem/blob/master/libraries/chain/include/steemit/chain/steem_objects.hpp#L279-L280).  I'm pretty sure all integer fields (including `enum`'s) should be default-initialized to prevent undefined values from occurring.

I'm sure we initialize these on code paths where it matters, but nonetheless we should really have a default value.

**Comment by mvandeberg** [comment]
I do not see a PR for this issue.
