### ISSUE TITLE
P2P Mining Question

### ISSUE THREAD

**Issue by appjitsu** [steemit/steem#1406]
![image](https://user-images.githubusercontent.com/10903600/29490244-d7afe51a-84fb-11e7-927f-5df2e199d5c6.png)

Currently I have a p2p node up and running on Linux Mint and it says that it syncing. When will the actual mining start? After the sync? How long does it take?

**Comment by TimCliff** [comment]
Mining is no longer supported in the latest version of the software/blockchain. All of the blocks are produced and validated by the delegated proof of stake witnesses.

**Comment by appjitsu** [comment]
Then what is the point of running the p2p node?

**Comment by TimCliff** [comment]
If you were looking to do development, and wanted to run your own node, or were interested in becoming a witness, those would be two possible reasons. There also users in the community that host seed or API nodes to help support the network.

**Comment by appjitsu** [comment]
Is there monetary reward involved in becoming a witness?

**Comment by TimCliff** [comment]
Witnesses are paid per block that they produce. The GitHub repository is not really the appropriate forum for this discussion though. You can find out more information from researching on Steemit.com. There is also a #witness channel in Steemit chat if you have specific questions about being a witness.

**Comment by appjitsu** [comment]
Ok thank you for your response.
