### ISSUE TITLE
Move locks into heap

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1416]
If steemd crashes unexpectedly locks do not always release. When this occurs the following message (or one similar) will display. 

`Lock timeout, moving to lock 1`

It appears that steemd does not always recover from this state. A solution is deleting he shared memory meta file, but we do not need the file any more.

A better solution is to move the shared lock mechanism to be local to the chainbase database because we are no longer supporting multiple process locking. Making everything in process meets the locking requirements and allows steemd to start on a clean slate relative to locking every time it is started. This will eliminate this bug entirely and is a better design for the problem we are solving.

**Comment by mvandeberg** [comment]
This must be done in 0.19.X because 0.19.2 still has the support (albeit poorly) for the read only node.

**Comment by mkochanowicz** [comment]
What I observe, when running steemd in testnet with --enable-stale-production:
1. Run steemd first time, to produce blocks with flush as persistent data.
2. Re-run steemd to be sure continue blocks production.
3. Run second instance of steemd with --enable-stale-production. It try to reindex, but failed and crashed.
4. First instance of steemd still producing blocks. I press Ctrl-C, and this instance "exited cleanly".
5. Now, when I start new instance of steemd, it crashed the same way as in p.3. The only solution now is to delete blockchain folder manually.

Conclusion:
Any other instance of steemd has no sense to start if detect other instance with the same data files already started.

**Comment by mvandeberg** [comment]
Is the second instance running in the same data_dir? We are removing that as a use case.

If we want to have a bit of error checking we can have steemd acquire a file lock on the state file. If no other process has it, then we're good. If another process has it, steemd exits.

**Comment by mkochanowicz** [comment]
Yep, second one running with the same data_dir.

Current code try to flock and if failed, remove bin/meta files, creates new ones and trying re-index. Fail on flock should cause immediate exit - isn't it?

About locks (suggestions need acceptation):
- read_write_mutex -> std::mutex;
- read_lock -> remove;
- write_lock -> std::lock_guard; 
- rw_manager -> remove.

A few questions about data integrity (it is probably related to this issue):
1. Blocks are generated into memory mapped file, but become persistent after flush. 'block_log.index' is flushed in the same moment or after each generated block? Is it possible index contains more than 'shared_memory.bin'?
2. If steemd detect any problems with existing blockchain data integrity,
- should exit (now it ends with crash/uknown_exception) - the only solution is to manually remove blockchain data;
- try to resolve a problem (recreate data, resync etc. or even start from scratch in case of testnet).

**Comment by mvandeberg** [comment]
We have some other issues that are working on recovery. For now, just move the locks into the local database class instead of existing in shared memory (this removes the need for shared_memory.meta entirely), but keep the same locking semantics.

We need high availability writing (once every 3 seconds). The point of the locking mechanism is to allow the write process to move to a new lock if a reader halts or takes too long and updates healthy readers to use the new lock.

**Comment by mkochanowicz** [comment]
ok, done
