### ISSUE TITLE
Segmentation fault on SIGINT

### ISSUE THREAD

**Issue by tchap** [steemit/steem#142]
Sent SIGINT to `steemd` when it was processing some RPC, although I am not sure that is really related. Could have been something different, just describing the context.

```
3402885ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc":"2.0","method":"get_block","params":[2979512],"id":46}

3405110ms asio       main.cpp:173                  operator()           ] Caught SIGINT attempting to exit cleanly
3405628ms ntp        thread.cpp:246                exec                 ] thread canceled: 9 canceled_exception: Canceled
cancellation reason: [none given]
    {"reason":"[none given]"}
    ntp  thread_d.hpp:463 start_next_fiber
3405705ms th_a       thread.cpp:95                 thread               ] name:ntp tid:123145304985600
Segmentation fault: 11
```

**Comment by Phistr90** [comment]
I get a seq fault every time I send a SIGINT to kill steemd as well. That sucks since I have to replay the bc every time.

**Comment by mvandeberg** [comment]
There were some race conditions between the application and the network code that were resolved when we added shared-db. I have not ran into this issue locally in some time so I am closing this issue.
