### ISSUE TITLE
reputation plugin

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1425]
hivemind can supplant nearly all functionality of the `tags` and `follow` plugins, except for rep score. I suspect it's a relatively cheap computation compared to the rest of the `follow` plugin, so it would be convenient if it was separated out.

**Comment by mvandeberg** [comment]
For now, we can keep the follow plugin as is. I do not see an advantage to separating it out at this point in time. We will do a little bit of extra work (tracking follows twice), but there are much higher priorities at the moment.

**Comment by roadscape** [comment]
Sounds good. As a partial workaround I'm using `follow-start-feeds = 2000000000` to ignore feeds themselves, but I assume tracking of follows has non-trivial overhead.

> We will do a little bit of extra work (tracking follows twice)

Not sure I understand; rep doesn't depend on follow status.

**Comment by mvandeberg** [comment]
We will be tracking follows in hivemind and steemd.
