### ISSUE TITLE
Market orders should expire

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1449]
We should minimize users' ability to post things that require long-lived consensus bandwidth.  Thus, all orders in the on-chain market should be required to have an expiration time that is not too far in the future, say at most `head_block_time() + MAX_ORDER_EXPIRATION_TIME`.

At the hardfork time arrives, all currently existing orders are converted to expire at `head_block_time() + MAX_ORDER_EXPIRATION_TIME`.  Thus, ancient orders will eventually be cleaned off the books.  Anyone user who wishes to have their orders continue to exist can simply re-create them.

I'm thinking `MAX_ORDER_EXPIRATION_TIME` should be 72 hours.

Thoughts?

**Comment by iamsmooth** [comment]
Seems fine to me. Please allow the expiration time to default to the maximum if specified as 0 (currently: no expiration) to allow for some partial backward compatibility with existing applications (I think most of my existing trading bots would continue to work) but also for non-programmatic use with, for example, cli-wallet where needing to actually specify a time would be a frustrating annoyance.

**Comment by theoreticalbts** [comment]
@mvandeberg What are your thoughts on this change?

Also, at least one exchange has implemented a [similar policy](https://support.bittrex.com/hc/en-us/articles/115003004171-What-are-my-trade-limits-).

**Comment by mvandeberg** [comment]
I think this is a reasonable change. I would follow the precedence set by the exchange and use 28 days as a max expiration. Interestingly enough, they are implementing a policy similar to the tick pricing rule proposed in #1573

**Comment by theoreticalbts** [comment]
Great minds think alike!  I'm unassigning myself for now, since I'm not actively working on this.

**Comment by sneak** [comment]
My opinion is that 72h is too low, while 28d might be slightly high, but not so high that it's a showstopper.
