### ISSUE TITLE
New Limit Order Operation 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#147]
A new limit order operation is needed that allows all orders of any size to use full precision.

**Comment by bytemaster** [comment]
https://steemit.com/steem/@complexring/a-mathematical-analysis-of-obtaining-liquidity-rewards

**Comment by abitmore** [comment]
How about force the amount of STEEM in `price` to be 10^N only? For example, 0.345 SBD per 1 STEEM, or 34.567 SBD per 100 STEEM or etc.
