### ISSUE TITLE
update_witness_schedule issue?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#15]
According to [the code](https://github.com/steemit/steem/blob/515afd71b1b6ae08bfe8e98e7b86784bf9865a86/libraries/chain/database.cpp#L891), the logic in `update_witness_schedule()` executes every 21 blocks. 
* With [this code](https://github.com/steemit/steem/blob/515afd71b1b6ae08bfe8e98e7b86784bf9865a86/libraries/chain/database.cpp#L903-L912), 21 elected witnesses and 1 time sharing witness are pushed;
* with [this code](https://github.com/steemit/steem/blob/515afd71b1b6ae08bfe8e98e7b86784bf9865a86/libraries/chain/database.cpp#L945-L947), one pow witness is pushed;

So in total 23 witnesses are pushed into the `active_witnesses` list, after shuffled, only the first 21 will produce blocks in this round (the last 2 won't have chance due to reschedule).

Am I missing something?

**Comment by bytemaster** [comment]
I have addressed this issue in the latest commits. There were many problems in this area of the code.

**Comment by arhag** [comment]
I think there are still some problems with the fixes. Please see my line notes here: https://github.com/steemit/steem/commit/376915ed61155f1679c7123c5f96d6b677121bdd
