### ISSUE TITLE
(Develop) Steemd should display sync messages at the default log level

### ISSUE THREAD

**Issue by NateBrune** [steemit/steem#1503]
```
------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.19.0
------------------------------------------------------
1088668ms th_a       smt_test_plugin.cpp:252       smt_test_plugin      ] Caught exception:
{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"smt_operations.cpp","line":41,"method":"validate","hostname":"","thread_name":"th_a","timestamp":"2017-09-05T01:18:08"},"format":"is_valid_unit_target( e.first ): ","data":{}}]}
1088669ms th_a       p2p_plugin.cpp:524            plugin_initialize    ] Option seed-node is deprecated in favor of p2p-seed-node
1089136ms th_a       webserver_plugin.cpp:156      plugin_initialize    ] configured with 256 thread pool size
1089139ms th_a       chain_plugin.cpp:97           plugin_startup       ] resync requested: deleting block log and shared memory
1099573ms            p2p_plugin.cpp:273            get_block_ids        ] 90005 peer_is_on_an_unreachable_fork: peer is on another fork
Unable to provide a list of blocks starting at any of the blocks in peer's synopsis
    {}
      p2p_plugin.cpp:258 get_block_ids
1099616ms            p2p_plugin.cpp:273            get_block_ids        ] 90005 peer_is_on_an_unreachable_fork: peer is on another fork
Unable to provide a list of blocks starting at any of the blocks in peer's synopsis
    {}
      p2p_plugin.cpp:258 get_block_ids
1099618ms            p2p_plugin.cpp:273            get_block_ids        ] 90005 peer_is_on_an_unreachable_fork: peer is on another fork
Unable to provide a list of blocks starting at any of the blocks in peer's synopsis
    {}
      p2p_plugin.cpp:258 get_block_ids
1099635ms            p2p_plugin.cpp:273            get_block_ids        ] 90005 peer_is_on_an_unreachable_fork: peer is on another fork
Unable to provide a list of blocks starting at any of the blocks in peer's synopsis
```

Potentially a local issue, but I haven't been able to --resync the develop branch for a week or so.

**Comment by theoreticalbts** [comment]
I can reproduce this bug, investigating.

**Comment by theoreticalbts** [comment]
Do you leave it running or do you kill it as soon as you see these errors?  For me it spews these messages repeatedly but continues to sync.

The `get_block_ids()` function has `FC_LOG_AND_RETHROW()`, the `application.cpp` code from `master` has `FC_CAPTURE_AND_RETHROW()`.

So I think these exceptions are normal (the exception is caught in `node.cpp`).  We just don't log them on `master`.

**Comment by roadscape** [comment]
The errors shown in OP might be due to bad seed nodes in your config, but it shouldn't affect syncing as long as at least one is good.

Also it seems the sync messages don't show anymore unless you set your log level to debug. Last time I tested develop, this was the case. It looked stuck but `info` revealed it was indeed syncing.

**Comment by mvandeberg** [comment]
> steemd should display sync messages at the default log level.

No, it really shouldn't. We have it set to log every 10k blocks, I believe. If it logged every block then syncing would slow down significantly because of console IO. That is why p2p logs default to a log file and the console logs are sparse but show progress.

**Comment by roadscape** [comment]
The issue is that on develop (*with default config*) no "syncing blockchain" messages are ever displayed -- creating the appearance that the process is stuck.

**Comment by mvandeberg** [comment]
We had a few messages about opening the blockchain with X many blocks. Some of those may have been inadvertently deleted in the refactor.
