### ISSUE TITLE
Implement smt_setup_operation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1508]
All `smt_setup_operation` semantics needs to be implemented.

- Fields should be copied from operation to corresponding fields `smt_token_object`
- Per-block processing should be added to check for arrival of timed events `generation_begin_time`, `generation_end_time`, `announced_launch_time`
- `smt_creation_fee` field should be removed, since it is now in `smt_elevate_account_operation`
- Implement unit tests

**Comment by vogel76** [comment]
Waits for answers to questions inside:
https://github.com/steemit/steem/issues/1554

**Comment by Kiwonik** [comment]
Is any backend reaction supposed to happen when SMT creator abandons its token i.e. no further smt operation follows successful `smt_setup_operation`? In other words all three dates (contribution start/end & launch) pass by with no operation triggered by creator (no contributors either).
If the answer is 'none' (I assume so) then `smt_setup_operation` is not the place to start per-block processing described in this issue - the next smt operation (including contribution attempt) is.

**Comment by theoreticalbts** [comment]
From the spec:

> ICOs may specify a minimum number of STEEM units `min_steem_units`. If the ICO does not reach `min_steem_units` before `generation_end_time`, then it does not occur, and contributors become eligible for refunds.

The situation where `min_steem_units` is not reached is called a *failed launch*.  We should require `min_steem_units > 0`, so in case no contributions occur, it will be a failed launch.

The asset ID remains reserved to the SMT, at least until the end date occurs, because `smt_contribute_operation` needs a way to uniquely refer to the asset.

**Comment by vogel76** [comment]
I think the asset ID being used at executed smt_create_operation shall stay reserved forever, since the control-account owner already paid for this reservation.

**Comment by Kiwonik** [comment]
@theoreticalbts I didn't find any mention about _failed launch_ term in whitepaper (including the state diagram). I assume it's a kind of SMT creation phase - which would for example 
- Allow contributors for refund.
- Allow for possible re-launch attempt with another `smt_create_operation`.
Can you confirm?

@vogel76 Yes, the asset ID stays reserved with the control account per whitepaper:
> At launch_expiration_time, if the ICO has not yet launched, all contributors will be automatically refunded (with virtual operations) and the ICO will be cancelled. The symbol will remain reserved to the specified control_account. However, in order to launch the token, an smt_create_operation must be issued and the smt_creation_fee must be paid again.

**Comment by mvandeberg** [comment]
Failed Launch is a state where the ICO has finished but the creator has not revealed the caps.

Because the initial disbursement cannot happen, contributors can still put out of ICO and get a refund for their contributions.

**Comment by vogel76** [comment]
This issue depends on the scheduler implementation, since some time based actions must be done at smt_setup evaluation.
https://github.com/steemit/steem/issues/1724

**Comment by youkaicountry** [comment]
The evaluator for this is currently a stub.

**Comment by youkaicountry** [comment]
Examine how savings withdraw requests are handled, and implement the timed event in that manner.
