### ISSUE TITLE
Implement token generation logic

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1509]
Let's call this method `smt_generate_initial_tokens()`.  It will be called when `announced_launch_time` is reached and after a cap is revealed.  It will perform the following checks:

- Has `announced_launch_time` been reached and both caps revealed?  If not, then no-op.
- Assign tokens and STEEM according to logic described in the spec
- For now don't worry about special destinations like `alice.vesting`, they will be implemented as a separate issue

- Implement unit test which checks balances

**Comment by youkaicountry** [comment]
Outdated.
