### ISSUE TITLE
Trending section does not work....

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#151]
> @rgcrypto: https://steemit.com/trending/ is showing old post that has been paid out. Is that normal?

https://github.com/steemit/steemit.com/issues/35

The UI is calling `get_state /trending` ...
https://github.com/steemit/steem/blob/0ea6049e760e0452ecb22b98a2ad808493bd3760/libraries/app/database_api.cpp#L951-L960

**Comment by mvandeberg** [comment]
#549 is possibly related and has been fixed in PR #550.
