### ISSUE TITLE
Implement smt_setup_inflation_operation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1513]
- Record inflation parameters in database
- Per-block processing which executes inflation event and reschedules next event (if any)
- Add constant for minimum inflation event spacing (1 hr?)
- Implement unit test

**Comment by Kiwonik** [comment]
I'm changing `interval_seconds` type to **u**int32_t as I can see no scenario in which its negative value would be meaningful.

**Comment by mvandeberg** [comment]
Does the interval need to be divisible by the block interval?

What is the semantic for disabling inflation? Setting inflation to 0% APR or setting an infinite interval. The later seems more efficient.

**Comment by Kiwonik** [comment]
I'm forcing at least one of `lep_abs_amount`, `rep_abs_amount` to be positive value.

**Comment by Kiwonik** [comment]
Closing this issue as follow-up issue has been created that requires development of further phases of SMT ICO. See #1638 
The accompanying branch may be deleted now.
