### ISSUE TITLE
Implement smt_set_setup_parameters_operation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1516]
- Implement the operation
- Implement unit tests
- Record parameters in `smt_token_object`
- Unit tests to check parameters have intended functionality

**Comment by vogel76** [comment]
1) How associated `smt_token_object` shall be retrieved ? I see in the other part of code that potentially associated token object is dynamically looked in the database. Why it is not directly associated to the `account_object`  being persistent in the storage ? 
2) Which definition of `smt_token_object` is effective one - there are two in the code:
a)  one inside chain/include/steemit/chain/smt_token_object.hpp
b) second inside plugins/smt_test/include/steemit/smt_test_objects.hpp
Probably a) but maybe single definition shall be shared across testing code too ?

**Comment by mkochanowicz** [comment]
@theoreticalbts Questions (not only for this issue, but rather general):
1. We need to know what is current phase of smt creation. Should `smt_token_object` has enum field with current phase?
2. How flat_set should be recorded in `smt_token_object`? In this issue case, there are two possible values: `allow_vesting` and `allow_voting`. Should I simply create two bool fields for them?

**Comment by vogel76** [comment]
Probably finished as associated PR is closed:
https://github.com/steemit/steem/pull/1564
