### ISSUE TITLE
Implement SMT based comment rewards

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1518]
- SMT rewards for comments
- Fields or helper function to determine which SMT's a comment is eligible for
- Should re-use existing rewards code as much as possible
- Unit tests to verify functionality

**Comment by vogel76** [comment]
Main question is: what is a source of asset symbol types used at voting (and next internally at generating a reward):
1. assets (SMTs) chosen by comment publisher at comment/post (from set of SMTs being owned by publisher), 
1. assets (SMTs) chosen by voter
1. concatentation of 2 sets described above

How voting power relates to SMT reward ? Does each voter shall have stored power specific to given SMT.

**Comment by mvandeberg** [comment]
Closed, outdated.
