### ISSUE TITLE
Implement extended fund destination syntax

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1519]
SMT syntax has some specials like `smt.rewards` for the rewards pool, `alice.vesting` for a user's vesting balance, etc.  Also `$from`.

Precise syntax specification, parsing, and serialization of these "destinations" needs to be developed.

Operations which potentially take a destination should have a different field type.

**Comment by theoreticalbts** [comment]
Moving to SMT project and unassigning myself.  This isn't necessary for MVP.  Maybe we should add this feature once the base functionality of SMT's is a little more developed.

**Comment by youkaicountry** [comment]
Closing as outdated.
