### ISSUE TITLE
Rename steemit namespace to steem

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1529]
The steemit namespace should be changed to steem every where that it occurs.

**Comment by mvandeberg** [comment]
All steemit build targets should be renamed to steem. (i.e. steemit_chain -> steem_chain)

**Comment by vogel76** [comment]
Does this change shall also affect directories (ie `libraries/protocol/include/steemit`) ?

**Comment by mvandeberg** [comment]
Yes
