### ISSUE TITLE
itr != by_permlink_idx.end():   This error message won't let me comment on posts?!?

### ISSUE THREAD

**Issue by Lylabird** [steemit/steem#154]
itr != by_permlink_idx.end():

Earlier today while researching steemit I all the sudden got this LOUD noise and an error message to call Windows support. After several hours computer techs cleaned out my computer and got rid of the Malware.

But now I can't seem to post anything on steemit. Get this error message everytime. ?!?

**Comment by songproducer** [comment]
I also got this error trying to comment on my Android phone (using Firefox).

**Comment by Lylabird** [comment]
I am using Chrome. Did you figure out how to get past it?

Namaste,

Lynda Leonard / ~ljl~
816-421-0620
www.LyndaJLeonard.com <http://www.lyndajleonard.com/>


[image: --]

Lynda Leonard
[image: https://]about.me/lyndaleonard
<https://about.me/lyndaleonard?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
Kansas City, "America's Creative Crossroads"

"Be who you are and say what you feel, because those that mind don't matter
and those that matter don't mind." .....Dr. Suess

**Comment by songproducer** [comment]
No, I am now using chrome too and still having the same problem. Someone has broken steemit!!

**Comment by songproducer** [comment]
The issue has now been fixed.

**Comment by Lylabird** [comment]
Yes, it is FIXED! Thank you all so much. Just did a test post/comment on steemit sans that annoying message ;-) ~ljl~
