### ISSUE TITLE
Cannot Use Locales in Subject

### ISSUE THREAD

**Issue by clayop** [steemit/steem#155]
Error message:
permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH:

This is what I got when I tried to use Korean for subject

**Comment by theoreticalbts** [comment]
What is the actual subject you attempted to use?

The length check is the number of bytes in the UTF-8 representation.

**Comment by clayop** [comment]
It works now
