### ISSUE TITLE
Unsuccessful sync of blockchain

### ISSUE THREAD

**Issue by i3bitcoin** [steemit/steem#1551]
Hi,

I've been trying to sync the wallet for 2 times already, but at the end I'm getting a strange error.

OS:  Ubuntu 16.04
Wallet: Steem 0.19.2

First attempt:
I tried to sync the full node, but when I get 60+ gb filled space, I shut down steemd to free some space and sync again. After this action I got error **Lock timeout, moving to lock 1** and synchronization didn't start anymore.

Second attempt:
I've set track-account-range, downloaded block_log and started syncing with replay option.
When the process finished, I got this error **No witnesses configured**. Once I tried to restart steemd, I got the same error: **Lock timeout, moving to lock 1**.

BTW, if I set seed-node multiple times in config.ini, I'm getting this error:
**Error parsing logging config from config file /root/.steem/config.ini, using default config**

Is there any instruction, how should I start my steemd correctly, because synchronization takes a very long time.

**Comment by mvandeberg** [comment]
First of all, instead of resyncing every time, the blockchain is saved locally as the block log. You can replay from this local log using `--replay`. 

As for `lock timout, moving to lock 1.` Delete `shared_memory.meta` in the blockchain subdirectory of your data directory and restart (default is `witness_node_data_dir/blockchain`).

**Comment by i3bitcoin** [comment]
The message lock timeout has gone, but steemd do nothing

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8G3tDuCZbP44HzMLV6zPZGwVQ8Nt4Kji8PfjsPiNq1BK653XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.19.2
------------------------------------------------------
