### ISSUE TITLE
Run tests in read-only chroot

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1562]
Let's tighten down the CI environment to catch bugs of the form of #1561 (unit tests attempting to write to locations they shouldn't).

Some notes on this issue:

```
# See explanation at https://unix.stackexchange.com/questions/128336/why-doesnt-mount-respect-the-read-only-option-for-bind-mounts
mkdir -p steem-ro
mount -t none -o bind steem steem-ro
mount -t none -o bind,remount,ro steem steem-ro
chroot steem-ro tests/chain_test
```

Note, we will need to `ldd chain_test` and then copy the libraries needed by the `chain_test` binary into the chroot.  This process can be simplified by statically linking `steemd`.  The static build PR https://github.com/steemit/steem/pull/1446 needs to be ported to `develop`.

**Comment by theoreticalbts** [comment]
`chroot` may be overkill, it could be simpler to just `chmod -R a-w build`

**Comment by mvandeberg** [comment]
Closing, this is a part of #1561
