### ISSUE TITLE
JSON RPC Tests

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1568]
The json rpc plugin should be tested for conformance with the json rpc 2.0 spec.

http://www.jsonrpc.org/specification

All "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", and "RECOMMENDED" directives of the spec should fail the unit test if the requirements are not met.

All  "MAY" and "OPTIONAL" directives should be tested, but not fail the test. Print a warning if such a test fails.

**Comment by vogel76** [comment]
At first please look for some tools able to do such verification..
