### ISSUE TITLE
Add order ops to account transfer_history

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#157]
We need to get users' order op history in `get_state` for `@account/transfers` route.

It may be best to simply feed these operations into the existing `transfer_history` list.

https://github.com/steemit/steem/blob/0ea6049e760e0452ecb22b98a2ad808493bd3760/libraries/app/database_api.cpp#L1212

Could you feed the following cases into `transfer_history`?

```
case operation::tag<limit_order_create_operation>::value:
case operation::tag<limit_order_cancel_operation>::value:
case operation::tag<fill_convert_request_operation>::value:
case operation::tag<fill_order_operation>::value:
```

**Comment by mvandeberg** [comment]
Adding `fill_convert_request_operation` and `fill_order_operation` to returned transfer history.

**Comment by mvandeberg** [comment]
Merged
