### ISSUE TITLE
Simplify interface of asset / price

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1571]
I'm currently working on refactoring `asset` class.  To make this work easier, I'd like to remove or make private some methods such as `precision()`, `decimals()`, `set_decimals()`, `to_real()` and `symbol_name()`.

In particular `to_real()` is only used in API's so it should be moved to those API's.

**Comment by theoreticalbts** [comment]
Related: #1549

**Comment by mvandeberg** [comment]
What is the motivation for this change?

In the past we have decided against making methods private. `precision()`, `decimals()`, `to_real()`, and `symbol_name()` are all accessors. There seems to be little reason to make them private.

**Comment by theoreticalbts** [comment]
Because I'm going to be removing them.  I changed my mind about `decimals()`, it ended up being `public`.

**Comment by theoreticalbts** [comment]
Why is this ticket still open?  The relevant PR was merged months ago.

**Comment by mvandeberg** [comment]
It was probably not closed by accident.

You know, you can close it ;)
