### ISSUE TITLE
Add decimal_price field to API's, re-implement real_price

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1575]
So if we implement tick pricing rules #1573, a price will always have a divisor that is a power of 10.  Decimal prices are currently implemented approximately, for the `real_price` field, using floating-point `double` computations.

Let's implement them exactly using integer arithmetic and string processing.  Here are the requirements:

- Remove `real_price` for now as part of #1571 
- Refactor asset internals #1549
- Implement Tick Pricing Rules #1573
- Implement `decimal_price` field which is a decimal value stored as a string
- `decimal_price` should be exact for TPR prices, approximate with a `?` character appended for non-TPR prices
- Implement `real_price` field by using some standard library or Boost function to convert string `decimal_price` field to `double`
- (Optional) Create plumbing to send `real_price` as a `string` value to the JSON output code, so the conversion to `double` and precision loss never happens [1].

[1] In order for this to actually be useful, a client parser would need to be sufficiently flexible to read `real_price` as a string and convert it to some non-floating-point type.  This is fairly easy to do in Python, in fact [the standard library docs](https://docs.python.org/3/library/json.html) provide an example (simply `import decimal` and then specify `parse_float=decimal.Decimal`).

This is an "optional" requirement for the following reasons:

- We should still supply it as a string in the JSON to support client libraries that aren't as flexible as Python
- Precisely defining and building this plumbing is non-trivial

**Comment by mkochanowicz** [comment]
@theoreticalbts - just for sure: you mean `real_price` field of `order`, right?

**Comment by mvandeberg** [comment]
Blocked by #1573
