### ISSUE TITLE
OS X home brew instructions - too lazy for pull req

### ISSUE THREAD

**Issue by davembg** [steemit/steem#158]
1) brew doctor
2) brew update
3) brew install https://gist.github.com/shazow/c71c652409015479a7e6/raw/secp256k1.rb
4) brew install boost cmake git openssl autoconf automake python3

5) DON'T EVER "brew link --force" ANYTHING - EVER, FOREVER.
Change the build vars for cmake.

cmake -DENABLE_CONTENT_PATCHING=OFF -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include

**Comment by bmann** [comment]
This fixes most things. I am still stuck on OS X. Currently getting an error from boost 1.61.0. Seems to be the same issues as reported here https://github.com/facebook/folly/issues/413.

I can paste the full log if that's helpful.

**Comment by TigerND** [comment]
Here's a working Formula:
https://steemit.com/steem/@teego/homebrew-package-is-updated-to-the-version-0-13-0-rc3

**Comment by bmann** [comment]
@TigerND thanks, just kept following threads on steemit itself and found your brew. Comments/votes etc. as thank you!

Next up, trying to get mining etc. setup!
