### ISSUE TITLE
hardfork.hpp missing

### ISSUE THREAD

**Issue by b00klegger** [steemit/steem#159]
Running into an issue trying to compile `steemd`:
```# make steemd/fast
[ 18%] Building CXX object programs/steemd/CMakeFiles/steemd.dir/main.cpp.o
In file included from /var/local/steemsrc/steem/libraries/app/include/steemit/app/application.hpp:28:0,
                 from /var/local/steemsrc/steem/programs/steemd/main.cpp:1:
/var/local/steemsrc/steem/libraries/chain/include/steemit/chain/database.hpp:7:38: fatal error: steemit/chain/hardfork.hpp: No such file or directory
 #include <steemit/chain/hardfork.hpp>
                                      ^
compilation terminated.
make[1]: *** [programs/steemd/CMakeFiles/steemd.dir/main.cpp.o] Error 1
make: *** [steemd/fast] Error 2```

I cannot find this file `hardfork.hpp` in the repo. Any ideas as to what I'm doing wrong?

Centos 7 host
Boost 1.5.8
HEAD detached at v0.8.5

**Comment by abitmore** [comment]
`hardfork.hpp` is generated from the files in `libraries/chain/hardfork.d` by a script. Perhaps the script doesn't work in CentOS, or the directories are messed up?

Try `make build_hardfork_hpp` and check the logs.

(By the way I've never tried `make ***/fast`)

**Comment by b00klegger** [comment]
Thanks for your help. Was having multiple problems even after the hardfork fix you suggested. Switched over to build on Fedora/latest and got a working binary out of that. Compiled the whole project, not just steemd.
Thx!
