### ISSUE TITLE
Implement benchmarking system to measure steemd reindex performance

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1590]
Before any serious refactorings will start, definitely benchmarking system must be created, offering performance measure for each done build.
Prequisistes:

1.  steemd must offer an option to stop reindex at given block number, to make possible limiting execution time during benchmark
1. introduce functionality which allows gathering statistic data related to
- number of processed blocks per `s` during reindexing. 
- number of created state objects (i.e. account_objects etc),
- allocated memory
Such data collection shall be done in intervals (ie every 1k processed blocks), to show potential time/memory allocation change
Maybe existing `blockchain_statistic_api` could be enhanced and reused for this purpose.

**Comment by vogel76** [comment]
Such benchmarking process shall operate on already downloaded blockchain, to avoid time violation caused by network traffic.

**Comment by mvandeberg** [comment]
We should be careful using the `blockchain_statistic_plugin` in this manner because it creates objects and has a non-trivial runtime. It would be easy enough to have some counters in chainbase that count creations/modifications/deletions for each object type.

**Comment by vogel76** [comment]
Please add options:
1. stop-replay-at-block <block-no> which shall lead steemd to stop and exit after reaching given block number.
1. collect-benchmark-results <out-file> which shall print benchmark results on the stdout, together with messages related to replay progress. Additionally, XML/JSON file shall be produced containing:
  - benchmark data header containing: operation name, operation start time
  - potentially multiple data collections containing range of blocks the data have been gathered for. Collected data shall contain CPU time, Real time values, Current mem. allocation, Peak mem. allocation
  - one final data collection containing total time measure for whole operation incl. memory report as described above

**Comment by Gandalf-the-Grey** [comment]
blocks per second value would change over time during the reindexing
getting average for every 100k blocks processed might be a good idea

**Comment by Gandalf-the-Grey** [comment]
oh, also transactions per second (along with blocks per second) would be a valuable info

**Comment by vogel76** [comment]
Implementation done, memory report has been verified and corrected as specified here:
https://github.com/steemit/steem/issues/1651
@sneak  Please move it to any person being responsible for adding a benchmark scenario (at replay) to CI and do collection of results for further analysis.

**Comment by mvandeberg** [comment]
The next step in this issue is adding some automated benchmarking.

Removing myself and adding to Backlog

**Comment by mvandeberg** [comment]
For now, we won't add the benchmarking to CI. Closing.
