### ISSUE TITLE
Limit Follow Plugin Blog

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1593]
Feeds have a limit to how much will be archived at one time.

We should extend the same logic to a user's blog.

Hivemind should replace this functionality entirely. We can get a significant reindex speedup by enforcing these same rules in the meantime.

**Comment by roadscape** [comment]
@mvandeberg is this about limiting by count (a la `follow-max-feed-size`) or by date (`follow-start-feeds`)?

I'm not sure it's good to limit author blogs by date, it will empty a lot of blogs. 
Limiting by count would work, as long as it's not too constrictive. 

But I was also under the impression that:
1/ There is already some limit to blogs (reports of not being able to go to some authors' first posts)
2/ Limiting by count does not help reindex time, only mem usage

Hivemind will replace these functions entirely.

**Comment by mvandeberg** [comment]
We would do a little of both. The blog start date can be longer than the feed start date. My idea is to impose slight restrictions while we test appbase and get Hivemind ready to prod.

**Comment by roadscape** [comment]
Ran some numbers using 6 month cutoff as a test:

Accounts w/ 1+ blog entries: 122,373
Accounts w/ 1+ entries last 6mo: 97,281

If the cutoff was 6 months, 20.5% of non-empty blogs would become empty.

Top-level posts last 6mo: 1,895,655 (~82%)
Top-level posts prior 6mo: 424,775 (~18%)

And it would allow us to skip ~18% of all posts. IMO -- the savings is not significant given the cost.

**Comment by roadscape** [comment]
A 3-month cutoff could get us more substantial savings, but IMO that's cutting it way too short for a blogging platform. Even 6 months is not great; bloggers on our platform expect their articles will be available forever.

**Comment by mvandeberg** [comment]
This is not a change we have plans on making at anytime in the near future.
