### ISSUE TITLE
gcc 6.1.1 - compilation error

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#160]
In file included from /usr/include/boost/config.hpp:61:0,
                     from /usr/include/boost/container/flat_map.hpp:14,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/container/flat_fwd.hpp:2,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/reflect/typename.hpp:10,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/reflect/reflect.hpp:18,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/time.hpp:138,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/log/logger.hpp:3,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/exception/exception.hpp:6,
                     from /home/xeroc/Steemit/steem/libraries/fc/include/fc/uint128.hpp:6,
                     from /home/xeroc/Steemit/steem/libraries/fc/src/uint128.cpp:1:
    /usr/include/boost/multiprecision/cpp_int.hpp:193:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
        BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
        ^
    /usr/include/boost/multiprecision/cpp_int.hpp:416:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
        BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
        ^
    /usr/include/boost/multiprecision/cpp_int.hpp:568:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
        BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
        ^
    make[3]: *** [libraries/fc/CMakeFiles/fc.dir/build.make:63: libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o] Error 1
    make[2]: *** [CMakeFiles/Makefile2:379: libraries/fc/CMakeFiles/fc.dir/all] Error 2
    make[1]: *** [CMakeFiles/Makefile2:2089: programs/cli_wallet/CMakeFiles/cli_wallet.dir/rule] Error 2
    make: *** [Makefile:617: cli_wallet] Error 2

Possible fix:

http://stackoverflow.com/questions/36925881/boost-uint128-t-with-varying-behaviors

**Comment by Gandalf-the-Grey** [comment]
https://github.com/boostorg/multiprecision/commit/f9c8f9ec091ad232c0a291904f7839d665d098e0

**Comment by theoreticalbts** [comment]
This is an issue for either Boost or GCC to fix, not us. Closing.

**Comment by l0k1-smirenski** [comment]
Being that Ubuntu 16.04 uses a quite old version of GCC (5.3.1) I think that this ticket should be reopened and the precision of the variables be corrected. For someone trying to build it on anything other than 16.04 it requires the building (in many cases) of an old version of GCC which is an hour or more compilation.

**Comment by Gandalf-the-Grey** [comment]
a)
> This bug causes a compilation failure only for steemd

b)
> boost 1.5.7 compiles just fine on GCC 6

a) is not true
b) doesn't mean that it won't cause issues while building other software that depends on boost

**Comment by l0k1-smirenski** [comment]
Between `steemd` and boost, only `steemd` fails to compile on gcc 6.1, so a) is true.

Other software that depends on Boost mainly all works on 1.6.3, but `steemd` does not, as far as I know also does not work with 1.5.8. Thus, it follows that nobody is building any other software in the same environment as `steemd` anyway, so b) is also incorrect.

**Comment by ander7agar** [comment]
I am using Ubuntu 18.04 LTS and gcc 7.3.0. I have tried compiling with Boost 1.57.0 and Boost 1.60.0 and I have obtained this same error in both cases. Should I use another version of gcc? Of course I have not had problems using boost in other projects.

**Comment by thomass2008** [comment]
> [boostorg/multiprecision@f9c8f9e](https://github.com/boostorg/multiprecision/commit/f9c8f9ec091ad232c0a291904f7839d665d098e0)

Thanks Bro for link/ Awesome Help for me. Problem has gone after such changes.
