### ISSUE TITLE
Steem Cli get_account_history and get_transaction returns nothing

### ISSUE THREAD

**Issue by i3bitcoin** [steemit/steem#1604]
I'm having an issue while getting transaction history or information about any transaction.
**get_account_history** and **get_transaction** methods returns nothing. I can search for block and export transactions, but it isn't convenient.

Config settings:
public-api = database_api login_api account_by_key_api
enable-plugin = witness account_history account_by_key
track-account-range = ["myaccount"]

Any idea?

**Comment by i3bitcoin** [comment]
OS: Ubuntu 16.04
Steemd version: 0.19.2

Also I get an error when use method **transfer**.
"error":"10 assert_exception: Assert Exception\nfalse: invalid symbol\n {}\n th_a database.cpp:3472 get_balance

**Comment by mvandeberg** [comment]
track-account-range = ["myaccount","myaccount"]

The documentation says this is a ["from","to"] pair.

**Comment by mvandeberg** [comment]
I am assuming this was a configuration problem. Closing.
