### ISSUE TITLE
fixed_string::size() returning potential garbage data

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1609]
clang tidy displays the following message:

```
steem/libraries/protocol/include/steem/protocol/fixed_string.hpp:100:14: warning: Branch condition evaluates to a garbage value [clang-analyzer-core.uninitialized.Branch]
         if( *(((const char*)&d) + sizeof(d) - 1) )
```

The method in question is:

```
uint32_t size()const
{
   Storage d = boost::endian::native_to_big( data );
   if( *(((const char*)&d) + sizeof(d) - 1) )
      return sizeof(d);
   return strnlen( (const char*)&d, sizeof(d) );
}
```

The conditional is not clear. The intent is that if the last byte is non-zero then the entire string has been used and the length is the size of `Storage`. It is a necessary shortcut because a full `fixed_string` is not null-terminated. The method appears to work, but it may be silently failing.

I see a few solutions:

1. We add a size field that is initialized on construction or copy that is the size of the original string. This could even be a boolean flag that is, "`fixed_string` is size of `Storage`".

2. Add a null byte of padding at the end of `Storage` so that `strlen` operates properly.

3. Remove `size()`. When copying to a string, we would need to copy `Storage` to the stack, add a null byte of padding, and then convert to a `std::string`. Everywhere else that uses `size()` is usually checking against `account_name_type()` and should be changed to the explicit check `if( name == account_name_type() )`.

**Comment by theoreticalbts** [comment]
I think the `if` statement can be removed, the `strnlen()` correctly handles all cases.
