### ISSUE TITLE
get_witness_by_account doesn't work

### ISSUE THREAD

**Issue by inertia186** [steemit/steem#1619]
When making requests for `get_witness_by_account`, most full nodes reply with an invalid response.

```bash
#!/bin/bash

url='https://steemd.steemit.com'
#url='https://steemd.steemitdev.com'
#url='https://steemd-int.steemit.com'
#url='https://steemd.steemitstage.com'
#url='https://gtg.steem.house:8090'
#url='https://seed.bitcoiner.me'
#url='https://steemd.minnowsupportproject.org'
#url='https://steemd.privex.io'
#url='https://rpc.steemliberator.com'

json='{"jsonrpc": "2.0", "id": 1, "method": "call", "params": ["database_api", "get_witness_by_account", ["", 19]]}'

curl --data "$json" $url 2> /dev/null
```

Returns (invalid):

```json
{"id":1,"result":null}
```

Except for `steemd.steemitdev.com`, which returns:

```json
{
   "jsonrpc":"2.0",
   "error":{
      "code":-32601,
      "message":"Assert Exception:method_itr != api_itr->second.end(): Could not find method get_witness_by_account",
      "data":{
         "code":10,
         "name":"assert_exception",
         "message":"Assert Exception",
         "stack":[
            {
               "context":{
                  "level":"error",
                  "file":"json_rpc_plugin.cpp",
                  "line":107,
                  "method":"rpc",
                  "hostname":"",
                  "timestamp":"2017-10-03T04:03:48"
               },
               "format":"method_itr != api_itr->second.end(): Could not find method ${method}",
               "data":{
                  "method":"get_witness_by_account"
               }
            }
         ]
      }
   },
   "id":1
}
```

**Comment by mvandeberg** [comment]
Do not rely on our dev domain for reliability. I can be up, down, or running experimental/ new software (like it is right now).

We deployed a new version of steemd to steemitdev that has had extensive changes to APIs. The method you are looking for is now under the `condenser_api`. We will make an announcement detailing all of the changes when we are closer to public testing. In the meantime, you are free to poke at steemitdev, but any problems you encounter may not actually be problems.

**Comment by inertia186** [comment]
Except that it appears that `steemd.steemitdev.com` was the only node in this scenario that was responding correctly.  If `get_witness_by_account` has moved to a new namespace, all of the nodes (except `steemd.steemitdev.com`) are responding incorrectly with:

```json
{"id":1,"result":null}
```

**Comment by mvandeberg** [comment]
> We deployed a new version of steemd to steemitdev that has had extensive changes to APIs.

These changes have not yet been released. steemitdev is for development.

**Comment by mvandeberg** [comment]
Also, the "invalid" response you noted from other nodes is because you aren't calling the API properly. `get_witness_by_account` takes a single account name as an argument. You were calling expecting that the method was paginated, which it is not.

**Comment by inertia186** [comment]
That's beside the point.  `{"id":1,"result":null}` is completely wrong, even passing bad arguments.

And I tried it without pagination, same invalid result.

**Comment by mvandeberg** [comment]
`{"jsonrpc":"2.0", "method":"call", "params":["database_api", "get_witness_by_account", ["roadscape"]], "id":1}` works for me on steemd.steemit.com.

When you say "is completely wrong", what do you mean? What response are you expecting?

**Comment by inertia186** [comment]
I'm using an empty string as an argument:

```json
{"jsonrpc": "2.0", "id": 1, "method": "call", "params": ["database_api", "get_witness_by_account", [""]]}
```

**Comment by mvandeberg** [comment]
Ok, so there is not a witness with an empty string name. What is your expected result?

**Comment by inertia186** [comment]
Last week, it would respond with the first *n* witness, up to the limit, even with an empty string.  In other words, it acted like a wildcard.

This week, it's looking for an exact match only.  Got it.  I appreciate you taking the time to look at this.

**Comment by mvandeberg** [comment]
Last week you were probably calling `lookup_witness_accounts`.

**Comment by inertia186** [comment]
Yup, looks like I made a mistake.  Thank you.
