### ISSUE TITLE
Flexible witness parameter operation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1620]
SMT's specify some additional witness parameters.  Rather than add to the existing witness update operation, which requires the user to specify values, it makes more sense to have a `steem_set_runtime_parameter` operation, similar to the SMT version, which allows witnesses to set the desired parameter values without being required to set old parameters.

In particular, this will give us a path to completely deprecate the old operation, which is important because its validation checks are tricky and non-rigorous since they need to support broken past operations which made it into the blockchain in ancient times.

**Comment by mvandeberg** [comment]
I am behind this 100%

Related: 
#352

**Comment by mvandeberg** [comment]
This is now a requirement for 0.20.0
