### ISSUE TITLE
Check Existing SMT Ops for NAI Compatibility

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1622]
Some development was done on SMTs before the decision to use NAIs. Those operations need to be checked for NAI compatibility and updated where needed.

**Comment by vogel76** [comment]
Waits for clarification of doubts inside:
https://github.com/steemit/steem/issues/1554

**Comment by Kiwonik** [comment]
This Issue is being implemented as part of #1554 as separating the code changes would be artificial and only delayed the development. I already incorporated the changes from this issue commits into #1554 commit.
