### ISSUE TITLE
New Steemit Registration Process - Using Mobile Phones

### ISSUE THREAD

**Issue by atomGit** [steemit/steem#1630]
are you KIDDING ME?

> I think it's a positive move on the part of Steemit - what do you think?

well, utter disregard for privacy comes to mind

any social media platform developer that decides to require personally identifying information in light of the surveillance state AND chooses to host in the U.S. isn't worth used toilet paper ... that's what i think

**Comment by TimCliff** [comment]
There are alternative methods of signing up which do not require you to supply any personal information. There are details in the FAQ on Steemit.com.

This issue does not comply with the repository's guidelines for submitting. @sneak to close.

**Comment by nurazhar** [comment]
Use https://anon.steem.network

**Comment by atomGit** [comment]
> There are alternative methods of signing up which do not require you to supply any personal information.

yeah, imagine how popular YouTube would be if you had to pay to create an account

good luck with that

**Comment by nurazhar** [comment]
skin in the game... proof of stake
