### ISSUE TITLE
Implementation of get_next_smt_identifier

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1633]
The whitepaper is written to reflect the user experience of `get_next_smt_identifier`, there are some implementation details to be cleared up.

- The `get_next_smt_identifier()` method will be implemented in the blockchain core and exposed by RPC.
- The `smt_create_operation` evaluator will enforce that the `symbol` field matches the result of `get_next_smt_identifier()`.

It may be noted that we could save a few bytes by omitting the `symbol` field from the operation.  Since the object created by the SMT operation must be referenced in subsequent operations, essentially `symbol` serves as an object identifier.  BitShares has some occasions where blockchain-level object identifiers to be used in subsequent operations, but this was found to complicate client design and was avoided in Steem.

So the reasons include:

- Follow design criterion that blockchain-assigned symbols cannot be user-visible
- In other places where objects might have blockchain-assigned ID's, they are allowed user-assigned ID's instead (for example market order ID's)
- Allows users to easily include subsequent operations that reference a newly created SMT in the same transaction
- Suppose that we launch SMT's with some `get_next_smt_identifier()` algorithm, and then in the future, we eventually change the algorithm of the `get_next_smt_identifier()` operation in a hardfork.  The new code after the hardfork must be able to replay old `smt_create_operation` and understand the SMT symbols they created.  If the `symbol` field is not included in the SMT operation, the old `get_next_smt_identifier()` algorithm must be kept in the source code forever in order to execute past operations during replay.  If the `symbol` field is included in the operation, then when any hardfork change is made to the `get_next_smt_identifier()` algorithm, the old algorithm may be deleted from the source code after the hardfork has occurred.

**Comment by theoreticalbts** [comment]
Issues with above implementation

- Completely untested
- Some of the bit twiddling might be wrong, need to verify by hand that results match intended behavior
- Need to add special handling for unit tests (maybe redefine `SMT_SHIFT_REGISTER_LOOKBACK = 1` when `IS_TEST_NET`)
- Need to write RPC to query which symbols are allowed
- Need to add `FC_ASSERT()` to evaluator to actually enforce that SMT created symbol is one of the allowed symbols
- Need to add wallet support

**Comment by theoreticalbts** [comment]
@mvandeberg asked the following on Slack:

> Have you thought about how to handle `get_next_smt_identifier` races?  Does `get_next_smt_identifier` return the whole set of available identifiers, or just the head of the queue?

Yes, I've thought about it.  One simple mitigation is to return and accept creation of the whole set of available identifiers.

If we consider an attack where the attacker Eve has a better network connection than an SMT creator Alice, Eve can deny service to Alice by observing Alice's attempted SMT registration and then registering the same symbol as Alice.  In practice Alice would repeatedly try to register her SMT until she succeeds or runs out of money / patience.

Eve can also deny service to the whole network by registering the full queue every 128 blocks.  The maximum number of SMT registrations per day (and thus, Eve's cost to deny service by buying them all herself) is determined by  `STEEM_BLOCKS_PER_DAY * SMT_ALLOWED_SYM_BACKLOG / SMT_SHIFT_REGISTER_LOOKBACK = 1800`.  We can increase `SMT_ALLOWED_SYM_BACKLOG` or decrease `SMT_SHIFT_REGISTER_LOOKBACK` to increase the available number of SMT registrations, and thus Eve's cost.  The tradeoff would be allowing users more control over the entropy of the resulting symbol.

**Comment by mvandeberg** [comment]
I think our design requirements have resulted in an impossible system.

They are:

- NAIs are not mineable
- NAIs are deterministically random
- An SMT creator must know their NAI at the time of creation
- Another user cannot deny creation of an SMT to another user

I think a fee of 1 STEEM is too low. 1000 was too high, but perhaps 50-100 STEEM hits the sweet spot.

**Comment by mvandeberg** [comment]
With regards to the NAI reservation process, `get_next_smt_identifier` should return the full list of NAIs. That way if two users are creating SMTs in the same block, there is only a 1/2^14 chance of a collision.

In addition, let's define as part of the NAI reservation interface, a method `smt_reserve_identifier` that accepts an NAI, returns false if the NAI is not valid. Otherwise it removes it from the available list and returns true.

**Comment by theoreticalbts** [comment]
> I think our design requirements have resulted in an impossible system

It's not a logical contradiction, it's a tradeoff.  The two requirements that are actually in conflict are:

> NAIs are not mineable
> A user cannot deny creation of an SMT to another user

As I said in the above post, if we increase `SMT_ALLOWED_SYM_BACKLOG` or decrease `SMT_SHIFT_REGISTER_LOOKBACK` it gets more mineable but costs Eve more to deny service by using all available registrations.

I don't think this attack will actually happen, since Eve would be going to a lot of trouble for no obvious gain.  If it does, then we can mitigate it by raising the fee (which AFAIK is a witness parameter anyway). 
 Or we can tweak the constants to change the tradeoff set-point.

**Comment by theoreticalbts** [comment]
So I have a proposal to deal with the potential denial-of-service vector while not making SMT's very mineable.  So far all the proposals envisioned have had a user able to register any one of `N` available ID's, with a single global `fee` which is the same regardless of which available SMT is registered.

What if instead each of the available SMT's has its own cost, such that the costs are approximately exponentially increasing up to `STEEM_MAX_SHARE_SUPPLY`?  Maybe like this:

| Slot | Fee         | asset_num  |
| ---- | ----------- | ---------- |
|    A |   10   STEEM |   fdef889p |
|    B |   25 STEEM |   f18d0e5p |
|    C |   50   STEEM |   996166dp |
|    D |  100   STEEM |   25a4efbp |
|    E |  250   STEEM |   98b8a9fp |
|    F |  500   STEEM |   ca704c7p |
|    G | 1000   STEEM |   369ca2dp |
| ...  | ...         | ...        |

Of course every `asset_num` has `bit4 = 1` and `bit0-3 = p` where `p` is the precision (decimal places).

Spammers will still be able to churn out low-value SMT registrations as fast as they regenerate.  But that won't stop non-spammy users from getting an SMT immediately by opting to pay for one of the more expensive registrations [1].

[1] Unless it turns out that the spammers are *very* wealthy compared to legitimate users, i.e. if a legitimate user is willing to pay `s` STEEM for a registration, the spammers would have to buy all the registrations below `s` -- whose collective value is about equal to `s` if each entry is about 2x the one above it.  And the spammers would have to pay *over 200 times `s` per day* to deny service (assuming a regeneration time of 128 blocks).

**Comment by theoreticalbts** [comment]
The complexity in my above proposal can be hidden from the user with a well-designed UI.  The UI might work like this:

- Go to the "Create an SMT" page of the UI
- The UI queries the blockchain and pre-fills the "fee" field with the lowest value slot that's available, let's say that's `X` STEEM
- User fills in other fields
- User clicks "Create SMT"
- If the tx fails due to low-cost field having been used, after any tx that's been broadcast has expired it prompts the user "Do you want to try again?  Option 1:  Try again with same fee of `X` STEEM.  Option 2:  Try again with higher fee of `Y` STEEM.  Option 3:  Try again after 6.4 minutes (128 blocks)" where `Y` is the larger of the next highest fee after `X`, and the smallest slot on the blockchain.

This way it's pre-filled with what it will probably actually cost in normal no-spam conditions, and gives the user suggestions about how to mostly-automatically fix the error.

**Comment by mvandeberg** [comment]
One of the key advantages of multiple NAIs is to help avoid race conditions when creating an SMT. So long as the slots encompass multiple NAIs (perhaps 8) then I think this can work.
