### ISSUE TITLE
Rename SMT_MIN_NAI, SMT_MAX_NAI to SMT_MIN_ASSET_NUM, SMT_MAX_ASSET_NUM

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1637]
These names are more descriptive.

**Comment by theoreticalbts** [comment]
Actually in reality it's `SMT_MIN_NAI_DATA_DIGITS`, `SMT_MAX_NAI_DATA_DIGITS`

**Comment by youkaicountry** [comment]
Closing as outdated.
