### ISSUE TITLE
Implement SMT inflation processing

### ISSUE THREAD

**Issue by Kiwonik** [steemit/steem#1638]
This issue requires SMT launch implementation.

It is a continuation of earlier issue that concluded with SMT inflation parameters stored in smt_token_object in pre-setup phase. See #1513

What needs be done:
* Initial inflation event schedule at SMT launch using parameters stored in smt_token_object (if any).
* Per-block processing which executes inflation event and reschedules next event (if any)
* Add constant for minimum inflation event spacing (1 hr?)
* Implement unit test

**Comment by youkaicountry** [comment]
Closing as outdated.
