### ISSUE TITLE
Compile time bounds checking of asset arithmetic

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1646]
See discussion in #1625

**Comment by mvandeberg** [comment]
Copy the discussion here instead of linking to the epic. It is going to take time to read through the thread whenever this particular issue is referenced.

Theoretical:
> AFAIK safe<t> has fixed lower and upper bounds of numeric_limits<T>::min() and numeric_limits<T>::max(). I am thinking that the following new features should be added:
> 
> The lower/upper bounds should be template parameters instead.
> asset / share_type fields used in objects and operations should have lower limit of 0 and upper limit of STEEM_MAX_SHARE_SUPPLY
> Serialization / deserialization does bounds checks
> Arithmetic on assets results in type with template parameters with new different bounds. That is, safe<A,B> + safe<C,D> = safe<A+C, B+D> since if A <= x <= B, C <= y <= D then A+C <= x+y <= B+D. Likewise safe<A,B> - safe<C,D> = safe<A-D, B-C> since if A <= x <= B, C <= y <= D then A-D <= x-y <= B-C.
> You can explicitly convert safe<A,B> to safe<C,D> which adds runtime bounds checks.
> Basically the idea's that by default, the compiler will enforce that code doesn't accept unreasonable values, i.e. negative or greater than STEEM_MAX_SHARE_SUPPLY. Code that manipulates amounts with arithmetic may generate temporary variables that are out-of-bounds, but the compiler will force you to add an explicit runtime bounds check in order to store such a temporary in an object field.
> 
> I want to make it very hard to accidentally write code that accepts input that is negative or unreasonably large.

Vandeberg:
> Having an upper bound of STEEM_MAX_SHARE_SUPPLY is problematic as demonstrated in #1640
> 
> We would need to make the asset type also templated and have well defined semantics when creating prices between assets with different bounds.
> 
> For the record, I do not believe that negates the changes in #1641
> 
> I don't think we need to support cross bounds arithmetic other than in the price class. Arithmetic of assets that have different symbols is already invalid.
> 
> I propose the templated asset type called bounded_asset and templated price type (inferred template parameters for price to preserve existing code) and typedef asset as bounded_asset< 0, STEEM_MAX_SHARE_SUPPLY > and vesting_asset as bounded_asset<> (default to numerical limits).

Theoretical:

> >Having an upper bound of STEEM_MAX_SHARE_SUPPLY is problematic as demonstrated in #1640
>
> Agreed. We should create a new upper bound called STEEM_MAX_SATOSHIS or something.
> 
> >We would need to make the asset type also templated and have well defined semantics when creating prices between assets with different bounds.
>
> I think that it suffices to say price can only be constructed by assets with the global bounds, an asset with any other bounds will require an explicit conversion.

**Comment by youkaicountry** [comment]
Closing as outdated.
