### ISSUE TITLE
steemit address bytes

### ISSUE THREAD

**Issue by davidkevork** [steemit/steem#1650]
I am developing steemphp and i need the bytes which are used by the blockchain
https://github.com/Bit-Wasp/bitcoin-php/blob/2b8220761ef00efae6a80ac7e6938f796dfe4fa8/src/Network/NetworkFactory.php#L24

i cant find those bytes anywhere so that i can use it in the application

**Comment by theoreticalbts** [comment]
It appears you are trying to port some Bitcoin code to Steem.  This is probably not possible.  The Steem blockchain's design has many significant fundamental differences from Bitcoin, the implementation is not based on the Bitcoin code, and most of the serialization formats are not the same as Bitcoin.
