### ISSUE TITLE
Your project is not decentralized or against censorship and claiming they are just to market yourself if shameful

### ISSUE THREAD

**Issue by whatisgravity** [steemit/steem#166]
Steem is not a decentralized platform. None of the developers or members do not care about cenorship. 

Steem is a farse to get money while using decentralization and censorship as a marketing tool. You guys should be ahsamed of yourselves.

You are making it harder for people *actually* working towards these goals to get funding and ruining the meaning of these terms. Your driven by greed and not values.

They changed the code of the client, suddenly had 54% of the network and forked then those nodes disappeared. They use their **closed source** platform to censor things that exist on the blockchain. I did analysis and several posts have been altered from what they were on the blockchain, and not for security reasons but for political reasons.

**Comment by xeroc** [comment]
Content on the blockchain is open, censorship resistant and can be read from anyone that can read the documentation about how to call content via RPC. If you are having difficulties finding that information, I can recommend the tool `piston` that allows to read the unaltered content of the blockchain.

As for the *greed* ruining your business, well, we are living in a world with free markets and obviously Steem is received better than your product. Bad luck? Cheating? I can't answer this, but I know that Steem has implemented a lot of leasons that had been learned from previous projects.

The recent hardfork is in line with the constitution that has been brought to the "community" (most importantly to the witness nodes) quite some time ago.

The hardfork was also in line with the shareholders as they voted for most of the witness nodes.

Finally, I would recommend you read [this fine article](https://en.wikipedia.org/wiki/Non-aggression_principle). 

PS. I am quite sure you are smart enough to understand what the github issue system is usually used for. If you are brave, you could post your comment on Steem and start a discussion about it.

**Comment by ShawnKimble** [comment]
Can you link to the tool "piston"?

**Comment by jl777** [comment]
http://piston.readthedocs.io/en/develop/

**Comment by beyondbitcoin** [comment]
Politics are unavoidable in any system where humans are involved.  The simple fact that tools like this exist show us how much better blockchain based social platforms can be for transparency. 

I personally have changed posts myself because I reread them and realized how they came across wasnt how I intended.  This is kind of a gray area imo because of I want to rephrase comments after the fact, I as a user should be able to do so.  I do, however fancy the idea of being able to show the history of those changes so there is a historical record.  

Gotta love experiments :)

**Comment by theoreticalbts** [comment]
Political debates are off-topic for the bug tracker.
