### ISSUE TITLE
Increase Active Ignored Request Timeout

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1660]
When a node requests a transaction or block, there is a 1 second timeout before disconnecting and asking another peer. We know there are circumstances in which full API nodes can't respond within one second, causing all peers to disconnect from them.

We want to increase this value to 6 to give ample time for the p2p code to respond to the request.

**Comment by theoreticalbts** [comment]
Let's not close this ticket until we've merged PR's for both `master` and `develop`
