### ISSUE TITLE
Fix update_witness to match documentation in cli_wallet

### ISSUE THREAD

**Issue by arhag** [steemit/steem#167]
Documentation of `update_witness` CLI command:
```
gethelp update_witness

Update a witness object owned by the given account.

Parameters:
    witness_name: The name of the witness's owner account. Also accepts the
        ID of the owner account or the ID of the witness. (type: string)
    url: Same as for create_witness. The empty string makes it remain the
        same. (type: string)
    block_signing_key: The new block signing public key. The empty string
        makes it remain the same. (type: public_key_type)
    props: The chain properties the witness is voting on. (type: const
        chain_properties &)
    broadcast: true if you wish to broadcast the transaction. (type: bool)
```

However, if you look at the relevant code (https://github.com/steemit/steem/blob/v0.10.0/libraries/chain/steem_evaluator.cpp#L63-L67 and https://github.com/steemit/steem/blob/v0.10.0/libraries/wallet/wallet.cpp#L1533-L1537 and https://github.com/steemit/steem/blob/v0.10.0/libraries/chain/protocol/steem_operations.cpp#L140) it doesn't actually satisfy the described behavior for `url` and `block_signing_key`.

Personally, I would like to see this fix happen at the consensus level in steemd (included in the next hard-forking change) rather than in cli_wallet. This would reduce the blockchain bloat for most update_witness transactions which are either to change `block_signing_key` to switch over during witness node upgrades (thus not needing to change the `url`) or to update the registration fee in `props` to keep up with the price changes (thus not needing to change either `url` or `block_signing_key`).

In fact, many witnesses may wish to update the registration fee as frequently as the price feed (to maintain a stable dollar value for the registration fee), so there is in fact an argument for spinning off that part of the update_witness operation into its own operation.

**Comment by theoreticalbts** [comment]
For the most part, I just changed the docs to match the behavior. Fixing it at the blockchain level will require a new operation, and should wait until generic witness parameters are updated -- #150 -- so the new operation can get rid of the `props` member as well.

**Comment by theoreticalbts** [comment]
Merged, any blockchain-level improvement discussion should happen on #150.

**Comment by arhag** [comment]
@theoreticalbts: Your change (https://github.com/steemit/steem/commit/3f528503197efdc7d7953fc793390ff00d34dbf2#diff-eba6dcca79f28def3dea11f284600592R1599) would mean a new witness object cannot be created for an existing account. That is the only way a non-mined account can choose to become a witness.

**Comment by theoreticalbts** [comment]
@arhag : Yeah, I guess Steem uses update_witness for creating a witness and doesn't have a separate create_witness command -- which is another way the documentation is misleading.
