### ISSUE TITLE
Trim Account History

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1671]
To keep state smaller, we will only keep 30 days of account history or 30, whichever is more.

If node operators want to keep the current functionality, an option `--history-disable-pruning` will be added which will turn off this behavior.

**Comment by KINGdotNET** [comment]
Yes please keep it slim and small for faster access.
Thank you.

**Comment by steemypete** [comment]
What happens if requesting further, does just send 30 or uses a slower access method to grab and return it?

**Comment by mvandeberg** [comment]
No, this limits the account history accessible via API to 30 days or 30, whichever is more. The API call to access history remains unchanged.

**Comment by KINGdotNET** [comment]
@steemypete I was about to ask the same question. 
Thank you @mvandeberg for a quick answer

**Comment by mvandeberg** [comment]
Pruning can be disabled if you want to run it on your node.

We also have plans to move account history available through our public APIs outside of steemd and will return full account history.
