### ISSUE TITLE
Registration is broken

### ISSUE THREAD

**Issue by mattwkelly** [steemit/steem#1673]
My account was approved and I tried finalizing it:
![screen shot 2017-10-19 at 1 45 14 pm](https://user-images.githubusercontent.com/174449/31793339-d1b69386-b4d3-11e7-9dbc-83735583dc1e.png)

I tried resubmitting:
![screen shot 2017-10-19 at 1 45 22 pm](https://user-images.githubusercontent.com/174449/31793374-e68643a6-b4d3-11e7-9616-9b83bce6c1dc.png)

**Comment by adhood** [comment]
I tried signing up on the 14th and again on the 20th and haven't even received the approval email yet. How long did it take them to approve your account?

**Comment by TimCliff** [comment]
GitHub is not the appropriate place for account support. Please ask for help in the "help" channel of steemit.chat if you are having issues.

**Comment by mvandeberg** [comment]
This is not a steemd issue.
