### ISSUE TITLE
Implement testnet state init / transfer Python scripts

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1677]
This is a ticket for a Python script to initialize testnet state.  Ideally this script would live in its own repo, but for now it can be part of the steem repo.

This script actually has a few different tools, each of which should each be their own script (or perhaps command-line options to a single script if it's easier to code that way).

- The *snapshot tool* will export all necessary query data from the Steem blockchain.  The input to the snapshot tool is an API endpoint, the output is a JSON file containing all relevant data.  For now the data will be of the form `{"accounts" : [ ... ]}` where `[...]` contains all of the account objects on the blockchain.
- The *txlist generator tool* will take as input a config file and a snapshot, and stream on stdout a list of transactions to be executed, without TaPoS or signatures.  More detail about how the txlist generator tool will work is below. 
- The *txlist signer tool* will take as input a config file containing an API endpoint URL and some private keys (testnet only private keys so config file security need not be too paranoid, the worst that a compromise can do is wreck the testnet).  The tool will stream in on stdin a txlist as outputted by the tx generator tool, and stream out on stdout signed transactions with TaPoS / required keys as determined by querying the API endpoint.  Any query cache which is implemented for performance should be tunable and killable by a config file option.
- The *txlist submitter tool* will take as input a stream of signed transactions, and send them to an API endpoint specified by a command line option and/or config file.  Any failure to push a transaction should be logged but ignored.  The submitter tool should have a `generate_block_after_tx_count` option which, when a nonzero value is specified, will call `debug_generate_blocks` to generate a single block every time that many transactions are submitted, and then when `stdin` is exhausted, call `debug_generate_blocks` until the last transaction is irreversible.
- The *txlist port tool* will take as input an API endpoint and block height, and output on stdout all the transactions starting at that block height.  Once the end of the blockchain is reached, it should sleep for ~1 second, then check for a new block.

The tx generator tool should create a list of transactions as follows to initialize testnet state:

- Create `n` different witnesses all with the same block production key as `initminer` as specified in a config file
- Create `m` different accounts which will vote for the witnesses, call these "elector accounts" (they are not special in any way, just normal accounts controlled by us)
- Vest a large amount of Steem to elector accounts
- Have each of the `m` elector accounts vote for each of the `n` witnesses
- Create testnet account for every account which exists in the snapshot file.  Add an extra pubkey specified in the config file to each testnet account's authorities.
- Have each of the `n` witnesses update their block production key to be one of `n` production keys specified in the config file

Then we can string these tools together in classic UNIX fashion to initialize testnet state.  First we use the snapshot tool to export all the accounts.  Then we create a testnet with the `n` production keys divided among some seed nodes (possibly as few as 3 or as many as `n` seed nodes), a normal production node and a debug node to create the initial blocks.  All seed nodes should have the addresses of all other seed nodes in their config files, and the debug node should have address of all seed nodes in its config file.

To create the initial blocks, pipe `generator | signer | submitter` with `generate_block_after_tx_count` and the API endpoint set to the debug node.  The transactions should propagate from the debug node to the seed nodes.  The `debug_push_blocks` call will cause the debug node to create blocks with timestamps in the past, as fast as possible, until the accounts have been created.  Then the block production key update should cause the seed nodes to take over block production using normal witness logic.  Once the seed nodes begin normal block production, the debug node can be shut down permanently.

To start porting transactions from the main network, we can pipe `port | signer | submitter` and use any mainnet API node for `port` and any testnet API node for `signer` / `submitter`, no special plugins are required.

**Comment by vogel76** [comment]
To operate on blockchain should we use this Python library or direct calls to API methods ?
https://github.com/xeroc/piston

**Comment by mvandeberg** [comment]
Steemit has Steem-python which is forked from piston.

**Comment by mvandeberg** [comment]
Clarifications on some of the requirements from conversation with @theoreticalbts 

> The snapshot tool will export all necessary query data from the Steem blockchain. The input to the snapshot tool is an API endpoint, the output is a JSON file containing all relevant data. For now the data will be of the form {"accounts" : [ ... ]} where [...] contains all of the account objects on the blockchain.

For consensus, we only care about their posting authority, which should be set on the test net to owner, active, and posting. Copy the memo key as is. And for compatibility with our stack, also copy the JSON metadata. Normally, I would say we should export the entire set of accounts, but we are talking about hundreds of megabytes if not a gigabyte or two of data. Ideally, this tool should run on the order of seconds to a minute or two to get a test net launched. We should also grab a list of witnesses and set their signing keys to the init miner key. When creating the accounts, the init miner account should be added as an account auth on all authorities with weight equal to the threshold of the authority. This will be used for propagation from the main net to the test net.

> The txlist submitter tool will take as input a stream of signed transactions, and send them to an API endpoint specified by a command line option and/or config file. Any failure to push a transaction should be logged but ignored. The submitter tool should have a generate_block_after_tx_count option which, when a nonzero value is specified, will call debug_generate_blocks to generate a single block every time that many transactions are submitted, and then when stdin is exhausted, call debug_generate_blocks until the last transaction is irreversible.

Proper use of the test net should not require the debug plugin. It is a great tool, but the test net is going to use every aspect. The test net code is currently designed to create blocks starting at `now` with `enable-stale-production` set to `true` to avoid having to set a current seed time or generating old empty blocks to catch up.

I think a lot of this is over complicated. The signed and submitter tool just needs to be a cli wallet pointed at a local node. An initial script should accept a test net key different than the hard coded init miner key. The first thing that should happen is change the authorities of the init miner to the new key (which will be in the config file as well as the cli wallet). Copy over accounts and create witnesses as described above using the cli wallet. This will handle proper TAPOS, expiration, and signing of transactions. If we still want a `signer` and `submitter` process, I would put them together and have that process own the cli wallet process. In this manner you can still launch as `port | signer` while leveraging existing tooling.

For the main net to test net port, blocks off the main net should be read, all comment and vote operations put in new transactions, and submitted to the cli wallet. If a comment and comment options exist in the same trx on the main net, they should still exist in the same trx on the test net. The real exercise is stripping all other ops.

**Comment by theoreticalbts** [comment]
> this tool should run on the order of seconds to a minute or two to get a test net launched

Yes, it should run as fast as possible

> generating old empty blocks to catch up

Part of the idea here is that the debug plugin can generate blocks in the past as fast as possible. 
 If you run the testnet normally, you will only be able to create `maximum_block_size` worth of account creations (and other initialization transactions) every 3 seconds.  But if you force generation of blocks unconnected to real-time using the debug plugin, you can run the initialization tx's as fast as your CPU can go.

Once the initialization transactions are generated, you can shut down the node running the debug plugin, allowing the testnet to run without it.  The debug plugin is only required to force generation of blocks.

**Comment by mvandeberg** [comment]
If we want to launch the test net in this manner, then there is an added requirement to how we do so. We want to start the testnet initializing all hardforks that already happened in the past. There are a lot of constants that exist already to handle our hardforks. It is tedious already and I do not want to add another constant that needs to be updated every release (the more we have the better the chances are that we will forget one). Currently, the system in place is entirely dynamic, relying on the time of the first block to apply the initial set of hardforks.

The debug plugin will need to ensure that the first block generated is after the most recent hardfork time but early enough that it can generate all of these blocks without running into now. And preferably all of this would happen without user intervention. Probably creating the first block at `now() - 1 week` would suffice. I don't think we have the exact tooling in the debug plugin to do this currently, but it shouldn't be hard to create a `debug_generate_block_at_time()` call.

We will also need to figure out a way to bootstrap the debug node. Currently it requires pushing of actual blocks to prime the undo state so it can change keys and what not. I believe if the key you send is identical to the key the witness has, it will skip this step, but we need to validate this behavior.

**Comment by theoreticalbts** [comment]
> Probably creating the first block at now() - 1 week would suffice. 

Sounds like a reasonable default, which we should be able to override somehow.

>  Currently it requires pushing of actual blocks to prime the undo state so it can change keys and what not

I don't understand what you mean by this.

> I believe if the key you send is identical to the key the witness has, it will skip this step, but we need to validate this behavior.

AFAIK you send a private key in the API call, and it needs to match the witness's key so it can sign the block.  TBH the key should probably be moved to the config file.

**Comment by mariusztrela** [comment]
"snapshot tool" - Are account names enough or we want more info about every account ?

**Comment by mvandeberg** [comment]
@mariusztrela I outlined what is needed earlier.

> For consensus, we only care about their posting authority, which should be set on the test net to owner, active, and posting. Copy the memo key as is. And for compatibility with our stack, also copy the JSON metadata. Normally, I would say we should export the entire set of accounts, but we are talking about hundreds of megabytes if not a gigabyte or two of data. Ideally, this tool should run on the order of seconds to a minute or two to get a test net launched. We should also grab a list of witnesses and set their signing keys to the init miner key. When creating the accounts, the init miner account should be added as an account auth on all authorities with weight equal to the threshold of the authority. This will be used for propagation from the main net to the test net.

**Comment by mariusztrela** [comment]
ad. "Yes, it should run as fast as possible"

I have just done test:

I received all accounts( only names, without additional data ) from `shared_memory.bin`.
Locally, i.e from 127.0.0.1

My time:
	real	3m31.282s

My computer:
	8 GB RAM
	i5-7400
	

Question:
	Is good idea to save data from real db to json file and next from json file to another db ?

**Comment by theoreticalbts** [comment]
> Is good idea to save data from real db to json file and next from json file to another db

Yes this is fine, because we are not copying a state file directly.  We are extracting a subset of the data (accounts / balances) and then transforming it (to transaction(s) that can be included in blocks).  It is much easier in terms of developer productivity to use JSON for this.  A faster version could exist in C++, as a plugin that reads the DB directly and creates the transactions immediately.  But it would take longer to write, take longer to iterate on, need to be recompiled and redeployed, and would have fewer people capable of using the source.  Where possible we want to move things out of Steemd, to Python scripts that interface with steemd at arms' length.

**Comment by vogel76** [comment]
https://github.com/steemit/steem-python.git 
does not support RPC calls in `develop` version - some methods referenced in Python are missing:
for example: `get_all_usernames` calls internally database_api::lookup_accounts  .
Other method calls probably will fail too because of changed RPC protocol specification (between develpop & master), ie:
```
print(s.get_account('ned'))

steembase.exceptions.RPCError: Assert Exception:v.size() == 2: method specification invalid. Should be api.method
```
s.get_config()'
steembase.exceptions.RPCError: Bad Cast:Invalid cast from type 'array_type' to Object

Probably we will do own data access iface at python level encapsulating RPC API calls to be in the future switched to fixed steem-python library.

**Comment by mvandeberg** [comment]
Steem-Python has probably not been updated for appbase.

**Comment by theoreticalbts** [comment]
I'm working on that right now :)

**Comment by vogel76** [comment]
Please make clear who should implement this task (testnet helper script) since I am confused. There are more important Ben's tasks we also wait for (ie at least smt-id related functions).

**Comment by theoreticalbts** [comment]
Related PR's:  #1718 #1719 #1720 #1722 #1723
Related `steem-python` PR's:  [86](https://github.com/steemit/steem-python/issues/86) [87](https://github.com/steemit/steem-python/issues/87) [88](https://github.com/steemit/steem-python/issues/88)

**Comment by mvandeberg** [comment]
Related progress #1278

**Comment by youkaicountry** [comment]
@vogel76 :
@theoreticalbts is currently implementing this task, he has a version nearly completed and ready for use.
