### ISSUE TITLE
Balance is not correctly resettet when an account_create_with_delegation_operation failed

### ISSUE THREAD

**Issue by marvin-we** [steemit/steem#1678]
Hello together,

I did some tests for SteemJ and executed an account_create_with_delegation_operation - I've provided all required fields and set the delegation to 0 VESTS and the account_creation_fee to 6 STEEM.

The transaction is accepted by Steem, meaning that I do not receive an error, but the account is not created . I guess this is the case because the delegation needs to be greater than 0?

However, the account is not created and the 6 STEEM are still in my Wallet as expected, which I know because I still have my 7 STEEM I had before executing the operation - BUT if I know try to execute the account_create_with_delegation_operation again, Steem returns an error message saying that I only have 1 STEEM left (I had 7 STEEM at the beginning - 6 STEEM for the failed Operation ==> 1 STEEM).

This is actually not true as I can see in my Wallet that I still have 7 STEEM, because the first Operation was not applied. The only way to make Steem notice my 7 STEEM again I've found was to create a Market order and cancel it again - After this Steem seems to know again that I have 7 STEEM and not 1.

Due to that I guess that there is a problem with resetting the balance if an account_create_with_delegation_operation  was not applied.

Thanks and best regards!

**Comment by TimCliff** [comment]
Can you send the full syntax of the cal you are making and the name of the account that you are using to try and create the account?

**Comment by marvin-we** [comment]
Hay @TimCliff ,

I guess you can find the requested information when you check the user at steemdb: https://steemdb.com/@ray66rus

To reproduce the issue described above simply execute the same operation with the delegation set to 0.

**Comment by TimCliff** [comment]
@marvin-we - it sounds like what happened was the transaction to create the account was not put into a block by the witnesses. If this happens, the node that you sent the transaction to may act as if the transaction was a success, but then shortly after (once the transaction expires without making it into a block), it will reflect the original state. This has occasionally happened with some transactions, and is in the process of being debugged.

**Comment by marvin-we** [comment]
Hay @TimCliff - Exactly, that is also my guess =) 

> This has occasionally happened with some transactions, and is in the process of being debugged.

Thank you for the update - In general this issue is not really ciritical as there is a way to reset everything, but it may help to debug it.

Thanks and best regards!

**Comment by mvandeberg** [comment]
What steemd node are you connecting to to propagate the transactions?

**Comment by marvin-we** [comment]
I am not 100% sure but it was "wss://seed.bitcoiner.me" or "wss://steemd.steemit.com"

**Comment by mvandeberg** [comment]
`account_create_with_delegation_operation` is deprecated. Closing.
