### ISSUE TITLE
Mining Syntax

### ISSUE THREAD

**Issue by ShawnKimble** [steemit/steem#168]
Making use of this command syntax:
./steemd --miner=["uniquename55555","${5JF........FJgs}"] --witness="uniquename55555" --seed-node="52.38.66.234:2001"

I get "bad situation" response

Altering it to (taking out $ and brackets)
./steemd --miner=["uniquename55555","5JF........FJgs"] --witness="uniquename55555" --seed-node="52.38.66.234:2001"

I get
Unexpected char '117' in "uniquename55555"
    {"c":117,"s":"uniquename55555"}
    th_a  json.cpp:433 variant_from_stream

    {"str":"uniquename55555"}
    th_a  json.cpp:478 from_string

**Comment by mvandeberg** [comment]
Use config.ini instead of the command line arguments and see if you get different behavior.

**Comment by abitmore** [comment]
Quotes are needed. Try:
```
./steemd --miner='"uniquename55555","5JF........FJgs"]' --witness='"uniquename55555"' --seed-node="52.38.66.234:2001"
```

**Comment by ShawnKimble** [comment]
I tried abitmore's syntax, but got the following errors:

Error parsing logging config from config file /home/username/steem/programs/steemd/witness_node_data_dir/config.ini, using default config
No idea what the parse error might be in the config, unless the syntax of my private key, but I followed this exactly and only other change was my witness = "username here"
# name of miner and its private key (e.g. ["account","WIF PRIVATE KEY"] )

and then also:

1726083ms th_a       witness.cpp:165               plugin_initialize    ] 7 bad_cast_exception: Bad Cast
Invalid cast from string_type to Array
    {"type":"string_type"}
    th_a  variant.cpp:537 get_array

**Comment by abitmore** [comment]
@ShawnKimble sorry there is a typo in my last message (missed a `[`). It should be:
```
./steemd --miner='["uniquename55555","5JF........FJgs"]' --witness='"uniquename55555"' --seed-node="52.38.66.234:2001"
```

**Comment by theoreticalbts** [comment]
This is not a bug, but a support issue -- if we start using this issue tracker for support, we'll never get anything done.
