### ISSUE TITLE
Integrate SMT's with market

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1683]
The order creation operations `limit_order_create_operation` and `limit_order_create2_operation` should be extended to support SMT's.

We need to check the matching engine works properly when the `multi_index_container` for orders contains orders with multiple assets.  It *should* work but it hasn't been reviewed or tested.

- [ ] Adjust `limit_order_create_operation` and `limit_order_create2_operation` `validate` methods to allow SMTs on  `amount_to_sell`

- [ ] Extend operation tests by SMT based scenarions (`limit_order_create2_operation` specific)

- [ ] Extend operation_tests, operation_time_tests, market_history by SMT based scenarios (`limit_order_create_operation` specific)

- [ ] Create wallet_api tests related to `create_order`method

**Comment by youkaicountry** [comment]
Testing the matching engine has been moved to issue #1814.

**Comment by vogel76** [comment]
@youkaicountry Does limit_order_create2_operation is still effectively used ? limit_order_create_operation object is created in wallet module, but limit_order_create2_operation don't...

**Comment by youkaicountry** [comment]
@vogel76 Good question, actually it seems that both should be maintained. I'll go ahead and modify the issue description to list both.

**Comment by vogel76** [comment]
@youkaicountry Both operations require the `min_to_receive` or `exchange_rate` to be specified in STEEM or SBD. Does it is still true also for SMT ? Maybe these parameters shall be specified also in other SMTs ?

**Comment by vogel76** [comment]
@youkaicountry Although modifying operation_tests probably is not big problem for us (just asset symbol must be changed) I'd like to ask for preparing description of wallet_api scenario using create_order, to be able to correctly verify state after executing the order. Also case when order expires could be valuable.
Maybe let's create separate issue for such API test and link them in this issue description at proper task-item place.

**Comment by youkaicountry** [comment]
@vogel76 Market orders will always be between SMTs and STEEM, never between two types of SMTs.

I'll create issues for the create_order tests with descriptions later today.

**Comment by vogel76** [comment]
@youkaicountry We have adjusted one of existing tests to also operate on SMTs and there is a problem related to iteration order from `[limit_order_index, by_price]` index . As I see the comparison ops of `price` class depend on asset-symbols which define the price. The problem is that when we are trying to iterate over `by_price` contents, original order is changed depending on `max_price` we are looking for and  `sell_price` held in `limit_order_object` (this is an effect of asset_symbol_type comparison). Does it is correct to process in the `database::apply_order` method only limit_order_objects having their `sell_price` expressed in exact asset_symbol_types as processed `new_order_object` ? 
If not, how we should achieve correct ordering of processed objects (now such changed processing order leads this test to fail).

**Comment by theoreticalbts** [comment]
There are two "sides" of orders, "buy SBD order" (you give STEEM, you get SBD) and "sell SBD order" (you give SBD, you get STEEM).

To add support for SMT's, we similarly have two sides, "buy SMT order" and "sell SMT order".

An order can only match against an order of the opposite side.  So a buy order can only match against a sell order, a sell order can only match against a buy order.

Buy orders and sell orders are represented in the same `multi_index_container`.  How does this work?

A "buy SBD order" can be considered a "sell STEEM order."  If we think about it this way, there is only one kind of order, a "sell order."  Some orders are selling SBD for STEEM, other orders are selling STEEM for SBD, these two are opposite sides and can match against each other.

So the asset you're selling is the `base` member of the `price` structure, as shown [here](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/protocol/steem_operations.cpp#L435-L446).

When matching an order, you have to [look for matches on existing orders that are the "flipped" price](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/chain/database.cpp#L3199-L3219), which is conveniently implemented by [overloading](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/protocol/include/steem/protocol/asset.hpp#L143) the `~` operator.

So let's say STEEM is trading at $2.  Alice places an order to sell 360 SBD for 180 STEEM.  Then `bob_order` places a matching order, sell 160 STEEM for 300 SBD.  From Bob's point of view, Alice's order is *better* than *the worst price Bob would accept*.

We then have the following orders:

```
alice_order.exchange_rate.base = 2 SBD
alice_order.exchange_rate.quote = 1 STEEM
bob_order.exchange_rate.base = 1 STEEM
bob_order.exchange_rate.quote = 1.875 SBD
```

Alice and Bob's orders fill against each other, it may be informative to look at the code in [apply_order](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/chain/database.cpp#L3199-L3219) and the [price comparison operators](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/protocol/asset.cpp#L368-L378).

For prices `a, b`, the comparison operator code implements:

- If `a`, `b` have different symbols, then `a < b` if `std::tie( a.base, a.quote ) < std::tie( b.base, b.quote )`
- If `a`, `b` have identical symbols, then `a < b` if `b.quote * a.base < a.quote * b.base`, which can be re-written as `a < b` if `a.base / a.quote < b.base / b.quote`

Sorry for the long rambling post.  Did I answer your question?
