### ISSUE TITLE
Change github steemit repo description, It is not technically accurate and misleading.

### ISSUE THREAD

**Issue by Transisto** [steemit/steem#1696]
![image](https://user-images.githubusercontent.com/388716/31947836-421ed296-b8a3-11e7-848d-f5896c25863d.png)

**Comment by Gandalf-the-Grey** [comment]
It's different now:
![github_steemit](https://user-images.githubusercontent.com/6341057/35465529-027cc8d8-02fd-11e8-8e2e-92452a1d99aa.png)
