### ISSUE TITLE
Modify Block Log for Parallel Access

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1698]
The block log is not designed for parallel access.

It has an fstream for  blocks and an fstream for the index file. When a read or write occurs, if it is in the wrong mode (read/write) is closes and reopens the fstreams in the correct mode. However, it allows multiple reads at the same time will will change in the internal pointers and result in undefined reads.

This needs to me modified so that the read calls use stack allocated fstreams.

This introduces some inefficiencies when multiple reads are done from the same thread, but removes race conditions from parallel reads.

**Comment by theoreticalbts** [comment]
If we want to access the block log file from multiple threads, we should use OS / Boost low level I/O.  The stdlib streaming API does buffering, which is bad for multiple threads.

I would say all effort that goes into the block log should go into a rewrite, see #844.

**Comment by mvandeberg** [comment]
The primary concern here is to get develop live without seg faulting the nodes. We can optimize later.
