### ISSUE TITLE
Mac version of cli_wallet doesn't make any logs to rpc.log

### ISSUE THREAD

**Issue by songproducer** [steemit/steem#171]
cli_wallet is not running properly and without any logs it makes it impossible to debug.

When I run cli_wallet this is the full output:
Leos-MacBook-Pro:cli_wallet leotreasure$ ./cli_wallet 
Logging RPC to file: logs/rpc/rpc.log
Starting a new wallet
456400ms th_a       main.cpp:154                  main                 ] wdata.ws_server: ws://localhost:8090 

There is no file on my laptop called rpc.log

**Comment by alexant123** [comment]
same problem. Any suggestions?

**Comment by abitmore** [comment]
No `rpc.log` file on Ubuntu either. Leave this alone, probably the connection issue can be fixed by starting `steemd` with a parameter `--rpc-endpoint=127.0.0.1:8090`, or set that parameter in `config.ini` (it's commented out by default).

**Comment by sneak** [comment]
Suggestion (without testing): try `mkdir -p logs/rpc` before running `cli_wallet` to see if having the directory it expects `rpc.log` to be written to helps.

**Comment by mvandeberg** [comment]
Closing. Won't fix.
