### ISSUE TITLE
Content cannot be edited after 7 days

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#1714]
Issue https://github.com/steemit/steem/issues/1266 was supposed to allow the editing of content older than 7 days after using `enable_content_editing` json with the active key. This still is not working. Could a change be made to just allow editing of all posts with just the posting key? If not, can `enable_content_editing` be fixed?

**Comment by aaroncox** [comment]
Adding my support to this - would really like to see this resolved.

**Comment by ap444** [comment]
so was this modification ever made?

**Comment by mvandeberg** [comment]
Yes, but we have not made a release on this branch since it was merged.

**Comment by ap444** [comment]
sorry, i dont understand. could you put it in simple terms please?

**Comment by mvandeberg** [comment]
The next release will contain this change.

**Comment by ap444** [comment]
thank u. Are u aware of an estimated time for the release?

**Comment by mvandeberg** [comment]
Soon

**Comment by ap444** [comment]
thank u

**Comment by armaccloud** [comment]
Hi @mvandeberg 
Has this issue been implemented? I cannot see how to edit a post after 7 days.

**Comment by mvandeberg** [comment]
It will be active after the next hardfork. I do not have a date for when that will be.
