### ISSUE TITLE
Full Node Sync is very slow after HF19

### ISSUE THREAD

**Issue by moisesmcardona** [steemit/steem#1727]
Syncing with Steemd v0.19.2 and having all the plugins activated, the sync goes up to HF19 at a decent time, but then seems to do 100,000 blocks every 3 hours approximately. At the current block height, it is a pain as this means that the replay could take several days.

The process is using 100% of a CPU thread as expected.

**Comment by sens2** [comment]
There was an exponential increase in activity and thus transactions around that time. You'll notice the first million blocks are so are super fast, when there were probably a few hundred active users. Also, things slow down exponentially if you've run out of RAM and swapping to disk etc. I'd say a full node requires RAM or at least Optane for best results. It should be possible to run on RAM + nVMe RAID swap, but yes, the initial sync will take time in that case.

**Comment by relativityboy** [comment]
Good explanation.
