### ISSUE TITLE
Error loading peer node IP addresses when mining

### ISSUE THREAD

**Issue by ShawnKimble** [steemit/steem#173]
1844622ms th_a       application.cpp:349           startup              ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: Invalid argument
Invalid argument: error converting string to IP endpoint
    {"what":"Invalid argument"}
    th_a  ip.cpp:84 from_string

    {}
    th_a  application.cpp:130 reset_p2p_node

Solution?

**Comment by mvandeberg** [comment]
Can you post your config.ini without private keys?

**Comment by ShawnKimble** [comment]
# Endpoint for P2P node to listen on
p2p-endpoint = seed.steemd.com:34191

# Maxmimum number of incoming connections on P2P endpoint
# p2p-max-connections = 

# P2P nodes to connect to on startup (may specify multiple times)

#seed-node = 52.38.66.234:2001
#seed-node = 52.37.169.52:2001
#seed-node = 52.26.78.244:2001
#seed-node = 192.99.4.226:2001
#seed-node = 46.252.27.1:1337
#seed-node = 81.89.101.133:2001
#seed-node = 52.4.250.181:39705
seed-node = steemd.pharesim.me:2001
seed-node = seed.steemed.net:2001
seed-node = steem.clawmap.com:2001
#seed-node = seed.steemwitness.com:2001
#seed-node = steem-seed1.abit-more.com:2001
# Pairs of [BLOCK_NUM,BLOCK_ID] that should be enforced as checkpoints.
# checkpoint = 

# Endpoint for websocket RPC to listen on
# rpc-endpoint =  

# Endpoint for TLS websocket RPC to listen on
# rpc-tls-endpoint = 

# The TLS certificate file for this server
# server-pem = 

# Password for this certificate
# server-pem-password = 

# Block signing key to use for init witnesses, overrides genesis file
# dbg-init-key = 

# API user specification, may be specified multiple times
# api-user = 

# Set an API to be publicly available, may be specified multiple times
public-api = database_api login_api

# Plugin(s) to enable, may be specified multiple times
enable-plugin = witness account_history

# Defines a range of accounts to track as a json pair ["from","to"] [from,to)
# track-account-range = 

# RPC endpoint of a trusted validating node (required)
trusted-node = seed.steemd.com:34191

# Track market history by grouping orders into buckets of equal size measured in seconds specified as a JSON array of numbers
bucket-size = [15,60,300,3600,86400]

# How far back in time to track history for each bucket size, measured in the number of buckets (default: 5760)
history-per-size = 5760

# Defines a range of accounts to private messages to/from as a json pair ["from","to"] [from,to)
# pm-account-range = 

# Enable block production, even if the chain is stale.
enable-stale-production = false

# Percent of witnesses (0-99) that must be participating in order to produce blocks
required-participation = false

# name of witness controlled by this node (e.g. initwitness )
witness = "steem8reddit"

# name of miner and its private key (e.g. ["account","WIF PRIVATE KEY"] )
miner = ["",""]

# Number of threads to use for proof of work mining
mining-threads = 2

# WIF PRIVATE KEY to be used by one or more witnesses or miners
# private-key = 

# Account creation fee to be voted on upon successful POW - Minimum fee is 100.000 STEEM (written as 100000)
# miner-account-creation-fee = 

# Maximum block size (in bytes) to be voted on upon successful POW - Max block size must be between 128 KB and 750 MB
# miner-maximum-block-size = 

# SBD interest rate to be vote on upon successful POW - Default interest rate is 10% (written as 1000)
# miner-sbd-interest-rate = 

# declare an appender named "stderr" that writes messages to the console
[log.console_appender.stderr]
stream=std_error

# declare an appender named "p2p" that writes messages to p2p.log
[log.file_appender.p2p]
filename=logs/p2p/p2p.log
# filename can be absolute or relative to this config file

# route any messages logged to the default logger to the "stderr" logger we
# declared above, if they are info level are higher
[logger.default]
level=warn
appenders=stderr

# route messages sent to the "p2p" logger to the p2p appender declared above
[logger.p2p]
level=warn
appenders=p2p

**Comment by ShawnKimble** [comment]
Commenting out the p2p-endpoint seems to resolve the issue, but it is normal to get startup to list?
Is it syncing?

Adding seed node 176.9.85.102:2001
Adding seed node 54.191.118.123:2001
Adding seed node 109.74.206.93:2001
Configured p2p node to listen on 0.0.0.0:43666
starting plugins
witness plugin:  plugin_startup() begin
Launching block production for 1 witnesses.
Starting mining...
witness plugin:  plugin_startup() end
Started witness node on a chain with 0 blocks.

**Comment by abitmore** [comment]
> Commenting out the p2p-endpoint seems to resolve the issue, but it is normal to get startup to list?
Is it syncing?

You should use your own IP address or 0.0.0.0 in `p2p-endpoint`. 

You can connect a cli wallet to it to check if it's syncing, with command `info`.

**Comment by theoreticalbts** [comment]
Yeah, p2p-endpoint needs to specify an interface and port to listen. If you don't know what to pick, use 0.0.0.0:2001

There is no bug here.
