### ISSUE TITLE
Diagram flow from whitepaper - update.

### ISSUE THREAD

**Issue by mariusztrela** [steemit/steem#1730]
Diagram flow from whitepaper is obsolete. Here is a updated version that includes all changes as we understand them. It includes the changes proposed in #1680 
Is this how you imagine this flow?

![diagram2](https://user-images.githubusercontent.com/30412612/32229778-f03ca656-be51-11e7-84d6-50f4cecbfeb4.png)

**Comment by mariusztrela** [comment]
Above diagram includes changes from #1680

**Comment by theoreticalbts** [comment]
The actual flow looks good, but there are a few consistency / spelling issues in the names:

```
setup phase -> setup_phase
pre_contribution_pause -> pre_contribution_phase
have -> Have
min steam -> min_steem
fail phase -> fail_phase
active phase -> active_phase
```

**Comment by youkaicountry** [comment]
The flow definitely seems good, and this is a very nice diagram to reference.

**Comment by nedsteem** [comment]
nice work - once this is resolved, please make sure we complete a pull request to update the SMT Whitepaper @mauriusztrela

**Comment by Kiwonik** [comment]
Here's a pull request in smt-whitepaper corresponding with this issue, waiting to be merged: https://github.com/steemit/smt-whitepaper/pull/172

**Comment by Kiwonik** [comment]
Merged in SMT whitepaper repo.
