### ISSUE TITLE
Testnet should die a certain time / height after genesis

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1732]
Let's make sure any testnet is short-lived by adding a testnet-only consensus rule to forbid blocks above a certain time / height.

**Comment by mvandeberg** [comment]
Let's do 3,000,000 blocks. That gives us 3 months of test net "runway". I don't think we would ever need that much, but as I understand the ticket, the purpose is just to put an automatic kill switch in the test net.

**Comment by vogel76** [comment]
@youkaicountry What does it mean that test net has to be killed ? I suppose it shall be impossible to start it again (ie block production shall be disallowed), but definitely we need more details.

**Comment by youkaicountry** [comment]
@vogel76 The testnet should simply stop producing blocks after the "time of death".
Something similar to:
`FC_ASSERT( block.block_num() < TESTNET_BLOCK_LIMIT )`

**Comment by mvandeberg** [comment]
> Let's do 3,000,000 blocks. That gives us 3 months of test net "runway".

**Comment by youkaicountry** [comment]
Sure, we should probably expose that in some configuration?

**Comment by mvandeberg** [comment]
No, bake it in. The point of this is that we don't want runaway test nets. 3 months is plenty of time for a test net. I doubt we'll let one live that long anyway.

**Comment by mvandeberg** [comment]
If we want to make it a constant in `config.hpp` so it can be tweaked easily, that is fine. But it should not be user configurable.

**Comment by youkaicountry** [comment]
We're on the same page, I think. The TESTNET_BLOCK_LIMIT I proposed should be a constant in config.hpp, set initially to 3,000,000.

**Comment by vogel76** [comment]
I suppose this check shall be added to:
`bool database::_push_block(const signed_block& new_block)`
?

**Comment by youkaicountry** [comment]
Putting it there should stop block production, so go ahead and add it there.
