### ISSUE TITLE
cli_wallet is not functional

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1734]
I am trying to use `cli_wallet` on the `theoretical-testnet` branch, but the wallet is non-responsive.

- Is this a problem on `develop`?
- How do we fix it?

**Comment by mvandeberg** [comment]
I will need to investigate, but it worked on the testnet branch I was working on.

**Comment by theoreticalbts** [comment]
Closing.  The problem is that the wallet needs steemd to run the RPC server and cannot talk to the HTTP server.
