### ISSUE TITLE
Inconsistency between name_to_asset_symbol and asset_symbol_type

### ISSUE THREAD

**Issue by Kiwonik** [steemit/steem#1738]
The method `database_fixture::name_to_asset_symbol` we're supposed to be using when testing SMT generates symbols that are rejected by `asset_symbol_type::validate` (assertion fails at `nai_data_digits <= SMT_MAX_NAI` condition).
Sample arguments to `name_to_asset_symbol` that trigger the problem:
"0", 0
"d2", 1
"da1", 1
I'm stopping expanding SMT tests until this inconsistency is fixed or better yet the target method `get_next_smt_identifier` is finally delivered.

**Comment by youkaicountry** [comment]
This has now been resolved in PR #1791
