### ISSUE TITLE
Question: Using one private signin key on multiple nodes. What harm to the network? over production?

### ISSUE THREAD

**Issue by vikxx** [steemit/steem#1741]
Suppose I want 3 (witness only plugin) nodes to work at the same time. 
All three nodes perform only one function - signing the blocks for only one account, with same signin key.
(Each node's `config.ini` specifies same private key & login. And public key declared with an `witness update` call)

This is more convenient than using some keys switcher script. 
But I don't know about consequences of this signin mode.

I'm testing on two nodes for about a day and do not see any problems. 

Server №1 (it's from golos blockchain block height, don't be confused)

![image](https://user-images.githubusercontent.com/26347159/32391440-c0808640-c0da-11e7-953e-8f77c1330ca4.png)

Server №2 

![image](https://user-images.githubusercontent.com/26347159/32391447-c81e68ea-c0da-11e7-9f40-1812f3a864ff.png)

I suppose if one node is down, then second will continue to sign blocks and will nothing not be missed.

Did I miss something? Or is this normal?

## PS
over production op. is currently disabled
```
void report_over_production_evaluator::do_apply( const report_over_production_operation& o ) {
   FC_ASSERT( false, "this operation is currently disabled" );

```

**Comment by TimCliff** [comment]
This is called double producing, and should not be done. The users in the #witness channel of Steemit chat can explain more if you have further questions.
