### ISSUE TITLE
Apply all hardforks in the past at genesis

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1747]
Right now we have two competing implementations of this functionality, both of which break things:  #1723 and the [1278-steemit-testnet branch](https://github.com/steemit/steem/tree/1278-steemit-testnet).

In the case of #1723, it is not usable without #1722 which breaks many unit tests.

In the case of the branch,

- No PR has been created from this branch, so its developers do not consider it ready to merge
- It fails CI (but only one test)
- It contains unrelated changes (mostly configuration constant changes)

So I'm going to write a clean PR to do pre-update at genesis

**Comment by mvandeberg** [comment]
Should have been closed a year ago.
