### ISSUE TITLE
Discount Account Creation

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1771]
Creating an account normally requires matching the account creation fee. A discounted account will always have a fee of 0 STEEM. If an account is created in this matter, a discounted account creation token should be consumed and fail if no tokens remain.

**Comment by mvandeberg** [comment]
Any account creation that consumes the account creation fee or greater should not consume a discount token. Any account creation that has a fee less than the account creation fee should consume a token and fail if a token does not exist. In this manner accounts can be created cheaply, but not infinitely and account creation is never prevented via the full fee.

**Comment by mvandeberg** [comment]
Discount account creation will consist of two operations:

``` c++
struct claim_account_operation
{
   account_name_type creator;
   asset             fee;
   extensions_type   extensions;
};
```

``` c++
struct create_claimed_account_operation
{
   account_name_type creator;
   account_name_type new_account_name;
   authority         owner;
   authority         active;
   authority         posting;
   public_key_type   memo_key;
   string            json_metadata;
   extensions_type   extensions;
};
```

The first op will claim an account from the discount pool to the creator. This account can be created later at any time with the second op. If the fee is greater than or equal to the account creation fee, an account is claimed without taking from the discount pool.

The second op consumes a claimed account from the creator to create the account object which is able to transact.

Combining these two operations with the temp account as creator satisfies anonymous account creation. Combining them with any other account works identically to the `account_create_operation` currently in use. However, because of the added extensions field, any potential changes to account creation will likely require this operation flow.

**Comment by theoreticalbts** [comment]
There are three related issues in here:

- Implement the operations (this issue)
- Implement hard (consensus) limiting #1770 
- Implement soft (non-consensus) limiting #1772
