### ISSUE TITLE
Implementation of claim_smt_identifier

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1777]
Proposed in Issue #1633 and #1554. 
The `claim_smt_identifier` method should take a reference to the database and an NAI, and will return true on a valid NAI, and false otherwise.

**Comment by mvandeberg** [comment]
This is referenced as a solution to SMT creation. The idea as brought up in #1633 is an internal method, not an operation. Using this as a solution to #1795 changes the spec of this method.

**Comment by youkaicountry** [comment]
We're going to use TaPoS to solve the issue of atomic SMT creation (#1795), so this is no longer needed.
