### ISSUE TITLE
Implement smt_test_give_balance_operation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1778]
A test operation to be useable on a test network only, never in production.
This operation will take an account and a balance for an SMT, and should add that balance to the account.

Related to #1681

**Comment by vogel76** [comment]
@youkaicountry Does we really need such operation ? I thought supplying SMTs to the account will be done via some hardcoding (in the code creating the account) in testnet. It should be much simplier than implementing an operation, next evaluator for them which finally will set given amount of SMTs to the account. What just call to database::adjust_balance(account_object, asset) is not satisfying testnet needs ?

**Comment by mvandeberg** [comment]
I am going to jump in here and say that we should not implement this with a testnet only op.

I was tempted to do so when we first implementing Steem. Instead, what you should do, is create a helper method in the database_fixture (or extend the existing `fund` method). Those methods use the debug node to modify objects directly in a manner that preserves state through block production.

**Comment by youkaicountry** [comment]
The problem we are trying to solve is that currently we are missing the ICO/contribution phase, which in the final form will be how users obtain SMTs. But we want to test SMT operations on the testnet before we have ICOs.
The problem I see with database_fixture in this case is that those methods are only available for unit testing, which won't help us here.
@vogel76 brings up an interesting solution.
My proposal to this problem is to use `database::adjust_balance` in the SMT creation operation to confer a reasonably sized initial balance to the account which created it. This account can then transfer SMTs to other users for test purposes.

**Comment by mvandeberg** [comment]
Until there is something to control, I don't think SMTs need a control account.

I recommended in our meeting today that during genesis we can create a couple SMTs and a large balance to init miner. Then, we accounts are copied over to the test net, we can fund them with some SMTs from the init miner balance. All of this can be done without adding an extra op.

Alternatively, the `smt_create_operation` could short circuit the ICO phase an grant the creator a large balance exactly as you described above. But I would rather do that via a stubbed op that will eventually exist on the main net.

**Comment by youkaicountry** [comment]
@mvandeberg We'll go with your suggestion. I'll close this issue and open a new one.
