### ISSUE TITLE
Suggestion - Sort in Real Time

### ISSUE THREAD

**Issue by hdmed** [steemit/steem#1780]
# Suggestion - Sort in Real Time
![Moroccan Community   teammorocco  — Steemit.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510926296/bolj3qzfdd5p02ubsnaa.png)

We like to see in our blog, a drop-down list that allows to sort posts, by different criteria like:
- By date
- By number of views
- By number of votes
- By rewards value
- By number of comments
- And of course from A to Z and from Z to A.
## Like that of YouTube.
![37  TeamMorocco   YouTube   YouTube.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510926557/xkuu3fmht4azobfq6esv.png)

**Comment by mvandeberg** [comment]
This is an issue for [steemit/condenser](https://github.com/steemit/condenser). Closing
