### ISSUE TITLE
Signed up on steemit.com but did not receive the verification code via SMS

### ISSUE THREAD

**Issue by hjbaptiste** [steemit/steem#1799]
I signed up with the account name "erv" and provided email address and phone number but never received the verification code.  When I try to sign up again it tells me that the account name is not available.  Can the verification code be sent out to me again?  I don't understand why there isn't a way for users who are signing up to request another verification code.  The code may have not been delivered or the user could have lost their cell phone or their cell phone may have been temporary de-activated.  Whatever the reason it seems to make good user experience to provide such a feature.  This could be for any other part of the sign up process like receiving an email confirmation.  How can a user request that the email be resent?  These negative user sign-up experiences don't take place on non-blockchain social media sites.  If Steemit wants a wider adaptation similar to it's non-blockchain counterparts, it needs to ensure a simple and forgiving sign up process.  

Someone working at Steemit please resend my verification code.  It's been about 3 months now. Sheesh!!
![steemit account name erv not available](https://user-images.githubusercontent.com/8689865/33149849-3c52c3fa-cf9f-11e7-892a-f9556bec2499.png)

**Comment by goldibex** [comment]
I agree with you here @theoreticalbts - setting support expectations is important. We'll post an answer here in pretty short order.

**Comment by BonfaceKilz** [comment]
I've put in my phone number but I did not get the SMS confirmation code. Kindly help out on this.

**Comment by TimCliff** [comment]
@BonfaceKilz please ask for help in the steemit.chat help channel.

**Comment by andela-sjames** [comment]
Not sure why, but same has been happening to me

**Comment by mvandeberg** [comment]
The account sign up and verification process is separate from steemd, so I am closing this issue.

**Comment by anantanandgupta** [comment]
Ihave not received any sms code tried 3 mobiles from different countries but no luck ... After a few attempts it even stopped taking me to the verification code screen itself ... Posting the mobile number simply started returning 400 error.

**Comment by TimCliff** [comment]
@anantanandgupta the place to ask for help is in the help channel of steem chat.

**Comment by sam4jips** [comment]
It's definitely broken... not working for me... i have tried with three different working numbers and yet I did not receive a code for even one of them...

**Comment by TimCliff** [comment]
@sam4jips please ask for help in the help channel of steem chat.

**Comment by kapilip** [comment]
@TimCliff Confirmation code isn't working at all. I have asked for help in chat but there's no response there as well. can you help?

**Comment by TimCliff** [comment]
As it says in the pinned messages, responses should be given within 24 hours.

**Comment by vishalhkothari** [comment]
Cant get the code on my phone

**Comment by TimCliff** [comment]
@vishalhkothari please ask for help in the help channel of steem chat.

**Comment by kapilip** [comment]
@vishalhkothari I think you need to deactivate your 'DND' option on your mobile to get the code. I used the same trick and it worked for me.
