### ISSUE TITLE
Lack of a `create_witness` API?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#18]
Lack of a `create_witness` API?

**Comment by abitmore** [comment]
Looks like it's able to create a witness with the `update_witness` command. Related code is [here](https://github.com/steemit/steem/blob/04695ac64019213f5834b3f4510db7db26297217/libraries/chain/steem_evaluator.cpp#L64-L93)

**Comment by bytemaster** [comment]
Correct, update witness is the call to use.
