### ISSUE TITLE
Change default asset registration fee to STEEM

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1802]
To simplify testing, let's change the default asset registration fee from SBD to STEEM, at least for now.

**Comment by mvandeberg** [comment]
The `database_fixture` has helper functions to establish a price feed and give an account SBD.

See `set_price_feed` and `fund`.

For the test net we should brainstorm ideas for creating an SBD supply that can be played around with.

**Comment by youkaicountry** [comment]
Closing as outdated.
