### ISSUE TITLE
Discussion: Vesting SMT Symbols

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1819]
We have a small problem with the current NAI scheme for SMT Power.

For STEEM and Steem Power we have the symbols STEEM and VESTS.

For SMTs we only have the NAI. Most operations do not have SMT and SMT power at the same time or when they do, we can have the vesting field and liquid fields specified in the op.

The exception to this is the claim rewards operation. The simplest implementation for the op is a vector of assets. Each asset is checked against the relevant reward balance and claimed. It is a simple and elegant solution for claiming arbitrary reward balances. But it lacks a way to distinguish between SMT and SMT power using the NAI scheme.

We need to figure out what the best solution to this problem is.

I propose the following potential solutions:

1) Repurpose one bit of the NAI to distinguish liquid SMT vs vesting SMT. This has the advantage that knowing one of the symbols means you know the other symbol.

2) When an op would contain liquid and vesting SMTs, we create two ops. One for the liquid SMT and one for vesting SMT and use the same NAI for both, relying on the field description to define the behavior of the asset. So far, I think only the claim reward op runs into this problem.

I am personally in favor of solution 1. I think we have a large enough NAI space. Halving it should not be significant. Additionally, assets are implemented in such a way that prevents addition between assets with different symbols. If vesting and liquid SMTs have the same symbol type, then we can run code that operates on the assets. It is not a hard requirement, but adds a layer that significantly reduces our chances of writing buggy code.

**Comment by theoreticalbts** [comment]
I've thought about this, and repurposing a bit would work.  But of course that means someone needs to go into the NAI parsing code and change it.

**Comment by youkaicountry** [comment]
Let's go with repurposing a bit to represent SMT power.
