### ISSUE TITLE
Test fixture convert method can produce negative balance

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1825]
[Here](https://github.com/steemit/steem/blob/57ccef79989e5fd8a24fdf46a21b0df5bb91f7d2/tests/tests/smt_tests.cpp#L328-L329) a test funds an account with five *thousand* satoshis of STEEM, then attempts to convert five *million* satoshis to USD using the `convert()` [method](https://github.com/steemit/steem/blob/57ccef79989e5fd8a24fdf46a21b0df5bb91f7d2/tests/db_fixture/database_fixture.cpp#L450-L453) of the database fixture.  The database fixture method, unlike (for example) the [transfer operation](https://github.com/steemit/steem/blob/57ccef79989e5fd8a24fdf46a21b0df5bb91f7d2/libraries/chain/steem_evaluator.cpp#L691-L692), does not check that sufficient funds occur, and happily converts 5,000,000 satoshis, leaving a balance of `-4995.000 STEEM`.  We may verify this by adding `wlog()` immediately after the `convert()` call:

```
// we print the amount, because printing an asset will trigger validate() which causes an exception
wlog( "Balance: ${b}", ("b", db->get_balance("dany", STEEM_SYMBOL).amount) );
```

Really the right fix is to leverage templates to allow the compiler to enforce non-negative balances wherever possible #1646 , but a simpler, more immediate mitigation strategy is to add a sufficient funds check to `adjust_balance()` #1811.

To fix this issue, we need to do the following:

- (a) Change `convert()` to throw an exception when a user converts more than the user holds
- (b) As a result of (a), the `set_setup_parameters_apply` test now fails
- (c) Fix the `set_setup_parameters_apply` test to fund `dany` with 5,000,000 STEEM satoshis, as the original author clearly intended
- (d) Create a new test that attempts to convert too many SBD and checks that an exception is thrown, meaning future regressions against (a) will fail

So far (a) and (b) are already by PR #1812, which fails CI.  Even though the problem here is a separate issue from #1811 (the issue that PR is trying to solve), it makes more sense to fix this issue in PR #1812 because:

- PR #1812 is halfway to resolving this issue already, it makes no sense to add balance checks to `convert()` just to take them out again because they are made redundant by #1812
- PR #1812 needs this issue fixed to pass CI

**Comment by youkaicountry** [comment]
Closing as outdated.
