### ISSUE TITLE
Remove Appbase Lock Recursion

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1827]
While investigating #1823, I realized that we needed to call `witness_api.get_account_bandwidth` in a loop. The accessible version of the API call acquires a read lock, but the read lock has already been acquired by `get_accounts` at this time. Chainbase uses an `interprocess_sharable_mutex`

According to the [Boost docs](http://www.boost.org/doc/libs/1_60_0/doc/html/interprocess/synchronization_mechanisms.html), `interprocess_sharable_mutex` is

> A non-recursive, anonymous sharable mutex that can be placed in shared memory or memory mapped files.

And earlier in the documentation it is stated that

> Non-recursive mutexes can't be locked several times by the same thread. If a mutex is locked twice by a thread, the result is undefined, it might throw an error or the thread could be blocked forever.

Obviously, this is bad and needs to change.

All of our API methods are already declared and defined via macros. I propose creating a read and write wrapper macro that handles the creating the lock. This new method signature would contain a boolean default initialized to false for whether to use a lock or not. The jsonrpc plugin will explicitly call this with true and internal calls (plugin to plugin) or APIs will implicitly avoid locking assuming that the calling thread is already locked. There will be a third macro for lockless APIs which define this field but mark at as unused. That is because the jsonrpc plugin will call all APIs with true, but not all APIs need to be locked (some are purely utility). This has the added benefit that all APIs at compile time need to be explicitly marked as read/write/lockless.

**Comment by goldibex** [comment]
some questions from a n00b:
- why is it necessary to call `witness_api.get_account_bandwidth` in a loop?
- why can't we just copy the relevant code out of `witness_api.get_account_bandwidth` and import it into the `condenser_api` method?
- why are the API methods defined by preprocessor macros? I would have thought subclassing would be more straightforward.

**Comment by mvandeberg** [comment]
> why is it necessary to call witness_api.get_account_bandwidth in a loop?

The method returns a vector of extended accounts. On `master` the struct is passed the database on construction and reads the data directly from the database to populate it's fields. The refactor for appbase moved plugin APIs to their own APIs (where they belong). We need to query the API to get the data.

> why can't we just copy the relevant code out of witness_api.get_account_bandwidth and import it into the condenser_api method?

DRY. It works in a pinch, but as soon as it ships it no longer becomes a priority to fix. I think we are all in agreement that if we can afford it, we should not be in the habit of knowingly shipping poor code.

> why are the API methods defined by preprocessor macros? I would have thought subclassing would be more straightforward.

It might be. The initial implementation for defining our APIs in Appbase was simple and used macros as a short cut. As appbase development continued, the macros were expanded into much more than a shortcut, but a definition of what an API is all on its own. It might be worth refactoring this into something a bit cleaner. I realize this seems to contradict with my previous statement and I view the difference as knowingly writing bad code to ship a quick fix vs working with existing bad code that you don't have the time to fix. I don't think the preprocessor macros are a bad thing, but they are borderline unwieldy.

I forgot to mention in the issue that `get_accounts` currently does this with reputation and the follow plugin. So it needs to be fixed there.

**Comment by theoreticalbts** [comment]
> why are the API methods defined by preprocessor macros? I would have thought subclassing would be more straightforward

To implement a JSON-RPC API, you have to JSON serialize API call arguments and return values.  Since all our FC stuff is done with FC's reflection system, the function arguments / return values have to be introspectable by the FC type system, which essentially uses the macros and templates to generate the boilerplate that implements the serialization.  All the type information to generate those macros and templates would be lost if you just had a class with `virtual variant call(variant args)` method which is implemented with a different subclass for each call, you'd have to handle grabbing the stuff out of `args` and checking its type manually.  FC reflection generates all that boilerplate automatically, so if we set things up properly, we can write RPC methods as `return_struct my_api_method( args_struct my_args )` and it Just Works.

**Comment by goldibex** [comment]
Thanks so much for the rapid feedback @mvandeberg. Under any other circumstances I would agree with you concerning DRY. But shipping Appbase is high priority and refactoring the APIs afterward I think would not be a burden.

I would strongly recommend the following:
- if in your assessment the macro change you have proposed will not take longer than a day, do that.
- if the macro change will take longer than a day, fix the APIs by unDRYing them. I would strongly endorse that the macro change would then be your absolute next priority after that.

I think @youkaicountry has the final say on all this anyway, but that's my two cents.
