### ISSUE TITLE
Market Maker Simulator

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1835]
To gain experience with the intricacies of the market maker feature, and as a tool to help clarify the mathematics, we should write a simple simulator. 

It should allow users to test different scenarios and strategies by changing parameters on the fly, and provide simple visual feedback to aid intuitive understanding of the concepts.

To meet these goals, it should probably be a web project, written in Javascript.

**Comment by goldibex** [comment]
@youkaicountry can we get this broken out into sub-issues? Can I help you with that at all?

**Comment by youkaicountry** [comment]
@goldibex Sure, I will create specific issues related to development when I create a new repository for this project.

**Comment by goldibex** [comment]
cheers

**Comment by youkaicountry** [comment]
Closing as outdated.
