### ISSUE TITLE
Create SMTs in testnet genesis

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1838]
We need a way to test basic SMT functionality before we have ICOs implemented. The decision reached in #1778 was to create them during genesis. 

We should to create several SMTs in genesis, and a give a large balance to the init miner.  When accounts are copied to the test net, we give them SMT balances from the init miner.

**Comment by youkaicountry** [comment]
@mvandeberg I added this to the SMT project, but this may end up falling somewhat in your area.

**Comment by vogel76** [comment]
@youkaicountry Where we can find how to configure & start SMT testnet ?

**Comment by youkaicountry** [comment]
@vogel76 The tinman repository is the location of the testnet code, and the README.md has a pretty good guide to getting everything setup. It still needs a bit of work before it will serve our needs properly, but it is partially useable currently.

https://github.com/steemit/tinman

**Comment by youkaicountry** [comment]
Outdated.
