### ISSUE TITLE
STEEM inclusion in votable_assets

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1844]
A post will have at most three votable assets, but one of which will always be STEEM. 

A design decision should be made on whether STEEM will be explicitly included in `votable_assets` for each comment, or will be implicitly assumed to be a votable asset for each comment.

**Comment by youkaicountry** [comment]
Implicit would make the code somewhat more confusing, but explicit would increase the size of comments with redundant information. 

I would lean towards efficiency in this case, and vote for implicit.

**Comment by mvandeberg** [comment]
Not storing it in an object makes a lot of sense. However, the rewards calculations should be token agnostic (STEEM included) for maximum reusability.

**Comment by youkaicountry** [comment]
Whether STEEM is implicit or explicit to comments, the reward balance objects will explicitly be made to calculate and list the reward to be paid out in STEEM, and we should be able to make it token agnostic.

**Comment by theoreticalbts** [comment]
I envisioned it to be implicit when I wrote the spec.  So I'm leaning toward implicit as well, but I'm not leaning that way very strongly.  @mvandeberg what do you think?

**Comment by youkaicountry** [comment]
We'll proceed with STEEM being implicit.
