### ISSUE TITLE
votable_assets validation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1855]
Validation should be done on `votable_assets` to ensure:
1) There are no repeat asset types
2) There are no more than 2 asset types (Since STEEM is implicit)
3) STEEM is not included as an asset type

- [ ] Update `void comment_options_operation::validate()` by modifying helper visitor processing comment extensions: `comment_options_extension_validate_visitor`
- [ ] Add/extend unit tests to cover implemented functionality in positive and negative cases.

**Comment by vogel76** [comment]
This implementation depends on #1843
