### ISSUE TITLE
SBD Tokens transfer still pending!?

### ISSUE THREAD

**Issue by vindberg** [steemit/steem#1862]
How long is the expected transfer time for sending SBD from one exchange to another!? Its been several hours now. I was under impression that the STEEM Graphene blockchain was efficient!?

Thanks for any answers.

**Comment by mvandeberg** [comment]
With the high volume of cryptocurrency trades the last few weeks, it is possible the exchange in question is not processing deposits/withdrawals as quickly as they normally would. I would give them 24 hours to sort it out and if the deposit does not appear in your exchange wallet by then, contact support for the exchange.

You can also look at account transfer history at `steemit.com/@youraccountnamehere/trasfers` to ensure that it was sent to the right account with the right memo. If the transfer is there, then the SBD was transferred on the blockchain.

**Comment by mvandeberg** [comment]
As this does not appear to be a blockchain bug, I am going to close the issue.
