### ISSUE TITLE
Proposal: Curation Reverse Auction Changes

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1874]
This is proposal brought to me by the witnesses for HF 20. This is a summary of some of our conversations regarding the proposal.

The current curation rewards has a rule that in the first 30 minutes of voting, rewards are paid, in part, to the author instead of the curator. The initial reasoning for this was that back in 2016, curation bots we racing to instantly upvote popular authors to maximize their rewards. We acknowledged that we weren't going to be able to get rid of bots, but needed a system that allowed human curators a chance to compete for curation rewards. The reverse auction was born as a way to require bot operators to be a bit smarter about how they voted. As a method to cut back on the vote racing, it was a success. The basic algorithm is that there is linear discount on curation rewards, 100% to 0% over 30 minutes that reduces payout of curation rewards.

There is one more small rule in the reverse auction that is a bit odd. The curation rewards lost in this time period get paid directly to the author. The idea behind this was that if content can be curated that quickly, then it is probably good enough that the author deserves a bonus. Ideologically, this doesn't quite pan out because easy to curate does not equate to good content.

In 2017 we switched from quadratic to linear rewards. This has lead to some interesting interactions with self voting and curation rewards. 

Self voting and the reverse auction has behaves weirdly. There is no penalty for voting on yourself early because the lost rewards get paid to you as the author. Under quadratic rewards, when voting for yourself early, you still needed significant traction in order to profit from the early self upvote. However, with linear rewards, you do not need any momentum for voting on yourself. This has lead to users paying for upvote bots to vote on themselves early, which gives them good author rewards but also a cut of the bot's curation rewards.

Linear rewards has essentially reintroduced the instant upvote but only when voting on yourself.

The proposal involves two changes.

1. Remove paying lost curation rewards to authors. Instead, they should go back to the rewards pool.

2. Reduce the reverse auction time to 5 minutes. Over the past year Steem has shifted from medium/long form content to short/medium form content. Many witnesses believe that the 30 minute reverse auction time is too long and users are losing curation rewards without realizing the rule exists. The rule is to reign in bots without punishing users. However, it was designed to make bots and users compete. 5 minutes may be too short, but somewhere in the 5-15 minute range seems reasonable.

A related, but independent change in the proposal is increasing the budgeted curation rewards from 25% to 50%. This is a more controversial change. Not all witnesses believe the curation budget is too low, but there is some merit to the change as Golos has bots that redistribute author rewards to curators and is achieving close to a 50/50 split all through voluntary redistribution of rewards.

Here is Blocktrades' original post that lead to the discussion between the witnesses and myself:

https://steemit.com/steem/@blocktrades/voting-abuse-and-ineffective-curation-a-proposal-for-blockchain-level-change

**Comment by mvandeberg** [comment]
We are going to implement 1 as is and 2 with a 15 minute reverse auction.

**Comment by theoreticalbts** [comment]
- (1) I like this.
- (2) Agree.
- (3) I considered making this settable on a per-comment basis, but we probably want it to be equal for everyone.

**Comment by eonwarped** [comment]
Hey not sure if this is the right place to open discussion or from another thread, I can move it if need be.

There have been a lot of concerns about returning lost curation rewards to the pool, and this post sums it up very nicely:

https://steemit.com/steemit/@tcpolymath/a-more-thorough-consideration-the-early-voting-penalty-issue

It's strange that early votes affect the total paid out to curation at all, and I think it's worth considering options that return lost funds to curators instead, or even rebalance the distribution while keeping it amongst the participants.

Here are alternatives that I think might be reasonable to discuss:

1. As written in the proposal. Maintain author pool and curator pool. Distribute the funds in the curator pool in accordance to penalizing the stake linearly.

2. Do (1) except always give the author 75%.

3. Take the current lost rewards and redistribute it among the curators based on penalized weights.

Have these been discussed in any form? It's hard to find any other discussion about this.

**Comment by tcpolymath** [comment]
I think this post is worth looking at as well, as it has some descriptions of weird behavior created by the pool distribution, albeit in a more sardonic fashion: https://steemit.com/steem/@tcpolymath/this-post-will-exist-in-fifteen-minutes

In particular the fact that a percentage of comment votes will now be wasted if they're given in the first fifteen minutes is very irksome to me, and users adjusting to that has the potential to skew the natural pace of discussion.

I very strongly believe that the problem is not unfair author rewards, but the fact that early votes change the percentage of the post that pays out for curation. This should be fixed, rather than keeping it and just changing where the money goes. 

I believe the proposal in the post could be accomplished relatively easily by simply having the curation algorithm behave as if the portions of early votes that are subject to the penalty did not exist at all.

**Comment by TimCliff** [comment]
@eonwarped @tcpolymath Here is the issue for that specific change: https://github.com/steemit/steem/issues/1267

There was also a lot of discussion on it back when the 12 hour lock-out period was added: https://github.com/steemit/steem/issues/900

**Comment by eonwarped** [comment]
Wait that's about votes in the last 12 hours right? This is about the first 15 minutes.

**Comment by TimCliff** [comment]
Woops, sorry. Got my wires crossed. That issue is here: https://github.com/steemit/steem/issues/1878

It was proposed and discussed in this steemitblog post 6 months ago:
https://steemit.com/steem/@steemitblog/hardfork-20-velocity-development-update
