### ISSUE TITLE
All tags do not show up in the sidebar search box and tag list

### ISSUE THREAD

**Issue by Coinhoarder** [steemit/steem#188]
If you search for a majority of tags in the sidebar of Steemit.com search box they do not show up. Also, when you click on "show more topics" there are a lot of tags missing as well.

**Comment by mvandeberg** [comment]
The number of tags displayed in /tags will be bumped to 250 soon. The search is limited to just the tags that are returned. There may be small tags that are not returned in the search (if you notice the search says, 'filter'). If a more robust search exists in the future, it will be handled completely on the front end. 

I am aware my answer may not reflect the state of steemit.com at the time of the ticket.
