### ISSUE TITLE
New SMT asset serialization

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1899]
Change SMT asset serialization to follow the following rules:

- The number will consist of 8 decimal digits that specify the `asset_num`, followed by a single hex digit that specifies the precision, followed by a check digit.
- The check digit will be computed by converting the 8-digit integer to a 9-digit integer by expanding the hex digit to two decimal digits (0-9 -> 00-09, a -> 10, b -> 11, c -> 12).
- Some of the check digit code may need to be changed to handle 9 digits.
- Keep in mind that a 10-digit integer will not fit in `uint32_t`.

**Comment by youkaicountry** [comment]
See discussions in #1892 and #1888

**Comment by youkaicountry** [comment]
Currently blocked until a decision is made in #1892

**Comment by mvandeberg** [comment]
I believe #2028 supersedes this issue. @youkaicountry to close.

**Comment by youkaicountry** [comment]
You are correct, closing this.
