### ISSUE TITLE
Public api settings

### ISSUE THREAD

**Issue by xallavon** [steemit/steem#190]
If i set 
`public-api = database_api login_api network_broadcast_api`
network_broadcast_api is not really enabled

If i set 
`public-api = network_broadcast_api database_api login_api`
only network_broadcast_api is enabled, but i lose access to other apis and my wallet won't start.

Is it a bug? How can I enable all api sets in one daemon?

**Comment by theoreticalbts** [comment]
- The C++ `cli_wallet` expects `database_api` and `login_api` to be API 0 and API 1.  If you want to use the `cli_wallet`, those two API's must be listed before other API's and in that order.
- Accessing API's by string relies on `login_api` to be the API in the second slot (API 1).  Basically the FC API framework expects the API that resolves API names to numeric API ID's to be API 1.
- Many third party scripts and tools are written to rely on `database_api` and `login_api` being API 0 and API 1.

Keep the first two `public-api` entries as `database_api` `login_api` and all your problems should go away.

**Comment by xallavon** [comment]
So, if I use jsonrpc api, how do I enable/specify network_broadcast api subset?
