### ISSUE TITLE
New SMT asset serialization tests

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1900]
In addition to making sure serialization / deserialization works and returns the same asset, tests should be made to ensure the SMT asset is properly formatted when serialized.

- Check number of asset_num digits
- Check precision and check digits are properly ordered and placed after asset_num

**Comment by youkaicountry** [comment]
Depends on #1899

**Comment by mvandeberg** [comment]
Related: #2028

**Comment by youkaicountry** [comment]
Closing as outdated.
