### ISSUE TITLE
Change NAI parsing to recognize a vesting bit

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1901]
To represent SMT power (analagous to VESTS), we will repurpose a single bit in the NAI to represent the SMT vesting version of a token.

This will allow differentiation without forcing us to have two fields in operations for tokens & their vesting version.

**Comment by youkaicountry** [comment]
Discussion in #1819

**Comment by vogel76** [comment]
@youkaicountry  This probably also should wait for stable spec of asset serialization ?

**Comment by youkaicountry** [comment]
Closing this since it may not be necessary now. Discussion about alternatives in #1909.
