### ISSUE TITLE
Use visitor to visit all operation extensions

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1907]
Visitors ignore multiple extensions of the same type, so we should make it able to visit them.

From #1886:
> We should be using the same visitor struct to visit all extensions in the vector. We could use a bitmap or similar structure in the visitor and fail if we visit the same entry twice. I think for most operations, this is a reasonable assumption. It would need to be protected by a hardfork check.

**Comment by Kiwonik** [comment]
Turned out to be unnecessary, see comments to its PR https://github.com/steemit/steem/pull/2005
