### ISSUE TITLE
can't cross-compile on Ubuntu 14.04 64 bit for windows 64 bit with mxe

### ISSUE THREAD

**Issue by windz2009** [steemit/steem#191]
mxe has gcc 4.9.2, (boost 1.5.7 and openssl 1.0.2a already inside cross-compiled)
i got this error and can't understand where is issue

> [ 57%] Building CXX object libraries/fc/CMakeFiles/all_tests.dir/tests/bloom_test.cpp.obj
> [ 57%] Building CXX object libraries/fc/CMakeFiles/all_tests.dir/tests/bloom_test.cpp.obj
> [ 57%] Building CXX object libraries/fc/CMakeFiles/all_tests.dir/tests/bloom_test.cpp.obj
> [ 58%] Building CXX object libraries/fc/CMakeFiles/all_tests.dir/tests/real128_test.cpp.obj
> [ 58%] Building CXX object libraries/fc/CMakeFiles/all_tests.dir/tests/utf8_test.cpp.obj
> Linking CXX executable all_tests.exe
> collect2: error: ld returned 1 exit status
> make[2]: **\* [libraries/fc/all_tests.exe] Error 1
> make[1]: **\* [libraries/fc/CMakeFiles/all_tests.dir/all] Error 2
> make: **\* [all] Error 2

**Comment by cryptid11** [comment]
I get same error on ubuntu 14 lts

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               1681.375
BogoMIPS:              6396.81
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
```


I `sudo make` after  `sudo cmake CC=gcc-4.9 CXX=g++-4.9 -DBOOST_ROOT=~/Documents/boost_1_57_0 -DCMAKE_BUILD_TYPE=Release .`

I try even without `CC=gcc-4.9 CXX=g++-4.9` instruction and with boost 1.60 but got same error...

**Comment by cryptid11** [comment]
```
Linking CXX executable all_tests
libfc_debug.a(thread.cpp.o): In function `boost::coroutines::basic_protected_stack_allocator<boost::coroutines::stack_traits>::allocate(boost::coroutines::stack_context&, unsigned long)':
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:46: undefined reference to `boost::coroutines::stack_traits::minimum_size()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:47: undefined reference to `boost::coroutines::stack_traits::is_unbounded()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:47: undefined reference to `boost::coroutines::stack_traits::maximum_size()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:53: undefined reference to `boost::coroutines::stack_traits::page_size()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:55: undefined reference to `boost::coroutines::stack_traits::page_size()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:71: undefined reference to `boost::coroutines::stack_traits::page_size()'
libfc_debug.a(thread.cpp.o): In function `boost::coroutines::basic_protected_stack_allocator<boost::coroutines::stack_traits>::deallocate(boost::coroutines::stack_context&)':
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:85: undefined reference to `boost::coroutines::stack_traits::minimum_size()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:86: undefined reference to `boost::coroutines::stack_traits::is_unbounded()'
/home/rodomonte/Documents/boost_1_57_0/boost/coroutine/posix/protected_stack_allocator.hpp:86: undefined reference to `boost::coroutines::stack_traits::maximum_size()'
libfc_debug.a(filesystem.cpp.o): In function `boost::filesystem::path::path<boost::filesystem::directory_entry>(boost::filesystem::directory_entry const&, boost::enable_if<boost::filesystem::path_traits::is_pathable<boost::decay<boost::filesystem::directory_entry>::type>, void>::type*)':
/home/rodomonte/Documents/boost_1_57_0/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
make[2]: *** [libraries/fc/all_tests] Error 1
make[1]: *** [libraries/fc/CMakeFiles/all_tests.dir/all] Error 2
make: *** [all] Error 2
```

with -DCMAKE_BUILD_TYPE=Debug

**Comment by windz2009** [comment]
Oh! Great! I think may be to try with boost 1.58?

**Comment by cryptid11** [comment]
Why you say so? Does it works for you? doesn't work for me. It fails even before Building CXX object libraries/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o

**Comment by cryptid11** [comment]
I think @mvandeberg should add the binaries for debian based systems in https://github.com/steemit/steem/releases

**Comment by windz2009** [comment]
What mxe version do you use?

**Comment by cryptid11** [comment]
I'm on ubuntu I don't need it.

**Comment by cryptid11** [comment]
Actually it seems doesn't depend at all from the mxe but only ubuntu, so maybe you have to change title of this or I need to open another issue.

**Comment by windz2009** [comment]
i understand you try compile NOT CROSS-COMPILE steem on ubuntu....so this issue is not yours....

**Comment by windz2009** [comment]
you've mislead me ))

**Comment by cryptid11** [comment]
Actually it's the same issue https://github.com/steemit/steem/issues/225 if, as it seems,  the fault it's not on mxe but on ubuntu.

**Comment by windz2009** [comment]
i tried with -DCMAKE_BUILD_TYPE=Debug on mxe but got the same error as in my first post here (( no difference(( on Ubuntu 14.04 with boost 1.57 nativly it compiles well

**Comment by mvandeberg** [comment]
Docker is our supported build environment. If there are cross platform compilation configurations that the community designs, we will consider merging the changes, but we will not actively develop for such configurations.
