### ISSUE TITLE
Random crash at chain::database::~database()

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1915]
As far as it was debugged and analyzed it was caused by memory buffer overrun at call to `database::init_hardforks`. The cause was too short `_hardfork_times` and `_hardfork_versions` arrays defined by `STEEM_NUM_HARDFORKS` which just had too small value according to lately introduced for the STEEM_NET version `STEEM_HARDFORK_0_20` code.

**Comment by mvandeberg** [comment]
Fixed in #1913
