### ISSUE TITLE
develop branch `jsonrpc.get_signature method` params field not valid jsonrpc

### ISSUE THREAD

**Issue by john-g-g** [steemit/steem#1919]
If present, parameters for the rpc call MUST be provided as a Structured value. Either by-position through an Array or by-name through an Object.

```
$ http --print HBhb --pretty all https://steemd.steemitdev.com id=1 jsonrpc='2.0' method=jsonrpc.get_signature params=tags_api.get_discussions_by_votes
POST / HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 111
Content-Type: application/json
Host: steemd.steemitdev.com
User-Agent: HTTPie/0.9.9

{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "jsonrpc.get_signature",
    "params": "tags_api.get_discussions_by_votes"
}

HTTP/1.1 200 OK
Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 162
Date: Fri, 15 Dec 2017 18:39:14 GMT
Server: nginx
Strict-Transport-Security: max-age=31557600; includeSubDomains; preload

{"jsonrpc":"2.0","result":{"args":{"tag":"","limit":0,"filter_tags":[],"select_authors":[],"select_tags":[],"truncate_body":0},"ret":{"discussions":[]}},"id":"1"}
```

**Comment by mvandeberg** [comment]
Our decision to require parameters be structs has nothing to do with the jsonrpc spec. Saying it is not valid jsonrpc is inaccurate.

The two jsonrpc API method to query methods are special cases. On its own, requiring all parameters be structs is a bit odd, but we have specific design goals behind this decision. My thinking was so long as it was documented to call `get_methods` and `get_signatures` to view enabled APIs, it would imply the convention for struct args and struct returns.

However. of `get_signatures` required a struct arg itself, then it could lead to confusion.

Granted, having it be the only method that does not require a struct argument can lead to some confusion itself.

**Comment by mvandeberg** [comment]
I am going to update `get_signature` to take the struct `{"method":"method_name"}`.
