### ISSUE TITLE
Performance and Load Time Improvements needed

### ISSUE THREAD

**Issue by vishalchandna1** [steemit/steem#1921]
I did a Performance and Load time Audit today and found that there is a lot of room for improvements. Please refer to the post for details : 

[https://steemit.com/steemit/@funnyman/steemit-audit](https://steemit.com/steemit/@funnyman/steemit-audit)

If it cannot be improved considering the current scenario. Let's add some tweaks like 
[https://clasifika.com](https://clasifika.com) Add some loading screen on the screen to help user understand the UX and UI.

**Comment by mvandeberg** [comment]
Thank you for your feedback.

However, these suggestions are for Steemit.com (The Condenser repo). The Steem repo is just for Steemd (The Blockchain).

I am closing this issue and creating a new on in the proper repo.

**Comment by vishalchandna1** [comment]
CoOL!

On Mon, Dec 18, 2017 at 8:44 PM, Michael Vandeberg <notifications@github.com
