### ISSUE TITLE
warnings on shared memory file size

### ISSUE THREAD

**Issue by chenlocus** [steemit/steem#1922]
I setup a test environment in ubuntu 16.04,  then install steem using the following commands:

```
apt-get update
```
```
apt-get install -y git build-essential cmake libssl-dev libboost-all-dev autoconf autotools-dev doxygen libncurses5-dev libreadline-dev libtool screen libicu-dev libbz2-dev graphviz unzip
```

```
git clone https://github.com/steemit/steem.git
```

```
cd steem
```
```
git checkout v0.19.X
```
```
git submodule update --init --recursive
```
```
mkdir build
```
```
cd build
```
```
cmake -DLOW_MEMORY_NODE=ON -DCMAKE_BUILD_TYPE=Release ..
```
```
make -j$(nproc) steemd
```
```
make -j$(nproc) cli_wallet
```
```
sudo make install
```
```
make chain_test
```
```
./tests/chain_test
```

However, I found this:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513137326/dq21vznwgzumpdlryqjq.png)

It looks somebody else raised this before in Sep this year and was closed, here is the link:
https://github.com/steemit/steem/issues/1601

so I assume this is a regression bug in steem.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@chenlocus/warnings-on-shared-memory-file-size">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mvandeberg** [comment]
> This has already been fixed in develop

You built an older version of Steem.
