### ISSUE TITLE
Change Asset String Serialization

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1937]
Assets are currently serialized as `1.000 STEEM`. Parsing this as an integer value by apps interacting over APIs requires custom parsing of the string. The biggest reason we use this serialization is that it is easy to use via the cli wallet.

We are going to change to a different serialization format to make handling assets easier via API.

The new format will be a tuple of `[satoshis, precision, nai]`. We will also assign special NAIs to represent STEEM, SBD, and VESTS.

The previous example would then serialize as `[1000, 3, NNNN]`. Where `NNNN` is whatever we end up using as the reserved STEEM nai.

All APIs returned via condenser API will return the existing format. Other APIs will return the new format. This will release with Appbase so the new APIs use the new format at launch.

**Comment by theoreticalbts** [comment]
I would suggest making it a dictionary `{"amt" : "1234", "pr" : 3, "an" : "99993333"}`.  Reasons:

- Simplify maintaining backward compatibility if we ever want to add additional field(s).
- Short keys to preserve bandwidth (`amount` -> `amt`, `precision` -> `pr`, `asset_num` -> `an`)
- Use `string` values for potentially large integers, because some JSON parsers might lose precision or silently mask integers above a certain size.  This helps the client ensure this handling occurs under control of its own code, not its JSON parser.

**Comment by mvandeberg** [comment]
Tagging @john-g-g @roadscape @goldibex For their input on what they would prefer the asset to look like in our services.

**Comment by roadscape** [comment]
Will NAIs be integers, hex strings, or base36?

Assuming `STEEM` nai would be `99993333`:

`"34.858 STEEM"`
`["34858", 3, 99993333]`
`{"amt":"34858", "pr":3, "an": 99993333}`

As @theoreticalbts stated, we need to watch out for large numbers as some json parsers will convert them to floating point. Safest is to encode as a string. 

The current format is the simplest, most accessible, and lightweight. Parsing the value requires string operations, but so would re-applying the precision on output with the other formats. I'm not a fan of the dict approach; `amount[2]` is as readable as `amount['an']` yet much lighter. I'm not sure what other fields would make sense for "amount" objects, but they could just as easily be pushed on the array.

**Comment by mvandeberg** [comment]
Our design goal behind NAIs was to to make all NAIs equal. Using base36 or hex introduces letters and the possibility for an NAI to represent something as is. I am inclined to say it will only every be returned as an integer.
