### ISSUE TITLE
Cannot connect to steemd instance

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1943]
I have built steemd in develop branch at commit `95b4175c9730ba94f675188fb756e34ea22a0e2a`
I have used configuration file attached to this issue.
When starting up steemd reports that webserver will listen on given port, but as far as I checked in netstat it does not.
steemd startup output:
```
syncad@lnx-ubuntu3:~/src/steem/build/RelWithDebInfo/programs/steemd$ ./steemd -d /home/syncad/src/full-data/  2>&1 | tee steemd.log
1359444ms webserver_plugin.cpp:302      plugin_initialize    ] configured with 1024 thread pool size
1359468ms webserver_plugin.cpp:311      plugin_initialize    ] configured http to listen on 127.0.0.1:8090
1359478ms webserver_plugin.cpp:340      plugin_initialize    ] configured ws to listen on 127.0.0.1:9876
------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.19.4
------------------------------------------------------
1359479ms main.cpp:107                  main                 ] Backtrace on segfault is enabled.
1359479ms webserver_plugin.cpp:353      plugin_startup       ] Waiting for chain plugin to start
1359479ms chain_plugin.cpp:118          plugin_startup       ] Starting chain with shared_file_size: 12884901888 bytes
1359479ms chain_plugin.cpp:186          plugin_startup       ] Opening shared memory from /home/syncad/src/full-data/blockchain
1359479ms block_log.cpp:142             open                 ] Log is nonempty
1359480ms block_log.cpp:151             open                 ] Index is nonempty

^C
syncad@lnx-ubuntu3:~/src/steem/build/RelWithDebInfo/programs/steemd$ 


```

**Comment by mvandeberg** [comment]
Webserver listening is for API requests, not p2p.

I do not see a config file attached to the issue.

**Comment by vogel76** [comment]
Config file contents I can't attach for some reason:
```
log-console-appender = {"appender":"stderr","stream":"std_error"}
log-file-appender = {"appender":"p2p","file":"logs/p2p/p2p.log"}

log-logger = {"name":"default","level":"debug","appender":"stderr"}
log-logger = {"name":"p2p","level":"info","appender":"stderr"}

backtrace = yes

plugin = webserver chain json_rpc 
plugin = database_api 

history-disable-pruning = false

# the location of the chain shared memory files (absolute path or relative to application data dir)
#shared-file-dir = "/dev/shm/steemd-state"

shared-file-size = 12G

flush-state-interval = 1000000

follow-max-feed-size = 500

market-history-bucket-size = [15,60,300,3600,86400]
market-history-buckets-per-size = 5760

# p2p-seed-node =

p2p-user-agent = Graphene Reference Implementation

webserver-thread-pool-size = 1024
webserver-http-endpoint = 127.0.0.1:8090
rpc-endpoint = 127.0.0.1:9876
enable-stale-production = false
```

**Comment by vogel76** [comment]
I of course did try to call API from this instance, both using tinman scripts and next using curl. When it didn't to work I used netstat and it didn't show any process listening for given port.

**Comment by mvandeberg** [comment]
`p2p-endpoint` is the config option to listen on p2p.
`p2p-seed-node` is needed to connect to the network.

**Comment by vogel76** [comment]
I don't need to use p2p - I have local blockchain file and generated state up to 5M block (don't need more for rough testing). Does these p2p options impact somehow http communication used by API calls ?

**Comment by mvandeberg** [comment]
Sorry, that was my misunderstanding of the issue.

I have not had any problems listening on localhost. Can you try setting both `webserver-http-endpoint` and `rpc-endpoint` to the same value. Perhaps there is a configuration error when they are different?

**Comment by mvandeberg** [comment]
There have not been changes to the webserver plugin in quite a while. Let me try a similar configuration locally and see what happens.

**Comment by mvandeberg** [comment]
Actually, this problem does not appear to be coming from the webserver. The webserver won't open until after the chain plugin is done starting. The last line two lines of `chain_plugin::plugin_startup` are a log message and a signal.

The log message is not appearing in your console output. Either the node is hanging during startup, or you killed it too soon.

**Comment by vogel76** [comment]
steemd was running all the time I tried to connect.

**Comment by vogel76** [comment]
I can confirm - steemd built in version from state_model_opts2 (older develop merged) listens and accepts connection, current develop does not.

**Comment by mvandeberg** [comment]
> steemd was running all the time I tried to connect.

Yes, but unless you see a line `Started on blockchain with ${n} blocks`, then the chain_plugin never finished starting and the webserver is not running.

This is not a webserver connection issue, but a chain_plugin startup issue.

**Comment by theoreticalbts** [comment]
Try adding `--replay-blockchain` to the command line.  It may take a long time to start up.

**Comment by vogel76** [comment]
It was done (up to 5M of blocks).
I also think webserver shall not display 'listening' messages until it really will start to listen. Now it is confusing.

**Comment by vogel76** [comment]
[lock_callstack.txt](https://github.com/steemit/steem/files/1588996/lock_callstack.txt)
It seems like some locking problem between threads (trying to figure out what happens there).

**Comment by mvandeberg** [comment]
At this point in time there should be no contention for locks. If there is, it is something Boost is doing internally.

We really only have one lock, the database read/write lock called via `with_read_lock` or `with_write_lock`. It is pretty naive, but works.

**Comment by vogel76** [comment]
From deeper analysis (under debugger) it looks like that scope_lock tries to acquire a lock on mutex which is already locked by the thread does not existing in *this* process. So looks like mutex.__data.owner holds id of the thread which held mutex during replay process and unlock was missed.

**Comment by vogel76** [comment]
[helgrind_replay1.log](https://github.com/steemit/steem/files/1589353/helgrind_replay1.log)
I reproduced unlock miss issue under helgrind (valgrind based tool related to thread issues analysis).
I think this can happen also in normal use when plugins are consuming blocks and SIGINT comes in. Probably application exit shall wait until current block processing will be complete.

**Comment by mvandeberg** [comment]
The lock the process holds in helgrind and the lock your stack trace is stuck on are different locks.

Besides, the read write locks are recreated every run. They used to live in the shared memory segment, but are now in the heap. Failing to release that lock should not have an impact on the next execution.

However, I am not sure the read lock manager is properly instantiated. When it existed in a file the file is guaranteed to holds 0s. That is not the case with heap memory.

The constructor should probably have a line `new( &_locks[ _current_lock % CHAINBASE_NUM_RW_LOCKS ] ) read_write_mutex();` after `_current_lock = 0` to ensure the first lock is created properly.

**Comment by vogel76** [comment]
This is unrelated to locks managed by database directly, but rather to internal locks used by boost interprocess data structures. 
I think it is possible to shutdown the application too early via SIGINT (ie during processing blocks/transaction by plugins) and leave the state file damaged.

**Comment by mvandeberg** [comment]
I believe the behavior seen here is a result of #1965 which has been addressed. Closing
