### ISSUE TITLE
SMT Creation Wizard

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1946]
To allow complex SMTs options to be specified but keep the UI simplified for most users, we propose an SMT creation wizard. This would help fill in values for SMT parameters to get the token the envision, without necessarily having to fully understand the underlying complexities.

Some things that might be discussed:
- What sort of information might the wizard ask the user?
- What variables would likely be hidden?
- What would a minimal wizard look like?
- How would we derive and update values for the wizard?

**Comment by theoreticalbts** [comment]
This isn't, strictly speaking, a steemd issue; it's entirely a UI concern.  But I guess this ticket lives here for the time being?

**Comment by youkaicountry** [comment]
I put it here so that it was included in the SMT project board for now. Once decisions are reached we can write tickets in the appropriate areas.

**Comment by goldibex** [comment]
Let's get this broken out into subissues @youkaicountry

**Comment by youkaicountry** [comment]
@goldibex Where would be the best repository for these discussions to live? Since they are UI related, maybe in condenser?

**Comment by goldibex** [comment]
File them here for now and I'll move them later when necessary.

**Comment by 1000goalgaming** [comment]
Can't wait for this. Doing a school project about cryptocurrency due at the end of May and I really want to make an SMT for it

**Comment by youkaicountry** [comment]
Blocked on SMT implementation.

**Comment by 1000goalgaming** [comment]
?

**Comment by mvandeberg** [comment]
Because this is an issue to discuss creation of a wizard, and we have an implementation in a separate repo, I am going to consider this issue done.
