### ISSUE TITLE
Account History Optimizations

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1949]
There are two optimizations listed in #1923 for Account History that I want to discuss the efficacy of.

> Avoid create & immediate remove of account history object when prune is enabled. 

> Redesign account history object structure and hold list of operations per given account instead of multiple account_history_object pairing account and the operation

The first seems reasonable except for the fact that pruning keeps 30 days or 30 items, whichever is more and it is impossible to know ahead of time exactly which history items will be needed at the end of reindexing. We make need to tweak these rules for faster reindexing.

The reason we don't keep a list of operations is that when an object is modified, a copy is made in the undo state. Saving undo states as a diff is challenging and can be expensive. Assuming objects are relatively small and do not contain dynamic fields, these copies are not that expensive. Making the object contain a list of operations per account would mean that the entire history would be copied whenever the object is modified. It is worth noting that this would not happen on reindex (undo states are not used during reindex except for custom json ops), but would slow syncing and live performance significantly.

**Comment by mariusztrela** [comment]
- `Avoid create & immediate remove of account history object when prune is enabled.`

	I think here is some misunderstanding. Let's me clear.

	In method `steem::plugins::account_history::operation_visitor::operator()` before, was unnecessary creating `chain::account_history_object` object. Later the same object was removed in `while` loop. At now behaviour is smarter and creation is then, when it is really needed. Business logic is still the same.

- `Redesign account history object structure and hold list of operations per given account instead of multiple account_history_object pairing account and the operation`
	a) `Saving undo states as a diff is challenging and can be expensive` : vector in `account_history_object` is very small and takes at most sizeof( int64_t ) * 30 = 240 bytes
	b) `...undo states are not used during reindex...` : 
		method `chainbase::database::modify` calls `get_mutable_index<index_type>().modify`
		method `get_mutable_index<index_type>().modify` calls `on_modify` where is created copy of object ( `head.old_values.emplace` ).
		It seems, that undo states are used during index. We made performance-tests ( during reindex ) and finally reindex is faster when given changes are introduced.
		Maybe in the future will be worth to save only diffs, it will simplify problem yet more.

**Comment by mvandeberg** [comment]
Do you have the performance data available?

See my comment in #1967 regarding some of my performance concerns. I do not doubt that this is faster in the scenarios you tested, but there are other scenarios where I am worried this change breaks down and results in poorer performance.

**Comment by youkaicountry** [comment]
This is being closed in favor of the work done in #2129

**Comment by lopugit** [comment]
what do you guys think of the c++ syntax? imo it's cancer ::'s <>'s ()'s &'s [&]'s wtf.... it's just chaos
