### ISSUE TITLE
get_inbox crashes cli_wallet

### ISSUE THREAD

**Issue by jl777** [steemit/steem#195]
I am probably calling it wrong via
curl --url "http://127.0.0.1:8091" --data "{\"id\":444,\"method\":\"get_inbox\",\"params\":[\"jl777\", \"2016-07-20T17:50:15\", 86000]}"

but it immediately caused cli_wallet to crash. I did a prior send_private_message which actually made it to the blockchain as some sort of encapsulated data, so maybe the crash is only with accounts that have an incoming message?

**Comment by noisy** [comment]
@jl777 could you confirm, that you still have this problem?

**Comment by mvandeberg** [comment]
The message plugin is deprecated.
