### ISSUE TITLE
Eliminate Unused Indices

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1950]
> Eliminate unused indices created by follow_plugin data structures: `feed_index`: `by_account`, `by_old_feed`, `blog_index`. `blog_index`: `by_old_blog`. `reputation_index`: `by_reputation`. `follow_count_index`: `by_followers`, `by_following`

I do not know which branch this change is in, but it is marked complete in #1923.

Let's get this into its own branch and make a PR.

**Comment by mvandeberg** [comment]
Some of these indices exist to support API calls. We need to be careful to preserve the API calls for now. Many of them will be removed/not needed in the coming months.

**Comment by goldibex** [comment]
#2228
