### ISSUE TITLE
Eliminate Superfluous Indices and Use Reverser Iterators

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1951]
> Review all existing indices to check for obsolete ones and potentially replaceable by reverse_iterator usage (especially look for indices prefixed with `by_old`)

Referenced in #1932

Some indices need to be accesses in both directions. Because `lower_bound` semantics are easier, we were lazy and created a second index. Those should be removed and replaced by reverse iterator semantics.

**Comment by mariusztrela** [comment]
It is done - see implementation in PR 1963.

**Comment by mvandeberg** [comment]
#1999 concerns this task and is complete.
