### ISSUE TITLE
Issue with Voting payout and VOTE_DUST_THRESHOLD

### ISSUE THREAD

**Issue by aminar6** [steemit/steem#1954]
I'm trying to set up a private blockchain for an academic project, but I'm encountering an issue with voting payouts and STEEMIT_VOTE_DUST_THRESHOLD.
My network needs to have 50 million premine (STEEMIT_INIT_SUPPLY 50000000000), 3 witnesses (initminer and 2 others) and I have created 1 user to whom I transferred 5 STEEM POWER (transfer_to_vesting from cli wallet) from initminer.

The problem is that this user cannot  vote an I am getting the error "Voting weight is too small, please accumulate more voting power or steem power.".
I can fix this issue by transferring huge amount of steem to the user (several hundrend thousand), but even then the user's votes count for $0 payout.
I have reduced the Dust threshold from 50000000 to 30000000 but the problem still exist.

I would really appreciate if you could put me in correct direction regarding this issue. What is causing it and how to solve the problem.

**Comment by mvandeberg** [comment]
The vote dust threshold is compile time configurable in `libraries/protocol/include/steem/protocol/config.hpp`.

**Comment by aminar6** [comment]
Hi mvandeberg and thank you for the reply.

Unfortunately reducing the dust threshold does not solve the underlying issue (that it takes many thousands of steem for user to have any meaningful vesting shares so votes can payout).

After some investigation it seems the steem_per_mvests on my network is **~47605.237** which looks very high to me (total_vesting_fund_steem is 5466.000 STEEM while total_vesting_shares is only 11.481930 VESTS).

Is there any way I can reduce the steem_per_mvests value? If I understand I need to reduce either total_vesting_fund_steem or increase total_vesting_shares but I'm not sure how to achieve it.

**Comment by mvandeberg** [comment]
Are you forking the live network, or starting a private blockchain from scratch?

**Comment by aminar6** [comment]
I have started a private blockchain from scratch. I have got 3 witnesses and 3 seednodes and everything is working perfectly except the vote and payout issues that I mentioned above.

**Comment by mvandeberg** [comment]
Are you running `master` or `develop`? `develop` has some test net code in it that might help you. Specifically, applying hardforks at genesis. Because of inflation changes and interactions with VESTS, the high inflation rate combined with a high pre-mine could cause this behavior.

**Comment by aminar6** [comment]
I will try to use develop to find out what is causing this behavior. 
Again thank you for your time and your help, hugely appreciated.

**Comment by mvandeberg** [comment]
There has not been activity on this and it is for a private blockchain, closing.
