### ISSUE TITLE
User spamming the blockchain with duplicate custom_json "follow"

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/steem#1956]
Some users are spamming the blockchain by sending custom_json operation to follow all users again and again. 

Here is an extract of SteemSQL Database Injector.

```
DEBUG: Processing block 18485762 with 115 transactions 
Follow record already exists arnoldwish -> itsallasong 
Follow record already exists arnoldwish -> irphotography 
Follow record already exists arnoldwish -> irrs 
Follow record already exists arnoldwish -> irwanda 
Follow record already exists arnoldwish -> irtaza 
Follow record already exists arnoldwish -> is-educator 
Follow record already exists arnoldwish -> irwanumpal 
Follow record already exists arnoldwish -> isaacshobs 
Follow record already exists arnoldwish -> irwingtell0 
```

I think such "invalid" transactions should generate an error and be refused

**Comment by mvandeberg** [comment]
How is the transaction invalid?

By definition, `custom_json_operation` is always a valid transaction. If following should be rejected, then it needs to be added to consensus. That is the exact opposite direction of where development is headed. We are moving follows to an external service entirely and will stop supporting it in steemd.
