### ISSUE TITLE
Virtual supply computation review

### ISSUE THREAD

**Issue by eonwarped** [steemit/steem#1961]
I want to bring up a possible discrepancy in the way the virtual supply is completed and the SBD ratio. I believe there's a mistake in the way SBD converts to Steem.

In https://github.com/steemit/steem/blob/57451b80d2cf480dcce9b399e48e56aa7af1d818/libraries/chain/database.cpp

Line 3000, update_virtual_supply.

The SBD supply is multiplied by the median price feed, but the units don't work out. It should be divided instead. At current rates 1 STEEM is worth 3 USD, so 1 SBD should be converted to 0.333 STEEM, not 3 STEEM.

If this is true, then I suspect sbd's ratio is being over reported right now and as steem's value rises we may not be printing SBD any longer.

Can someone please confirm or deny my suspicion?

**Comment by pmconrad** [comment]
Note that the price object has an overloaded * operator that checks the currency against which it is applied, and uses the appropriate ratio: https://github.com/steemit/steem/blob/57451b80d2cf480dcce9b399e48e56aa7af1d818/libraries/protocol/asset.cpp#L160

**Comment by eonwarped** [comment]
Oh thank goodness! I suspected I was missing something but I couldn't figure it out. Thank you for the pointer!
