### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by porky11** [steemit/steem#1968]
the type `fcontext_t` is not defined in the namespace bc:
```
      my_context(new bc::fcontext_t),
                         ^~~~~~~~~~
```
File: `steem/libraries/fc/src/thread/context.hpp:103:25`

**Comment by nannal** [comment]
: error: 'fcontext_t' in namespace 'bc' does not name a type
      my_context(new bc::fcontext_t),

Here too.

**Comment by mvandeberg** [comment]
What version of Boost are you building with?

Boost 1.61+ changed the interface for threading that is currently not compatible with Steem.

**Comment by porky11** [comment]
Version 1.66 (arch linux).
Rust with cargo doesn't have these version problems.

**Comment by mvandeberg** [comment]
As stated, Boost 1.60 is the newest version of Boost we support. Either download that version specifically or build from source. Also, versions of steemd are built via Docker and uploaded to Docker Hub. Regardless of your system's environment, you can always launch steemd in Docker.

**Comment by romeojulietthotel** [comment]
Looks like some ifdefs are needed:

https://github.com/facebook/folly/commit/823ecf8917d7f0534ed02b8d38bfc966cb0fd7b6

and redefining the bc and bco namespaces.

I could try a PR through trial/error but it might take a little time.
