### ISSUE TITLE
Killing steemd with SIGINT results in seg fault

### ISSUE THREAD

**Issue by Phistr90** [steemit/steem#197]
Every time I kill the steemd with SIGINT signal I get a seg fault and the next time I start steemd I have to do an replay since it was shut down 'unclean'.

**Comment by taoteh1221** [comment]
I can confirm same issue on a lower-end minipc on Ubuntu 14.04 (quad core 2.18 GHz Celeron, 8Gb ram). Almost never exits cleanly.

**Comment by theoreticalbts** [comment]
Duplicate of #142.
