### ISSUE TITLE
fast content fetching

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1975]
In trying to keep up with steemd, hive's biggest bottleneck is getting data from steemd; and in particular, `get_content` calls.

Is it possible to:
(a) speed up the response
(b) implement batch fetching (like `get_accounts`)

**Comment by mvandeberg** [comment]
(a) It is as fast as it is going to get with the current database architecture.
(b) We could, but I don't think you'll get much. Appbase supports parallel reads, which should be somewhat faster than batch, or you can do batch reads with jsonrpc batch requests.

**Comment by roadscape** [comment]
Appbase + rpc batching looks very promising... getting ~1000 calls/sec on dev, batch size = 500.
