### ISSUE TITLE
Build Fails on Ubuntu Xenial 64

### ISSUE THREAD

**Issue by devluxg** [steemit/steem#198]
Great idea!  Wanted to try and build it for linux.  Didn't see any install instructions anywhere, but I was able to hunt and peck the libs and reqs out, so maybe once this part is over I'll post a guide or something.  In the meantime the latest master which you have tagged for release isn't building on Ubuntu Xenial 64 Bit.

`CMake Error at CMakeLists.txt:35 (include):
  include could not find load file:

    GetGitRevisionDescription

-- BUILD_STEEM_TESTNET: OFF
-- LOW_MEMORY_NODE: OFF
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   atomic
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   coroutine
--   context
--   system
-- Configuring Steem on Linux
CMake Error at libraries/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/dev/Projects/steem/libraries/fc

  does not contain a CMakeLists.txt file.

CMake Error at libraries/utilities/CMakeLists.txt:2 (include):
  include could not find load file:

    GetGitRevisionDescription

CMake Error at libraries/utilities/CMakeLists.txt:3 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".
`

**Comment by devluxg** [comment]
Went through and read the cmake file line by line.
Need to do a git clone --recursive or it misses a lot of submodules.  Also there are a TON of libs this thing still needed.  Seems to be building fine now.  Once built I will update the readme for ubuntu and submit a PR.
Closing issue

**Comment by reppolice** [comment]
Wow, still seems to be missing the proper instructions, ran into the same CMake error
