### ISSUE TITLE
Implement compilation time switching between boost::interprocess allocator and standard memory allocator

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1984]
All changes are already done in the state_model_opts2 branch. All we need is rebasing it agaist current develop and separate allocator specific changes to actual branch to make clear PR for it.

**Comment by vogel76** [comment]
We did dedicated test (by running reindex process up to current head block). It passed and I don't see any reason to blocking merge of this PR 1995 more.

**Comment by theoreticalbts** [comment]
I do not understand the purpose of this branch / code.  Please post or link to a more complete explanation of what is being attempted here.

**Comment by vogel76** [comment]
This branch better organizes definitions of types (specifically container types) in the code, since they are defined in one place using aliases.
These changes are needed (as a codebase), to share data structures between places still using Boost Interprocess Allocator and new code using standard allocator, where persistent layer is basing on different solution (ie rocksdb).
Now, because some container types are strictly tied to BIP it is impossible to use structures referencing such container types without BIP, because it won't compile.
