### ISSUE TITLE
Implement json_rpc plugin option to dump all API request and responses

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1986]
Option should dump data in a form matching scheme of API automatic tests suite (see #1567) to be able automatically generate test inputs and initial patterns ie by using a condenser connected to given steemd instance.

All changes are done in state_model_opts2 branch, must be separated to dedicated branch and rebased according to current develop status.

**Comment by mvandeberg** [comment]
The plugin used to do an idump of all accepted requests. Let's add that back with a custom logger (see p2p code) so that we can specify a log location in the config file.
