### ISSUE TITLE
miner , no witness , no miner

### ISSUE THREAD

**Issue by AmA-sud** [steemit/steem#1990]
hi there i have installed the miner , and have done all the settings in the config file , but still it won't kick out , it stops on the following message : 
1031191ms th_a       witness.cpp:189               plugin_startup       ] No witnesses configured! Please add witness names and private keys to configuration.
1031191ms th_a       witness.cpp:197               plugin_startup       ] No miners configured! Please add miner names and private keys to configuration.

and even the wallet cli  , gives the following message 

2472737ms th_a       main.cpp:154                  main                 ] wdata.ws_server: ws://localhost:8090
0 exception: unspecified
Underlying Transport Error
    {"message":"Underlying Transport Error"}
    asio  websocket.cpp:444 fc::http::detail::websocket_client_impl::{ctor}::<lambda_07ad2457060ff51cd32eb8549cbb202a>::operator ()

    {"uri":"ws://localhost:8090"}
    th_a  websocket.cpp:673 fc::http::websocket_client::connect

here is the configuration file part that i have edited , it all matches , i don't know where is the problem exactly .

# P2P nodes to connect to on startup (may specify multiple times)
seed-node = 52.38.66.234:2001
seed-node = 52.37.169.52:2001
seed-node = 52.26.78.244:2001
seed-node = 192.99.4.226:2001
seed-node = 46.252.27.1:1337
seed-node = 81.89.101.133:2001
seed-node = 52.4.250.181:39705
seed-node = 85.214.65.220:2001

# name of witness controlled by this node (e.g. initwitness )
witness = "xxxxxxxxxxxx"

# name of miner and its private key (e.g. ["account","WIF PRIVATE KEY"] )
miner = ["xxxxxxxxxxxxxx","xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

# Number of threads to use for proof of work mining
mining-threads = 2

**Comment by mvandeberg** [comment]
Mining has not been a part of Steem for many months. Specifying a miner is not required in the config, nor is specifying witnesses. The message is there to let you know there are none configured.

I am not sure where you go your seed nodes. We have a published list of seed nods in doc/seednodes.txt

In order to connect to your node via cli make sure to have `rpc-endpoint = 127.0.0.1:8090` in your config.

**Comment by timogoosen** [comment]
"Mining has not been a part of Steem for many months. " Is there some way to make money from running a node other than mining, considering that Mining isn't part of steam anymore. I'm just curious.

**Comment by TimCliff** [comment]
Block producers on the Steem blockchain are called witnesses, and they are paid per block they produce. They are assigned blocks based on the stake weighted votes of the token holders under a protocol called Delegated Proof of Stake (DPoS).

**Comment by youkaicountry** [comment]
Closing.
