### ISSUE TITLE
Extend reindex-process benchmark by collection statistical and execution time informations related to operations processed for each visited block

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1996]
Statistic and time data should be collected for each processed operations. Report should be dumped in json format similary to reindex benchmark collector.
Best collect operation processing times in distribution to plugins which processed them, to generate report contatining time distribution for each plugin.

**Comment by mkochanowicz** [comment]
Blocked until accepted https://github.com/steemit/fc/pull/40

**Comment by mvandeberg** [comment]
fc is vendored to steemd. fc changes are now a part of the steemd PR. This is no longer blocked.
