### ISSUE TITLE
How to calculate and update average bandwidth?

### ISSUE THREAD

**Issue by yao23** [steemit/steem#2009]
In the whitepaper section [Bandwidth Instead of Micropayment Channels](https://github.com/noisy/steem-whitepaper/blob/master/whitepaper/04-eliminating-transaction-fees/sections/bandwidth-instead-of-micropayment-channels.asc):

B = a user’s average bandwidth at time T
W = the number of seconds per week
N = the size of the new transaction that occurred S seconds after T.

Given this information the blockchain can calculate the new average bandwidth for a user as:

Bnew = MIN(0,B * (W­S) / W) + N * S / W
Tnew = T + S

Questions:
1. Why use WS divided by W?
2. If B*(WS) / W means toal size cost by transactions in S seconds, N * S/ W represents total transaction time per week, what's meaning by add them together?

**Comment by mvandeberg** [comment]
That is not the Steem whitepaper. [This](https://github.com/steemit/whitepaper/blob/master/whitepaper.md) is the whitepaper. 

[witness_plugin.cpp](https://github.com/steemit/steem/blob/master/libraries/plugins/witness/witness_plugin.cpp#L357-L411) contains the implementation of the bandwidth algorithm.

The lines specific to what you're interested in are:

``` c++
share_type new_bandwidth;
share_type trx_bandwidth = trx_size * STEEM_BANDWIDTH_PRECISION;
auto delta_time = ( _db.head_block_time() - band->last_bandwidth_update ).to_seconds();

if( delta_time > STEEM_BANDWIDTH_AVERAGE_WINDOW_SECONDS )
   new_bandwidth = 0;
else
   new_bandwidth = ( ( ( STEEM_BANDWIDTH_AVERAGE_WINDOW_SECONDS - delta_time ) * fc::uint128( band->average_bandwidth.value ) )
      / STEEM_BANDWIDTH_AVERAGE_WINDOW_SECONDS ).to_uint64();

new_bandwidth += trx_bandwidth;
```

As you can see, that documentation is not accurate to how bandwidth works. The repository in question is controlled by Noisy, a member of the Steem community, not by Steemit.

**Comment by yao23** [comment]
@mvandeberg 

1. trx_size is like a base bandwidth size, new_bandwidth is like a delta bandwidth? 

2. Is there yellow paper which has technical explanation about math formula or even some piece of code?

**Comment by mvandeberg** [comment]
`trx_size` is size of transaction in steemd's binary serialization (effective size in the blockchain).
`new_bandwidth` is the current bandwidth, linearly reduced by time passed since last update, and then adding in the size of the new transaction.

No, there is no yellow paper.

Pseudocode for this would be.

```
account_bandwidth -= account_bandwidth * delta_time / 1 week // decreases linearly over one week
account_bandwidth = max( 0, account_bandwidth ) // floor to 0 
account_bandwidth += new_transaction_size // add new bandwidth cost
```

**Comment by yao23** [comment]
From comments line 305 to 317, it seems reserve ratio is same for every user account?

**Comment by mvandeberg** [comment]
Yes, bandwidth is a fractional reserve system. By definition, every user needs to be affected by the same reserve ratio.

**Comment by yao23** [comment]
In line 404, comment as "Account: ${account} bandwidth limit exceeded. Please wait to transact or power up STEEM.", how to achieve this? Does it lower Steep Power and slowly increase to make it work? Or just frozen the account for a while?

**Comment by mvandeberg** [comment]
`account_bandwidth -= account_bandwidth * delta_time / 1 week // decreases linearly over one week`

The first line of calculating bandwidth reduces used bandwidth slightly. This can allow an account to transact again after a short period of time.

If the account gets more Steem Power then they have a higher percentage of the total bandwidth to use and can transact again.

If the blockchain is used less then there is more bandwidth available and the reserve ratio will increase (allowing lower steem power accounts to transact).

**Comment by yao23** [comment]
If I understood correctly, it means:

every user account has relatively "fixed" amount of bandwidth (B_weekly_you in the following formula) in the beginning of a week, it will reduce until zero based on usage, then recover with time.  Not strictly "fixed" because of reserve ratio might change.

B: Bandwidth, SP: Steem Power, R: Reserve Ratio
B_weekly_you = B_weekly_total * SP_your / SP_total
B_weekly_total = Size_per_block * Number_block_weekly * R
