### ISSUE TITLE
removal of 20s comment limit

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2019]
Users have expressed that having to wait 20 seconds between comments can be too much. IIRC, accounts can only make one post per block, so effectively the lowest comment interval is 3s.

A 3-second interval combined with bandwidth limits seems quite reasonable; we should consider removing the 20s rule.

**Comment by iamsmooth** [comment]
In addition to being annoying even with the current UI, the hard coded blockchain limit fails to be UI agnostic, as certain types of UIs or blockchain applications would suffer even more from a 20 second limit. I agree with removing it and just having the 3s+bandwidth limits.

**Comment by sneak** [comment]
👍
