### ISSUE TITLE
cli_wallet error: 11 eof_exception: End Of File

### ISSUE THREAD

**Issue by fusenn** [steemit/steem#202]
Full Print out after trying to start wallet.

Logging RPC to file: logs/rpc/rpc.log
11 eof_exception: End Of File
unexpected end of file
    {}
    th_a  json.cpp:430 variant_from_stream

**Comment by asalei** [comment]
same here.

**Comment by fusenn** [comment]
I reinstalled the entire thing, worked for me, but still don't know how to fix this error.

**Comment by omotherhen** [comment]
if you start it with sudo, it should work.
sudo ./cli_wallet
This is because it's probably in a protected area that needs sudo permissions

**Comment by theoreticalbts** [comment]
This ticket is old and does not seem to have enough information to reproduce.  Closing.
