### ISSUE TITLE
Concurrent execution of API calls does not work - they are sequenced in steemd process

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#2023]
We have done test scripts which allows to execute API calls (account_history_api.get_ops_in_block and get_account_history) on 2 specified instances, to compare results got from reference instance.
Codebase specific to this issue is in branch:
https://github.com/steemit/steem/tree/1987_rocksdb_prototype_develop
The API has been defined using macro: `DEFINE_LOCKLESS_APIS`.
There are located testing scripts, lets focus only on one of them: `test_ah_get_ops_in_block.sh`.
This script allows to execute `account_history_api.get_ops_in_block` call for each block up to specified limit (or up to head-block reported by given instance) using specified number of parallel jobs.
Let's try to saturate steemd instance and call this script like follows:
`./test_ah_get_ops_in_block.sh 100 127.0.0.1 8090 127.0.0.1 8090 5000000`
what means that you want to spawn 200 concurrent jobs to call given API on specified instance (because we have used the same instance's address as reference and testing one we have 100 concurrent calls for reference one and 100 for testing one).   
As you can observe, steemd is still using 1 core (I suppose you are working on multicore system) what leads to conclusion that calls are synchronized and executed in by 1 thread (on 12 core system CPU load is near to 10-12%).
Some synchronization is done in ddump inside `json_rpc_response json_rpc_plugin_impl::rpc( const fc::variant& message )`, but eliminating it only a little increases CPU load (up to 15%).
Source of this unexpected lock is for sure outside RocksDB engine, since after removing calls to its functions, CPU load (on these 200 concurrent calls) get down to 10%.

**Comment by vogel76** [comment]
Created a branch `2023_broken_concurrent_api` to show that parallel execution done from c++ level directly works well.
Here is example JSON request to start test API:
```
{"jsonrpc": "2.0", "method": "call", "params": ["account_history_api","test_parallel_get_ops_in_block",{"totalBlockNumber": 5000000, "callRepeatNumber": 1, "threadNumber": 8}], "id": 2}
```
On local machine having 8 cores, steemd's CPU has been saturated to 720% as `top' tool reported.

In opposite version operating through `test_ah_get_ops_in_block.sh` is unable to use more than 10% of steemd's CPU (so *only 10% of single core*).

`ab` tool got better results than script mentioned above, but still not satisfying - CPU usage by steemd process was at most 82%.
Below is report from `ab` tool:
```
ab -n 625000 -c 8 -p ./request http://127.0.0.1:8080/rpc
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 62500 requests
Completed 125000 requests
Completed 187500 requests
Completed 250000 requests
Completed 312500 requests
Completed 375000 requests
Completed 437500 requests
Completed 500000 requests
Completed 562500 requests
Completed 625000 requests
Finished 625000 requests


Server Software:        WebSocket++/0.7.0
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /rpc
Document Length:        665 bytes

Concurrency Level:      8
Time taken for tests:   156.030 seconds
Complete requests:      625000
Failed requests:        0
Total transferred:      457500000 bytes
Total body sent:        174375000
HTML transferred:       415625000 bytes
Requests per second:    4005.65 [#/sec] (mean)
Time per request:       1.997 [ms] (mean)
Time per request:       0.250 [ms] (mean, across all concurrent requests)
Transfer rate:          2863.42 [Kbytes/sec] received
                        1091.38 kb/s sent
                        3954.80 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2  51.6      0    7290
Processing:     0    0   5.6      0    3712
Waiting:        0    0   5.6      0    3712
Total:          0    2  52.3      0    7290

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%      0
  99%      1
 100%   7290 (longest request)
```

**Comment by mvandeberg** [comment]
Please demonstrate this on `develop` using an API other than the RocksDB API. I have not been able to reproduce your results and want to eliminate as many variables as possible.

**Comment by vogel76** [comment]
After another round of tests, we have found that our use of `ab` tool was wrong. We have passed there wrong number of total requests to be made, so comparison to C++ version was wrong. I am closing the issue as it looks the things works well.
