### ISSUE TITLE
Asset identifier serialization specification

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2028]
We never did exactly specify how the asset serialization format should look in JSON.  The current code is different from what I envisioned, so in this issue I'll do a deep dive on it.

### Definitions

Let's go back and write some detailed definitions, because the previous ones (in #1888 #1892) are somewhat out-of-date.

#### Values that do not contain precision

- An *NAI string* is a *string of eleven characters* where the first two characters are `@@`, each subsequent character is between `'0'` and `'9'`, and the last character is a specific deterministic *checksum function* of the previous characters.
- An *NAI integer* is the integer represented by *all nine numeric digits* of an NAI string (excluding the two initial `@` values).
- An *asset identifier* is the integer represented by *eight numeric digits* of an NAI string *excluding the final check digit*.
- A *special number* is the integer `1` for `SBD` or `TBD`; the integer `2` for `STEEM` or `TESTS`; the integer `3` for `VESTS`

#### Values that contain precision

- An *asset number* is an integer where the four lowest bits are a precision value ranging from `0` to `STEEM_ASSET_MAX_DECIMALS`; the next-lowest bit is `1`; and the remaining high-order bits are an asset identifier.
- An *extended NAI string* is a *string of twelve or more characters* where the first ten characters are identical to a NAI, and the remaining characters include precision and a check digit.

#### Miscellaneous definitions

- The *system assets* are `STEEM`, `SBD`,  `TESTS`, `TBD`, `VESTS`
- A *named asset* is an asset which has a name in the namespace dictionary used by a UI to name assets.
- An *unnamed asset* is an asset which exists on the blockchain but has no entry in the UI's namespace dictionary.

#### theoretical's original proposal

Here's my original proposal.  When I wrote this proposal, I took the first two items as requirements.  The only two things exposed to users are asset numbers (when dealing with binary) and NAI strings (when dealing with JSON), all the other formats were intended to be internal implementation details.

- System assets binary serialize in legacy format
- System assets JSON serialize in legacy format
- Non-system assets binary serialize as asset numbers
- Non-system assets JSON serialize as NAI strings

#### What the code currently does

This is what was implemented.  We decided to waive the requirement that JSON serialization be backward compatible.  But a new format, special numbers, somehow made it into the code.  The user-facing JSON serialization now uses NAI integers for non-system assets, and special numbers for system assets.  NAI strings are totally unused!

- System assets binary serialize in legacy format
- System assets JSON serialize as special numbers
- Non-system assets JSON serialize as NAI integers
- Non-system assets binary serialize as asset numbers
- The `asset` data structure JSON serializes as `["amount", precision, NAI integer | special number]`

#### Considerations for modifying this spec

- We have to spec this right, once SMT's are released (or even once clients start building on a testnet) it will become hard to change
- UI's will probably use whatever is returned by the JSON API for unnamed assets.  Therefore, if we want the UI to use NAI strings or extended NAI strings, assets should be serialized in that way.
- If we don't ever use NAI strings or NAI integers in JSON or binary serialization, then we should remove the NAI concept from C++ code altogether, and use asset identifiers and/or asset numbers instead.
- A large amount of asset identifiers should be reserved for future asset types.
- Having a field that allows either special numbers or NAI integers is extra complexity.  Let's get rid of special numbers altogether.  I'm not sure why they were introduced to begin with.
- I intended NAI integers to be an implementation detail, not exposed externally by any means whatsoever.
- There are multiple proposed specifications for an extended NAI string in various tickets.  I believe there is a tentative consensus among the backend developers that extended NAI strings will never be implemented.  Given that they will never be implemented, a precise spec of extended NAI strings does not need to be fully formed.
- Current operations all have `asset_symbol` as part of an `asset`, which is JSON serialized holistically.  We need to decide whether `asset` should continue to have a holistic serialization like `["amount", precision, "NAI symbol"]`, or a more modular serialization like `["amount", [precision, "NAI symbol"]]` which subsumes a serialization of `asset_symbol` as `[precision, "NAI symbol"]`.
- In general, we need to define and test a standalone serialization of `asset_symbol`, as some SMT operations require it.  If this serialization includes a precision field, we need to review SMT operations specified and/or implemented for redundant precision values.

#### Shortcomings of current implementation

- A JSON API that returns NAI integers instead of NAI strings risks that UI developers will inconsistently implement NAI strings, some will likely use different formatting or specify NAI integers instead.
- The check digit should always be computed in the same way regardless of whether the NAI represents a system or non-system asset.  Special numbers mean code needs more special cases.  I want to remove special numbers from the spec.
- The current code's a little careless about standalone `asset_symbol_type` (apparently `from_variant` isn't even defined for `asset_symbol_type`?)

#### What I propose

Here are the changes I propose:

- Unit tests of all binary and JSON serializations of `asset` and `asset_symbol_type`
- Currently the naming conventions in the code generally only distinguish between NAI and `asset_num`.  Each function, variable, preprocessor constant, etc. should be renamed to make clear whether it is an NAI string, NAI integer, asset identifier, asset number, or special number.
- NAI integers and asset identifiers are internal identifiers that never appear in JSON or binary serializations
- Special numbers are a dead end; delete or refactor all related code so system and non-system asset symbols are handled as similarly as possible in user-facing interfaces and (to the extent easily doable) internal code
- System assets binary serialize in legacy format
- System assets JSON serialize as `["amount", precision, "NAI string"]`
- System asset symbols JSON serialize as `[precision, "NAI string"]`
- Non-system assets binary serialize as asset numbers
- Non-system assets JSON serialize as `["amount", precision, "NAI string"]`
- Non-system asset symbols JSON serialize as `[precision, "NAI string"]`
- The NAI string for `SBD` is `@@00000001x` where `x` is determined according to the checksum function
- The NAI string for `STEEM` is `@@00000002x` where `x` is determined according to the checksum function
- The NAI string for `VESTS` is `@@00000003x` where `x` is determined according to the checksum function
- NAI strings starting with `0` are reserved for future assets and will not be assigned

**Comment by theoreticalbts** [comment]
Another design question:  Should deserialization code accept alternate binary spelling of `STEEM` / `SBD` / `VESTS` ?  I think the answer is "no" because it would risk forking the network if such a transaction appears before everyone's upgraded, unless `unpack()` has a feature flag, which we don't have proper architecture to support right now.

**Comment by mvandeberg** [comment]
A couple of notes:

- `asset_symbol_type` has not had a specific serialization in steemd. Prior to changes to prepare for SMTs, it was a typedef integer and serialization was handled by `asset`. There was no need to serialize an `asset_symbol_type`. SMTs change that, so something does need to be added.

- The "special" numbers for system assets are invalid NAI numbers and are thus safe to use for system assets. (Note: you cannot serialize `00000001` as an integer, so it becomes `1`. This is where is comes from)  The purpose of having them identified in this way is to streamline to lookup of such symbols. We have discussed the possibility of Steemit publishing a dictionary of NAI to names. The process to convert this serialization to a readable string involves a lookup in this dictionary, therefore I believe it is a requirement that system assets conform to the same NAI formats as non-system assets. Your above proposal satisfies this requirement.

A number of these requirements need to happen for SMTs, but do not need to happen for Appbase compatibility with the future design.

The following requirements would become blockers for an Appbase release:

- [ ] Unit tests of all binary and JSON serializations of asset (asset_symbol_type not needed for Appbase release, but for SMTs)
- [ ] NAI integers and asset identifiers are internal identifiers that never appear in JSON or binary serializations. (I assume you mean appear alone. They are embedded in the NAI string)
- [ ] Special numbers are a dead end; delete or refactor all related code so system and non-system asset symbols are handled as similarly as possible in user-facing interfaces and (to the extent easily doable) internal code (For Appbase, this requirement is identical to the previous)
- [X] System assets binary serialize in legacy format
- [ ] System assets JSON serialize as ["amount", precision, "NAI string"]
- [ ] The NAI string for `SBD` is `@@00000001x` where `x` is determined according to the checksum function
- [ ] The NAI string for `STEEM` is `@@00000002x` where `x` is determined according to the checksum function
- [ ] The NAI string for `VESTS` is `@@00000003x` where `x` is determined according to the checksum function

There is one more requirement:

- [ ] The NAI string for invalid assets using the legacy binary format is `@@00000000x` where `x` is determined to the checksum function.

The rule of thumb for choosing these requirements is that System assets do not have the requirement for serializing `asset_symbol_type` by itself. Therefore, we can delay that aspect of the spec to SMT development.

The changes needed here are quite simple, replace the special number with defined NAI strings for system assets.

**Comment by mvandeberg** [comment]
We do not need to make a format for unknown symbols. The `legacy_steem_asset` forces canonical symbols. We should never have a legacy space asset that is unknown exist in the SMT compatible `asset`.

**Comment by theoreticalbts** [comment]
Updated above checklist, before my update only "System assets binary serialize in legacy format", but I checked that at present `develop` implements everything listed above.  Since the checklist is complete, are we ready to close this issue?

**Comment by mvandeberg** [comment]
The checklist above was just the subset for the appbase release.

From OP, I do not believe the following is complete:

- NAI strings starting with 0 are reserved for future assets and will not be assigned

However, that is an SMT specific implementation detail. Let's make an issue for completing the SMT NAI generation code along with this requirement and then close this issue. @youkaicountry Do you want to create that issue?

**Comment by youkaicountry** [comment]
Sure, I'll close this and create a new issue.

**Comment by theoreticalbts** [comment]
> NAI strings starting with 0 are reserved for future assets and will not be assigned

Good catch.

> From OP

Oops, I reviewed the checklist, but not OP.  That's how I missed it.  I reviewed the rest of OP and found the following should also have a new issue:

> Define and test a standalone serialization of `asset_symbol`, as some SMT operations require it. If this serialization includes a precision field, we need to review SMT operations specified and/or implemented for redundant precision values.

So @youkaicountry , that is two new issues to create.  Neither is a blocker for `appbase`.
