### ISSUE TITLE
Can't configure a witness node

### ISSUE THREAD

**Issue by dev00100000** [steemit/steem#203]
Hey there.

I am trying to configure a witness node. I am following the instructions on steem.io:

> Configure a Witness Node (Miner)
> A witness is any full node that processes and validates blocks. It is “witnessing” the real time blockchain. This is a necessary prerequisite to produce blocks. We start by synchronizing with an existing network and let the witness node create a data directory datadir for us that contains the default configuration file:
> 
> cd programs/witness_node
> ./witness_node -d datadir 

However, when I try to cd into programs/witness_node, it does not exist. I did an ls on the directory and the directory certainly does not exist. Here is what I have:

drwxr-xr-x  2 root root 4096 Jul 23 11:47 build_helpers
drwxr-xr-x  3 root root 4096 Jul 23 13:41 cli_wallet
drwxr-xr-x  2 root root 4096 Jul 23 12:49 CMakeFiles
-rw-r--r--  1 root root 1576 Jul 23 12:29 cmake_install.cmake
-rw-r--r--  1 root root  194 Jul 23 11:47 CMakeLists.txt
drwxr-xr-x  3 root root 4096 Jul 23 13:02 js_operation_serializer
-rw-r--r--  1 root root 5277 Jul 23 12:29 Makefile
drwxr-xr-x  3 root root 4096 Jul 23 13:02 size_checker
drwxr-xr-x  4 root root 4096 Jul 23 13:10 steemd
drwxr-xr-x  3 root root 4096 Jul 23 13:02 util

Then, I tried to "upgrade from source" by running this:

```
git fetch
git checkout <version>
git submodule update --init --recursive
cmake .
make
```

As it is detailed in the post on "How to Build Steem" on steem.io, but I received another error:

```
/steem/programs/cli_wallet/main.cpp:30:26: fatal error: fc/io/json.hpp: No such file or directory
 #include <fc/io/json.hpp>
                          ^
compilation terminated.
```

I didn't think I would need to upgrade, considering I had just pulled from source today, but thought I'd give it a shot anyway. Either way, I'm lost at this point.

**Comment by mvandeberg** [comment]
What OS are you building on?

In the meantime, the error with the cli wallet which is not a dependency of steemd. Run make targeting steemd, `make steemd` and that should get you up and running.

**Comment by dev00100000** [comment]
Ubuntu 16.04 Server

**Comment by realhagie** [comment]
I got the same problem - witness_node is just not there. Compiling of steemd works.
Debain 8 here

**Comment by realhagie** [comment]
Ok I think this can be closed - for some reason the witness code is build in as plugin into steemd right ? the doc is wrong at this point. 

thanks

**Comment by theoreticalbts** [comment]
@realhagie The `witness_node` build target was renamed to `steemd` very early in Steem development.  If any of our documentation refers to `witness_node`, it is many months out-of-date.  I'll take a look at it later.

**Comment by sneak** [comment]
Just realized this is a `steem.io` bug.
