### ISSUE TITLE
My account is "frozen" after I delegate 100% of my STEEM power

### ISSUE THREAD

**Issue by icaroharry** [steemit/steem#2030]
I'm not sure if this is actually an issue. But I delegated 100% of my STEEM power to @utopian_io through SteemConnect, now my bandwith is 0 (you can check here https://steemd.com/@icaro). This means that I can't make any transactions (including powering up). 

I'm thinking that one solution would be somebody delegate me a few STEEM power so I can power up or un-delegate. But I'm not sure if this would work.

Maybe it shouldn't be possible to delegate 100% of your STEEM power to avoid this kind of issue.

**Comment by TimCliff** [comment]
This technically is not the right forum for account support. Please go to the help channel of Steemit chat.

Regarding allowing it, some users may want to delegate 100% of their stake to another account if they don’t plan to use it (for a while or anymore). It really wouldn’t be correct to prevent it at a blockchain level. UIs could give their users a warning message, but that is a decision for the individual UI owners/operators to make.
