### ISSUE TITLE
Possible JSON serialization change to static_variant

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2044]
Currently, `static_variant` for `operation` uses strings, all other `static_variant` use integers.

It seems like it would be better to either always use strings, or always use integers.  If we make this breaking change, it seems like the appbase release is the best time to do this, lumping it together with all the other breaking changes.

For `condenser_api` we will probably have to create a legacy type hierarchy for everything that's returned.

Related: #2036

**Comment by mvandeberg** [comment]
There are many small static variants used for extensions. While I don't disagree with this change, the majority of the workload for this issue is the creation of the legacy types that would need to preserve the current serialization. I am hesitant to say we should do this because of how close Appbase is to a release candidate and the delay this would cause.

**Comment by mvandeberg** [comment]
After letting this sit for a few days, I am in agreement with this change. The effect for JSON is that is turns a numeric indexed tuple into a dictionary, which I believe makes much more sense from the perspective of self-documentation.

@goldibex Thoughts?

**Comment by goldibex** [comment]
are we talking about changing the shape of the object altogether? let's document this.

per @theoreticalbts, right now a `static_variant` can take on one of two shapes in json:
```json
[1, { "hello": "world" }]
["transfer", { "from": "foo", "to": "bar", "amount": "50.0 STEEM" }]
```
these 2-tuples are really not at all idiomatic JSON (in fact I'd argue they aren't idiomatic anywhere, even Python). Nevertheless, this is the shape of the object, and there's an awful lot of code out there that depends on this particular shape.

I would propose the following for immediate work:
- When represented in JSON, all `static_variant` objects should be representable using either the numeric index or the string name of the underlying type.
- the current JSON serialization for all objects should be documented and frozen.

There is a much bigger, longer-term conversation we need to have about serialization. I would argue that steemd itself should not be doing anything with JSON at all. But that's outside the scope here.

**Comment by mvandeberg** [comment]
> When represented in JSON, all static_variant objects should be representable using either the numeric index or the string name of the underlying type.

Currently, only the `operation` static variant allows representation using the string name of the underlying type. And it omits `_operation` at the end of the typename (`transfer_operation` in C++ is serialized as `transfer`). And it appears that Condenser is heavily dependent upon it. In #2036 when the wrong op name was returned, Condenser simply spat out raw JSON.

The serialization is inconsistent across static variants and doesn't even follow the rule that would make the most sense when it attempts to follow a somewhat reasonable convention.

**Comment by goldibex** [comment]
Condenser may not be the only code dependent on this behavior. I'm afraid we'll probably have to leave a shim in place temporarily to allow all of these for operations:
```json
[ 1, ... ]
[ "vote_operation", ... ]
[ "vote", ... ]
```

With the explicit commitment that the shimmed version ("vote") is deprecated from this point forward and will eventually be removed.

So are we in agreement about this short-term plan?
1. Unify JSON serialization of `static_variant` types as a 2-element array for which the first element is _either_ the integer index of the concrete type _or_ the string name of the concrete type.
2. Shim the `operation` `static_variant` to continue to support it without the `_operation` suffix, but on the explicit understanding that it is deprecated.
3. Document and freeze the JSON serializations of all types we currently expose via API.

**Comment by mvandeberg** [comment]
I disagree slightly about point 2. We can change the default static_variant serializer and then overload the old format for specific static_variants in `condenser_api`.

We are already doing this with `legacy_operation` static variant, which uses yet another overloaded serializer because it needs to convert type names. Legacy operations are operations which have assets that need to be serialized in the legacy format. `legacy_` was prefixed to avoid confusion in the source code. When serialized, `legacy_transfer_operation` is transformed to `transfer`. If we want to support the `_operation` suffix format for this static_variant, then this serializers needs tweaking. If not, we are good to go as is.

We also need to create overloads for all other static variants that can be returned via Condenser API to be returned as expected. While some of the changes may not break Condenser API we should assume changing the format breaks other apps. This is where the bulk of the work will be. Based on what it took to get the asset serializations done, I estimate this at 1-2 days of work for me.

**Comment by mvandeberg** [comment]
Tested on a local endpoint.

New Serialization:

```
{
"ref_block_num": 60078,
"ref_block_prefix": 3791822430,
"expiration": "2018-01-15T13:18:03",
"operations": [
[
   "comment_operation",
   {
      "parent_author": "",
      "parent_permlink": "",
      "author": "",
      "permlink": "",
      "title": "",
      "body": "",
      "json_metadata": ""
   }
],
[
   "comment_options_operation",
   {
      "author": "",
      "permlink": "",
      "max_accepted_payout": [
      "1000000000",
      3,
      "@@000000013"
      ],
      "percent_steem_dollars": 10000,
      "allow_votes": true,
      "allow_curation_rewards": true,
      "extensions": [
      [
         "comment_payout_beneficiaries",
         {
            "beneficiaries": [
            {
               "account": "esteemapp",
               "weight": 500
            }
            ]
         }
      ]
      ]
   }
]
],
"extensions": [

],
"signatures": [
"205a3d1d37f1cf5ce6da7f96a5b38289c951d0b4b784bc2be9bd7294d4e644d5a7776bd52361e7959dbf75268300e546cd353a59cd02f5a6148dedc8ff449ae1fa"
]
}
```

Old  Serialization:

```
{
"ref_block_num": 60078,
"ref_block_prefix": 40542,
"expiration": "2018-01-15T13:18:03",
"operations": [
   [
   "comment",
   {
      "parent_author": "",
      "parent_permlink": "",
      "author": "",
      "permlink": "",
      "title": "",
      "body": "",
      "json_metadata": ""
   }
   ],
   [
   "comment_options",
   {
      "author": "",
      "permlink": "",
      "max_accepted_payout": "1000000.000 SBD",
      "percent_steem_dollars": 2,
      "allow_votes": true,
      "allow_curation_rewards": true,
      "extensions": [
         [
         0,
         {
            "beneficiaries": [
               {
               "account": "esteemapp",
               "weight": 500
               }
            ]
         }
         ]
      ]
   }
   ]
],
"extensions": [

],
"signatures": [
   "205a3d1d37f1cf5ce6da7f96a5b38289c951d0b4b784bc2be9bd7294d4e644d5a7776bd52361e7959dbf75268300e546cd353a59cd02f5a6148dedc8ff449ae1fa"
],
"transaction_id": "7b33df210685947c8fccfa242206fb4b259ccb0e",
"block_num": 0,
"transaction_num": 0
}
```

Apologies on some of the indentation. It got screwed up copying it around.

**Comment by mvandeberg** [comment]
The recent decision was made to eliminate the use of tuples in our JSON serializations. Due to this change, the static_variant serialization will now be `{"tag":"TAG", "object":{}}`.

`static_variants` in `condenser_api` are of course unchanged.

**Comment by mvandeberg** [comment]
Rather than `tag` and `object` fields I think `type` and `value` better represent the `static_variant`. Those will be used instead.
