### ISSUE TITLE
smt_setup_operation does not contain launch_expiration_time

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2048]
The `launch_expiration_time` field specified in the whitepaper does not exist in the operation.

**Comment by vogel76** [comment]
validate method shall accordingly check launch_expiration_time value similary to other fields.

**Comment by Kiwonik** [comment]
I added a positive and negative case of added field to newly created validation test. The code  testing other fields is awaiting in implementation of issue https://github.com/steemit/steem/issues/1508
