### ISSUE TITLE
Implement SMT emissions

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2053]
Some stub implementation of this operation is present, it just stores the values in the operation in `smt_token_object`.  The following changes need to be made to create a full-fledged implementation:

- Emission events need to be generated and processed.  There are spec changes proposed in #2052 for events to be an operation, rather than completely autonomous.

- It is not 100% clear from the whitepaper, but it is possible to issue multiple `smt_setup_emissions_operation` per SMT.  The net effect of multiple such operations is to have *all* the specified emissions schedules execute.  This means the relevant fields cannot be stored in `smt_token_object`, they must be split out into their own object, which may be many-to-one with SMT.

- If we implement #2052 then such objects will each need an identifier, which is specified in the ping operation.

**Comment by youkaicountry** [comment]
Outdated.
