### ISSUE TITLE
Whitepaper / steemd consistency CI

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2055]
We should have some way to automatically enforce that:

- Each `struct` in the whitepaper matches what's implemented in `steemd`
- The JSON in the whitepaper matches what's implemented in `steemd`

I've made scattered notes in various tickets about mismatches I've found, but there may be more.  Let's automate them away.

**Comment by mvandeberg** [comment]
When I have merged SMT PRs, I was assuming they were being checked against the spec in the white paper. Some of the differences are name changes that I know where discussed in issues or Slack and don't seem to have been changed in the whitepaper. I am not sure using the whitepaper as the source of truth for SMT structs is the correct course of action. I am also not convinced instrumenting this automation that is not really needed beyond initial development is a good use of developer resources.

**Comment by MRgithubs** [comment]
try

**Comment by youkaicountry** [comment]
Enforcing the whitepaper is correct will be implicit in SMT issues going forward.
