### ISSUE TITLE
Market maker trade execution

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2057]
OK, so the overall strategy for implementing the MM is as follows:

- The MM has balances of Steem and tokens and some internal parameters
- It will update these parameters according to certain external events (for example token emissions)
- Based on its balances and internal parameters, it will generate trades to execute
- Those trades will be executed by the same functions that execute user trades

In this ticket, we will discuss some of the rough edges for the execution part of this.

- The market maker isn't an account.  The existing order processing code may need to be refactored to expose the token flows directly, rather than adjusting account balances as a side-effect.
- The market maker's order semantics may not be implemented.  The semantics I envision for the market maker's orders are "fill this order against any matching orders, then immediately cancel it."  The existing orders include a fill-or-kill order type, but I'm not sure if that order type allows partial fills.
- Rounding.  All rounding of MM transactions should be in the MM's favor.  We need to be sure the existing code does this.

**Comment by youkaicountry** [comment]
Closing as outdated.
