### ISSUE TITLE
Make testnets die at a hardcoded time / height

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2064]
We don't want to risk testnets becoming long-lived and starting to, say, take on economic value of their own.  The simplest fix is to implement the following restrictions for testnets:

- Forbid new blocks to have timestamp greater than the timestamp of block 1 plus some fixed interval [1]
- Forbid new blocks to have a height greater than some fixed constant

[1] We need the timing to be relative to a block in the past, rather than an absolute number, to be sure we can always start up a new testnet without editing `steemd`.

**Comment by mvandeberg** [comment]
This looks like a duplicate of #1732

**Comment by theoreticalbts** [comment]
I guess it is.  Closing.
