### ISSUE TITLE
Steem Developer forum or mailing list

### ISSUE THREAD

**Issue by lonnieOST** [steemit/steem#2080]
Hello, 

I am  sorry if this is not the correct place to post this, but I am looking for a Steem Developers Forum or Mailing List and the only thing that I have come across is the SteemChat site, which is mainly for general users from what I can tell.

I am looking to work on a project using the Steem core and Condenser as part of  the work  and am trying to find a developer that I can either work with or possibly offer a small contract to do some work on the project but did not know where to find such a person.

Any help would be greatly appreciated.
Thanks and have a great day

**Comment by TimCliff** [comment]
@lonnieOST there are some community developers that discuss Steem development topics here:
https://discord.gg/B29Bbng

**Comment by lonnieOST** [comment]
@TimCliff Thanks for the link and I'll look closer at it to see what I can locate.  If you happen to know of anybody, or perhaps you yourself, that might be interested in some small side job working with setting up a private TESTNET of Steem-core and Condenser in a Docker environment with some modifications then please let me know as I would be happy to discuss it more with them as well. Thanks again. :)

**Comment by Karimai** [comment]
You may find these links useful :
https://steemit.com/steemit/@aschatria/resources-steemit-discord-server-list-50-steemit-related-discord-servers

https://steemit.com/discord/@pivx100/top-5-steemit-discord-server

**Comment by youkaicountry** [comment]
Closing.
