### ISSUE TITLE
Separate state.hpp from database_api.hpp

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#209]
The `database_api.hpp` file returns `extended_account` objects which are defined in `state.hpp`.
- The database API should be a very basic, minimal API to get the data from the database, with a philosophy of "return what the user asked for, and no more."
- The API calls provided by the web plugin should be a comprehensive, maximal API to get all possibly relevant queries, with a philosophy of "return everything a UI client needs, to minimize round trips per page render."

The web stuff needs to be separated into a plugin, and the first step in doing that is removing all web-specific functionality from database_api.

**Comment by mvandeberg** [comment]
Backlogging this for when the UI isn't reliant on get_state.

**Comment by mvandeberg** [comment]
This is handled in #1265
