### ISSUE TITLE
CI Smoketest

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2098]
Write a script which does the following:

1. Run steemd in reindex mode up to a chosen number of blocks (such as 3M)
2. Run dedicated tests which compare results to a reference instance (which is built from the last revision which completed CI). 

The reference instance is manually configured (and stays running) before starting smoke-test.
AH dedicated tests for now cover calls to get_ops_in_block for specified number of blocks and get_account_history for all accounts.

This should be configured in such a way to ensure it doesn't take too long (ie no more than 20 minutes), and will be run as part of CI.

**Comment by theoreticalbts** [comment]
So basically there are some problems:

- Updating to a fixed block height of the main network doesn't exercise new features.  If we test it with the mainnet, we need to make sure that it updates to (nearly) the present.  Testing with testnet may be better for the per-build run.
- Testing via API is slow and requires a complicated test script.   An easier way is to dump state into a cross-platform format ( #854 ) and compare it.

**Comment by youkaicountry** [comment]
Merged.
