### ISSUE TITLE
Block Timestamp Validation?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#21]
If a witness produces a block with a timestamp 100 years in the future, will the whole network get frozen / manipulated?
See https://github.com/cryptonomex/graphene/issues/645 for reference.
Since miners are out of control, the issue in STEEM is much more serious than which in BitShares.

**Comment by abitmore** [comment]
Probably should validate it within [this code block](https://github.com/steemit/steem/blob/3bb37ad275d35f1cb9181beb0d8773fb137e023a/libraries/chain/database.cpp#L1913-L1934)

**Comment by abitmore** [comment]
Related BitShare 0.x code: [link 1](https://github.com/bitshares/bitshares-0.x/blob/master/libraries/blockchain/chain_database.cpp#L814-L815), [link 2](https://github.com/bitshares/bitshares-0.x/blob/master/libraries/blockchain/chain_database.cpp#L2051-L2057)

**Comment by bytemaster** [comment]
@abitmore the database is unaware of external data such as "time".  The proper place to validate this is upon receipt from the network in the application library.
