### ISSUE TITLE
Roadmap for API overhaul

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#210]
There are many architectural issues in the API:
- Inconsistent pagination.  Some API calls are paginated, some aren't.  All API calls need to be checked for potential unlimited-size responses and proper pagination specifications designed and implemented.
- API calls should take and return structs, so adding additional arguments or returning additional information is possible in a reasonably backwards-compatible manner.
- Database API should be split up into several smaller API's.
- API's which require specific history plugins to be loaded should be placed into plugin-specific API's.
- No API's except the login API should be loaded by default.
- Web-specific stuff needs to be moved into its own set of plugins.
- Web-specific stuff needs to be made modular.

Here is a rough plan of action:
- Develop the new API's as an out-of-tree plugin set.
- When new API is tested and interface is stable, add submodules for core functions to tree, move old API's to out-of-tree "legacy" plugins.
- When all API clients (UI + exchanges + key third-party tools) have upgraded, stop maintaining legacy plugins.

**Comment by mvandeberg** [comment]
Related #209

**Comment by mvandeberg** [comment]
Related #1265

Some of the changes will satisfy this refactor.

**Comment by mvandeberg** [comment]
This is handled by Appbase
