### ISSUE TITLE
Signup is broken for Brazilian Mobile Phone Numbers!

### ISSUE THREAD

**Issue by queirozfcom** [steemit/steem#2106]
I cannot sign up. I am in Brazil and it seems the javascript form validation (on https://signup.steemit.com/) does not know that our mobile phone numbers now have 9 numbers (plus 2 area codes) instead of 8!! 

**I'm aware that this may not be the best place to file issues on the website's UX** but where can I file an issue about this then?

**Comment by mvandeberg** [comment]
I have gone ahead and made mention of this problem in the relevant repo. Thank you for bringing this to our attention.
