### ISSUE TITLE
Charge bandwidth per op

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#2120]
**Making some tests to discover how and how much bandwidth is usually charged, I discovered/realized that, at least in some cases, every user involved in a tx get charged for the full tx.**
### Following a test I made:
- In tx 1) there is one single vote op to reward post X, the signer of the tx is also the voter.
   ---> It gets charged 171 bytes for it.
- In tx 2) there are 128 votes that reward the same post X. All voters share 1 signing authority, so there is only one signer who is the same as tx 1) but this time it doesn't vote in tx 2).
    ---> **Every** voter is charged 11928 bytes and the signer is not charged at all

tx 1) https://steemd.com/tx/2ca184e9518e5aa0587107f4a61b88623d841c11
tx 2) https://steemd.com/tx/3818fc72b0965e3b2a1a78441927214c81b3bec7

### To note:
a) If every voter in 2) had voted individually, the total blockchain space used would have been ~171*128=21888 bytes
b) Grouping all ops in one single tx lowered the space used to 11928 bytes, **saving almost 50%** (the more ops are grouped, the more space is "saved", ofc)

Unfortunately, grouping all ops in one single tx led every user to be charged for the full tx.
In that example they were charged approximately **93** times more than what they would have been charged if voted as 1). Considering a) and b), this behavior doesn't really make sense.

### Charge bandwidth per op:
I think it's more reasonable and fair if every user is charged only for his own operation.
At that point tho the tx overhead is not charged for, so it should:
A) be divided among all users OR B) be charged to the signer/s of the tx (probably easier?)

Another option would be to keep charging for the whole tx, but really charge only the signer/s depending on how many ops are using their authority

I think the first option is probably better, any way you surely know better how to handle it

**Comment by BhuzOr** [comment]
@mvandeberg @theoreticalbts 
Are you guys considering charging bandwidth per op with the new RC Bandwidth system?
How will the above scenario be handled?

**Comment by theoreticalbts** [comment]
First of all, this is a really rare scenario in practice.  People tend not to bundle multiple ops that require different signers into a transaction.

That being said, the current behavior of charging everyone who uses the transaction the full cost of the transaction is not great.

The solution I've implemented in the new bandwidth plugin (RC plugin) is to "charge" each transaction to the required authority of the first op in the transaction.

Here's the exact algorithm [1]:

```
account_name_type get_resource_user( const signed_transaction& tx )
{
   flat_set< account_name_type > req_active;
   flat_set< account_name_type > req_owner;
   flat_set< account_name_type > req_posting;
   vector< authority > other;

   for( const operation& op : tx.operations )
   {
      operation_get_required_authorities( op, req_active, req_owner, req_posting, other );
      for( const account_name_type& account : req_active )
         return account;
      for( const account_name_type& account : req_owner )
         return account;
      for( const account_name_type& account : req_posting )
         return account;
   }
   return account_name_type();
}
```

This code's in a public branch on Github, but it's still undergoing intense development.

[1] For the *normal case* of a transaction whose first op has a single required account, this algorithm selects that account.  This algorithm also has reasonable handling of rare pathological cases where the first op has *no* required authority (in that case, you continue scanning until you see an op that does have one), or *multiple* required authorities.(in that case, prefer active to owner to posting, and within an authority type, prefer the first account alphabetically).

In the case of an operation which somehow has *no* required account authorities, it returns `account_name_type()`, which causes other code to reject the transaction from entering the local node's pool or locally produced blocks.

**Comment by BhuzOr** [comment]
Thank you for the reply. I am not sure on some points, please bear with me.

> First of all, this is a really rare scenario in practice. People tend not to bundle multiple ops that require different signers into a transaction.

The example above shows the grouping of multiple ops that require **the same** account authority/signer (all those voting users share the same account in their posting authority, and that single account is used to sign the tx).

I can agree that it is not a very common scenario, but it's not so rare either. Lots of services out there require the user to add the "service account" to the user authority. Those services then use their own account to make ops "in the name" of the user. Think about voting trail services like streemian and autosteem, or even UIs and applications like busy.org, dtube, dlive, esteem etc, all require their user base to add the app's account to their authority, and then use that single account to sign for the user made ops. All these services could and probably should group as many ops as they can on a single tx to save on txs overhead (I don't know if they are doing it already or not).

(Btw I thought it was not possible to bundle, in the same tx, ops that require **different** signers...)

> This algorithm also has reasonable handling of rare pathological cases where the first op has [...] multiple required authorities.(in that case, prefer active to owner to posting, and within an authority type, prefer the first account alphabetically).

I am not sure to follow this. To me it seems like an op (or a full tx) made by user A could be charged to user B just because B is in the A's account authority.
This would open an attack vector... But probably I am just misunderstanding?

**Comment by youkaicountry** [comment]
RC bandwidth accomplishes this.
