### ISSUE TITLE
No approval email same on steemit chat

### ISSUE THREAD

**Issue by casperjakobsen19** [steemit/steem#2121]
Hello 
so i made my signup at https://signup.steemit.com/
i put my username, email and phone but still no email for the approval :(

i then go to https://steemit.chat and signup there so i can get some help but not even here i get my email after i signed up 

what is actually going on here?
tried both gmail and hotmail nothing works

**Comment by sciborg** [comment]
steemit.com I cant help with but steemit.chat signups are supposed to be instant and you should have received an email immediately.. can you try again on steemit.chat and also make sure to check your spam folder

**Comment by casperjakobsen19** [comment]
tried on 3 different emails checked spam in all 3 no email

**Comment by casperjakobsen19** [comment]
no one can help not even steemit them sef nice!

**Comment by casperjakobsen19** [comment]
BUUUUUUUUUUUUUMP

**Comment by mvandeberg** [comment]
This repo is not for customer support and Steemit does not control steemit.chat. If there is a problem with steemit.chat signups, we are unable to help you.

**Comment by casperjakobsen19** [comment]
WAOW nice company
