### ISSUE TITLE
Steemd JSONRPC problems

### ISSUE THREAD

**Issue by xallavon** [steemit/steem#213]
1. I can not use steemd `network_broadcast_api` over jsonrpc. It only allows methods from first public api, specified in config. Any ideas on how to use it?
2. I can not use string request id, though it is enabled by jsonrpc specification. Steemd/cli_wallet both return me a 'parse error' message.

**Comment by theoreticalbts** [comment]
For (1), read [here](https://github.com/steemit/steem/blob/master/doc/api-notes.md) about the API.  The TLDR version is to use a JSON request like this:

    curl --data '{"jsonrpc": "2.0", "params": ["network_broadcast_api", "broadcast_transaction", [YOUR_TRANSACTION_GOES_HERE]], "id":1, "method":"call"}' http://127.0.0.1:8090/rpc

For (2), this is a legitimate issue, but it's not going to be a priority.

**Comment by theoreticalbts** [comment]
Added ticket with more descriptive name to specifically discuss second issue, closing this one.
