### ISSUE TITLE
Steem node not syncing

### ISSUE THREAD

**Issue by DSofter** [steemit/steem#2132]
Hello guys,

I was trying to start a Steem node and following this tutorial:

https://steemit.com/witness-category/@klye/the-complete-noob-guide-to-steem-witness-setup

The blockchain archive link in the above article didn't work, so i downloaded `block_log` from here https://gtg.steem.house/get/blockchain/block_log instead and moved it to `steem/programs/steemd/witness_node_data_dir/blockchain`. 

And then I ran `./steemd --replay` under `steem/programs/steemd/`, and then I saw this:

![image](https://user-images.githubusercontent.com/1687829/36336482-0a4c0c2c-133d-11e8-85c0-077894c7c1d9.png)

And it's just stuck there forever.

Anything I'm missing here?

Thanks!

**Comment by TimCliff** [comment]
Try checking out and rebuilding with the ‘stable’ branch

**Comment by DSofter** [comment]
@TimCliff Thanks for responding! I did nothing since I posted the issue, and it's syncing now:

![image](https://user-images.githubusercontent.com/1687829/36345903-980a2cd2-13e8-11e8-87cc-b190034ba030.png)

Maybe it's just slow. However, I noticed something else:

![image](https://user-images.githubusercontent.com/1687829/36345905-a41780e2-13e8-11e8-8bf2-7b77b135c661.png)

The node seems to have ignored the `block_log` file I downloaded (it never changed in size) and has been writing to `shared_memory.bin`. Is that something I should expect?

Thanks!

**Comment by mvandeberg** [comment]
That is the log of a reindex from block_log, not a sync. It would appears to be working exactly as you expected. Slowness might be due to certain plugins being enabled incorrectly or even erroneously. Because there is no bug to report in this issue, I am closing it.
