### ISSUE TITLE
Steemit Login

### ISSUE THREAD

**Issue by IqraKausar** [steemit/steem#2133]
Hi,

I know that this may not be the appropriate forum to air my discontent, but I have tried signing up for Steemit and it has now been over a week and no response yet.  I just got the confirmation code via mobile and was then asked to wait for confirmation e-mail.  Fast forward, seven days, and nothing yet.

Hoping that there is not a secret handshake involved here :D  For someone who is actually trying to jump ship from Facebook and wants to actively engage with this exciting new platform, it is disconcerting that no follow-up e-mail is sent to let an individual know how long they may have to wait or what the current status of their request it.

I still like the platform and what you are trying to do but looking at the number of rants along this line posted on Google, I think your team should look into this issue if you are serious about disrupting the social media space.

Thank you,
Iqra

**Comment by TimCliff** [comment]
The signup process is through steemit.com. This is the repository for the Steem blockchain, which is unrelated to the signup process. This repository is not the appropriate place to discuss this issue.

You can use any of the third party (paid) services to signup for an account (listed on the steemit.com FAQ page) or ask for help in the steemit chat #help channel for assistance with a steemit.com signup.
