### ISSUE TITLE
Must contributions be processed in FIFO order?

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2138]
In #1694 @mvandeberg claims:

> The contributions would need to be processed FIFO because of the soft cap.

I am not sure this is true.  I think we may be able to avoid FIFO processing if we record information iteratively.  An unknown set of contributions could be withdrawn in the case of a failed launch where some refunds are claimed.

**Comment by mvandeberg** [comment]
ICO contribution rewards have already been implemented and this discussion is stale.
