### ISSUE TITLE
SBD in orders not qualified for interest?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#214]
According to the [code](https://github.com/steemit/steem/blob/v0.12.2/libraries/chain/database.cpp#L3234), `sbd_seconds` only increases by `sbd_balance * seconds`, so the amounts in orders are not counted in. IMO it is not good for internal market makers.

It could be fixed by adding and tracking a `sbd_in_orders` field in `account_object`.

**Comment by theoreticalbts** [comment]
Orders do not receive interest by design.
