### ISSUE TITLE
Cannot Sign Up

### ISSUE THREAD

**Issue by nyl9488** [steemit/steem#2143]
Hello guys.... i facing issue when creating steemit account, its show Phone number already used. How to solve it? And also cannot get email from steemit

**Comment by TimCliff** [comment]
This is not an issue that should be reported in GitHub. Please ask for help in the Steemit chat #help channel.

**Comment by nyl9488** [comment]
I cant register at Steemit Chat also..... Canot login and forgot password is not working

**Comment by TimCliff** [comment]
Message me (TimCliff) here in discord: https://discord.gg/HYj4yvw and I’ll respond within 24 hours.
