### ISSUE TITLE
Steemit Verification Mail?

### ISSUE THREAD

**Issue by nikolap99** [steemit/steem#2146]
I don't know if this is appropriate place to ask, but wherever I asked, no clear answer was given.
So I (kinda?) made the accoount on steemit.com and I guess I was supposed to get the verification e-mail, but it never arrived.
I first thought it might be some problem with signing up, so I tried to make account again. My e-mail "nikolapavlov33@gmail.com" and username "nikolap99" were free for choosing, but for my phone number, it said that it was taken.

Can someone explain a little more clear how is the system functioning, and how much is the ususal wait time, and why?
Thanks in advance!

**Comment by TimCliff** [comment]
Please read the steemit.com FAQ. This issue does not belong in GitHub.
