### ISSUE TITLE
Account Recovery Not Working

### ISSUE THREAD

**Issue by r351574nc3** [steemit/steem#2150]
I tried account recovery, but I am getting an error  

```
{"cause":{},"isOperational":true}
```

How do I get my account into `isOperational: false`?

**Comment by bnchdrff** [comment]
Hi @r351574nc3 -- that looks like a bluebirdjs (frontend library) error -- it will be very hard to diagnose this issue unless you have some more info :)

can you open an issue at https://github.com/steemit/condenser/issues/new with additional information?

**Comment by r351574nc3** [comment]
See condenser#2561

**Comment by r351574nc3** [comment]
@bnchdrff Any way we can reopen this? steem-js has open PRs that go back to October last year. That project has all the signs of a dead project. I don't think I will get a response there.

**Comment by mvandeberg** [comment]
AFAIK, steem-js is not dead. It may not be under active development right now, but we use it extensively in projects. It is certainly not dead.

I hate to keep bumping you around, but if you are going to reopen an issue, open it in Condenser. What you are experiencing is further up in the software stack than steemd. I can 100% not fix it here. Condenser at least has a shot fixing it there.

**Comment by r351574nc3** [comment]
@mvandeberg thanks for responding ^_^

Ok. Well, that's what I meant. It's not active.

I am going to try this https://github.com/steemit/condenser/blob/master/src/server/api/account_recovery.js#L224

and if it fails, I'll reopen. Thanks so much.
