### ISSUE TITLE
Allow string ID for JSONRPC messages

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#216]
Continuing discussion of the second issue raised in #213:  Namely, FC's JSON-RPC implementation is not spec-compliant as it doesn't allow string ID's.

I think the problem is [here](https://github.com/steemit/fc/blob/c672e3b4b4676ee90a63dbee4179207bbcd14e56/src/rpc/json_connection.cpp#L150-L151) -- basically we do internal bookkeeping with `_awaiting` which is declared as a `map` using `uint64_t` as its key.  I'm not sure `variant` (the FC type representing a JSON object) has the right interface to be used as a key in a map, and I'm sure that changing it to anything other than a uint64 will have negative performance implications.

I'm tempted to tag this wontfix, but we should strive to be spec-compliant.

**Comment by mvandeberg** [comment]
Will be fixed in #1265
