### ISSUE TITLE
New logging config does not work

### ISSUE THREAD

**Issue by clayop** [steemit/steem#2166]
```
log-console-appender = {"appender":"stderr","stream":"info"}
```
Given the above option, console stream does not show `info` logs. I added old config;
```
[log.console_appender.stderr]
stream=info
```
then it works,

**Comment by mvandeberg** [comment]
What branch are you running?

**Comment by mvandeberg** [comment]
For the record, this is the logging config I use for development:

```
# Console appender definition json: {"appender", "stream"}
log-console-appender = {"appender":"stderr","stream":"std_error"}

# File appender definition json:  {"appender", "file"}
log-file-appender = {"appender":"p2p","file":"logs/p2p/p2p.log"}

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"debug","appender":"stderr"}
log-logger = {"name":"p2p","level":"info","appender":"p2p"}
```

**Comment by clayop** [comment]
`0.19.4rc1`
Can you test console stream as `info`?

**Comment by mvandeberg** [comment]
Look at your config for `log-console-appender`. The stream is the console stream name, not the log level.

When you went back to old config, did you add it or replace the new config?

**Comment by clayop** [comment]
I copy-pasted the config in [this repo](https://github.com/steemit/steem/blob/master/contrib/config-for-broadcaster.ini) and made little tweak.

**Comment by abitmore** [comment]
@clayop your little tweak made it wrong. Specifically, you changed it to `"stream":"info"`, but "info" is not a standard stream name.

**Comment by clayop** [comment]
I see thanks
