### ISSUE TITLE
Building on macOS with Apple LLVM version 9.0.0 (clang-900.0.39.2)

### ISSUE THREAD

**Issue by dacom-dark-sun** [steemit/steem#2167]
Google give to me reference, that problem on interaction between new version of clang (XCode) and Steem code. I can't downgrade now (internet toooo slooow), so, that mean i can't build it :-( 

Or may be some other reasons of this trouble or directions to fix it? 

> [  4%] Built target project_secp256k1
> [  5%] Built target equihash
> [ 35%] Built target fc
> [ 35%] Built target log_test
> [ 36%] Built target ecc_test
> [ 37%] Built target blinding_test
> [ 37%] Built target hmac_test
> [ 38%] Built target bloom_test
> [ 44%] Built target all_tests
> [ 45%] Built target real128_test
> [ 46%] Built target bip_lock
> [ 47%] Built target ntp_test
> [ 48%] Built target task_cancel_test
> [ 49%] Built target blind
> [ 49%] Built target api
> [ 49%] Building CXX object libraries/schema/CMakeFiles/graphene_schema.dir/schema.cpp.o
> In file included from /Users/darksun/dacom-code/Vox/libraries/schema/schema.cpp:2:
> In file included from /Users/darksun/dacom-code/Vox/libraries/schema/include/graphene/schema/schema.hpp:5:
> In file included from /Users/darksun/dacom-code/Vox/libraries/schema/include/graphene/schema/schema_types.hpp:7:
> In file included from /Users/darksun/dacom-code/Vox/libraries/schema/include/graphene/schema/schema_types/static_variant.hpp:7:
> /Users/darksun/dacom-code/Vox/libraries/fc/include/fc/static_variant.hpp:385:34: error: class template partial specialization is not more specialized than the
>       primary template [-Winvalid-partial-specialization]
>   template<typename... T> struct get_typename<T...>  { static const char* name()   { return typeid(static_variant<T...>).name();   } };
>                                  ^
> /Users/darksun/dacom-code/Vox/libraries/fc/include/fc/reflect/typename.hpp:18:30: note: template is declared here
>   template<typename T> class get_typename{};
>                              ^
> 1 error generated.
> make[2]: *** [libraries/schema/CMakeFiles/graphene_schema.dir/schema.cpp.o] Error 1
> make[1]: *** [libraries/schema/CMakeFiles/graphene_schema.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by mvandeberg** [comment]
The problem is in the fc submodule. `steem/master` has a newer version of fc with this fixed. There are changes in fc that makes `fc/master` incompatible with `steem/stable`. If you want to apply the fix directly, [here](https://github.com/steemit/fc/commit/d3610bf4de153d58d4a99ff2c83ebbc39328f514) is the commit.

`steem/master` has fc vendored in. If you want to switch and build `master` instead you will need to deinit the fc submodule prior to checkout.

**Comment by dacom-dark-sun** [comment]
After checkout libraries/fc to d3610bf4de153d58d4a99ff2c83ebbc39328f514, cmake it and run build, i have error above. Anything else?  

[ 17%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o
/Users/darksun/dacom-code/vox/libraries/fc/src/rpc/state.cpp:47:12: error: no matching constructor for initialization of 'fc::rpc::request'
   request request{ "2.0", _next_id++, method_name, std::move(args) };
           ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/darksun/dacom-code/vox/libraries/fc/include/fc/rpc/state.hpp:7:11: note: candidate constructor (the implicit move constructor) not viable: requires 1
      argument, but 4 were provided
   struct request
          ^
/Users/darksun/dacom-code/vox/libraries/fc/include/fc/rpc/state.hpp:7:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 4 were provided
/Users/darksun/dacom-code/vox/libraries/fc/include/fc/rpc/state.hpp:7:11: note: candidate constructor (the implicit default constructor) not viable: requires 0
      arguments, but 4 were provided
1 error generated.
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/rpc/state.cpp.o] Error 1
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make: *** [all] Error 2

**Comment by mvandeberg** [comment]
Cherry pick the commit onto `stable`'s fc. Other changes to fc make it incompatible with `stable`.
