### ISSUE TITLE
Waiting for the “approval” is not a biggie, but waiting for an approval without knowing for how long to wait, is quite frustrating

### ISSUE THREAD

**Issue by Ronneback** [steemit/steem#2169]
Dear Steemit Team,
I have been trying to signup on Steemit since 5 weeks. Unfortunately the registration verification email that I should receive after the phone verification does not arrive. I have tried several times and also cleared cookies. Anyone who knows what to do to solve the issue and start add valuable content to the community? 
Waiting for the “approval” is not a biggie, most of people would understand, especially in a Beta phase. But waiting for an approval without knowing for how long to wait, is quite frustrating. It would be great if there would be somehow a countdown, or a time-note, or waiting list number, or something that would the “applicants” know for how long they have to wait.
Also an official contact channel would be a great idea 😊. Slack, Facebook, Twitter – you name it.
Thank you.
/ronneback

**Comment by TimCliff** [comment]
Please refer to the FAQ page on steemit.com.
