### ISSUE TITLE
UX: steemd does not start with sane defaults

### ISSUE THREAD

**Issue by sneak** [steemit/steem#2176]
Starting steemd without a `witness_node_data_dir` does not cause the blockchain to sync.  It should.  This means that seednodes should be compiled in, and should be populated in config.ini if and only if the config.ini doesn't exist and is being created.  If the config.ini already exists, the compiled-in seed nodes should be ignored.

**Comment by sneak** [comment]
It also doesn't specify any plugins, so it isn't useful for anything with the default config.  Simply running `steemd` should bring up a node that a) syncs and b) does something minimally useful.

**Comment by mvandeberg** [comment]
chain_plugin, p2p_plugin, and webserver_plugin are always enabled in the binary. So long as seeds are specified, steemd will sync with no plugins specified.

**Comment by sneak** [comment]
I'm saying we should bake in some sane defaults that are used when writing out a config file so that the user doesn't have to start steemd, control-c, get seeds, edit config file, save config file, restart steemd.

**Comment by Gandalf-the-Grey** [comment]
Ot maybe some middle-ground?
`steemd` run without specifying `--data-dir` (aka `-d`) will create default dir in `$HOME/.steem/steemd` (per #2177) with default config and exit (assuming that default config is just a template that user need to review and optionally tweak to their needs before starting such resource intensive operation as resync.
Alternatively above process can get content of `doc/seednodes.txt` if available (installed to a known location during `make config` or so) and use it for generating default `config.ini` file.

**Comment by sneak** [comment]
no, compile the seednodes in so the default config file writes them out. 

also, the first launch with no data dir and no config file should not exit - it should sync and do something useful.

**Comment by mvandeberg** [comment]
The default config will be updated with the following:

The default data directory will be `$HOME/.steem`

For the mainnet, our default seed nodes will be contained in the generated config file. When building with the testnet, no seed nodes will be compiled in.

The default plugins will be suitable for a seed node with a wallet pointed at it. (witness_plugin, account_by_key, condenser_api, etc.)

Starting without a data directory will result in a node that syncs.

**Comment by roadscape** [comment]
I wouldn't put 100GB+ of databases into a hidden directory. In my experience the default for apps with large stores is something like `/var`, `/usr/local/var`, or `~/Libraries/`. And for Windows, maybe `C:\ProgramData`. (Personally I like using current working directory because I tend to keep several steemd binaries around and it's convenient to have the default directory segmented nicely by default.)

Also, I noticed the default logger's level is set to `warn` on `develop` and `master`. IIRC, we changed this back to `info` already because without it the node gives no indication any work is being performed... e.g. initial sync produces no output for a long time, which is confusing, especially when building many different versions for testing. And for new devs it's not friendly.

**Comment by sneak** [comment]
It needs to be under $HOME in any case, and things like .config and .bitcoind are common in there already, which can be quite large.

Relative to the CWD is silly, you are first arguing for doing what others do, then go on to argue for what literally nobody else does. :)

Using a system level directory is inappropriate as the process cannot assume it is run as root or that those directories will exist.

**Comment by roadscape** [comment]
Well I did say personally, parenthetically ;)

Wherever you put it, I would avoid putting 100GB+ into hidden directories. Not a friendly pattern imo.

**Comment by mvandeberg** [comment]
Putting it in `$HOME/.steemd` follows what Bitcoin does. It should not be a curve ball for cryptocurrency sys admins.

**TODO:** Add default data dir path to README

**Comment by mvandeberg** [comment]
Steemd now creates the data dir in `$HOME/.steemd` with the following default config

```
# Console appender definition json: {"appender", "stream"}
log-console-appender = {"appender":"stderr","stream":"std_error"}

# File appender definition json:  {"appender", "file"}
log-file-appender = {"appender":"p2p","file":"logs/p2p/p2p.log"}

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"info","appender":"stderr"}
log-logger = {"name":"p2p","level":"warn","appender":"p2p"}

# Whether to print backtrace on SIGSEGV
backtrace = yes

# Plugin(s) to enable, may be specified multiple times
plugin = witness account_by_key account_by_key_api condenser_api 

# Defines a range of accounts to track as a json pair ["from","to"] [from,to] Can be specified multiple times.
# account-history-track-account-range = 

# Defines a range of accounts to track as a json pair ["from","to"] [from,to] Can be specified multiple times. Deprecated in favor of account-history-track-account-range.
# track-account-range = 

# Defines a list of operations which will be explicitly logged.
# account-history-whitelist-ops = 

# Defines a list of operations which will be explicitly logged. Deprecated in favor of account-history-whitelist-ops.
# history-whitelist-ops = 

# Defines a list of operations which will be explicitly ignored.
# account-history-blacklist-ops = 

# Defines a list of operations which will be explicitly ignored. Deprecated in favor of account-history-blacklist-ops.
# history-blacklist-ops = 

# Disables automatic account history trimming
history-disable-pruning = 0

# Allows to specify path where rocksdb store will be located. If path is relative, actual directory is made as `shared-file-dir` subdirectory.
account-history-rocksdb-path = "account-history-rocksdb_storage"

# Defines a range of accounts to track as a json pair ["from","to"] [from,to] Can be specified multiple times.
# account-history-rocksdb-track-account-range = 

# Defines a list of operations which will be explicitly logged.
# account-history-rocksdb-whitelist-ops = 

# Defines a list of operations which will be explicitly ignored.
# account-history-rocksdb-blacklist-ops = 

# How often to print out block_log_info (default 1 day)
block-log-info-print-interval-seconds = 86400

# Whether to defer printing until block is irreversible
block-log-info-print-irreversible = 1

# Where to print (filename or special sink ILOG, STDOUT, STDERR)
block-log-info-print-file = ILOG

# the location of the chain shared memory files (absolute path or relative to application data dir)
shared-file-dir = "blockchain"

# Size of the shared memory file. Default: 54G
shared-file-size = 54G

# Pairs of [BLOCK_NUM,BLOCK_ID] that should be enforced as checkpoints.
# checkpoint = 

# flush shared memory changes to disk every N blocks
# flush-state-interval = 

# Database edits to apply on startup (may specify multiple times)
# debug-node-edit-script = 

# Database edits to apply on startup (may specify multiple times). Deprecated in favor of debug-node-edit-script.
# edit-script = 

# Set the maximum size of cached feed for an account
follow-max-feed-size = 500

# Block time (in epoch seconds) when to start calculating feeds
follow-start-feeds = 0

# json-rpc log directory name.
# log-json-rpc = 

# Track market history by grouping orders into buckets of equal size measured in seconds specified as a JSON array of numbers
market-history-bucket-size = [15,60,300,3600,86400]

# How far back in time to track history for each bucket size, measured in the number of buckets (default: 5760)
market-history-buckets-per-size = 5760

# The local IP address and port to listen for incoming connections.
# p2p-endpoint = 

# Maxmimum number of incoming connections on P2P endpoint.
# p2p-max-connections = 

# The IP address and port of a remote peer to sync with. Deprecated in favor of p2p-seed-node.
# seed-node = 

# The IP address and port of a remote peer to sync with.
p2p-seed-node = seed-east.steemit.com:2001 seed-central.steemit.com:2001 seed-west.steemit.com:2001 steem-seed1.abit-more.com:2001 52.74.152.79:2001 seed.steemd.com:34191 anyx.co:2001 seed.xeldal.com:12150 seed.steemnodes.com:2001 seed.liondani.com:2016 gtg.steem.house:2001 seed.jesta.us:2001 steemd.pharesim.me:2001 5.9.18.213:2001 lafonasteem.com:2001 seed.rossco99.com:2001 steem-seed.altcap.io:40696 seed.roelandp.nl:2001 steem.global:2001 seed.esteem.ws:2001 94.23.33.61:2001 104.199.118.92:2001 192.99.4.226:2001 seed.bhuz.info:2001 seed.steemviz.com:2001 steem-seed.lukestokes.info:2001 seed.blackrift.net:2001 seed.followbtcnews.com:2001 node.mahdiyari.info:2001 seed.jerrybanfield.com:2001 seed.windforce.farm:2001 seed.curiesteem.com:2001 seed.riversteem.com:2001 steem-seed.furion.me:2001 148.251.237.104:2001 seed1.blockbrothers.io:2001 

# P2P network parameters. (Default: {"listen_endpoint":"0.0.0.0:0","accept_incoming_connections":true,"wait_if_endpoint_is_busy":true,"private_key":"0000000000000000000000000000000000000000000000000000000000000000","desired_number_of_connections":20,"maximum_number_of_connections":200,"peer_connection_retry_timeout":30,"peer_inactivity_timeout":5,"peer_advertising_disabled":false,"maximum_number_of_blocks_to_handle_at_one_time":200,"maximum_number_of_sync_blocks_to_prefetch":2000,"maximum_blocks_per_peer_during_syncing":200,"active_ignored_request_timeout_microseconds":6000000} )
# p2p-parameters = 

# Block time (in epoch seconds) when to start calculating promoted content. Should be 1 week prior to current time.
tags-start-promoted = 0

# Skip updating tags on startup. Can safely be skipped when starting a previously running node. Should not be skipped when reindexing.
tags-skip-startup-update = false

# Local http endpoint for webserver requests.
# webserver-http-endpoint = 

# Local websocket endpoint for webserver requests.
# webserver-ws-endpoint = 

# Local http and websocket endpoint for webserver requests. Deprecated in favor of webserver-http-endpoint and webserver-ws-endpoint
# rpc-endpoint = 

# Number of threads used to handle queries. Default: 32.
webserver-thread-pool-size = 32

# Enable block production, even if the chain is stale.
enable-stale-production = false

# Percent of witnesses (0-99) that must be participating in order to produce blocks
required-participation = 33

# name of witness controlled by this node (e.g. initwitness )
# witness = 

# WIF PRIVATE KEY to be used by one or more witnesses or miners
# private-key = 
```

**Comment by sneak** [comment]
Sweet!  Is it pulling in those seednodes from doc/seednodes.txt during compile or are they hardcoded in somewhere so that we need to be sure @Gandalf-the-Grey updates that source file at the same time he updates seednodes.txt?

**Comment by sneak** [comment]
Once we verify that the rocksdb account history replacement works well, that should probably be included in the default config, as it can safely be assumed that `$HOME` will be an SSD and have a few hundred GB free.

**Comment by sneak** [comment]
AFAIR the docker build scripts expect a doc/seednodes.txt, so it needs to be duplicated for the moment unless you want to make a python build helper as part of this work.

**Comment by mvandeberg** [comment]
The docker build script needs it so when the node is ran, it has a list of seeds. Now that it is compiled in, the docker build script has no need for doc/seednodes.txt

**Comment by sneak** [comment]
Are the default seeds used when no seeds are specified in the config file? The compiled in seeds should probably only be used when writing out a config file in the case of one not existing.

The docker image creates its own config file, so in that case the compiled in ones should not get accessed...

We can revisit the docker scripts too but for now that’s how it works.

**Comment by mvandeberg** [comment]
The way steemd writes the default is by writing the default values. We would have to write a new handler for the default config if we wanted the printed config to differ from the default values. As far as I was aware, that was not a requirement of this work, but I suppose it can be if the following behavior is not satisfactory.

- If no seeds are specified, the compiled in seeds are used. 

- If any other seeds are specified, **only** those seeds are used. 

- If a blank seed is specified (i.e `p2p-seed-node = ` ) then no seeds are used.

**Comment by Gandalf-the-Grey** [comment]
sounds great for me ^

btw, above is also a convenient way to quickly check defaults after new release (i.e. by generating config and reviewing it's values)
