### ISSUE TITLE
Launch testnet problem

### ISSUE THREAD

**Issue by devdack** [steemit/steem#2188]
I want to launch Steem private testnet on 19HF with inflation model and see how it works. All going good until HF17, which implement reward fund. Until hardfork i see pending payout value for any upvoted post, and every new block i see changes on rewards and total_reward_fund_steem. All like must be. 

But after HF17, i did'not see any changes for posts rewards. I see rshares for upvoted post, i see increases reward fund, but nothing about payout_value for upvoted posts... just zero everywhere. I have investigate the code, and it seems to me, that problem related with non-genesis transitions between HF. But.. this is testnet, and should works any case, i think too... 

I have reduce first cashout time to first block, and this is not reason of it, cause until HF17 all payments going well.. I have publish price_feed for all initminers. I have many, many different combinations of changes on config.hpp file, but this is not helps to start payments after HF17... 

Give me any directions, please.. Im already 5 days just rebuild, rebuild, rebuild, rebuild, and have really heavy stuck on it.....  ((( Which key parameters should be setted correctly, in order to begin payments after 17 HF? What I need to check?

**Comment by mvandeberg** [comment]
We are working on a Steemit supported testnet. When that is released, you can use that. Until then, we are not going to provide support on a custom testnet.
