### ISSUE TITLE
Can we add account-whitelisting to have the foundations for a "web-of-trust"?

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#219]
The account-whitelisting in BitShares was a great invention and I wonder why it's not part of steem already.
Together with a "web-of-trust" formed through this list, and the account recovery feature recently introduced, this could open up Steem to be number one internet identity provider on the globe. 

Just make it scale!

**Comment by theoreticalbts** [comment]
While it's an interesting idea, this proposal is still far too vague to be ready for discussion here; I'll close this.
