### ISSUE TITLE
Batch Write Requests

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#2194]
Currently each write to database acquires the locks, performs the write, and releases it.

When we are live, this is not the worst (can be improved upon), but it is horribly inefficient when syncing the blockchain.

We should move to a producer/consumer model where all writes are placed in a queue and consumed by a dedicated thread that can hold the write lock for a specified amount of time and batch writes so that we minimize the amount of locking that needs to be done.

To prevent starvation of writers the write lock should be willingly released every so often only when live. When syncing, the write process can (and should) be greedy with the lock so long as there are pending writes.

**Comment by sneak** [comment]
PS: I love this design approach

**Comment by r351574nc3** [comment]
Like event-driven distributed log? Like kafka/rabbitmq?
