### ISSUE TITLE
OPENSSL_CRYPTO_LIBRARY

### ISSUE THREAD

**Issue by HSTEP** [steemit/steem#2197]
I am getting this error while compiling steem on mac:

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
  libraries/fc/CMakeLists.txt:152 (find_package)

help?

**Comment by sneak** [comment]
You need to have OpenSSL libraries installed and set `OPENSSL_ROOT_DIR` to point to them.
