### ISSUE TITLE
Trending shows very old posts

### ISSUE THREAD

**Issue by riensen** [steemit/steem#220]
Since the last update we the /trending category will show obsolete posts which are several days old.
These posts seem to remain there until the second payout happens (4 weeks), which is discouraging new content to show up (the originell intent of the last update)
Example: https://steemit.com/steemit/@anyx/cheetah-bot-the-fight-against-spam-and-plagiarism-continues

**Comment by mvandeberg** [comment]
We are aware of this and working on splitting new trending from trending 30 days.

**Comment by jl777** [comment]
a related issue is that even top trending posts appears to expire after about 14 to 16 hrs, this means depending on the time something is posted, it could miss an entire area of the globe.

Shouldnt a top trending post last 24hrs?

**Comment by iamsmooth** [comment]
@jl777 I agree that the 12 hour limit was a bad change and should be reverted. Several other well-known community members have commented similarly. But I think that should be a separate github issue.  I was planning to open one when I have to time to write it up properly but you are welcome to do so first.

**Comment by theoreticalbts** [comment]
This seems to have been merged, so I'm closing it.
