### ISSUE TITLE
appbase witness plugin causes significant resync performance degradation

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#2205]
During [Appbase Bughunting](https://github.com/steemit/steem/issues/2101) I've noticed significant increase of sync times. Surprisingly they are gone when witness plugin (recommended for all consensus nodes because of bandwidth) is not enabled.
Here I'm listing block and absolute time (minutes) from the start of sync needed to get that far while doing `--resync` comparing stable vs develop with and without witness plugin:
```
block  stable  stable+w  develop  develop+w
  5M     28       30        29        42
 10M     73       77        75       121
 15M    170      182       171       337
 20M    379      415       377       851
```
even more visible on a chart:
![resync_times_chart](https://user-images.githubusercontent.com/6341057/37088849-ee81c538-21fe-11e8-8397-ae67d0e9a194.png)

**Comment by Gandalf-the-Grey** [comment]
Comparing replay time (minutes) on the same machine running appbase with and without witness plugin gives much much smaller difference:
```
block  develop  develop+w
  5M       5         6
 10M      17        18
 15M      44        50
 20M     108       126
```
![replay_times_chart](https://user-images.githubusercontent.com/6341057/37166744-3a7cfd8e-2300-11e8-8664-2b5ec0eb486d.png)

**Comment by dnotestein** [comment]
Without checking the code it's just a guess, but it seems quite possible that signatures aren't validated during replays since they would have been previously checked, but signatures would require validating during a sync. A non-witness node may only be checking the block signatures by the witnesses, while a node running the witness plugin would check the signatures of all the transactions in the block as well.

**Comment by Gandalf-the-Grey** [comment]
If so, that would explain `develop` vs `develop+w` but then I would expect same huge difference with `stable` vs `stable+w` (there was only less than 10% difference for resync time up to 20M block, while on develop it's more than 125% difference)

**Comment by dnotestein** [comment]
I took a quick look at the witness plugin, there's a couple of functions that could be the culprit. To narrow down the problem, I suggest nullifying those functions individually by returning out of them to see what's the culprit (i.e. add a return to kill the function, then run the benchmark with the modified code). I suggest you try a reindex first before a resync, just to be sure the modified code doesn't complete.

I would start by adding a return here: 

https://github.com/steemit/steem/blob/42e2d95ec09d1695ec1b392d47a2e44612815cf0/libraries/plugins/witness/witness_plugin.cpp#L221

It looks sort of like that code checks signatures and computes account bandwidth. If that fails to reindex, you might need to return out of the on_block as well, but hopefully they are independent.

**Comment by mvandeberg** [comment]
@Gandalf-the-Grey Nothing immediately jumps out at me in the appbase witness plugin. The scope of the plugin has not changed for appbase. I had observed the general slow down of appbase syncing and fixed it in #2194. I am curious how that change impacts this behavior.

My quick testing of #2194 was observing steemd in a profiler over the same range of blocks (syncing right around 3,000,000). My goal was to minimize time spent in synchronization overhead. The branch now takes the same, or less overhead, for synchronization than `stable`. The profiler I used profiled for the same amount of time, so percent overhead directly converts to time. However, if the witness plugin is doing something fishy, this could throw off those results. I did not record blocks per second in my initial testing. I did, however, observe blocks per second for the branch in our dev environment and it was out performing `stable`.

**Comment by Gandalf-the-Grey** [comment]
So the `--resync` times on my reference machine was like that (time in minutes):
```
block  stable  stable+w  develop  develop+w
  5M     28       30        29        42
 10M     73       77        75       121
 15M    170      182       171       337
 20M    379      415       377       851
```
we were talking about `41bc18c` when referring to `develop`
`develop+w` means with witness plugin
During ongoing hunt I was benchmarking current `master` which is `76d32c1`
```
block  41bc18c+w  76d32c1+w
 5M        42        168
10M       121        424
```
That's a significant ~4x slowdown

**Comment by mkochanowicz** [comment]
@mvandeberg Michael, could you take a look at this, please? How to check what commit of fc vendored?

I've made measurements for a dozen of commits with resync for 1M blocks. Interesting part of results so far:
- `stable` branch as reference: **2:50**
- `1d7c4dd9b7466312ce41f08b65c14b3b02918ff8` (Merge pull request #2142 from steemit/2141-clean-shutdown): **3:47**
- `2945196ca5ead5049e78679d69affea98d97e27b` (Merge pull request #2145 from steemit/1301-vendor-fc): **6:40**

Looks like `1301-vendor-fc` change fc commit steemd used before vendoring. This is the last and largest slowdown I observe, but still `2141-clean-shutdown` has worse performance then `stable`.

**Comment by mvandeberg** [comment]
I believe it would be `fc/master` e3e2912760884c08513626fad5b50339b16da8ef

**Comment by mkochanowicz** [comment]
I've found the cause. Now, the decision: looking for earlier slowdowns or close issue?

**Comment by mvandeberg** [comment]
Let's get some current timings on `develop` before closing the issue.

**Comment by Gandalf-the-Grey** [comment]
Here are some results from current `develop`: **`32e7e64`** in comparison to previous results:
```
block  stable   stable+w  41bc18c  41bc18c+w 76d32c1+w f614ef0+w  32e7e64  32e7e64+w
 5M      28        30        29        42       168        62        37        42
10M      73        77        75       121       424       177        89       121
```
There were two major slowdowns found:
- first, the original one on the top of this issue, **7 Mar**
where sync times with witness plugin enabled increased from **77 minutes** for 10M blocks on stable to **121 minutes** on develop (appbase)
- second, **9 Apr**, was even worse increasing that times on master and develop to 168 and 62 minutes respectively.

@mkochanowicz found a cause for the **second slowdown** and it's now fixed (thanks!)
that means that we are back to the state of the original issue from **7 Mar** (slowdown caused by witness plugin) so **it can't be closed**

also please note that resync without witness plugin is now slower that it used to be back then
so ironically, now, witness plugin is slowing us down less, because resync is slower even without it.

To simplify, the current state:
```
block  stable   stable+w  develop  develop+w
 5M      28        30        37        42
10M      73        77        89       121
```
Remaining questions:
- why adding witness plugin on current develop makes resync 10M blocks **32 minutes** slower, while it was only **4 minutes** slower on stable.
- why resync to 10M blocks **without** witness plugin, compared to stable, is **16 minutes** slower on current develop, while it was only **2 minutes** slower on **7 Mar**

**Comment by mvandeberg** [comment]
How did @mkochanowicz only find the cause of the second slowdown that was observed on April 9th when the fc vendor was merged on Feb 21st? I would argue that the fix to the fc vendor fixed the first problem because the witness plugin does extra signature checks that were using the unoptimized secp256k. Now that it is fixed, there is still a slowdown using the witness plugin, but it is not as much. And a larger percentage of that slowdown is coming from steemd without any plugins.

**Comment by mvandeberg** [comment]
Merged to develop. @Gandalf-the-Grey Can you retest?

**Comment by Gandalf-the-Grey** [comment]
```
block  stable   stable+w  develop  develop+w
 5M      28        30        28        29
10M      73        77        72        75
```
Awesome! Thank you.
