### ISSUE TITLE
Design flaw allows DDoS attacks against users and is inciting general unrest.

### ISSUE THREAD

**Issue by willbanks** [steemit/steem#221]
steem has a design flaw you need to correct soon before it gets out of hand and you end up with a mass revolt on your hands.

At present there is no penalty whatsoever for "flagging" someone for the person who does the flagging.
This is causing a war to break out between people who have some seriously hurt feelings over it.

The problem looks like this..
You have people advocating to noobies that they use flagging as their own personal disagree button as well as acting like they are the censorship police and just downvoting everything a single person is saying if they view what that person as "spammy" in general.
https://steemit.com/steemit/@neoxian/flagging-i-m-back-on-the-job-and-a-new-criteria-for-flagging

The inevitable result of which is this...
https://steemit.com/steemit/@desmonid/s-o-s-i-m-being-targeted-by-a-malicious-downvote-bot

Basically user @desmonid hit a hornet's nest because he followed bad advice from someone and got stung.  

Meanwhile @hasherfromhell at least stepped forward and owned the fact that he was the attacker.

In the meantime I'm babysitting this because I'm trying to give the bot builders something better to do with their time than build upvote/downvote and spam bots.
https://steemit.com/introduceyourself/@williambanks/announce-steembots-com-your-source-for-everything-bot-related-now-hiring

Here is how you fix this...
First off, stop debiting from a person's earnings based on the weight of the downvoter's purse. This is the actual source of resentment here.  Fix your algorithm so downvotes count proportional to number received, with 100 being enough to completely nix a post.  This is not something to be determined by flagger's wealth.  Otherwise when there is spam we have to go find a whale to mod them down and that's just not right on so many levels.

Charge a flat $0.01 for every single post and flag/upvote.  Period, whales and minnows alike.
The money is a negligible amount, that most of us won't ever notice if we're posting like humans.
The money from flagging should automatically be added to a total payout kitty for the entire conversation weighted by number of replies and upvotes then split accordingly.

Also add a n "i disagree" button, maybe make it look like a down arrow.  It doesn't have to have a financial effect on the target, but people are faced with upvoting which is agreement, or flagging which is being as an "i disagree" button despite it just being a passive aggressive way of bullying.  A spanking or disagree button would stop a lot of hard feelings.

Anyways doing these things will stop botspam in it's tracks, making it uneconomical to run these kinds of wars, or at least if they do run them, the attacks will run out of steem as soon as the attacker looks and sees his account is now empty.

It makes having a thousand minnow accounts doing upvote spam a money losing proposition.

It will also allow those of us genuinely trying to have a thoughtful conversation to not simply loose all of our accumulated wealth in a thread simply because someone has a beef with the poster.
Finally, it will incentivize those of us who are busy trying to build quality bots to look at other important tasks like stopping plagarism, detecting fraud, training classifiers etc.  

My last word of advice on this is that new accounts need to having a cooling off period before being allowed to either up or downvote.  Sure let them post, but make them wait awhile before they can up or down vote and if they are flagged for spam at all, then simply mute them at the blockchain level for a minimum 24hrs.  This prevents them from doing anything at all for 24hrs, upvote, flag, post or withdrawal.

**Comment by theoreticalbts** [comment]
> First off, stop debiting from a person's earnings based on the weight of the downvoter's purse

We can't do it this way, because we have to have a tool to keep people from earning money for anti-social posts.

> Fix your algorithm so downvotes count proportional to number received, with 100 being enough to completely nix a post

We can't do it this way, because it's trivial (but slightly expensive) to create 100 accounts.  One fundamental principle of Steem is that rewards are based on SP, not number of accounts.

> Charge a flat $0.01 for every single post and flag/upvote.

Paying a fee, no matter how small, causes a certain minimum cognitive load on the user.

> Also add an "i disagree" button, maybe make it look like a down arrow.

This is a UI-level enhancement and does not belong in this repository, which is the backend.

If you want to continue this discussion, please use steemit.com, not the bug tracker.
