### ISSUE TITLE
Move Python code to steem_build_helpers

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2210]
So there is Python code scattered throughout our build tree, mainly in two places:

- A Python package called `steem_manifest` in `libraries/manifest`
- A bunch of standalone scripts in `programs/build_helpers`

Let's move the scripts to a Python package called `steem_build_helpers` under `build_helpers` .  CI and Dockerfile will need to be updated with the new locations.

**Comment by mvandeberg** [comment]
This is not part of the sprint. I agree with these changes, but I cannot think of an argument for this being high enough priority to work on outside of a sprint. It could have waited a few days to be scheduled in the sprint.

**Comment by youkaicountry** [comment]
@theoretical Is this related to the changes you are making to the build system for AMM? If so it is okay to be in the sprint. If not it will have to wait until the next sprint.
