### ISSUE TITLE
 I need help changing my username can somebody help my display name 

### ISSUE THREAD

**Issue by zenashopson** [steemit/steem#2216]
Hi I need help changing my display name/user name on this platform nobody seems to be able to help me https://steemit.com/@zenashopson if you go on my profile  you will see  my display name as N/A  I would like to change it to  Zenas Hopson  but every time I get a error message saying this (Server Returned Error)

**Comment by TimCliff** [comment]
Can you open an issue in the condenser repository: https://github.com/steemit/condenser/issues

This is the repository for the blockchain. Condenser is the code that runs steemit.com.

**Comment by zenashopson** [comment]
Ok done
