### ISSUE TITLE
Promoted Content

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#222]
Allow users to promote their content as another ranking metric.

**Comment by theoreticalbts** [comment]
Implemented and compiling, but not tested.  See [here](https://github.com/steemit/steem/blob/222-promoted/doc/backplane.md) for design notes.

**Comment by jcalfee** [comment]
It was discovered that post promoted after the first payout would disappear from the promoted section.  This might happen upon a subsequent vote or additional boost payment.  So, we are hiding the Promote post unless the post is in the first_payout...  We still have issues: the user could submit payment just before or even after the payout (stale screen).  What is the plan? thanks..

**Comment by theoreticalbts** [comment]
This has been in for a very long time, closing.
