### ISSUE TITLE
node.cpp:1345 may a bug

### ISSUE THREAD

**Issue by rabbitHX** [steemit/steem#2229]
<img width="1027" alt="node" src="https://user-images.githubusercontent.com/37372210/37404819-eeab9d5c-27cd-11e8-8f64-250f41a8a95e.png">
    there is a "break" on the line 1345 of node.cpp, this break cause a escape from "for" so that the bad connection is not "push_back" into  peers_to_disconnect_forcibly. 
    It is a problem? hope a reply.

**Comment by abitmore** [comment]
Good catch.

**Comment by abitmore** [comment]
@rabbitHX why closed?

**Comment by rabbitHX** [comment]
@abitmore i think "closed" means this problem is done, im wrong? need reopen?

**Comment by TimCliff** [comment]
If a code change has not been made to fix it yet, it should remain open.

**Comment by rabbitHX** [comment]
@TimCliff ok, i know

**Comment by dnotestein** [comment]
I agree this fix should be included.
