### ISSUE TITLE
Create smt_base_operation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2235]
To avoid redundant code, create a base operation `smt_base_operation` from which which smt operations will descend. 

It should contain members representing control_account and token, and should have a validate method which validates these members.

**Comment by theoreticalbts** [comment]
I am not sure if FC reflection or some of our other template automagic (for example `static_variant.visit()` dispatch) can handle this.

**Comment by mvandeberg** [comment]
`FC_REFLECT_DERIVED` handles this.
