### ISSUE TITLE
Text verification doesn't work

### ISSUE THREAD

**Issue by IndianLegend** [steemit/steem#2242]
Hello! I'm interested in using your services as a content publisher from India, but I'm afraid I'm not able to get past the text verification stage. I tried with two different numbers (beginning with +91) and two different browsers, but with no result. 

Please look into the issue.

**Comment by TimCliff** [comment]
This is not an issue with the blockchain software. Please as for help in the help channel of steem chat.

**Comment by IndianLegend** [comment]
Hello! I went onto #help on SteemChat and a generous moderator swiftly helped resolve the issue. Nevertheless, thank you :)
