### ISSUE TITLE
Bug on trending tags

### ISSUE THREAD

**Issue by sydneyitguy** [steemit/steem#2243]
Looking at the "all tags" menu on https://steemit.com/tags

There's "#laefboy" tag at the end of the list (sort by posts),
and it says it has only 1 post, but 3,552 comments with average payout of $7.262

![image](https://user-images.githubusercontent.com/1332279/37706252-6745421e-2d31-11e8-886c-51d1b857c34b.png)

However, the actual list is

![image](https://user-images.githubusercontent.com/1332279/37706303-a53e939a-2d31-11e8-8853-a13964ae6d4c.png)

It has
- only 1 post: which is correct
- 3 comments (not 3,552)
- $0.01 in total payout (not $7.262)

It looks like a bug that people can abuse to list their tags on the trending list (what's the algorithm to sort trending tags btw?)

**Comment by mvandeberg** [comment]
Tags are now handled by hivemind. No changes will be made to their implementation in steemd.

@roadscape to close if this issue needs to be copied to the hivemind repo, or if it is a non-issue.
