### ISSUE TITLE
Cleanup rocksdb configuration

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#2247]
As @sneak noted in #2129 

> I think perhaps that the new rocksdb-based AH plugin should be given a new name, so that people can enable the new-style rocksdb-based plugin or the old-style AH plugin with a small list of whitelisted ops or account names and continue using steemd like they did before.

I suggest renaming `rocksdb_plugin` to `account_history_rocksdb`. The existing account history plugin and rocksdb account history should be made mutually exclusive and should both accept the same config options so that upgrading to rocksdb is as simple as changing the plugin list and reindexing.

**Comment by sneak** [comment]
let’s stick to the options prefixed by the full plugin name so they can coexist if someone wanted that for some reason.
