### ISSUE TITLE
Precision semantics for new assets

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2250]
When the SMT operations were originally specified, the `precision` was not included in `asset_symbol_type` for SMT's, so it was specified in a separate field.

That design decision has since been revisited.

Since `precision` is in the `symbol`, the fields `smt_create_operation::precision` and `smt_setup_operation::decimal_places` should be removed.  Here are the options for how we can design it:

- (1) Precision set by `smt_create_operation`, all subsequent operations must match
- (2) Precision set by `smt_setup_operation`, setup phase operations must match `smt_create_operation`
- (3) Precision set by `smt_setup_operation`, setup phase operations can be anything
- (4) Precision set by `smt_setup_operation`, setup phase operations and `smt_create_operation` must have precision of zero.

We can get rid of the two middle options:  In Option (2) and (3), in the "normal case" SMT creation tools will likely specify the same precision in `smt_create_operation`, the setup phase operations, and `smt_setup_operation`.  UI designers may then *rely* on it being the same in these three operations, and incorrectly present cases where it is different to the user.  We can prevent this possibility by removing Options (2) and (3) from consideration.

Option (4) offers slightly more flexibility:  SMT creators who want to relaunch a failed SMT with a different precision to create another SMT.  The resulting UI design criteria are simple:

- Account history for operations which occur before `smt_setup_operation` lists amounts in satoshis.
- Display of inflation for SMT's in the setup phase should either use satoshis, or have an editable `precision` form field
- Display of inflation / parameters for SMT's after the setup phase should use RPC queries which return the actual precision, not account history.

So let's implement Option (4).

**Comment by youkaicountry** [comment]
Closing as outdated.
