### ISSUE TITLE
PR #2233 SMT transfer_to_vesting problems

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2253]
These are some minor issues with PR #2233 for SMT `transfer_to_vesting`.

First, a word about `validate()` methods:

- `account_regular_balance_object::validate()` and `account_rewards_balance_object::validate()` return a `bool` value.  Elsewhere, `validate()` methods indicate failure by throwing an exception.  It would be very easy to write code that calls these `validate()` methods that looks correct, but is actually a no-op since it doesn't check return value.
- `xxx_object` usually doesn't have `validate()`, only operations have `validate()`
- If these `validate()` methods are unused, let's delete them.
- If these `validate()` methods can be easily rewritten to `FC_ASSERT()`, let's do that.
- If it is hard to rewrite these methods, let's rename them something other than `validate()` (maybe `check_xxx()` or `is_xxx()`)

The line `FC_ASSERT( smt.allow_voting == to_reward_balance )` is problematic.  I think maybe it should be `if( to_reward_balance ) { FC_ASSERT( smt.allow_voting ); }` which is not logically equivalent.

The `delta` value is passed into `smt_balance_operator` and also passed as a parameter.  This seems unnecessary, let's get rid of the parameter and read the `smt_balance_operator` field when needed.

Why are we adding the VESTS case to `modify_balance()`?  Shouldn't vesting adjustment always go through vesting methods to avoid problems?

Look at the `is_vesting` initializer in `smt_reward_balance_operator`.  This may be incorrect.

**Comment by youkaicountry** [comment]
Referenced in #2746 
Closing as outdated.
