### ISSUE TITLE
_most_recent_blocks_accepted  double push

### ISSUE THREAD

**Issue by rabbitHX** [steemit/steem#2264]
hi:
  in node.cpp:process_block_during_normal_operation(),after _delegate->handle_block(), push the first time:
 _most_recent_blocks_accepted.push_back(block_message_to_process.block_id); and about 50 lines later there is a broadcast() op. in the broadcast(), if (msg_type == graphene::net::block_message_type) now push the second time:_most_recent_blocks_accepted.push_back( block_message_to_broadcast.block_id );
  the message is same, but pushed twice,is it purposely?

**Comment by mvandeberg** [comment]
The difference is where the block is originating from. If the node in question is the witness node producing the block, they would not have received the block from the p2p network. It is recorded in `broadcast` so the node does not request the block it just produced.
