### ISSUE TITLE
My account has been stolen - how to get it deleted so i can reuse the mobile number?

### ISSUE THREAD

**Issue by sandralouis** [steemit/steem#2266]
Hi all,

Require assistance urgently...

My account has been hijacked and now, it is being used to hijacked and downvote so many users. How do I get the admin to delete that account? At the same time, I would like to reuse the mobile number with the new account.

Thanks in advance to all who can assist,
Sandra

**Comment by TimCliff** [comment]
It is not possible to delete an account, but if you still have the previous working password you can request a “stolen account recovery” via the main menu of steemit.com. You will need to use the email address that was used to register the account.

**Comment by sandralouis** [comment]
Thanks @TimCliff 

I have initiated the process and the problem now is the hijacker is using my @sandralouis account to downvote and 'disturb' others.

Will wait till the process is over then.
Thanks,
Sandra
