### ISSUE TITLE
post deletion ? ? ? 

### ISSUE THREAD

**Issue by ap444** [steemit/steem#2267]
when will post deletion be an added feature? steemit will never succeed without this feature. i know its permanent on the blockchain but at least include the feature where we can delete it from the site

**Comment by AmoghSubhedar** [comment]
You can delete a post or a comment within a few seconds of its creation (don't know the exact value)
A common practice is to edit the post and keep it blank or just some garbage values, effectively 'deleting' that post from the site.

**Comment by mvandeberg** [comment]
The reason for the restriction is because deleting a post can have side effects on other's posts/votes. The fairest way to deal with deletion is only allow it when there are no comments or votes on it.
