### ISSUE TITLE
TypeError when using stream_from

### ISSUE THREAD

**Issue by AmoghSubhedar** [steemit/steem#2269]
File "curation_bot.py", line 63, in run
    for transfer in stream:
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/blockchain.py", line 237, in stream
    for ops in self.stream_from(*args, **kwargs):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem/blockchain.py", line 104, in stream_from
    time.sleep(block_interval)
TypeError: an integer is required (got type NoneType)

Getting this error when I try to stream all the transfers made on the blockchain.

This is how I'm streaming it:

b = Blockchain(s)
stream = b.stream(filter_by=['transfer'])
try:
    for transfer in stream:

**Comment by mvandeberg** [comment]
This is probably a Steem Python problem. Similar issues have already been reported and are being fixed.

**Comment by DurkoMatko** [comment]
I have exactly same problem in both Python 3.6 and 2.7
