### ISSUE TITLE
Filters please

### ISSUE THREAD

**Issue by nostradam** [steemit/steem#227]
Hello,

Please we need custom filters on steemit. We (users) don't have all day to browse through all this (mostly useless) content.
I would like to see posts only from users with at least 100 SP for example.
Also a filter that could be useful, only posts with at least x USD and x votes.

I know that i could use trending/hot, but i would like to see new posts from power users before they reach 5K USD. 

Thank you very much.

**Comment by theoreticalbts** [comment]
This is a UI feature suggestion. It doesn't belong here.
