### ISSUE TITLE
After verifying phone, I didn't get the final confirmation email

### ISSUE THREAD

**Issue by agro1986** [steemit/steem#2271]
Hi, I am an Ethereum smart contract developer and want to join Steemit.

I could get up to SMS confirmation, and after that I got a message saying that I will get an email. It has been more than a week but I still haven't got my email. Therefore I couldn't complete the registration process.

Please guide me on what to do next. Thank you!

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.
