### ISSUE TITLE
get_account_references --- Needs to be refactored for steem

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#228]
calling
{"jsonrpc": "2.0", "id":1, "method":"get_account_references", "params": ["2.2.27007"]}

returns error 

{"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nfalse: database_api::get_account_references --- Needs to be refactored for steem.\n    {}\n    th_a  database_api.cpp:368 get_account_references","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database_api.cpp","line":368,"method":"get_account_references","hostname":"","thread_name":"th_a","timestamp":"2016-08-01T14:17:10"},"format":"false: database_api::get_account_references --- Needs to be refactored for steem.","data":{}}]}}}

is this method not finished? why do we not have a proper api doc?

**Comment by theoreticalbts** [comment]
It's supposed to return the accounts which have your account as a multisig authority member.  It needs a supporting index.

The main reason we don't have a proper API doc is that the API is rapidly evolving and somewhat unstable right now.

**Comment by Kostronor** [comment]
Are there any news on this? I need to see all accounts that allow me posting.

**Comment by mvandeberg** [comment]
It should be possible to implement this in the `account_by_key` plugin. We are not working towards it right now, but it is in the backlog of issues we want to get to.

**Comment by mvandeberg** [comment]
Closing. Besides reporting this error, this feature has not been requested.
