### ISSUE TITLE
Oops!  error_api_token_invalid

### ISSUE THREAD

**Issue by armaccloud** [steemit/steem#2281]
Hi!
I've tried to sign up for Steemit, however after providing my details and opening the verification link I didn't get an SMS message. I've tried several times, but now the verification link takes me here

![oops](https://user-images.githubusercontent.com/9272078/37989782-a9ba2470-3204-11e8-8d35-4bec6a7aa0e2.jpeg)

Clicking continue and trying the verification doesn't work

![invalid token](https://user-images.githubusercontent.com/9272078/37989702-81c1f902-3204-11e8-9e68-47bff94f4a20.jpeg)

I cannot log in
![username does not exist](https://user-images.githubusercontent.com/9272078/37989811-b8d3bbd8-3204-11e8-9380-3b3c457e1046.jpeg)

Or sign up again
![username reserved](https://user-images.githubusercontent.com/9272078/37989817-be89511e-3204-11e8-850c-1b36a1d8cea3.jpeg)

Can you help me out? Thanks

**Comment by TimCliff** [comment]
Please ask for help in the help channel of steem chat.

**Comment by mvandeberg** [comment]
Thank you for the bug report about our sign up process. However, this is off topic in the repository, so I am closing the issue.
