### ISSUE TITLE
verify_authority errors in condenser_api; unexpected result in database_api

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2284]
Test call pre-appbase:

`{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "verify_authority", [{"ref_block_num": 13984, "ref_block_prefix": 551221541, "expiration": "2018-03-27T20:32:10", "operations": [["claim_reward_balance", {"account": "test", "reward_steem": "0.000 STEEM", "reward_sbd": "0.000 SBD", "reward_vests": "0.000000 VESTS"}]], "extensions": [], "signatures": ["1f2ee28e71e107a5c8a78bd5a53439ec26001da44ce81370b53f6f29a305012d6246162c796000e596701bbe02ec52e47ffdfe05e815a076d983ac98ef26b9e277"]}]]}`

Correctly returns `Missing Posting Authority test` error

---

Same call, using appbase/condenser_api:

`{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["condenser_api", "verify_authority", [{"ref_block_num": 13984, "ref_block_prefix": 551221541, "expiration": "2018-03-27T20:32:10", "operations": [["claim_reward_balance", {"account": "test", "reward_steem": "0.000 STEEM", "reward_sbd": "0.000 SBD", "reward_vests": "0.000000 VESTS"}]], "extensions": [], "signatures": ["1f2ee28e71e107a5c8a78bd5a53439ec26001da44ce81370b53f6f29a305012d6246162c796000e596701bbe02ec52e47ffdfe05e815a076d983ac98ef26b9e277"]}]]}`

Returns `"format":"Invalid cast from ${type} to Array","data":{"type":"string_type"}}`

---

Same call, using appbase/database_api:

`{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "verify_authority", [{"ref_block_num": 13984, "ref_block_prefix": 551221541, "expiration": "2018-03-27T20:32:10", "operations": [["claim_reward_balance", {"account": "test", "reward_steem": "0.000 STEEM", "reward_sbd": "0.000 SBD", "reward_vests": "0.000000 VESTS"}]], "extensions": [], "signatures": ["1f2ee28e71e107a5c8a78bd5a53439ec26001da44ce81370b53f6f29a305012d6246162c796000e596701bbe02ec52e47ffdfe05e815a076d983ac98ef26b9e277"]}]]}`

Returns `"format":"Invalid cast from type '${type}' to Object","data":{"type":"array_type"}}]}}`

---

Same call, using appbase/database_api, changing `[api, method, [param]]` to `[api, method, param]`:

`{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "verify_authority", {"ref_block_num": 13984, "ref_block_prefix": 551221541, "expiration": "2018-03-27T20:32:10", "operations": [["claim_reward_balance", {"account": "test", "reward_steem": "0.000 STEEM", "reward_sbd": "0.000 SBD", "reward_vests": "0.000000 VESTS"}]], "extensions": [], "signatures": ["1f2ee28e71e107a5c8a78bd5a53439ec26001da44ce81370b53f6f29a305012d6246162c796000e596701bbe02ec52e47ffdfe05e815a076d983ac98ef26b9e277"]}]}`

Returns `{"valid":true}`

**Comment by mvandeberg** [comment]
What do you expect the results to be for each of these calls?

**Comment by mvandeberg** [comment]
On dev environment: 

Case 2 works.

Case 3 does not work and should not work because serialization has changed.

Case 4 is behaving properly. The argument definition is:

``` c++
struct verify_authority_args
{
   signed_transaction trx;
};
```

When the arguments are deserialized, they do not map into the arg type and the transaction is default instantiated, which is trivially signed.

**Comment by roadscape** [comment]
Great, case 2 was the biggest concern.

**Comment by mvandeberg** [comment]
Although we may want to consider modifying the reflection to fail when there are unnecessary fields to fail with error message instead of silently fail and return success (case 4). @theoreticalbts

**Comment by mvandeberg** [comment]
This is working on `develop`. Closing
