### ISSUE TITLE
cant get call get_key_references to work

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#229]
calling 
{"jsonrpc": "2.0", "id":1, "method":"get_key_references", "params": [["redactedprivatekey"]]}

always returns
{"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nbase58str.substr( 0, prefix_len ) == prefix: \n    {\"base58str\":\"redactedprivatekey\"}\n    th_a  types.cpp:27 public_key_type","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"types.cpp","line":27,"method":"public_key_type","hostname":"","thread_name":"th_a","timestamp":"2016-08-01T14:21:00"},"format":"base58str.substr( 0, prefix_len ) == prefix: ","data":{"base58str":"redactedprivatekey"}}]}}}

which also should not return redactedprivatekey in the error as a matter of security

**Comment by theoreticalbts** [comment]
This API is intended to use public keys, not private keys.  The only API's which take private keys are the ones in the wallet (libraries/wallet).  get_key_references is a steemd method in database_api.  Feel free to re-open this ticket or file a new one if it doesn't work with your public key.
