### ISSUE TITLE
API "method":"jsonrpc.get_signature" no work

### ISSUE THREAD

**Issue by Gyga8K** [steemit/steem#2297]
I send this to api.steemit.com 

`{"jsonrpc":"2.0", "method":"jsonrpc.get_signature", "params":{"method":"condenser_api.get_discussions_by_hot"}, "id":1}`

This is the result:

```
{
    "jsonrpc": "2.0",
    "result": {
        "args": [],
        "ret": []
    },
    "id": 1
}
```

I am using Postman.

**Comment by muksihs** [comment]
I don't think this API call is supported any more, the toolkit you are using needs updating.

**Comment by mvandeberg** [comment]
This call was created for Appbase. It does not work on `condenser_api` because args are lists and are not self describing in json. If you were to call it on another api, you would get an arg struct and a return struct.

**Comment by Gyga8K** [comment]
Where can I get the documentation of the list of available endpoints with the parameters that have to be sent?

**Comment by mvandeberg** [comment]
Our developer portal (https://developers.steem.io/) will soon be up-to-date for the appbase release.
