### ISSUE TITLE
SBD Stability

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#230]

**Comment by abitmore** [comment]
Interest will still be paid in SBD when new SBD is not being printed as author reward. See [the code](
https://github.com/steemit/steem/blob/15896a4448ea02d8885e21f8d8254da35b9389aa/libraries/chain/database.cpp#L3324). Intended?

**Comment by abitmore** [comment]
Still possible multiplication overflow at [this line](https://github.com/steemit/steem/blob/15896a4448ea02d8885e21f8d8254da35b9389aa/libraries/chain/database.cpp#L2132) in `database::stabalize_sbd()`.

And probably need a virtual op to record the forced conversion.

**Comment by mvandeberg** [comment]
There is an issue in the current implementation caused by rounding down when converting 1% SBD into STEEM when SBD makes up 20% of the market cap. A user can split their SBD into 99 satoshi portions, which we be penalized each block at a rate of 0 satoshis, effectively avoiding the conversion altogether. SBD stability needs to be updated to round up on the 1% conversion to prevent an account from avoiding the automatic conversion.

**Comment by mvandeberg** [comment]
Removing NEEDS TESTING label as these changes have already been implemented, tested, and merged.
