### ISSUE TITLE
local TESTNET init,HF19,unknown key

### ISSUE THREAD

**Issue by tang1655** [steemit/steem#2300]
Hi,recently, i am trying to build Testnet on local-linux.
First,i meet hf5 problem,then I used the call `set_hardfork(STEEMIT_NUM_HARDFORKS, true);`to pass it.
and now i meet a new problem on hf19.
the err  mesage was:

`./steemd -d testnet --enable-stale-production `

> STARTINGTEST NETWORK
------------------------------------------------------
initminer public key: TST6LLegbAgLAy28EHrffBVuANFWcFgmqRMW13wBmTExqFE9SCkg4
initminer private key: 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n
chain id: 18dcf0a285365fc58b71f18b3d3fec954aa0c141c44e4e5cb4cf777b9eab274e
blockchain version: 0.19.2
------------------------------------------------------

> 1534100ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 6 at block 648
1534100ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 7 at block 648
1534100ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 8 at block 648
1534100ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 9 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 10 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 11 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 12 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 13 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 14 at block 648
1534101ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 15 at block 648
1534102ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 16 at block 648
1534102ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 17 at block 648
1534102ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 18 at block 648
1534102ms th_a       database.cpp:3623             apply_hardfork       ] HARDFORK 19 at block 648
1535000ms th_a       witness_plugin.cpp:584        block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
1538856ms asio       main.cpp:187                  operator()           ] Caught SIGINT attempting to exit cleanly

`./steemd`
am i worng here? is just use cmd:./steemd  diff to the  cmd:-d testnet 

> STARTING TEST NETWORK

------------------------------------------------------
initminer public key: TST6LLegbAgLAy28EHrffBVuANFWcFgmqRMW13wBmTExqFE9SCkg4
initminer private key: 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n
chain id: 18dcf0a285365fc58b71f18b3d3fec954aa0c141c44e4e5cb4cf777b9eab274e
blockchain version: 0.19.2
--------------------------------

> 1666014ms th_a       database.cpp:144              open                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE: unknown key
unknown key: 
    {"what":"unknown key"}
    th_a  database.cpp:451 get_hardfork_property_object
    {}
    th_a  database.cpp:2443 init_genesis
1666014ms th_a       database.cpp:144              open                 ] data_dir: /home/XXX/steem/build/programs/steemd/witness_node_data_dir/blockchain shared_mem_dir: /home/XXX/steem/build/programs/steemd/witness_node_data_dir/blockchain shared_file_size: 57982058496 
1666014ms th_a       application.cpp:397           startup              ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE: unknown key
unknown key: 
    {"what":"unknown key"}
    th_a  database.cpp:451 get_hardfork_property_object
    {}
    th_a  database.cpp:2443 init_genesis
rethrow
    {"data_dir":"/home/XXX/steem/build/programs/steemd/witness_node_data_dir/blockchain","shared_mem_dir":"/home/XXX/steem/build/programs/steemd/witness_node_data_dir/blockchain","shared_file_size":"57982058496"}
    th_a  database.cpp:144 open

I have find lots of PR,but still have no idea.
Could anyone help me,tks

**Comment by tang1655** [comment]
my mistake

**Comment by danirabbani90** [comment]
Hello @tang1655  Did you figure it out  ???
