### ISSUE TITLE
How to sync steem full node 

### ISSUE THREAD

**Issue by mabodx** [steemit/steem#2315]
when I sync the steem full node, it breaks, but every time I sync with following command, it will resync from the beginning, is there a way to sync from the the point that I stops? 
```
docker run \
    --env USE_WAY_TOO_MUCH_RAM=1 \
    -d -p 2001:2001 -p 8090:8090 --name steemd-full \
    steemit/steem

docker logs -f steemd-full
```
![image](https://user-images.githubusercontent.com/4045116/38404169-f4e0532e-391c-11e8-8427-6cbc8091ae3a.png)

**Comment by mabodx** [comment]
@mvandeberg  I mean I cancel it, but I don't know how to sync from the point that I sync last time

**Comment by mvandeberg** [comment]
First, you don't need to cancel it.

Second, restarting the service in the container should resume where it left off.

**Comment by mabodx** [comment]
@mvandeberg how to restart the it but i sync the node at the begining, how to sync the node from last time ? sorry I am newbie cannot find the tutorial easy enough to sync the p2p node or full node.
