### ISSUE TITLE
detect './witness_node_data_dir' for backwards-compat

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2340]
With https://github.com/steemit/steem/issues/2176, the default data dir location changes; for a smoother experience for users who are upgrading from prior versions (and using defaults), steemd should first check for the old-style `./witness_node_data_dir`. Otherwise it may be confusing to have a new build resync even though there's an intact data dir nearby.

**Comment by mvandeberg** [comment]
It should use this data dir and print a warning telling the user they should move their data dir to `~/.steemd`

**Comment by sneak** [comment]
The correct answer here is that steemd should let you specify a `--datadir`  command line flag, and if you want to use `./witness_node_data_dir` then start it with `steemd --datadir ./witness_node_data_dir`.

We don't need to bend over backwards for BC, just as long as people can configure it to work the old way.  It doesn't need to detect anything.  This should definitely be mentioned in the blog post/release notes.

**Comment by sneak** [comment]
If such a dir is detected and it doesn’t match `--datadir`, print a clear message instructing them to move it to the normal location (or specify datadir in args) and exit. Then we don’t have to support the old behavior forever.

**Comment by mvandeberg** [comment]
@youkaicountry This will impact node operators as soon as we make an Appbase release. Please prioritize accordingly.
