### ISSUE TITLE
Under rare sitations, "id" in jsonrpc response is missing

### ISSUE THREAD

**Issue by inertia186** [steemit/steem#2341]
When constructing a jsonrpc request, the `id` is passed:

```json
{
   "jsonrpc":"2.0",
   "method":"condenser_api.get_ops_in_block",
   "params":[
      21626788,
      true
   ],
   "id":1234
}
```

Error on get_ops_in_block for block 21626788

```json
{
   "code":-32603,
   "message":"Internal Error",
   "data":{
      "error_id":"aaf94776-205e-4383-8e2e-0bd49a19e922",
      "request":{
         "amzn_trace_id":"Root=1-5ad5067b-5786f674bc2f4cc6a78ab6ae",
         "jussi_request_id":null
      }
   }
}
```

... or ...

```json
{
   "code":-32003,
   "message":"Unable to acquire database lock"
}
```

In both situations, the `id` (1234) is missing from the response.

**Comment by theoreticalbts** [comment]
Are you querying a steemit.com endpoint, or are you running steemd locally?

**Comment by mvandeberg** [comment]
```
{
   "code":-32603,
   "message":"Internal Error",
   "data":{
      "error_id":"aaf94776-205e-4383-8e2e-0bd49a19e922",
      "request":{
         "amzn_trace_id":"Root=1-5ad5067b-5786f674bc2f4cc6a78ab6ae",
         "jussi_request_id":null
      }
   }
}
```

is not a steemd error. Looks like Jussi to me ;)

However, 

```
{
   "code":-32003,
   "message":"Unable to acquire database lock"
}
``` 

is a steemd error and should be returning the with the id and the `jsonrpc` field. This is very strange because the jsonrpc field is set in the response object on construction. This needs to be investigated. It may be a Jussi translation error?

https://github.com/steemit/steem/blob/master/libraries/plugins/json_rpc/json_rpc_plugin.cpp#L32-L38

If we make an API that acquires the write lock and doesn't let go, I bet the response would have both the `jsonrpc` and `id` fields.

**Comment by inertia186** [comment]
My code would only log that there was a missing `id` and show me `error`, not the original response body.

Now I'm worried that my test app had two simultaneous requests from the first example but dumped the error from the second example first.  There are some asynchronous components in the app I'm running, so it's possible they were reported to the log out of order.

I'll see if I can recreate this with just `curl`, if we have another rash of `Unable to acquire database lock`.

**Comment by mvandeberg** [comment]
My local testing returned a response of the form:

```
{"jsonrpc":"2.0","error":{"code":-32003,"message":"Unable to acquire database lock"},"id":2}
```

It could be a Jussi error. However, for now, I do not believe this to be a problem with steemd.

**Comment by inertia186** [comment]
I think this is an error on my end.  I'll keep investigating.
