### ISSUE TITLE
Explore Upgrading to Boost 1.62

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#2344]
This is an exploratory issue to cost out potential future work.

Boost 1.62 is the default boost included in Ubuntu 18.04 LTS. We should determine what incompatibilities exist and the path to upgrade if we so choose.

I know fc threads are broken. Perhaps we can vendor in the specific libraries needed for fc threads and everything else can use Boost 1.62 as a stop gap until we can replace the p2p code.

**Comment by abitmore** [comment]
FYI BitShares has boost 1.62 in production already. https://github.com/bitshares/bitshares-fc/pull/5.

**Comment by mvandeberg** [comment]
Thank you, I will take a look.
