### ISSUE TITLE
Update smt_setup_operation implementation and tests.

### ISSUE THREAD

**Issue by Kiwonik** [steemit/steem#2345]
During implementation of `smt_cap_reveal_operation` (#1511) some issues were discovered with previously implemented `smt_setup_operation`. They are described by appropriate pragmas in `smt_setup_evaluator::do_apply` method:
```
#pragma message ("TODO: Adjust assertion below and add/modify negative tests appropriately.")
   const auto* _token = _db.find< smt_token_object, by_symbol >( o.symbol );
   FC_ASSERT( _token, "SMT ${ac} not elevated yet.",("ac", o.control_account) );

   _db.modify(  *_token, [&]( smt_token_object& token )
   {
#pragma message ("TODO: Add/modify test to check the token phase correctly set.")
      token.phase = smt_phase::setup_completed;
```
So the first one is about updating assertion and SMT setup tests to current logic where single account may control several tokens. The second one is about updating SMT setup tests to check that appropriate phase is/isn't set after setup operation evaluation success/failure.

**Comment by youkaicountry** [comment]
Closing as outdated.
