### ISSUE TITLE
Duplicate transaction check failed

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#2347]
On Ubuntu 16.04, latest master as on yesterday:
```
{
  "blockchain_version": "0.19.4",
  "client_version": "v0.19.4rc1-111-gdb93b69",
  "steem_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "steem_revision_age": "8 days ago",
  "fc_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "fc_revision_age": "8 days ago",
  "compile_date": "compiled on Apr 16 2018 at 16:21:48",
  "boost_version": "1.58",
  "openssl_version": "OpenSSL 1.0.2g  1 Mar 2016",
  "build": "linux 64-bit",
  "server_blockchain_version": "0.19.4",
  "server_steem_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "server_fc_revision": "db93b696503d04cb0b82dc96578b3924db233ff3"
}
```

After generating a block (`21647145`), the node failed to apply the next one with the following error:
`10 assert_exception: Assert Exception
(skip & skip_transaction_dupe_check) || trx_idx.indices().get<by_trx_id>().find(trx_id) == trx_idx.indices().get<by_trx_id>().end(): Duplicate transaction check failed`
The node do not crash, but remains unable to sync.

More details [here on pastebin](https://pastebin.com/0wAY7HEK)

**Comment by roadscape** [comment]
The node which stopped syncing was a block producer?

**Comment by mvandeberg** [comment]
It cannot sync even after restarting it?

**Comment by mvandeberg** [comment]
Alright, I think I know what it is. When we introduced the batch write queue, we did not change the witness plugin to work alongside it. There is a race conditions between incoming pending transactions and generating a block due to lack of synchronization.

`generate_block` should be exposed as a write type in `chain_plugin` to use the batch write queue. Additionally, we should allow some parameters in the chain plugin to let a witness node pre-empt all reads when writes occur. It is paramount that a witness node never fall behind in database writes.

**Comment by mvandeberg** [comment]
@BhuzOr Thank you so much for testing appbase on your witness node. It is likely we would not have caught this otherwise. I do believe restarting the node should fix the problem as it will reset undo states.

**Comment by BhuzOr** [comment]
@mvandeberg Sorry for not being very clear, I meant the node will keep failing in pushing blocks if doing nothing. After restart everything works good and the node will sync back... until that issue happens again ofc.

**Comment by mvandeberg** [comment]
Until this is fixed, I recommend your witness node run `stable` to ensure stability in block generation.

**Comment by BhuzOr** [comment]
Unfortunately it's been a while that my witness position is a bit down in the list, so I figured that I would be more useful by testing new developing code as a block producer than just "be safe" signing few blocks a day on stable xD

I am available for testing a fix as soon as it will be available! Until then, if you think it's better to run stable even considering my low production rate, I will switch to it :)
