### ISSUE TITLE
Create smt_set_setup_parameters_operation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2348]
Create the `smt_set_setup_parameters_operation`.

It is defined in the whitepaper:
`struct smt_set_setup_parameters_operation
{
account_name_type control_account;
flat_set< smt_setup_parameter > setup_parameters;
extensions_type extensions;
};`

**Comment by vogel76** [comment]
@youkaicountry AFAIK this has been already done. Work has been done in the issue:
https://github.com/steemit/steem/issues/1516
Of course it is worth to check if spec has been changed in the meantime - if so, please specify which parts shall be adjusted in the made implementation.

**Comment by youkaicountry** [comment]
You're correct, this has already been implemented. Closing this issue.
