### ISSUE TITLE
follow_plugin is rejecting transactions

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#235]
See [this](https://steemit.com/steemit-help/@patrice/steem-reputation-flagging) user report.

**Comment by mvandeberg** [comment]
I am curious then, which miner/witness is running the follow plugin?

```
try
   {
      op_obj.op.visit( on_operation_visitor( _self ) );
   }
   catch( fc::assert_exception )
   {
      if( database().is_producing() ) throw;
   }
```

This was logic left in from @bytemaster's original implementation of the plugin.

**Comment by theoreticalbts** [comment]
`is_producing()` is set to `true` when doing `push_transaction`.  Thus, any `is_producing()` check will not only be applied when you're a block producer, it will also apply to locally generated tx's and tx's that come in via the p2p network.
