### ISSUE TITLE
[appbase] You have already voted in a similar way

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#2353]
On Ubuntu 16.04, latest master as of yesterday, running as a block producer:
```
{
  "blockchain_version": "0.19.4",
  "client_version": "v0.19.4rc1-111-gdb93b69",
  "steem_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "steem_revision_age": "8 days ago",
  "fc_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "fc_revision_age": "8 days ago",
  "compile_date": "compiled on Apr 16 2018 at 16:21:48",
  "boost_version": "1.58",
  "openssl_version": "OpenSSL 1.0.2g  1 Mar 2016",
  "build": "linux 64-bit",
  "server_blockchain_version": "0.19.4",
  "server_steem_revision": "db93b696503d04cb0b82dc96578b3924db233ff3",
  "server_fc_revision": "db93b696503d04cb0b82dc96578b3924db233ff3"
}
```

After generating block `21655927` the node failed to apply the next one with the following error:
`10 assert_exception: Assert Exception
itr->vote_percent != o.weight: You have already voted in a similar way.`
The node do not crash but keep failing in pushing new blocks.
Unfortunately restarting the node do **not** solve the issue!
More info [here](http://termbin.com/2ghx)

I will wait for a response before trying a replay.

**Comment by mvandeberg** [comment]
It is possible the way in which the undo state was invalidated that the state was written to the database but is not present in an undo state, which effectively makes it irreversible even though it shouldn't be. Currently, this behavior can be explained by the same bug causing #2347
