### ISSUE TITLE
Update non-C++ libraries with SMT support

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2358]
Update all python/js libraries to support SMT related changes.

**Comment by mvandeberg** [comment]
A pre-requisite for this is going to be finalizing all non-`condenser_api` APIs as `condenser_api` does not support the new asset serialization required for SMTs.

Not directly included in this work, but related, is the official sunset of monolithic APIs in `condenser_api` such as `get_state`.

**Comment by youkaicountry** [comment]
Closing as outdated.
