### ISSUE TITLE
Payout time can be extended

### ISSUE THREAD

**Issue by riensen** [steemit/steem#236]
Some Posts are able to extend their payout time post 12 hrs which makes them visible for for longer in the trending category and indirectly leads to higher payouts. Edits could play a role.

Example 23 hrs:
https://steemd.com/introduceyourself/@mihaiart/hi-i-am-mihai-artist-painter-illustrator-and-i-m-bringing-my-talents-to-steemit

https://steemit.com/scam/@r4fken/warning-scammer-on-steemit-steem-cash-is-the-latest-project-of-a-known-con-man

Counter example 12 hrs:
https://steemit.com/steemevents/@originate/steem-meetup-the-steem-meetup-group-is-now-live-create-and-attend-local-steem-events-in-your-city

**Comment by mvandeberg** [comment]
This is intended. Payout times are stake weighted voting. A whale voting for a post at the end of the payout time may extend the payout time another 12 hours, or close to it. This is needed so that posts with high payouts can be accurately curated.

**Comment by riensen** [comment]
Thanks for clarifying!
