### ISSUE TITLE
get_account_history does not always return the first element when index> -1

### ISSUE THREAD

**Issue by holgern** [steemit/steem#2373]
Related to changes in #2337 
https://utopian.io/utopian-io/@holger80/getaccounthistory-does-not-return-the-first-element-when-index-1

On specific accounts, e.g. account test, the first account operation can only be received when setting from=-1&limit=13.

The first operation with virtual index 0, is an account_create operation.

```
from steem.account import Account
acc = Account("test")
hist=[]
for h in acc.get_account_history(-1,13,order=1,raw_output=True): hist.append(h)
print(hist[0][0], hist[0][1]["op"][0])
```
0, account_create

But when setting index to an higher value, the first account_create  operation cannot be recieved anymore:

```
hist=[]
for h in acc.get_account_history(5,5,order=1,raw_output=True): hist.append(h)
print(hist[0][0], hist[0][1]["op"][0])
```
1 transfer

When increasing limit to 6, the rpc api call is not sucessful:
```
hist=[]
for h in acc.get_account_history(5,6,order=1,raw_output=True): hist.append(h)
```
Exception:args.start >= args.limit: start must be greater than limit

But:

```
from steem.account import Account
acc = Account("holger80")
hist=[]
for h in acc.get_account_history(1,1,order=-1,raw_output=True): hist.append(h)
print(hist[0][0], hist[0][1]["op"][0])
```
0 account_create_with_delegation

```
from steem.account import Account
acc = Account("justyy")
hist=[]
for h in acc.get_account_history(1,1,order=-1,raw_output=True): hist.append(h)
print(hist[0][0], hist[0][1]["op"][0])
```
0 account_create

```
from steem.account import Account
acc = Account("test")
hist=[]
for h in acc.get_account_history(1,1,order=-1,raw_output=True): hist.append(h)
print(hist[0][0], hist[0][1]["op"][0])
```
1 transfer

Not using python but steemjs:

https://api.steemjs.com/get_account_history?account=test&from=1&limit=1
Returns a transfer operation
https://api.steemjs.com/get_account_history?account=holger80&from=1&limit=1
Returns a account_create_with_delegation operation
https://api.steemjs.com/get_account_history?account=justyy&from=1&limit=1
Returns an account_create operation

**Comment by therealwolf42** [comment]
Same problem here - https://github.com/therealwolf42/steemmessenger

Had to temporary disable nodes that use 19.4

**Comment by mvandeberg** [comment]
I am not entirely sure what you are saying the problem is. 

` curl -d '{"jsonrpc":"2.0", "method":"call", "params":["database_api", "get_account_history", ["test", 5, 5]], "id":1}' https://api.steemit.com`

Index 0 is an `account_create`.

`curl -d '{"jsonrpc":"2.0", "method":"call", "params":["database_api", "get_account_history", ["test", 5, 6]], "id":1}' https://api.steemit.com`

Fails as expected.

**Comment by holgern** [comment]
Seem to work now and this issue can be closed.
