### ISSUE TITLE
Released source wont build - what is the dependency?

### ISSUE THREAD

**Issue by shawnpringle** [steemit/steem#238]
I tried to build this with a tar ball 0.12.2.  I decided this might have been a packaging problem.  I checked it out with git and I got the same error.  So, what dependency am I missing?

>   alumno@Exomate-X352 ~/development/steem-0.12.2 $ ls
>   BUILD_OSX.md     CMakeFiles      Doxyfile          libraries   python_scripts
>   BUILD_UBUNTU.md  CMakeLists.txt  example_plugins   LICENSE.md  README.md
>   CMakeCache.txt   doc             external_plugins  programs    tests
>   alumno@Exomate-X352 ~/development/steem-0.12.2 $ cmake .
>   CMake Error at CMakeLists.txt:35 (include):
>     include could not find load file:
>   
>       GetGitRevisionDescription
>   
>   
>   CMake Error at CMakeLists.txt:36 (get_git_head_revision):
>     Unknown CMake command "get_git_head_revision".
>   
>   
>   -- Configuring incomplete, errors occurred!
>   See also "/home/alumno/development/steem-0.12.2/CMakeFiles/CMakeOutput.log".

**Comment by mvandeberg** [comment]
I think that is the error when you do not grab submodules.

`git submodule update --init --recursive`

**Comment by shawnpringle** [comment]
Thanks for getting back to me so fast!  I am trying it now.

**Comment by shawnpringle** [comment]
That was not in the BUILD_UBUNTU.md doc.  Maybe it ought to be added?

I am getting new errors now:  Progress. :)  I need to figure out how to get cmake to look in /usr/local/lib for boost 1.60 and maybe I need to make it use gcc-4.9.  My system default is 4.8.

**Comment by abitmore** [comment]
@shawnpringle please check https://github.com/cryptonomex/graphene/wiki/build-ubuntu for reference. The BUILD_UBUNTU doc in this repo is incompleted. Afaik gcc-4.8 works fine with boost 1.57.

**Comment by theoreticalbts** [comment]
Closing, any further discussion should move to #283

**Comment by theoreticalbts** [comment]
If you're still having this issue, check out the [new build instructions](https://github.com/steemit/steem/blob/develop/doc/build-ubuntu.md).

**Comment by shawnpringle** [comment]
No more problems installing Steemd.   These new instructions should help
lots of steemd newbies.

**Comment by horsecoin** [comment]
cd libraries/fc
git fetch --all
git pull

worked for me!
