### ISSUE TITLE
Missing followers

### ISSUE THREAD

**Issue by mariusztrela** [steemit/steem#2382]
The proof was found that the problem with missing follows is due to commit `2340f2a811c4269a4452b2f6defd96151e73148e` ( `Update condenser_api to use old static_variant JSON serialization #2044` )
It's enough to replay 4,500,000 blocks to see the difference. Here are the commands which were executed:

```
BRANCH 'develop' - with commit `2340f2a811c4269a4452b2f6defd96151e73148e`
./steemd --replay-blockchain --stop-replay-at-block 4500000
curl --data '{"jsonrpc":"2.0","id":"2","method":"follow_api.get_followers","params":{ "account":"heiditravels", "start":"", "type":"blog", "limit":1000 } }' http://127.0.0.1:8090/rpc
```
```
BRANCH 'develop' - without commit `2340f2a811c4269a4452b2f6defd96151e73148e`
./steemd --replay-blockchain --stop-replay-at-block 4500000
curl --data '{"jsonrpc":"2.0","id":"2","method":"follow_api.get_followers","params":{ "account":"heiditravels", "start":"", "type":"blog", "limit":1000 } }' http://127.0.0.1:8090/rpc
```

During comparison of the results of the curl requests, we can see that current develop is lacking a single follower of `heiditravels`, while develop with given commit reverted prints it correctly.

Here is the missing follower info:

```
{
			"follower": "jamesc",
			"following": "heiditravels",
			"what": ["blog"]
}
```

Details:
The difference was discovered at block `4,481,977`.
The follow operation of `jamesc` was introduced at block `4,450,048`.

I also checked reverting my commit 1999 follow plugin, doesn't help. The follower jamesc is still missing.

**Comment by mvandeberg** [comment]
The fix is to have an old static variant deserializer for custom json operations. To keep static variant serializations consistent, we'll hardfork which serializer we use at a later date.

**Comment by mvandeberg** [comment]
@youkaicountry Be advised that this needs to also be updated before an Appbase release can be made. Please prioritize accordingly.
