### ISSUE TITLE
can set multiple witnesses  in private testnet?

### ISSUE THREAD

**Issue by smallnest** [steemit/steem#2388]
I have set up a private testnet that follows https://steemit.com/steem/@dantheman/how-to-start-a-test-network.

It works and it contains a  "initminer" witness.

Can I setup another node with customized witness such as "abc" and join it into thr first node?

**Comment by mvandeberg** [comment]
The instructions there are outdated. Steemit is currently working on streamlining test net creation. We will make an announcement when it is ready. Until then, we will not provide support for running a test net.
