### ISSUE TITLE
Synch error on master: item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#2395]
I did a fresh build of the master branch and am running `steemd --resync-blockchain`. In the process of resynching, it is outputting several of these errors. It continues on after the error, although it has output the error several times throughout the process so far.

```
1658360ms p2p_plugin.cpp:182            handle_block         ] Error when pushing block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":200,"head":913,"max_size":22}
    fork_database.cpp:57 _push_block

    {}
    database.cpp:673 _push_block

    {"new_block":{"previous":"000000c78dd942bb3b207f3a25ca798330f47cb4","timestamp":"2016-03-24T16:15:30","witness":"initminer","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"202df59b25ce8c41c8027c676961dbad5a7c59921cbeb402c96ddeb800aadaca4d03305911e59e40abcab801005e6f173ff5245f598446f56b07bc6b016becc35f","transactions":[]}}
    database.cpp:558 operator()
```

Attached are the full log file and config.ini from the server:
[full_log.log](https://github.com/steemit/steem/files/1959294/full_log.log)
[config.ini](https://github.com/steemit/steem/files/1959295/config.ini.txt)

**Comment by mvandeberg** [comment]
Are these errors preventing progress to be made on the sync?

**Comment by TimCliff** [comment]
No. The last I checked on it, it was still proceeding after the errors.

**Comment by mvandeberg** [comment]
If blocks were received out of order for any reason, this error could occur. I have observed an increased error rate with Appbase, but I have seen it since the launch of Steem.

**Comment by quochuy** [comment]
@mvandeberg I'm getting the same error on a seed node and in my case it does prevent progress to be made on the sync. It occurred 5 times but it is now stuck on the 5th one for over 24 hours now.

**Comment by quochuy** [comment]
From the core dump:
```Cannot access memory at address 0x10000000108
Cannot access memory at address 0x10000000100
Core was generated by `steemd --data-dir=/steem/witness_node_data_dir --replay'.
Program terminated with signal SIGBUS, Bus error.
#0  0x0000000000eee7ff in steem::plugins::condenser_api::detail::condenser_api_impl::get_withdraw_routes(std::vector<fc::variant, std::allocator<fc::variant> > const&) ()
[Current thread is 1 (LWP 1)]```

**Comment by Jolly-Pirate** [comment]
The error happens often on AppBase with 3 outcomes:
- let it be, after a few minutes it resumes
- restart steemd, then it resumes
- it stalls for hours with no progress at all, a restart doesn't help
