### ISSUE TITLE
Bots Voting for Each Other to Gain Reputation 

### ISSUE THREAD

**Issue by tyrinwu** [steemit/steem#241]
@steemitlove and other 40 bots are voting for each other and boost their below-zero reputation.  I found that his reputation went from -34,801,162,687,430 to -34,800,926,986,062 in a short while (an increase of 235,701,196 reputation scores). Please see the pictures below for detail. 

![](http://i67.tinypic.com/30n84kh.png)
![](http://i63.tinypic.com/30m50kk.png)
### Screenshot took at 7:07 UTC +8 
![](http://i64.tinypic.com/vqp10x.png)
### A difference of  235,701,196 in reputation from 7:07 to 7:13 UTC +8

This problem probably derives from that even votes from a low reputation guy would counts when it comes to reputation computation.

**Comment by abitmore** [comment]
In theory they won't gain reputation score if all accounts have negative scores. But they can gain some payout by self-voting. Probably some innocent legit user upvoted them, so reputation score increased?

**Comment by abitmore** [comment]
Found 2 accounts in the bot army with around +6 rep scores: `emilyelizabeth` and `soupernerd`. So yes, their rep score will increase slowly.
