### ISSUE TITLE
Token Emissions Bound Spike

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2430]
Token emissions are bounded at some value to prevent integer overflow. A bounding value needs to be chosen.

Some candidates:
- `STEEM_MAX_SHARE_SUPPLY`
- `STEEM_MAX_SATOSHIS`

The result of this spike should be a consensus on what value should bound emissions.

Related issue: #2429

**Comment by theoreticalbts** [comment]
`STEEM_MAX_SHARE_SUPPLY` is chosen to be the highest power of 10 less than `2^53`.  The significance of the value `2^53` is the mantissa size of `double`, which is the native "integer" type of JavaScript.  If we allow more than `2^53` satoshis of an asset, JavaScript Steem libraries may need to be rewritten to always use arbitrary-precision integers for satoshis.

I don't *believe* there is any C++ code in `steemd` which will break by raising to `2^64-1`, although I would suggest only raising the limit to `2^62-1` to be safe (setting aside one bit for a sign bit and another bit for arithmetic overflow).

It Would Be Nice to have better compile-time bounds checking of asset arithmetic, see #1646.

**Comment by Kiwonik** [comment]
1. It looks like `STEEM_MAX_SHARE_SUPPLY` is **not** used at all to check or limit the STEEM supply. What is its purpose then?
1. Same for `STEEM_MAX_SATOSHIS` - it pretends to be used in `asset::validate` but the method is **not** called anywhere.
1. Are these symbols a part of some unfinished effort @theoreticalbts ? Or were they created to control SMT supply and need their misleading names replaced with `SMT_...` prefixes?

**Comment by youkaicountry** [comment]
Closing as outdated,
