### ISSUE TITLE
cli_wallet Testing Spike

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2437]
The cli_wallet is going to need tested for appbase release. Before doing so, we need to identify what functionality we should ensure is working.

Some potential candidates:
- Importing keys
- Transfers
- Memos

The result of this spike should be a consensus on a list of functions to test in cli_wallet.

**Comment by mvandeberg** [comment]
Ideally, all commands should work.

The core functionality I think is needed for a meaningful wallet:

- Import keys
- List accounts by keys
- Transfer
- Account History
- Get blocks

I am not sure if encrypted memos in the cli wallet are widely used. I've never used the feature. IIRC, I was brought over from BitShares.

**Comment by theoreticalbts** [comment]
- Memos
- Transfer to vesting
- Withdraw from vesting

**Comment by youkaicountry** [comment]
Completed, and results recorded in issue #2438.

**Comment by theoreticalbts** [comment]
Maybe we should add account creation to the list.
