### ISSUE TITLE
cli_wallet Manual Testing

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2438]
Before appbase release, the functionality identified in #2437 should be manually tested in cli_wallet.

Acceptance Criteria:
* All listed features have been manually tested.
* All listed features are identified as either working or non-working. 

The identified functions to test:
- Import keys
- List accounts by keys
- Transfer
- Account History
- Get blocks- Memos
- Transfer to vesting
- Withdraw from vesting

**Comment by theoreticalbts** [comment]
Blocked by #2451, since in order to test this I need to create accounts, and I can't.  (Account creation isn't on the list, but maybe it should be?)

Bugs discovered: #2450
