### ISSUE TITLE
find_comments missing pending_payout_value

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2445]
The new `database_api.find_comments()` is missing `pending_payout_value`, and it doesn't seem to be available elsewhere.

---

For reference, these other `get_content` fields are also not in `find_comments` (not unexpectedly):
```
external objects
< "active_votes"
< "replies"

tag/follow-related
< "author_reputation"
< "promoted"
< "reblogged_by"

convenience
< "body_length"
< "root_title"
< "url"

deprecated
< "total_pending_payout_value"
```

**Comment by mvandeberg** [comment]
The new `database_api` returns the objects as they exist in the database. It does not add any additional information.
