### ISSUE TITLE
docker build stuck at steem_chain

### ISSUE THREAD

**Issue by younseunghyun** [steemit/steem#2459]
currently I'm following a build example by docker.

It works fine, but it is stucked at building for steem_chain.

It just happen to me or there is a problem for that?

**Comment by younseunghyun** [comment]
this is problem of build from master branch.

change branch to stable works fine

**Comment by mvandeberg** [comment]
Can you please share what the error was? We use Docker to build for our CI and have had problems.

**Comment by younseunghyun** [comment]
I just stucked when i build by docker.

it doesnt progressed at 78%.

I just changed branch to stable

**Comment by mvandeberg** [comment]
How long are you waiting? The Docker build contains our entire test suite and multiple build configurations. Even on a fast system, it can take over an hour to build.

**Comment by younseunghyun** [comment]
I’m waiting for an hour. if that was due to test case, then stable branch
have to not cotain test case. right? i didnt checked there is test cases or
not
2018년 5월 22일 (화) 오후 1:28, Michael Vandeberg <notifications@github.com>님이 작성:

**Comment by younseunghyun** [comment]
@mvandeberg Yeah, It may be due to test case.

I find that stable branch doesn't contain test suite for plugin.

I will try again with master branch again, and i will start build at late night , have a sleep, then check at morning :)

# stable
```
RUN \
    cd /usr/local/src/steem && \
    git submodule update --init --recursive && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_STEEM_TESTNET=ON \
        -DLOW_MEMORY_NODE=OFF \
        -DCLEAR_VOTES=ON \
        -DSKIP_BY_TX_ID=ON \
        .. && \
    make -j$(nproc) chain_test test_fixed_string && \
    ./tests/chain_test && \
    ./programs/util/test_fixed_string && \
    cd /usr/local/src/steem && \
    doxygen && \
    programs/build_helpers/check_reflect.py && \
    programs/build_helpers/get_config_check.sh && \
    rm -rf /usr/local/src/steem/build
```

# master

```
RUN \
    cd /usr/local/src/steem && \
    git submodule update --init --recursive && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_STEEM_TESTNET=ON \
        -DLOW_MEMORY_NODE=OFF \
        -DCLEAR_VOTES=ON \
        -DSKIP_BY_TX_ID=ON \
        .. && \
    make -j$(nproc) chain_test test_fixed_string plugin_test && \
    ./tests/chain_test && \
    ./tests/plugin_test && \
    ./programs/util/test_fixed_string && \
    cd /usr/local/src/steem && \
    doxygen && \
    PYTHONPATH=programs/build_helpers \
    python3 -m steem_build_helpers.check_reflect && \
    programs/build_helpers/get_config_check.sh && \
    rm -rf /usr/local/src/steem/build
```

**Comment by younseunghyun** [comment]
@mvandeberg 

I encounter error. 

Error log is like this

```
The command '/bin/sh -c cd /usr/local/src/steem &&     git submodule update --init --recursive &&     mkdir build &&     cd build &&     cmake         -DCMAKE_BUILD_TYPE=Release         -DBUILD_STEEM_TESTNET=ON         -DLOW_MEMORY_NODE=OFF         -DCLEAR_VOTES=ON         -DSKIP_BY_TX_ID=ON         .. &&     make -j$(nproc) chain_test test_fixed_string plugin_test &&     ./tests/chain_test &&     ./tests/plugin_test &&     ./programs/util/test_fixed_string &&     cd /usr/local/src/steem &&     doxygen &&     PYTHONPATH=programs/build_helpers     python3 -m steem_build_helpers.check_reflect &&     programs/build_helpers/get_config_check.sh &&     rm -rf /usr/local/src/steem/build' returned a non-zero code: 137
```

It looks like fatal error with signal 9, http://tldp.org/LDP/abs/html/exitcodes.html

What is problem for me?

I ran build on 16GB memory, 2.5GH i7 cpu machine (Mac book pro Mid 2015)

**Comment by younseunghyun** [comment]
now stable branch is also stucked at 78%, sometimes at 70%.
 
Is there are test suite which is depends on time?

**Comment by younseunghyun** [comment]
build at local seems  to be fine.

I build steem on my mac environment following build guide for mac env.

**Comment by mvandeberg** [comment]
If you were building in docker machine on a Mac, the VM may be under-provisioned. A building failing during compilation leads me to think the VM might have been OOM.

**Comment by younseunghyun** [comment]
right. It may be problem of VM spec of Mac environment.

I will try to build image with more higher spec than before ( before 2 cpu, 2 gb ram limit, after 8 cpu 16 gb ram)

Then, what is appropriate ram size to build image properly ?

**Comment by younseunghyun** [comment]
After increase ram size of docker-machine, pass the stuck stage.

It was problem of ram size of docker-machine. Thx
