### ISSUE TITLE
Allow broadcast disable with configurable threshold

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#247]

**Comment by theoreticalbts** [comment]
See `doc/bcd-trigger.md` for documentation.

**Comment by abitmore** [comment]
This option can (should?) be used on steemit.com as well, in case when an issue like https://github.com/steemit/steem/commit/2096e96eb97e4c85c0c9445ff8f0156c5ac2a620 occurs again. That said, posting/transferring should be disabled when steemit.com is forking to a minor chain.

Some suggestions given by @arhag  quoted here:
>I want to reiterate that I think in the next hardfork, all transactions that include an operation other than ﻿⁠⁠⁠⁠witness_update_operation﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠account_witness_vote_operation﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠account_witness_proxy_operation﻿⁠⁠⁠⁠, ﻿⁠⁠⁠⁠feed_publish_operation﻿⁠⁠⁠⁠, or ﻿⁠⁠⁠⁠pow2_operation﻿⁠⁠⁠⁠ should be rejected under the condition when witness participation is below some threshold. (I suppose you could also allow ﻿⁠⁠⁠⁠account_update_operation﻿⁠⁠⁠⁠ but only if it doesn't change owner keys).
