### ISSUE TITLE
Failed to Open Link from Whatsapp

### ISSUE THREAD

**Issue by cybermaya** [steemit/steem#2494]

**Comment by TimCliff** [comment]
@cybermaya - whatever your issue is, this is the wrong repository. Is this an issue with condenser (the code for steemit.com)?

Also, there needs to be more details in the issue (such as steps to repro) in order for anyone to assist.

**Comment by cybermaya** [comment]
I am beginneer to this. Please guide me to do this better

**Comment by TimCliff** [comment]
@cybermaya if you head to steem.chat and go to the #help channel, there are people who can help.
