### ISSUE TITLE
How can I send fund from a cold wallet?

### ISSUE THREAD

**Issue by egonson** [steemit/steem#2495]
After creating a new account with the keys that generated on an offline laptop, how can I send fund with that account?

I couldn't find any help about this.

**Comment by TimCliff** [comment]
@egonson - you will need to use the keys from your cold wallet on a “hot” (connected) server if you want to do any transfers with it.

It is best to use your private active key (not owner) when doing transfers.

After you are done with the transfer(s), you can update the keys on the account again to new keys that are generated on the “cold” (offline) server.

**Comment by egonson** [comment]
Thank you for the answer. It was really helpful.

**Comment by roadscape** [comment]
You could also use steem-python to generate transactions offline, and broadcast them on a separate machine.
