### ISSUE TITLE
Restore default vesting route upon account recovery

### ISSUE THREAD

**Issue by gryter** [steemit/steem#2498]
Hackers have been changing the set_withdraw_vesting_route to their own accounts to continue milking victims after recovery.

We need to have the set_withdraw_vesting_route auto-revoked (the to_account reset to from_account) and restored to default upon recovery.

Example:
![maruharraca steem - 2018-05-24_17-36-48](https://user-images.githubusercontent.com/31012685/40515189-e2c7db0c-5f79-11e8-89d0-553ff264c43a.png)

The sami100 account belongs to a know hacker who runs a script that finds accidentally posted passwords and active keys.

**Comment by mvandeberg** [comment]
We could reset routes when an account is recovered, but this creates a situation where an undetermined number of routes are reset on recovery.

Imagine the scenario where a hacker sets the smallest route possible to each of their bot accounts. The account's bandwidth covers the cost of creating the routes, but because we don't know what the total impact of the recovery is, it is hard to cost the recover.

**Comment by gryter** [comment]
Draining the bandwidth is a small price to pay.  The issue would be if the account runs out of bandwidth as you suggested. Increasing the delegation, if any, to it during the bundled recovery process and then immediately removing would prevent that. 

Limiting the number of routes would be a related step.  Currently the largest botnet we have logged in Steemcleaners is approx 20k known accounts. 20k routes for one powering down account would be detrimental to the blockchain.

**Comment by mvandeberg** [comment]
I double checked and the maximum number of routes is 10.

I have a better suggestion. If we enabled managing vesting withdraw routes in condenser, then we do not need to modify steemd behavior to address the problem.

**Comment by gryter** [comment]
Agreed.  Managing beneficiaries and delegations directly in condenser can go along with that too.

**Comment by roadscape** [comment]
Moved to https://github.com/steemit/condenser/issues/2835
