### ISSUE TITLE
StatsD push_block / push_transaction timing

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2511]
The time `push_block` and `push_transaction` take to execute should be logged, as well as any useful information (block id, txn id, etc)

Acceptance criteria:
- [ ] Time `push_block` takes should be measured.
- [ ] Time `push_transaction` takes should be measured
- [ ] Data should be sent via StatsD plugin

**Comment by mvandeberg** [comment]
Some of this work may have been done already in the `chain_plugin`
