### ISSUE TITLE
Seven day cool-down period for undelegation potentially creates double-voting vulnerability.

### ISSUE THREAD

**Issue by pibara** [steemit/steem#2514]
Disclaimer: I haven't tested this to validate, as doing so without consent would constitute abuse. This means there is a small possibility this issue might be invalid.

There seems to be a double voting vulnerability in the fact that the undelegation cool-down period is only seven days.

I wrote a blog post [here](https://steemit.com/steem/@mattockfs/why-cool-down-for-undelegation-should-be-10-days) and @crokkon pointed out [here](https://steemit.com/steem/@mattockfs/why-cool-down-for-undelegation-should-be-10-days#@crokkon/re-mattockfs-re-crokkon-re-mattockfs-why-cool-down-for-undelegation-should-be-10-days-20180528t105530848z) that my example overcomplicated things and two accounts (instead of 12) would do the trick just as well.

The core of the problem:

* Bob does 200 100% votes bringing his voting strength down to 1.76%
* Bob delegates 10,000 SP to Alice
* Alice does 200 100% votes bringing her voting strength down to 1.76%
* Bob undelegates the 10,000 SP, starting off the seven-day cool-down period.
* After seven days everything is as in step 0 and the cycle starts over.

If we look at decrease in voting strenght as measure of cast vote rshares (what it is basically), under non-delegation circumstances, Bob could recover (and thus sustainably vote) 140% (7*20) worth of rshares  in one week. In the above scenario, however, Bob and Alice together manage to recover 196.5% (2 x 98.24) worth of rshares. What boils down to an about 40% worth of double voting vulnerability.

If the seven day cool-down period for undelegation were to be expanded to ten days, this vulnerability should be fixed.

**Comment by holgern** [comment]
Issue is addressed in https://github.com/steemit/steem/issues/2428
