### ISSUE TITLE
error update_witness in cli_wallet

### ISSUE THREAD

**Issue by jessezhj** [steemit/steem#2527]
run
`update_witness "node3" "" "TST7RHsJmJwqs2YQCapsoqqfMRfqDWkZReQxkmsE4Bqb1iHvrHPng" {"account_creation_fee":"10.000 TESTS","maximum_block_size":131072,"sbd_interest_rate":1000} true`

error
`10 assert_exception: Assert Exception
var.is_object(): Asset has to treated as object.
    asset.cpp:401 from_variant`

**Comment by inertia186** [comment]
We're seeing something similar in documentation: 

https://developers.steem.io/apidefinitions/condenser-api#condenser_api.broadcast_transaction_synchronous-curl-examples

In a nut-shell, `condenser_api` *appears to require non-legacy assets*, which seems like a bug.

If an op contains an asset (`1.000 STEEM`), it isn't being accepted, even if we use `condenser_api`.  But switching to `{"amount":"1000","precision":3,"nai":"@@000000021"}`, it works.  It doesn't seem like this should happen on `condenser_api`.

For example, I do not expect `Asset has to treated as object.` from this:

```bash
curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.broadcast_transaction_synchronous", "params":[{"ref_block_num":1097,"ref_block_prefix":2181793527,"expiration":"2016-03-24T18:00:21","operations":[["pow",{"worker_account":"cloop3","block_id":"00000449f7860b82b4fbe2f317c670e9f01d6d9a","nonce":3899,"work":{"worker":"STM7P5TDnA87Pj9T4mf6YHrhzjC1KbPZpNxLWCcVcHxNYXakpoT4F","input":"ae8e7c677119d22385f8c48026fee7aad7bba693bf788d7f27047f40b47738c0","signature":"1f38fe9a3f9989f84bd94aa5bbc88beaf09b67f825aa4450cf5105d111149ba6db560b582c7dbb026c7fc9c2eb5051815a72b17f6896ed59d3851d9a0f9883ca7a","work":"000e7b209d58f2e64b36e9bf12b999c6c7af168cc3fc41eb7f8a4bf796c174c3"},"props":{"account_creation_fee":"100.000 STEEM","maximum_block_size":131072,"sbd_interest_rate":1000}}]],"extensions":[],"signatures":[]}], "id":1}' https://api.steemit.com
```

Yet providing the new idomatic JSON avoids `Asset has to treated as object.`:

```bash
curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.broadcast_transaction_synchronous", "params":[{"ref_block_num":1097,"ref_block_prefix":2181793527,"expiration":"2016-03-24T18:00:21","operations":[["pow",{"worker_account":"cloop3","block_id":"00000449f7860b82b4fbe2f317c670e9f01d6d9a","nonce":3899,"work":{"worker":"STM7P5TDnA87Pj9T4mf6YHrhzjC1KbPZpNxLWCcVcHxNYXakpoT4F","input":"ae8e7c677119d22385f8c48026fee7aad7bba693bf788d7f27047f40b47738c0","signature":"1f38fe9a3f9989f84bd94aa5bbc88beaf09b67f825aa4450cf5105d111149ba6db560b582c7dbb026c7fc9c2eb5051815a72b17f6896ed59d3851d9a0f9883ca7a","work":"000e7b209d58f2e64b36e9bf12b999c6c7af168cc3fc41eb7f8a4bf796c174c3"},"props":{"account_creation_fee":{"amount":"100000","precision":3,"nai":"@@000000021"},"maximum_block_size":131072,"sbd_interest_rate":1000}}]],"extensions":[],"signatures":[]}], "id":1}' https://api.steemit.com
```

... giving us `transaction tapos exception`, which is the error we orignally expected in the first example.
