### ISSUE TITLE
how to get post content (question)

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#253]
I would expect calling `{"jsonrpc": "2.0","id":1,"method":"get_content", "params": ["joseph", "saturday-night-movie-the-terror-1963-full-movie-public-domain"]}`

would return the body of the post however in the results it is empty

`{"id":1,"result":{"id":"2.8.481916","author":"joseph","permlink":"saturday-night-movie-the-terror-1963-full-movie-public-domain","category":"movie","parent_author":"","parent_permlink":"movie","title":"","body":"","json_metadata":"","last_update":"2016-08-06T19:44:36","created":"2016-08-06T19:44:36","active":"2016-08-06T23:3...`

what is the best way to get the content of a post?

**Comment by omotherhen** [comment]
If you're running a low memory node it will give you this issue. Try recompiling with a full node and running that command.

**Comment by ByronAP** [comment]
yup that was it, thank you :-)

**Comment by theoreticalbts** [comment]
The point of low-memory node is not to track stuff not needed for consensus, and post bodies aren't needed for consensus.
