### ISSUE TITLE
Voting power inaccuracies

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#2530]
Querying the blockchain via the cli_wallet or steemjs says my `"voting_power": 7961` (79.61%) but on steemd.com it's 92.61%. The VP is stuck at 79.61% since last night. There are discrepencies for other accounts too.
Example: https://api.steemjs.com/get_accounts?names[]=["drakos"]

**Comment by mvandeberg** [comment]
The blockchain calculates voting power regeneration lazily while steemd.com calculates what your voting power would be. If you cast a vote your voting power will increase and for a short while steemd.com and the cli-wallet will match.
