### ISSUE TITLE
get_content is dependent on tags plugin

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2535]
`get_content` should not have a hard dependency on `tags` or `follows` plugins.

`assert_exception: 'Assert Exception:_tags_api: tags_api_plugin not enabled.' in get_content(['avizor', 're-unknownmystery-re-avizor-re-unknownmystery-re-avizor-foodboasting-my-selmade-roastbeef-with-potatoes-20180530t202851030z'])`

**Comment by roadscape** [comment]
Reportedly `get_active_votes` has the same issue, I guess because it includes reputation on each vote from the follows plugin.

**Comment by mvandeberg** [comment]
Ok, `get_active_votes` should be easier to fix.

**Comment by mvandeberg** [comment]
`get_content_replies` and `get_replies_by_last_update` both had unnecessary dependencies on `tags_api`.
