### ISSUE TITLE
Can't login to steemit.com

### ISSUE THREAD

**Issue by Invertisment** [steemit/steem#2540]
Hello.

I didn't know where to submit this type of issue so I do it here. If it does not belong here we can figure something out.

The login for me does not work with Firefox and Chrome. I believe this is some flawed JS code that fails, because eSteem app login works. Could anyone look at it?

Image:
![screenshot at 2018-06-11 06 55 51](https://user-images.githubusercontent.com/1641263/41212154-8f63c920-6d44-11e8-87a5-77633b6d014d.png)

**Comment by Invertisment** [comment]
The `csp_violation` failed request contains something about the failed Montserat font.

**Comment by mvandeberg** [comment]
The [Condenser](steemit/condenser) repo is the correct place to file this bug. Condenser is updated regularly. If this problem persists, please report it there.
