### ISSUE TITLE
'get_accounts' returns different reputation value on most full rpc nodes

### ISSUE THREAD

**Issue by steemchiller** [steemit/steem#2543]
Account: berniesanders (differences)

Node | Reputation
------------ | -------------
api.steemit.com | 988232893187 
api.steem.house | 988232893187
rpc.buildteam.io | 3130216690175
rpc.steemviz.com | 3130216690175
rpc2.steemviz.com | 3130216690175
steemd.privex.io | 3130216690175
steemd.pevo.science | 3130216690175

---

Account: steemchiller (all ok)

Node | Reputation
------------ | -------------
api.steemit.com | 20937247602333
api.steem.house | 20937247602333
rpc.buildteam.io | 20937247602333
rpc.steemviz.com | 20937247602333
rpc2.steemviz.com | 20937247602333
steemd.privex.io | 20937247602333
steemd.pevo.science | 20937247602333

**Comment by Gandalf-the-Grey** [comment]
@steemchiller Just a quick note, I'm in the middle of testing / rebuilding my appbase based endpoint so currently when you make a request to `api.steem.house` you will be most likely proxied to `api.steemit.com` that's why you get same results.

**Comment by mvandeberg** [comment]
I believe the discrepancy is due to #946.

It is fixed and running on our nodes but has not yet been included in a numbered release of Steem.
