### ISSUE TITLE
`vote2_operation` - specify rshares instead of percent weight

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2545]
A downside of specifying only percent `weight` in a `vote` op is that it's not possible to calculate `rshares` outside of steemd (you would have to know the exact VP and VESTS balance at the time of the vote). Vote `rshares` data is only available via steemd API and it only tracks latest state.

Since `rshares` has a lot of utility it would be ideal if we could eventually migrate to a sort of `vote2` operation which has you specify `rshares` instead of `weight`. This would allow outside apps easy and direct access to the raw value.

Steemd *could* maintain the current vote power logic and simply enforce that the specified rshares don't exceed what a 100% vote would be able to generate at that moment. Or this restriction could be loosened to give users more flexibility over how they distribute their influence.

Likewise, frontends could implement the same vote power logic to submit equivalent ops without changing UX. Or they could easily implement constant-weight voting.

**Comment by mvandeberg** [comment]
This is related to the stateless discussion we were having this week.

**Comment by mvandeberg** [comment]
Will be implemented in #2748
