### ISSUE TITLE
Measure Computational Load of Operations

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2546]
Design and apply some metric for measuring computational load of operations.

The deliverables are a reusable framework for accomplishing this task, and that associated data that is collected via utilizing it.

**Comment by mvandeberg** [comment]
Framework exists in this branch. There is still some work needed to get it in a decent mergeable state. The data for the next task has been shared. My recommendation is closing this issue and finishing the reusable framework at a later date.

**Comment by youkaicountry** [comment]
Split reusable framework into #2694.
Data deliverable has been completed.
