### ISSUE TITLE
Stateless plugin API's

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#255]
A design pattern has emerged on plugins:  Many plugins offer stateless API's, i.e. API's which have no per-client state.  In-process clients (i.e. other plugins / API's) should be able to access this stateless API easily without requiring creating an API object and the dynamic memory allocation overhead that entails, both for the API object itself and for the arguments / results of any API calls.

Therefore plugins which offer stateless API's should have a `get_stateless_api()` method which returns a singleton stateless API owned by the plugin object.  API methods should simply call the stateless method without any return values.

I think some plugins written by me (not sure which ones) take the alternative of leaving the methods on the plugin object.

**Comment by mvandeberg** [comment]
This design pattern is no longer needed due to the future deprecation of get_state.
