### ISSUE TITLE
exception in steemit js

### ISSUE THREAD

**Issue by kradster** [steemit/steem#2562]
when i trying to use setSubscriberWithCallback function it wants callback and callfilter function in arguments .
but there is no explanation about these methods 

this is the error

name: 'RPCError',
  code: -32002,
  data:
   { code: 10,
     name: 'assert_exception',
     message: 'Assert Exception',
     stack: [ [Object] ] } } undefined

**Comment by mvandeberg** [comment]
That method has never worked in Steem. It was a carry over from BitShares 2.0 whose functionality was never ported over. I opened an issue in the steem-js repo to remove the method. steemit/steem-js#387
