### ISSUE TITLE
Restore 24 hour payout period 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#257]
The websites can use off-chain algorithm to keep main page fresh.

**Comment by mvandeberg** [comment]
Implemented in commit f27eea7

**Comment by iamsmooth** [comment]
Any consideration to reducing somewhat the degree of time extension? I understand the need to extend payout to allow time for down votes of abusive upvotes but It currently seems quite extreme, which was a large part of the motivation for shortening the starting payout time. Maybe a bit less extension would be sufficient?

**Comment by bytemaster** [comment]
That was accidentally included in HF13.  We can now close this.
