### ISSUE TITLE
Why is BUILD_STEEM_TESTNET=ON in dockerfile?

### ISSUE THREAD

**Issue by lopugit** [steemit/steem#2575]
Does this mean the docker built nodes are using the testnet part of config.hpp?

**Comment by mvandeberg** [comment]
The Dockerfile encapsulates our entire CI process. You'll notice those builds run the tests and then delete that build before building main net versions of Steem which are included in the resulting Docker Image. We will likely be separating our CI process and Docker Image build process soon.
