### ISSUE TITLE
replaying is never end...

### ISSUE THREAD

**Issue by egonson** [steemit/steem#2578]
I ran 'steemd --replay-blockchain' after downloading whole block data 3 weeks ago.
But it is still syncing...

   75.6492%   17500000 of 23133082   (61718M free)
2625389ms th_a       database.cpp:2575             show_free_memory     ] Free memory is now 59G
1989277ms th_a       database.cpp:2575             show_free_memory     ] Free memory is now 58G

And the bigger problem is shared memory file is almost exhausted.

What can I do?

used plugin is
plugin = webserver p2p json_rpc witness account_by_key account_history_rocksdb
plugin = database_api witness_api condenser_api account_by_key_api account_history_api block_api
and shared file size is 200GB
shared-file-size = 200G

yeh, I know that account_history_api lets steemd slow down. But I need it to refer account history.

What should I do now? Please help me. Thank you.

**Comment by moisesmcardona** [comment]
It's because steemd is RAM-hungry. You need more physical RAM. Even using SWAP is slow.

**Comment by egonson** [comment]
Thank you for the answer.
64 GB of memory not enough?
If so, how is much memory needed? Do I need memory as much as shared memory file size?

**Comment by moisesmcardona** [comment]
64gb should work for a Witness node. I don't run a full node so I'm not
really sure on that one.

**Comment by Gandalf-the-Grey** [comment]
First of all, you are not using current `stable` branch.
What would be that node used for?
Do you really need account history for all accounts?
What is your storage backend?
Are you using low memory node?
Depends on other factors and details of configuration, 64GB "might" be enough.

**Comment by egonson** [comment]
I am using stable version
$ git status
On branch stable
Your branch is up-to-date with 'origin/stable'.
nothing to commit, working directory clean
And I think the version is not the problem.

My node is for the exchange wallet.

Is account_history_api is needed even for one or two account history?

The storage is SSD on EC2.

What is low memory node? I am using 64GB.

My configuation is here. What is wrong with this configuration?
=================================================================
# Console appender definition json: {"appender", "stream"}
log-console-appender = {"appender":"stderr","stream":"std_error"}

# File appender definition json:  {"appender", "file"}
log-file-appender = {"appender":"p2p","file":"logs/p2p/p2p.log"}

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"info","appender":"stderr"}
log-logger = {"name":"p2p","level":"info","appender":"stderr"}

# Plugin(s) to enable, may be specified multiple times
plugin = webserver p2p json_rpc witness account_by_key account_history_rocksdb

plugin = database_api witness_api condenser_api account_by_key_api account_history_api block_api

# Defines a range of accounts to track as a json pair ["from","to"] [from,to] Can be specified multiple times
account-history-rocksdb-track-account-range=["mywallet.cold","mywallet.hot"]
# account-history-track-account-range =
webserver-ws-endpoint = 0.0.0.0:8090
webserver-http-endpoint = 0.0.0.0:8090
p2p-endpoint = 0.0.0.0:2001

shared-file-full-threshold = 9500
shared-file-scale-rate = 1000
follow-start-feeds = 1527212690
# --tags-skip-startup-update

# Defines a list of operations which will be explicitly logged.
# account-history-whitelist-ops =

# Defines a list of operations which will be explicitly ignored.
# account-history-blacklist-ops =

# the location of the chain shared memory files (absolute path or relative to application data dir)
# shared-file-dir = "blockchain"

# Size of the shared memory file. Default: 54G
shared-file-size = 200G

# Pairs of [BLOCK_NUM,BLOCK_ID] that should be enforced as checkpoints.
# checkpoint =

# flush shared memory changes to disk every N blocks
flush-state-interval = 0

# Database edits to apply on startup (may specify multiple times)
# edit-script =

# Set the maximum size of cached feed for an account
follow-max-feed-size = 500

# Block time (in epoch seconds) when to start calculating feeds
# follow-start-feeds = 0

# Track market history by grouping orders into buckets of equal size measured in seconds specified as a JSON array of numbers
market-history-bucket-size = [15,60,300,3600,86400]

# How far back in time to track history for each bucket size, measured in the number of buckets (default: 5760)
market-history-buckets-per-size = 5760

# The local IP address and port to listen for incoming connections.
# p2p-endpoint =

# Maxmimum number of incoming connections on P2P endpoint
# p2p-max-connections =

# The IP address and port of a remote peer to sync with. Deprecated in favor of p2p-seed-node.
# seed-node =

# The IP address and port of a remote peer to sync with.
# p2p-seed-node =
p2p-seed-node = 46.252.27.1:1337
p2p-seed-node = 52.62.24.225:2001
p2p-seed-node = 192.99.4.226:2001
p2p-seed-node = 45.55.217.111:2001
p2p-seed-node = 81.89.101.133:2001
p2p-seed-node = 52.4.250.181:39705
p2p-seed-node = 104.199.157.70:2001
p2p-seed-node = 104.236.82.250:2001
p2p-seed-node = 212.47.249.84:40696
p2p-seed-node = 162.213.199.171:34191
p2p-seed-node = steem.kushed.com:2001
p2p-seed-node = steemd.pharesim.me:2001
p2p-seed-node = seed.steemed.net:2001
p2p-seed-node = steem.clawmap.com:2001
p2p-seed-node = seed.steemnodes.com:2001
p2p-seed-node = seed.steemwitness.com:2001
p2p-seed-node = steem-seed1.abit-more.com:2001

# User agent to advertise to peers
p2p-user-agent = Graphene Reference Implementation

# The local IP and port to listen for incoming http connections.
# webserver-http-endpoint =

# The local IP and port to listen for incoming websocket connections.
# webserver-ws-endpoint =

# Number of threads used to handle queries. Default: 32.
webserver-thread-pool-size = 256

# Enable block production, even if the chain is stale.
enable-stale-production = false

# Percent of witnesses (0-99) that must be participating in order to produce blocks
# required-participation =

# name of witness controlled by this node (e.g. initwitness )
# witness =

# WIF PRIVATE KEY to be used by one or more witnesses or miners
# private-key =

**Comment by egonson** [comment]
track-account-range option needed. it solved! Thanks.
