### ISSUE TITLE
Can not remove upvotes from own post.

### ISSUE THREAD

**Issue by Alifton** [steemit/steem#259]
I've now tried several times to remove my own upvote from my own post and here's the error I now get. This issue just started today to the best of my knowledge.  This has happened several times today on several different posts of mine where I forgot to uncheck the auto self-upvote box.

>Transaction failed: abs_rshares > 30000000: voting weight is too small, please accumulate more voting power or steem power

I know this isn't a lack of voting power because I had over 98%+ of my voting power both times I tried to remove my own accidental upvotes.

**Comment by abitmore** [comment]
I don't think above commit fixed the issue. `abs_rshares` is not `1` in most cases when `voting_weight` is `0`. Why not just check if `o.weight == 0`?

**Comment by mvandeberg** [comment]
Just a couple lines previous...

``` c++
if( abs_rshares == 0 ) abs_rshares = 1;
```

It is there to prevent a divide by zero other places. Decided it was best to have the assert only deal with abs_rshares rather than add in another variable.

**Comment by abitmore** [comment]
@mvandeberg you didn't get it.

When unvoting, `abs_weight == 0`, 
thus `used_power = (current_power * abs_weight / STEEMIT_100_PERCENT) / 200 + 1 = 1`, 
thus `abs_rshares    = voter.vesting_shares.amount.value * used_power / STEEMIT_100_PERCENT` should > `1` when `vesting_shares.amount` is more than `2 * STEEMIT_100_PERCENT` aka `20,000`, which is true in most cases.

**Comment by abitmore** [comment]
#132 is related

**Comment by arhag** [comment]
Here is my suggestion for how to fix this problem:

Replace [this line](https://github.com/steemit/steem/blob/6958b0c6cce693684a24a7594b0b056f9dbcd234/libraries/chain/steem_evaluator.cpp#L882) with: 
```
used_power = (used_power/200);
if( !db().has_hardfork( STEEMIT_HARDFORK_0_13__259 ) )
   used_power += 1;
```

Replace [this line](https://github.com/steemit/steem/blob/6958b0c6cce693684a24a7594b0b056f9dbcd234/libraries/chain/steem_evaluator.cpp#L886) with:
```
if( !db().has_hardfork( STEEMIT_HARDFORK_0_13__259 ) && abs_rshares == 0 ) abs_rshares = 1;
```

Replace [this line](https://github.com/steemit/steem/blob/6958b0c6cce693684a24a7594b0b056f9dbcd234/libraries/chain/steem_evaluator.cpp#L889) with:
```
FC_ASSERT( abs_rshares > 50000000 || o.weight == 0, "voting weight is too small, please accumulate more voting power or steem power" );
```

And replace [this line](https://github.com/steemit/steem/blob/6958b0c6cce693684a24a7594b0b056f9dbcd234/libraries/chain/steem_evaluator.cpp#L1096) with:
```
auto avg_cashout_sec;
if( db().has_hardfork( STEEMIT_HARDFORK_0_13__259 ) && abs_rshares == 0 )
   avg_cashout_sec = cur_cashout_time_sec;
else
   avg_cashout_sec = (cur_cashout_time_sec * old_root_abs_rshares + new_cashout_time_sec * abs_rshares ) / ( old_root_abs_rshares + abs_rshares );
```

And of course you would define `STEEMIT_HARDFORK_0_13__259` to be `STEEMIT_HARDFORK_0_13` in `0_13.hf`.

I hope these changes (or something like it) is included into hardfork 13, so that users can unvote without having to wait until hardfork 14.

**Comment by Alifton** [comment]
@arhag 

That would work and would fix the concerns about possible divide by zero problems though they would likely never arise. Regardless it never hurts to play it safe and a push to hf 13 would be much appreciated because it's a simple bug fix that could easily be remedied before the hf 13 rollout in a couple days.

**Comment by abitmore** [comment]
Pull request submitted (#270), please review.

**Comment by abitmore** [comment]
OK, now hard fork 13 is in effect. My patch can't be merged as is. It's up to the devs to decide how to deal with this issue.

**Comment by mvandeberg** [comment]
I'll update the merge to work with the next hardfork

**Comment by theoreticalbts** [comment]
The first change suggested by @arhag -- effectively replacing `used_power = (used_power/200)+1` with `used_power = used_power/200` -- will keep an account from ever being able to drain its voting power to zero; effectively once your voting power is 199, you can no longer vote.  The reason for the +1 was to allow voting power to be drained to zero.

- (a) The thing we need to do to prevent the problem in this ticket is to make sure that the result of this operation is zero when the input is zero.
- (b) The thing we need to do to prevent the problem of being unable to vote despite having nonzero voting power is to make sure that the result of this operation is nonzero when the input is nonzero.

The existing code satisfies (b) but not (a); @arhag's solution satisfies (a) but not (b); I propose to divide and round up, which satisfies both (a) and (b).

    used_power = (used_power+199) / 200

**Comment by abitmore** [comment]
@theoreticalbts please check #132 as well.

**Comment by theoreticalbts** [comment]
Thanks, I think that ticket can be closed as well.

**Comment by abitmore** [comment]
[This line of code change](https://github.com/steemit/steem/commit/21410e9481901030a9ebb94f63801b741b3dc013#diff-04f6af9cdbf180a31ccdbf6335b8f240R1001) brought forks.

**Comment by abitmore** [comment]
Proposed fix in this commit: https://github.com/steemit/steem/commit/e6f860847de82ff70b96cefacfe2712198076a5c, please review.
