### ISSUE TITLE
I Voted 5 Posts Which Became Popular But Not Getting Curation Reward - ZERO CURATION - Help Required!

### ISSUE THREAD

**Issue by steemist** [steemit/steem#260]
Hello, I posted my thread on steemit too about it, My username is : @steemist

These are 5 top posts which I voted but didn't receive ANY reward:

https://steemit.com/elonmusk/@xtester/i-am-quitting-medium-or-elon-musk-self-driving-cars-will-be-here-in-2-years

I voted before the whales and that post made around $500 but where is my curation reward? Not even 0.001 SP????

https://steemit.com/steemit/@decha/steam-white-paper-translated-version-in-thailand-thai

I was the 4th person to vote for that thai translated version which made over $100 but no curation reward.

https://steemit.com/steemit/@knozaki2015/steemit-just-refreshed-with-a-new-design-and-addet-some-great-features

I voted before ANY whale and no curation reward. I was the 8th person to vote for it.

https://steemit.com/photography/@manthostsakirid/welcome-to-my-new-style

Same is the case here. I voted before whales and the post made $400+ but I didn't receive even a little piece of curation reward.

https://steemit.com/life/@dragonslayer109/the-real-rewards-of-steemit-my-journey-from-despair-to-a-bright-future-featuring-new-author-sauravrungta

This post was a hit, but didn't gave even a dust to me. I voted before any big whale.

And the proof of zero curation reward: 

https://img1.steemit.com/0x0/https://s10.postimg.org/6hauspo9l/curation.png

I am sure that this is a bug because it is strange to have ZERO People are receiving even little reward of 0.001 SP but I didn't even receive that. Please solve this issue.

**Comment by abitmore** [comment]
Already lots of explanation in your post. https://steemit.com/steem-help/@steemist/voted-for-successful-posts-before-whales-but-zero-curation-reward-help-steemit-com-and-steem-help

**Comment by steemist** [comment]
I calculated with the given formula of @venuspcs and it seems like the only issue is my low SP. Thank you
