### ISSUE TITLE
[BUG] Steem deletes the data directory and replaces it with a log file if you don't specify a file to the file logger

### ISSUE THREAD

**Issue by Someguy123** [steemit/steem#2612]
I was playing the logging options, trying to get it to log to stdout like 0.19.5 - ~~turns out if you set p2p to go to std_out (I mean safe assumption considering error is std_error right?)~~ EDIT: if you don't specify a file to the file logger, it will nuke your witness_node_data_dir

by turning it into a log file...

```
-rw-r--r-- 2 root root  57624 Jul 10 23:20 witness_node_data_dir
-rw-r--r-- 2 root root  57624 Jul 10 23:20 witness_node_data_dir.20180710T210000
```

Notice the timestamped one - that's a log file
just like the p2p log

```
./data/witness_node_data_dir/logs/p2p/p2p.log
./data/witness_node_data_dir/logs/p2p/p2p.log.20180710T210000
```

To replicate this, simply put this as your logging config and restart:

```
# Console appender definition json: {"appender", "stream"}
log-console-appender = {"appender":"stderr","stream":"std_error"}

# File appender definition json:  {"appender", "file"}
log-file-appender = {"appender":"p2p", "stream":"std_out"}

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"debug","appender":"stderr"}
log-logger = {"name":"p2p","level":"info","appender":"p2p"}
```

And voila, your data directory has been deleted and replaced with the p2p log  🤦‍♂️

**Comment by Someguy123** [comment]
Turns out I didn't notice the fact there was a `log-file-appender` and a `log-console-appender`.

Either way this is pretty bad behaviour - it shouldn't obliterate your data directory if you don't specify a file...

**Comment by Jolly-Pirate** [comment]
My understanding is, the `log-file-appender` is meant to be a file, not `std_out`

**Comment by mvandeberg** [comment]
It should write the logs to `$DATA_DIR/std_out`. I think there is something else going on here. It does not add up...

**Comment by Someguy123** [comment]
@mvandeberg note this was done using my steem-docker. not sure if there's anything wrong here with data-dir (maybe it's upset from no ending slash?):

```        docker run $DPORTS -v /dev/shm:/shm -v "$DATADIR":/steem -d --name $DOCKER_NAME -t steem steemd --data-dir=/steem/witness_node_data_dir```
