### ISSUE TITLE
Intel Compiler not working

### ISSUE THREAD

**Issue by vonkoda** [steemit/steem#262]
Using Parallel Studio XE 16 (ICC v16.03) on Ubuntu 16.10. Compiles fine on gcc, but errors out around 44% on icc.  
Tried upto Steem v0.12.3.
I need Intel Compiler working as I want to try Steem mining on Intel Xeon Phi cards soon (which I think everyone agrees would be a cool experiment ;). 

See attached a dump of the errors. They seem to be around api_connection.hpp and/or the Test dir.

[icc build errors steem.txt](https://github.com/steemit/steem/files/412537/icc.build.errors.steem.txt)

**Comment by theoreticalbts** [comment]
Maybe fixed by 894d784523a7c7312dfd04f381c792378836e132

**Comment by vonkoda** [comment]
How can I get this update to test it out?

**Comment by theoreticalbts** [comment]
I just bumped the fc submodule, so just compiling the develop branch should work:

    git checkout origin/develop -b develop
    git submodule update --init --recursive
    make steemd

If `cd libraries/fc ; git log -2` shows `894d784523a7c7312dfd04f381c792378836e132` then you've got the change.

**Comment by vonkoda** [comment]
Just to update, tested this and yes, it now compiles and is working! Good work, thx! Can we get this in the official release?

**Comment by mvandeberg** [comment]
All of develop will go into the next release. For now, you can build on develop. We try to keep develop compatible with the main chain.

**Comment by theoreticalbts** [comment]
Since it works I'm going to close this.
