### ISSUE TITLE
rc_plugin debug checks should not be triggered by unit tests

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2627]
In order to merge `rc_plugin` to `develop`, it needs to pass all unit tests.  Currently there is only one failing test that still needs resolved:  The `clear_null_account` test checks that `VESTS` belonging to the null account are cleared, which changes its vesting balance but does not generate a virtual op.

The fix is to simply add a virtual op for the per-block processing that clears null account balances.

**Comment by mvandeberg** [comment]
Why? It can't transact. I would simply ignore the debug check if anything happens to the null account.
