### ISSUE TITLE
In-database versioning overhaul

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#264]
We need to have the object_database store its serialization of each type it contains, and force re-index when this serialization changes.

Basically we'd use fc to auto-generate the serialization description object.  When saved, the description can be a JSON-ball that can be a building block for out-of-process introspection -- it may be useful to extend this to API introspection as well.

**Comment by mvandeberg** [comment]
I believe this was implemented as the schema library which has been broken since we switched to the shared memory file and needs to be updated for chainbase.

**Comment by theoreticalbts** [comment]
Yeah, this is essentially the schema library.  Closing as this is superseded by #683 #854 #285.
