### ISSUE TITLE
Installation failed on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by arghyakusumdas7** [steemit/steem#2643]
The error message is as follows:

$ make -j$(nproc) steemd
....
In file included from /usr/include/boost/config.hpp:61:0,
                 from /usr/include/boost/lexical_cast.hpp:21,
                 from /home/arghyakusum/Steem/steem/libraries/fc/include/fc/reflect/reflect.hpp:10,
                 from /home/arghyakusum/Steem/steem/libraries/fc/include/fc/time.hpp:138,
                 from /home/arghyakusum/Steem/steem/libraries/fc/include/fc/log/logger.hpp:3,
                 from /home/arghyakusum/Steem/steem/libraries/fc/include/fc/exception/exception.hpp:6,
                 from /home/arghyakusum/Steem/steem/libraries/fc/include/fc/uint128.hpp:6,
                 from /home/arghyakusum/Steem/steem/libraries/fc/src/uint128.cpp:1:
/usr/include/boost/multiprecision/cpp_int.hpp:181:4: error: right operand of shift expression ‘(1 << 63)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:404:4: error: right operand of shift expression ‘(1 << 63)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:556:4: error: right operand of shift expression ‘(1 << 63)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
libraries/fc/CMakeFiles/fc.dir/build.make:62: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o' failed
make[3]: *** [libraries/fc/CMakeFiles/fc.dir/src/uint128.cpp.o] Error 1
CMakeFiles/Makefile2:162: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
CMakeFiles/Makefile2:2682: recipe for target 'programs/steemd/CMakeFiles/steemd.dir/rule' failed
make[1]: *** [programs/steemd/CMakeFiles/steemd.dir/rule] Error 2
Makefile:721: recipe for target 'steemd' failed
make: *** [steemd] Error 2

**Comment by TimCliff** [comment]
What branch are you building?
Did you install all of the dependencies?
What commands have you run up to this point?

**Comment by Gandalf-the-Grey** [comment]
Please make sure that you have "clean" Ubuntu 16.04, i.e. without extra repositories added or custom packages installed.

**Comment by theoreticalbts** [comment]
This is a Boost issue with recent compilers.  The older version of Boost we use does not compile in GCC 6, see [here](https://svn.boost.org/trac10/ticket/12181) for the Boost bug report.

The immediate solution to your problem is to use GCC 5.x.

Unfortunately, the FC multithreading system used by the p2p networking code [is not compatible](https://github.com/steemit/steem/issues/503) with recent versions of Boost, so I'm not sure if Steem will switch to a newer Boost version anytime soon.

**Comment by arghyakusumdas7** [comment]
I tried in another fresh installation of Ubuntu 16.04 (VMWare) in my laptop. This issue was resolved. But the compilation process was killed after some time.  

However, in another machine with 32GB RAM and 10cores I installed it without any problem. Is it a memory issue?

**Comment by Gandalf-the-Grey** [comment]
> But the compilation process was killed after some time.

most likely because too much cores vs available RAM
