### ISSUE TITLE
mem leak

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#265]
on the latest build my mem usage just keeps growing until the system can not allocate anymore (15.5 gb)

**Comment by ByronAP** [comment]
problem may lie in the tags api, I keep seeing Couldn't create API tags_api

**Comment by ByronAP** [comment]
but that can't be it since it happens even when doing a rescan

**Comment by ByronAP** [comment]
etail_string(): 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
3370565ms th_a       database_api.cpp:185          ~database_api_impl   ] freeing database api 7778233760
3370565ms th_a       websocket_api.cpp:88          on_message           ] message:
3370565ms th_a       websocket_api.cpp:132         on_message           ] e.to_detail_string(): 11 eof_exception: End Of File
stringstream
    {}
    th_a  sstream.cpp:109 peek

    {"str":""}
    th_a  json.cpp:478 from_string
3370565ms th_a       database_api.cpp:185          ~database_api_impl   ] freeing database api 7778243568

**Comment by abitmore** [comment]
Why closed? No mem leak actually, or how to fix?

**Comment by ByronAP** [comment]
It is not a mem leak as far as I can tell. It is just that full nodes use something like 8gb of ram... Crazy Amount...

**Comment by mvandeberg** [comment]
I am running a full node with *only* 6.66 GB memory used.

What system are you running on and which versions of your dependencies?

**Comment by ByronAP** [comment]
ubuntu 14, with boost 1.60.0

**Comment by ByronAP** [comment]
http://imgur.com/a/g1uf1

**Comment by abitmore** [comment]
There was definitely some kind of mem leak in the node. But I'm not sure if it's same thing described in OP.
I'm running low-mem nodes, after some days, they use about 4GB VIRT and 3GB RES.
* if restart without `--replay`, same usage
* if restart with `--replay`, will drop to around 1GB, then increase slowly.

**Comment by tchap** [comment]
I am running on 8 GB and I cannot even do `--replay-blockchain` any more :-/ Really wondering why `steemd` is consuming such an insane amount of memory...

**Comment by abitmore** [comment]
Got some time to analyse the memory leak issue.

This file is keep growing: `object_database/2/4`, which turns out to be `impl_transaction_object_type` objects, looks like `clear_expired_transactions()` is not working correctly.

Pull request submitted #372

**Comment by sneak** [comment]
fixed in #372 (merged)
