### ISSUE TITLE
Implement field for fee discount

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2651]
In addition to the `fee` field, there should be a fee paid, and a fee discount.

- [ ] Remove partial subsidization

**Comment by mvandeberg** [comment]
There should be an additional field in the `claim_account_operation` called `requested_discount` (name?) that must satisfy the requirement `account_creation_fee = paid_fee + requested_disctount`. This needs to be enforced via stateful verification and requires a unit test.

**Comment by theoreticalbts** [comment]
This code attempts to fix the following bugs:

- If the max account creation fee is too big, overflow might happen.  To prevent this, clamp to `STEEM_MAX_ACCOUNT_CREATION_FEE`.
- We probably want to forbid requesting such truly enormous fees, so enforce this bound in witness update / set property ops after HF20 or if `is_producing()`.
- Add a `static_assert()` documenting / enforcing that numerical overflow is impossible.
- Rename `percent_unpaid` -> `current_subsidy`, change to signed, scale it by `STEEM_ACCOUNT_SUBSIDY_PRECISION` instead of `STEEM_100_PERCENT`
- `recovered_subsidies` suffers possible numerical overflow as everything is 32-bit.
- `recovered_subsidies` has `STEEM_100_PERCENT` in both numerator and denominator which does nothing.
- Refactor `new_subsidies` computation to a branchless one-liner
- When a witness includes a partial subsidy, only apply a partial subsidy to its `recent_account_subsidies`.
- Cast terms of `single_witness_subsidy_limit` to `uint64_t` to prevent possible overflow.

**Comment by mvandeberg** [comment]
This is containing bug fixes only.
