### ISSUE TITLE
Different operation ids when calling 'get_account_history'

### ISSUE THREAD

**Issue by steemchiller** [steemit/steem#2666]
I'm not sure if it is related to the switch to RocksDB but I've never noticed this before. When I load the last operations for my account via 'get_account_history', I don't get the same op ids from the Steemit node (api.steemit.com) than from other public nodes. The other nodes which I've tested return an id that is smaller by 7.

**Example:**
Account 'steemchiller' received a vote from account 'rawutah'

Node | Op Id
------------ | -------------
api.steemit.com | 35802
Other Nodes | 35795

Since I'm using the id to check for new operations it can lead to double items when switching between nodes. I could add a second check on the op time to fix it temporarily but I'm not sure if I really want this.

Is it just a temporary issue or do I need to change my code for supporting different results from the nodes in future? Is the id a unique number and should it be the same for all nodes or is it related to the active plugins of the connected node and can vary?

Thanks in advance!

**Comment by mvandeberg** [comment]
The IDs are not canonical and are not guaranteed to be identical from node to node for a couple of reasons:

1. Every once and a while we add or change a virtual operation to better represent an account's history. When we reindex, these operations are changed historically and can result in different IDs. Some accounts may have the same IDs and some are different, so do not assume one account that looks right means the nodes have identical IDs.

2. Nodes can filter ops. Missing ops won't have IDs associated with them and will change the IDs for all other ops.

We try not to change this too often, but it does happen and can result in discrepancies such as this. If you are trying to digest account history, I recommend remembering where you left off by some other variable (block num or trx id) that does not change from node to node.

**Comment by mvandeberg** [comment]
The operation objects have a set of fields specifically for this.

The tuple `(block, trx_in_block, op_in_trx, virtual_op)` sorted in ascending order represents the order in which the operations where applied. Virtual ops have `trx_in_block` set to -1 or 2^32-1.

**Comment by steemchiller** [comment]
Thanks for the detailed explanation! Now it all makes sense to me. I don't even need to change much in my existing logic. When I use the tuple instead of the id directly, it will work for all nodes.
