### ISSUE TITLE
0.19.10 extremely slow to start

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/steem#2667]
I am testing 0.19.10 on a full node and startup is extremely slow.  It sits at this point for a good 30 minutes before it moves on and actually starts looking at blocks and catching up

`1008836ms tags_plugin.cpp:516           operator()           ] Updating all tag stats on startup`

**Comment by mvandeberg** [comment]
Set `tags-skip-startup-update=true` in your config file. This allows the tags plugin to get reindexed faster but is not needed on subsequent startups. We assume full nodes are started and stopped sparingly, so the default is set to false. Setting to false saves much more than 30 minutes during reindex.
