### ISSUE TITLE
Properly count number of accounts for claimed accounts

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2700]
The new `claim_account_operation` / `create_claimed_account_operation` are not currently counted as creating accounts in `resource_count.cpp`.  We need to:

- Figure out which of these ops should be considered as claiming an account for purposes of RC
- Increment `new_account_op_count` in the relevant visitor method in `count_operation_visitor`

**Comment by mvandeberg** [comment]
When an account is claimed, it decrements to count in the gpo. The same semantics should be used in the rc plugin.

**Comment by theoreticalbts** [comment]
I was going to work on this, but in the interest of avoiding merge conflicts, let's wait until PR #2687, PR #2702 and the branch for #2547 are merged.
