### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by gamerate** [steemit/steem#271]
While compiling 0.13.0-rc3 on Ubuntu 16.04 LTS I got following error:

> [ 61%] Building CXX object libraries/chain/CMakeFiles/steemit_chain.dir/protocol/steem_operations.cpp.o
> /home/dr2073/s13/steem/libraries/chain/protocol/steem_operations.cpp: In member function ?void steemit::chain::pow2::create(const block_id_type&, const string&, uint64_t)?:
> /home/dr2073/s13/steem/libraries/chain/protocol/steem_operations.cpp:217:26: error: ?class fc::sha256? has no member named ?approx_log_32?
>        pow_summary = work.approx_log_32();
>                           ^
> libraries/chain/CMakeFiles/steemit_chain.dir/build.make:230: recipe for target 'libraries/chain/CMakeFiles/steemit_chain.dir/protocol/steem_operations.cpp.o' failed
> make[2]: *** [libraries/chain/CMakeFiles/steemit_chain.dir/protocol/steem_operations.cpp.o] Error 1
> CMakeFiles/Makefile2:985: recipe for target 'libraries/chain/CMakeFiles/steemit_chain.dir/all' failed
> make[1]: *** [libraries/chain/CMakeFiles/steemit_chain.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

What I doing wrong and how to fix this? (same effect on 3 different systems)

**Comment by clayop** [comment]
Checkout tag first then submodule update.

**Comment by TigerND** [comment]
You can inspect these Dockerfiles to find out how to compile Steem on Ubuntu:

https://steemit.com/steem/@teego/steem-docker-images-roadmap

Also, there are some Dockerfiles for MinGW cross compilation:

https://hub.docker.com/r/teego/mingw-steem/~/dockerfile/
https://hub.docker.com/r/teego/mingw-boost/~/dockerfile/
https://hub.docker.com/r/teego/mingw-openssl/~/dockerfile/

Compilation passes. However, `steemd` crashes on NTP synchronisation.

**Comment by gamerate** [comment]
Thanks - submodule update it's step I forgot to do - it's was a problem.
Now all works fine =)
