### ISSUE TITLE
Event Driven Automated Action Push

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2718]
Automated actions should be pushed to the schedule queue in an event driven manner.

**Comment by mvandeberg** [comment]
The database has a simple interface, `push_required_action` and `push_optional_action` that creates and schedules the correct action. This interface is safe to call from within an automated action, creating an "event driven push". Some actions will still need to be scheduled from some per-block-processing.

Optional actions can impact consensus, but are not required. They should be generated via plugins. The database allows registering a generate optional actions handler. The handler will only be called when it is time to generate optional events, which should then be pushed by the plugin to the database. Optional actions can create optional actions.

**Comment by mvandeberg** [comment]
After a discussion and clarification, the following additions will be made to the existing AA framework for this issue.

Required actions can be scheduled in advance to be executed at a particular time. This needs to addition of this field and will modify the consensus logic for verification of actions slightly.

The same type of scheduling should be supported for optional actions as well. Additionally, optional actions will have an implicit expiration of one round (63) seconds past their inclusion time. This gives all witnesses one shot at including an optional action.
