### ISSUE TITLE
Event Driven Automated Action RC scheduling

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2719]
Event Driven Automated Action RC scheduling

**Comment by mvandeberg** [comment]
Scheduling of actions is quite easy. The structure of the block is as follows:

Up to 75% transactions
Required Actions (up to block size)
Optional Actions (up to block size)

Required actions can only be delayed if the inclusion of the next required action would cause the block to grow beyond the block size.

The order of required actions is pre-determined consensus state to make verification of actions easier. This significantly simplifies the scheduling of actions.

**Comment by mvandeberg** [comment]
Re-reading my comment, I think it should have been in a different issue. Maybe #2722

The AC of this issue is adding the plumbing in the rc plugin so that optional automated actions are correctly account for in resource costs and can be rejected for insufficient RCs.
