### ISSUE TITLE
DON'T REMOVE Curation Rewards! Just  stop them when the post reach the trending page !!!

### ISSUE THREAD

**Issue by liondani** [steemit/steem#272]
As we discussed many times it seems curation rewards don't work as intended !
I think the most problems regarding curation rewards  would get auto solved if the system would use a treshold to stop them !

This treshold should be the success of the post to be included on the trending page (for example 20 top posts) When it gets to TOP 20 ... STOP the curation rewards!!!  

Just let the people know after the curation reward get "deactivated" when they try to upvote...

the community has already a positive reaction to this idea!
check and participate to the brainstorming with the steemit community on this link...
https://steemit.com/steemit-ideas/@liondani/don-t-remove-curation-rewards-just-stop-them-when-the-post-reach-the-trending-page

here from my conversation with @iamsmooth ....
![screenshot from 2016-08-15 14 01 26](https://cloud.githubusercontent.com/assets/6908400/17662804/f892deb4-62f0-11e6-9f58-2287de48a0bd.png)

**Comment by mvandeberg** [comment]
The context of this discussion is no longer relevant. Closing this issue to prefer newer tickets for discussing curation rewards.
