### ISSUE TITLE
(API Question) get users post history

### ISSUE THREAD

**Issue by ByronAP** [steemit/steem#273]
what is the best way to get a users post history from the api?

**Comment by theoreticalbts** [comment]
`get_account_history`, then filter by posts.

**Comment by ByronAP** [comment]
thank you, could you explain what the "from" field actually is? It doesn't seem to relate to block numbers or anything that I can see

**Comment by abitmore** [comment]
@ByronAP:
```
locked >>> gethelp get_account_history
gethelp get_account_history

Account operations have sequence numbers from 0 to N where N is the most
recent operation. This method returns operations in the range [from-limit,
from]

Parameters:
    account: - account whose history will be returned (type: string)
    from: - the absolute sequence number, -1 means most recent, limit is
        the number of operations before from. (type: uint32_t)
    limit: - the maximum number of items that can be queried (0 to 1000],
        must be less than from (type: uint32_t)
```

For example,
* `get_account_history your_account -1 10` will return the latest 10 records, 
* `get_account_history 100 10` will return the No.91 - No.100 records.

`gethelp` command in CLI is your friend, you need to build with `doxygen` installed (`apt-get install doxygen`)
