### ISSUE TITLE
ICO Contributor Payout

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2732]
As a contributor to an ICO, I want to receive my SMT.

```c++
struct smt_contributor_payout_action
{
   account_name_type contributor;
   uint32_t          contribution_id;
   asset             payout;
};
```

**AC:**
1. At the SMT launch time, if all caps are revealed, trigger cascading `smt_contributor_payout_action`s.
2. If the SMT launch time is passed and caps are revealed, trigger cascading `smt_contributor_payout_action`s.

In whitepaper see sections `Token units` and `Unit Ratios`

**Comment by dynamicrypto** [comment]
When you stake a token should it not take a while to extract all tokens slowing down any possible day trading and dumps affecting the price negatively.  To trade it you keep it on an exchange, to keep it on the platform earning income you wait a little while.
