### ISSUE TITLE
Define Structure of SMT DNS TXT Record

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2741]
Define the txt record structure for the NAI - symbol mapping DNS.

**Comment by Smittyvb** [comment]
I can't find any mention of DNS in [the SMT whitepaper](https://smt.steem.io/smt-whitepaper.pdf). What is this? Would this allow domains names to be used as asset identifiers, and DNS to be used as the non-consensus asset directory?

**Comment by mvandeberg** [comment]
SMTs will specify a non-consensus desired ticker symbol. Replaced by #3586
