### ISSUE TITLE
SMT DNS Documentation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2744]
Create documentation describing the SMT DNS.

**Comment by Smittyvb** [comment]
Posting the here since this seems to be the main issue for this:
I can't find any mention of DNS in [the SMT whitepaper](https://smt.steem.io/smt-whitepaper.pdf). What is this? Would this allow domains names to be used as asset identifiers, and DNS to be used as the non-consensus asset directory?

**Comment by mvandeberg** [comment]
We have not yet documented this, which is why this issue is to create the documentation for it. All your questions will be answered in the documentation.

**Comment by mvandeberg** [comment]
SMTs will specify a non-consensus desired ticker symbol. Replaced by #3586
