### ISSUE TITLE
As a content creator, I want to be able to specify which token(s) in which rewards are to be paid.

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2747]
As part of comment options, authors can specify up to three (consider less) SMTs that are valid votable assets on the content.

Comments on posts inherit the votable assets of the root post.

Entails:
votable_assets
SMT and comment options
Decline payouts
active_phase

**Comment by mvandeberg** [comment]
Some work was already done on this. Old work needs to be evaluated for bit-rot. Update and complete as needed. Tests need to be checked and updated as well.

Related issues: #1855 #1843
