### ISSUE TITLE
As a token holder, I want to be able to vote using voting power attached to my vested tokens.

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2748]
Implement new vote operation that allows voting with different SMTs and with different amounts of mana.

```
struct vote_operation2 : public base_operation
{
   account_name_type    voter;
   account_name_type    author;
   string               permlink;
   flat_map< asset_symbol_type, int64_t > asset_mana;

   extensions_type      extensions;
};
```

This operation allows users to vote on content with different amounts of mana for each SMT in the comment's votable assets.

**Comment by roadscape** [comment]
Will this still enforce a limit of 5% of remaining mana?

**Comment by mvandeberg** [comment]
That can be open for discussion. We have entertained the idea of "super votes" for a while. This change does not require we implement them, but it is a prerequisite for that work.
