### ISSUE TITLE
new API request: transfer_votepower

### ISSUE THREAD

**Issue by jl777** [steemit/steem#276]
https://steemit.com/steemit/@jl777/transfervotepower-solution-to-whale-voting-power-concentration

a time limited transfer of voting power in 1% increments

**Comment by mvandeberg** [comment]
We are discussing solutions to the whale voting problems internally. In the meantime, this is not a simple API addition, but an entirely new operation requiring a hardfork. For now, I am marking this as will not fix and closing the issue. When we have more to say on our plans to address whale voting, there will be a ticket a steemit blog post shortly thereafter.
