### ISSUE TITLE
Buggy logging. Unexpected char '108' in "log-appender"

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#2777]
When starting steemd v0.19.11, this error is reported, with or without logging in the config.ini.

`1953549ms main.cpp:115                  main                 ] Error parsing logging config. Parse Error:Unexpected char '108' in "log-appender"`

- steemd file logging isn't working (it worked in 0.19.10).
- cli_wallet says `Logging RPC to file: logs/rpc/rpc.log` but nothing is happening there.
- logging level not obeyed, debug/warn/info all show the same things.

**Comment by emre** [comment]
+1 on the issue. Running v0.19.11 from the tag.

**Comment by liuzhixiang** [comment]
+1 on the issue. Running v0.19.11 from the tag.


=====================
------------------------------------------------------
            STARTING STEEM NETWORK
------------------------------------------------------
initminer public key: STMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.19.11
------------------------------------------------------
3086095ms main.cpp:115                  main                 ] Error parsing logging config. Parse Error:Unexpected char '108' in "log-appender"
3086095ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
3086095ms webserver_plugin.cpp:361      plugin_startup       ] Waiting for chain plugin to start
3086095ms chain_plugin.cpp:394          plugin_startup       ] Starting chain with shared_file_size: 22548578304 bytes
3086095ms chain_plugin.cpp:501          plugin_startup       ] Opening shared memory from /var/lib/steemd/blockchain
3086095ms block_log.cpp:142             open                 ] Log is nonempty
3086096ms block_log.cpp:151             open                 ] Index is nonempty
3087294ms webserver_plugin.cpp:310      plugin_initialize    ] configured with 256 thread pool size
3087300ms webserver_plugin.cpp:319      plugin_initialize    ] configured http to listen on 0.0.0.0:8090
3087300ms webserver_plugin.cpp:328      plugin_initialize    ] configured ws to listen on 0.0.0.0:8090
3087396ms p2p_plugin.cpp:614            plugin_initialize    ] caught exception 0 exception: unspecified


=====================

**Comment by mvandeberg** [comment]
What does your config file look like?

**Comment by Jolly-Pirate** [comment]
config.ini example
```
# Console appender definition json: {"appender", "stream"}
log-console-appender = {"appender":"stderr","stream":"std_error"}

# File appender definition json:  {"appender", "file"}
log-file-appender = {"appender":"p2p","file":"logs/p2p/p2p.log"}

# Logger definition json: {"name", "level", "appender"}
log-logger = {"name":"default","level":"info","appender":"stderr"}
log-logger = {"name":"p2p","level":"info","appender":"stderr"}
```

**Comment by Crypto2** [comment]
Same here. The error also appears if I comment out all the logger related lines with a #
