### ISSUE TITLE
Strange behavior when switching witness signing key

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#28]
I performed a witness server switch by swapping out the signing key.

The destination node had an unexpected hiccup, causing my missed blocks to go from 0.. to 1.
Without any intervention on my part, the issue resolved itself in time for the next block. 

Is this a bug, and if not, how can I avoid it in the future?

Destination server:

    641998ms th_a       witness.cpp:268               block_production_loo ] Not producing block for ${w} because I don't have the private key for STM6xg5F26etrTCmKVESbEoXJGy28VkUsxxjUBWjJtcSBmpS89bhW
    645118ms th_a       application.cpp:437           handle_block         ] Got 1 transactions from network on block 921774
    669060ms th_a       application.cpp:437           handle_block         ] Got 1 transactions from network on block 921782
    683999ms th_a       database.cpp:1767             _apply_block         ] 10 assert_exception: Assert Exception
    next_block.validate_signee( witness.signing_key ):
        {}
        th_a  database.cpp:1920 validate_block_header
    683999ms th_a       database.cpp:557              _push_block          ] Failed to push new block:
    10 assert_exception: Assert Exception
    next_block.validate_signee( witness.signing_key ):
        {}
        th_a  database.cpp:1920 validate_block_header
    rethrow
        {}
        th_a  database.cpp:1767 _apply_block
    684000ms th_a       witness.cpp:373               maybe_produce_block  ] 10 assert_exception: Assert Exception
    next_block.validate_signee( witness.signing_key ):
        {}
        th_a  database.cpp:1920 validate_block_header
    rethrow
        {}
        th_a  database.cpp:1767 _apply_block

        {"new_block":{"previous":"000e10ba81d6228933b40b7f8bdd9df61ffd83e2","timestamp":"2016-04-26T07:11:24","witness":"roadscape","transaction_merkle_root":"ca857bbe721d731efc137d348eb91df840e92234","extensions":[],"witness_signature":"1f1d809fe5ab75fed1a9815f55d6cea3a73232183447fdbf035fff20f07fe9223c5bd05dbd504531f2d8db6e92f516f598c4169bc2a1e5634b276cd04b72a946f5","transactions":[{"ref_block_num":4282,"ref_block_prefix":2300761729,"expiration":"2016-04-26T07:11:51","operations":[["witness_update",{"owner":"roadscape","url":"https://steemd.com/@roadscape/witness-roadscape","block_signing_key":"STM5P5sgVcp8z3hYXVHsTZnZVLtyp8Hsrjsotan8XLsheVMicxMhS","props":{"account_creation_fee":"10.000 STEEM","maximum_block_size":131072,"sbd_interest_rate":1000},"fee":"0.000 STEEM"}]],"extensions":[],"signatures":["202c1e589141fa19dc99ef66a1b29c4e0c27bb667beea62be599f87a095ec1091b39375c290f6f365d52b76388849da03f55b62dff4c8ec1fb725d25564fa09c14"]}]}}
        th_a  database.cpp:563 _push_block

        {"witness_owner":"roadscape"}
        th_a  database.cpp:729 _generate_block
    684000ms th_a       witness.cpp:374               maybe_produce_block  ] Clearing pending transactions and attempting again
    684000ms th_a       witness.cpp:373               maybe_produce_block  ] 10 assert_exception: Assert Exception
    witness_obj.signing_key == block_signing_private_key.get_public_key():
        {}
        th_a  database.cpp:642 _generate_block

        {"witness_owner":"roadscape"}
        th_a  database.cpp:729 _generate_block
    684000ms th_a       witness.cpp:374               maybe_produce_block  ] Clearing pending transactions and attempting again
    684000ms th_a       witness.cpp:280               block_production_loo ] Failure when producing block with no transactions
    684998ms th_a       witness.cpp:268               block_production_loo ] Not producing block for ${w} because I don't have the private key for STM6xg5F26etrTCmKVESbEoXJGy28VkUsxxjUBWjJtcSBmpS89bhW
    685998ms th_a       witness.cpp:268               block_production_loo ] Not producing block for ${w} because I don't have the private key for STM6xg5F26etrTCmKVESbEoXJGy28VkUsxxjUBWjJtcSBmpS89bhW
    687180ms th_a       application.cpp:437           handle_block         ] Got 1 transactions from network on block 921787
    690200ms th_a       application.cpp:437           handle_block         ] Got 1 transactions from network on block 921788
    744000ms th_a       witness.cpp:256               block_production_loo ] Generated block #921806 with timestamp 2016-04-26T07:12:24 at time 2016-04-26T07:12:24 by roadscape
    789001ms th_a       witness.cpp:256               block_production_loo ] Generated block #921821 with timestamp 2016-04-26T07:13:09 at time 2016-04-26T07:13:09 by roadscape
    849000ms th_a       witness.cpp:256               block_production_loo ] Generated block #921840 with timestamp 2016-04-26T07:14:09 at time 2016-04-26T07:14:09 by roadscape

Source server:

    498009ms th_a       witness.cpp:256               block_production_loo ] Generated block #921726 with timestamp 2016-04-26T07:08:18 at time 2016-04-26T07:08:18 by roadscape
    561007ms th_a       witness.cpp:256               block_production_loo ] Generated block #921746 with timestamp 2016-04-26T07:09:21 at time 2016-04-26T07:09:21 by roadscape
    570280ms th_a       application.cpp:431           handle_block         ] Got 1 transactions from network on block 921749
    642007ms th_a       witness.cpp:256               block_production_loo ] Generated block #921773 with timestamp 2016-04-26T07:10:42 at time 2016-04-26T07:10:42 by roadscape
    645211ms th_a       application.cpp:431           handle_block         ] Got 1 transactions from network on block 921774
    669154ms th_a       application.cpp:431           handle_block         ] Got 1 transactions from network on block 921782
    684005ms th_a       witness.cpp:268               block_production_loo ] Not producing block for ${w} because I don't have the private key for STM5P5sgVcp8z3hYXVHsTZnZVLtyp8Hsrjsotan8XLsheVMicxMhS

**Comment by bytemaster** [comment]
Can you provide a more detailed time line on:

1. block that included the update key op
2. blocks that your witness was supposed to produce

**Comment by roadscape** [comment]
Looks like 
 - block 921787: update key op 
 - block 921788: the missed block

------

Server A timeline

2016-04-26T07:10:42 -- Server A - 642007ms -- **generated block 921773**
2016-04-26T07:10:45 -- Server A - 645211ms -- Got 1 transactions from network on block 921774
2016-04-26T07:11:09 -- Server A - 669154ms -- Got 1 transactions from network on block 921782
2016-04-26T07:11:21 - ***************************** - **block 921787: update key op applied**
2016-04-26T07:11:24 -- Server A - 684005ms -- **Not producing block 921788**

Server B timeline

2016-04-26T07:10:42 -- Server B - 641998ms -- **Not producing block 921773**
2016-04-26T07:10:45 -- Server B - 645118ms -- Got 1 transactions from network on block 921774
2016-04-26T07:11:09 -- Server B - 669060ms -- Got 1 transactions from network on block 921782
2016-04-26T07:11:21 - ***************************** - **block 921787: update key op applied**
2016-04-26T07:11:24 -- Server B - 683999ms -- 10 assert_exception: Assert Exception
2016-04-26T07:11:24 -- Server B - 683999ms -- **Failed to push new block 921788 (?)**
2016-04-26T07:11:24 -- Server B - 684000ms -- Assert Exception next_block.validate_signee( witness.signing_key ):
2016-04-26T07:11:24 -- Server B - 684000ms -- Clearing pending transactions and attempting again
2016-04-26T07:11:24 -- Server B - 684000ms -- Assert Exception witness_obj.signing_key == block_signing_private_key.get_public_key():
2016-04-26T07:11:24 -- Server B - 684000ms - Clearing pending transactions and attempting again
2016-04-26T07:11:24 -- Server B - 684000ms - Failure when producing block with no transactions
2016-04-26T07:11:25 -- Server B - 684998ms - Not producing block
2016-04-26T07:11:26 -- Server B - 685998ms - Not producing block
2016-04-26T07:11:27 -- Server B - 687180ms - Got 1 transactions from network on **block 921787**
2016-04-26T07:11:30 -- Server B - 690200ms - Got 1 transactions from network on **block 921788**
2016-04-26T07:12:24 -- Server B - 744000ms - **Generated block #921806**

**Comment by abitmore** [comment]
I'm afraid It's rather a "feature". We had discussions about this behavior in BitShares long time ago. @pmconrad knows it best.

Best practice is: switch signing key **after** your witness produced a block.

**Comment by theoreticalbts** [comment]
Closing this, as it seems to be something of a non-issue.
