### ISSUE TITLE
Fix broken bcd-trigger

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#280]
The logic of `--bcd-trigger` option #247 is broken, needs fixed and tested.

**Comment by bytemaster** [comment]
What is "bcd trigger" and has this been fixed?

**Comment by theoreticalbts** [comment]
bcd-trigger stands for "broadcast disable trigger".  It is the feature to disable broadcast on low participation.  Due to some bugs, this code never actually activated.  It is documented [here](https://github.com/steemit/steem/blob/develop/doc/bcd-trigger.md).  The change has been merged for a long time but still needs testing.
