### ISSUE TITLE
percent_steem_dollars in comment_options shows random results on AppBase

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#2807]
When querying block # 25220874 for example and checking transaction_num 15, the `percent_steem_dollars` in `comment_options` shows 10000. Working properly with non-appbase:
```
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://rpc.steemviz.com | jq -r ".result.transactions[15]"
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://rpc.buildteam.io | jq -r ".result.transactions[15]"
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://gtg.steem.house:8090/ | jq -r ".result.transactions[15]"
```
(requires jq on linux, `apt install jq`)

![percent_steem_dollars bug nonappbase](https://user-images.githubusercontent.com/4613678/44346185-5d5e9f80-a463-11e8-8319-c1d7ded5c28b.jpg)

But on appbase nodes, it's giving random results every time it's queried! Interestingly on api.steemit.com it gives one value only: 55832 (which is still wrong).
```
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://api.steemit.com | jq -r ".result.transactions[15]"
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://appbasetest.timcliff.com | jq -r ".result.transactions[15]"
curl -s -d '{"id":0,"jsonrpc":"2.0","method":"call","params":["condenser_api","get_block",[25220874]]}' https://appbase.buildteam.io | jq -r ".result.transactions[15]"
```
![percent_steem_dollars bug appbase](https://user-images.githubusercontent.com/4613678/44346200-63548080-a463-11e8-8af5-b4e38e6f250c.jpg)

**Comment by mvandeberg** [comment]
My gut says to double check that the condenser API version of the comment options operation is copying `percent_steem_dollars` properly.
