### ISSUE TITLE
TN: Move active code of testnetinit.sh out of this repo.

### ISSUE THREAD

**Issue by relativityboy** [steemit/steem#2820]
As a developer I want to be able to modify the testnet deployment script and not have to wait a very-long-time (15+mins) before I can use it when no other changes have been made to steem.

**AC**
- [x]  testnetinit.sh task specific code is moved out of this repo into another one that does not have long build times
- [x] a mechanism is in place for making that code useable quickly
- [x] a comment titled `# Results` is added to this story (likely after technically being closed) with the utility of the change documented by the team making changes to the script.

**Comment by jredbeard** [comment]
# Results

Branch `2820-external-testnet-scripts` has the necessary changes.

A new repo was created to hold steem deployment scripts (currently only for the testnet) at github.com/steemit/steem-deployments

Script was modified to pull in the necessary files from that repo on launch

Three additional env vars were set in orchestration for the testnet - `SCRIPTURL`, `LAUNCHENV`, and `APP`.

This was tested and worked perfectly on a deployment earlier today.
