### ISSUE TITLE
Chain plugin chain ID command line parameter isn't specified in hex

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2827]
`--chain-id` option to `steemd` [here](https://github.com/steemit/steem/blob/develop/libraries/plugins/chain/chain_plugin.cpp#L318) is specified as a string, not a hex value.  It should be specified as a hex value for consistency with the rest of the tooling (`get_config` API call, `sign_transaction` CLI).

**Comment by theoreticalbts** [comment]
I just noticed `cli_wallet` uses a name.

**Comment by mvandeberg** [comment]
Yes, because those options we added at the same time https://github.com/steemit/steem/commit/7823b488b723285f23784e6cad575afd68268be1
