### ISSUE TITLE
limit the number of posts for the users with low reputation

### ISSUE THREAD

**Issue by Kiaazad** [steemit/steem#2834]
[As I explained here](https://steemit.com/utopian-io/@kiaazad/limit-zero-reputation-users-to-one-post-per-day-suggestion-for-steemit), some accounts keep spamming every five minute without any limitation, we can stop such spammers by imposing limitations on accounts with no SP and near zero reputation.

**Comment by mvandeberg** [comment]
The new RC plugin does a better job at accurately costing operations for stake based usage. Please wait for HF 20 and RC plugin to become active. If there is tweaking needed after the fact, we will do so.

Reputation is far too game-able to be used for such purposes.

Closing for now as won't fix as we already have pending fixes that have yet to be released.
