### ISSUE TITLE
Posts which will be truncated should not be allowed to be made

### ISSUE THREAD

**Issue by muksihs** [steemit/steem#2848]
Posts/comments which will never be viewable due to size should not be allowed to be posted to the blockchain and not be subject to an "after transaction filtering out".

Offending post with comments: https://steemit.com/far-horizons/@leatherdog-games/far-horizons-steem-game-complete-game-1526338556

I run a gamebot and the final game results cannot be viewed as they were posted as comments and exceed the max comment size.

If the contents of a post cannot be viewed due to size it should not be allowed to be posted.

Please add code to reject posts/comments which exceed hard coded limits for reading back out of the blockchain via the API.

```C
if( d.body.size() > 1024128 )
    d.body = "body pruned due to size";
if( d.parent_author.size() > 0 && d.body.size() > 102416 )
    d.body = "comment pruned due to size";
```

**Comment by mvandeberg** [comment]
`database_api.find_comments` does not impose this limit when returning a comment. This is a new API included in Steem 0.19.10+.

There does exist a soft limit on comment size where the node won't save the content if it exceeds 128MiB in size. However, with a 64k block size, that cannot happen.
