### ISSUE TITLE
Save blocks in bootstrap files

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#286]
- Save blocks in hourly / daily / weekly / monthly / yearly .bz2 files using Boost bz2 stream
- When LIB advances past the hour / day / week / month / year mark, save blocks in range into file.
- On startup, allow scanning for files in directory.
- Treat bootstrap files as additional block sources.
- If checkpoint is present, treat blocks from before checkpoint as trusted (so long as prev hash, tx hashes and checkpoint are still enforced)

**Comment by theoreticalbts** [comment]
Saving in separate files:

- Allow easier porting of blockchain directory between machines
- Compression saves transfer bandwidth
- Less likely than block DB to experience corruption on exit
- Bootstrapping new nodes via compressed bulk download reduces load on p2p network

**Comment by theoreticalbts** [comment]
OK, initial implementation is finished.  Current limitations:

- Only supports a single file
- Only supports files on the local filesystem (downloading must be done by an external script)
- Does not support any sha256 (integrity checking must be done by an external script)
- Saving must be done by an external script

You can prefix the bootstrap filename with `push:` to do full checking on the bootstrap blocks (recommended for the "does <branch> still sync to the network?" monitoring cronjob).

**Comment by mvandeberg** [comment]
We are favoring state snapshotting over this approach.

The block log solves many of the issues of the block DB that this issue was trying to fix.
