### ISSUE TITLE
Memos in transfer_from_savings

### ISSUE THREAD

**Issue by gryter** [steemit/steem#2862]
Currently transfer_from_savings allows for the inclusion of memos. When cancel_transfer_from_savings is broadcast, the memo had already been delivered without incurring any cost to the transaction (except for bandwidth which can be continuously recharged if minimum intervals between messages are observed).

![image](https://user-images.githubusercontent.com/31012685/44922268-f1a5ed80-ad12-11e8-86e6-3431a3ee406d.png)

**Vulnerability:** This means that a user may send a virtually unlimited number of memos without incurring a cost, allowing for a continuous script to be set up.

**Issue:** Removing memos reduces functionality. 

**Alternative solution:** 3 day timer to apply to all attempted transfers (funds locked for 3 days prior to return on cancellation).

**Comment by mvandeberg** [comment]
> the memo had already been delivered without incurring any cost to the transaction.

This is not true. While the user may not be spending STEEM, they are paying bandwidth/RC costs.

**Comment by gryter** [comment]
Thank you, edited statement.

**Comment by youkaicountry** [comment]
Currently the functionality is working as intended at the blockchain level, and there are definitely legitimate reasons users could cancel savings with a memo. 

Potential blockchain level changes to this may or may not be explored in the future, but at present this is a UI filtering issue whether/how to show cancelled savings transfers.
