### ISSUE TITLE
Merge btscube Visual Studio fixes

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#288]
#138 has bit-rotted enough that I'm going to rebase it onto staging.

**Comment by mvandeberg** [comment]
@btscube, would you mind writing WIN32 Build Instructions that we can add to the repo?

**Comment by abitmore** [comment]
@mvandeberg this? https://steemit.com/steem/@bitcube/steem-mining-in-microsoft-windows-a-builder-s-guide-part-1

**Comment by mvandeberg** [comment]
Thanks, I'll take a look at the guide.

**Comment by theoreticalbts** [comment]
Merged and closed. Further discussion of Windows build instructions should go under #328.
