### ISSUE TITLE
NAI Generation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2886]
Numerical Asset Identifiers should be pseudorandomly generated. 
NAIs should be taken from a pool, and replaced upon taking - to avoid a race condition.
The NAI should be checked for collision via `by_symbol`.

**Comment by sgerbino** [comment]
**Requirements**

- Create pseudorandomly generated NAI values
- Create database object to store these values in a pool
- Create JSON RPC call in database API called `get_nai_pool` that returns all available NAIs in the pool

**TODO**

- Change the wording in the SMT white paper defining a JSON RPC call `get_next_smt_identifier`

**Comment by TimCliff** [comment]
I'm trying to follow development for this change and it looks like a PR was merged, then a new PR was merged to revert the changes, and the issue is now closed. Will work be continuing on this issue, or is there another issue where the development has transitioned to?

**Comment by sgerbino** [comment]
@TimCliff This code is now merged in to master. It did get reverted, but then put back in. See https://github.com/steemit/steem/pull/3094.
