### ISSUE TITLE
'function' was not declared in this scope

### ISSUE THREAD

**Issue by Brinkss** [steemit/steem#2891]
First time user

this is part of a sketch I am working onn the first section allowes it to compile,
the second part dose not allow it to compile,
the only difference  see is the extra space between 'void' and 'timer,
am _ missing something. or is that not allowed ?????
If not why dose it not point to that
Arduino 1.8.7

void timer() {                   // timer timer timer timer
  
  if(start_millis > 0 && setpoint > 0) {
  new_millis = millis();
  usable_millis = new_millis; - start_millis; 
  usable_millis = usable_millis /1000;   // in seconds 
  }
  else
    usable_millis = 0;
 }           //End Timer

This statement works

void  timer() {                   // timer timer timer timer 
  
  if(start_millis > 0 && setpoint > 0) {
  new_millis = millis();
  usable_millis = new_millis; - start_millis; 
  usable_millis = usable_millis /1000;   // in seconds
  } 
  else
  usable_millis = 0;
 }           //End Timer

This causes the IDE to not allow functions to be reconised

**Comment by Brinkss** [comment]
In the sketch the second 'void  timer' had 2 spaces, as shown here.
Don't know what happened when I pasted it diapered

**Comment by Smittyvb** [comment]
This issue tracker is for issues relating to the Steem blockchain.
You might want to ask your question on the [Processing forums](https://discourse.processing.org/).

**Comment by Brinkss** [comment]
thanks for the help
