### ISSUE TITLE
`pending_claimed_accounts` not returned in `get_accounts`

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2896]
The responses from `database_api.get_accounts` and `condenser_api.get_accounts` do not appear to include the `pending_claimed_accounts` field.

**Comment by mvandeberg** [comment]
We should double check API schemas for all objects modified in `0.20.0`.

Those are:

```
account_object
dynamic_global_property_object
witness_object
chain_properties
witness_schedule_object
```
