### ISSUE TITLE
My undelegated steem, not yet received back in my account

### ISSUE THREAD

**Issue by rytimes** [steemit/steem#2905]
My account name @ryt. I have undelegated 1000 steem from @botz.  I didn't not received it back.  @timcliff said this may takes 30 days for new users I didn't understand whether it takes 30 from day of delegation by new user or from day account created. As per my account, it crossed 30 days from account creation. I didn't received my SP back😟😞☹️

**Comment by mvandeberg** [comment]
When you create an account via a delegation it takes 30 days for the SP to get back to you. I see you created the account Botz 22 days ago. You should expect your delegation to be returned to you in 8 days.

**Comment by rytimes** [comment]
Oh that's great! Thank you so much for helping me with this...  I was breaking my head, thinking why I didn't received my SP yet? Thank you again for responding

**Comment by Smittyvb** [comment]
Shouldn't SP delegated not in the account creation get returned early? Here's what happened
1. ryt creates an account with 28 SP.
2. ryt delegates 1000 SP, in a separate transaction.
3. ryt undelegates

Shouldn't the 1000 SP be returned in 7 days, followed by the 28 SP in 30 days?

**Comment by mvandeberg** [comment]
What do you mean by "unstable state"? HF 20 is not changing existing accounts or delegations. It is simply deprecating `account_create_with_delegation_operation` in favor of a better account creation system.

**Comment by rytimes** [comment]
That's fine, thank you mvandeberg.
