### ISSUE TITLE
get_block API returns null

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#2910]
The API calls `database::fetch_block_by_number()` 

https://github.com/steemit/steem/blob/017698e615096afa04412582ec0a77369f7be6c2/libraries/plugins/apis/block_api/block_api.cpp#L49-L58

https://github.com/steemit/steem/blob/017698e615096afa04412582ec0a77369f7be6c2/libraries/chain/database.cpp#L356-L367

A block in fork db means it's not in block_log. When there are more than one block with same height in fork db, aka `results.size() > 1`, the function calls `_block_log.read_block_by_num` but won't find the block, thus will return null.

**Comment by mvandeberg** [comment]
Closed in PR #2915
