### ISSUE TITLE
Add configuration option for rocksdb data directory

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem#2927]
Just like we can currently configure `--data-dir` and `--shared-file-dir`, it would be nice to have a `--rocksdb-data-dir` configuration parameter that allows specifying the location of where this data is stored. 

Currently I'm accomplishing this by symlinking the `account-history-rocksdb-storage` folder to another drive.

**Comment by mvandeberg** [comment]
`account-history-rocksdb-path` does this.

It will work relative to data dir if it is a relative path.

**Comment by aaroncox** [comment]
Awesome, thank you! I searched through the codebase looking for things related to `rocksdb` and `path`, but didn't stumble across this option.
