### ISSUE TITLE
Can't update owner authority in multisig account.

### ISSUE THREAD

**Issue by avral** [steemit/steem#2934]
Some error with multisig.. I have account with owner:
```
{"weight_threshold":2,"account_auths":[["avral",1]],"key_auths":[["STM84c6pHM2ii7YynqjVi7LpYQNnxhY59WYjJNbTtwZRwE7yjKVEk",1]]}
```

want change owner threshold to 1 and delete avral from account_auths
i sign transaction with owner key avral and owner key of my account(mapala.tester)
but had an error: missing required owner authority:Missing Owner Authority mapala.tester

avral owner key is not multisig, just one key: STM8Xk6JXpFfmjeF2cMVr2NeoaJb2oRr8bzGy5SFgtdLYp2NoGEUR
what am I doing wrong? with active keys, a similar operation works. Thanks!

my trx
```
{ ref_block_num: 60997,
  ref_block_prefix: 4261406205,
  expiration: '2018-09-24T00:04:21',
  operations:
   [ [ 'account_update',
       { account: 'mapala.tester',
         owner:
          { weight_threshold: 1,
            account_auths: [],
            key_auths:
             [ [ 'STM84c6pHM2ii7YynqjVi7LpYQNnxhY59WYjJNbTtwZRwE7yjKVEk', 1 ] ] },
         active: undefined,
         posting: undefined,
         memo_key: 'STM81bNApCKJPxYTKpoYfMj14J9Q3igvmkQWcKnyRnLo4zAp7BrCH',
         json_metadata: '' } ] ],
  extensions: [],
  signatures:
   [ '1f16645af6109e0740c7fc4be728446041e293d891f277792f2883dab42f5896921987e7a1b34c3fa0466e01ec66c7dfeb839c21cf0987df2ad87c0532ad98ad1e',
     '1f35b063cc9df5585488c9378897e00ff62972b9d641680456bdc2345e03cdd37b230e9d84e072d8470e7013057a902ec05aff6d449ffed3881e04fa69428780e2' ] }
```

**Comment by jredbeard** [comment]
Assuming you are running this against the testnet, your address prefix should be TST and not STM. The chain id for the testnet would also need to be set.

Can you please let us know if you are running this against the testnet or the mainnet, and if on  mainnet, what version of steem are you running?

**Comment by avral** [comment]
@jredbeard Yes, this is in mainnet. Im use official steem-js lib(0.7.2) api.steemit.com

For this operation i tried steempy, steem-js, steembase(Python)
but each time i had: missing required owner authority
Accordingly, I have a question, can I at all change the owner authority with the multisig transaction?

**Comment by abitmore** [comment]
@avral your account's owner threshold is 2 but weight of both items in the authority are 1, so, in order to change the owner authority, the transaction need to be signed by privates keys of `STM84c6pHM2ii7YynqjVi7LpYQNnxhY59WYjJNbTtwZRwE7yjKVEk` (the key in the authority) and avral's **active** key (the account in the authority). Theoretically it will work if replace avral's active key with avral's owner key.

**Comment by abitmore** [comment]
Update: owner of avral won't work if the same bug exists in Steem: https://github.com/bitshares/bitshares-core/issues/584
