### ISSUE TITLE
lost password

### ISSUE THREAD

**Issue by nabilharabi** [steemit/steem#2937]
I tried recovery my password but I encountered this error ( We are unable to recover this account, it has not changed ownership recently. )
help me please.thanks

**Comment by TimCliff** [comment]
It is not possible to recover a lost password. The stolen account recovery only works if your account has been hacked and the password changed, and requires you to have your previous working password.

**Comment by nabilharabi** [comment]
I have the last previous 2 passwords witch I changed be4re.

**Comment by TimCliff** [comment]
@nabilharabi please ask for further assistance from the steem.chat #help channel.

**Comment by nabilharabi** [comment]
I will do. thank you.
