### ISSUE TITLE
cli_wallet does not handle JSON-RPC Batch requests

### ISSUE THREAD

**Issue by HenryNguyen5** [steemit/steem#294]
Attempting to send a JSON-RPC Batch request results in a bad_cast_exception: Bad Cast
Invalid cast from array_type to Object

This seems like batch requests aren't supported in cli_wallet but they should be according to JSON-RPC 2.0 Spec: http://www.jsonrpc.org/specification#batch

**Comment by theoreticalbts** [comment]
Our JSON-RPC implementation is not precisely compliant to the spec (see e.g. #216).

It would be nice to be fully compliant, but it's a rather low priority -- patches are welcome.

**Comment by mvandeberg** [comment]
This is fixed in Appbase
