### ISSUE TITLE
Newly created accounts (via cli_wallet create_account_with_keys) have 0 current_mana

### ISSUE THREAD

**Issue by lukestokes** [steemit/steem#2940]
Not sure if this is a bug, but Tim suggested I go ahead and create a ticket just in case.

I created a new account on the testnet via create_account_with_keys and it doesn't appear to have any manna:

```
curl -s --data '{"jsonrpc":"2.0","id":1,"method":"rc_api.find_rc_accounts","params":{"accounts":["lukestokestest1"]}}' localhost:8090 | jq -r
{
  "jsonrpc": "2.0",
  "result": {
    "rc_accounts": [
      {
        "account": "lukestokestest1",
        "rc_manabar": {
          "current_mana": 0,
          "last_update_time": 1537832799
        },
        "max_rc_creation_adjustment": {
          "amount": "0",
          "precision": 3,
          "nai": "@@000000021"
        },
        "max_rc": 0
      }
    ]
  },
  "id": 1
}
```
Maybe this is specific to the testnet or something specific to how new accounts are created that isn't a bug, but here's the issue ticket either way.

It appears to have cost about `2,238,592` manna to create the account (19673397817 - 19671159225).

**Comment by lukestokes** [comment]
Also, the newly created account can't post:
```
RPCError: plugin exception:Account: lukestokestest1 needs 834820 RC. Please wait to transact, or power up STEEM.rethrow
```

**Comment by therealwolf42** [comment]
@lukestokes RCs are being generated similar to how VP is being regenerated. So AFAIK, it's normal that a new account doesn't have a lot of RCs. But I'm not sure if fresh accounts shouldn't start with a basic minimum, or if the RC costs are simply too high on testnet.

**Comment by theoreticalbts** [comment]
> it doesn't appear to have any mana

RC's are lazily regenerated over time.  So, if your account had zero mana at some point in the past, it will now regenerate to its maximum value over 5 days (`STEEM_RC_REGEN_TIME`).

> the newly created account can't post

The maximum RC is `max_rc`, which is defined by `get_maximum_rc()` function.  Checking this account on the testnet, it appears the account has no VESTS.  It is intended behavior that such an account cannot transact.  To enable transactions, transfer or delegate VESTS to the account.

**Comment by lukestokes** [comment]
Thanks, that makes sense and was the conclusion we seemed to come to after a bit of discussion as well because of the tesnet currently having an account creation fee of 0. Might it be good to change this on the testnet via the init accounts so we could do further testing of the RC system? Thanks for replying. Closing.

**Comment by mvandeberg** [comment]
Accounts in 0.20 don't have any SP (the fee is burned) so their max mana is 0. However, as soon as you power up or delegate to the account it will get 100% power of that SP in mana.
