### ISSUE TITLE
testnet - genesis accounts have no bandwidth

### ISSUE THREAD

**Issue by lopugit** [steemit/steem#2941]
So I've been running a testnet and I can get_account account with the cliwallet, but I can't make any new accounts or anything because it says the account doesn't have any bandwidth, and it says to power up or wait, but the account has reward_vesting_shares because it's been mining blocks.

and it seems like the only reason it fails the has_bandwidth check is because the current transaction size is taken into account when calculating the average bandwidth for the account, and because the operand is only > and not >= if the txn_bandwidth wasn't added to the accounts average bandwidth before the _db.modify and the operand was >= then the account would be allowed to create the transaction. 

see
https://github.com/steemit/steem/blob/master/libraries/plugins/witness/witness_plugin.cpp#L446

I can't even claim the rewarded score because of the way this code is structured? 

How else are you meant to get the chain off the ground?

I was thinking instead of adding a starting vesting_shares value in the init_genesis miner account creation loop.

am I missing something here?

How can the chain progress if all the genesis accounts have 0 vesting shares and can't claim any rewarded shares or power up??

**Comment by bobinson** [comment]
so this is the same as rc becoming negative and freeze or something else ?

**Comment by lopugit** [comment]
@bobinson I'm not sure what it is, because rearranged the formula is accountShares/totalShares > accountAverageBandwidth/totalBandwidth

but the genesis accounts don't start with any score so it's always gonna be false cause 0/x > 0+n/y will always be false... 

I just gave the genesis account some starting score to fix this but yeah still

**Comment by bobinson** [comment]
I think the issue you are mentioning is fixed in the following code  ?

PR https://github.com/steemit/steem/pull/2944

![2018-09-26_00-39-56](https://user-images.githubusercontent.com/18070249/46037193-1a0fe480-c125-11e8-9aec-6ccd8b6a3a74.jpg)

**Comment by lopugit** [comment]
@bobinson what does rc stand for sorry....?

**Comment by lopugit** [comment]
I'm on a v19.5 fork lol so it's still using the bandwidth mechanism

**Comment by bobinson** [comment]
resource credits : https://github.com/steemit/steem/blob/master/doc/devs/2018-08-20-resource-notes.md

**Comment by relativityboy** [comment]
@lopugit - we're using [tinman](https://github.com/steemit/tinman/) to bootstrap our testnet.

**Comment by lopugit** [comment]
@relativityboy yeah I bet you fucking are

**Comment by lopugit** [comment]
@roadscape this isn't testnet specific, if you just run the software without the TESTNET flag but with no peers the problem still exists, I meant "testnet" as in a new chain

so you guys literally have to power up via tinman before doing anything on a new chain?

**Comment by lopugit** [comment]
how come there isn't a powerup api in the cliwallet? ohh I could run a powerup transaction instead of adding vesting_shares to the genesis accounts and making sure the total_vesting_shares gpo prop adds up
