### ISSUE TITLE
Votingpower drained after transaction on HF20

### ISSUE THREAD

**Issue by therealwolf42** [steemit/steem#2949]
It seems that transactions while HF20 is active, resulted in drained votingpower.

For example:

@smartsteem send a transfer 15 minutes after HF20, which resulted in the voting power going down to around 2%.

![image](https://user-images.githubusercontent.com/31614097/46043578-b1226f80-c118-11e8-987b-75a2115e0212.png)

This also happened to multiple other accounts (https://steemd.com/@utopian-io, https://steemd.com/@postpromoter, https://steemd.com/@therealwolf, https://steemd.com/@qurator)

But accounts that didn't do anything after HF20, still have their votingpower intact (https://steemd.com/@smooth, https://steemd.com/@steem-ua)

**Comment by skzap** [comment]
https://steemd.com/@dtube too

**Comment by mightypanda-x** [comment]
+1

**Comment by Transisto** [comment]
Didn't do any transfer with mine and it got drained, I think it might have been the caim reward tx.

**Comment by cyh76507707** [comment]
https://steemd.com/@steemhunt has the same issue too.

**Comment by Transisto** [comment]
Pointing out that many didn't had this issue and receiving delegation is what all the above account have in common.

**Comment by ajayyy** [comment]
@Transisto that would make sense to be a probably cause

**Comment by ajayyy** [comment]
https://steemd.com/@timcliff is unusually low without delegation coming in.

**Comment by TimCliff** [comment]
Here is a good example of the issue. The account has only voted three times (ever), and is down to 12.94% voting power.

https://steemd.com/@accountcreators

![image](https://user-images.githubusercontent.com/20735105/46046556-19585d80-c0e7-11e8-8f04-3b3c43541220.png)

**Comment by Transisto** [comment]
My research shows that the more SP you had the move VP got drained.
Above about ~20k SP = ~100% drain.

**Comment by Transisto** [comment]
TimCliff example above is for two votes of 1% weight.

**Comment by therealwolf42** [comment]
@Transisto yes, any transaction resulted in the drain. Another great example: http://prntscr.com/kypv0l

**Comment by sydneyitguy** [comment]
seems it happened to all the dApps as well

![image](https://user-images.githubusercontent.com/1332279/46056472-c389c100-c18b-11e8-8203-f1ab6f1c3dc6.png)

![image](https://user-images.githubusercontent.com/1332279/46056482-cdabbf80-c18b-11e8-8ba4-bbfdf8b4fd53.png)

![image](https://user-images.githubusercontent.com/1332279/46056489-d8665480-c18b-11e8-9b21-19d8eea21c63.png)

![image](https://user-images.githubusercontent.com/1332279/46056524-fb910400-c18b-11e8-8250-a60f4df95050.png)

**Comment by TimCliff** [comment]
There is info here: https://steemit.com/steem/@steemitblog/update-on-unexpected-voting-power-behavior

**Comment by Chuuuckie** [comment]
![image](https://user-images.githubusercontent.com/36227271/46060665-b3c3aa00-c196-11e8-93e8-a81512e92f90.png)

SteemPress is also drained.

**Comment by roadscape** [comment]
I believe these cases are explained by https://steemit.com/steem/@steemitblog/update-on-unexpected-voting-power-behavior. Any ops which affect SP cause a recalculation of voting mana, e.g. claiming rewards. This would be a one-time occurrence. If there are otherwise reproducible cases, please file a new issue.
