### ISSUE TITLE
Cannot vote on Steemit.com with an account who's supposed to have enough mana.

### ISSUE THREAD

**Issue by Transisto** [steemit/steem#2951]
![image](https://user-images.githubusercontent.com/388716/46048008-47dd3500-c0f5-11e8-9d6a-c96a6f605f88.png)

account : https://steemd.com/@bitcoincore

Receiving this error from steemit.com when trying to vote.

`RPCError: plugin exception:Account: bitcoincore needs 3009160901 RC. Please wait to transact, or power up STEEM.rethrowDismiss`

**Comment by roadscape** [comment]
From https://steemd.com/@bitcoincore:
```
rc manabar-
current_mana   -1,571,348,952,628
last_update_time    1,506,556,911
estimated_mana     31,081,452,407
estimated_max      31,081,452,407
estimated_pct              100.00%

vesting_shares      31,081.452407
```

Unexpected:
```
estimated_mana    31,081,452,407
needs              3,009,160,901 RC
```

**Comment by mvandeberg** [comment]
We've investigated and identified the cause. It is already handled by a previous fix.
