### ISSUE TITLE
Negative mana in an account that never upvoted

### ISSUE THREAD

**Issue by develCuy** [steemit/steem#2953]
According to https://steemd.com/@uconecta

current_mana | -487,139,233,773
-- | --
last_update_time | 1,515,888,171
estimated_mana | -257,102,362,190
estimated_max | 4,505,702,569
estimated_pct | -5706.15%

How many years should this account wait to get enough mana?

**Comment by roadscape** [comment]
Negative RC resolved with #2945 in 0.20.3 release
