### ISSUE TITLE
Refilling of voting power after claiming rewards

### ISSUE THREAD

**Issue by the-oasis** [steemit/steem#2954]
Had multiple reports of people claiming rewards and their voting power is subsequently refilled by a substantial amount (>5%)

Note: Also by powering up, maybe other actions have similar effects as well. Maybe the numbers are still stabilizing. Reporting here just in case.

**Comment by therealwolf42** [comment]
It seems that the real voting power is `estimated_pct` of the manabar. The default voting power does increase when claiming rewards etc., but this has no effect while voting. I.E. doesn't increase the vote-value.

**Comment by roadscape** [comment]
Negative RC resolved with https://github.com/steemit/steem/pull/2945 in 0.20.3 release

**Comment by roadscape** [comment]
Powering up instantly increases voting power now. If you have 10 SP and 0% VP, and power up 10 SP, you would now be at 50% VP
