### ISSUE TITLE
Require RC plugin to produce blocks or broadcast transactions

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2965]
Now that we know that RC basically works on mainnet and we're pretty sure we won't need to switch back to the old bandwidth algorithm in a hurry, we can remove some of the contingency options which allowed nodes to easily switch between the old and new bandwidth algorithms (e.g. #2648).

Node misconfigurations that don't check RC are a prerequisite for situations like #2963.  Let's make it harder for that kind of misconfiguration to occur, by no longer exposing options for broadcast and witness nodes to disable checking RC's.

**Comment by boyacun** [comment]
Why can't I post a post on the Steemit blog, please give me a solution?
