### ISSUE TITLE
New hot algorithm should not depend on current time

### ISSUE THREAD

**Issue by arhag** [steemit/steem#297]
[This algorithm](https://github.com/steemit/steem/blob/52af1687b5305294c4f175836195d3667d91decd/libraries/plugins/tags/tags_plugin.cpp#L138-L141) is a problem because it depends on `now` which is `head_block_time()`.

Because the hot score depends on current time but it is only modified when post is updated, e.g. due to vote changes on the post, the hot scores of nearly all the posts will almost always be out-of-date. For this algorithm, an out-of-date hot score means that the rankings according to the hot scores of posts at any given time will most likely be incorrect. This can be proven:
```
x1 / y1 < x2 / y2 => x1 * y2 < x2 * y1 => x1 * y2 - x2 * y1 < 0
where y1, y2 > 0. 

Is x1 / (y1 + t) < x2 / (y2 + t) for any t > 0?
x1 / (y1 + t) < x2 / (y2 + t)
<=
x1 * (y2 + t) < x2 * (y1 + t)
<=
x1 * y2 - x2 * y1 < t * (x2 - x1)
<=  (since x1 / y1 < x2 / y2 is true and thus, since y1 > 0 and y2 > 0, it means x1 * y2 - x2 * y1  is less than 0)
x2 > x1    

But if x1 > x2, one cannot deduce from the given information that x1 / (y1 + t) < x2 / (y2 + t) for any t > 0.

Counterexample:

Let x1 = 3, x2 = 2, y1 = 2, y2 = 1, t = 3.
Then x1 / y1 = 1.5 < x2 / y2 = 2.
However, x1 / (y1 + t) = 3 / 5 = 0.6 > x2 / (y2 + t) = 2 / 4 = 0.5.

Therefore, given that x1 / y1 < x2 / y2,  x1 / (y1 + t) is not necessarily less than x2 / (y2 + t) for any t > 0.
```

The solution is **not** to update the hot score of every post each block, since that puts unreasonable computational demands on the nodes. The solution is instead to modify the algorithm that calculates the hot score so that it doesn't depend on the current time. Notice that the original reddit algorithm doesn't have this problem because it doesn't depend on the current time.

I appreciate the effort to change the reddit algorithm so that the new hot score does not depend on the Sybil-vulnerable `net_votes` but instead depends on the `net_rshares` of the post. However, the new algorithm is not good. I recommend instead using a simple modification of the reddit algorithm where a scaled version of `net_rshares` is used in place of `net_votes`. The other constant in the original algorithm may potentially be modified as well.

**Comment by bytemaster** [comment]
this has bene fixed with recent commit to develop,.
