### ISSUE TITLE
New accounts with 0 SP only have 3,000 RC

### ISSUE THREAD

**Issue by sydneyitguy** [steemit/steem#2971]
![image](https://user-images.githubusercontent.com/1332279/46120134-44f35900-c249-11e8-92e8-a5285aef41ad.png)

Shouldn't it be 5,000,000,000 RC?

Power up costs like 2,363,749,448 RC now.

**Comment by sydneyitguy** [comment]
Potentially resolved by https://github.com/steemit/steem/issues/2958 ?

**Comment by roadscape** [comment]
#2958 resolves incorrect adjustment, and https://github.com/steemit/steem/issues/2961 addresses drained RC upon creation.
