### ISSUE TITLE
max_rc slightly different to max_mana

### ISSUE THREAD

**Issue by quochuy** [steemit/steem#2973]
I noticed on steemd.com that the max_mana for RC and max_mana for voting mana is slightly different.
![screen shot 2018-09-27 at 10 20 48 pm](https://user-images.githubusercontent.com/310654/46145562-da233b80-c2a3-11e8-969f-c68cdd40645e.JPG)

An API call to rc_api.find_rc_accounts is giving a number but then calculating the effective VESTS of a user (max_mana for vote) gives a slightly different number as seen on the screenshot above.

**Comment by roadscape** [comment]
This is not a bug -- the calculations are otherwise very similar, but RC gets a slight increase from `max_rc_creation_adjustment` (burned creation fee).

**Comment by roadscape** [comment]
Voting Mana Calc https://github.com/steemit/steem/blob/c6b865b6f27999cba38f3840151c8306f14f3371/libraries/chain/include/steem/chain/util/manabar.hpp
RC Calc https://github.com/steemit/steem/blob/7c0d1204d076b0cfb2c0956c3f7939a023d1faec/libraries/plugins/rc/rc_plugin.cpp#L1002
