### ISSUE TITLE
new accounts start with 0 RC

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2976]
Distinct issue from #2961 (powerup/delegate does not credit RC instantly) - newly created accounts appear to be starting with 0 RC.

![image](https://user-images.githubusercontent.com/5168676/46169004-91499380-c25f-11e8-9491-9f35e0524839.png)

**Comment by roadscape** [comment]
Applies to `create_claimed_account` as well, e.g. https://steemd.com/@interfecto89

**Comment by theoreticalbts** [comment]
Actually, it seems the code does the right thing in the relevant place: https://github.com/steemit/steem/blob/5da440e2d312711a34349c94538a947428e10fca/libraries/plugins/rc/rc_plugin.cpp#L119

I suspect the apparent difference is a combination of #2961 and #2958.

**Comment by mac128k** [comment]
https://steemd.com/@interfecto89 back to 100% RC.
