### ISSUE TITLE
Remove private message plugin

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#299]
I want to either get rid of the private message plugin, or move it to a separate repo as an external plugin.

- It is broken; see #195 
- It has been in for a long time, but AFAIK it has exactly zero users.
- There is no web UI for it, and AFAIK no plans or development resources to make one.
- Private messaging is better implemented by side-chain or off-chain means.  There is no good reason to memorialize PM's forever on the main chain.

**Comment by brennhill** [comment]
This should be done P2P and not on a chain at all.  PMs are generally expected to be private and the userbase likes privacy.

**Comment by TheDarkLightX** [comment]
I disagree. Just encrypt the private messages with PKI and leave it on chain. Having the ability to always retrieve conversations is good for Alice and Bob because they have the keys to do it. Having no way to ever retrieve it offers no security benefit in the case of a dispute between Alice and Bob. 

Having it on chain yet encrypted allows for future dispute resolution.

**Comment by brennhill** [comment]
I like this idea. Agreed.

**Comment by iamsmooth** [comment]
Wow, I'm very surprised to see this feature not being prioritized on both the UI and blockchain. This is a frequently- and widely-requested feature that is a a conspicuous absence when compared to virtually every other social media platform. In the demand for it is also clearly apparent from the fact that many users have already discovered that payment memos can be used for this. When people find a secondary method to do something it demonstrates clearly that the demand to do it is strong.

**Comment by abitmore** [comment]
>The demand for it is also clearly apparent from the fact that many users have already discovered that payment memos can be used for this.

That said, on the other hand, we can just use that as an alternative for now.

By the way, once an "official" & "free" messaging feature is available, it will likely be (ab)used for spamming, we need to think about solutions in advance (e.g. white-listing), which consumes dev resources so perhaps low priority.

**Comment by TheDarkLightX** [comment]
Spam is easily defeated by applying the attention economy through a payment in the form of Steem for every private message from sender to receiver. The more Steem attached to the message, the higher the priority the message gets for the attention of the receiver. In this way if someone does want to spam they can pay for it in Steem and everyone is happy. 

Only friends should be able to bypass this pay for attention mechanism. F2F messages should be whitelisted on both sides.

**Comment by faddat** [comment]
I suggested this in one of my posts, but I want to shout this right now:

https://tuleap.ring.cx/plugins/mediawiki/wiki/ring/index.php/Build_Instructions
https://ring.cx/en/news#take-control-of-your-communication-with-ring-video-libre-planet

They're right now looking at blockchain technologies for logins.  Steemit.com is right now looking for a messaging solution.  Imagine that Steemit.com encompassed a messaging client where, among other things, users could send one another money to one another?  

* Ring's not super-mature
* Steemit is not super-mature

.....this means there's plenty of time for the 2 technologies to get it on, exchange DNA, and emerge stronger..... and have some freaky technology sex.  

**High x-factor**

**Comment by bytemaster** [comment]
This feature is high priority, @theoreticalbts spoke out of turn.  It has come up in every planning session.  To say it isn't on the roadmap or no resources are planned to be allocated to it is wrong.

**Comment by faddat** [comment]
Either way-- have you given any thought to integrating ring?

I'd also like to ask about compatiblity-- anything we can do to ensure that
steemit is compatible with as many other messaging systems as possible will
surely boost our uptake.  See: libpurple.

Let me know if you'd like a hand with this.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421
