### ISSUE TITLE
condenser_api.get_accounts reporting erronous voting power values

### ISSUE THREAD

**Issue by muksihs** [steemit/steem#3001]
Historically the condenser reports voting power as percent * 100. The value it is showing now makes no sense.

Example account: https://steemd.com/@leatherdog-games

steemd/mana currently shows: 

```
last_mana | 24,113,878,715
-- | --
last_update_time|1,538,205,033
max_mana|31,620,161,995
current_mana|26,683,456,046
current_mana_pct|84.39%
```

But condenser voting_power shows "49" which converts to 0.49%

**Comment by roadscape** [comment]
`acount.voting_power` adjusted for `acount.last_vote_time` === `voting_manabar.current_mana` adjusted for `voting_manabar.last_update_time`.

The `current_mana` value reported on steemd.com shows *is* the adjusted figure (the unadjusted figure was renamed to `last_mana`)
