### ISSUE TITLE
accounts with 0 voting mana can't vote

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#3004]
Received a report that a claim-created account was unable to cast votes.

**Comment by Smittyvb** [comment]
``@evoscoin`` is once such user. This is probably because claim-created users have 0 SP.

**Comment by roadscape** [comment]
Should "advisory"/no-op votes be allowed at all? Given that SP delegation seems to be a core concern for UIs, faucets, and communities for the foreseeable future, how many legit users would ever have 0SP?

Other than it seems strange to allow no-op reward distribution core consensus actions, one practical concern is that there is no way for external services to efficiently filter spammy no-op votes (until we have something like https://github.com/steemit/steem/issues/2545)

If the goal is to allow 0SP users to interact with content, there are alternative solutions:
 - off-chain, up to each UI
 - on-chain in the form of some custom_json-based "advisory vote" standard
