### ISSUE TITLE
Filtering of account history

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#301]
We will need several account histories -- in particular we need to filter out "spammy" transactions like fill orders, voting, curation rewards, and (when #300 is implemented) block production.  These should still be accessible in a separate history, but not included in the main history.  (The website already does this, but internal organization in steemd only has a single account history type -- it should be partitioned instead.)

It might also be useful to summarize these operations somehow -- e.g. you may not care too much about each individual block produced or each individual vote rewarded, but it might be useful to get a period summary each day / week.  The summary would make it possible to audit the user's balance in the block where the summary is included (along the lines of #300).

**Comment by mvandeberg** [comment]
I would like us to have different categories of operations and then be able to white list or black list the categories.
