### ISSUE TITLE
Scattered definitions of resource scales

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#3010]
Different resources' scales are defined in different places.  Let's make sure they're all returned correctly in `get_resource_params()`.

**Comment by theoreticalbts** [comment]
This should maybe be its own field, the `"resource_unit"` field of `resource_dynamics_params` is used in calculations.

**Comment by theoreticalbts** [comment]
It looks like `resource_state_bytes` is the only one for which `resource_unit` field doesn't tell the whole story.

**Comment by mvandeberg** [comment]
This is a non-issue
