### ISSUE TITLE
Why is my steemit account not login other device. 

### ISSUE THREAD

**Issue by mdraselhossain** [steemit/steem#3017]

**Comment by mdraselhossain** [comment]
plz any help me..?

**Comment by gryter** [comment]
If you are unable to login, make sure you're typing in your username and password properly without blank spaces before/after. Ask for help on https://steem.chat/channel/help if you require further assistance. 

Someone please close this.

**Comment by youkaicountry** [comment]
Unfortunately we can't offer general support but the Steemit community is often able to help. 

You can look for help by posting your question in the #help channel at https://steem.chat/home
