### ISSUE TITLE
Security Feature Proposal to reduce the risks in a Bitfinex Scenario for STEEM and SBD

### ISSUE THREAD

**Issue by Netherdrake** [steemit/steem#302]
Bitfinex has lot most of their customer's funds when their private keys misappropriated. One of ways they could have mitigated the risks is by having daily limits in place by the 3rd party (bitgo) they used for one of the signing keys.

I propose we make settable limitations on daily transfers part of the protocol, and easy to use by anybody.

**Example Implementation:**
Owners should have the ability to set an `active_limit` on their active keys (from `cli_wallet`).

If active_limit is set, transactions signed with the Active key cannot exceed a set amount of funds in a given time period.

If a transaction is signed with the Owner key, limits are ignored.
Furthermore, only the Owner key can be used to set/remove the limit.

The RPC call could be as simple as:
```
====> set_active_limit
{
    "STEEM": 0,  // no limit
    "SBD": 1000  // limit to 1,000 SBD in a 24hr period
}
```

This would essentially enable the exchange owners, as well as large stakeholders, to proactively limit their risks in an event of a hack.

**Exchange Owners:**
For example, if a major exchange holds $2,000,000 worth of STEEM and SBD, and their average daily STEEM/SBD withdrawals are $100,000 a day, they could set the limit to $200,000 a day. The automated withdrawal systems would be unaffected, and rarely - if ever - require human intervention.

In the above example, **only 10% of holdings are at risk**.
 
Full:
https://steemit.com/steemit/@furion/security-feature-proposal-to-reduce-the-risks-in-a-bitfinex-scenario-for-steem-and-sbd

**Comment by mvandeberg** [comment]
Related #239

**Comment by theoreticalbts** [comment]
I'm declaring this a duplicate of #239.
