### ISSUE TITLE
Bandwidth should be completely removed from code

### ISSUE THREAD

**Issue by Smittyvb** [steemit/steem#3029]
Original:

Right now it's commented out, but IMO it should be completely removed.

AC:

Delete the bandwidth code in its entirety.
Remove bandwidth related API fields.
Document API changes.

**Comment by bobinson** [comment]
Thank you @mvandeberg  on your inputs. 

> We made the decision to comment it out right now to get it done quickly with the plan to remove it later. 

Just to understand,
 1. are we planning to do a new version without completely removing the  bandwidth code ? 
2.  do we plan to test it extensively on the TESNET and make sure that all the side effects of removing the bandwidth code is identified and then, do a release ?

**Comment by reggaemuffin** [comment]
SteemCommunity/steem#3 is fixing this and the crashes, after review I will do a pr to the steemit repo. ping @theoreticalbts

**Comment by mvandeberg** [comment]
Need documentation of API changes from the removal.

**Comment by reggaemuffin** [comment]
@mvandeberg I have decided for reasons of backwards compatibility to keep apis as is and return dummy values, so these endpoints can be deprecated.

Exact values returned are https://github.com/SteemCommunity/steem/pull/3/files#diff-f0a8047a921832891adab38f170b4580R25-45

I added messages to all code parts that need to be removed when deprecation happens to make it easier for the next developer.

**Comment by mvandeberg** [comment]
We have discussed internally and decided to remove the deprecated APIs.

This will cause apps that rely on bandwidth to fail fast. Those apps might be misbehaving currently and failing silently.
