### ISSUE TITLE
Why can not I find my post in my blog

### ISSUE THREAD

**Issue by dmilash** [steemit/steem#303]
Why can not I find my post, such as this https://steemit.com/steemit/@dmilash/steemit-polls-is-that-possible-it-s-necessary in my blog? It really is not

**Comment by mvandeberg** [comment]
I can see it in your blog https://steemit.com/@dmilash
Besides the fact that this doesn't appear to be an issue, it is a Steemit.com "problem" and not a steemd one. Closing because it is irrelevant to steemd.
