### ISSUE TITLE
I am stucked...

### ISSUE THREAD

**Issue by BillTime** [steemit/steem#3031]
I am stucked when i try to build steem in google Ubuntu server.

I just followed the instruction, which is:
https://github.com/steemit/steem/blob/master/doc/building.md

but when i typed 'cmake -DCMAKE_BUILD_TYPE=Release ..', the program was stopped on 63%:
[ 63%] Building CXX object libraries/chain/CMakeFiles/steemit_chain.dir/database.cpp.o

I have no idea why this happens...

**Comment by TimCliff** [comment]
What are the specs of the server you are building on?

**Comment by BillTime** [comment]
Im using 50GB. Is this server memory problem? Should i expend memory?

**Comment by TimCliff** [comment]
50 GB of what? RAM?

**Comment by BillTime** [comment]
booting disk size is 50GB and machine type is g1-small(1 vCPU , 1.7GB memory)

**Comment by BillTime** [comment]
I was just try to running wallet so i fallowed the text, that's all.

Im noob in crypto and programing.

**Comment by VIM-Arcange** [comment]
You should compile the applications on a more powerful computer/instance (i.e. with more RAM), then copy it on your small google instance.

**Comment by BillTime** [comment]
Thanks for helping me, i just extend the computer power (re-make the google VM) and it go very smoothly.

**Comment by bobinson** [comment]
@BillTime  - great to know. If the issue is not persisting, do consider closing the issue.

**Comment by youkaicountry** [comment]
Closing.
