### ISSUE TITLE
Why does the get_discussions_by_tag api use the account db?

### ISSUE THREAD

**Issue by lopugit** [steemit/steem#3035]
See this: https://github.com/steemit/steem/blob/807fb40ec137a987dc53cee6d8455c7b6c47aeed/libraries/plugins/apis/tags_api/tags_api.cpp#L264

just wondering why the query parameter is "tag" and then it does an account query?

**Comment by espoem** [comment]
The title says `get_discussions_by_tag` but you linked the line from `get_discussions_by_feed` where the parameter *tag* holds the account name.

**Comment by lopugit** [comment]
@espoem damn sorry...
