### ISSUE TITLE
condenser_api.get_config returns wrong chain_id for https://testnet.steemitdev.com

### ISSUE THREAD

**Issue by cassade** [steemit/steem#3036]
I noticed that `condenser_api.get_config` returns wrong `chain_id` for https://testnet.steemitdev.com.

![2018-10-05 17 30 35](https://user-images.githubusercontent.com/9163038/46541330-66e18100-c8c4-11e8-808d-29e1921d36db.png)

Actual value for testnet is `46d82ab7d8db682eb1959aed0ada039a6d49afa1602491f93dde9cac3e8e6c32`, as far as I know.

**Comment by therealwolf42** [comment]
Looks like chain_id is `18dcf..` inside the get_config.json.path file.

https://github.com/steemit/steem/blob/c6b865b6f27999cba38f3840151c8306f14f3371/python_scripts/tests/api_tests/database_api/get_config.json.pat#L31

**Comment by inertia186** [comment]
`get_config` returns compile time values.  To get the runtime chain-id:

```json
{
  "jsonrpc" : "2.0",
  "method" : "database_api.get_version",
  "id" : 1
}
```

Which returns:

```json
{
  "jsonrpc" : "2.0",
  "result" : {
    "fc_revision" : "a8cd260e819dccca173993e4dc295229072082c5",
    "blockchain_version" : "0.21.0",
    "steem_revision" : "a8cd260e819dccca173993e4dc295229072082c5",
    "chain_id" : "46d82ab7d8db682eb1959aed0ada039a6d49afa1602491f93dde9cac3e8e6c32"
  },
  "id" : 1
}
```

**Comment by youkaicountry** [comment]
Summary or resolution: use the chain-id from `database_api.get_version`, as it returns the runtime value.
