### ISSUE TITLE
Allow Advertising

### ISSUE THREAD

**Issue by brennhill** [steemit/steem#304]
Bring extra money into the system via advertising and tracking views.

**Comment by taoteh1221** [comment]
@brenhill I think half of STEEMit's appeal is no advertising...and it's already bringing in tons of money.

**Comment by brennhill** [comment]
There's a limit to how much money will come in for buying steempower.  The point of money is that you can exchange it for many things.  Advertising also rewards different user types and business models other than getting lots of upvotes from whales.  E.g. if you have a blog that can reach 100,000k minnows, you make nothing compared to what you could make on youtube with ads and sales for whatever your niche is.  We should enable those creators as long as they aren't selling BS.  

The current ecosystem is overly introspective.  Allowing advertising but making transactions happen in STEEM would make the currency way more robust.

**Comment by brennhill** [comment]
Also, this should be something the AUTHOR should enable for their posts.

**Comment by mvandeberg** [comment]
**_If_** we added advertising and tracked views, it would be done on Steemit.com, not on the blockchain. Closing this because it is unrelated to steemd.
