### ISSUE TITLE
API Error Smoketest

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3045]
To help prevent the team from missing API failures, such as the one described in #3040, we will develop a simple test harness that tests all API calls against a known good input and fails on the existence of the jsonrpc error field.

This does not check the validity of the data returned, simply that the API does not return an error.

**Comment by inertia186** [comment]
We actually have this already implemented:

https://github.com/steemit/devportal/blob/develop/readme.md#tests

The tests in devportal execute the `curl` examples currently documented on the site to ensure they are accurate.  But they are just manually executed at the moment.

They even return shell error codes, depending on the outcome.  So they're perfect for smoke tests.
