### ISSUE TITLE
Audit smt_test_plugin

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3053]
I am not entirely sure what the purpose of the smt test plugin is. With the exception of #3038 it does not appear to have been maintained.

We should review the plugin to determine if it is needed and if so determine whether to keep such tests in a plugin or move the test cases to our unit test framework.

**Comment by youkaicountry** [comment]
Audited, decided to keep for duration of SMT v1 development. Issue #3093 will remove it.
