### ISSUE TITLE
Bug in Asset

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3057]
```
2907232ms database.cpp:3267             _apply_block         ] 10 assert_exception: Assert Exception
a.symbol == b.symbol:
    {}
    asset.hpp:69 operator>=

    {"op":{"type":"transfer_operation","value":{"from":"arunava","to":"a-bot","amount":{"amount":"100","precision":3,"nai":"@@000000013"},"memo":"https://steemit.com/steemit/@arunava/collecting-silver"}}}
    database.cpp:3491 _apply_transaction
```

I am assuming that the bug is not actually in the comparator, but maybe in deserialization of legacy assets.

**Comment by sgerbino** [comment]
To produce this reported issue:
1. Take a blockchain state file that existed before the NAI generation code.
2. Run `steemd` compiled with NAI generation code

**Comment by sgerbino** [comment]
I assume this change is the reason for this:
https://github.com/steemit/steem/pull/2925/files?utf8=%E2%9C%93&diff=split#diff-ec4e95ddbd5ba0c8f2d86ced35cc3870L24

**Comment by youkaicountry** [comment]
Fixed as part of NAI generation.
