### ISSUE TITLE
allow_replies cannot be set through a comment_options_operation

### ISSUE THREAD

**Issue by holgern** [steemit/steem#3059]
In https://github.com/steemit/steem/commit/5fcabd81b0f31862608533d2157e470f6db4e921 the option `allow_replies` was removed from the comment_options_operation. 

The allow_replies  logic and checks seem to be in place. So I think there is no reason why allow_votes can and allow_replies cannot be set.

I think the changes from https://github.com/steemit/steem/commit/5fcabd81b0f31862608533d2157e470f6db4e92 regarding allow_replies should be reverted.

**Comment by mvandeberg** [comment]
You are referencing a commit from June 28, 2016 that was clearly made during the development of the operation. IIRC, the decision to remove the option from consensus was based on use cases for comments beyond simply communicating (many Steem Dapps do this) and preventing comments in consensus could constrain certain apps.
