### ISSUE TITLE
Partially revert resource increases, stronger feedback

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#3061]
PR #2981 was written to quickly fix issues in the cost curves immediately after the HF20 release.  The purpose of this issue is to replace that quick fix with a more robust implementation.

The following changes should be implemented:

- (a) Multiply `resource_history_bytes`  by `0.125`
- (b) Multiply `resource_market_bytes`   by `0.125`
- (c) Multiply `resource_state_bytes`    by `0.150`
- (d) Multiply `resource_execution_time` by `0.125`

- (e) Change `a_point_num`, `a_point_denom` from `(37, 1000)` to `(50, 10000)` for all resources.

- (f) Hard-code `resource_unit_base`, `resource_unit_exponent` for all resources

The resource limit reductions in changes (a)-(d) by themselves would increase RC costs.  But they are counterbalanced by (e), which decreases costs when resource usage is low.  (e) also increases the "gain" or "elasticity" to near its original intended value, which should improve the "market feedback loop" between resource usage and RC costs.

(f) is simply to prevent the need for unit conversions when dealing with both old/new parameter sets, at a small cost in precision.

A simulation shows these changes should have the following approximate multipliers on the RC costs of standardized transactions at current pool levels:

```
2018-10-11 17:00:00:1   long_post               0.265
2018-10-11 17:00:00:1   short_post              0.265
2018-10-11 17:00:00:1   transfer                0.970
2018-10-11 17:00:00:1   vote                    0.265
```

As you can see, the RC cost of standardized transactions actually *drops* based on these changes.

**Comment by clayop** [comment]
So `0.265` for `long-post` means required RC is decreased about 1/4 compared to current consumption?
