### ISSUE TITLE
consenser_api.get_content() no more returns root_comment

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/steem#3069]
I noticed that, as of 2018-09-17, when calling consenser_api.get_content() no more  returns the `root_comment` field.

I guess it happened when I upgrades my nodes for HF20.

I made a quick search in the code but could not find when/where it has been removed.
Is this behavior intended or not? If yes, can you explain why the change?

**Comment by mvandeberg** [comment]
The `root_comment` field returned an integer `comment_id_type`. It was replaced with `root_author` and `root_permlink` assuming that these fields were far more useful than an identifier that is intended for internal use only.

Do you need the field as is? Or do the replaced fields work for you? If you absolutely need the `comment_id_type`, we can add it back, but I am quite curious why you specifically need it.

**Comment by VIM-Arcange** [comment]
> The root_comment field ... was replaced with root_author and root_permlink
Good to know. I missed that

> Do you need the field as is? (comment_id_type)
Yes, I would like to.

As you know, SteemSQL stores all comments. People performs analysis or processes on posts and use this field to retrieved all post's related comments.

Having `root_comment` as an integer allows fast indexing and saves **gigabytes** of storage.

Should SteemSQL switch to the new `root_author` and `root_permlink` and delete `root_comment`, it will require a huge storage space because SteemSQL will have to store twice the values (once for data itself and once more for the index)

**Comment by mvandeberg** [comment]
The reason we have moved away from returning comment id as a foreign key in APIs is that the object id in steemd is an implementation detail. It isn't actually a part of consensus and _could_ change as a result of some other requirement. Where comment IDs were returned, we now return the canonical identifier (author/permlink). We do still return the id of the object, but perhaps be shouldn't.

> Should SteemSQL switch to the new root_author and root_permlink and delete root_comment, it will require a huge storage space because SteemSQL will have to store the values twice (once for data itself and once more for the index)

I would not actually recommend SteemSQL changes its internal format. However, returning the root comment id is not a requirement for SteemSQL to continue to store comments this way. I am assuming that SteemSQL still allows for comment lookup via author/permlink. When adding a new comment to SteemSQL, you lookup what the ID of the root comment is and replace the root author and root permlink with the ID. In fact, this is how steemd works internally.

Even if steemd APIs did not return comment IDs at all, SteemSQL could still use a numeric ID a primary key for each comment and as a foreign key for the root/parent.

I am curious now if SteemSQL is using the parent author/permlink as the foreign key for the parent comment. If so, you can apply the same transformation and save on resources.

> I would even see the new fields removed and see you more resource saving oriented.

This is not necessary. steemd defines two versions of each object, the internal version and the API version. We've done this specifically so we can optimize the internal version without compromising the API version. Internally, comments are actually stored as two database objects. One with static length fields and another with dynamic length fields to minimize the number of dynamic memory allocations needed. When you query `get_content` we effectively do a join on the two objects to create the object that you know of as a comment.

**Comment by VIM-Arcange** [comment]
> When adding a new comment to SteemSQL, you lookup what the ID of the root comment is and replace the root author and root permlink with the ID. In fact, this is how steemd works internally.

This looks like as a good idea, despite the fact it will add additional load to the database because of the ID lookups.

Currently, SteemSQL does not use ID <-> author/permlink mapping because until now I have prioritized performances and usability over storage usage. 

That's also why, even if the Comments table has an ID  set as a primary key, I did not implement foreign key on any related table. Not a good database design, but when performances matter, you need to make some choices. I consider that the blockchain does the required integrity checks and that the data that SteemSQL receives is therefore consistent.

As I said when I met you at SF2, all those author/permlink everywhere is a storage nightmare. 
But implementing ID mapping everywhere would be a nightmare for users (and/or the server) who will have to JOIN everywhere to resolve ID to author/permlink.
