### ISSUE TITLE
Testnet api error 

### ISSUE THREAD

**Issue by jmliz** [steemit/steem#3077]
I'm trying to use the live testnet node described here https://developers.steem.io/testnet/

but I'm getting the error "Invalid cast from type 'array_type' to Object" while trying using the comment command (trying to post something).

Here's my code using [dsteem](https://github.com/steemit/dsteem) lib:

```
testnetApi = new dsteem.Client('https://testnet.steemitdev.com', {
    chainId: '46d82ab7d8db682eb1959aed0ada039a6d49afa1602491f93dde9cac3e8e6c32',
    prefix: 'TST'
});
```

`testnetDSapi.broadcast.comment(article, key);`

article object:

```
    article.parent_author = '';
    article.title = 'blablah';                
    article.author = username;
    article.parent_permlink = tags[0];
    article.permlink = 'valid_permlink'
    article.json_metadata = JSON.stringify({
        tags: tags
     });
```

**Comment by youkaicountry** [comment]
This looks like an issue in dsteem library or your code accessing it, not one in steemd. Please carefully check the documentation and ask the community https://jnordberg.github.io/dsteem/. Good luck!

**Comment by jmliz** [comment]
@youkaicountry thanks for answering my issue.

how do you know the errors is on my side?

The error message "Invalid cast from type 'array_type' to Object" 

is returned by your api with a HTTP error code.

**Comment by jmliz** [comment]
@youkaicountry and I'm making the same query against steemit mainnet server and I get no error in that case. It only happens with the testnet node.

**Comment by mvandeberg** [comment]
My guess is that the version of dsteem you are using has not been updated for the "appbase" release of Steem (0.19.10). api.steemit.com runs some extra services that helped ease the transition that are not in place on our testnet.

**Comment by mvandeberg** [comment]
One of the big changes was moving from array arguments to object args. The error makes sense "Invalid cast from type 'array_type' to Object" if dsteem is still passing in arguments in an array and steemd is attempting to deserialize it as an object.

**Comment by jmliz** [comment]
@mvandeberg 

I updated dsteem and the error is gone. thank you v much.
