### ISSUE TITLE
showing weird key for non-exisiting account 

### ISSUE THREAD

**Issue by TOMOAKI12345** [steemit/steem#309]
locked >>> get_private_key_from_password "tomoakAjhoih0t8jaijoIJOFnai" "owner" ""
>> then show the public key and private key for the non-exisiting account.

**Comment by liondani** [comment]
I think it happens for any password that don't link to an existing account... Just put a random passwords to check it out.... That is actually not a problem!

**Comment by liondani** [comment]
It's a way to check out forgotten passwords (if it much the public key you found your lost priv.key)
I assume that is the way for hackers to brute-force accounts with easy passwords...(using a script of course)

**Comment by theoreticalbts** [comment]
This is really just a convenience string / key processing method that doesn't reference chain state at all. Judging by the commit message, it is the same as what the JS on steemit.com uses.

I guess the purpose is to allow a steemit.com password to be converted to a private key from within the CLI. If you feed it an invalid password, account, or role, it'll happily give you a garbage private key, as it doesn't reference any chain state or even validation.

This isn't a bug, it's a consequence of the architecture of this method.

**Comment by TOMOAKI12345** [comment]
@theoreticalbts thanks :)
