### ISSUE TITLE
Separate hardfork constants per feature

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#31]
The Steem hardfork numbering scheme used so far is different from Graphene.  Each Steem hardfork time has a sequential number identifying the hardfork.  However, the problem is that this confounds the code for several distinct features / bugfixes which take effect at the same time.  For example `STEEMIT_HARDFORK_1` is used to activate the following code:

- Vesting share split
- Asserting URL sizes in witness_update
- Removing fees from witness account creation
- Enforcing account creation fees
- Forbidding updates of the temp account
- Changing the permlink validation algorithm for comments
- Removing the enforcement of once-per-minute posting time
- Allowing zeroing vesting withdrawals
- Enforcing minimum VESTS balance for withdrawal.

Each of these should have its own issue number which should be used to create a separate hardfork constant.

**Comment by mvandeberg** [comment]
I have been thinking about how best to handle the hardfork naming convention. I do not like having a separate hardfork constant for each issue, especially in cases like the first hardfork. We would end up with 8-10 different hardfork constants, each corresponding to an issue, but it would reduce the readability of the code substantially. As it is, it is easy to know what happens at a certain time. Searching for `STEEMIT_HARDFORK_1` reveals all changes that occur at that particular time. On the other hand, I do agree that an increasing hardfork numbering system isn't ideal. It is a magic number, and nothing less.

I propose the following scheme instead. Each hardfork constant should refer to the release in which it is introduced. (e.g. `STEEMIT_HARDFORK_2` would become `STEEMIT_HARDFORK_0_2_0`) In addition to this, we should be assigning all issues to milestones that represent the releases (even if they are not planned we can assign milestones post release. Our github history should accurately reflect the state of the codebase) and each release should come with patch notes. This retains the property of grouping various changes temporally into the same constant, but allows aggregation of such changes in a way that is easy to document, look up, and has relevance outside of the source code.

**Comment by mvandeberg** [comment]
We have settled on a hardfork naming scheme that will mirror the version scheme in #54.

Each hardfork will have a constant `STEEMIT_HARDFORK_M_H` which matches the major and hardfork version numbers. There is no need for revision number as no hardforks will be present in them. This constant contains the unique hardfork id number which is simply an increasing number which is the absolute hardfork number. In addition, each issue referred to in the hardfork will have their own hardfork constant which will be prefixed with `STEEMIT_HARDFORK_M_H` and have the suffix of `__ISSUENUM`. For example, this change will hit along with 0.5. Although it does not need a hardfork, if it did, we would call it `STEEMIT_HARDFORK_0_5__31`. This gives us readability in the code to quickly group hardforks temporally while retaining an easy way of referencing back to the issue the hardfork addresses.
