### ISSUE TITLE
Unable to complete sync on DO droplet (killed)

### ISSUE THREAD

**Issue by steempayments** [steemit/steem#310]
Every time i start steemd, after 99.065% of replay steemd shuts down with message 'killed'.
Running digital ocean 8Gb droplet.

The same installation and configuration works without any hassle on over 20 other VPS servers.

Anyone familiar?

![sync](https://cloud.githubusercontent.com/assets/20741940/17837086/1a92ff8c-67a9-11e6-97aa-ff30abb0adc2.png)
https://screencloud.net/v/B5S4

**Comment by ByronAP** [comment]
use the top command and watch the mem usage, make sure you are running steemd in a different session (screen -R steemd) so you can switch between the 2

**Comment by steempayments** [comment]
I'm at 17% of RAM usage it says

**Comment by ByronAP** [comment]
at 99%... that doesn't sound right

**Comment by steempayments** [comment]
2Gb Swap, 8Gb RAM. Once again...
![iss1](https://cloud.githubusercontent.com/assets/20741940/17837371/dddaf0f0-67b1-11e6-8faf-d141b09ef8a7.png)

**Comment by steempayments** [comment]
TOP results


![iss2](https://cloud.githubusercontent.com/assets/20741940/17837425/f509e92e-67b2-11e6-8cda-d35422e1635c.png)

**Comment by steempayments** [comment]
Resolved. Turns out my CPU was to low.
