### ISSUE TITLE
Fix build in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#3102]
Build fails on OpenSSL 1.1.0f, see steemit/fc#18.
Potential fix: https://github.com/bitshares/bitshares-fc/commit/0a90eff69778c0ef1d26f75d11d459ca172eff0c

Acceptance Criteria:

- Able to build in Ubuntu 18.04 with default package manager versions of libraries.

**Comment by mvandeberg** [comment]
Using our Dockerfile as build instructions, steemd builds but the wallet fails with the following error:

`Can't locate doxygen/perlmod/DoxyDocs.pm in @INC (you may need to install the doxygen::perlmod::DoxyDocs module) (@INC contains: /home/ubuntu/steem/libraries/wallet /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/ubuntu/steem/libraries/wallet/generate_api_documentation.pl line 6.`

Related: #1752

**Comment by mvandeberg** [comment]
Following the DockerFile I can build with the following commands

``` bash
apt-get update
apt-get install -y \
   autoconf \
   automake \
   autotools-dev \
   bsdmainutils \
   build-essential \
   cmake \
   doxygen \
   gdb \
   git \
   libboost-all-dev \
   libyajl-dev \
   libreadline-dev \
   libssl-dev \
   libtool \
   liblz4-tool \
   ncurses-dev \
   pkg-config \
   python3 \
   python3-dev \
   python3-jinja2 \
   python3-pip \
   nginx \
   fcgiwrap \
   awscli \
   jq \
   wget \
   virtualenv \
   gdb \
   libgflags-dev \
   libsnappy-dev \
   zlib1g-dev \
   libbz2-dev \
   liblz4-dev \
   libzstd-dev

cd /usr/local/src/steem
mkdir build
cd build
cmake \
   -DCMAKE_BUILD_TYPE=Release \
   -DBUILD_STEEM_TESTNET=ON \
   -DLOW_MEMORY_NODE=OFF \
   -DCLEAR_VOTES=ON \
   -DSKIP_BY_TX_ID=ON \
   ..
make -j$(nproc)
```

Build still works on OS X on my local machine and prior to merging will be tested on Ubuntu 16.04 as part of CI.
