### ISSUE TITLE
Replay stops during the flood of rc_plugin messages

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#3111]
During the replay on v20.6, the process stops completely with no CPU activity. It happens during the rc_plugin messages around 97% of the replay.

In one replay, it stopped at block **26442815**:
```
3370021ms rc_plugin.cpp:261             operator()           ] Accepting transaction by marcusmalone, has -56779517986 RC, needs 385396919 RC, block 26442813, witness bhuz.
3370022ms rc_plugin.cpp:261             operator()           ] Accepting transaction by modelcoinmc, has -42654774093 RC, needs 382648008 RC, block 26442814, witness blocktrades.
3370024ms rc_plugin.cpp:261             operator()           ] Accepting transaction by modelcoinmc, has -42672633235 RC, needs 383826212 RC, block 26442815, witness smooth.witness.
3370024ms rc_plugin.cpp:261             operator()           ] Accepting transaction by marcusmalone, has -57072862187 RC, needs 383040787 RC, block 26442815, witness smooth.witness.
```
In another replay, it stopped at block **26356958**:
```
3554771ms rc_plugin.cpp:261             operator()           ] Accepting transaction by edesee, has 16064720 RC, needs 372003748 RC, block 26356958, witness therealwolf.
3554771ms rc_plugin.cpp:261             operator()           ] Accepting transaction by lalalopoberlin, has 56225102 RC, needs 110262013 RC, block 26356958, witness therealwolf.
3554772ms rc_plugin.cpp:261             operator()           ] Accepting transaction by ammard, has 986765142 RC, needs 1404167528 RC, block 26356958, witness therealwolf.
```
I'm using the same config.ini as in 20.5. On 3 servers, everything went fine, but on one server it just doesn't want to go any further. I tried deleting the block_log and block_log.index, downloaded a fresh file, deleted and re-created the shared mem file. No success.

**Comment by Jolly-Pirate** [comment]
As a desperate measure, I did a system update then rebooted, the 20.6 replay went well. Not sure if it was the update or the reboot, but it worked in a mysterious way.

**Comment by mvandeberg** [comment]
> Not sure if it was the update or the reboot, but it worked in a mysterious way.

![Turn it off and back on](https://thumbs.gfycat.com/UnconsciousAltruisticBasil-size_restricted.gif)

**Comment by Jolly-Pirate** [comment]
It seems a reboot wasn't enough, the system needs and update and an upgrade, followed by the reboot.
```
apt update
apt upgrade
shutdown -r now
```
Then reset the shared file and replay.

**Comment by youkaicountry** [comment]
Closing as resolved.
