### ISSUE TITLE
Undefined error at CMake command

### ISSUE THREAD

**Issue by Rimann91** [steemit/steem#312]
While trying to build I keep getting this error
`Configuring incomplete, errors occurred!`

I checked the output logs, no obvious errors stand out. 
The log just stops at-

`implicit fwks: []`

**Comment by mvandeberg** [comment]
Can you post the entire output of cmake?

**Comment by Rimann91** [comment]
Thanks for the offer at help, I just removed the files and started from the beggining. It worked this time. Not sure what I did wrong

**Comment by theoreticalbts** [comment]
Closing, as this doesn't sound at all reproducible.
