### ISSUE TITLE
int_array::from_variant assumes integer type

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#3123]
I implemented the `int_array` class for `rc_plugin`.  It is basically the same as `fc::array`, but with default initialization for integer values, and better JSON serialization.

The JSON deserialization compares to integer bounds.  This causes `int_array` to fail compilation when generating the code to deserialize non-integer types, as is actually done in `rc_plugin`.  (`int_array` should probably be renamed to something else since it now works with non-integer types.  I'm open to suggestions.)

**Comment by mvandeberg** [comment]
Closed in #3124
