### ISSUE TITLE
Allow smt_create_operation to reset setup

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#3144]
As a token creator who has put their token in an unlaunchable state, I would like to be able to fix the problems.

AC:
- Issuing `smt_create_operation` with 0 fee and the NAI of a token in setup should reset emmisions and setup state.
- Create API calls `list_smt_tokens` and `find_smt_token`

**Comment by sgerbino** [comment]
@youkaicountry And override smt_create_operation variables (e.g. precision)?

**Comment by youkaicountry** [comment]
Yep, it should also override `smt_create_operation` variables.

**Comment by mvandeberg** [comment]
Blocked on #2726 #2727 #2728

**Comment by youkaicountry** [comment]
The whitepaper should be updated to include documentation for this behavior, in `SMT object creation`, `SMT creation fee`, and/or `SMT pre-setup` sections.

**Comment by youkaicountry** [comment]
Whitepaper changes accepted, moving to code review.

**Comment by mvandeberg** [comment]
As mentioned in #3164

> We are still discussing the best method for modifying emission schedules. This is motivated by the fact that emissions are unbounded and this op can modify an unbounded number of objects.

Possible solutions: 

- Allow deleting of emission schedules with with `smt_setup_emission_operation`
- Allow changing of precision with `smt_create_operation` if there are no emission objects already created.
