### ISSUE TITLE
Transaction status rebuild state can crash

### ISSUE THREAD

**Issue by sgerbino** [steemit/steem#3145]
The transaction status plugin can crash if rebuild_state is called, this is possibly caused by unique constraint violation when a race condition occurs between chain plugin pushing blocks/transactions while transaction status rebuilds state.

**Comment by mvandeberg** [comment]
It looks like `void transaction_status_impl::rebuild_state()` just needs to acquire the write lock on the database as it happens outside of the normal block application path.
