### ISSUE TITLE
Exchange sample config.ini is missing plugins

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#3149]
In the https://github.com/steemit/steem/blob/master/doc/example_config.ini file, which is linked to from exchangequickstart.md, the list of plugins on the plugin line is not sufficient for running an exchange node.

Update it to:
```
plugin = witness account_history_rocksdb account_history_api
```

**Comment by mvandeberg** [comment]
Thanks for bringing this our attention, but this fix alone does not make this a valid config file. I propose changing the acceptance of this issue to updating the entire config to be a valid config file.

**Comment by TimCliff** [comment]
Will do. I'll update the PR.

**Comment by mvandeberg** [comment]
Completed by #3440
