### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by stefhenry** [steemit/steem#315]
Hi,

I mined 5 blocked a few days ago, but my wallet is still showing 1 steem power.

showing blocks:
https://steemd.com/@cryptofranco

wallet:
https://steemit.com/@cryptofranco/transfers

thanks a lot for your reply

**Comment by abitmore** [comment]
On the page, you can see:
```
total_missed
5
last_confirmed_block_num
4,249,170
```
Which means you produced at least one block (so 1 STEEM) but missed 5 blocks. Perhaps you're not online when it's your turn or some networking issue happened? Please be aware that once you mined out a "ticket", you need to stay online for about 2 hours to produce a block to get the reward.

**Comment by stefhenry** [comment]
ok thanks for the explanation 👍
