### ISSUE TITLE
"RPCError: Assert Exception" occurs.

### ISSUE THREAD

**Issue by ayogom** [steemit/steem#3178]
I get an error when I vote (used 50% voting power) as below.

```
RPCError: Assert Exception:(skip & skip_transaction_dupe_check) || trx_idx.indices().get<by_trx_id>().find(trx_id) == trx_idx.indices().get<by_trx_id>().end(): Duplicate transaction check failed
```

**Comment by mvandeberg** [comment]
For whatever reason, the interface you were using generated an identical transaction to a previous transaction you made. Steemd is working as intended. Please report the problem to the maintainer of the interface you are using.
