### ISSUE TITLE
Add Proposed Transactions with Chaining

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#318]
This feature would be similar to BitShares proposed transactions, with the added ability to approve a chain of transactions with a single confirmation.

**Comment by jcalfee** [comment]
This would make it easier to do multisig friend-to-friend account recovery.  ;)

**Comment by xeroc** [comment]
Can we have a slight different behavior when it comes to creating a proposal and approving it such that .. if the creator of the proposal is among the required account/key approvals, this approval is automatically added?
That makes the whole multisig scheme way more natural as you don't need to approve your own proposals anymore.

**Comment by theoreticalbts** [comment]
Before we go any further on this, we need to consider a few questions:

- AFAIK proposed transactions weren't used at all in BitShares, except where the blockchain required them to be used (e.g. for setting chain parameters).  Let's think about why nobody used them in BitShares, and why those reasons don't apply to Steem.

- Do we need to add anything to core consensus, or can we use custom ops? Basically a proposed tx is a no-op until it's got sufficient sigs.

- What is a chain of transactions, and what are the semantics and use cases for signing one?

**Comment by abitmore** [comment]
@theoreticalbts FYI proposed transactions are heavily used in BitShares right now, especially by multi-auth accounts, because it's supported in GUI (thanks to @svk31).

**Comment by svk31** [comment]
Just want to add that something that's holding proposed transactions back slightly in Bitshares, which is that the accounts that need to sign off on a transaction have no way of being notified that their signature is required.

Say you propose a transfer from A to B. Account A is 2/3 multi-sig requiring the signatures of C, D or E.

In Bitshares, for C, D and E to find the transaction to sign they need to access the account page of A, which works but is not intuitive. If you add this to Steem it would be great if accounts C, D, E could be notified directly of the proposed transaction they need to sign.

**Comment by abitmore** [comment]
Just a note, the issue @svk31 described was discussed here: https://github.com/cryptonomex/graphene/issues/442

**Comment by mvandeberg** [comment]
This can easily be implemented using a plugin to generate a query-able report of proposed transactions that can be signed by specific keys or accounts.

**Comment by mvandeberg** [comment]
It suffices to use custom json. Closing
