### ISSUE TITLE
Community - Allow designation of account recovery agent at account creation

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#3181]
Currently when a user create a new account for another user, whoever created the account is the account recovery agent. It can be changed, but it takes 30 days to go into effect. It would be beneficial to allow the creator to specify an alternate recovery agent at the time of account creation, so that other parties can step in and support the account recovery process without the user having to wait 30 days for their account to be safe.

**Comment by therealwolf42** [comment]
Great idea! Much needed.

**Comment by TimCliff** [comment]
If you change the recovery account, it takes 30 days before it goes into effect.

Here is the reason: assume Alice’s account is hacked. Alice needs to be able to initiate an account recovery to get her account back. If the hacker could immediately change the recovery account, then Alice would not be able to complete an account recovery.

**Comment by mvandeberg** [comment]
Closing and consolidating discussion on #3242
