### ISSUE TITLE
permlink.size() > STEEM_MIN_PERMLINK_LENGTH && permlink.size() < STEEM_MAX_PERMLINK_LENGTH: Permlink is not a valid size.

### ISSUE THREAD

**Issue by jmliz** [steemit/steem#3182]
Hi the server is telling me the error in the title while I'm trying to submit a post using [dsteem](https://github.com/steemit/dsteem) lib to steemit.

Full error object:

```
context:
file: "steem_evaluator.cpp"
hostname: ""
level: "error"
line: 50
method: "validate_permlink_0_1"
timestamp: "xxxxxxxxxx"
```

I'm trying to submit a permlink of size 59 bytes. For example:

`uytgfr6-aswer-asde-asdfg-aswe-aswqerdft-20181025t102537007z`

I see at the steem [config files](https://github.com/steemit/steem/blob/181099297954c86608744a956715753c937356f9/libraries/protocol/include/steem/protocol/config.hpp#L223) that the max permlink constant is 256 bytes. Then why am I getting the error?

**Comment by ArtoLabs** [comment]
jmliz, how did you resolve this issue? I am getting the same error using the hot signing feature via the steem connect website.

**Comment by jmliz** [comment]
Are you getting this error in steemresources again?

**Comment by jmliz** [comment]
@ArtoLabs parent_permlink must be the first tag of the post.
