### ISSUE TITLE
keep restarting

### ISSUE THREAD

**Issue by isamuelson** [steemit/steem#3183]
/tmp/core
 * Restarting FastCGI wrapper fcgiwrap
   ...done.
 * Restarting nginx nginx
   ...done.
 * Restarting FastCGI wrapper fcgiwrap
2018/11/28 14:02:58 [crit] 67#67: *1 connect() to unix:/var/run/fcgiwrap.socket failed (2: No such file or directory) while connecting to upstream, client: 10.76.101.2, server: , request: "GET /health HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "10.233.66.110:8090"
10.76.101.2 - - [28/Nov/2018:14:02:58 +0000]  "GET /health HTTP/1.1" 502 166 |"-"| "kube-probe/1.12"
   ...done.
 * Restarting nginx nginx
   ...done.
2018/11/28 14:03:08 [error] 224#224: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "POST / HTTP/1.1", upstream: "http://127.0.0.1:8091/", host: "localhost:8090"
2018/11/28 14:03:08 [error] 224#224: *1 FastCGI sent in stderr: "parse error: Invalid numeric literal at line 1, column 7" while reading response header from upstream, client: 10.76.101.2, server: , request: "GET /health HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "10.233.66.110:8090"
10.76.101.2 - - [28/Nov/2018:14:03:08 +0000]  "GET /health HTTP/1.1" 502 49 |"-"| "kube-probe/1.12"
 * Restarting FastCGI wrapper fcgiwrap
2018/11/28 14:03:18 [crit] 224#224: *5 connect() to unix:/var/run/fcgiwrap.socket failed (2: No such file or directory) while connecting to upstream, client: 10.76.101.2, server: , request: "GET /health HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "10.233.66.110:8090"
10.76.101.2 - - [28/Nov/2018:14:03:18 +0000]  "GET /health HTTP/1.1" 502 166 |"-"| "kube-probe/1.12"
   ...done.
 * Restarting nginx nginx

   ...done.
 * Restarting FastCGI wrapper fcgiwrap

**Comment by isamuelson** [comment]
when running inside the container steemd
Illegal instruction (core dumped)

**Comment by isamuelson** [comment]
Duplicate of #2335

**Comment by mvandeberg** [comment]
What hardware are you running on?

**Comment by isamuelson** [comment]
via var /proc/cpuinfo

vendor_id       : GenuineIntel
cpu family      : 6
model           : 47
model name      : Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
stepping        : 2
microcode       : 0x37
cpu MHz         : 1064.000
cache size      : 30720 KB
physical id     : 3
siblings        : 20
core id         : 25
cpu cores       : 10
apicid          : 243
initial apicid  : 243
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt aes lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
bugs            : clflush_monitor cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4794.82
clflush size    : 64
cache_alignment : 64
address sizes   : 44 bits physical, 48 bits virtual
power management:

**Comment by mvandeberg** [comment]
There is some optimization we believe in RocksDB that is creating the illegal instruction on older architectures. The workaround right now would be to build the docker image yourself, which will cause the build options to match your hardware and should resolve the issue.

**Comment by isamuelson** [comment]
thanks, I was trying to do so, though it fails...i'll look more into it...is there any slack/telegram channel for more hands-on tech help?

**Comment by mvandeberg** [comment]
It is quitting with illegal instruction during the build process?

**Comment by isamuelson** [comment]
no 

quitting on

Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'

**Comment by mvandeberg** [comment]
That sounds like a connectivity issue. However, there have been no updates on this and no other similar reports, so I am closing the issue. If the problem persists, please open a new issue with current logging/errors.
