### ISSUE TITLE
Side-by-side post editor

### ISSUE THREAD

**Issue by dandv** [steemit/steem#3187]
<sub>Apologies for filing this in the wrong repo; please use the new "Transfer issue" GitHub feature to move this issue to [condenser](https://github.com/steemit/condenser).</sub>

I've been blogging for ~10 years and I've just joined Steem. Happy to see Markdown being used instead of a ["minimalist"](https://news.ycombinator.com/item?id=10820633) editor. It was hard though to have to scroll between the text and the rendered version all the time, since [my post](https://steemit.com/productivity/@dandv/the-best-productivity-hacks-from-15-years-of-practice) was quite a bit longer than one page.

Would it be useful to implement a side-by-side post editor? An excellent open-source implementation of this is @benweet's [StackEdit](https://github.com/benweet/stackedit), which is also easily [embeddable](https://github.com/benweet/stackedit#ecosystem).

![image](https://user-images.githubusercontent.com/33569/49350181-dbd1fc80-f662-11e8-853b-c87933322c38.png)

**Comment by scr53005** [comment]
Bună Dan, mă bucur să mai descopăr un compatriot în comunitate. Propunerea ta este foarte pertinenta. Steemit front-end este însă pe cale de a fi "deprecat". Compania vrea să se focalizeze pe blockchain și sa lase fron-endurile comunității de dApps. Cunoști busy.org, steeve.app sau steempeak.com ? Sunt trei front-enduri independente pe steem. Cel din urmă implementează un side-by-side editor dacă nu mă înșel. 
Cu bine

**Comment by wehmoen** [comment]
This is not the right repo for your suggestion @dandv 
Try it with the repo for condenser: https://github.com/steemit/condenser :)
