### ISSUE TITLE
need to change Chain_id from mainnet to testnet

### ISSUE THREAD

**Issue by prateektiwari7** [steemit/steem#3189]
Hello Guys 

Can anybody help me to connect with my private Steem chain ? I already created `config.in`i file and use the command that is `steemd -d path ` to run the chain but still I have chain_id as all zeros(mainet id).

My config.ini file 

```
rpc-endpoint = 127.0.0.1:9876
p2p-endpoint = 0.0.0.0:3333
p2p-seed-node = testnet.steemitdev.com:2001
shared-file-size = 1G
enable-stale-production = true
witness = "initminer"
private-key = 5JKVA1RMufcDpprpWmRsNVrkJtb3m3E8VbRUHdsVxC9CRxii2Z4
```

```
root@stmst:~/steem/programs/steemd# steemd -d eftg
1950764ms rc_plugin.cpp:1077            plugin_initialize    ] Initializing resource credit plugin
1950764ms rc_plugin.cpp:1125            plugin_initialize    ] RC's will be computed starting at block 26256743
1950764ms witness_plugin.cpp:467        plugin_initialize    ] Initializing witness plugin
1950764ms account_by_key_plugin.cpp:251 plugin_initialize    ] Initializing account_by_key plugin
1950765ms webserver_plugin.cpp:311      plugin_initialize    ] configured with 32 thread pool size
1950765ms webserver_plugin.cpp:343      plugin_initialize    ] configured http to listen on 127.0.0.1:9876
1950765ms webserver_plugin.cpp:349      plugin_initialize    ] configured ws to listen on 127.0.0.1:9876
------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.20.6
------------------------------------------------------
1950766ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
1950766ms chain_plugin.cpp:416          plugin_startup       ] Starting chain with shared_file_size: 1073741824 bytes
1950766ms chain_plugin.cpp:522          plugin_startup       ] Opening shared memory from /root/steem/programs/steemd/eftg/blockchain
1950766ms block_log.cpp:142             open                 ] Log is nonempty
1950766ms block_log.cpp:151             open                 ] Index is nonempty
1950768ms chain_plugin.cpp:536          plugin_startup       ] Started on blockchain with 697245 blocks
1950769ms p2p_plugin.cpp:646            operator()           ] Configuring P2P to listen at 0.0.0.0:3333
1950770ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 34.203.124.119:2001
1950770ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 54.175.98.100:2001
1965772ms p2p_plugin.cpp:681            operator()           ] P2P node listening at 0.0.0.0:3333
1965773ms p2p_plugin.cpp:683            plugin_startup       ] P2P Plugin started
1965773ms witness_plugin.cpp:515        plugin_startup       ] witness plugin:  plugin_startup() begin
1965773ms witness_plugin.cpp:520        plugin_startup       ] Launching block production for 1 witnesses.
1965773ms witness_plugin.cpp:531        plugin_startup       ] witness plugin:  plugin_startup() end
1965773ms webserver_plugin.cpp:122      operator()           ] start processing ws thread
1965773ms webserver_plugin.cpp:135      operator()           ] start listening for http requests
1965773ms webserver_plugin.cpp:138      operator()           ] start listening for ws requests
1986547ms database.cpp:2937             check_free_memory    ] Free memory is now 11G. Current block number: 697246
1987823ms chain_plugin.cpp:562          accept_block         ] Syncing Blockchain --- Got block: #700000 time: 2016-04-18T10:03:27 producer: tombstone
1994282ms chain_plugin.cpp:562          accept_block         ] Syncing Blockchain --- Got block: #710000 time: 2016-04-18T18:48:09 producer: recursive25
1996037ms p2p_plugin.cpp:229            handle_block         ] Error when pushing block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":712258,"head":712564,"max_size":22}
    fork_database.cpp:57 _push_block

    {}
    database.cpp:787 _push_block

    {"new_block":{"previous":"000ade4148804c451e54b61906bfedc2049932fd","timestamp":"2016-04-18T20:42:42","witness":"lionsgate","transaction_merkle_root":"db6a21f67b508dacf6aa966f95d65a00054707fc","extensions":[],"witness_signature":"1f7cd5049517eba1f579f0c4c7a018d988ba23c3ce587cddb70dc2cb01f022ebf943e653d0159dc76e941bc18f8dca03d088a7266505cbfc3288cf5dcd685db56c","transactions":[{"ref_block_num":56897,"ref_block_prefix":1162641480,"expiration":"2016-04-18T20:43:09","operations":[{"type":"transfer_operation","value":{"from":"tombstone76","to":"dele-puppy","amount":{"amount":"150","precision":3,"nai":"@@000000021"},"memo":""}}],"extensions":[],"signatures":["201ce61898f87977581217403ff8991fc7b3aae9fc3d45aca01733b5cc049ed29c5002210ee8c655da5889d0674551d50d11b45766b97ca64329d635d92308c757"]}]}}
    database.cpp:671 operator()
1996066ms p2p_plugin.cpp:229            handle_block         ] Error when pushing block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":712350,"head":712637,"max_size":22}
    fork_database.cpp:57 _push_block

    {}
    database.cpp:787 _push_block

```

I need to change the chain_id to my private net . I already changed seed.txt file

**Comment by mvandeberg** [comment]
https://steemit.com/hardfork20/@steemitdev/hardfork-20-testnet-details

This has brought to my attention the fact that we need to replicate our testnet documentation in this repo.

**Comment by prateektiwari7** [comment]
Then how I add the specific producer to produce testnet blocks? 

`p2p-seed-node = testnet.steemitdev.com:2001`

I got this 

`            STARTING TEST NETWORK

------------------------------------------------------
initminer public key: TST6LLegbAgLAy28EHrffBVuANFWcFgmqRMW13wBmTExqFE9SCkg4
initminer private key: 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n
blockchain version: 0.21.0
------------------------------------------------------
2976924ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
2976924ms chain_plugin.cpp:416          plugin_startup       ] Starting chain with shared_file_size: 12884901888 bytes
2976924ms chain_plugin.cpp:522          plugin_startup       ] Opening shared memory from /root/test-data/./blockchain
2976924ms block_log.cpp:142             open                 ] Log is nonempty
2976924ms block_log.cpp:151             open                 ] Index is nonempty
2976941ms chain_plugin.cpp:536          plugin_startup       ] Started on blockchain with 109516 blocks
2976943ms p2p_plugin.cpp:646            operator()           ] Configuring P2P to listen at 0.0.0.0:2001
2976943ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 54.175.98.100:2001
2976943ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 34.203.124.119:2001
2976944ms p2p_plugin.cpp:681            operator()           ] P2P node listening at 0.0.0.0:2001
2976944ms p2p_plugin.cpp:683            plugin_startup       ] P2P Plugin started
2976945ms witness_plugin.cpp:515        plugin_startup       ] witness plugin:  plugin_startup() begin
2976945ms witness_plugin.cpp:520        plugin_startup       ] Launching block production for 1 witnesses.
2976945ms witness_plugin.cpp:531        plugin_startup       ] witness plugin:  plugin_startup() end
2976945ms webserver_plugin.cpp:156      operator()           ] start processing http thread
2976945ms webserver_plugin.cpp:122      operator()           ] start processing ws thread
2976945ms webserver_plugin.cpp:166      operator()           ] start listening for http requests
2976945ms webserver_plugin.cpp:138      operator()           ] start listening for ws requests
3018005ms database.cpp:2937             check_free_memory    ] Free memory is now 10G. Current block number: 109517
3021004ms chain_plugin.cpp:562          accept_block         ] Syncing Blockchain --- Got block: #110000 time: 2018-10-16T09:16:00 producer: init-8`

**Comment by prateektiwari7** [comment]
@mvandeberg I need to create my private chain in steem blockchain.
