### ISSUE TITLE
Assert Exception in get_witness command

### ISSUE THREAD

**Issue by prateektiwari7** [steemit/steem#3193]
Hello I build the private steem network with one peer. 

Here is the output 

   ```
       STARTING STEEM NETWORK


initminer public key: EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf
chain id: b3f32f410037a129b990f29230698048fe895e23e7dc297fd6f6e9d167a62571
blockchain version: 0.20.6

1744336ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
1744337ms chain_plugin.cpp:416          plugin_startup       ] Starting chain with shared_file_size: 1073741824 bytes
1744337ms chain_plugin.cpp:522          plugin_startup       ] Opening shared memory from /root/steem/build/eftg/blockchain
1744337ms block_log.cpp:142             open                 ] Log is nonempty
1744337ms block_log.cpp:151             open                 ] Index is nonempty
1744337ms chain_plugin.cpp:536          plugin_startup       ] Started on blockchain with 1732 blocks
1744338ms p2p_plugin.cpp:646            operator()           ] Configuring P2P to listen at 0.0.0.0:3333
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 52.207.85.82:2001
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 54.252.214.47:2001
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 52.74.152.79:2001
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 162.213.199.171:34191
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 66.70.181.184:2001
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 204.12.248.146:12150
1744339ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 45.77.136.107:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 185.183.182.147:2016
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 51.254.67.207:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 147.135.11.74:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 94.130.48.111:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 5.9.18.213:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 163.172.190.33:2001
1744340ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 173.208.146.132:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 195.154.80.121:40696
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.14.144:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.13.30:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.24.247:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 104.199.118.92:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 195.201.197.118:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 88.99.165.91:2001
1744341ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 173.249.47.125:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 136.243.101.205:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.40.109:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 88.99.151.145:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 195.154.82.127:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 148.251.237.104:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 85.10.198.243:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.3.171:2001
1744342ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 89.163.146.180:2001
1744343ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 64.118.64.145:2001
1744343ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 95.216.3.114:2001
1744343ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 129.232.204.82:2001
1744343ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 144.217.71.190:2001
1744343ms p2p_plugin.cpp:654            operator()           ] P2P adding seed node 94.130.238.244:2001
1764347ms p2p_plugin.cpp:681            operator()           ] P2P node listening at 0.0.0.0:3333
1764347ms p2p_plugin.cpp:683            plugin_startup       ] P2P Plugin started
1764348ms witness_plugin.cpp:515        plugin_startup       ] witness plugin:  plugin_startup() begin
1764348ms witness_plugin.cpp:520        plugin_startup       ] Launching block production for 1 witnesses.
1764348ms witness_plugin.cpp:531        plugin_startup       ] witness plugin:  plugin_startup() end
1764348ms webserver_plugin.cpp:122      operator()           ] start processing ws thread
1764348ms webserver_plugin.cpp:135      operator()           ] start listening for http requests
1764348ms webserver_plugin.cpp:138      operator()           ] start listening for ws requests
1764400ms witness_plugin.cpp:331        block_production_loo ] Generated block #1733 with timestamp 2018-12-07T13:29:24 at time 2018-12-07T13:29:24
1766608ms witness_plugin.cpp:331        block_production_loo ] Generated block #1734 with timestamp 2018-12-07T13:29:27 at time 2018-12-07T13:29:27
1769608ms witness_plugin.cpp:331        block_production_l
```

But when I fire the command 

`unlocked >>> get_witness initminer
get_witness initminer
1286156ms websocket_api.cpp:102         on_message           ] message: {"jsonrpc":"2.0","result":{"id":0,"owner":"initminer","created":"1970-01-01T00:00:00","url":"","votes":0,"virtual_last_update":"0","virtual_position":"0","virtual_scheduled_time":"340282366920938463463374607431768211455","total_missed":0,"last_aslot":28451228,"last_confirmed_block_num":1619,"pow_worker":0,"signing_key":"EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf","props":{"account_creation_fee":"0.030 STEEM","maximum_block_size":131072,"sbd_interest_rate":1000,"account_subsidy_budget":797,"account_subsidy_decay":347321},"sbd_exchange_rate":{"base":"0.000 STEEM","quote":"0.000 STEEM"},"last_sbd_exchange_update":"1970-01-01T00:00:00","last_work":"0000000000000000000000000000000000000000000000000000000000000000","running_version":"0.20.6","hardfork_version_vote":"0.0.0","hardfork_time_vote":"1970-01-01T00:00:00","available_witness_account_subsidies":1465593},"id":3} 
10 assert_exception: Assert Exception
false: Cannot parse asset symbol
    {}
    condenser_api_legacy_asset.cpp:58 string_to_asset_num`

and when I fire command I get 

'unlocked >>> **create_account_with_keys_delegated initminer "5.000 EFTG" "50000.000000 VESTS" alice "{}" EUR5UoqDENemtP3ZXdE7SnpwFSWkcg3ixEbs72A4gSAgJzRZCK4FC EUR6iLKqL8mcWw51infttQci5vRQrSdt5HUNhu3ojLj2eaXpQCDW7 EUR6fm7XzYauCTF54tgbge5jnX8Xox1RNZYJQNA6mq3FJjzjuR3no EUR5fcWoaMAjfjYVuce52AG2gEdXeacZdBk9nrt51Lhdwg3XSw84t true**

create_account_with_keys_delegated initminer "5.000 EFTG" "50000.000000 VESTS" alice "{}" EUR5UoqDENemtP3ZXdE7SnpwFSWkcg3ixEbs72A4gSAgJzRZCK4FC EUR6iLKqL8mcWw51infttQci5vRQrSdt5HUNhu3ojLj2eaXpQCDW7 EUR6fm7XzYauCTF54tgbge5jnX8Xox1RNZYJQNA6mq3FJjzjuR3no EUR5fcWoaMAjfjYVuce52AG2gEdXeacZdBk9nrt51Lhdwg3XSw84t true
1961381ms websocket_api.cpp:102         on_message           ] message: {"jsonrpc":"2.0","result":[{"id":3,"name":"initminer","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf",1]]},"memo_key":"EUR8PsyH8FSX7VPKg3ecKLD4khpkrUTYLJeWYcN8h2fJyhVnd1iHf","json_metadata":"","proxy":"","last_owner_update":"1970-01-01T00:00:00","last_account_update":"1970-01-01T00:00:00","created":"1970-01-01T00:00:00","mined":true,"recovery_account":"","last_account_recovery":"1970-01-01T00:00:00","reset_account":"null","comment_count":0,"lifetime_vote_count":0,"post_count":0,"can_vote":true,"voting_manabar":{"current_mana":0,"last_update_time":1544189559},"voting_power":0,"balance":"0.000 STEEM","savings_balance":"0.000 STEEM","sbd_balance":"0.000 SBD","sbd_seconds":"0","sbd_seconds_last_update":"1970-01-01T00:00:00","sbd_last_interest_payment":"1970-01-01T00:00:00","savings_sbd_balance":"0.000 SBD","savings_sbd_seconds":"0","savings_sbd_seconds_last_update":"1970-01-01T00:00:00","savings_sbd_last_interest_payment":"1970-01-01T00:00:00","savings_withdraw_requests":0,"reward_sbd_balance":"0.000 SBD","reward_steem_balance":"0.000 STEEM","reward_vesting_balance":"0.000000 VESTS","reward_vesting_steem":"0.000 STEEM","vesting_shares":"0.000000 VESTS","delegated_vesting_shares":"0.000000 VESTS","received_vesting_shares":"0.000000 VESTS","vesting_withdraw_rate":"0.000001 VESTS","next_vesting_withdrawal":"2106-02-07T06:28:15","withdrawn":0,"to_withdraw":0,"withdraw_routes":0,"curation_rewards":0,"posting_rewards":0,"proxied_vsf_votes":[0,0,0,0],"witnesses_voted_for":0,"last_post":"1970-01-01T00:00:00","last_root_post":"1970-01-01T00:00:00","last_vote_time":"1970-01-01T00:00:00","post_bandwidth":0,"pending_claimed_accounts":0,"vesting_balance":"0.000 STEEM","reputation":0,"transfer_history":[],"market_history":[],"post_history":[],"vote_history":[],"other_history":[],"witness_votes":[],"tags_usage":[],"guest_bloggers":[]}],"id":1} 
10 assert_exception: Assert Exception
false: Cannot parse asset symbol
    {}
    condenser_api_legacy_asset.cpp:58 string_to_asset_num

    {"from":"0.000 STEEM"}
    condenser_api_legacy_asset.cpp:175 from_string

    {"creator":"initminer","new_account_name":"alice","json_meta":"{}","owner":"EUR5UoqDENemtP3ZXdE7SnpwFSWkcg3ixEbs72A4gSAgJzRZCK4FC","active":"EUR6iLKqL8mcWw51infttQci5vRQrSdt5HUNhu3ojLj2eaXpQCDW7","memo":"EUR5fcWoaMAjfjYVuce52AG2gEdXeacZdBk9nrt51Lhdwg3XSw84t","broadcast":true}
    wallet.cpp:1289 create_account_with_keys_delegated'

please help me

**Comment by mvandeberg** [comment]
The wallet and steemd both need to be built for testnet.

**Comment by prateektiwari7** [comment]
it is built over mainnet with my chain Id. I edited chain id in config.hpp file and changes Public key to my key.

**Comment by prateektiwari7** [comment]
I am following this tutorial https://steemit.com/utopian-io/@jga/the-user-guide-for-a-newbie-on-how-to-build-a-private-steem-blockchain-for-corporate-projects

**Comment by SirVeryBritish** [comment]
@prateektiwari7 If you've found the solution, can you post it here? I'm facing a similar issue.
