### ISSUE TITLE
Disabled curation rewards return to reward pool - bug or feature?

### ISSUE THREAD

**Issue by hrosspet** [steemit/steem#3195]
I was looking into the code how rewards work for comments with disabled curation rewards (`allow_curation_rewards = false`) and found a potential bug.

It all comes down to this line of code, which sets all curation rewards to 0 if allow_curation_rewards is false:
https://github.com/steemit/steem/blob/7ebe3f8bddf9e58c943618f55136db6330dd95a0/libraries/chain/database.cpp#L1712

As I understand it, this means the curation rewards go back to the rewards pool. Is this an intended behavior, or a bug?

Thanks for clarification.

**Comment by mvandeberg** [comment]
Intended behavior. Authors should not be able to profit by not allowing curation rewards.
