### ISSUE TITLE
Increase STEEMIT_IRREVERSIBLE_THRESHOLD

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#320]
As part of #319 I checked the actual value of `STEEMIT_IRREVERSIBLE_THRESHOLD`. It is 51%.   As noted in #319, increasing `STEEMIT_IRREVERSIBLE_THRESHOLD` is necessary to safeguard against misbehaving witnesses (either due to bug, misconfiguration or malice).  I propose increasing this number to 80%.

Transactions will take slightly longer to get irreversible status, but increase safety for e.g. exchanges.  If #319 is implemented, this will not matter too much, as this should improve operating latency to 2-3 blocks when at least STEEMIT_IRREVERSIBLE_THRESHOLD witnesses are up.

**Comment by bytemaster** [comment]
67% is the threshold indicated by byzantine generals

**Comment by theoreticalbts** [comment]
Citation for 67% number?

**Comment by theoreticalbts** [comment]
The intention here is for the blockchain to continue as long as 14 of the 19 elected witnesses are signing off.  The numbers need to be set so that this happens.

**Comment by theoreticalbts** [comment]
14 / 19 elected witnesses signing off -> 16 / 21 of slots signing off; i.e. we tolerate at most 5 failures.  Considering a situation like this:

    0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
    1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2

we need to set last irreversible block to 1, but if the 5 slot changes to 2 then we should set it to 2.  So the critical slot is 5, calculated as `offset` by [this line](https://github.com/steemit/steem/blob/6500bb65eb6282866f3c6f356cbcbe09fd03c7bf/libraries/chain/database.cpp#L3196).  This means that, in order to implement the 5-failures-ok, stop-for-6 intent, we need to set STEEMIT_IRREVERSIBLE_THRESHOLD between 71.42% and 76.19% (inclusive); setting to 75% is a nice round number in this range.

**Comment by theoreticalbts** [comment]
Merged.
