### ISSUE TITLE
Error on submit when using Dtube

### ISSUE THREAD

**Issue by marlon99rocks** [steemit/steem#3206]
I get the following issue when trying to submit a video on Dtube: permlink.size() > STEEM_MIN_PERMLINK_LENGTH && permlink.size() < STEEM_MAX_PERMLINK_LENGTH: Permlink is not a valid size.

Any help or advice would be greatly appreciated.

**Comment by igormuba** [comment]
This is most likely a DTube issue, though, looking at their guthub I couldn't find the issue

The file that makes the permlink is https://github.com/dtube/dtube/blob/16b5380d5756c4c6d3c0b8dbd23220b2f077c890/client/views/pages/upload/upload.js

And the function is on line 13

And it is called by the file
https://github.com/dtube/dtube/blob/2436a8ddcbc91979297a74390847113b104335f7/client/views/pages/upload/uploadform/uploadform.js
at line 73

Maybe it is an error on your side? what are the actions you are taking when uploading? how is the process?

**Comment by mvandeberg** [comment]
This is not a bug with the Steem Blockchain. Please contact the developers of DTube with your issue.
