### ISSUE TITLE
get_block returning Invalid cast from object_type to Array

### ISSUE THREAD

**Issue by Crypto2** [steemit/steem#3212]
Using steemd + cli_wallet, when I request blocks I'm getting this error.

Full error message:

RPC ERROR: {"id":1,"error":{"code":1,"message":"7 bad_cast_exception: Bad Cast\nInvalid cast from object_type to Array\n    {\"type\":\"object_type\"}\n    variant.cpp:537 get_array\n\n    {\"call.method\":\"get_block\",\"call.params\":[28704070]}\n    http_api.cpp:116 on_request","data":{"code":7,"name":"bad_cast_exception","message":"Bad Cast","stack":[{"context":{"level":"error","file":"variant.cpp","line":537,"method":"get_array","hostname":"","timestamp":"2018-12-19T16:17:32"},"format":"Invalid cast from ${type} to Array","data":{"type":"object_type"}},{"context":{"level":"warn","file":"http_api.cpp","line":116,"method":"on_request","hostname":"","timestamp":"2018-12-19T16:17:32"},"format":"","data":{"call.method":"get_block","call.params":[28704070]}}]}}}

**Comment by mvandeberg** [comment]
Is the `block_api` enabled on the endpoint you are connecting to?

**Comment by mvandeberg** [comment]
Can you curl your endpoint to make sure it is sending the correct response?

`curl -d '{"jsonrpc":"2.0", "method":"call", "params":["block_api", "get_block", [28704070]], "id":1}' ENDPOINT`

**Comment by Crypto2** [comment]
Doing that I get a different error:

curl -d '{"jsonrpc":"2.0", "method":"call", "params":["block_api", "get_block", [28704070]], "id":1}' http://ENDPOINT/

{"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_local_apis.size() > api_id: \n    {}\n    api_connection.hpp:233 receive_call\n\n    {\"call.method\":\"call\",\"call.params\":[\"block_api\",\"get_block\",[28704070]]}\n    http_api.cpp:116 on_request","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api_connection.hpp","line":233,"method":"receive_call","hostname":"","timestamp":"2018-12-19T19:52:25"},"format":"_local_apis.size() > api_id: ","data":{}},{"context":{"level":"warn","file":"http_api.cpp","line":116,"method":"on_request","hostname":"","timestamp":"2018-12-19T19:52:25"},"format":"","data":{"call.method":"call","call.params":["block_api","get_block",[28704070]]}}]}}}

**Comment by mvandeberg** [comment]
What version of Steem is the endpoint running?

**Comment by mvandeberg** [comment]
Are your curling the wallet endpoint or the steemd endpoint?

The error being reported contains stack trace information from older API code that is only used in the wallet. The error could not have come from a recent version of steemd.

**Comment by Crypto2** [comment]
Yep, it's cli_wallet. It's been working fine for years not sure why it's not now.

**Comment by mvandeberg** [comment]
Can you curl the steemd endpoint that the wallet is connecting to?

**Comment by mvandeberg** [comment]
If you are querying the wallet, you should need to query against `wallet_api`, not `block_api`.
