### ISSUE TITLE
STEEM account recovery is not working

### ISSUE THREAD

**Issue by ayogom** [steemit/steem#3213]
Hello guys,

I received an account recovery email from Steem yesterday.
I requested recovery.
But I didn't get a response as I thought.

This is another user's account recovery history.
> https://steemd.com/@whatissteem?page=6

According to his records,
1. whatissteem request_account_recovery at 2016-07-23 08:48:09 (UTC)
![image](https://user-images.githubusercontent.com/40152930/50253868-37f09b00-042f-11e9-9e26-ed6bc0acf8bc.png)

2. whatissteem recover_account at 2016-07-23 08:48:15 (UTC)
![image](https://user-images.githubusercontent.com/40152930/50253927-72f2ce80-042f-11e9-9dc1-a0fc908e0644.png)

3. whatissteem update account data (show details) at 2016-07-23 08:48:18 (UTC)
![image](https://user-images.githubusercontent.com/40152930/50253956-91f16080-042f-11e9-88d6-7115e88ea0f0.png)

The time information above took 6 and 3 seconds each.
I don't think it was manipulated by the user. It's probably been restored according to the mechanism.

This time I show you my record.
>https://steemd.com/@sallyfun

![image](https://user-images.githubusercontent.com/40152930/50254117-3673a280-0430-11e9-8a6c-799cb63da9fd.png)

2018-12-19 06:53:30 (UTC)
2018-12-19 08:04:45 (UTC)
2018-12-19 08:16:36 (UTC)

I sent you(steem?) a request for three times, but there was no response.
Is there anything I am making a mistake?
Or was the feature turned off to save money in STINC?

**Comment by mvandeberg** [comment]
Thank you for the bug report. There should be a fix up already. Please try again and let us know if you still experience problems.

**Comment by ayogom** [comment]
I have completed account recovery. Thank you
