### ISSUE TITLE
[HELP] Steem private net + voting on post gets no reward

### ISSUE THREAD

**Issue by yashbhavsar007** [steemit/steem#3219]
i have own setup of steem private net but the issue is when i vote on post from initminer's key i get total_vote_weight on post but when another user vote on post total_vote_weight of post does not increasing,

**Comment by mvandeberg** [comment]
How much STEEM Power does the account have that you are trying to vote with?

**Comment by inertia186** [comment]
Does "steem private net" mean testnet?  Is there are current price feed?

**Comment by yashbhavsar007** [comment]
Closing this issue and thanks for response guys @mvandeberg  i was having 0.04253 vests in my vesting_shares that's why it was not increasing i have given 3000000 steem to vesting after that i am able to share my weights for post.
Still have some confusion what is minimum vesting share required for this ?
and how to calculate post's value from total_vote_weight ?

**Comment by yashbhavsar007** [comment]
@inertia186  thanks for reply,i have steem's private net setup not testnet !
