### ISSUE TITLE
get_follow_count returns wrong value and get_followxxx returns chronologically 

### ISSUE THREAD

**Issue by economicstudio** [steemit/steem#3222]
Maybe there is some migration going on now (related to https://steemit.com/steemit/@steemitdev/upcoming-changes-to-api-steemit-com), but currently

- there are some accounts that get_follow_count returns the wrong value, e.g., https://steemit.com/@bukio/followed (38 but it should be zero) (I also checked with API call)

- get_followers/ing return the results chronologically 
should better return alphabetically as before (unless the change is notified very clearly) I believe in hive this will be an easy fix.

**Comment by roadscape** [comment]
Hi, thanks for the report. This is indeed related to those changes; could you please file this at https://github.com/steemit/hivemind/issues for discussion?

**Comment by economicstudio** [comment]
Sure, by the way, could you check my new pull request? Thanks.
