### ISSUE TITLE
Delete sneak@steemit.com in CONTRIBUTING.md

### ISSUE THREAD

**Issue by stratos-steem** [steemit/steem#3232]
In CONTRIBUTING.md:

> # Enhancement Suggestions

> Do not use the issue tracker to suggest enhancements or improvements to the platform. The best place for these discussions is on Steemit.com. If there is a well vetted idea that has the support of the community that you feel should be considered by the development team, please email it to sneak@steemit.com for review.

I tried to email sneak@steemit.com but believe the email is no longer active and able to receive mail. If you would give me info about what needs to be in the place of sneak@steemit.com in the file I can update in a pull request.

**Comment by stratos-steem** [comment]
Since this has not been responded to, I guess I'll just do it and create a pull request.

**Comment by ausbitbank** [comment]
Please do - replace it with support@steemit.com :)
