### ISSUE TITLE
SIP - Allow account to decline Voting Rights 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#324]
The update would allow any account to permanently revoke its voting rights after a 7 day waiting period.  This feature could be used by @steemit to create a binding contract with the community that the account could not be used to:

1. take control of witness queue 
2. take control of all content rewards 

This feature could be used by any account that wanted to avoid the political and regulatory liability of having power / influence over the network.

This requires one operation to revoke and/or cancel the request.  The delay is there to allow hacked accounts an opportunity to recover.

**Comment by xeroc** [comment]
Could you specify the term *vote*? You talking about

* DPOS/witness voting,
* curation, or
* both of the above?

**Comment by abitmore** [comment]
Permanently? What's the use case?

**Comment by bytemaster** [comment]
This applies to both DPOS and curation.

We are moving it to a 30 day waiting period to match recovery window.

**Comment by arhag** [comment]
> We are moving it to a 30 day waiting period to match recovery window

Good. Also make sure the operation that initiates the request requires owner authority.

**Comment by iamsmooth** [comment]
Of course, such a powerful account could still move stake to a new account and take over the system (with an obvious time delay, but it wouldn't necessarily take the entire two years to move "sufficient" stake to achieve practical control).

Perhaps this change satisfies regulatory concerns (I can't say) but economically there is no substitute for actually distributing the stake.

**Comment by mvandeberg** [comment]
Implemented and tested

**Comment by asuleymanov** [comment]
Greetings.
I understand that this has long been done and hardly anyone will remember.
But let me ask the question.
Is it possible to restore voting control after the decline_voting_rights operation?

**Comment by quetzalcoatl** [comment]
They said `permanently` all the time, so I doubt it.
