### ISSUE TITLE
I can not find Owner Private Key in steemit.com

### ISSUE THREAD

**Issue by ayogom** [steemit/steem#3244]
As you know, I can not see the owner's private key on the permissions page.
> https://steemit.com/@ayogom/permissions

Can I find it?
I do not want to use the master key, but because I do not know my owner's private key, I will continue to use it.

**Comment by Gandalf-the-Grey** [comment]
Using `cli_wallet`:
`get_private_key_from_password ayogom owner YourMasterPassword`

**Comment by ayogom** [comment]
> Using `cli_wallet`:
> `get_private_key_from_password ayogom owner YourMasterPassword`

I wanted a way for ordinary users to know.
and I found a way to check it at steemworld.com.
