### ISSUE TITLE
missing time field in vote details

### ISSUE THREAD

**Issue by economicstudio** [steemit/steem#3245]
steemd doesn't show time in vote details. neither does wgt% (which I don't care though :)

![](https://user-images.githubusercontent.com/38183982/52167979-c9844580-271b-11e9-90f6-0b5a917291e3.png)
> https://steemd.com/utopian-io/@blockchainstudio/busy-3-new-features-and-2-bug-fixes-powerdown-information-zero-payout-3-digit-precision-etc

steempeak and esteem surfer have the same problem.

Interestingly, if I use `condenser_api.get_content` or `condenser_api.get_active_votes` manually, then time field is there correctly. esteem surfer seems to use dsteem. Others I don't know. Probably dsteem or any wrapper library problem?

**Comment by roadscape** [comment]
This is a hive issue, discussion here: https://github.com/steemit/hivemind/issues/161

**Comment by economicstudio** [comment]
@roadscape Thanks!
