### ISSUE TITLE
Instant logout when using active key on steemit.com

### ISSUE THREAD

**Issue by AndaBlackWidow** [steemit/steem#3249]
Tested on two different accounts using Firefox Quantum 64.0 (incognito with heavy privacy oriented settings) and Chrome 72.0.3626.109 (default settings).
Steps:
 - open https://steemit.com/@andablackwidow/transfers
 - log in using active key
 - for a brief moment the button to claim rewards shows up but the page quickly reloads and I'm logged out before I can do anything
In the end after several failed attempts on steemit I claimed rewards using eSteem Mobile.

**Comment by mvandeberg** [comment]
This issue should be made in the [Condenser](https://github.com/steemit/condenser) repo.
