### ISSUE TITLE
SIP - Allow post to split author rewards with another account

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#325]
With this feature a posts' author reward could be shared between two accounts.  The website that generates the transaction to submit the post to the blockchain would configure the post to pay a commission to the service provider. 

Users of a particular website would then agree to share revenue earned on their posts.

With this model in place, it creates a market for competing sites to steemit.com to pop up where they can earn income from the content generated by their users.

This process would be almost completely transparent to the users (existing in the Terms of Service) of the website operator.

**Comment by abitmore** [comment]
This feature is somehow similar to what I requested in #251, but looks like more complicated. In this proposal, site owners should construct special operations/transactions? If it's the case, it's probably easy to be bypassed by "technical" authors. Competition without any barrier is not so good.

**Comment by iamsmooth** [comment]
@abitmore I think you are misunderstanding the goal of this feature, it is not to tie a user account to a web site (which as you point out is easily bypassed), it is to monetize actual use of the web site itself. So for example, I could take my exiting account and start using another non-steemit.com web site if I find it adds enough value (features) to me that I want to give up a (presumably small, but not necessarily) slice of rewards.

**Comment by mvandeberg** [comment]
Usurped by #773
