### ISSUE TITLE
Symbolic "@At sign" (/@u/ in URL) breaks legitimate documentation links.

### ISSUE THREAD

**Issue by payingattention** [steemit/steem#3250]
For example (please know it was my first personal encounter with this specific problem/error/bug, I did not know what to say and important error-proving time passed ~~[should I have just said someAtSign {camelcase (slowly? {Or just spit the word, if it's important to tell?})}?]~~), add your Steem profile URL to your Github profile and watch the About Text Field Parser just throw a fit. (Spoiler/Hint: Turns https://steemd.com/@scribe to `https://steemd.com/&#64;scribe` and does not even politely warn in error).

Escalating deeper ~~, my second experience (I was not ready, even after the first problem error bug, but I could read now, at least, I knew the "@" now, felt readable),~~ into the alarming [symbol_swearing issue](https://en.wiktionary.org/wiki/Appendix:Symbol_swearing), https://github.com/neo-project/docs/blame/127663900e1e9f1c5cafc7fce19c1a3cf7caedc1/en-us/basic/about.md#L53 (http://web.archive.org/web/20190217221720/https://github.com/neo-project/docs/blame/127663900e1e9f1c5cafc7fce19c1a3cf7caedc1/en-us/basic/about.md, http://web.archive.org/web/20190217200137/https://docs.neo.org/en-us/basic/about.html) is being read egregiously, ~~just shocking if I might say so myself I do not even want to ask or even know how that happens in this day and age with modern computers and artificial intelligence (do we need another _NASA Challenger_ before we all can agree to talk seriously about usernames?),~~ as a "mailto:" HTML code and not as a normal link text.

Should we advise/suggest the Documentation Generators change protocol (and what about Github, who agrees to host us from their heart, and does not have time for our "[syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar)" @sign syntax issues), or give an alternative at-sign (+? [`/u` would make sense _***with***_ `@u`, and maybe `+u`.]) in case of the issue?

Further, I think I remember Twitter adding username redirects from `@username` to `/username` before (public support issue ticket not found) nearly becoming a standard (https://www.google.com/search?q="w3.org+username+standards" only has https://serverfault.com/questions/348912/best-practices-in-username-standards-avoiding-problems being why I said 'nearly', to be kind about that being _undetermined_) specification ~~for~~ from the same reasons.

~~Legal Disclaimer: I used/worked with https://en.wikipedia.org/wiki/Symbolic_link before and may have been influenced by that "symlink" terminology in writing/coding the title for our issue.~~

**Comment by mvandeberg** [comment]
This issue should be made in the [Condenser](https://github.com/steemit/condenser) repo.

The `@username` notation does not exist as a part of the blockchain protocol itself, but is an application layer notation.
