### ISSUE TITLE
I Want My network

### ISSUE THREAD

**Issue by isaack0329** [steemit/steem#3252]
------------------------------------------------------

            STARTING TEST NETWORK

------------------------------------------------------
initminer public key: MUR8H6FBe5DRsDcXGxpmh2ypPbKTXiM5v711oNx1SC8pjszj6LrQA
initminer private key: 5K5ZyFA5NqiBzCbiaTh5KYJmSh7dXdk65DvGkcx9G6ydsj83TM1
blockchain version: 0.21.0
------------------------------------------------------
1755777ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
1755777ms chain_plugin.cpp:405          plugin_startup       ] Starting chain with shared_file_size: 57982058496 bytes
1755777ms chain_plugin.cpp:511          plugin_startup       ] Opening shared memory from /platform/steem/build/./blockchain
1755782ms database.cpp:170              open                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE: unknown key
unknown key:
    {"what":"unknown key"}
    database.cpp:571 get_hardfork_property_object

    {}
    database.cpp:2957 init_genesis
1755782ms database.cpp:170              open                 ] args.data_dir: /platform/steem/build/./blockchain args.shared_mem_dir: /platform/steem/build/./blockchain args.shared_file_size: 57982058496
1755782ms chain_plugin.cpp:520          plugin_startup       ] Error opening database. If the binary or configuration has changed, replay the blockchain explicitly. Error: {"code":13,"name":"N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE","message":"unknown key","stack":[{"context":{"level":"warn","file":"database.cpp","line":571,"method":"get_hardfork_property_object","hostname":"","timestamp":"2019-02-27T10:29:15"},"format":"${what}: ","data":{"what":"unknown key"}},{"context":{"level":"warn","file":"database.cpp","line":2957,"method":"init_genesis","hostname":"","timestamp":"2019-02-27T10:29:15"},"format":"","data":{}},{"context":{"level":"warn","file":"database.cpp","line":170,"method":"open","hostname":"","timestamp":"2019-02-27T10:29:15"},"format":"rethrow","data":{"args.data_dir":"/platform/steem/build/./blockchain","args.shared_mem_dir":"/platform/steem/build/./blockchain","args.shared_file_size":"57982058496"}}]}

**Comment by LeoCornelius** [comment]
what is the  git repo of your fork?

**Comment by mvandeberg** [comment]
There have been no responses to this issue in several months. Closing.
