### ISSUE TITLE
Improvement of curation system (professional curation)

### ISSUE THREAD

**Issue by ayogom** [steemit/steem#3267]
This issue is mentioned in the post below.
https://steemit.com/kr/@good21/--1553430262799

We propose a professional curation system.
Basically I think we are curators. However, there are low quality authors for compensation in steemit. For developing STEEM, it should be divided into professional author and curator.

Users can distinguish their accounts as curators or authors. And it can be changed at any time.

1. An account defined as curation can receive higher rewards than cur- rent 25% rewards when doing curator activities. (For example, 66.7%)
And, when curators write, curators can not get compensation for writing.

2. The author takes a reward of about 33.3% and does not reward curation activities. he also zero the compensation for the curator who voted for my article. This is to prevent the form of making an upusing on each other.

Through specialized curation activities, high spa owners can receive continuous rewards, and authors can get enough rewards, so they can train better quality articles.

* we can adjust the compensation rate. (66.7% / 33.3%)

**Comment by mvandeberg** [comment]
I think this is better handled with SMTs that can have different curation parameters.
