### ISSUE TITLE
SIP - Update Account Metadata via Posting Key

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3274]
An account's JSON metadata is currently updated via the owner or active authority. The field is non-consensus and is used for many applications that do not need/want access to an account's active authority. To require the active authority for updating such information is a security weakness as it requires users to sign with an active key when they would otherwise not need to.

## New Operation

``` C++
struct account_update2_operation : public base_operation
{
   account_name_type             account;
   optional< authority >         owner;
   optional< authority >         active;
   optional< authority >         posting;
   optional< public_key_type >   memo_key;
   string                        json_metadata;
   string                        posting_json_metadata;

   extensions_type               extensions;
};
```

The operation would behave identically to the existing `account_update_operation` except that it would allow the posting authority to sign when the owner and active authorities and memo key are not present (i.e. only valid for posting and JSON metadata).

Prior to HF 21, `json_metadata` and `posting_json_metadata` will be updated at the same time by the previous operation. After HF 21, the old account update will only change `json_metadata`, and `posting_json_metadata` can only be updated by this operation. This way any App that is relying on security backed by the active authority can and will continue to operate after the hardfork without needing to update.

## Alternate Solutions

The biggest drawback here is the creation of a new (and mostly redundant) operation. There are two alternative solutions. Both involve using existing portions to the account update operation to signal old use of the operation and remove the soft fork during a hard fork. This would allow us to get around requiring a new operation, but would require apps to update their use of this operation to continue operating. Creating a new operation would allow for perfect backwards compatibility with existing apps as well as adding the extraordinarily useful extensions field.

**Comment by economicstudio** [comment]
I strongly agree with this change.

For the mass adoption by most non-advanced users, this change is a must. Think about FB, insta, people wanna change their profile photo quite often. Most Steemit newbies are already frustrated with that initial step.

ps. Just for curiosity, may I ask what was the rationale behind that it was made to require the active key?

**Comment by mvandeberg** [comment]
Many operations were taken directly from BitShares during the development of Steem. The posting authority was only added to new operations. This was a not a new operation. It was not necessarily an explicit decision to require the active key (because the active key was required in BitShares) but rather an implicit decision to not add the posting key. Combine that with the fact that we underestimated how much use the metadata field would be used, and here we are.

**Comment by economicstudio** [comment]
@mvandeberg Thanks a lot for your answer. @sgerbino thanks for implementing this. Working like a charm!
