### ISSUE TITLE
[HELP] get_feed_history Not showing updated result

### ISSUE THREAD

**Issue by yashbhavsar007** [steemit/steem#3275]
What i have did?

I have my own steem private net setup(Not TestNet!) And i executed this command from my witness cli console 
`publish_feed "initminer" {"base":"3.000 SBD", "quote":"3.000 STEEM"} true`

And i tried this command on same console `get_feed_history` 
And i get this result 
```
{
  "id": 0,
  "current_median_history": {
    "base": "0.000 STEEM",
    "quote": "0.000 STEEM"
  },
  "price_history": []
}
```

Please suggest any solution for this ?

**Comment by mvandeberg** [comment]
The returned price feed is a median of medians.

Every hour, the price feed from each of the scheduled witnesses is checked and the median of those is saved to a queue. The most recent price is enqueued and the oldest is removed. Then those are sorted and the median of those is set as the price feed that is used for all blockchain calculations.

How quickly the price feed updates is defined by `STEEM_FEED_HISTORY_WINDOW`, which is 84. When capturing the price feed every hour, this creates a lifetime of 3.5 days for a single price entry.

Additionally, the price feed is only captured if there are 7 witnesses publishing a price.

I order for you to see a price feed on your private testnet, you'll need to create witnesses, vote them in to produce, have them each publish prices, and then generate blocks. You can use the debug plugin to generate blocks faster on a private setup, which should allows to script and automate this process.

**Comment by yashbhavsar007** [comment]
Thank you @mvandeberg I got it
