### ISSUE TITLE
SPS - Remove owner auth history and pending recoveries for steemdao

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3276]
The owner authority history and pending recoveries should be cleared at the time of HF21 to prevent any case where the account could be recovered.

These conditionals can be removed after the fork once we know the account is successfully unrecoverable.

**Comment by joticajulian** [comment]
Instead of removing the owner authority history, let's change the account recovery directly. So, blocktrades does not need to change the account recovery and wait 30 days. I propose blocktradesdevs#138

**Comment by mvandeberg** [comment]
Also an acceptable solution. We also need to, to be safe, check for a pending recovery and remove it if it exists. If we assume the most likely scenario of account recovery causing issues at the time of the hardfork is the key being stolen, then we should assume the thief will do everything they can to get the account back in to their possession. The current safeguards are good, but a recovery could be pending prior to the fork and then recovered after the fork. Additionally, if a recovery partner change is pending, it must be removed as well.

**Comment by joticajulian** [comment]
ok. I added it to blocktradesdevs#138
