### ISSUE TITLE
Create updated Windows build instructions

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#328]
This ticket should be closed when either of the following two conditions occurs:
- (a) We declare Windows is not an officially supported platform
- (b) We add Windows build instructions to the tree (perhaps based on [this](https://steemit.com/steem/@bitcube/steem-mining-in-microsoft-windows-a-builder-s-guide-part-1))

**Comment by abitmore** [comment]
@theoreticalbts please check this patch (Division by zero): https://github.com/steemit/steem/pull/333/files#diff-76b4b57a464fcf6ec0c0525753ed1222R417 which is mentioned in https://github.com/steemit/steem/issues/311#issuecomment-242955207

**Comment by theoreticalbts** [comment]
I think running full nodes on Windows should not be officially supported.  @sneak , what do you think?

**Comment by mvandeberg** [comment]
This is our Windows support. https://docs.docker.com/docker-for-windows/

**Comment by sneak** [comment]
There are *no* officially supported platforms. We develop on one, deploy on another, and fix bug reports from a third.  We do not provide support for any of them.
