### ISSUE TITLE
Diversifying steemPower contract.

### ISSUE THREAD

**Issue by LeeBlues** [steemit/steem#330]
Dear developers of steem platform.
 I think 104-week time frame of steempower and inflation scheme make short term traders stay away from steem trading. Consequently, There is low trading volume. This low trading volume incur severe steem price volatility. Also post per day graph is flat or slightly declining which means game participants are not rising. Steem needs trading volume and increasing posts(new steempower holders). If there are short time frame steempower contracts then it can bring short term traders into the game of steemit. Yes ,they will jump in and jump out but that is trading volume which is essential to protect its price from manipulation 
Of course there should be some financial penalty for short term contract holders and financial reward for long term contract holders.  I think just by differing inflation reward, we can achieve this goal

Let SteemPower = Sp
Sp.x , x represents required time(week) for full liquidation 
Sp.x inflation compensation = x/104 (%)

ex)
SpProducts = {Sp.8, Sp.13, Sp.21, Sp.34, Sp.55, Sp.89, Sp.104}
Sp.8 inflation compensation= 8/104 , approximately 7.6923% of Sp.104 contract inflation compnesation
Sp.21 inflation compensation = 21/104 , approximately 20.1923% of Sp.104 contract inflation compnesation

**Comment by theoreticalbts** [comment]
This will not be implemented.
