### ISSUE TITLE
Bump STEEM_SMT_HARDFORK to HF 22

### ISSUE THREAD

**Issue by sgerbino** [steemit/steem#3301]
Since SMTs will not be ready for HF21, we need to bump the macro to HF22.
It appears this also has caused #3291 to fail CI due to two HF21s in the same switch statement.

**Comment by mvandeberg** [comment]
The SPS branch already has this change included. I was holding off implementing this to merge the SPS branch first and try to avoid merge conflicts on other branches.

**Comment by sgerbino** [comment]
Ok, resolved by #3278.
