### ISSUE TITLE
<header> Element With CSS Selector "header" Blocks Title Of Article

### ISSUE THREAD

**Issue by littlemiddlebiddle** [steemit/steem#3304]
**Specifications:
* FF 60.6.1 ESR
* Windows 7
* 1920px window.innerWidth;
* 960px window.innerHeight

**Steps to reproduce the problem:**

1. Navigate to https://steemit.com/steamit/@noisy/steem-bug-bounty-program-how-to-reports-bugs-and-new-ideas in browser and wait for the ad to load

**Actual behavior:**
* Ad blocks part of title
![image](https://user-images.githubusercontent.com/14179790/57563850-10b05100-7371-11e9-905b-b76b84df4ba5.png)

**Expected behavior:**
* Ad does not block title or page content and is as non-invasive as possible

**Comment by mvandeberg** [comment]
This is an issue for [Condenser repo](https://github.com/steemit/condenser/issues?q=is%3Aopen+is%3Aissue).

Please make an issue there and close this one.

**Comment by littlemiddlebiddle** [comment]
Thanks, will do!
