### ISSUE TITLE
Switching BMIC to RocksDB at runtime doesn't produce output

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#3305]
In low memory conditions it takes a significant amount of time before `steemd` produce any output at info level.
That is between 
` chain_plugin.cpp:534          operator()           ] Performance report at block`
and
`database.cpp:329              reindex              ] Done reindexing, elapsed time`

(where low = 32GB of RAM, and significant = many hours)

Any signs of progress will be very helpful to node operators.

**Comment by Gandalf-the-Grey** [comment]
`mira-runtime-adapter` (before it was merged) reindexing 30M blocks.
Yes, there are status notifications every 100k blocks and everything goes smooth while doing "in memory part" up to 
`chain_plugin.cpp:534          operator()           ] Performance report at block 30000000`
then HUGE gap before 
`database.cpp:329              reindex              ] Done reindexing`
and less (but still significant - over an hour)
before last two lines, that is:
`chain_plugin.cpp:552          plugin_startup       ] Performance report (total). Blocks: 30000000. `
and
`chain_plugin.cpp:557          plugin_startup       ] Stopped blockchain replaying on user request. Last applied block number: 30000000.`

**Comment by sgerbino** [comment]
#3311 should display information regarding what index is being converted to what type in either direction.
