### ISSUE TITLE
High Interest On Vests Likely Killing Platform Token Value and Scaring Away Big Investors

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steem#331]
I love the STEEM platform and have since the beginning, except for one fatal flaw in the system: ultra-high interest rates on STEEM Power vesting shares ( https://steemit.com/steem/@taoteh1221/anybody-else-think-current-steem-power-interest-creates-sell-pressure ). 

In the 2 years I've been in crypto I've seen ZERO exceptions to this rule: super high interest == endlessly shrinking value of the network token. Just look at HYPER or HYPERSTAKE for example. STEEM Power vests is even higher interest than those two COMBINED. 

Only being able to liquidate 0.96% of STEEM Power weekly seems it likey is not enough to make the sell pressure go way (all it takes is a couple dozen whales or a hundred or so dolphins powering down at the current daily trading volume). Once the spiraling decrease in value starts and is confirmed to be a stable trend, any wise investor just exits their position as fast as possible, further intensifying the sell pressure.

The STEEM platform is very valuable, the front page of Steemit.com is a well balanced mix of different topics that are interesting. I think all you have to do is hard fork to get STEEM Power interest to a relatively normal level, no more than 5% to 10%, and the token value may stabilize and reflect the value of the platform better. A super high interest rate is a red flag though, and big investors likely are not BUYING because of this issue.

The massive yearly increase in token amounts is risky enough on it's own, we don't need super high interest to risk even further and possibly being the final nail in the coffin on token value. I understand it may be an attempt to offset risk for vest holders with so many new tokens created daily, but I think it just makes things worse. 

I sincerely do hope the platform's high points (of which there are many to say the least...it is absolutely awesome) eventually stabilize the token, and prove me wrong...but I have much doubt this can happen with the current vesting interest rate set to last 6-7 more months.

**Comment by AlekseiSmirnov** [comment]
Completely agree with you. IMO almost nobody buys STEEM now, so there is no any investment inflow. 
According to http://steemwhales.com/ lots of whales constantly Power Down their SP. Some of them move STEEMS to exchange strongly pushing price down

It can be easily checked using ExchangeTransfers scripts here https://github.com/lukestokes/php-steem-tools
ExchangeTransfers: Get the 50 accounts transferring to and from an exchange along with a daily report of exchange transfer activity.

Steemit team should definitely do something with that, otherwise, it will screw up pretty soon

**Comment by theoreticalbts** [comment]
Steem Power is a fundamental part of Steem economic system and will not be changed.

Discussion of the supply / demand fundamentals of Steem, and alternative economic systems, while interesting and potentially fruitful, is off-topic for the issue tracker.

**Comment by taoteh1221** [comment]
@theoreticalbts Ok sorry, couldn't think of where else to post this to, as it seemed like an issue to me...will skip posting here other than purely technical issues from now on. Good luck with this new network.

**Comment by taoteh1221** [comment]
Cough
