### ISSUE TITLE
[Suggestion] Real payout declined post

### ISSUE THREAD

**Issue by economicstudio** [steemit/steem#3315]
The current payout declined post still consumes the voting power of voters, and therefore it also shows "pending payout" which will not be paid out.

It's been mainly used by Steemit Inc's accounts (e.g., steemitblog) or top witnesses (mainly in the past when they earn a lot :) or any users for testing or looking cool :)

I suggest that we should also introduce **_real_** payout declined post. By *real*, I mean, it doesn't consume VP, nor showing the pending payout.

#### Mockups / Examples
![](https://ipfs.busy.org/ipfs/QmRNbQy2n91GycYrdrtEaLZ9Wii4tvBXY2yKKjEMMz5FnJ)
> a typical payout declined post

Instead of ~~$2.69~~ in the above, `declined` can be shown, for instance. (Let me not do the photoshop for this, since it's so clear and not important here. The important things are
1. It doesn't consume VP
2. (Thus,) It doesn't show the pending amount

#### Benefits
I hope you've already realized why we need this. Keeping voters who voted on current payout declined posts from frustration is one benefit.

But much more importantly, imagine already well-recognized famous writers outside of Steemit. Would they write on Steemit? Even when the Steem price was pretty high, they might have been reluctant to do that for many reasons.

Among those reasons, one very important reason is that they want to avoid an embarrassing situation that they don't get enough vote. For them, earning from voting isn't  important at all (unless it's really huge). They just share their opinion and influence.

We all know that decentralized PoB is almost impossible. Even for famous people, if they don't invest or communicate (which is pretty difficult since they're busy), they can't get enough votings after a few warm welcomes in the beginning.

In addition to ad-revenue sharing with authors, this real payout declined posting is a key to bring those people.

ps. It's a simple and short suggestion. But I truly believe that this is very important. I also pointed out the importance of this feature in [my column](https://www.coindeskkorea.com/%EB%B8%94%EB%A1%9D%EC%B2%B4%EC%9D%B8-%EA%B8%B0%EB%B0%98-%EC%86%8C%EC%85%9C%EB%AF%B8%EB%94%94%EC%96%B4%EA%B0%80-%EA%B8%B0%EC%88%A0%EC%A0%81%EC%9C%BC%EB%A1%9C-%EA%B3%A0%EB%A0%A4%ED%95%B4%EC%95%BC/) on Coindesk Korea (sorry it's in Korean) recently. 

If you don't understand the importance, you probably haven't thought about the problems of the current Steemit carefully, or you may not be able to imagine the famous people's position. Hope many people  would agree that this is really needed. Thanks.

**Comment by Smittyvb** [comment]
This is non-consensus, and only relates to front-ends, not the blockchain. This could be achieved by hiding voting tallies and using non-consensus votes at the front-end level. You might want to file an issue at [steemit/condenser](https://github.com/steemit/condenser/issues), the repo for the Steemit frontend.

**Comment by economicstudio** [comment]
Hi @Smittyvb No No. It's not about hiding. Please read it carefully again. I'm also sorry if it wasn't clear.

It should be done at the blockchain level.

1. Doesn't consume VP
2. Not hiding but doesn't count toward payout at all.

**Comment by Smittyvb** [comment]
@economicstudio 
That could be done via ``custom_json`` advisory votes. There is no difference between hiding the payout and not counting towards the payout, as no STEEM/SBD is paid out either way. 

Regardless of how this proposal is implemented, it would still be *theoretically* possible to show a post's payout, by summing the SP of all voters. Regardless, that payout figure would be useless.

It would be much simpler to just have a ``hide_payout`` (or similar) field that can be set in a post's ``json_metadata`` signalling to hide a payout (which would only be valid if a post had a declined payout).

**Comment by economicstudio** [comment]
I think I understand what you're trying to say by "it would still be theoretically possible to show a post's payout, by summing the SP of all voters."

But I believe it's still very different, since people will react differently. for this real payout declined post, people will never worry about their VP. So it's quite different from usual post or the current payout type. Hope you would agree on this. (And again, VP shouldn't be spent. currently it's spent) And that's why I think it should be done by the chain.

For implementation details, I believe there are many ways including your suggestion. If the chain modification is a burden, then why not? changing all the UIs is an option. Thanks again.

**Comment by economicstudio** [comment]
@Smittyvb I also posted it on condenser GH: https://github.com/steemit/condenser/issues/3345 Thanks again for your very helpful comments!

**Comment by mvandeberg** [comment]
HF 21 is allowing 0 rshare votes. If a UI wants to implement this, it will be easy for them to do so by automatically making votes on declined payout posts consume 0 rshares. For now, I think it is better to keep flexibility by not chainging consensus code and let UIs experiment with how best to display this information. There is no sense coding ourselves into a UX corner with a hardfork.

**Comment by economicstudio** [comment]
@mvandeberg Great to hear that HF21 is preparing 0 rshare votes. Would it be too much a burden to add a type of this real payout declined post togehter with that? Hope it can be done. But I understand we have too many important things ahead. Thanks a lot!

By the way, any estimate on the date of HF21?

**Comment by mvandeberg** [comment]
We are trying not to add new non-consensus fields to our Steem APIs. That was a big motivator in creating Hivemind, which can much more easily implement these types of non-consensus fields.

**Comment by economicstudio** [comment]
totally understand.

btw, unrelated, but people (to be honest including me) start a bit worrying about the progress of SMT. Of course, most (again including me) like these days various small and big improvements, but the real big thing is still SMT. Hope you or someone also makes a post about it near future. Thanks again!

**Comment by mvandeberg** [comment]
> but the real big thing is still SMT.

We agree completely and are wrapping up MIRA and HF21 as quickly as we can so we can devote the full attention of our blockchain engineers to SMTs.
