### ISSUE TITLE
comments missing under a post, loads after refresh

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#332]
Happened few times while searching for new users introductions.

Way to reproduce (sometimes):
- click on some post, scroll down to potential payout time, etc. comments are visible
- click on a username (show options to FOLLOW or MUTE)
- click on username again to get to his home page
- click again on a same post that you were just watching.
- scroll down and see no comments.
- reload would show them again

I noticed that multiple times, semi-randomly. I just tried to reproduce on exact same post/user as a minute before but without success.

**Comment by abitmore** [comment]
An steemit.com issue? Reposted here: https://github.com/steemit/steemit.com/issues/204

**Comment by theoreticalbts** [comment]
Until / unless this is shown to be a backend issue, I'm closing this ticket; discussion should move to the above ticket on steemit.com repo.
