### ISSUE TITLE
condenser_api.get_discussions_by_active returns empty array as response

### ISSUE THREAD

**Issue by lion-200** [steemit/steem#3331]
Hi all,
I was trying to get all active discussions by calling the condenser_api.get_discussions_by_active method as defined in the developers.steem.io website.

This is my request:
```javascript
curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_discussions_by_active", "params":[{"tag":"lion200","limit":10}], "id":1}' https://steemd.minnowsupportproject.org
```
This is the response I get no matter which user I provide as "tag" parameter:
```php
{"jsonrpc":"2.0","result":[],"id":1}
```

Is this a known issue or am I forgetting something?

**Comment by mvandeberg** [comment]
There is one thing wrong on your end, which does expose a lack a features in the tags_api.

Your parameters are wrong assuming you want to get the top 10 active discussions by author `lion200`. The params that would make sense in that scenario are `"params":[{"select_authors":["lion200"],"limit":10}]`, but the `select_author` field seems only to have an impact on the call, `get_discussions_by_blog`.

We are moving away from the tags api to Hivemind. If there are features you want to see added there, I suggest creating an issue in that repo.
