### ISSUE TITLE
Add `beneficiary_payout_value` to database_api and condenser_api

### ISSUE THREAD

**Issue by joticajulian** [steemit/steem#3334]
In this moment the RPC nodes return posts without `beneficiary_payout_value`, which cannot be derived from the `total_payout_value` because it is the final author payout.

**Comment by mvandeberg** [comment]
We are trying not to add more non-consensus fields to the steemd APIs. This information can be obtained through account history, but understandably, this is difficult for old comments. This is something I believe Hivemind should be able to handle without much work.

**Comment by mvandeberg** [comment]
Closing in favor or #3429
