### ISSUE TITLE
check_bcd_trigger always fails and logs 'now_slot' = 0

### ISSUE THREAD

**Issue by str11ngfello** [steemit/steem#334]
@theoreticalbts, wondering if bcd_trigger has a bug or if it's a node setup issue on my part. When I broadcast a raw, signed transaction...say something like this ->

{'expiration': '2016-08-30T04:02:05',
 'extensions': [],
 'operations': [['vote',
                 {'author': 'charlieshrem',
                  'permlink': 'a-geek-in-prison-a-life-series-by-charlie-shrem-preamble',
                  'voter': 'steemapp',
                  'weight': 10000}]],
 'ref_block_num': 13500,
 'ref_block_prefix': 2820342457,
 'signatures': ['201be9a39dd4b51c4be650af146c463205d8793ece1b47a7ef4c2b43f0b11b0de912b7698cfeb5d167afe75d6ca7a41f9e5c059f3fcdcb664f8705bea8bfcb0176']}

Our full node always, regardless of the transaction sent, logs bcd_trigger failure event with a now_time of 0.  The delta between slot 0 and slot current_aslot is of course, very large so some internal checks in the code will cause a failure condition.   Sample output from our full node upon receiving the tx... 

989601ms th_a       api.cpp:107                   get_api_by_name      ] found api: network_broadcast_api
989601ms th_a       api.cpp:134                   check_bcd_trigger    ] Entering check_bcd_trigger: now=2016-08-30T15:16:29
989602ms th_a       api.cpp:140                   check_bcd_trigger    ] Testing bcd trigger: [0,10]  trig_slots=4
989602ms th_a       api.cpp:148                   check_bcd_trigger    ] **now_slot: 0   current_aslot: 4578329**
989602ms th_a       api.cpp:155                   check_bcd_trigger    ] discarded_slots: 4578329
989602ms th_a       api.cpp:159                   check_bcd_trigger    ] Bailed in check_bcd_trigger because the blockchain extends too far into the future
989602ms th_a       api.cpp:140                   check_bcd_trigger    ] Testing bcd trigger: [85,300]  trig_slots=100
989602ms th_a       api.cpp:148                   check_bcd_trigger    ] **now_slot: 0   current_aslot: 4578329**
989602ms th_a       api.cpp:155                   check_bcd_trigger    ] discarded_slots: 4578329
989602ms th_a       api.cpp:159                   check_bcd_trigger    ] Bailed in check_bcd_trigger because the blockchain extends too far into the future
989604ms th_a       database_api.cpp:189          ~database_api_impl   ] freeing database api 8916384880

now_slot is always 0.  Looking at the code this seems like a failure condition I shouldn't be experiencing. check_bcd_trigger always fails because now_slot is 0.  

I first tried for help steemit.chat and am trying here to see if this is expected behavior EVER under normal conditions (that is, now_slot=0).  Or, perhaps this is a configuration issue on my end.

I'm running latest v13. I've verified we timestamp the transaction about 30 seconds ahead of the time returned by the global blockchain parameters. I've also verified the head block num and id are set correctly.

Thoughts?

**Comment by theoreticalbts** [comment]
The bcd-trigger implementation in v0.13 is badly broken, but it's broken in a way that makes it completely inactive except for printing these log messages.  This issue has been fixed in develop for some time now, see issue #280 and [this commit](https://github.com/steemit/steem/commit/5473c48fde9c1e1336e38626324bdd0acbe0d1fa).

**Comment by str11ngfello** [comment]
Fantastic.  I can now concentrate on the real issue without worrying about these logs. Thank you!
