### ISSUE TITLE
fc library fails to build: -Werror=class-memaccess

### ISSUE THREAD

**Issue by moisesmcardona** [steemit/steem#3348]
I'm getting several errors of the following:

```
error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class fc::sha1’; use assignment or value-initialization instead [-Werror=class-memaccess]
```

The class changes between the messages.

**Comment by mvandeberg** [comment]
What OS and version of gcc are you building with?

**Comment by moisesmcardona** [comment]
Ubuntu 19.03 / GCC 8.3.0

**Comment by mvandeberg** [comment]
We are not yet supporting builds on Ubuntu 19.04, but I will add this to the backlog to get fixed.

In the meantime, you can still run Steem via a Docker image (either our provided image or by building your own). Our Docker image is a static binary, which you can extract from the image and should run locally on Ubuntu 19.04.
