### ISSUE TITLE
[Question]: Steemd On A Low-end ARM device (rpi zero wh)

### ISSUE THREAD

**Issue by ilyaigpetrov** [steemit/steem#3360]
I want to get a list of last publications of a steemit user in a bash script on a low-performance arm device (rpi zero wh). The solution must be censorship resistant so we should avoid using DNS domains or known ips that are easy to get blocked.

What would be the best way to get steemd (wallet cli) working in a bash script on a low end device?

**Comment by mvandeberg** [comment]
I do not believe steemd will currently compile on ARM devices. It is something that would be nice to do, but simply is not a priority right now.
