### ISSUE TITLE
"Reset TEMP account auth weights"  didn't execute

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#34]
There is a `break` before it. In addition lack of a `break` after it. Related code is [here](https://github.com/steemit/steem/blame/72f2570319fe9f6b9d4cd23c09ff04243e787673/libraries/chain/database.cpp#L2404-L2422).

**Comment by mvandeberg** [comment]
There were problems when merging different branches and it did not execute. However, the case for which it was created did not occur and the temp account currently has the correct authorities, so it is not needed. It should have or will be removed in a future release to clean up the code base, but it is a non issue.
