### ISSUE TITLE
Unsuccessful sync of blockchain, using block_log-latest downloaded

### ISSUE THREAD

**Issue by qkrwnsgh1288** [steemit/steem#3400]
OS: centos7.5
steemd version: v0.20.10

I downloaded block_log-latest in steem git.
And I have run steemd with --replay-block flag.
But error has occured.
![steem_replay_error](https://user-images.githubusercontent.com/37591278/60938527-417c1a80-a30f-11e9-9441-d17bbdeae31c.png)

What causes this error?
What should I do if I want to sync?

**Comment by Gandalf-the-Grey** [comment]
please check
`dd if=block_log bs=1M count=200k | md5sum`
to verify that your `block_log` file is not corrupted (You are checking first 200G of a file which includes blocks where your issue happened but doesn't include tail which will make checksums differ every time)

(should be `74252fd140eb297923e29ace4ae3a34d`)

**Comment by qkrwnsgh1288** [comment]
I have already deleted and re-downloaded. and replay processing..
And I checked your command, The block_log is `74252fd140eb297923e29ace4ae3a34d` as you say.
So far it is going well. Thank you so much.

**Comment by mvandeberg** [comment]
Assuming this issue has been resolved. Closing.
