### ISSUE TITLE
new steem in the curation distribution

### ISSUE THREAD

**Issue by joticajulian** [steemit/steem#3401]
Suppose that a post receives an upvote of $100 from Alice, and next a downvote of -$99 from Bob.
Then, in the curation distribution, the Alice's weight will be greater than the total weight. And then `claim` will be greater than `max_rewards` in the following formula:

```claim = max_rewards * weight / total_weight```

Which could create new steem.

Is this possible? I'm not sure if I am missing something.

If this is the case then it's better to change this line:
https://github.com/steemit/steem/blob/a470bc283260e582b56897bd5c68107aa0289f18/libraries/chain/database.cpp#L1826

to

``` if( claim > 0 && unclaimed_rewards >= claim)```

**Comment by eonwarped** [comment]
Why do you think Alice's weight will be larger than the total? I believe where the weights are computed handles downvotes properly, but would have to double-check

**Comment by joticajulian** [comment]
Ok, I found what I was missing:
https://github.com/steemit/steem/blob/a470bc283260e582b56897bd5c68107aa0289f18/libraries/chain/steem_evaluator.cpp#L2098-L2105

I thought that the total weight was calculated by evaluating the curve using `net_rshares`, which is a value that could decrease.

But actually, the total weight is only modified for upvotes, no downvotes. So there is no problem.

Thanks.
