### ISSUE TITLE
[HF21 Testnet] Asking for "steem.dao" account (pre-HF) fails

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#3402]
`curl -s --data '{"jsonrpc":"2.0", "method":"condenser_api.get_accounts", "params":[["steem.dao"]], "id":1}' https://testnet.steemitdev.com`

returns:
`{"jsonrpc":"2.0","error":{"code":-32000,"message":"Unknown error - parsing rpc message failed","data":"unknown key"},"id":1}`

same request works fine on `api.steemit.com`

**Comment by mvandeberg** [comment]
My guess is that the steemd.dao account was not yet created in the snapshot that we used for the testnet.
