### ISSUE TITLE
RC API sometimes incorrectly reports user doesn't have enough RC

### ISSUE THREAD

**Issue by netuoso** [steemit/steem#3404]
### Issue
Some nodes show an incorrect RC amount for users when trying to transact. In certain situations, this results in an error preventing the transaction when the user does, in fact, have enough RC.

### Quick Fix
The issue appears to be happening on **some nodes some of the time**. Switching to a different node seems to fix the issue, both allowing the transaction to go through and removing the issue from the original, affected node.

### Steps to Reproduce
**WARNING: Very hard to reproduce reliably.*
1. Try to perform some transaction on SteemIt.com
2. Get an error "plugin exception:Account: netuoso has 1123844 RC, needs 728922 RC. Please wait to transact, or power up STEEM.rethrow"
3. Observe the error saying user has 1,123,844 RC and needs 728,922 RC. The current RC amount is higher than the required RC amount.
4. Send the same transaction to a different node this time
5. If transaction goes through, observe that user can perform actions on the original node

### More Information
- Error tells user they need more RC when they have enough
- Issue is present on the Mainnet
- Issue is fixed by using a different node
- Has been reported by several users in the past few weeks

### More Information - User reports
```
Hi, I'm trying to make a costly op: resteem
RPCError: plugin exception:Account: USER has 5523170590 RC, needs 431011452 RC. Please wait to transact, or power up STEEM.
5523170590 is bigger than 
431011452
I don't understand...
```

```
RPCError: plugin exception:Account: USER has 309612403135 RC, needs 76426276 RC. Please wait to transact, or power up STEEM.rethrow
```

**Comment by sgerbino** [comment]
Thank you for the report. Can you tell if the working node is non-MIRA and the broken node is MIRA? If so, then I think this commit will address it 397ac6290c4363b08ed5588f1dd085e82f0644d4.

**Comment by netuoso** [comment]
In this particular test I saw, the node that "fixed" the problem was not MIRA while the node that had the issue was.

**Comment by roadscape** [comment]
Dupe of https://github.com/steemit/steem/issues/3351?

**Comment by netuoso** [comment]
@roadscape Yep. My searching and Githubs "possibly related issues" failed to find it.
