### ISSUE TITLE
Can't do anything, even with sufficient RC

### ISSUE THREAD

**Issue by centurions90** [steemit/steem#3431]
I've been waiting for two days already. I haven't been able to do anything on Steemit. Whenever I try to upvote, post, or do anything, I just receive an error message that says I do not have enough RC, even though the message itself states that I have more than enough.
![Annotation 2019-07-29 195549](https://user-images.githubusercontent.com/44990178/62046931-bde18980-b23b-11e9-9da7-f24fb5c36099.png)
![Annotation 2019-07-29 195830](https://user-images.githubusercontent.com/44990178/62046932-be7a2000-b23b-11e9-9a3a-887358de36dc.png)

**Comment by centurions90** [comment]
The problem strangely went away for seemingly no reason.

**Comment by mvandeberg** [comment]
This was probably a duplicate of #3351, the fix for which was recently deployed on our end.
