### ISSUE TITLE
Integrate follow data into existing architecture, with option to filter results based on current_account_name

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#344]
This tends to penalize readers of popular bloggers that have a lot of people following.  For example, look at the all of the `get_followers` API calls that happen to everyone that reads Dan's post:

https://steemit.com/philosophy/@dantheman/why-do-we-fight-to-change-the-world

![image](https://cloud.githubusercontent.com/assets/204121/18208784/706f1f16-70f6-11e6-9e34-25bf7518d413.png)

This varies but i have seen each API cause a pause in scrolling for almost a 1/4 of a second.  I'm sure this is not favorable to the server either.

In the case of the top-level post, I don't need all of the following and followers anyways.  I just need to know if this author is followed or muted.  For this to work we need the current_account_name.  This would probably be done here:

`get_state url [current_account_name]`
`get_content author permlink [current_account_name]`

Each content object might have:

``` js
content: {
   author: ...
   current_account_following: ['blog' | 'ignore', ...] // null if current account was not provided
}
```

Anytime we have an account returned, we could include the full follow data for that account:

``` js
accounts: {
    [account_name]: [
        id: ...
        followers: {
            [account_name]: ['blog', ...]
            [account_name]: ['ignore', ...]
        }
        following: {
            [account_name]: ['blog', ...]
            [account_name]: ['ignore', ...]
        }
    }
}
```

This would also allow these numbers appear on the screen immediately instead of seeing the followers and followed loading in blocks of 100:

![image](https://cloud.githubusercontent.com/assets/204121/18211547/d6194bd6-7103-11e6-9857-3b8c89d4e7fc.png)

During a page refresh, from the time it showed 0 followers to the time it finished loading was 9 seconds.

**Comment by jcalfee** [comment]
Also needed:
```javascript
content: {
   author: ...
   current_account_reblog: true | false
}
```

**Comment by jcalfee** [comment]
Alternatively, just include current_account_following and followers and following totals (excluding ignore) and I'll continue to pull the follow list the way I do now from the database api.

**Comment by mvandeberg** [comment]
The follow plugin has had an API call to return follow counts for some time now. We have also since moved on from shoving more data in the state object by default. Closing this as it is no irrelevant.
