### ISSUE TITLE
Chainbase revision does not match head block num

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/steem#3441]
Non-MIRA 20.12 and 21.0 replayed and synched fine, but won't restart after exiting cleanly, giving those errors:
```
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.20.12
------------------------------------------------------
3105321ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
3105321ms chain_plugin.cpp:464          plugin_startup       ] Starting chain with shared_file_size: 64424509440 bytes
3105321ms chain_plugin.cpp:594          plugin_startup       ] Opening shared memory from /shm/
3105325ms block_log.cpp:142             open                 ] Log is nonempty
3105326ms block_log.cpp:151             open                 ] Index is nonempty
3105327ms database.cpp:184              open                 ] 10 assert_exception: Assert Exception
revision() == head_block_num(): Chainbase revision does not match head block num
    {"rev":29109,"head_block":35149856}
    database.cpp:142 operator()
3105327ms database.cpp:184              open                 ] args.data_dir: /steem/witness_node_data_dir/blockchain args.shared_mem_dir: /shm/ args.shared_file_size: 64424509440 
3105327ms chain_plugin.cpp:603          plugin_startup       ] Error opening database. If the binary or configuration has changed, replay the blockchain explicitly. Error: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database.cpp","line":142,"method":"operator()","hostname":"","timestamp":"2019-07-31T17:51:45"},"format":"revision() == head_block_num(): Chainbase revision does not match head block num","data":{"rev":29109,"head_block":35149856}},{"context":{"level":"warn","file":"database.cpp","line":184,"method":"open","hostname":"","timestamp":"2019-07-31T17:51:45"},"format":"rethrow","data":{"args.data_dir":"/steem/witness_node_data_dir/blockchain","args.shared_mem_dir":"/shm/","args.shared_file_size":"64424509440"}}]}
```

```
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.21.0
------------------------------------------------------
793343ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
793343ms chain_plugin.cpp:464          plugin_startup       ] Starting chain with shared_file_size: 107374182400 bytes
793343ms chain_plugin.cpp:594          plugin_startup       ] Opening shared memory from /shm/
793345ms block_log.cpp:142             open                 ] Log is nonempty
793345ms block_log.cpp:151             open                 ] Index is nonempty
793346ms database.cpp:184              open                 ] 10 assert_exception: Assert Exception
revision() == head_block_num(): Chainbase revision does not match head block num
    {"rev":5405,"head_block":35152692}
    database.cpp:142 operator()
793346ms database.cpp:184              open                 ] args.data_dir: /steem/witness_node_data_dir/blockchain args.shared_mem_dir: /shm/ args.shared_file_size: 107374182400 
793346ms chain_plugin.cpp:603          plugin_startup       ] Error opening database. If the binary or configuration has changed, replay the blockchain explicitly. Error: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database.cpp","line":142,"method":"operator()","hostname":"","timestamp":"2019-07-31T20:13:13"},"format":"revision() == head_block_num(): Chainbase revision does not match head block num","data":{"rev":5405,"head_block":35152692}},{"context":{"level":"warn","file":"database.cpp","line":184,"method":"open","hostname":"","timestamp":"2019-07-31T20:13:13"},"format":"rethrow","data":{"args.data_dir":"/steem/witness_node_data_dir/blockchain","args.shared_mem_dir":"/shm/","args.shared_file_size":"107374182400"}}]}```

**Comment by Gandalf-the-Grey** [comment]
I thought that this is related only to case of stopping `v0.20.12` and then starting non-mira `v0.21.0` but no, I have non-docker, Ubuntu 18.04 LTS build of `v0.21.0-no-mira`
( `-DCMAKE_BUILD_TYPE=Release -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DSKIP_BY_TX_ID=OFF -DBUILD_STEEM_TESTNET=OFF -DSTEEM_STATIC_BUILD=ON -DENABLE_MIRA=OFF` )

Way to reproduce:
`--replay` with `blocks_log` (I remove index to be re-created each time)
stop instance `Ctrl+C`
start instance (no `--replay`, obviously)

**Comment by mvandeberg** [comment]
> EDIT: adding switch --i-know-what-im-doing-ignore-that-check could save lives (days of), in case of some exchanges), that already fell in that trap

This is what I am planning.

**Comment by mvandeberg** [comment]
Sorry, I completely misread what the original issue is. I assumed it was a problem with changing the hardfork version from 20 to 21, which would result in a dummy check in chainbase failing. An oversight on my part.

Your error is much worse. The database revision is the block that it is on. For the head block and the database revision to get out of sync is really bad. Yours being so far off probably points to database corruption rather than a bug.

**Comment by mvandeberg** [comment]
This is happening every time, non-mira, within and without a Docker container for 0.21.0 and 0.20.12 when not switching between the two. Correct?

**Comment by Jolly-Pirate** [comment]
> This is happening every time, non-mira, within and without a Docker container for 0.21.0 and 0.20.12 when not switching between the two. Correct?

@mvandeberg correct. I haven't tested switching yet because it doesn't restart within the same version to begin with.

**Comment by Jolly-Pirate** [comment]
Good job @mvandeberg, after patching 20.12 with https://github.com/steemit/steem/commit/3308eb8d8f1a773536a5b08db33616786e58a4ca, I had to replay and I can switch back and forth with the patched 21.0 without a problem.

**Comment by DataSteam2019** [comment]
May I ask how to solve this issue? I encountered a same one but I don't know how to handle it.

**Comment by Gandalf-the-Grey** [comment]
That's an obsolete code base with ZERO development here. All the people who had the slightest idea about this code and technology moved away leaving steemit as empty shell. Given the huge progress and development that was made over time to our fork (Hive), and zero maintenance effort here (Steem) I believe it's no longer safe to run this code.

**Comment by DataSteam2019** [comment]
> 

May I ask where I can find the HIVE code?
