### ISSUE TITLE
database created by a different compiler, build, or operating system

### ISSUE THREAD

**Issue by oflyhigh** [steemit/steem#3446]
I build v0.20.12-no-mira from the source, and then replaced the steemd (v0.20.10).

But when I try to run it, i got the following error messages:
>Error opening database. If the binary or configuration has changed, replay the blockchain explicitly. Error: {"code":13,"name":"N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE","message":"database created by a different compiler, build, or operating system","stack":[{"context":{"level":"warn","file":"database.cpp","line":184,"method":"open","hostname":"","timestamp":"2019-08-01T15:37:50"}
....

But in the v0.20.12-no-mira release note. it shows that:
>Steem 0.20.12 does require reindexing from all previous versions.

So, What's wrong?

**Comment by mvandeberg** [comment]
Don't replay. Keep your v0.20.12 state file. While the state files are compatible, there is a check that is assuming they aren't (we don't usually release compatible builds that have different hardfork versions). We will get a new build out that adds a cli flag to skip this check.

**Comment by mvandeberg** [comment]
I read your issue too fast. If you are upgrading from 0.20.10 -> 0.20.12/0.21.0 you will need to replay. The release notes read "Steem 0.20.12 **does** require reindexing from all previous versions."

**Comment by oflyhigh** [comment]
Sorry,  I made a mistake. I misread the content,😳

So do I need to replay if I upgrade steemd from v0.20.10 to  ***v0.20.12-no-mira***?

**Comment by mvandeberg** [comment]
Correct.
