### ISSUE TITLE
Replace bcd-trigger parameter with max-block-age parameter

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#345]

**Comment by theoreticalbts** [comment]
According to @bytemaster `--bcd-trigger` is "too complicated" or something #247 #280 and should be replaced with `--max-block-age` which suppresses broadcast based only on the age of the most recent block.

This is not a change I personally agree with, because it throws out a great deal of work I did (especially with respect to creating a testing framework), and it is not as robust to forking (`--max-block-age` will still allow broadcasting of transactions when you're on a minority fork as long as you've recently seen a block, whereas a suitable `--bcd-trigger` is capable of suppressing all transactions on a minority fork).

In the interests of getting a release out, here is the code.  It is completely untested.

**Comment by abitmore** [comment]
> ... it is not as robust to forking (--max-block-age will still allow broadcasting of transactions when you're on a minority fork as long as you've recently seen a block, whereas a suitable --bcd-trigger is capable of suppressing all transactions on a minority fork).

Agree.

But perhaps we can add another parameter `--min-participation-rate` so it will be more robust.

**Comment by theoreticalbts** [comment]
Merged
