### ISSUE TITLE
Review smt_setup_operation destination inputs

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3455]
The full extended fund destination code was not written until #3407. This means that extended fund destinations were not properly tested during SMT setup. The following fund destinations need to be tested during SMT setup.

| Special Destinations | Valid ICO STEEM Dest | Valid ICO SMT Dest | Valid Emission Dest
|---------------------:|:--------------------:|:------------------:|:-------------------:|
| `$from` |   | X |   |
| `$from.vesting` |   | X |   |
| `$rewards` |   | X | X |
| `$vesting` |   |   | X |
| `$market_maker` | X | X | X |
| `${account}.vesting` | X | X |   |
| `{account}` | X | X |   |

#3379 Has related work to clean up SMT setup tests. This work will have some overlap and can be done together.

**Comment by sgerbino** [comment]
We should add founder vesting to this chart, e.g. `$alice.vesting`
