### ISSUE TITLE
Oops, something went wrong. Here is the error message:  "Cannot convert string to bool (only "true" or "false" can be converted)"  when voting by witness

### ISSUE THREAD

**Issue by marjuanm** [steemit/steem#3463]
Hi:

  When I want to vote for a witness, Steemit shows the following error message:
![Screenshot_1](https://user-images.githubusercontent.com/30614131/63025203-51d36800-be6e-11e9-9090-d27f4d84959b.png)

This is the URL
https://beta.steemconnect.com/sign/account-witness-vote?witness=actifit&approve=1

**Comment by mvandeberg** [comment]
This a parsing error in steemd. I am assuming Steem Connect is setting a boolean as `True` or `False` instead of the lowercase version.

You can report the error on their github. https://github.com/bonustrack/steemconnect/issues

**Comment by marjuanm** [comment]
ok, thanks, reported
https://github.com/bonustrack/steemconnect/issues/425
