### ISSUE TITLE
Hardfork 14: Post Edits & Steem as a universal content storage system

### ISSUE THREAD

**Issue by faddat** [steemit/steem#348]
```
Post Edits

Posts are now editable up to the second payout when they are archived.
```

Why not make posts editable forever? 

Also, how to store IoT data in the blockchain?  What I mean is-- what is the best approach to organizing it?

**Comment by theoreticalbts** [comment]
> Why not make posts editable forever?

Memory usage.

> how to store IoT data in the blockchain?

For writing, submit a transaction with `custom_json_operation` or `custom_binary_operation`. Of course you'll need an account with private keys, and your account may need to power up some STEEM if you use significant amounts of bandwidth.

For reading, create a plugin to parse the operations from the chain and build some sort of state, then create an API to query the state.
