### ISSUE TITLE
Delegation is not working due to not having enough downvote mana

### ISSUE THREAD

**Issue by RiseOfTH** [steemit/steem#3485]
It seems that delegation may deplete downvote mana similar to RC. Is it intentional or a bug. I have 356 SP and 100% RC, but can't delegate any amount of SP due to the following error.

Oops, something went wrong. Here is the error message: 
"available_downvote_shares >= op.vesting_shares: Account riseofth does not have enough downvote mana to delegate. required: {"amount":"436098000000","precision":6,"nai":"@@000000037"} available: {"amount":"12947000727","precision":6,"nai":"@@000000037"}"

**Comment by sgerbino** [comment]
Resolved by #3489.
