### ISSUE TITLE
Convergent linear penalty under 20 STEEM is way too high!

### ISSUE THREAD

**Issue by economicstudio** [steemit/steem#3486]
I've done some testing, and penalty on under 20 STEEM seems way too much. Almost half for most user's normal posting comparing to over 20 STEEM posting.

Who can get votes more than 20 STEEM without using voting bot / voting token?

This is wrong. very wrong. If this is really about spams, please try to find a better way to mitigate it.

**Comment by economicstudio** [comment]
I know 50/50, and I also left a comment based on some tests.

I think the reason for almost half or even less than half is because posts with more than 20 steem, they are a lot higher. In your graph, you can also see than they gain more than before. So comparing with them, it's less than half.

Even around 5 steem, it's steem -25% compared to 20 steem post. This is already too much. Most real posts don't get 5 steem. Just try with very fantastic posts under a new id. I'm pretty sure you'll get less than 2 steem after a few introducemyself things.

I saw that HF22 will come very soon :) why not adjusting it to 3~5 steem together with delegation fix?

Many users believe that Steemit Inc 

1. actually supports voting bot business this way. While due to 50/50, using bot doesn't give a good ROI as before, it's still much better to use due to that convergent linear (well, I like to call it exponential convergence to the death of PoB).

2. and/or gives advantage to big holders. Well, maybe reasonable, but is it really advantageous to them? not sure, since there's a more chance that steem price is going down further this way.

**Comment by mvandeberg** [comment]
I believe content discovery with Communities will help address many of these concerns. It is currently too difficult for users to find content they are interested (and then vote on it). We are working to solve that in the front end. That should make it easier for new authors to find like minded users and get more fairly rewarded for their content.
