### ISSUE TITLE
Downvotes do not remove the correct amount of reward according to Steemit

### ISSUE THREAD

**Issue by Transisto** [steemit/steem#3487]
Sometime it increase by a lot
![flagbug](https://user-images.githubusercontent.com/388716/63842423-835e3000-c952-11e9-8095-035b7b6372d3.gif)

Here it remove 65c while it's supposed to be ~2.30
2nd vote remove 68c, should be lower if anything.

![flagbug2](https://user-images.githubusercontent.com/388716/63842432-89541100-c952-11e9-9852-e46da657b243.gif)

**Comment by mvandeberg** [comment]
There have been no updates on this issue in over two months and no further reports. I am assuming it was a weird inconsistency unless more evidence of a bug is provided. Closing for now.
