### ISSUE TITLE
Could not create account due to having insufficient funds. 

### ISSUE THREAD

**Issue by shazbert** [steemit/steem#349]
10 assert_exception: Assert Exception creator.balance >= o.fee: Insufficient balance to create account {"creator.balance":"2.310 STEEM","required":"10.000 STEEM"} th_a steem_evaluator.cpp:89 do_apply {"op":["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["",1]]},"memo_key":"","json_metadata":""}]} th_a database.cpp:2975 _apply_transaction {"trx":{"ref_block_num":15966,"ref_block_prefix":4291579893,"expiration":"2016-09-06T13:36:18","operations":[["account_create",{"fee":"10.000

**Comment by mvandeberg** [comment]
The faucet account is currently out of Steem. We are funding it now.
