### ISSUE TITLE
votin power and vote value on private steem network is 0

### ISSUE THREAD

**Issue by rabbykst** [steemit/steem#3498]
I set up private steem network and setup condenser but it seems that all operation is ok but there is no voting value on post reward. it's showing 0 after get a vote and some times later vote counts -1 what is the problem please help and feed price is not update on blockchain, please help

**Comment by mvandeberg** [comment]
While you are allowed to fork the Steem repo, we do not provide support for forks. There are a some community devs in steem.chat that have experience with forks of Steem. They may be able to  help you.
