### ISSUE TITLE
Savings withdraw request_id is very difficult for steemit.com to manage

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#350]
Can we just use the same model we use in market transactions?  This provides uniqueness and creation simplicity.

@theoreticalbts describes this here:
https://github.com/steemit/steem/issues/239#issuecomment-237883893

**Comment by theoreticalbts** [comment]
It was originally a uint8_t, but if you scroll down in that thread, you'll see I made the exact same suggestion on Aug 5 (change to uint32_t to be like market orders), and this change was later implemented.

So AFAIK the request ID is a 32-bit integer and you can just use the current timestamp.

**Comment by jcalfee** [comment]
Great.. Better check this though: https://github.com/steemit/steem/blame/develop/libraries/chain/steem_evaluator.cpp#L1717

**Comment by jcalfee** [comment]
A side node, you might want to rename STEEMIT_SAVINGS_WITHDRAW_LIMIT to STEEMIT_SAVINGS_ACTIVE_WITHDRAW_LIMIT.

**Comment by jcalfee** [comment]
Please double check this assertion:
https://github.com/steemit/steem/blob/develop/libraries/chain/steem_evaluator.cpp#L1720  
`FC_ASSERT( from.savings_withdraw_requests < STEEMIT_SAVINGS_WITHDRAW_REQUEST_LIMIT );`

**Comment by jcalfee** [comment]
Nevermind.. my bad.. I thought that was the request ID.. Looks fixed, I still have to test it though.
