### ISSUE TITLE
Request to report illegal content on Steemit

### ISSUE THREAD

**Issue by marjuanm** [steemit/steem#3502]
Greetings to all:

  I have seen in web forums that there is the option to report a topic to administrators if it violates the terms of use of the forum, I think it also exists in some blogs, but I do not see something like this on Steemit, the situation is as follows:

  In this web address (Steemit) https://steemit.com/dtube/@juanangel40bcn/lkg3tbc8#@juanangel40bcn/39aydlhdiln the user **juanangel40bcn** promotes illegal content that is published on Steemit (**full movies**) under the argument _"Someone else put it, if he doesn't remove it, then I won't take it away either"_, he has been told that this is illegal but he refuses to remove his items under the same excuse. Obviously he seeks to profit from the traffic to his articles but is incurring the crime of piracy.
  I would like to please implement a report button at the bottom of the article (there are only buttons to share the article). When reporting it to the administrators, it would receive a negative sanction or even delete that article from the administrators.

Thank you.

**Comment by Jolly-Pirate** [comment]
You should contact Dtube about copyright material.

**Comment by mvandeberg** [comment]
Our [terms of service](https://www.steemit.com/tos.html) outline the process by which we receive DMCA requests. If you wish to file a DMCA takedown request, please follow those guidelines.
