### ISSUE TITLE
Spam Abuse: Add author reputation to content.active_votes

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#351]
A user `@r4fken` with a very low reputation is abusing the down vote causing many posts to become grayed out.  I simply need to filter on rep when deciding if an active vote counts towards this graying.  Please add this value so I can implement this on the front end.

https://steemit.com/steemitabuse/@wakeupnd/steemit-abuse-by-r4fken

https://github.com/steemit/steemit.com/issues/225

**Comment by 4ken** [comment]
It's @r4fken not me.

**Comment by jcalfee** [comment]
@4ken my apologies, I updated the ticket above...  And this ticket is done, we are counting reputation in the votes..
