### ISSUE TITLE
there is no voting power and voting reward on condenser on local network

### ISSUE THREAD

**Issue by rabbykst** [steemit/steem#3512]
on local deploy steemd with jussi in condenser voting power, voting reward value and reputation didn't work my config.ini plugins are below

plugin = statsd stats_export webserver p2p json_rpc account_history_rocksdb witness account_by_key tags follow reputation market_history account_history

plugin = database_api account_by_key_api chain_api network_broadcast_api tags_api follow_api market_history_api account_history_api condenser_api block_api rc_api transaction_status_api debug_node_api

what can i do?

**Comment by mvandeberg** [comment]
Is this a private network or on the Steem main net?

**Comment by rabbykst** [comment]
On main net but condenser on local server and steem on local with seed node api.steemi.com

**Comment by mvandeberg** [comment]
Have you verified that your steemd node is caught up with the live network?

If so, this would be a condenser/jussi problem.

**Comment by rabbykst** [comment]
Yes all caught up and all transaction vesting and powerup working well but no voting reward on vote and post

**Comment by mvandeberg** [comment]
What account are you voting with?

**Comment by mvandeberg** [comment]
This has not been updated in two months, closing.
