### ISSUE TITLE
`get_content` and `get_blog` return difference `pending_payout_value` for the same post

### ISSUE THREAD

**Issue by oflyhigh** [steemit/steem#3515]
According to my understanding, no matter how we obtain it, the `pending_payout_value` for the specified post should be consistent.

But when I tried to get `pending_payout_value` for one of my posts, I got the difference results.

Using `get_content`:
>`{"jsonrpc": "2.0", "method": "condenser_api.get_content", "params": ["oflyhigh", "ufo-2019-09-18"], "id": 1}`
![image](https://user-images.githubusercontent.com/25529332/65207089-3689f700-dac3-11e9-9622-5c4ed9b1dd11.png)

Using `get_blog`:
>`{"jsonrpc": "2.0", "method": "condenser_api.get_blog", "params": ["oflyhigh", 1787, 1], "id": 1}`
![image](https://user-images.githubusercontent.com/25529332/65207142-5e795a80-dac3-11e9-9905-4672054a9c83.png)

There were no new upvote or downvote changes to net_rshares during my tests, and the reward fund pool did not change significantly.

**Comment by eonwarped** [comment]
What about price feed median? That affects as well

**Comment by roadscape** [comment]
Payouts are calculated on the fly based on the rewards pool, which changes every block. So it's quite possible the same call to the same node gives a slightly different result every few seconds.

Also, if you're using api.steemit.com, the `get_blog` call would be routed to hivemind, which caches the pending payout at the time of the last vote/edit/comment/payout. `get_content` on the same endpoint goes to steemd, which provides the most accurate estimate.

However, hivemind always updates posts after they are paid out, so the result for posts older than 7 days should be identical.

**Comment by mvandeberg** [comment]
Out steemd nodes in production do not the follow api, so I agree that it is probably a slight discrepancy between steemd and Hivemind. I am going to close this issue. If you run across new evidence that supports there is a problem in condenser_api, please create a new issue with the evidence.
