### ISSUE TITLE
get_state2

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#353]
Add a get_state2 database API call that takes a second parameter of a struct that will included various metadata needed to make the web GUI more flexible and efficient.

**Comment by jcalfee** [comment]
I vote for JSON as that second parameter format...

**Comment by mvandeberg** [comment]
I was going to create a generic `state_context` struct that would contain a bunch of optional fields. The json representation would be to include the fields you want and disregard those you don't care about.

**Comment by adcpm** [comment]
It would be great to have pagination with get_state

**Comment by mvandeberg** [comment]
We are moving state construction to an external process. `get_state` is effectively deprecated so there is no need for `get_state2`
