### ISSUE TITLE
How can I replay blocklog in docker's container？

### ISSUE THREAD

**Issue by eggacher** [steemit/steem#3551]
My Computer:
CPU:Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
RAM:32GB
SSD:1TB

1、I run a docker container 
`docker run \
    --env USE_WAY_TOO_MUCH_RAM=1 \
    -d -p 2001:2001 -p 8090:8090 --name steemd-full \
    steemit/steem`

2、copy the block_log file to the path
`docker cp ./block_log  ${container}:/var/lib/steemd/blockchain/`

But the steemd's process is running。
`ps -ef|grep steemd`

How can I replay a block_log in the docker's container?

**Comment by mvandeberg** [comment]
Documented [here](https://github.com/steemit/steem/blob/master/doc/exchangequickstart.md).

`docker run -d --name steemd-exchange --env TRACK_ACCOUNT=nameofaccount --env USE_PUBLIC_BLOCKLOG=1 -p 2001:2001 -p 8090:8090 -v /path/to/steemwallet:/var/steemwallet -v /path/to/blockchain:/var/lib/steemd/blockchain --restart always steemit/steem`

When you start the docker container, you want to link the blocklog in to the container. steemd will pick up the existing block log on startup and reindex.
