### ISSUE TITLE
Generic witness parameters

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#357]
I think there's a ticket for this already, but I can't find it.

We want to be able to make some chain constants configurable, but the existing parameter structs don't really allow for additional fields to be added easily. Therefore we should make a new operation which is extensible in some way, shape or form, allowing us to add new chain parameters anytime. E.g. each witness specifies their desired parameter values as a `map<string, variant>`.

**Comment by abitmore** [comment]
https://github.com/steemit/steem/issues/150 is related.

**Comment by mvandeberg** [comment]
Implemented in #1620
