### ISSUE TITLE
[TestNet] Sync using current master (6412e735) stalled for hours

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#3602]
While syncing with current instance of testnet (
It stays on:
```
  "head_block_number": 100827,
  "head_block_id": "000189db42e04ea975e12cd3d34f15b69cf74bde",
  "time": "2020-02-05T18:07:39",
  "current_witness": "init-0",
```
for hours with CPU being used all the time.

**Comment by Gandalf-the-Grey** [comment]
Possibly duplicate of #3589 except that for my case (non-MIRA) it seems to take at least 12 hours (I wasn't patient enough to keep it running for a longer time)

**Comment by mvandeberg** [comment]
Can you run it again and profile to see where it is spending time?

**Comment by Gandalf-the-Grey** [comment]
Sure :-)
```
steem::plugins::chain::detail::chain_plugin_impl::start_write_processing()::{lambda()#1}::operator()() const
                                    |
                                    |
                                   \|/
bool boost::lockfree::queue<steem::plugins::chain::write_context*>::pop<steem::plugins::chain::write_context*>(steem::plugins::chain::write_context*&)
```
![call_graph](https://user-images.githubusercontent.com/6341057/74093109-d1648b80-4acd-11ea-9ed3-5ff45e4d9cd1.png)

**Comment by mvandeberg** [comment]
`master` has serialization changes not present on the public testnet. It will work when the testnet is redeployed.
