### ISSUE TITLE
It appears this blockchain has been put under centralized control

### ISSUE THREAD

**Issue by pfunks** [steemit/steem#3619]
Seems like a poor decision.

**Comment by pfunks** [comment]
Hey I don't recognize any of these witnesses and I've been here since a week after the chain started. Which community members are supporting these witnesses?  They only seem to have one vote.

![image](https://user-images.githubusercontent.com/22420130/75718318-54759d80-5c98-11ea-88e6-67873cdf49fb.png)

**Comment by KINGdotNET** [comment]
It will takes a while to join the Top 20 witnesses. These accounts are proxy by some big crypto exchanges.

**Comment by pfunks** [comment]
I can't seem to find the code for this version 0.22.5 anywhere in this repository. Isn't Steem open source?

**Comment by KINGdotNET** [comment]
Not here?
https://github.com/steemit/steem/releases

**Comment by pfunks** [comment]
@jiangyy0824 it appears this is still an ongoing issue. Even some of the new witnesses are centralized sockpuppets.  Perhaps you hit the wrong button

**Comment by Smittyvb** [comment]
@pfunks Not sure if you are aware, but there is a hardfork (Hive) without this centralized control.

**Comment by pfunks** [comment]
Ah so this steem project is deprecated? Got it.
