### ISSUE TITLE
Unusual behaviour with formatting on CLI wallet OSX v10.11.6 (15G31)

### ISSUE THREAD

**Issue by c055** [steemit/steem#362]
I'm facing issues with CLI wallet currently -- autocomplete etc functions are not working for me.
is there some trick to get it work again .. IIRC this was working when i was play with in march.

let me know if u would need some more infos

for example, when using  `arrow UP` to make use of clip board i'm getting 

`^[[A`

Any idea why this happens? Any advise is highly appreciated

**Comment by mvandeberg** [comment]
This is the result of readline not being properly configured into the project with cmake. I have the same problem with my environment and have not spent the time investigating why readline isn't configured correctly.

**Comment by cassiopaia** [comment]
ok yea but it's really exhausting to have each time write all again .. but thanks for you fast reply!

**Comment by pmconrad** [comment]
Speaking of readline - readline is licensed under the GPL. The steem license is incompatible with that. You should either remove readline, or make steem free software.

**Comment by cassiopaia** [comment]
thanks for clarification on this peter!

**Comment by roadscape** [comment]
A workaround: 

    brew install readline

    brew link readline --force
    make cli_wallet
    brew unlink readline

**Comment by alexant123** [comment]
Strange, if it helps, cause my same problem still with it: 
```
brew install readline

brew link readline --force
make cli_wallet
brew unlink readline
```
