### ISSUE TITLE
SMT hardfork date should be moved back to prevent accidental hardforking

### ISSUE THREAD

**Issue by Smittyvb** [steemit/steem#3624]
https://github.com/steemit/steem/blob/ff9b801615ba8c347a0c3f534ad06adc551b58e5/libraries/protocol/hardfork.d/0_23.hf#L8

This line will cause a hard fork on Aug 20 2020. This date should be moved back to prevent issues.

**Comment by pfunks** [comment]
If this blockchain is deprecated, it's no longer an issue needing attention. Probably best to delete this issue, so that it is not paid any attention to.

**Comment by Benson0224** [comment]
@Smittyvb  Agree with pfunks,  and only this change will not lead to a folk. please help to close this issue, thanks.

**Comment by jiangyy0824** [comment]
@Smittyvb This configuration will not directly cause hardfork. We will modify it after confirming the time. Thank you for your suggestion.
