### ISSUE TITLE
How does the data stored in block_log? how is it possible to trim off a few blocks data from the file

### ISSUE THREAD

**Issue by bilalpakistani** [steemit/steem#3633]
Hi, 

I want to know, how the blockchain data is stored in block_log .
I happen to know, that the data gets appended to the file.

but i want to know how?
```
XXXXX
block1 data
XXXXX
block2 data
XXXXX
```

So what I want to do is, I want to remove X blocks data from the file, but I don't know exactly how to do that, without corrupting the file.

Regards
Bilal Haider KING

**Comment by netuoso** [comment]
Good luck, KING. I am sure you will figure it out.

**Comment by bilalpakistani** [comment]
@netuoso  Is it possible tho? if it is, then probably i can?

**Comment by pfunks** [comment]
Steem's already got a king.

**Comment by bilalpakistani** [comment]
@pfunks @netuoso  we can have fun some other day :stuck_out_tongue_closed_eyes:  please.

**Comment by bilalpakistani** [comment]
I solved it Thanks everyone for taking a moment to reply
