### ISSUE TITLE
170,000 Steem was removed from my account.

### ISSUE THREAD

**Issue by officiallymarky** [steemit/steem#3651]
I had over 170,000 Steem in my wallet before HF23.

![image](https://user-images.githubusercontent.com/33408375/84315529-cda64b80-ab37-11ea-8ad9-0a67af60ba53.png)

After the hard fork, I had 0.

![image](https://user-images.githubusercontent.com/33408375/84315555-d5fe8680-ab37-11ea-9fc1-0346b88a27e2.png)

**Comment by pfunks** [comment]
This blockchain is a sham run by scammers

**Comment by Smittyvb** [comment]
As you're likely aware, [this was intentional](https://github.com/steemit/steem/commit/a101bd8c31df18a4f0ca7b107491a8e2eacb6c0b#diff-5f5356c18939f3b2ce7f3e74ab944614R67).

**Comment by officiallymarky** [comment]
Oh yeah, I know.  The theft was planned and deliberate.

**Comment by DaveyD2** [comment]
-

**Comment by officiallymarky** [comment]
Thanks for returning my Steemy Justin.  Looking forward to watching how your case with the SEC turns out.
