### ISSUE TITLE
delete_comment operations not shown in get_account_history api call

### ISSUE THREAD

**Issue by keverw** [steemit/steem#366]
Hello, I noticed delete_comment isn't showing up in get_account_history but the post I did make and deleted is there still but no indications it was deleted.

It seems like the only way to watch if a post is deleted is to poll get_content...

Any workarounds? This seems like somthing that should be there is missing.

For example on my testing account you'll see testing as a article, on the site it's not there to show I deleted it. https://steemit.com/@kevintester/feed but no indication in the get_account_history api

`http://steemroll.io/api-explorer/#method=get_account_history&params=["kevintester","1000","1000"]`

Github seems to screw up the api-explorer link by adding %encodings, so copy and paste it instead.

**Comment by abitmore** [comment]
Pull request submitted #368
