### ISSUE TITLE
Request for pop blocks operation in debug_node_api

### ISSUE THREAD

**Issue by arhag** [steemit/steem#37]
Ideally the [debug_node_api](https://github.com/steemit/steem/blob/a58a849309e03a342668a14f7ebc099e97db165e/libraries/plugins/debug_node/include/steemit/plugins/debug_node/debug_node_api.hpp) would have a `debug_pop_blocks` method that will essentially "reverse time" and act like a block was never generated or pushed.

I found live debugging code to be a miserable experience because of the lack of this operation. I would realize after I had already generated blocks that I really wanted to know the state of the database some blocks ago. But I had no way to undo other than clearing the blockchain and starting all over again from an earlier snapshot that I copied in my filesystem. This slowed down my debugging process considerably.

**Comment by mvandeberg** [comment]
On my radar for things to add.

**Comment by mvandeberg** [comment]
This was added a while back.
