### ISSUE TITLE
Add the savings transactions to account object: transfer_history

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#377]
The transactions created by the following operations are needed in transfer_history:

transfer_to_savings
transfer_from_savings
cancel_transfer_from_savings

**Comment by jcalfee** [comment]
I tested all three ops, none of them are in the history.  Is another change needed?

**Comment by mvandeberg** [comment]
@bytemaster Am I missing something in how you set up transaction history?

**Comment by abitmore** [comment]
Need to add visitors [here](https://github.com/steemit/steem/blob/v0.14.1/libraries/plugins/account_history/account_history_plugin.cpp#L87-L116)?
You're querying with `--filter-posting-ops` or not?

**Comment by jcalfee** [comment]
related: 
https://github.com/steemit/steem/blob/develop/libraries/plugins/account_history/account_history_plugin.cpp#L121-L134

**Comment by jcalfee** [comment]
works .. thanks
