### ISSUE TITLE
Add process exit code to check_reflect.py

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#388]
For easily integrating with build scripts, `check_reflect.py` should `sys.exit(1)` on failure.

**Comment by sneak** [comment]
that's the spirit! :D

**Comment by theoreticalbts** [comment]
Tricky figuring out why CI was failing for this. Basically this Python script uses Python's `open()` followed by `read()` to bring the entire contents of each source file into memory, then does some string processing to extract FC reflection which is then compared against Doxygen. It works fine on my system, but fails with UnicodeDecodeError on CircleCI. Some investigation revealed the UTF-8 character [here](https://github.com/steemit/fc/blob/f59a51625690d40b9bf481c1f8b158434e9ca88e/src/crypto/base64.cpp#L6) was the culprit.

From Python docs for `open()` [here](https://docs.python.org/3/library/functions.html#open) it says "The default encoding is platform dependent" -- meaning that for some reason on the CircleCI box, it defaults to ASCII, while my system defaults to UTF-8.
