### ISSUE TITLE
Assertion issues(2) in `comment_options_evaluator`

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#391]
I'm trying to submit comment_options with a Max Accepted Payout value of: 1000000000.000 SBD

1000000000.000 SBD is the default value in the comment_options_operation .. So the intent is to leave this unchanged.

Some asserts appear backwards.  Should this be `o.max_accepted_payout >= comment.max_accepted_payout`?  When I submit a top-level comment update this is what I get:

>comment.max_accepted_payout >= o.max_accepted_payout: cannot accept a greater payout
>    {}
>    th_a  steem_evaluator.cpp:245 do_apply

transaction:
>[{"ref_block_num":23984,"ref_block_prefix":2988025508,"expiration":"2016-09-13T16:58:27","operations":[
>
>["comment",{"parent_author":"","parent_permlink":"test","author":"jcalfee","permlink":"testing-submit-story-transaction-commentoptions","title":"Testing submit story transaction: comment_options","body":"test","json_metadata":"{}"}],
>
>["comment_options",{"author":"jcalfee","permlink":"testing-submit-story-transaction-commentoptions","max_accepted_payout":"1000000000.000 SBD","percent_steem_dollars":0,"allow_votes":false,"allow_curation_rewards":false,"extensions":[]}]
>
>],"extensions":[],"signatures":["1f38d3...21e1"]}]

**Comment by jcalfee** [comment]
https://github.com/steemit/steem/issues/391

**Comment by mvandeberg** [comment]
1000000.000 STEEM is the max accepted payout. You are off by 1000x. The assert is so that an operation cannot increase the accepted payout of the post. It is an agreement with the curators that the post will never receive more than that value under *any* circumstances.
