### ISSUE TITLE
intermittent test failure

### ISSUE THREAD

**Issue by sneak** [steemit/steem#393]
During documentation edits, a build failed(!)

Failing: https://circleci.com/gh/steemit/steem/21

It recovered on the next commit (to unrelated documentation).

I will create a test harness to build and run a whole ton of tests in a loop to see if I can trigger it again.

**Comment by mvandeberg** [comment]
The test case in question that failed is the following:

```
ver_str = fc::variant( "1.0" );
STEEMIT_REQUIRE_THROW( fc::from_variant( ver_str, ver ), fc::assert_exception );
```

The version string deserialization should fail because it does not contain the revision field of the version.

**Comment by theoreticalbts** [comment]
/usr/local/src/steemtest/tests/tests/serialization_tests.cpp(205): fatal error in "version_test": exception fc::assert_exception is expected
    2764747ms th_a       serialization_tests.cpp:210   test_method          ] 0 exception: unspecified
rethrow
        {}
        th_a  serialization_tests.cpp:210 test_method
    unknown location(0): fatal error in "version_test": unknown type
    /usr/local/src/steemtest/tests/tests/serialization_tests.cpp(205): last checkpoint

Looks like it's *not* throwing the exception.  Perhaps due to `char` fields uninitialized?

**Comment by mvandeberg** [comment]
That is the error `STEEMIT_REQUIRE_THROW` throws when the exception it expects is not thrown.
