### ISSUE TITLE
Bug in v0.14.1 process_decline_voting_rights

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#399]
When an account declining voting rights, all its direct witness votes and proxied witness votes should be removed. Current code removes direct votes but not proxied votes.

Code in `process_decline_voting_rights`
```
+      adjust_proxied_witness_votes( account, -account.witness_vote_weight() );
+      clear_witness_votes( account );
+
+      modify( itr->account(*this), [&]( account_object& a )
+      {
+         a.can_vote = false;
+         a.proxy = a.name;
+      });
```

Should be similar to code in `account_witness_proxy_evaluator::do_apply`
```
   /// remove all current votes
   std::array<share_type, STEEMIT_MAX_PROXY_RECURSION_DEPTH+1> delta;
   delta[0] = -account.vesting_shares.amount;
   for( int i = 0; i < STEEMIT_MAX_PROXY_RECURSION_DEPTH; ++i )
      delta[i+1] = -account.proxied_vsf_votes[i];
   db().adjust_proxied_witness_votes( account, delta );
   ...
      /// clear all individual vote records
      db().clear_witness_votes( account );
   ...
      /// update proxy
      a.proxy = STEEMIT_PROXY_TO_SELF_ACCOUNT;
```

**Comment by mvandeberg** [comment]
`adjust_proxied_witness_votes` changes the witness vote weight of an account whenever Steem Power changes. One example is when VESTS are created [here](https://github.com/steemit/steem/blob/develop/libraries/chain/database.cpp#L1064).

Calling `adjust_proxied_witness_votes( account, -account.witness_vote_weight() );` is the same as saying "power down all Steem Power immediately", at least as far as witness votes are concerned. Any account that has proxied to the account declining their rights implicitly loses their vote until they select a new proxy, which this code covers.

**Comment by abitmore** [comment]
@mvandeberg this issue is similar to https://github.com/steemit/steem/issues/33. 

> Calling adjust_proxied_witness_votes( account, -account.witness_vote_weight() ); is the same as saying "power down all Steem Power immediately"

When there is a proxy chain, you can't treat it like all weight belongs to the account itself. Otherwise invariants will be inconsistent after executed the code.

**Comment by mvandeberg** [comment]
Then our Power Up code is wrong...
