### ISSUE TITLE
error when trying update_witness

### ISSUE THREAD

**Issue by blood2** [steemit/steem#4]
ran  
```
update_witness "steempty" "fmooo/steemd-docker" STM8LoQjQqJHvotqBo7HjnqmUbFW9oJ2theyqonzUd9DdJ7YYHsvD {"account_creation_fee":"100.000 STEEM","maximum_block_size":131072,"sbd_interest_rate":1000} true
```
also tried {} instead of the json  

  
error  
```
0 exception: unspecified
10 assert_exception: Assert Exception
o.fee >= std::max( asset( (STEEMIT_PRODUCER_APR * db().get_dynamic_global_properties().virtual_supply.amount.value) / (100*STEEMIT_BLOCKS_PER_YEAR), STEEM_SYMBOL), STEEMIT_MIN_PRODUCER_REWARD ):
```

**Comment by blood2** [comment]
when i comment out that Assertion part  in steem_evaluator.cpp, the transaction is not going through (cli_wallet hangs when it trying to broadcast)

**Comment by xeroc** [comment]
I think you need to quote the JSON object:

    update_witness 'steempty' 'fmooo/steemd-docker' STM8LoQjQqJHvotqBo7HjnqmUbFW9oJ2theyqonzUd9DdJ7YYHsvD "{'account_creation_fee':'100.000 STEEM','maximum_block_size':131072,'sbd_interest_rate':1000}" true

**Comment by xeroc** [comment]
There seems to be a constraint that tells me that the fee added by the cli_wallet call is not sufficient to produce a valid witness_update transaction ..

**Comment by bytemaster** [comment]
Thanks for the report, we are looking into it and will have a solution soon.  In the mean time you can try increasing the account creation fee specified until it works.
