### ISSUE TITLE
Witness node hang

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#40]
The witness node sometimes just hang and stop receiving blocks.

I finally caught it in gdb.

Running steem v0.3.0 on Ubuntu 14.04 64bit
>
pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
238     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000a13b68 in boost::cv_status boost::condition_variable::wait_until<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > >(boost::unique_lock<boost::mutex>&, boost::chrono::time_point<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > > const&) ()
#2  0x0000000000a161a8 in fc::thread_d::process_tasks() ()
#3  0x0000000000a16216 in fc::thread_d::start_process_tasks(long) ()
#4  0x0000000000ca55f1 in make_fcontext ()
#5  0x0000000000000000 in ?? ()

**Comment by theoreticalbts** [comment]
Closing due to:

- Ticket age
- In this case, backtrace doesn't contain any information which could help diagnose the problem
