### ISSUE TITLE
Reindexing terminated due to gap

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#407]
This is an old issue which occurs occasionally.

```
478425ms th_a       database.cpp:148              operator()           ] Reindexing terminated due to gap:  Block 4812647 does not exist!
```

After seen it, people need to wait for a while (it can be as long as 30 minutes or so) for the node to crash, then after restarted the node will work. If the node is killed before crashing by itself, after restarted, the above error will occur again.

I think the gap itself is related to block reorganization. 

This issue is probably low priority. I'll take a look at it when have time.

**Comment by mvandeberg** [comment]
I have noticed this problem occurring after the node shuts down improperly. My node then starts up with around 10x as many blocks, hits the previous head block time and then scans the remainder of the file looking for other blocks. I am guessing there is a bug in the shutdown code that is causing steemd to write blank or junk data the block_db file, although I have not inspected the file itself in such a scenario to see what it contains.

**Comment by abitmore** [comment]
I got some logs from one of my nodes:
```
2185657ms th_a       database.cpp:148              operator()           ] Reindexing terminated due to gap:  Block 4825043 does not exist!
3537128ms th_a       database.cpp:162              operator()           ] Dropped 140337 blocks from after the gap
3537128ms th_a       application.cpp:359           startup              ] 10 assert_exception: Assert Exception
Internal error: static_variant tag is invalid.
    {}
    th_a  static_variant.hpp:134 apply

    {"data_dir":"/data/steem/witness_node_data_dir/blockchain"}
    th_a  database.cpp:200 reindex
3537128ms th_a       application.cpp:906           startup              ] 10 assert_exception: Assert Exception
Internal error: static_variant tag is invalid.
    {}
    th_a  static_variant.hpp:134 apply

    {"data_dir":"/data/steem/witness_node_data_dir/blockchain"}
    th_a  database.cpp:200 reindex
rethrow
    {}
    th_a  application.cpp:359 startup
3537128ms th_a       main.cpp:196                  main                 ] Exiting with error:
10 assert_exception: Assert Exception
Internal error: static_variant tag is invalid.
    {}
    th_a  static_variant.hpp:134 apply

    {"data_dir":"/data/steem/witness_node_data_dir/blockchain"}
    th_a  database.cpp:200 reindex
rethrow
    {}
    th_a  application.cpp:359 startup
```

I also have a backup of the data dir, will try to analyse when got time.

**Comment by bytemaster** [comment]
This issue has been fixed by new chainbase system and block_log

**Comment by Tadasu85** [comment]
Dan could you possibly provide the push that fixed this issue in the new chainbase system please?

**Comment by mvandeberg** [comment]
This is less of a fix and more of an architectural rework that prevents such a case from occurring. Chainbase is an entirely different underlying database architecture from what Graphene uses. It so happens to have a similar interface for building blockchains on.
