### ISSUE TITLE
Potential unexpected behavior while calculating median feed?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#409]
While calculating median feed, need to compare feed prices to each other (code [here](https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/database.cpp#L2910-L2912),[here](https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/database.cpp#L2923)).

Format of feed prices can be either `{base:"xxx STEEM", quote:"yyy SBD"}` or `{base:"xxx SBD", quote:"yyy STEEM"}`, both are valid. Currently, most if not all witnesses are using the latter format. However, it's possible that some will use the other format in the future, which will cause unintended behavior while comparing due to [the comparison code](https://github.com/steemit/steem/blob/develop/libraries/chain/protocol/asset.cpp#L93-L96):

```
      bool operator < ( const price& a, const price& b )
      {
         if( a.base.symbol < b.base.symbol ) return true;
         if( a.base.symbol > b.base.symbol ) return false;
         if( a.quote.symbol < b.quote.symbol ) return true;
         if( a.quote.symbol > b.quote.symbol ) return false;
```

It's not a big deal as long as majority of active witnesses/miners use same format.

**Comment by mvandeberg** [comment]
I believe there was originally a restriction on base and quote symbols for the price feed that was inadvertently removed. It would be easy enough to add the requirement back in.

**Comment by mvandeberg** [comment]
This was fixed in hardfork 14 [here](https://github.com/steemit/steem/blob/master/libraries/chain/steem_evaluator.cpp#L79-L82).

**Comment by mvandeberg** [comment]
Don't know what I was thinking when I closed this issue, but the referenced code does not fix the problem.

**Comment by mvandeberg** [comment]
Will be fixed in #1620

**Comment by mvandeberg** [comment]
HF 20 will require the base to be SBD and the quote to be STEEM.

**Comment by mvandeberg** [comment]
This is from a quick check that most witnesses publish their price feed in this format. The change should impact the fewest number of people possible.
