### ISSUE TITLE
Attack to steal SP using active authority only

### ISSUE THREAD

**Issue by arhag** [steemit/steem#41]
I think updating the witness account to a new block signing key only requires active authority. This is a security concern because of how much power the block signing key has. An attacker that wants to steal a user's SP and has access to their active keys needs to:

1. If the victim doesn't have enough votes already, the attacker uses some of their own SP to vote for the victim.
2. The attacker predicts ahead of time roughly when the account will be scheduled as a runner-up witness. This is possible to do fairly accurately (ignoring large vote changes). Also, the attacker can err on predicting too early as much as they want with the only disadvantage being that the victim may be aware of compromise sooner.
3. A reasonable amount of time before when the account is scheduled to be a runner-up witness, the attacker changes the victim's block signing key to one the attacker controls.
4. The attacker intentionally double signs blocks under the victim's name and at the same time submits a proof of double sign to collect the victim's SP as a reward. It isn't guaranteed that the attacker will receive the reward, but the chances are good enough.

Alternative strategies to the above are:
- If the user has enough votes to vote the victim into top 19, they don't need to make the predictions in step 2. They only need to signal to the victim that their account was compromised for less than 66 seconds before they are able to successfully finish their attack.
- If the attacker has little voting power and doesn't want to wait too long for the victim to be a runner-up witness, the attacker may find it faster to instead solve a PoW under the victim's name (this also only requires active authority). For typical mining queue lengths (100), this means that the attacker signals to the victim that their account was compromised for less than 107 minutes before they are able to successfully finish their attack.

One potential fix for this problem is to allow providing a `block_signing_key` in the `witness_update_operation` to be optional (if none specified, the blockchain would just keep the previous signing key), *and* if a `block_signing_key` is specified, the blockchain would require the transaction containing the `witness_update_operation` to be signed by the owner authority of the corresponding account.

The problem with the above fix is that requires monitoring scripts that work by automatically detecting and switching over redundant block-signing witness nodes (by changing the block signing key) to keep the owner private key in the servers running the monitoring nodes. While signing keys currently give holders power over an account that owner authorities do not have (namely stealing SP as described in the above attack), it is also true that owner authorities have power over an account that signing key holders do not have (e.g. owning the account name). So a more elegant fix would be to take the above fix and modify it so that a `witness_update_operation` that changes the block signing key can also be validated by being included in a transaction signed by the current signing key (this won't mess up double signing proofs will it?). That way monitoring and switch-over management nodes need to hold all potential signing keys rather than the owner keys (those same keys are all necessarily on online servers anyway). And the user gets to keep their owner keys in cold storage where they belong.

**Comment by bytemaster** [comment]
In other words, block producers should not produce with accounts that have high steem balances and should guard their keys.  

In theory only active witnesses should be able to steal funds from other active witnesses. A reporter has no way to prevent the active witnesses from frontrunning him.

If only witnesses in the top 19 by total votes are able to report an abuse, then the probability of an attack falls to 0.  

Conclusion: this weakness only makes witness funds equally vulnerable to Bitcoin or other cryptocurrency funds.

**Comment by arhag** [comment]
>In theory only active witnesses should be able to steal funds from other active witnesses. A reporter has no way to prevent the active witnesses from frontrunning him.
>
>If only witnesses in the top 19 by total votes are able to report an abuse, then the probability of an attack falls to 0.

Good point on the front running. I'm not motivated enough right now to estimate the true probability of an attacker successfully using double sign proofs as a way to steal the funds of a victim who is not in the top 19. But the attack would require the attacker to have many miners in the queue to increase the probability that one of their miners will be scheduled to produce a block immediately after the scheduled runner-up witness of the victim. As soon as they get lucky to be scheduled in that manner, they can change the signing key of the victim to one they control and their carry out the attack. It may take several days of heavy mining before they get the desired witness schedule (far more than that if the victim has few votes), but it might still be profitable for the attacker.

Furthermore, there may be motivations other than pure financial reward. An attacker with access to the private active keys of the victim can wait a very short time (with no mining cost) to carry out an attack that hurts the victim (even if they get no profit from it) by causing them to lose all their SP. They just use some of their SP to vote for them (if they don't have enough votes already), wait until they are scheduled as a runner-up witness, then change their signing keys and double sign blocks. One of the other active witnesses would collect the reward, but the attacker would succeed in their goal of hurting the witness.

There is no way (currently) in Steem to mark a flag on your account that you do not wish to be considered in the `update_witness_schedule` algorithm in a way that the blockchain respects (my new scheduling algorithm makes this very straightforward to implement by the way). Having a mechanism to mark such a flag (only changeable by owner authority) would provide *regular users* (not miners or witnesses campaigning for votes) reassurance that they could not become victims of such an attack as long as they keep their owner keys safe. And I understand it isn't that likely for such an attack to occur against regular users, but I think the reassurance it provides regular users is worth the minor implementation effort.

**Comment by theoreticalbts** [comment]
Since report_over_production has been removed as of HF 0.4, this ticket is no longer relevant.
