### ISSUE TITLE
Asset type of account_creation_fee is not validated

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#410]
If one of active witnesses (including elected witnesses and miner witness) set the account creation fee to SBD for example, and the amount is median of all, the global parameter will be set to that amount and asset type for one round. Fortunately it will not shutdown the whole network. But it will likely effectively prevent new accounts from being registered in that round. It will also prevent non-mined accounts from powering down in that round.

https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/database.cpp#L1440-L1449
```
   /// sort them by account_creation_fee
   std::sort( active.begin(), active.end(), [&]( const witness_object* a, const witness_object* b )
   {
      return a->props.account_creation_fee.amount < b->props.account_creation_fee.amount;
   } );

   modify( wso, [&]( witness_schedule_object& _wso )
   {
     _wso.median_props.account_creation_fee = active[active.size()/2]->props.account_creation_fee;
   } );
```

https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/include/steemit/chain/protocol/asset.hpp#L49-L53
```
      friend bool operator < ( const asset& a, const asset& b )
      {
         FC_ASSERT( a.symbol == b.symbol );
         return std::tie(a.amount,a.symbol) < std::tie(b.amount,b.symbol);
      }
```

https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L93-L95
```
      FC_ASSERT( o.fee >= wso.median_props.account_creation_fee, "Insufficient Fee: ${f} required, ${p} provided",
                 ("f", wso.median_props.account_creation_fee)
                 ("p", o.fee) );
```

https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L692-L696
```
      asset min_vests = wso.median_props.account_creation_fee * props.get_vesting_share_price();
      min_vests.amount.value *= 10;

      FC_ASSERT( account.vesting_shares > min_vests,
                 "Account registered by another account requires 10x account creation fee worth of Steem Power before it can power down" );
```

**Comment by mvandeberg** [comment]
In `witness_update_operation::validate` https://github.com/steemit/steem/blob/develop/libraries/chain/protocol/steem_operations.cpp#L147
``` c++
FC_ASSERT( fee >= asset( 0, STEEM_SYMBOL ), "Fee cannot be negative" );
```

In `asset.hpp`

``` c++
friend bool operator == ( const asset& a, const asset& b )
{
   return std::tie( a.symbol, a.amount ) == std::tie( b.symbol, b.amount );
}
friend bool operator < ( const asset& a, const asset& b )
{
   FC_ASSERT( a.symbol == b.symbol );
   return std::tie(a.amount,a.symbol) < std::tie(b.amount,b.symbol);
}
friend bool operator <= ( const asset& a, const asset& b )
{
   return (a == b) || (a < b);
}
friend bool operator != ( const asset& a, const asset& b )
{
   return !(a == b);
}
friend bool operator > ( const asset& a, const asset& b )
{
   return !(a <= b);
}
```

This is convoluted, but the important part is that the asset symbol effects the direction of an inequality. To confirm what I believed to be true, I wrote this test, which passes.

``` c++
BOOST_AUTO_TEST_CASE( asset_test )
{
   FC_ASSERT( asset( 1, SBD_SYMBOL ) <= asset( 0, STEEM_SYMBOL );
}
```

Thus any witness update operation that has SBD as the account creation fee will not be valid.

**Comment by abitmore** [comment]
@mvandeberg I did a test with an old debug_node and successfully set a fee in SBD for a witness.

```
unlocked >>> get_witness xxx
...
  "props": {
    "account_creation_fee": "6.000 SBD",
    "maximum_block_size": 2265536,
    "sbd_interest_rate": 1000
  },
...
```

Oh I got it. The `fee` field in `witness_update_operation` is not for global properties, but a unused field. The operation in the trx looks like this: 

```
...
      "witness_update",{
        "owner": "xxx",
        "url": "https://steemit.com/",
        "block_signing_key": "STMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "props": {
          "account_creation_fee": "6.000 SBD",
          "maximum_block_size": 2265536,
          "sbd_interest_rate": 1000
        },
        "fee": "0.000 STEEM"
      }
...
```

**Comment by abitmore** [comment]
@theoreticalbts's patch doesn't fix this issue.
