### ISSUE TITLE
More checks in reset_account_operation::validate()?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#412]
Some checks about `new_owner_authority` exists in `recover_account_operation.validate()` but not in `reset_account_operation::validate()`.

By the way, probably better to use the new account name validate function `validate_account_name(...)` in
* decline_voting_rights_operation::validate()
* reset_account_operation::validate()
* set_reset_account_operation::validate()

**Comment by mvandeberg** [comment]
I have already addressed these problems in a local branch as part of my reset account audit. The `validate_account_name` change was part of my audit on error messages. Some branches were merged after that change that did not get audited. I am making changes as I see them.

Referencing back to reset account ticket for documentation of this problem. #240
