### ISSUE TITLE
Error message "can only update owner authority once a minute"

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#413]
https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L140

According to config.cpp, it should be once a hour.

**Comment by mvandeberg** [comment]
Thanks. I believe it was once a minute for a small time in development and we bumped it to owner an hour.

**Comment by abitmore** [comment]
Another message here: https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L240

"operations contains options that are only updatedable on an account with no rshares"
should be "... on a comment ..."

**Comment by abitmore** [comment]
More message: https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L423, https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L428

"The permlink of a comment cannot change"
should be "The parent permlink of ..."

**Comment by abitmore** [comment]
https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L1470

"account does not sufficient balance" is strange.

**Comment by abitmore** [comment]
https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L1610

"cannot recover an account that does not have you as there recovery partner"
should be "... as their ..."

**Comment by abitmore** [comment]
https://github.com/steemit/steem/blob/v0.14.1/libraries/chain/steem_evaluator.cpp#L1656

"there are no active recovery requests for this account"
perhaps should be "there is no active recovery request for this account"?

**Comment by mvandeberg** [comment]
This was fixed some time ago.
