### ISSUE TITLE
Possible to recover / reset owner authorities of temp and/or null account?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#414]
Possible to recover / reset owner authorities of temp and/or null account?

**Comment by mvandeberg** [comment]
Related #240

**Comment by mvandeberg** [comment]
Regarding recovery. They have no recovery authority set so the lead witness has rule over the recovery of those accounts. We can disable these operations on the blockchain for these accounts.

**Comment by lomashuk** [comment]
@mvandeberg  What does it mean?
If somebody don't have recovery authority it is mean that lead witness can recover that account?
Does it work now?

**Comment by abitmore** [comment]
@lomashuk most users have "steem" as their recovery account (by default) so it's able to recover their accounts. I this ticket we're talking about the special "null" account and "temp" account, so, don't worry.

**Comment by lomashuk** [comment]
Thanks @abitmore for your response) But as I understand only reset_account give a chance for the recovery. And i have null their( 

"recovery_account": "steem",
"last_account_recovery": "1970-01-01T00:00:00",
"reset_account": "null",

I don't have even posting key. I used Dash Lane and when I lose my Mac and checked my back up I didn't find there security notes) So be careful with password managers...

**Comment by abitmore** [comment]
The account reset feature won't be activated until another hard fork (15+), and still many things in discussion. Thanks for your input.

**Comment by lomashuk** [comment]
@abitmore thanks) My final question: What will you recommend to me to recover my account?
90 000 people are registered now and a lot of them can have the same problem...

**Comment by abitmore** [comment]
@lomashuk: wait for the reset feature. In the mean while you can try to contact support team of steemit.com:
* contact@steemit.com
* https://www.facebook.com/steemit
* https://twitter.com/CertainAssets

**Comment by mvandeberg** [comment]
There are two different features between account recovery and account reset. 

Account recovery has been live for two months now. It allows you to quickly recover your account from a hack. It requires both the recovery account and the owner of the account in question to agree that a hack occurred and how to deal with it. For accounts that have Steem as their recovery account, there is an automated process that can recover your account in most cases. We handle others manually on a case by case basis.

Account reset is a longer term option. It is for people that are locked out of their accounts entirely. After 60 days of inactivity, the reset account can change the owner key of an account, granting access to the owner of the account again. This feature is currently under development and will be deployed at a later hardfork.

**Comment by lomashuk** [comment]
@mvandeberg How can I restore my account? https://steemit.com/@creator
If i have only my first password? Then I changed, it was more than 30 days ago.
How can I restore it manually?

**Comment by mvandeberg** [comment]
The authorities of these accounts cannot be changed so a recovery cannot be started.
