### ISSUE TITLE
Dosn't do anything after clean install!

### ISSUE THREAD

**Issue by cryptid11** [steemit/steem#422]
I do
`./steemd -s 52.38.66.234:2001 --rpc-endpoint=127.0.0.1:8090`

after modifing config.ini in steem/programs/steemd/witness_node_data_dir to this: http://pastebin.com/dCXBZ8Yf

And printing this it's all it does:

```
------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
------------------------------------------------------
2342494ms th_a       witness.cpp:101               plugin_initialize    ] _witnesses: [] 
2342501ms th_a       thread.cpp:95                 thread               ] name:ntp tid:140669032380160
2342501ms th_a       thread.cpp:95                 thread               ] name:p2p tid:140669023987456
2342522ms th_a       witness.cpp:189               plugin_startup       ] No witnesses configured! Please add witness names and private keys to configuration.
2342522ms th_a       witness.cpp:197               plugin_startup       ] No miners configured! Please add miner names and private keys to configuration.
2342541ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to 1509 us

```

I'm on a fresh installed ubuntu 16, I follow the instructions here: https://github.com/steemit/steem/blob/develop/doc/build-ubuntu.md

**Comment by abitmore** [comment]
Press ctrl+C to kill the program, and then restart.

**Comment by cryptid11** [comment]
Good joke, I do it 100 times already.

**Comment by abitmore** [comment]
Looks like your node didn't try to connect to other seed nodes. You specified `-s 52.38.66.234:2001` in the command, if you have default log level set to `info` it will at least show something like this:
```
3454157ms th_a       application.cpp:104           reset_p2p_node       ] Adding seed node 52.38.66.234:2001
```

Your config file looks OK, but your output didn't show related log entries, which perhaps means your config.ini is not placed in the correct place. 

Try `ps -ef|grep steemd` to check if there is any process running in background and listening on the same port.

**Comment by cryptid11** [comment]
> config.ini is not placed in the correct place.

I told you where it is. I try that and obviously there is only mine.

Actually I solve the problems even if I would like to understand why it solve, before I cheated I do not write relative path being in the folder but actually I start steem with full path like /path/path/steemd,  now it works with relative path, even if this is quite strange and I don't understand why. But my fault I dont try this before, seems quite incredible to me also....

**Comment by abitmore** [comment]
> I start steem with full path like /path/path/steemd

Yes, this caused that steemd didn't find the config.ini in the place you put, because it will always try to locate the file in **current_path/witness_node_data_dir** where you start the program. Fortunately you find it out by yourself. You didn't describe the full story here so it's hard for people to guess what's wrong.

I always start `steemd` with a script like this:
```
/full/path/to/steemd --data-dir="/the/full/path/to/the/data/dir" -s 52.38.66.234:2001 --rpc-endpoint=127.0.0.1:8090 --replay
```

**Comment by cryptid11** [comment]
Thanks that command it's useful to me, another thing, I just discover it stuck at certain point with full ram and near full swap - updating but really slow - so you should write in info you need 16 GB ram to run this program, I try to cmake with -DLOW_MEMORY_NODE=ON option but it fails, maybe I will report the error on another issue, for now will simply buy other 8 GB of ram...

**Comment by mvandeberg** [comment]
What is your config.ini?

What OS and version are you running?

We have gotten some reports of incredibly high RAM usage but have been unable to reproduce using a basic witness node config.

**Comment by cryptid11** [comment]
> What is your config.ini?

Linked in first post.

> What OS and version are you running?

Also, Ubuntu 16, precisely "Linux rodden 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"

I just install the other 8 GB let's see if it works at least with 16 GB...

**Comment by cryptid11** [comment]
It just synced, it is using 12 GiB now, so 16 GB of RAM will be good until the end of the year at least it seems, also I will like to know how is possible a program will behave so unexpectedly in the most diffuse distribution on this planet, so if you get any new hint or need some info let me know.

**Comment by mvandeberg** [comment]
Try running without the account history plugin. Or specify the account range you're interested in.

**Comment by abitmore** [comment]
@cryptid11 I've given your my advice in previous comment, perhaps not so explicit though: start node with `--replay`
