### ISSUE TITLE
CI testing automation is slow.

### ISSUE THREAD

**Issue by sneak** [steemit/steem#426]
slow tests do not entail death, slow tests are death.

**Comment by mvandeberg** [comment]
The tests themselves are a couple of minutes at most. Most of the time is spent on two 15+ min builds.

**Comment by sneak** [comment]
ahh - didn't mean to assign blame to the test suite itself - i meant "CircleCI tests" which includes the whole thing (my design).  Going to try to pare it down.

**Comment by mvandeberg** [comment]
Didn't think you were. Just wanted to make sure you were spending your time optimizing the correct part of the CI test process.
