### ISSUE TITLE
Language standardization in Steem

### ISSUE THREAD

**Issue by samupaha** [steemit/steem#430]
Steem needs a standard way of telling what language the post is written in. If there is no standard, it's really hard for UI to filter posts and show only the languages that user understands. For a good user experience, it's not preferable to show languages that the user doesn't understand.

If there is no standard, UIs will have to use other means to detect the language and filter the posts. I don't see it as a great solution.

My suggestion is that Steem should implement a language tag feature. It is the most easiest way as far as I can see. Tag system already exists, so the only thing that is needed for standardization is to decide what kind of tag is a language tag.

Best standard to specify a language is [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3). It includes all written languages and has a three letter code for each of them. It's perfect for our needs.

Language tag could be, for example, expressed in a format like this: ``#iso639-3-xxx``, where xxx is the language code. Another possibility might be to replace hash with some other special character (like ``%xxx``). Or use double hash to do it (``##xxx``).

Currently the amount of tags that a post can have is limited. This limitation should not be applied to language tags. A user should have possibility to insert at least two language tags per post. We have already seen lots of bilingual posts in Steem. Also everybody who wants to teach a language needs to write with at least two languages. But we don't know what kind of use cases there will be in the future, so I suggest that we limit language tags to five per post in the beginning. If a legitimate use case appears that will need more tags, we can always add them later.

**Comment by mvandeberg** [comment]
There is a json metadata field on the comment object and operation for just these types of situations.

**Comment by mvandeberg** [comment]
Since steemd supports this type of extensions, I am closing this. This is an issue that should be posted for Steemit.com https://github.com/steemit/steemit.com

**Comment by wgsmit02** [comment]
Yes, please add this, your platform is very difficult to use due to this lacking feature, and please don't tell me to program an extension, this is not the user experience that will make this platform successful.

**Comment by ausbitbank** [comment]
> Yes, please add this, your platform is very difficult to use due to this lacking feature, and please don't tell me to program an extension, this is not the user experience that will make this platform successful.

It's a dead project, they're not doing anything anytime soon. Check out Hive for the evolution of Steem after the hostile takeover
