### ISSUE TITLE
Plan: Idea how to get longterm money into the steem system

### ISSUE THREAD

**Issue by polluxOne** [steemit/steem#433]
This idea was created during the nuremberg meetup and approved by @xeroc (in fact he told me to post this idea as an issue here): 

Hopefully this could be the initial of a "Big Thing" for steemit. Personally, I don´t have the position of talking to advertisers, so I share the idea here and on steemit.

So in short: 
Consideration 1: Steem articles are ranked excellently ranked in Google
Consideration 2: Steemit is based on voluntary principles, which must be respected in any case
Consideration 3: Steem will long term only work, if there is a reason to buy and keep Steem and SteemPower
Consideration 4: The biggest budgets for interest in the meaning of virtual attention is found in advertising.

Solution:
Making voluntary advertising like this (this principle can be "sold" to any advertiser)

1)Buy Steem and change it into SteemPower (you have to reach the power that your upvote is worth 1-10 Cents or the amount you like)
2) using the hashtag "advertising" (or a new section in Steemit) you can do a post with: 
    "product xyz :  get payed for your comment amount 2 Cent"
3) each comment gets an upvote by the advertiser (of course only for the first comment per user. It should be easy to use an upvote bot, capable to filter this.)

I hope this is not, too bad an idea. Read more: https://steemit.com/steem/@pollux.one/how-to-get-money-into-the-system-and-make-steemit-really-self-sustainable-deutsche-uebersetzung

**Comment by theoreticalbts** [comment]
Closing this ticket for the following reasons:

- I don't think any code needs to be added to the blockchain itself to support this idea.
- Discussions of economics and marketing are helpful and potentially important to future growth of the Steem ecosystem.  But such discussions are off-topic for this bug tracker.
