### ISSUE TITLE
Linux hard drive activity

### ISSUE THREAD

**Issue by yield65** [steemit/steem#434]
Hi,
I have a default installation of kubuntu 16 x64 just to test steemd, the computer has 2 hard drives one for / and the other for /mnt/repositories in which I git-cloned and compiled steem.
When I run steemd just as witness (I don't really want to mine) it runs without errors but the activity of the first hard drive is very intense and the drive in which steem is stalled is very low. I see it only holds the database on witness_node_data_dir which is around 1.2Gb and this folder is also on the second hard drive, so, why is it that the first hard drive is taking all the activity?
My second drive is a 250Gb 7200RPM and the first one is a SSD of 60Gb.

**Comment by Gandalf-the-Grey** [comment]
Just guessing: Low on RAM and your swap is located on first drive?

**Comment by yield65** [comment]
4Gb of RAM and yes, SWAP is on first drive.

**Comment by Gandalf-the-Grey** [comment]
Hard to say, as a quick example v0.13.0 is consuming 5GB on one of my nodes for one role (minimum plugins) and 13GB on another (for web apps), whether v0.14.2 running as a witness node needs less than 1.5GB (currently).

**Comment by yield65** [comment]
I terminated the process, added the option to ignore post operations and after that it used much more less resources, I also changed the swap partition to the second drive but it didn't use it like before.
Now is running well, thank you.

**Comment by mvandeberg** [comment]
Issue seems to be resolved.
