### ISSUE TITLE
Need a test case for addition overflow for numbers in escrow operations?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#437]
With `amount` in the `fc::safe` type, addition overflow is guaranteed not to happen. However, do we need a test case for it?

//Edit: 
Details:
According to the [code](https://github.com/steemit/steem/blob/v0.14.2/libraries/chain/steem_evaluator.cpp#L493-L501):

```
      asset steem_spent = o.steem_amount;
      asset sbd_spent = o.sbd_amount;
      if( o.fee.symbol == STEEM_SYMBOL )
         steem_spent += o.fee;
      else
         sbd_spent += o.fee;

      FC_ASSERT( from_account.balance >= steem_spent, "account cannot cover steem costs of escrow" );
      FC_ASSERT( from_account.sbd_balance >= sbd_spent, "account cannot cover sbd costs of escrow" );
```

There is no check before the additions to ensure all `steem_amount` and `fee` and `sbd_amount` be not greater than the balances `from` has.

**Comment by mvandeberg** [comment]
Overflow in `fc::safe` throws an exception. The op would fail.

**Comment by abitmore** [comment]
@mvandeberg I know that, as described in OP, it's not a bug. Just wanted to know if we need such a test case.
