### ISSUE TITLE
_index[space_id].size() > type_id, "type_id out of bounds in get_index(${space_id}.${type_id}.*)"

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#438]
<del>Because both `tag` plugin and `account_history` plugin have `SPACE_ID == 5`, when a node has `tag` plugin enabled but `account_history` plugin disabled, only these types are used
```
   tag_object_type = 3,
   tag_stats_object_type = 4,
   peer_stats_object_type = 5
```
so `_index[space_id].size` will be is 3? So unable to get any tag plugin data?
</del>

//Edit:
steps to reproduce:

<del>* build `steemd` with `LOW_MEMORY_NODE=OFF`</del>
- start node with `witness` plugin only
- call `get_content` via RPC

```
{  
   "id":4,
   "error":{  
      "code":1,
      "message":"10 assert_exception: Assert Exception\n_index[space_id].size() > type_id: type_id out of bounds in get_index(5.3.*)\n    {\"space_id\":5,\"type_id\":3,\"index[space_id].size\":0}\n    th_a  object_database.cpp:57 get_index",
      "data":{  
         "code":10,
         "name":"assert_exception",
         "message":"Assert Exception",
         "stack":[  
            {  
               "context":{  
                  "level":"error",
                  "file":"object_database.cpp",
                  "line":57,
                  "method":"get_index",
                  "hostname":"",
                  "thread_name":"th_a",
                  "timestamp":"2016-09-19T22:38:45"
               },
               "format":"_index[space_id].size() > type_id: type_id out of bounds in get_index(${space_id}.${type_id}.*)",
               "data":{  
                  "space_id":5,
                  "type_id":3,
                  "index[space_id].size":0
               }
            }
         ]
      }
   }
}
```

//Edit: the assertion code is [here](https://github.com/steemit/steem/blob/77f4d31a37d9436642e596e16a43a16423f77193/libraries/db/object_database.cpp#L57)

**Comment by mvandeberg** [comment]
The plugins both definitely work. I'm not sure what the thought process was when the object id types for the tags plugin were made... Regardless, this should be refactored.

**Comment by mvandeberg** [comment]
I run the tags plugin all the time without account history and have not had any problems.

**Comment by abitmore** [comment]
Reproduced.
* build `steemd` with `LOW_MEMORY_NODE=OFF`
* start node with `witness` plugin only
* call `get_content` via RPC

OP updated.

**Comment by abitmore** [comment]
Update: whether with `LOW_MEMORY_NODE` doesn't matter.

**Comment by arhag** [comment]
Here is the problem code:
https://github.com/steemit/steem/blob/v0.14.2/libraries/app/database_api.cpp#L937-L941

Those lines needed to be guarded by a check to see if the tags plugin is enabled (something similar to how the follow plugin is now treated in database_api is necessary for the tags plugin as well).

**Comment by mvandeberg** [comment]
I want to do a complete overhaul of how plugins work within the database api. This error does not cause the node to crash, so it isn't an attack vector (At least in my testing).

**Comment by mvandeberg** [comment]
With `has_index` added to chainbase we can more easily guard against such failures.

**Comment by mvandeberg** [comment]
#1265 gracefully handles this issue
