### ISSUE TITLE
Shutting down with SIGTERM crashes

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#439]
Shutting down **steemd** with `SIGTERM` makes it crash sometimes, surprisingly I was able to use `--replay-blockchain` without experiencing https://github.com/steemit/steem/issues/432

Huge core dump available on request.

**Comment by mvandeberg** [comment]
Can you post the core dump?

**Comment by Gandalf-the-Grey** [comment]
Due to its size shared directly instead of posting here.

**Comment by thor-the-norseman** [comment]
My steemd just kind of hangs forever after `ntp  thread_d.hpp:461 start_next_fiber`, never arriving at the command prompt.

**Comment by Gandalf-the-Grey** [comment]
the problem has gone since v0.16.0
