### ISSUE TITLE
Assert Exception -- maybe_found != nullptr: Unable to find Object -- {"id":"2.8.xx"}

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#440]
Updated to 354cd6bd and seeing some new errors when loading certain user's blogs.

```
get_state "@nonlinearone"
...
"error": "10 assert_exception: Assert Exception
  maybe_found != nullptr: Unable to find Object
      {\"id\":\"2.8.943121\"}
      th_a  index.hpp:111 get"
```

This prevents the entire blog from loading:
https://steemit.com/@nonlinearone

**Comment by physicsdude** [comment]
That was quick. Thanks @roadscape and @mvandeberg!

**Comment by physicsdude** [comment]
Thanks again! https://steemit.com/development/@nonlinearone/thank-you-steemit-and-steem-devs-for-fixing-a-tricky-bug-quickly-how-to-report-a-bug
