### ISSUE TITLE
Check for non-existing account in get_compromised_accounts() instead of using try/catch

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#441]
Reasons to get rid of exceptions in the "normal" path of control when possible:

- Having "normal" control flow paths based on exceptions makes using `catch throw` in GDB more painful because you spend time dealing with false positives
- Stylistically, exceptions should be "exceptional" circumstances, not normal
- Exceptions probably aren't great from a performance standpoint
- Our exceptions are untyped, so catch-all do-nothing blocks may inadvertently mask unintended exceptions in addition to correctly handling intended exceptions

Specifically, we can fix this in HF9 handling code by:

- Add `find_account()` method which returns pointer to account, or `nullptr` if it does not exist
- Refactor HF9 code to use `find_account()` instead of catch-all do-nothing block for exception

**Comment by mvandeberg** [comment]
merged
