### ISSUE TITLE
Content fetching APIs - minor fixes

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#445]
1) In `get_state "@user/posts"`, comment keys are returned in account.posts without '@author/' prefix, which is not consistent with how blogs and feeds are returned (as of late).

2) Loading of "recent replies" seems to be broken (after the 1st page). Here's the method: [get_replies_by_last_update(start_parent_author, start_permlink, limit)](https://github.com/steemit/steem/blob/76592f04af4a46bce9e8ad2d84020f7ed2b258c0/libraries/app/database_api.cpp#L1013)

Locally, I got the method to work (seemingly) as expected by making the following change:

```
-   bool filter_by_parent_author = true;
+   bool filter_by_parent_author = false;
```

**Comment by theoreticalbts** [comment]
@mvandeberg if this is merged, can this ticket be closed?
