### ISSUE TITLE
Add support for alternate language representation of a comment

### ISSUE THREAD

**Issue by ltogniolli** [steemit/steem#450]
Currently multi-language posts are often created on steemit by intermixing both languages in the same document [example](https://steemit.com/photography/@ace108/dining-one-of-the-top-10-gourmet-restaurants-in-the-world-by-ace108). This is not an ideal format for readers of either language.

Once steemit.com supports specifying language a post is written in (see steemit.com/issues#300) it should be possible to link different language representations of the same content as such in the blockchain.

Ideally this should be done in a way that a user could set his preferred language in the frontend and the proper content should be served to him if available.  

Possibly votes for an alternate representation of a content should be counted along the main content. If a different user submits a translation of an existing article, it should be represented similarly to a child comment in the blockchain (but not in the frontend).

**Comment by mvandeberg** [comment]
This could be handled by uploading repeated copies of the content and then defining metadata to instruct proper reading of the text. The blockchain supports full UTF-8. As this can be implemented using the existing tools and does not effect consensus, I am closing this ticket.
