### ISSUE TITLE
Allow post to destinate all (or most) author rewards to child comments

### ISSUE THREAD

**Issue by ltogniolli** [steemit/steem#451]
When looking at some of the most popular original content communities in reddit (like [writingprompts](https://www.reddit.com/r/writingprompts), [askreddit](https://www.reddit.com/r/AskReddit/), [askhistorians](https://www.reddit.com/r/AskHistorians/)), most of the value of the content is not on the original poster, but in the replies of the post.

In the Steem model, due to larger exposure of the main post, most of the rewards would be destinated to the original poster, not the commenters. Commenters would be incentivated of replying by creating their own posts and linking from there, in order to maximize exposure and gaining followers.

If the main post could be explicitely marked as to destinate all (or most) the author rewards to child commenters, steemit could be a very inviting place to foster this kind of comunities.

**Comment by faddat** [comment]
Hot.  I proposed something like this waaaaay back in the day:

https://steemit.com/content/@faddat/wow-this-platform-here-are-my-thoughts-on-keeping-it-awesome

And in fact, this remains the way that I think steemit should work.  Medium's policy of treating comments exactly as stories would have the effect of obliterating the difference between comment and story post values, and I think that this is an important step forward for us.  Comments are content too, and they take time to write, too.  So, I'm in favor of BOTH your suggestion, @ltogniolli and the idea of posts and comments carrying equal financial and social value on the site.  Difference being that in posts like what you mentioned, comments would get even more.  

Yes, comments.  Comments breathe life into our community, for sure :D.

**Comment by iamsmooth** [comment]
Something like this (though in that proposal it would apply to all posts) was proposed a while back and rejected. The issue is that any high reward-value post would create a mining market for spam comments trying to grab a piece of that extra reward.

Interestingly, the original design considered the reddit model and actually paid a portion of comment rewards upward toward the main post, on basis that making a main posts (and comments) that sparks a lot of child comment activity is itself valuable. That too was removed, with the intent to better-reward comments.

I think comment rewards are actually working pretty well now. I see small rewards sprinkled around pretty often, and very occasionally large ones.

**Comment by ltogniolli** [comment]
I agree that the current model works pretty well right now, I wouldn't want this to be the norm. But it might be a reverse causation thing: the reason it works well is because it invites the kind of content that is popular on steemit today - I'm hoping to promote a different kind of niche (discussion-heavy communities, where posts ask questions, set the theme, or otherwise spark discussions).

I think the spam issue would be handled well by the existing mechanisms we have today, voting on worthy content and flagging spammy ones. The rshares-squared model also takes care of making sure not much of the reward pool goes to those.

 High value posts already invite this kind of low-value comments today due to the extra visibility and it's not a big problem reward-wise, I believe.

**Comment by faddat** [comment]
I feel that all of this is going to be addressed only over time, as the blockchain evolves.  The site certainly isn't broken by any means.  

Here's some thoughts:
* Comments are undervalued today
* The current posting mechanism might make it hard to adopt to other formats (forums come to mind very readily)
* Sidechains could add alternative currencies for alternative communities.  

And in the end, it all comes back to:

https://www.youtube.com/watch?v=Vhh_GeBPOhs

I hope everyone in the community will take time to reach out to the devs in their world and show them what we've got.  As soon as that gets recognized, 100m is going to look like a really teeny valuation for "all the steem"

**Comment by mvandeberg** [comment]
This proposal is usurped by reward sharing introduced in 0.17.0
