### ISSUE TITLE
Node setup doc: install NTP package/service by default

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#462]
Can we include installing NTP package/service to the default witness node setup guide, although it's not a dependency, it's best practice to have it for block producing nodes as well other nodes.

**Comment by faddat** [comment]
Great idea!  

I've forgotten NTP a few times only to have "strange things" come up on the logs :)

**Comment by sneak** [comment]
We're going to stick specifically to steem-the-codebase-related things in the repo. Other system setup scripts belong in separate deployment configurations/repos.
