### ISSUE TITLE
shared-db branch does not sync

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#463]
In block 3705111 this op exists in the live blockchain:

```
"account_update",{
    "account": "jesus2",
    "posting": { "weight_threshold": 1,
      "account_auths": [["STM6GVCS7JeftT274UDKSFD2PGFMsJUxWMmQyTDCDnUouWkcReRFo",1]], ...
}}
```

Apparently this user inadvertently attempted to use a key as an account authority, and apparently the blockchain doesn't check:
- That accounts named as `account_auths` currently exist
- That the length of account names in `account_auths` is reasonable

On the `shared-db` branch, the block looks like this:

```
"account_update",{"account":"jesus2","posting":{"weight_threshold":1,"account_auths":[["STM6GVCS7JeftT27",1]], ... }}
```

So we can see `shared-db` branch code deals with this block by truncating the account name, leading to an incorrect Merkle hash, which causes pushing the block to fail.

**Comment by mvandeberg** [comment]
This is a rather unfortunate bug...

**Comment by mvandeberg** [comment]
Blocks with this error: 3705111, 3705120, 3713940, 3714132, 3714567, 3714588, 4138790

**Comment by mvandeberg** [comment]
shared-db syncs
