### ISSUE TITLE
It should be feasible to make frequent low-content posts

### ISSUE THREAD

**Issue by GarethNelson** [steemit/steem#469]
I've been discussing this on slack and steemit.chat the past few days and believe that it should be implemented at the protocol level, I also made a post on steemit here:
https://steemit.com/steemit/@garethnelsonuk/my-cat-is-cute-this-is-a-serious-concern-i-promise-you-it-really-is

Put simply, in order to allow traditional social network semantics it should be possible to mark a post as not a blog post and bypass the 4 posts per day limit - in exchange surrendering rewards for that post and not damaging rewards for blog posts that come after it.

There is already a twitter clone built on steem that i'm told uses comments to get around the 4 posts per day limit - this is a silly hack that should not be needed - instead it should be possible to make posts directly and mark them as frequent low-content posts.

I'm not overly familiar with the codebase yet or i'd submit a patch for this - but I do strongly believe that implementing this feature would make steem take off a lot more by pulling in users from sites like facebook and twitter.

**Comment by mvandeberg** [comment]
We have comment options implemented on the block chain. One of those is limiting the max payout of a comment. Setting it to 0 should not impact the 4 post per day "limit". The limit is intended to create a market around content creation by decreasing payout after four posts. The use case you are describing is less about content creation and more about social connections.

**Comment by theoreticalbts** [comment]
- Custom operation is a better fit for these types of applications.
- @mvandeberg is not quite clear, but that's how it *should* work, not how it *does* work right now (i.e. posts for which you revoke your payout still affect your limit).

There are some subtleties in the implementation.  In particular, the reward_weight update is done in comment_operation, but declining payout is done in a *later* comment_options_operation. Which leads us to the conclusion that updating the reward_weight logic in comment_operation is impossible, as it would require us to know whether the user will do something in the future (i.e. we'd have to know at the time a comment is created whether the user plans on doing a comment_options_operation to limit the payout).

So the best thing to do IMHO is to defer the reward_weight update logic to the first upvote. That way a user who wants to make a zero-payout post can do a comment_options_operation later, and as long as they beat the first upvote they aren't docked (and the user can guarantee this by putting in the same tx as the comment).

**Comment by faddat** [comment]
I think that the STEEM chain has a big future as an IoT back end, if it wants this.  "Frequent low-content posts" sums up the activity of many of the sensors for IoT.  

But I want to clear something up-- recently there have been moves to expand the overall functionality of the chain, which generally I support or ideated.  Examples:

* On-chain git
* on-chain IoT back end 
* On-chain geolocated sales of items
* Chain-mediated container cloud system

What I'd like to know is this:

* Should I be thinknig about baking these systems into STEEM or should I be talking with steemit, inc about how to productively fork / create another graphene 2.0 chain?  

* Or should I be talking with someone else altogether?  

Steem opens up a new world of possibilities for what can be done with blockchains :D.

**Comment by nedsteem** [comment]
Please think about all these things. However, if it can be done with Steem, then it may make more sense to bake it into the protocol.

**Comment by faddat** [comment]
@nedsteem 
It can surely be done with STEEM.  

Basically I'm asking for the go-ahead to do it with STEEM.  These are not intimately connected to the other functions of STEEM.

**Comment by iamsmooth** [comment]
> baking these systems into STEEM or should I be talking with steemit, inc about how to productively fork / create another graphene 2.0 chain?

Sidechain is a third possiblity

**Comment by mvandeberg** [comment]
"bake it into the protocol" means on chain primitives vs. abstract primitives that are interpreted via plugin or third party application.

The custom op is the on chain primitive whose sole purpose is being interpreted by plugins and third party applications.

**Comment by mvandeberg** [comment]
Because we are removing the 4 post/day limit this issue is not longer relevant.
