### ISSUE TITLE
dockerfile does not build both build types

### ISSUE THREAD

**Issue by sneak** [steemit/steem#470]
The Dockerfile should build both types of binaries and switch between them in the init script based on args.

**Comment by theoreticalbts** [comment]
By "both" do you mean (a) or (b)?

- (a) `-DCMAKE_BUILD_TYPE={Release|Debug}`
- (b) `-DBUILD_STEEM_TESTNET={ON|OFF}`

**Comment by sneak** [comment]
See discussion at https://github.com/steemit/steem/pull/400

**Comment by sneak** [comment]
I assigned this to me mostly as a personal TODO reminder. :)

**Comment by sneak** [comment]
fixed in #480
