### ISSUE TITLE
Change C++ compiler to require std=c++14

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#473]
Seems it Just Works with out-of-the-box gcc on Ubuntu 16.04, definitely doesn't work with out-of-the-box gcc on Ubuntu 14.04, and breaks in our CI environment but I have no idea why.

**Comment by theoreticalbts** [comment]
It Just Works isn't true as far as Ubuntu 16.04 is concerned.  I was building the wrong target.  There were several problems, the biggest one was both std=c++11 and std=c++14 were being specified.

**Comment by theoreticalbts** [comment]
If I remember properly, there was some versioning problem.  It might be the case that we need to upgrade Boost to support C++14, and we can't upgrade Boost until we get rid of FC's multitasking system.

**Comment by mvandeberg** [comment]
Boost >1.60 requires removing FC's multitasking.

However, we are already requiring C++14 on `develop`. So this is done.
