### ISSUE TITLE
Custom Meta JSON Information -- Ignore and Follow Inconsistent

### ISSUE THREAD

**Issue by matthewniemerg** [steemit/steem#482]
The custom meta json information returned for an operation with following and ignore are not consistent return types.

The Ignore meta-json information is strictly a dictionary, whereas the Follow meta-json information is an array with a string as the first element and a dictionary as a second.

Example from block 5515892

Follow : 

"json": "[\"follow\",{\"follower\":\"haster\",\"following\":\"dashpaymag\",\"what\":[\"blog\"]}]"

Ignore : 

"json": "{\"follower\":\"str11ngfello\",\"following\":\"cyonic\",\"what\":[]}"

**Comment by mvandeberg** [comment]
The json format for follow is correct. The ignore format is a legacy format prior to having the plugin ops framework complete. I will forward this on to the web devs as Steemit.com should not be creating any follow ops with the old format. At some point in the future the plugin architecture will no longer support the legacy format and all custom plugin ops will need to conform to the new format.

**Comment by roadscape** [comment]
AFAICT, those operations are being created from alternate UIs.

**Comment by mvandeberg** [comment]
Ok, I will write a blog post about how to properly format custom plugin ops and we will disable the backwards active backwards compatibility in a future hardfork. The alternate UIs will need to upgrade to the current standard.
