### ISSUE TITLE
Posting without the rewards

### ISSUE THREAD

**Issue by 3beanzz** [steemit/steem#492]
There needs to be a way for users to post material that cannot gain monetary rewards and therefore be subjected to copyright laws.  Facebook, twitter and other social media platforms all enable you to share material that belongs to somebody else legally without any claim of ownership or copyright.  Simply being able to remove the ability to get rewards on a post would make this possible on steemit too.

http://screencast.com/t/rperJTOY

These posts probably would not need to be stored on the blockchain since they are not included in the rewards pool and the post would only be visible to followers.  There may be legal as well as personal reasons why future platform users would prefer to be able to post material in this way.

**Comment by roadscape** [comment]
Such a feature is mostly supported by the backend and integration on the frontend is almost complete:
https://github.com/steemit/steemit.com/issues/262
