### ISSUE TITLE
Allowing to set voteweight higher then 100% (while consuming your SBD balance with each vote)

### ISSUE THREAD

**Issue by Gutalean** [steemit/steem#493]
Full description is given here: https://steemit.com/steemit/@everythink/proposal-allowing-to-range-your-voteweight-higher-then-10000-while-consuming-you-sbd-balance-with-each-vote

**Comment by mvandeberg** [comment]
This system is inherently game-able. As soon as you can pay X SD and earn X+1 SD in value from doing so, the only logical economic decision is to vote. The n^2 curve for paying out rewards heavily favors whale voters as their SD will provide more rshares per SD than minnows. This will only allow whales to spend their SD to give themselves more SD. It will become a sink for minnows that never pays a return. The only way this could possible work is if there were a flat SD to rshare conversion rate. This would eliminate the skew in favor of whales and even the playing field per SD. However, it would still favor large post payouts and does not solve the problem of earning more than you spend for high payout posts. For low payout posts it does not make sense to boost your vote in this way. You would be better off transferring the SD directly to author.

**Comment by theoreticalbts** [comment]
My understanding of this is it's a UI proposal for a per-user setting to transform the "upvote" button into an "upvote+tip" button (opt-in).

What would make this gameable is if the tip influenced the post payout (hence a tipper could push a post along the `O(n^2)` curve) or sort order (hence a tipper could purchase a high-ranked spot on Trending).

There's nothing inherently breaking about a UI action which simply combines a vote and a transfer.

**Comment by theoreticalbts** [comment]
Closing, let's move the discussion to https://github.com/steemit/steemit.com/issues/401
