### ISSUE TITLE
Safari stop loading: Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.

### ISSUE THREAD

**Issue by dragosroua** [steemit/steem#499]
I don't know where to post this, but the latest update of Steemit (happened a couple of hours ago) breaks on Safari. I'm seeing this in console: "Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/" so I suppose it's related to internalization in react. But I might be wrong.

**Comment by mvandeberg** [comment]
This is a steemit.com issue. I have copied your issue and created it in the correct repository.

steemit/steemit.com#470
