### ISSUE TITLE
Flagging and Downvoting Seperation

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#500]
Would it be possible to split flagging and down-voting into two separate things? Flagging would be any of the negative/abusive things in the list (Fraud, Plagiarism, Spam, Hate Speech, Trolling, etc.). Down-voting would just be along the lines of a thumbs down. (I didn't like it, the author did a bad job, the post is paying too much, etc.). It could be setup such that any flag automatically down-voted, but a down-vote does not automatically flag.

**Comment by sneak** [comment]
I believe this is somewhere on our roadmap presently.

**Comment by theoreticalbts** [comment]
Vaguely related: #358.

**Comment by taoteh1221** [comment]
This would clarify flagging a lot for folks. 👍

**Comment by mvandeberg** [comment]
This is a UI problem. Downvoting on chain will not be removed. A separate flag can be implemented in custom json.
