### ISSUE TITLE
get_state: rename account.posts to account.comments

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#507]
IIRC, `posts` used to mean top-level posts & comments, now it just means `comments`. This is confusing because most users associate "posts" with top-level blog entries.

On the UI, we are making this change to our routes and internal vars (#443)

For consistency and clarity, `get_state` should return comments under `comments` key instead of `posts`.

It would be good to do this before the next release because steemd already has a few similar API-breaking changes since the last release.

**Comment by sneak** [comment]
I am always a fan of consistency in naming.

**Comment by mvandeberg** [comment]
Merged
