### ISSUE TITLE
ability to blacklist ops for account_history plugin

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#521]
Use case: for most accounts on steemit.com, vote operations make up the majority of entries in account histories, even though we do not have any reason to access these ops.

This is an issue because the `get_state @account/transfers` API only takes the last 1000 items and filters out everything but ops relating to transfers/orders/rewards. 

This API call would be much more useful if the last 1000 ops didn't contain votes. Users would have a much longer history of transfers/rewards (some report a history as short as 5 hours)

Reference: https://github.com/steemit/steemit.com/issues/375

**Comment by roadscape** [comment]
There are 2 main issues which this workaround would fix:
 - limited author/curation rewards history https://github.com/steemit/steemit.com/issues/375
 - limited conversion request history https://github.com/steemit/steemit.com/issues/896

An alternative/easier solution may be to simply iterate over the last 10,000 items when loading `get_state "@user/transfers"` instead of just the last 1,000. 

Looking at some active accounts, it seems 1,000 can be barely enough to cover 24hrs, which means it's simply not enough data to be useful for these reports.

**Comment by mvandeberg** [comment]
For now I am going to file this as won't fix. We are planning on moving non-consensus data to an external db, account history included, which will allow us to more easily query account history. I don't think we should spend developer time on updating a plugin that will become deprecated in a few months. 

I am leaving the ticket open until we have a solution, but will no be working on one right now.

**Comment by roadscape** [comment]
What about:

> An alternative/easier solution may be to simply iterate over the last 10,000 items when loading get_state "@user/transfers" instead of just the last 1,000.

**Comment by mvandeberg** [comment]
#301 addresses this
