### ISSUE TITLE
Change default build / config to minimum necessary to run cli_wallet

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#522]
Most users who build cli_wallet simply want a way to transfer tokens without the web UI.  So let's change the default settings as follows:
- Enable LOW_MEMORY_NODE and CLEAR_VOTES
- ~~Remove account history plugin from default config file~~  Edit:  Transaction history of your accounts is a basic wallet function.  Maybe by default filter out tx's that don't change balances?  Related: #300 #521

The main goal here is that the default configuration should be a configuration which minimizes the memory footprint while still allowing basic wallet functions to be used.

Related:  #265 #277 #517

**Comment by sneak** [comment]
Anyone who is using cli_wallet can change the build settings to suit them.  Additionally, the docker build ships with a suitably built steemd.  Let's not worry about this right now.

**Comment by mvandeberg** [comment]
The docker image handles this sufficiently.
