### ISSUE TITLE
Automate syncing test

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#523]
We need a script that spins up a steemd process, monitors it, and shuts it down.  After shutdown the script should exit 0 (if sync was successful) or exit 1 (if sync was unsuccessful).

Basically it should check every ~3 minutes:
- Has my head block number advanced from the last check?  If not, exit with error.
- Is my head block time close to the present actual time?  If so, exit with success.

**Comment by sneak** [comment]
suggestion: output useful messages only, perhaps by `grep -v`ing output for common/nominal messages so it only outputs stuff we care about for testing/debugging.

**Comment by mvandeberg** [comment]
`steemdsync` sort of takes care of this already.
