### ISSUE TITLE
Prevent all threads from using the same POW nonce.

### ISSUE THREAD

**Issue by penguins-cymbals** [steemit/steem#525]
https://github.com/GolosChain/golos/pull/37

Not sure how to issue the pull request cross-chains, but anyways, the same thing applies to steemit.

> The nonce should be different for each thread, otherwise all threads are performing the exact same hash, which means effectively on a machine with N cores you were only actually performing 1 core's worth of work.
> This should hopefully bring back some fairness in mining.
> 
> Since I'm giving up my unfair advantage, I hope this comes with a bug bounty from steemit and/or golos. Please PM 'penguin' in golos or steemit chat if so, so I can say where to issue it. :)

**Comment by abitmore** [comment]
Threads aren't using same nounces, see this line of code: https://github.com/steemit/steem/blob/v0.14.2/libraries/plugins/witness/witness.cpp#L491 .

Simply, hash rate should be higher if `mining-threads` in config.ini set to more than 1 and if the machine has more than 1 core.

**Comment by penguins-cymbals** [comment]
thread_num is never changed in the current code base, it is always 0.

**Comment by abitmore** [comment]
You're right. It's introduced in this commit: https://github.com/steemit/steem/commit/42e95baf26c01378cb6adbc81b520e85c9fea91f#diff-76b4b57a464fcf6ec0c0525753ed1222L587

**Comment by arhag** [comment]
@abitmore: Actually the bug was first introduced with this commit: https://github.com/steemit/steem/commit/581317f7ce9ff4b2ed6305c06fd61e41006b2c8d#diff-76b4b57a464fcf6ec0c0525753ed1222

**Comment by theoreticalbts** [comment]
Fixed, merged.
