### ISSUE TITLE
Number of active witness does should not have to be STEEMIT_MAX_MINERS

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#526]
The assertion here is not needed.
[database.cpp:1193](https://github.com/steemit/steem/blob/develop/libraries/chain/database.cpp#L1193-L1194)

In [get_scheduled_witness](https://github.com/steemit/steem/blob/develop/libraries/chain/database.cpp#L951-L957) we account for the number of active witnesses by modding the slot num by the size of the active witness set.

While the assert should never fail under normal use cases, it makes testing on testnets particularly difficult and for testing purposes should be removed.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [timestamps don't link to entity so timestamped #447](https://trello.com/c/3dIeA7XQ/84-timestamps-don-t-link-to-entity-so-timestamped-447)
