### ISSUE TITLE
shared-db branch block_log does not work on Linux

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#532]
Attempting to run shared-db branch on Linux, I've found many issues in `block_log.cpp` implementation:
- The usage of two fstreams to the same file in block_log, one for reading and one for writing, is clearly incorrect on any platform.  Data may be kept in a buffer owned by the fstream class, private to the instance, not shared with other fstream instances pointing to the same file.  These need to be replaced with a single fstream.
- flush() only flushes one stream
- Errors aren't checked or thrown.  Some error handling is needed.  For now I'll enable throwing exceptions when I/O fails, so at least we have some logging when this happens, even if we don't have correct error semantics yet.
- flush() only flushes one stream.  Index also needs to be flushed.
- stdlib on Linux doesn't like `in | out | app` flags.  I'll replace this with `in | out` followed by `seekp( 0, std::ios::end )`.
- To prevent the new flags introduced in the previous item from erroring when the file does not exist, we need to add `trunc` to the flags in this case.

**Comment by mvandeberg** [comment]
I believe this is fixed. @theoreticalbts, can you confirm?

**Comment by theoreticalbts** [comment]
Yeah, it's fixed by the above commit, closing.
