### ISSUE TITLE
P2P network leaking issue (Steem+Golos)

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#535]
Recently someone connected Steem P2P network with Golos network, as a result, blocks/transactions generated in one network were being broadcasting to the other, although they're rejected and then peers were disconnected, peers will reconnect after some time and broadcast them again. Both network were being spammed, some nodes crashed (or perhaps not due to this).

According to [the original Graphene code](https://github.com/cryptonomex/graphene/blob/2.0.160328/libraries/net/include/graphene/net/core_messages.hpp#L190-L202), there was a `chain_id` field in `hello_message`, so nodes of one network will reject connections from nodes of other networks.

```
  struct hello_message
  {
    static const core_message_type_enum type;

    std::string                user_agent;
    uint32_t                   core_protocol_version;
    fc::ip::address            inbound_address;
    uint16_t                   inbound_port;
    uint16_t                   outbound_port;
    node_id_t                  node_public_key;
    fc::ecc::compact_signature signed_shared_secret;
    fc::sha256                 chain_id;
    fc::variant_object         user_data;
```

But the `chain_id` field was dropped in Steem (link is [here](https://github.com/steemit/steem/blob/v0.14.2/libraries/net/include/graphene/net/core_messages.hpp#L190-L201)) for whatever reason.

```
  struct hello_message
  {
    static const core_message_type_enum type;

    std::string                user_agent;
    uint32_t                   core_protocol_version;
    fc::ip::address            inbound_address;
    uint16_t                   inbound_port;
    uint16_t                   outbound_port;
    node_id_t                  node_public_key;
    fc::ecc::compact_signature signed_shared_secret;
    fc::variant_object         user_data;
```

Is it OK to include `chain_id` to the message again, perhaps add it to the `user_data` field and validate it while establishing new connections?

**Comment by xeroc** [comment]
On resyncs of the chain I see many unlinkable blocks because they are obviously for GOLOS and not steem.

**Comment by Gandalf-the-Grey** [comment]
> On resyncs of the chain I see many unlinkable blocks because they are obviously for GOLOS and not steem.

It doesn't affect resync/replay (steem rejects golos), but indeed: spammy and annoying

**Comment by abitmore** [comment]
More discussion in #612, closing this one.
