### ISSUE TITLE
Comment's `cashout_time` not set

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#546]
Comments in their first payout seem to be missing cashout_time:

![image](https://cloud.githubusercontent.com/assets/5168676/19943580/61ebbd9e-a10e-11e6-9910-4ee2481a675b.png)

Which causes a UI quirk:

![image](https://cloud.githubusercontent.com/assets/5168676/19943610/85e7a5e6-a10e-11e6-81e5-a9e26c15fec2.png)

**Comment by sneak** [comment]
meta bug - please add a warning output for the relative date checker for null/0 relative dates - it's very rare that "47 years ago" should ever display. :)

**Comment by mvandeberg** [comment]
To clarify, `cashout_time` is set correctly. All comments are paid out as a discussion, determined by the total r-shares on the discussion. This information is tracked by the root comment. To prevent non-root comments from being sorted into the payout list, they are given a cashout time of 0xFFFFFFFF, placing them at the end of the sort order. This is displaying as the epoch time -1. When returning comments we can replace the value with the discussion's payout time.

**Comment by mvandeberg** [comment]
Merged
