### ISSUE TITLE
get_discussions_by_trending not returning `limit` items

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#549]
`get_discussions_by_trending` (i.e. `get_discussions`) has to skip children, which becomes increasingly often as the offset increases. 

This results in truncation of results due to `Maximum iteration count exceeded` errors.

This confuses the frontend, which makes the assumption that if you request e.g. 20 items and only get 19 back, it must be the end of the list.

**Comment by roadscape** [comment]
This appears to be even more of an issue on the 'Promoted' page

**Comment by mvandeberg** [comment]
Merged
