### ISSUE TITLE
Introduction of a hosting fee per post, to maintain posts votable after the 30 days period

### ISSUE THREAD

**Issue by dragosroua** [steemit/steem#552]
It means that posts that are allowed to receive votes over the 30 days **have to pay a hosting fee**. Those posts should have the UI updated accordingly (there will be buttons for upvote, etc) and the authors should be credited as well.

The hosting fee should be split: 50% will be burned (sent to null), 50% redistributed to the rewards pool (which means it will increase the curation rewards pool as well).

Hosting fee can be activated / deactivated globally (for all posts) or individually, for each post.

My initial suggestion is that a hosting fee should be 3.65 STEEM / year / post. I didn't do any research for that, just a few simulations at 0.01 STEEM / day.

It's basically _a particular case for the advertising-based revenue model_: authors who are confident enough their posts will receive votes after more than 30 days should "burn" some of their revenue for that. And it is also a case of keeping the currency inside the platform and increasing the revenue pool.

It might be necessary to take out the blog posts from the blockchain and keep them somewhere else, linked with a key, the same way files are delivered from CDNs on high load networks of websites. In the blockchain we could store only references to those blog posts.

**Comment by everittdmickey** [comment]
Good plan.
I have an [alternate suggestion]( STM7ADodYzoXCx3uRZ8zhq7wNLBeFricMVwX5eqSx6msWFonaa5tY)

**Comment by dragosroua** [comment]
your link is broken, can you check? thanks.

**Comment by Gandalf-the-Grey** [comment]
@everittdmickey your link is broken because you accidentally pasted your key instead of an issue. Good thing is that it was a public one :-)

**Comment by dragosroua** [comment]
Whoa!

**Comment by everittdmickey** [comment]
oops...public key.

**Comment by everittdmickey** [comment]
https://steemit.com/steemit/@everittdmickey/keep-it-simple-stupid

also this

https://steemit.com/steemit/@everittdmickey/in-my-not-so-humble-opinion-the-number-one-modification-to-steem-it-that-needs-to-be-done-first

things need to be simplified?
Mistakes can happen (see above), but their much more likely to happen if
the user interface is complex.

**Comment by mvandeberg** [comment]
Replying to acknowledge that we have seen this issue. I don't have anything to say at this time but we will say something when we do.

**Comment by dragosroua** [comment]
@mvandeberg Thank you.

**Comment by mvandeberg** [comment]
This blog post explains why we will not be implementing a system as described in this issue.
