### ISSUE TITLE
Feature: Give The Poster Owner The Ability To Delete Comments

### ISSUE THREAD

**Issue by ebonsi** [steemit/steem#554]
Steemit needs to give the ability to the person that creates a post or "Submit a Story" to delete comments from users on a story. The person that post a story must have the rights to the story. Doing so will give the poster owner to delete comments from offender users as "trolls".
To know more, please read the post on Steemit at;

Steemit User's Biggest Security Flaw On Comments
https://steemit.com/technology/@ebonsi/steemit-user-s-biggest-security-flaw-on-comments
Thanks!

**Comment by samupaha** [comment]
A few weeks ago I proposed a new feature: [ownable tags](https://steemit.com/steem-ideas/@samupaha/feature-proposal-ownable-tags).

When a user posts under an ownable tag, he can decide who is allowed or banned to comment on that post. This feature would offer lots of benefits for users who want to build certain kind of communities on Steemit and in addition it would also solve what you are asking. You could buy a tag for yourself and post under it when you think the post might attract too much trolls.

**Comment by abitmore** [comment]
This feature is something like self-moderated post. It's not too hard to implement. However, the ability to remove replies at will would be abused if not well balanced. For example, a scammer can remove any reply that told the truth. So, perhaps a good idea that only authors that have more than X VESTS can set this option, and/or the option can only be set on a post which declined reward/payout.

**Comment by thecryptofiend** [comment]
Flagging is already there to serve this purpose.  Deletion of comments would go against the spirit of the platform and could be abused as in the case case suggested by @abitmore - the current situation strikes the right balance IMO.

**Comment by taoteh1221** [comment]
@thecryptofiend Agreed. Also, making the UI complicated with a thousand settings will drive away the general public.

**Comment by iamsmooth** [comment]
> This feature is something like self-moderated post. It's not too hard to implement. However, the ability to remove replies at will would be abused if not well balanced. For example, a scammer can remove any reply that told the truth. So, perhaps a good idea that only authors that have more than X VESTS can set this option, and/or the option can only be set on a post which declined reward/payou

Agree with this but I think the appropriate remedy is not depending on a particularly number of vests (arbitrary rule, and scammers may have any number, particularly if the scam is profitable) but to label the post as self-moderated (likewise for tags if implemented) and perhaps report the number of comments deleted.

**Comment by ebonsi** [comment]
Just for you guys to have an idea, Nextdoor allows people to post. People that post there do not have a way to moderate the comments. Following that, there are great comments but also there are a group of trolls that hang around and mess with some people posts just because they do not like the subject. People that are watching this happening do not feel motivate anymore to get into an unnecessary confrontation with the trolls and also do not feel motivate to play the "flag" game that ends up to serve more the trolls than others. That is not a theory, this is experience in posting there. The flag feature was used more by the trolls than the good people out there. The conclusion of this, it defeats social change and real community gathering. I as an example, no longer post anything there and hardly participate in their conversation. I want to start a project that is based on environmental reality on "Steemit". However, I am just not comfortable to start the project because of this issue. Maybe you think you understand this, but have any of you read **github community guidelines yet**? https://github.com/blog/2267-introducing-github-community-guidelines

**Comment by mvandeberg** [comment]
Letting a post owner delete comments is not something we will add, not does it make much sense.

1. If the comment has a pending payout, it gives the root author a nuclear option to get rid of their payout in its entirety.

2. The comment still exists in the blockchain. Even if it is not accessible on Steemit.com, it is still obtainable through the blockchain.

We are adding some moderation features with Communities that should satisfy this desire.
