### ISSUE TITLE
Transparent dmca claims

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#558]
Operators of public nodes/APIs need a transparent way to voluntarily handle DMCA claims.

All claims should be published publicly as posts on the blockchain. The format might be:

 - 'Decline Payout' enabled (`max_accepted_payout = 0.000 SBD`)
 - category: `dmca-claim`
 - `json_metadata` contains a `posts` key with an array of affected `author/permlink`s

The plugin would honor the claim only after a specific reviewer has upvoted it. So the config.ini should accept a list of 'reviewers' whose votes to watch. When offending posts are requested from the API, their content should be replaced with a link to the relevant claim.

**Comment by roadscape** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DMCA Handling](https://trello.com/c/IDtMwGcF/103-dmca-handling)

**Comment by faddat** [comment]
....but is this the memory hole?

**Comment by mvandeberg** [comment]
What do you mean by memory hole?

**Comment by faddat** [comment]
Ever read 1984?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by abitmore** [comment]
IIRC there will be a link to the claim showing on the "removed" post. "This content is removed due to this claim."

**Comment by mvandeberg** [comment]
This will not be implemented on the block chain.
