### ISSUE TITLE
No longer seeing "Promote" button in posts on Steemit

### ISSUE THREAD

**Issue by thecryptofiend** [steemit/steem#560]
I have just noticed this within the last hour.  I understand witnesses have started updating in preparation for the latest HF.  Looks like this might be a bug.

![screenshot 2016-11-07 22 28 20](https://cloud.githubusercontent.com/assets/21145935/20078734/ad8dc2e0-a539-11e6-9e0a-7b326929128b.png)

(This is just a screenshot from a random post in my feed to illustrate the missing button.)

**Comment by taoteh1221** [comment]
@thecryptofiend https://steemit.com/steemit/@steemitblog/promoted-posts-bug

**Comment by thecryptofiend** [comment]
Thanks well spotted:)

**Comment by taoteh1221** [comment]
@thecryptofiend :)

**Comment by mvandeberg** [comment]
#549 is the cause of the bug. Has been fixed on `develop`
