### ISSUE TITLE
Unable to cancel a power down when amount of VESTS is less than 10x account_creation_fee

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#562]
As described in this post: https://steemit.com/steemit-bug/@acidyo/a-bug-when-powering-down-cancelling-power-down :
> He was over 100 SP when he powered down but can't cancel the power down now even though he invested more and is at 230 SP now.

(current account creation fee is 30.000 STEEM)

**Comment by mvandeberg** [comment]
Merged
