### ISSUE TITLE
Account bandwidth updating issue

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#563]
According to the [code](https://github.com/steemit/steem/blob/v0.15.0/libraries/chain/database.cpp#L468-L477): 
```
         auto delta_time = (now - a.last_bandwidth_update).to_seconds();
         uint64_t N = trx_size * STEEMIT_BANDWIDTH_PRECISION;
         if( delta_time >= STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS )
            acnt.average_bandwidth = N;
         else
         {
            auto old_weight = acnt.average_bandwidth * (STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS - delta_time);
            auto new_weight = delta_time * N;
            acnt.average_bandwidth =  (old_weight + new_weight) / (STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS);
         }
```

It means, if one account can make multiple transactions into one block, the second and following transactions would be "free", because `delta_time` would be `0`.

I think there are other similar methods to spam the network.

Thanks to steemitmarket@steem for testing (related link: https://steemit.com/spam/@steemitmarket/6skilb-whitespamattack)

**Comment by abitmore** [comment]
The correct logic should be something like:
```
         auto delta_time = (now - a.last_bandwidth_update).to_seconds();
         uint64_t N = trx_size * STEEMIT_BANDWIDTH_PRECISION;
         if( delta_time >= STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS )
            acnt.average_bandwidth = N / STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
         else
         {
            auto old_weight = acnt.average_bandwidth * (STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS - delta_time);
            auto new_weight = N;
            acnt.average_bandwidth =  (old_weight + new_weight) / (STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS);
         }
```

**Comment by abitmore** [comment]
The scenario described in issue #3 is probably caused by this.

**Comment by theoreticalbts** [comment]
Yeah, this needs fixed.  Good news is, once HF is done, pre-HF code can be updated to ignore bandwidth entirely, so we don't need to keep the old BW algorithm around forever, and can even save some time re-indexing.

**Comment by mvandeberg** [comment]
This should be made a priority.

**Comment by abitmore** [comment]
The soft fork only blocks one way of abusing, perhaps there are still other ways, since making one trx on every block is as expensive as making one trx every x blocks with current code. Will the issue be fixed entirely in the coming hard fork, if not, when?

**Comment by mvandeberg** [comment]
We have plans to abstract bandwidth to an arbitrary resource consumption scheme which will take more time to implement and test.

**Comment by abitmore** [comment]
Thanks for the info.

**Comment by mvandeberg** [comment]
The bandwidth algorithm has been updated and is completely implemented through soft rejecting transactions. This issue has been addressed in those changes.
