### ISSUE TITLE
Unexpected behavior: listening on rpc endpoint during replay

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#565]
While runing develop (45d4360) full node, while initial resync/replay node is listening on rpc-endpoint.
While this might not be a bug as such, it present bad (i.e. out of date) perspective to frontend if not handled properly (head block age, etc.)

**Comment by mvandeberg** [comment]
Under the new parallel read/write architecture we cannot easily prevent reading from the database on a resync. Reindex is locked as a whole. The front end probably needs to check head block time against system time and have a pop-up warning if the head block age is more than 30 seconds old.

**Comment by mvandeberg** [comment]
This issue has been fixed with a temporary change. The real fix will be a refactor of our plugin architecture. Closing this because the next step is beyond the scope of this issue.
