### ISSUE TITLE
On-chain correlation of bitshares username(s)?

### ISSUE THREAD

**Issue by faddat** [steemit/steem#573]
Working on something that would bridge BTS and steem.  I'd like to gather thoughts on if this is something we might do on-chain?

If no, it's no big deal, there are of course other ways to do it.  If yes, great!

Goal: Enable moving assets on bitshares in response to events on STEEM.

**Comment by iamsmooth** [comment]
You could store something in account_json, like a signed message.

**Comment by mvandeberg** [comment]
Correct. It requires the account's active authority.

**Comment by faddat** [comment]
That's perfect.  Let me user storify this because I don't want to
accidentally harm anyone's privacy.

So I'm Johnny, and I have various asset holdings on BitShares, as well as a
few K SP.  Wanting to get my peanut butter and chocolate on, I choose to
announce my BTS account(s) to the world using the publicity platform which
is the STEEM blockchain.

Afterwards, any steem user can reference my BTS account info by looking up
my account_json.

Is all that correct?

**Comment by mvandeberg** [comment]
Yes, json metadata is public (assuming you don't encrypt any fields yourself), but can only be modified by your account's active authority.

The only challenge is that we cannot index account's on account metadata. If you wanted to have an easy API lookup you would need to create a plugin that monitors account json_metadata and maintains a non-consensus object that explicitly contains the BitShares account data along with the Steem account data. Not a huge challenge, but also not trivial. Alternatively, you can design an external service that maintains the same tables.

**Comment by xeroc** [comment]
Please contact @jesta (steemdb.com). He started to work on a standard for the json-metadata. It would be helpful to integrate the bts accountname there!

**Comment by roadscape** [comment]
@xeroc for json-metadata also see https://github.com/adcpm/steemscript

**Comment by faddat** [comment]
You have more experience in the guts of steem than me:. I could probably do
as you describe now, however.

So, which (plugin / external table) do you think is better for:

- speed/dev time(guessing that is the external tables)
- long lasting simple architectural solution (more of a tossup but I lean
towards the tables once more)

My focus with steem is on building interesting, reliable, extensible open
web applications that playfully jostle the power relationship between
individuals, governments, and multinational corps.

**Comment by mvandeberg** [comment]
We have no plans of implementing this as part of consensus at this time.
