### ISSUE TITLE
Delayed operations

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#576]
[Here](https://github.com/steemit/steem/issues/568#issuecomment-261316037) @bytemaster proposes creating a unified mechanism for specifying delayed operations, which generalizes and may be used as a building block to implement many different cases of delayed behavior.

**Comment by theoreticalbts** [comment]
Let's flesh this out a little:

```
struct propose_transaction
{
   account_name_type owner;
   uint32_t proposal_num;
   vector<char> op_list;
   uint32_t delay;
   uint32_t expiration;
};
```

Brief description of fields:

- `owner` is the proposal creator
- `proposal_num` is client-assigned ID
- `op_list` is a serialized list of ops
- `delay` is the minimum time for the transaction to take effect
- `expiration` is the maximum time for the transaction to take effect

Things to note:

- `(owner, proposal_num)` uniquely identifies a proposal
-  We cannot use a list of operations because our operation type would become too recursive for the compiler to handle.  I get around this by serializing the ops.

**Comment by theoreticalbts** [comment]
There is a subtle issue here.  We must be very careful with upgrades that change parsing validity (i.e. hardfork to add ops).  A node which includes the new op in op_list may be validly parsed by new versions but invalid by old versions.  The old/new versions must agree on whether to accept the proposal.

One simple way to do this is to defer parsing until immediately before evaluation of the list.  The downside is that this makes validation of the inner operations part of consensus rather than doing it pre-consensus, i.e., we'd be allowing invalid ops into the chain and catching them later before the tx is executed.

The more "correct" way is to parse/validate in validate(), then parse again in apply(), checking the ops are enabled in the current hardfork.  This would allow the new version to forget disabled ops.  We can skip the parsing in apply() if it is before a checkpoint.

**Comment by theoreticalbts** [comment]
We also need

```
struct approve_transaction_op
{
   account_name_type proposal_owner;
   uint32_t proposal_num;
   account_name_type signer;
   bool approve = false;   // decline if false, approve if true
};
```

- We can approve or decline by setting the `approve` flag
- A signer who approves can always change to decline later
- A signer who declines can never change to approve

These rules are designed so that the blockchain has a simple arbitration rule in case two people both have access to an account's signing key but disagree whether the account should approve the tx:  The decliner wins.

Such a situation could occur if Eve hacks Alice's account, Eve and Alice would both have access to the key, and disagree on whether the transaction "send all of Alice's Steem to Eve" should be approved.  In this situation the blockchain's arbitration rule decides in favor of Alice (obviously the desired behavior).

**Comment by arhag** [comment]
So would the blockchain determine the set accounts that need to approve (with active authority only?) the set of operations in `op_list` and either activate the entire sequence of operations as soon as possible (meaning time has exceeded the delay and enough `signer` accounts have approved the proposed transaction) or delete the proposed transaction as soon as possible (meaning perhaps the expiration time has not yet been reached but enough `signer`s have disapproved the proposed transaction to make it impossible for it to ever get approval from the necessary accounts to make the entire set of operations valid)?

**Comment by bytemaster** [comment]
This would need to be updated to handle the different authority levels

**Comment by theoreticalbts** [comment]
@arhag Maybe it should be a flag whether it activates ASAP or on expiration.  The original motivation for this (replacing transfer from blind savings objects with a generic delay primitive) argues in favor of the latter.

Deleting a declined proposed transaction ASAP is an obvious optimization, but probably won't be done on the first pass.

@bytemaster Yeah, the approval needs to include an authority type as well as a signer.

**Comment by arhag** [comment]
@theoreticalbts: I may be misunderstanding. As I understood it, it should never _activate_ on expiration. In the case of blind savings, I would think the delay would be 3 days, not the expiration (although I guess expiration need not be much longer than 3 days either).

**Comment by mvandeberg** [comment]
Closing, won't fix.
