### ISSUE TITLE
Report trending tags

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#578]
This ticket is to report trending in `get_state` as tags rather than categories.

Here is a summary of the changes:

- Sort based on `total_children_rshares2` rather than `abs_rshares`
- Fix index bug where name is first sort key (should be second)
- Delete `trending` from `category_index`
- Add `trending` to `tag_index`
- Create `tags` map which resolves things in `tag_index` [1]
- Disable unused indexes

This is a slightly breaking change which needs some coordination with the web folks.

[1] Analogous to currently existing `categories` map which resolves things in `category_index`

**Comment by mvandeberg** [comment]
This was merged
