### ISSUE TITLE
Plugin Operations

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#58]
We are adding a system that will allow plugins to define their own set of operations which will be implemented through custom ops. These ops will use the same validate/apply convention as core operations. More details will come as the system is developed. The currently implemented private_message_plugin will be the first plugin to use these ops and will also be enabled in this hardfork.

**Comment by revflash** [comment]
The only thing that is "hardforking" about this change is the addition of the custom_json_operation which is already implemented.  Everything else regarding the plugin system is optional and can be implemented at a later time.

**Comment by mvandeberg** [comment]
Reopening because the feature is still in development, removing the hardfork 5 milestone.

**Comment by theoreticalbts** [comment]
It's all working and merged, so I'm closing this.
