### ISSUE TITLE
get_discussions_by_blog to filter resteems

### ISSUE THREAD

**Issue by thebitcoiner** [steemit/steem#581]
In order to implement the splitting of the blog tab to a blog tab and a resteemed tab, and continue with https://github.com/steemit/steemit.com/pull/634, I propose the following changes to the relevant API call to handle this:

* `get_discussions_by_blog` will return blogs and resteems as it currently does
* `get_discussions_by_blog` with `hide=resteemed` will only return blog posts
* `get_discussions_by_blog` with `hide=authored` will only return resteemed posts

In addition:

* `get_state @user` will return blogs and resteems as it currently does
* `get_state @user/blog` will only return blog posts
* `get_state @user/resteemd` will only return resteemed posts

Separating author posts and resteemed posts in a user's blog will provide for a cleaner experience. Many users hesitate to resteem as their blog will clutter up.

I can start to familiarize myself with the steem codebase and try to make these changes. However, I would appreciate if someone who already has experience with the code can do this, so this may be implemented as quickly as possible.

**Comment by jcalfee** [comment]
Our design is probably more like this:  get_state would just split the blogs and resteems into two different lists but return both.  The change to get_discussions_by_blog is needed for paging.

**Comment by thebitcoiner** [comment]
Excellent suggestion, @jcalfee. I have updated the comment. Thanks.
