### ISSUE TITLE
Move tags plugin indexes out of constructor

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#584]
These indexes were moved into the constructor to make the reader process work, see #582.  Many things in database_api will crash in the reader process if the tags indexes don't exist.  So they've been moved to temporarily solve the immediate problem, but the architecture needs improved so they can be moved back.

**Comment by mvandeberg** [comment]
chainbase now has a method `has_index` which we can use to check existence of indices before following them. This architectural change should enable read nodes to successfully connect to a write node without the tags plugin enabled and not crash.

**Comment by mvandeberg** [comment]
#1265 cleans up this part of the plugin architecture quite nicely including moving away from the multi-process reader architecture.
