### ISSUE TITLE
steemd --version

### ISSUE THREAD

**Issue by Riverhead** [steemit/steem#591]
As near as I can tell there isn't a way to know which version of steemd you have without connecting a wallet to a running node. A simple --version flag would be great.

**Comment by BhuzOr** [comment]
There is not a way even with a connected wallet really. 
The "about" cli command shows the version of the cli_wallet and not the one of steemd. 

So a --version flag for steemd really seems needed imo

**Comment by mvandeberg** [comment]
merged
