### ISSUE TITLE
Request to add support for price feed discount

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#593]
Currently the witnesses are discounting their price feeds, so that SBD to STEEM conversations are closer to $1 USD worth of STEEM.

There are a lot of people that don't agree with the price being discounted this way, because it forces the witnesses to report an 'incorrect' price.

It would be cleaner and more transparent if the witnesses could report a 100% accurate price feed, and set a separate 'price feed conversation discount' parameter as part of their witness parameters.

**Comment by roadscape** [comment]
Witnesses can already do this by taking advantage of the fact that feed price consists of 2 parameters: `base` and `quote`.

e.g. here is the current median `feed_price`
```
base	0.115 SBD
quote	1.087 STEEM
```

`base` here is true price, and `quote` represents the discount.

You can see at https://steemd.com/witnesses that the majority of witnesses are using this approach. (The Feed column shows `base`, and the Bias column shows `quote`)

**Comment by TimCliff** [comment]
Thanks @roadscape. This is what I am currently doing for my feed too, but it still feels like it is not representing the discount 100% accurately. With 0.115 SBD / 1.087 STEEM, it still seems like we are reporting the price of 1.0 STEEM as 0.105 SBD.

There are is at least one witness who is not discounting their price feed because they feel it is not the way it was intended to be reported, and believes strongly that it is his duty to report an accurate price.

This change would make it more clear to the community and witnesses that a price discount is part of the intended functionality of the blockchain, and would separate it from the price feed which witnesses were intended to report accurately.

**Comment by mvandeberg** [comment]
Check your math because those are the same ratios when truncated. 1 STEEM * ( 0.115 SBD / 1.087 STEEM ) = **0.105**7957 SBD.

If you report as 0.115 SBD as 1.087 STEEM, the accuracy will remain during the conversion (assuming that price ends up being the median).

**Comment by TimCliff** [comment]
Hi @mvandeberg, I think you are saying the same thing as what I was trying to say. If a witness reports the price as 0.115 SBD / 1.087 STEEM, they are essentially reporting it as 0.1057957 SBD / 1.0 STEEM.

This is essentially reporting an 'inaccurate' price.

What I am suggesting is that the witnesses could report it as 0.115 SBD / 1.0 STEEM, and then set the 0.92 discount as a separate witness parameter.

**Comment by TimCliff** [comment]
@roadscape and @mvandeberg - the consensus seems to be that the current 'base	' and 'quote' implementation is working fine. The person who is not discounting their price feed because they feel it is not the way it was intended to be reported said that switching it would not address their reason for not doing it. Thanks for your help/input on this. (closing issue)
