### ISSUE TITLE
get_discussions_by_x and get_state API additions

### ISSUE THREAD

**Issue by feruzm** [steemit/steem#595]
This is request addition on API results returned by `get_discussions_by_x` and/or `get_state` ...

It would be great to have 

`author_json_metadata` next to `author_reputation` so that we can make use of account informations as well.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Downcase incoming http requests for profile pages & main categories #663](https://trello.com/c/E4rcVqJ9/139-downcase-incoming-http-requests-for-profile-pages-main-categories-663)

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Downcase incoming http requests for profile pages & main categories #663](https://trello.com/c/E4rcVqJ9/139-downcase-incoming-http-requests-for-profile-pages-main-categories-663)
