### ISSUE TITLE
Proposal: Simple 100% Decentralized Escrow System Option, To Automate Small Everyday Purchases

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steem#611]
(EDITED BASED ON FEEDBACK)

I propose an alternate simple / 100% decentralized / fully automated escrow system for smaller everyday purchases be implemented directly into the STEEM blockchain (to compliment @bytemaster 's current system), for allowing customers on STEEM storefronts to choose the option to use an automated self-mediating system, based off both parties depositing the same amount of tokens in escrow (so both parties have the same value at stake thereby incentivizing effective self-mediation). 

The biggest potential issue is obviously a possible need for mediation during a dispute. For smaller transactions, this potential need can be adequately / feasibly avoided by requiring THE SELLER to deposit the same exact amount as the buyer. So the decentralized escrow flow might go like this:

1. Seller lists item / service for sale.

2. Buyer submits a purchase order, which automatically locks their STEEM tokens for X days in the amount of the purchase cost.

3a. Seller confirms desire to complete the sale by locking the same exact amount of the Seller's STEEM tokens into the escrow, thereby activating permanent locking both the seller's and buyer's tokens into the escrow, until either party releases the tokens on their side (either a refund or a completed sale).

3b. Seller instead of desiring to complete the sale, ignores the purchase request. X days later, the buyer is refunded their tokens automatically.

4a. Seller completes sending item / service, customer is happy and releases the funds, thereby sending the payment and seller deposit to the seller.

4b. Customer is unhappy with item / service, and does not release the payment / seller deposit. Seller can then offer a full or partial refund (including exact percent of refund offered).

5a. Customer is happy with the refund offer, and accepts the seller's particular refund offer. Customer receives the refund amount offered and seller receives the remaining amount of payment and gets their entire deposit amount back.

5b. No resolution is reached regarding a refund amount. Both the seller and the buyer cannot get their deposits back. Unless they reach an agreement, both parties have now lost their tokens.

This proposal would streamline the currently implemented escrow system, allowing for automated mediation of sales for smaller everyday purchases, which I imagine could be the majority of sales transactions if popularity grows to a sizeable level.

We already have an exchange of value system in place, it's only natural to want to include commerce with that. Many new users and crypto veterans alike may wish to skip using the exchanges to convert to BTC / fiat, and purchase goods / services immediately after earning their tokens from authoring / curating. I think this will add tremendous value to the platform with yet another highly feasible use case fulfilled. The more streamlined it can become, the more efficient and usable it can be.

UPDATE: I have received feedback on this proposal (many thanks to @xeroc and @abitmore) and am now aware of @bytemaster 's previously implemented system and concerns around parts of my proposal (all revision ideas are welcome). I believe my proposal could compliment the already implemented system as an option to automate many smaller everyday purchases, where users may not wish to spend their time or other's time on mediating a dispute. Also, some users may be turned off from having to trust a 3rd party to mediate for them. 

FYI, I am fine with closing this proposal if the consensus is that it lacks feasibility, just let me know? I am no expert in blockchain technology, beyond being a miner / trader / end user since early 2014.

**Comment by xeroc** [comment]
you might want to read up on
* https://steemit.com/sip/@dan/escrow-sip-steem-improvement-proposal
* https://github.com/steemit/steem/issues/143

**Comment by taoteh1221** [comment]
@xeroc Thanks for the link. The difference between that proposal and mine is that proposal is not fully decentralized, so it may possibly maintain some amount of liability from a regulation standpoint in some jurisdictions. Also, it's not as simple / straightforward, which may discourage the average user from participating (many people may not be interested in having to trust a 3rd party to resolve their dispute). My proposal is completely decentralized and extremely simple yet very efficient. I think this effectively avoids regulation issues, as well as users not needing to be concerned with trusting 3rd parties to resolve disputes.

**Comment by taoteh1221** [comment]
Additionally, my above escrow proposal structure has the added benefit of easily providing a secure reputation score (cannot be manipulated by buyer or seller) based off the seller refund average, whereby you could calculate the average percentage refunded by that seller over their entire sales history. The higher the refund percentage, the lower their reputation would be.

**Comment by taoteh1221** [comment]
Furthermore, the same reputation score can be applied for buyer accounts too, providing feedback for both buyers and sellers, before committing to a sale with a certain user. A feedback score might look like this for a buyer or seller with an average of 5% refunds for all their commerce transactions:
~~~ username (95% success) ~~~

**Comment by abitmore** [comment]
@taoteh1221 the down side of your proposal is that it's too biased to buyers. For example, if a seller want to sell a house for 100K SBD, and it would be delivered after about 3 months, she have to lock 100K SBD in the escrow object for 3 months.. That's doesn't sound appropriate.

**Comment by abitmore** [comment]
In addition, the design of reputation score is just too simple and easy to be gamed/manipulated/Sybil-attacked.

By the way, giving sellers the freedom to choose buyers as they like without any restriction sounds not like a good idea.

We can learn rules from Ebay/Amazon/Taobao.

**Comment by taoteh1221** [comment]
@abitmore I realize it wouldn't be suitable for all situations, BUT I think it does compliment @bytemaster 's system as a way to cover many common smaller everyday purchase use cases in a fully decentralized / automated way (thereby freeing up mediators to address disputes on larger purchases). 

I'm totally open to any suggestions on tweaking anything here (or having you all dismiss this proposal completely if nothing seems feasible in your eyes to add to the platform), I'm merely sharing what seemed to be good alternatives for some use cases. My thoughts on the simple reputation system were to avoid over-complicating my initial proposal and anything from a user experience / node resource usage perspective. 

I think you could compliment / tier the current escrow system that @bytemaster built last summer to either do a simple / fully decentralized / automated escrow like I have described, or to have full 3rd party mediation if you prefer it. Just sharing my idea in case it tickles anyone's fancy. I'd code it up but I have never tried coding in C++.
