### ISSUE TITLE
[v0.16.0rc3] SIGSEGV after SIGINT (Ctrl+C)

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#613]
`SIGSEGV` after `SIGINT` (Ctrl+C) in `v0.16.0rc3`
encountered once, during `--resync`

```
#0  0x0000000000e658bf in steemit::chain::database::is_known_block(fc::ripemd160 const&) const ()
#1  0x0000000000ca277d in steemit::app::detail::application_impl::has_item(graphene::net::item_id const&) ()
#2  0x000000000152465c in fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::has_item(graphene::net::item_id const&)::{lambda()#1}>::run(void*, fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::has_item(graphene::net::item_id const&)::{lambda()#1}>) ()
#3  0x000000000121ae54 in fc::task_base::run_impl() ()
#4  0x0000000001218956 in fc::thread_d::process_tasks() ()
#5  0x0000000001219075 in fc::thread_d::start_process_tasks(long) ()
#6  0x0000000001682401 in make_fcontext ()
#7  0x0000000000000000 in ?? ()
```

( Not sure if related to #607 )

**Comment by mvandeberg** [comment]
It looks like another critical section in the network code. I will investigate.

**Comment by mvandeberg** [comment]
There were a couple of other places the p2p code was following a pointer to the database. The change prevents the immediate offending code from referencing the database when shutting down. Additionally, after the network is shutdown, we wait 1 second to let it clean up before closing the database. This is not the most efficient fix, but considering that a major overhaul to the network code is coming soon, this fix should work for the time being.

**Comment by mvandeberg** [comment]
merged
