### ISSUE TITLE
How to LOW_MEMORY_NODE

### ISSUE THREAD

**Issue by hrdwdmrbl** [steemit/steem#618]
I try running

`$ LOW_MEMORY_NODE=on cmake .`

But the output still says off...
```
-- BUILD_STEEM_TESTNET: OFF
-- LOW_MEMORY_NODE: OFF
--    CONFIGURING TO CLEAR OLD VOTES FROM MEMORY
```

**Comment by thebitcoiner** [comment]
Perhaps you can try passing it as a cmake argument instead of an env variable:

`cmake -DLOW_MEMORY_NODE=ON .`

**Comment by hrdwdmrbl** [comment]
I'll give that a try in just a second. What's the "D" prefix though?

**Comment by thebitcoiner** [comment]
Not sure what it could stand for.

https://cmake.org/cmake/help/v3.2/manual/cmake.1.html

**Comment by mvandeberg** [comment]
`-D` is the command line argument for Cmake cache entry. We use them as custom build options.

`-DLOW_MEMORY_NODE=ON` and `-D LOW_MEMORY_NODE=ON` both work and do the same thing. I prefer the second because the command's intent is clearer.
