### ISSUE TITLE
fc::array need a string() operator

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#620]
Has been mentioned [here](https://github.com/steemit/steem/commit/6b593c2d8f09d55669e4dfc135937a3c902599f4#commitcomment-19074868). Now `get_active_witnesses` command in cli_wallet returns a hex string (haven't been decoded).

>get_active_witnesses
2446728ms th_a       websocket_api.cpp:88          on_message           ] message: {"id":4,"result":"6461746173656375726974796e6f6465726f6164736361706500000000000000636f6d706c657872696e670000000000706861726573696d00000000000000006d6173746572796f646100000000000061626974000000000000000000000000726f656c616e6470000000000000000061697a656e736f7500000000000000007769746e6573732e73766b0000000000626c6f636b7472616465730000000000616e797800000000000000000000000072697665726865616400000000000000736d6f6f74682e7769746e657373000061726861670000000000000000000000636861726c6965736872656d000000006774670000000000000000000000000078656c64616c000000000000000000007375706572636f6d707574696e6738306c696f6e64616e690000000000000000636c61796f70000000000000000000006a657374610000000000000000000000"}
"6461746173656375726974796e6f6465726f6164736361706500000000000000636f6d706c657872696e670000000000706861726573696d00000000000000006d6173746572796f646100000000000061626974000000000000000000000000726f656c616e6470000000000000000061697a656e736f7500000000000000007769746e6573732e73766b0000000000626c6f636b7472616465730000000000616e797800000000000000000000000072697665726865616400000000000000736d6f6f74682e7769746e657373000061726861670000000000000000000000636861726c6965736872656d000000006774670000000000000000000000000078656c64616c000000000000000000007375706572636f6d707574696e6738306c696f6e64616e690000000000000000636c61796f70000000000000000000006a657374610000000000000000000000"

Thanks to @riverhead for reporting this issue.

**Comment by theoreticalbts** [comment]
In [this commit](https://github.com/steemit/steem/commit/39cf5f7329a44af34622084bec985e8eecd2509d) the return type is changed from `vector< account_name_type >` to `fc::array`.  The proper fix here is to change it back.

**Comment by mvandeberg** [comment]
merged
