### ISSUE TITLE
allow shared memory file location other than specified by --data-dir

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#626]
shared memory file is currently located within directory specified by `--data-dir`, however, in some use cases it would be better to keep it in separate location (i.e. having different features)
Like: `RAID-Z2` on HDD for `--data-dir` and + `tmpfs` or fast SSD drive with `nobarrier` for `shared_memory.*` files, etc.

`--shared-memory-dir`?

**Comment by mvandeberg** [comment]
That should be easy enough. By default we will still use `data_dir/blockchain` as to not break current functionality.

**Comment by mvandeberg** [comment]
merged
