### ISSUE TITLE
Add System Requirements to Readme

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#627]
This should include minimum RAM for building, expected RAM for different node configurations, required disk space, etc.

**Comment by theoreticalbts** [comment]
I've noted that the amount of dirty cache seems to reach a minimum at ~6GB for a full node including most plugins.  Therefore in practice, 8GB RAM is probably the minimum for a full node, and 12GB would be better.

**Comment by Gandalf-the-Grey** [comment]
Building full node at `v0.16.0rc3` on `Ubuntu 16.04.1 LTS` using `-j2` eats up to ~4,5GB RAM
for minimal requirements needs `-j1` should be measured, however build instructions uses `nproc` which makes memory requirements dependent on CPUs available on build machine.

**Comment by mvandeberg** [comment]
Add the Linux vm config options
https://steemit.com/steem/@steemitblog/steem-0-16-0-official-release

**Comment by abitmore** [comment]
I'd suggest tweak the Linux vm options only for the first sync and resync. It's unneeded in normal operation. It increased the possibility of data losing (mostly concerning about other services running in same vm).

**Comment by mvandeberg** [comment]
Merged
