### ISSUE TITLE
Fix return type of proxied_vsf_votes

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#631]
@roadscape points out that `proxied_vsf_votes` is `fc::array` and needs to be changed to a `vector`.

Related: #620

**Comment by abitmore** [comment]
It was `vector`. In [this commit](https://github.com/steemit/steem/commit/6b593c2d8f09d55669e4dfc135937a3c902599f4#diff-1c4a643b9adbe8c8f2d9b157e8f6edf3R92) it was changed to `fc:array`, perhaps for better performance.

**Comment by mvandeberg** [comment]
merged
