### ISSUE TITLE
How to monitor free space of a ChainBase memory mapped file?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#635]
It's good to monitor how much space can be allocated in the file, so we can be prepared to upgrade when needed.

**Comment by theoreticalbts** [comment]
For now I think I'll just print a log message whenever the minimum free memory drops by 1GB.

**Comment by abitmore** [comment]
Perhaps off-topic: we've just passed 8G threshold (for low memory node). One of my nodes crashed, another got stuck.

**Comment by abitmore** [comment]
@theoreticalbts @mvandeberg As I mentioned in the PR: https://github.com/steemit/steem/pull/642#issuecomment-264141824

>Possible issues of the implementation:
>1. when starting the node, if free memory is less than 2GB, _last_free_gb_printed will keep 0 and no message will be printed ever.
>2. assume not in case of above situation, it will print only one message when free memory dropped below 1GB, which will likely get ignored. I think it's better to print more after that.
>3. default console log level is warn, using ilog here doesn't help much
