### ISSUE TITLE
Votes shouldn't be removed on cashout 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#65]
The history of who has voted for a post is useful information that shouldn't get lost just because we make a payout.  

Now that we are allowing people to change their vote, a payout should just reset the current rshares voting for the post to 0 rather than remove it. This way users can vote again but they cannot get curation rewards a second time.

**Comment by mvandeberg** [comment]
The primary reason for this change is to keep around vote information for the website. As it isn't needed for consensus, this will be handled in a plugin and we will not be changing the consensus logic of clearing votes at this time.

**Comment by abitmore** [comment]
It's a hard fork indeed, so it changes consensus (imo it should change).
* old behavior: users can vote again and can get curation rewards again after paid out.
* new behavior: users can vote again but cannot get curation rewards again.
