### ISSUE TITLE
Unnecessary storage of blocks in ChainBase?

### ISSUE THREAD

**Issue by arhag** [steemit/steem#650]
[Here](https://github.com/steemit/steem/blob/v0.16.0/libraries/chain/database.cpp#L3036) the block is serialized and added to a `block_stats_object` so that it can be later retrieved in [this function](https://github.com/steemit/steem/blob/v0.16.0/libraries/chain/database.cpp#L271). 

Why is `fetch_block_by_number` implemented this way? Why not have it try to grab the block from `_fork_db` if it is recent (after last irreversible block) and if not, grab the block directly from `block_log`? With that implementation, there would be no need that I can see to store a duplicate copy of each block into the ChainBase database which unnecessarily adds additional memory usage and pages of memory that the OS must write to disk.

**Comment by mvandeberg** [comment]
Required changes implemented in #675
