### ISSUE TITLE
fc issue: Missing include in file_mutex.hpp

### ISSUE THREAD

**Issue by arhag** [steemit/steem#651]
I'm leaving this issue here because the steemit/fc GitHub repo hasn't enabled Issues.

The include directive `#include <memory>` is needed [here](https://github.com/steemit/fc/blob/d7276e2d15c791674722741451a4ad51972428b8/include/fc/interprocess/file_mutex.hpp#L4), otherwise some compilers give a compilation error while building fc.

The error looks something like this:
```
[ 11%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/interprocess/file_mutex.cpp.o
In file included from /root/steem_fork/libraries/fc/src/interprocess/file_mutex.cpp:1:0:
/root/steem_fork/libraries/fc/include/fc/interprocess/file_mutex.hpp:39:9: error: ‘unique_ptr’ in namespace ‘std’ does not name a type
         std::unique_ptr<detail::file_mutex_impl> my;
         ^
```

This error was reported when compiling steem v0.16.0 by a user on Ubuntu 16.10 and also by another user on Ubuntu 14.10 (gcc version 4.8.4). Compiling steem on Ubuntu 15.10 (gcc version 5.2.1) or Ubuntu 16.04 does not lead to this error. Adding the missing `memory` header as described above resolved the compilation error for the user on Ubuntu 14.10 (perhaps it would also fix the problem for Ubuntu 16.10 but that hasn't yet been tested).

**Comment by mvandeberg** [comment]
Merged
