### ISSUE TITLE
0.16.0 Miner nonce issue

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#655]
There are 2 `thread_num++` in the loop, which will perhaps lead to waste of 50% of total mining power.
https://github.com/steemit/steem/blame/v0.16.0/libraries/plugins/witness/witness.cpp#L491
https://github.com/steemit/steem/blame/v0.16.0/libraries/plugins/witness/witness.cpp#L605

**Comment by mvandeberg** [comment]
Since mining is no more this is no longer an issue.
