### ISSUE TITLE
Error message in cli_wallet: Connected node needs to enable account_by_key_api

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steem#656]
I'm getting the following issue when running the command "list_my_accounts" in the cli_wallet (0.16.0 release) after importing my private active key:

```

unlocked >>> list_my_accounts
list_my_accounts
2482419ms th_a       websocket_api.cpp:88          on_message           ] message: {"id":4,"result":null} 
2482419ms th_a       wallet.cpp:911                use_remote_account_b ] Couldn't get account_by_key API
2482419ms th_a       wallet.cpp:1003               list_my_accounts     ] Connected node needs to enable account_by_key_api
-------------------------------------------------------------------------
TOTAL                     0.000 STEEM       0.000000 VESTS            0.000 SBD

unlocked >>> 

```

I added "account_by_key_api" to my config.ini public-api setup, but initiating steemd throws a warning that it cannot load that API:

```

# Set an API to be publicly available, may be specified multiple times
public-api = database_api login_api account_by_key_api

```

steemd warning message:

```

2616214ms th_a application.cpp:414 create_api_by_name ] unknown api: account_by_key_api
2616214ms th_a application.cpp:222 on_connection ] Couldn't create API account_by_key_api

```

Any idea why I am having this issue? I have attached my build scripts to this message as well (build / rebuild scripts).

[steem-first-build.txt](https://github.com/steemit/steem/files/629185/steem-first-build.txt)
[steem-rebuild.txt](https://github.com/steemit/steem/files/629186/steem-rebuild.txt)

**Comment by thebitcoiner** [comment]
I suggest making sure you have the correct versions built and running. `steemd -v` and cli_wallet's `about` will show you more. Also, it is important to check out a specific tag after cloning, in this case v0.16.0

**Comment by taoteh1221** [comment]
@thebitcoiner Everything looks good as far as I can tell, cli_wallet output:

```

unlocked >>> about
about
2471532ms th_a       websocket_api.cpp:88          on_message           ] message: {"id":9,"result":{"blockchain_version":"0.16.0","steem_revision":"e2d4809bc6d76d047b56c205c67c35d1be700472","fc_revision":"d7276e2d15c791674722741451a4ad51972428b8"}} 
{
  "blockchain_version": "0.16.0",
  "client_version": "v0.16.0rc3-36-ge2d4809",
  "steem_revision": "e2d4809bc6d76d047b56c205c67c35d1be700472",
  "steem_revision_age": "27 hours ago",
  "fc_revision": "d7276e2d15c791674722741451a4ad51972428b8",
  "fc_revision_age": "11 days ago",
  "compile_date": "compiled on Dec  3 2016 at 13:18:51",
  "boost_version": "1.57",
  "openssl_version": "OpenSSL 1.0.1f 6 Jan 2014",
  "build": "linux 64-bit",
  "server_blockchain_version": "0.16.0",
  "server_steem_revision": "e2d4809bc6d76d047b56c205c67c35d1be700472",
  "server_fc_revision": "d7276e2d15c791674722741451a4ad51972428b8"
}
unlocked >>> 

```

steemd output:

```

------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.16.0
------------------------------------------------------
steem_blockchain_version: 0.16.0
steem_git_revision:       e2d4809bc6d76d047b56c205c67c35d1be700472
fc_git_revision:          d7276e2d15c791674722741451a4ad51972428b8


```

This was cloned from the master repo today, before building it.

**Comment by testzcrypto** [comment]
Check that you have:
**enable-plugin** = witness account_history **account_by_key**

**Comment by xeroc** [comment]
I think you may also need make it a public api. I have this worked out on the this.piston.rocks api node and the config can be found at http://piston.readthedocs.io/en/develop/public-api.html#running-your-own-node

**Comment by taoteh1221** [comment]
@testzcrypto That was the primary issue, thanks very much! :)  So the correct plugin and api are loading fine now with zero warning messages, BUT my active key seems it is not enough to automatically display my balances with the "list_my_accounts" command. "get_account" works fine though. Witness voting / token transfers work fine so I know my active key is correctly added to the wallet, and the steemd console logs show the correct public key when preforming the api request (replaced it with Xs in below console logs, but I verified it is what it should be visually besides voting / transferring tokens):

```

2590974ms th_a       websocket_api.cpp:88          on_message           ] message: {"id":7,"method":"call","params":[2,"get_key_references",[["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]]]} 

```

Any insight as to whether or not this is bug I should report in a separate thread? Closing this thread as my particular question has been answered. Thanks again.

**Comment by taoteh1221** [comment]
@xeroc I did not realize I needed to enable the plugin, on top of the separate act of enabling the public api. Thanks very much for your insight and the config example.

**Comment by abitmore** [comment]
@taoteh1221 currently if you want to use that feature, you need to enable that plugin, and, **replay** the whole block chain to get it to work. imo it's not ideal.

**Comment by mvandeberg** [comment]
There are a few plugins that rely only on current state and can be implemented without the need for a replay. Some of those plugins, like account_by_key, will be refactored to work in this way.

**Comment by taoteh1221** [comment]
Thanks for the information and insight @abitmore @mvandeberg . I will just stick with the get_account command for now so I don't cause undue SSD wear with the replay method.
