### ISSUE TITLE
Change Payout Evaluation Process

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#658]
1. All payouts made in the same block should receive the same reward-per-rshare^2 without respect to the order in which payouts are made.
2. All payouts should be made only in response to a special operation included by block producer
3. Reindexing the blockchain should not require processing of vote operations (older than 30 days)
4. Block producers will validate and enforce the rule that block producers include valid / expected / explicit reward payout transactions.

With the blockchain logic structured in this way we would be one-step closer to separating votes into their own blockchain.  This is the biggest bottleneck for STEEM reindexing at this time and should be our first focus.

**Comment by mvandeberg** [comment]
This issue contains tasks that are longer term than we are concerned with at this point in time. Task one is handled by issue #771. Subsequent tasks will receive their own issue as we are ready to implement them.
