### ISSUE TITLE
Aggregate Reward Payouts into Reward Balance separate from Checking

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#659]
Currently rewards are paid directly into the user's account balance, this limits the ability scale other options and results in many micro-payments that user's are unable to fully appreciate.

All users should have their rewards paid into a reward balance for STEEM, SP, and SBD.  These balances can have higher precision than the main checking account to accumulate the rounding errors from payouts.   

Once per day all rewards greater than a minimum balance can be swept into their checking account through an explicit virtual operation signed by the witness.  

This will be  baby step toward keeping reward calculation as a separate / independent thread from the rest of the blockchain.

**Comment by mvandeberg** [comment]
This is a requirement of the multi-chain fabric.

**Comment by mvandeberg** [comment]
Merged

**Comment by abitmore** [comment]
IMHO this need to be mentioned in the release note.

**Comment by abitmore** [comment]
By the way, it's best to pay witnesses this way as well if not done already, so there will be much less witness-voting related computations. Perhaps it worth a new ticket.

**Comment by mvandeberg** [comment]
The focus of this hardfork was to simplify the content and content reward systems in Steem. For this hardfork, handling witness balances is out of scope. This change may fit in with some of the ideas we are internally considering for the next release.
