### ISSUE TITLE
Invalid JSON-RPC response

### ISSUE THREAD

**Issue by tchap** [steemit/steem#66]
I am calling the RPC endpoint from Go and I am getting `bad response` error from the client library since `steemd` seems not to return any `jsonrpc` field in the response, even though the field MUST be set to `2.0` according to the spec.

**Comment by tchap** [comment]
Disabled the `jsonrpc` version string check and the client library started working, so I can really confirm this bug.

**Comment by mvandeberg** [comment]
We should probably update fc to conform to JSON RPC standard.

**Comment by mvandeberg** [comment]
Fixed in #1265
