### ISSUE TITLE
Reset Current Virtual Time / Position / Next Scheduled Time Weekly

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#660]
The current witness schedule depends upon the following information:

1. STEEM POWER + WITNESS VOTES
2. CURRENT VIRTUAL TIME + NEXT_SCHEDULED_TIME + POSITION
3. POW queue 

The order in which operations are applied impacts all of the above.   Ideally it should not be necessary to calculate these values during replay just to derive the current state.

I propose modifying the protocol such that the CURRENT_POSITION and NEXT_SCHEDULED_TIME and CURRENT VIRTUAL TIME are reset once per week.  When they are reset the following occurs:

1. all witnesses positions are reset to 0
2. virtual time is reset to 0
3. all witnesses virtual schedule time is calculated based upon total votes

The less information that depends upon replaying the full blockchain the less information is required to synchronize state.  With this change, we no longer need to include witness schedule information for snapshots that occur on the reset block.  

POW Queue + Witness Votes + SP will still be required in any vote snapshot. 

Witnesses with a virtual schedule time that is more than ROUNDS_PER_WEEK/4 times in the future than the average of the top 4 runner up will have their scheduled time set to infinity.  There is no need to manage / maintain this state for witnesses that don't have a realistic probability of getting scheduled in less than 1 week.

**Comment by mvandeberg** [comment]
Closing, won't fix.
