### ISSUE TITLE
Default plugins should use group 0 for connecting to on_applied_block

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#661]
This way we can deal with plugins whose on_applied_block() callback must be loaded before/after others.

**Comment by bytemaster** [comment]
What is a group?

**Comment by theoreticalbts** [comment]
It's an integer used to determine ordering of signal handlers.  See [here](http://www.boost.org/doc/libs/1_62_0/doc/html/boost/signals2/signal.html#idm46563209034032-bb).

**Comment by theoreticalbts** [comment]
This is probably still useful functionality with `appbase` and relatively straightforward to implement, but I haven't written any code so I'm removing my assignment.
