### ISSUE TITLE
Implement object streaming plugin

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#662]
Graphene once had the ability to stream modified objects.  This capability was removed earlier in Steem development.  After some discussion with our web and scalability experts, I'm going to re-add streaming functionality.  This will be per-block streaming, not per-account.  The focus of the streaming will be on enabling mirroring of some/all of the blockchain database in an external database (SQL, Redis, etc.) which is write-only from steemd's perspective.

**Comment by theoreticalbts** [comment]
This would definitely be useful, but should probably get our type system straightened out before we work on this.

**Comment by mvandeberg** [comment]
This was done with block stats.
