### ISSUE TITLE
Caught unexpected exception in plugin

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#665]
```
1509160ms th_a       application.cpp:439           handle_block         ] Got 3 transactions from network on block 7354923
1510058ms th_a       database.cpp:903              notify_post_apply_op ] Caught unexpected exception in plugin
1512273ms th_a       database.cpp:903              notify_post_apply_op ] Caught unexpected exception in plugin
1512274ms th_a       application.cpp:439           handle_block         ] Got 3 transactions from network on block 7354924
1516439ms th_a       application.cpp:439           handle_block         ] Got 7 transactions from network on block 7354925
```

The error message doesn't tell which plugin :(

**Comment by realhagie** [comment]
Could be this in 0.16.0 final

2877952ms th_a       database.cpp:929              notify_post_apply_op ] Caught exception in plugin: 10 assert_exception: Assert Exception
static_variant does not contain a value of type steemit::protocol::pow2
    {"t":"steemit::protocol::pow2"}
    th_a  static_variant.hpp:305 get
2880248ms th_a       database.cpp:929              notify_post_apply_op ] Caught exception in plugin: 10 assert_exception: Assert Exception
static_variant does not contain a value of type steemit::protocol::pow2
    {"t":"steemit::protocol::pow2"}
    th_a  static_variant.hpp:305 get

**Comment by mvandeberg** [comment]
#666 has more details
