### ISSUE TITLE
Update mining code / stats for equihash

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#668]
I'm going to refactor the stats display.  Basically every time a mining thread shuts down, it should stream off its stats to a dedicated stats thread.  The stats thread will aggregate all stats into one-minute intervals, then aggregate all one-minute intervals to one-hour stats.

**Comment by theoreticalbts** [comment]
Issues to solve:

- Clean shutdown of witnesses
- Double increment of thread_num

**Comment by mvandeberg** [comment]
Merged
