### ISSUE TITLE
No of People I Am Following has gone from 753 to 61 without my intervention since HF today

### ISSUE THREAD

**Issue by thecryptofiend** [steemit/steem#671]
As stated I just noticed the number of people I am following is now showing as 61 (instead of 753).  If I click on the link it only allows me to view 61 names.  I have already had one user asking me why I unfollowed.  I am assuming this is a bug?  My follower number has not changed.  Here is a post I made about this.  It seems I am not the only experiencer of this issue:

https://steemit.com/steemit/@thecryptofiend/possible-bug-over-90-of-people-i-am-following-have-vanished-since-the-fork-down-from-753-to-61

I thought I should let you all know ASAP.  Thanks.

**Comment by thecryptofiend** [comment]
OK more information.  It seems to be a display issue. Logging out and then in restores the followers to the previous number.  Refreshing the page puts it back to 61.  However checking Steemdb still shows the correct number.  Also on speaking to others who have the exact same issue neither my nor their number of followers has changed.

**Comment by BarryDutton** [comment]
I am not a techhie at all.... but many are having the same issues, as am I.  Here is my post to show the screen caps.

https://steemit.com/steemit/@barrydutton/system-error-after-the-hardfork-i-lost-2-3-of-the-people-i-was-following-check-your-account-page-and-share-this

**Comment by ausbitbank** [comment]
I see the same issue. My profile cycles between 143 and 1034 people followed. 
If I hard refresh my profile page it shows 1034 for a moment, before changing back to 143 ..

**Comment by jacobcards** [comment]
I noticed the people that are being displayed are people I have recently followed Im assuming follows before a certain time frame are not displaying. Hmmm....

**Comment by thecryptofiend** [comment]
>I noticed the people that are being displayed are people I have recently followed Im assuming follows before a certain time frame are not displaying. Hmmm....

The people that are being displayed for me are not recent follows (at least not all of them).

**Comment by mvandeberg** [comment]
Forwarded this to steemit.com

Closing as it is not a blockchain related bug.
