### ISSUE TITLE
Don't keep all blocks in memory

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#675]
Currently a fair amount of the memory usage of steemd is due to keeping all the blocks in memory.  It's fairly low-hanging fruit to take this data out of memory and read from the block log instead.

**Comment by mvandeberg** [comment]
I have been working on this a little.

**Comment by BhuzOr** [comment]
#650

**Comment by arhag** [comment]
Why are you storing blocks into ChainBase at all in the first place? Even if you remove that data later, that is still causing additional pages of memory to become dirty unnecessarily, which may lead to additional IO. There is no need for the `packed_block` field in the `block_stats_object`. Blocks newer than the last irreversible block can be retrieved from `_fork_db` in the `fetch_block_by_number` function.

**Comment by mvandeberg** [comment]
Merged
