### ISSUE TITLE
Properties not updated in witness schedule object

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#682]
As pointed out in the second screenshot in #681 we have some fields in `witness_schedule_object` that are not being updated, specifically `maximum_block_size` and `sbd_interest_rate`.  These fields are mirrored in the GPO; the GPO fields *are* being correctly updated.  Moreover, the GPO fields are what's referenced by all consensus code.  So the behavior is correct, it is just the object (and thus the API call result) that is wrong.

After some discussion with @mvandeberg we've decided to simply update both sets of fields, rather than attempting any larger refactoring at this time.

**Comment by mvandeberg** [comment]
Merged
