### ISSUE TITLE
Unit test for signature stripping

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#684]
This test proves we're not vulnerable to an attack which re-uses a transaction with a different signature set (e.g. if 2-of-3 multisig signed by (A, B) is included, a version of the transaction signed by (B, C) must fail).

Fortunately we use txid for duplicate checking, txid is the hash of the transaction excluding sigs.  So the attack doesn't work.  But I've written a unit test for it anyway.

**Comment by mvandeberg** [comment]
Merged
