### ISSUE TITLE
Feature Suggestion: Tipping Balance

### ISSUE THREAD

**Issue by clayop** [steemit/steem#690]
When users want to give a tip, they need to login with active key. This is inconvenient as well as less secure since there will be more possibility of exposing active keys. This suggestion is to address it and to encourage tipping activities.

Features:
1. Using active key, users can recharge their tipping balance with SBD
2. Tipping balance can be used with posting key
3. Tipping balance has a limit, which is set by users (e.g. 20 SBD)
4. Received tips go to tipping balance first. When it exceeds a limit, the rest of them goes to normal SBD account (Given 10 SBD limit, when one receives 12 SBD, 10 SBD goes to tipping balance and 2 SBD goes to normal SBD balance)

This topic was discussed by @arhag and @smooth in Slack.

**Comment by clayop** [comment]
I would like to rename it as "Quick balance" or "Gift balance" (the latter can be weird with small merchandising activities but better than "tipping" IMO)

**Comment by mvandeberg** [comment]
Closed, won't fix.
