### ISSUE TITLE
Missed block with nullified signing key

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#691]
```
1953013ms th_a       witness.cpp:266               block_production_loo ] Generated block #7461276 with timestamp 2016-12-10T10:32:33 at time 2016-12-10T10:32:33 by bhuz
...
1981757ms th_a       websocket_api.cpp:88          on_message           ] message: {"id":18371,"method":"call","params":[2,"broadcast_transaction_synchronous",[{"ref_block_num":55717,"ref_block_prefix":2966096469,"expiration":"2016-12-10T10:33:30","operations":[["witness_update",{"owner":"bhuz","url":"https://steemit.com/witness-category/@bhuz/bhuz-witness-thread","block_signing_key":"STM1111111111111111111111111111111114T1Anm","props":{"account_creation_fee":"10.000 STEEM","maximum_block_size":65536,"sbd_interest_rate":1000},"fee":"0.000 STEEM"}]],"extensions":[],"signatures":["1f40beb5216aae990dba375ca024e0a783814ec094869f5ebade412d0880317b1b5ceec2fff53a4d65c950e44d2a9b62fcef1c2434b948952459cff4ac3926605a"]}]]}
1983186ms th_a       application.cpp:488           handle_block         ] Got 4 transactions from network on block 7461286
...
2019046ms th_a       application.cpp:488           handle_block         ] Got 4 transactions from network on block 7461298
2022007ms th_a       witness.cpp:278               block_production_loo ] Not producing block for bhuz because I don't have the private key for STM1111111111111111111111111111111114T1Anm
2023007ms th_a       witness.cpp:278               block_production_loo ] Not producing block for bhuz because I don't have the private key for STM1111111111111111111111111111111114T1Anm
2024007ms th_a       witness.cpp:278               block_production_loo ] Not producing block for bhuz because I don't have the private key for STM1111111111111111111111111111111114T1Anm
2025165ms th_a       application.cpp:488           handle_block         ] Got 6 transactions from network on block 7461299
...
```

I guess that updating the signing key to the nullified one, doesn't really *remove* the witness from the schedule, but only prevent him to be scheduled in the later rounds?

This means that if a witness nullifies his signing key when he is already scheduled for the current round, there is no way that witness can prevent missing a block.

Nullifying the signing key instantly after generating a block would improve the chance to make the request before the next round starts... still you can not be 100% sure (you could be the last scheduled witness for the current round, and in the next block you will be already scheduled for the new round just begun)

Can the nullifying process be improved to remove this "edge" case?

Of course, you could:
1- Wait for the next round to start
2- Check that your witness is not scheduled in the last slots
3- Wait to generate the block
4- Nullify the signing key
But would be nice to have a better handling that does not rely on the user

**Comment by NateBrune** [comment]
![](http://i.imgur.com/8Fb2MhL.png)

**Comment by sneak** [comment]
What problem does this solve? Missed blocks aren't a big deal.

**Comment by mvandeberg** [comment]
I don't believe this issue is serious enough to devout dev resources to.
