### ISSUE TITLE
Database API get_account add follower/following count

### ISSUE THREAD

**Issue by adcpm** [steemit/steem#692]
Is that possible that the method "get_account" from the database API return following_count and follower_count? Actually to get this information it require multiple get_followers requests, it retrieve followers 100 by 100 but not seem to be scalable solution to get the follower/following count.

![image](https://cloud.githubusercontent.com/assets/16245250/21079895/63e040f6-bfa0-11e6-952a-2a2cb501336d.png)

**Comment by svk31** [comment]
v0.16.0 introduced a new method `get_follow_count` that gives you the number of followers/following directly for a given account.

**Comment by adcpm** [comment]
Amazing! Thank you Sigve!

I think we would also need a method has_follow. If we dont want to do a get_follower loop to know if you've already followed someone or not.

**Comment by svk31** [comment]
No problem. I believe there are plans to address things like getting follower data, but at least with this new method you can delay fetching all the followers until actually needed, and `has_follow` you can do by simply calling get_followers/get_following with the account in question.
