### ISSUE TITLE
Can't connect with cli_wallet 

### ISSUE THREAD

**Issue by gulfpearl** [steemit/steem#693]
Hello, I'm setting up a witness and the chain is still in the process of syncing. 

I tried connecting to the node using the cli_wallet but get the following exception:

```
root@steemd:~/witness_node_data_dir/logs/p2p# cli_wallet
Logging RPC to file: logs/rpc/rpc.log
Starting a new wallet
2246046ms th_a       main.cpp:154                  main                 ] wdata.ws_server: ws://localhost:8090 
0 exception: unspecified
Underlying Transport Error
    {"message":"Underlying Transport Error"}
    asio  websocket.cpp:444 operator()

    {"uri":"ws://localhost:8090"}
    th_a  websocket.cpp:673 connect
```
Is this just because it still hasn't finished downloading the blockchain? I haven't configured the rpc endpoing in the ini file so it should work with the default localhost:8090.

**Comment by gulfpearl** [comment]
I should also add, it hasn't logged or created the logs/rpc/rpc.log file in the witness_node_data_dir as it says it has.

**Comment by BhuzOr** [comment]
Did you set up the rpc?
`./steemd --rpc-endpoint 127.0.0.1:8090`
or add in the config.ini
`rpc-endpoint = 127.0.0.1:8090`
and restart steemd

**Comment by abitmore** [comment]
> I haven't configured the rpc endpoing in the ini file so it should work with the default localhost:8090.

If no rpc endpoint is specified, `steemd` won't listen at all.

**Comment by gulfpearl** [comment]
Thanks that was it, I assumed there was a default since the client has a default.

**Comment by parsagh97** [comment]
I'm using the docker image in this case and I get the same error, how should i fix it?
