### ISSUE TITLE
Markdown for Images Not Functioning

### ISSUE THREAD

**Issue by altimagewritingco** [steemit/steem#694]
Markdown style says the format for pictures is:
![your text] (url)

However, when using this format, you now see:

![your text] (
![image](https://cloud.githubusercontent.com/assets/18469214/21085464/c0d75cb4-c012-11e6-8342-83ccae9735ae.png)
)

*I put the space between the "]" and "(" symbols in this issue, but not in the steemit editor.

**Comment by Gandalf-the-Grey** [comment]
Please make sure that you are using "raw" mode, not editor when willing to use markdown.

I observed that above can happen when you use markdown in editor:
```
![your text](https://url)
```
and switch to raw mode. This would change code to:
```
<html>
<p>![your text](https://url)</p>
</html>
```
In this case removing html might help

**Comment by abitmore** [comment]
If need, it should be tracked in https://github.com/steemit/steemit.com/issues.

**Comment by roadscape** [comment]
It's most likely the issue described by @Gandalf-the-Grey. 

If not, please file here instead: https://github.com/steemit/steemit.com/issues

**Comment by altimagewritingco** [comment]
Removing the html did help. Thanks all!
