### ISSUE TITLE
Miner stucks when private key misconfigured

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#7]
With [this code](https://github.com/steemit/steem/blob/e8fdb8166c6f1677eff614d26af2cf9a84ca73e1/libraries/plugins/witness/witness.cpp#L406-L410), the miner will still try to mine when an account with same name was already registered on the chain with a different key set, but it will get nothing.

**Comment by mvandeberg** [comment]
This is a minor issue that can be solved through changing the user configuration. 

I agree the witness node should handle this better than wasting hash power, but it is easy enough for the user to check with the cli wallet if their name is taken.

**Comment by sneak** [comment]
@mvandeberg do we want to close this WONTFIX or should we leave it open?

**Comment by mvandeberg** [comment]
Mining is being removed so this issue is irrelevant.
