### ISSUE TITLE
Docker dosent works

### ISSUE THREAD

**Issue by Hostile** [steemit/steem#700]
docker run \
    -d -p 2001:2001 -p 8090:8090 --name steemd-default \
    steemit/steem

gives:

root@thaiprochat:~# docker run \
>     -d -p 2001:2001 -p 8090:8090 --name steemd-default \
>     steemit/steem
Unable to find image 'steemit/steem:latest' locally
Pulling repository docker.io/steemit/steem
docker: Tag latest not found in repository docker.io/steemit/steem.
See 'docker run --help'.

**Comment by jredbeard** [comment]
This was due to a change in the way we do CI - latest tag doesn't exist as of right now but it will on the next push to the 'stable' branch. For now, you can do this instead:
`docker run -d -p 2001:2001 -p 8090:8090 --name steemd-default steemit/steem:master`
