### ISSUE TITLE
Refactor switch(which) as visitor in pow2 validation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#702]
Whenever there's a `switch(which)` it should usually be replaced by a visitor.  In particular [here](https://github.com/steemit/steem/blob/600c46410ecd6a25b997f0d614915cdb2597b54d/libraries/protocol/steem_operations.cpp#L204-L215) both control paths are doing the same thing (calling validate()) so this is a prime candidate for such refactoring.

**Comment by theoreticalbts** [comment]
Rebased to fix CI.

**Comment by mvandeberg** [comment]
Merged
