### ISSUE TITLE
Disappearing emoji bug

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#714]
From https://github.com/steemit/steemit.com/issues/854

----

> Here I reset the content of a post:
> https://steemd.com/tx/fda96fdcb90f7fd7fbb8fc20c161bf33735c2b2a
> ```
> http://static.flickr.com/48/109552812_f12c097f9e_o.jpg
> test eeee
> ```
> 
> Then edited to append an emoji:
> https://steemd.com/tx/cba0f7e9c0e78c5582039b556c99109460837f3e
> ```
> @@ -57,8 +57,11 @@
> est eeee
> + %F0%9F%98%A1
> 
> ```
> 
> At this point steemd shows:
> 
> ```
> >>> get_state "spam/@test-safari/november-spam"
> ...
> "body": "http://static.flickr.com/48/109552812_f12c097f9e_o.jpg\ntest eeee ",
> ```
> 
> Not sure where `%F0%9F%98%A1` (😡) went

Any idea what might be happening? It's fairly easy to reproduce when the emoji is at the end of the post (but it doesn't need to be). In other cases it works fine... usually.

**Comment by mvandeberg** [comment]
We believe this is a bug in in the `diff_match_patch` library.

**Comment by mvandeberg** [comment]
Closing, won't fix.
