### ISSUE TITLE
How to Change Permissions and Keys?

### ISSUE THREAD

**Issue by finleyexp** [steemit/steem#723]
Hello Steemians! Your help is greatly appreciated. I've scoured the internet searching for the answer to: How do I change Permissions and Keys? 

All the SteemIt articles that I've found are six to eight months old and no longer seem to apply as there is no "pencil" icon for me to click. Does anyone know what to do?

**Comment by mvandeberg** [comment]
finleyexp, I am going to close your issue because there is no reported bug. If need assistance using Steemit.com or the CLI wallet, you can ask knowledgable community member on [steemit chat](https://steemit.chat/home).
