### ISSUE TITLE
Feature: Show a List of APPs or 3rd Parties Given Account Permissions

### ISSUE THREAD

**Issue by finleyexp** [steemit/steem#724]
In the Permissions section, it seems beneficial to add a list of who else is using the account (APPs, etc.). Additionally, adding some way to remove these 3rd party users would be helpful. If this already exists, please let me know how to access the feature. Thank you!

**Comment by mvandeberg** [comment]
This is a Steemit.com UI feature request. Please create the issue in the correct repository [here](https://github.com/steemit/steemit.com).
