### ISSUE TITLE
Authority Key Revoker

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#725]
Allow users to declare accounts/keys as a revoker on an account/key in an authority.

Adding a revoker to a key requires a signature at the same permission level. (Adding a revoker to an active key, requires the active authority to be fulfilled).

The revoker can only remove the key they have been added to as the revoker. They cannot sign transactions for the account nor can they reject past transactions that were signed with the key they can revoke. The use case for this feature is an emergency removal of a key. Specifically, keys added on behalf of third parties.

**Comment by mvandeberg** [comment]
Spec:

We want to allow third parties to be able to act on behalf of users. This is easy to do by adding a key or an account to the user's account authority, but there are inherent risks in granting that level of permission to third parties. Key revocation is an added security layer that allows a trusted individual to revoke keys on your behalf. The intended use for a such a feature is a watchdog with a kill switch on third party keys to limit damage to an account if the third party is compromised.

An added requirement is that authorities can no longer have permission over changing authorities at their same level. Currently an active key can add and remove active keys. Under this model, an active authority can no longer act in this way. Otherwise an active key with a revoker can add another active key without a revoker and misbehave on the non-revokable key.

To implement this specification we need two new operations, `add_authority_revoker_operation` and `revoke_authority_operation`.

```
struct add_authority_revoker_operation
{
   account_name_type             account;    /// Account whose authority to modify
   account_name_type             revoker;    /// The account name of the revoker
   authority_classification_type auth_class; /// The auth type to modify (owner, active, posting)
   authority_type                auth;       /// The public key or account name of an authority
}
```

```
struct revoke_authority_operation
{
   account_name_type             revoker;    /// The account name of the revoker
   optional< account_name_type > account;    /// The account name to revoke an auth on. Left blank revokes all matching auths that can be revoked
   authority_type                auth;       /// The public key or account name of an authority
}
```

There can only be one revoker per key/account entry in the authority. Owner authority cannot have revokers. This is to disincentivize adding third party keys to the owner authority because this should not be done under any circumstance. It is also impossible to counter the attack stated above because there is no authority higher than the owner authority and such an attack would necessitate an account recovery for the rightful owner to regain control of these account.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [view page for specific comment does not display comment's children #814](https://trello.com/c/g9HxXWA8/161-view-page-for-specific-comment-does-not-display-comment-s-children-814)

**Comment by bytemaster** [comment]
It would be nice if we could arrange for a more general approach.  Also, from the description given on this issue I am unable to fully understand the use case.

**Comment by mvandeberg** [comment]
This will be implemented using a soft forking implementation. Details to follow.

**Comment by mvandeberg** [comment]
This feature is dead. Closing. If something similar appears again, it will be in a new issue.
