### ISSUE TITLE
Use visitor for pow2 required active authorities

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#726]
[This code](https://github.com/steemit/steem/blob/e70b1560cef70887ddf8c0b74d0d9bc8cae3dada/libraries/protocol/include/steemit/protocol/steem_operations.hpp#L621-L631) should be refactored to use a visitor (so it Just Works if we define a new PoW type [as is planned to happen imminently](https://github.com/steemit/steem/issues/722) ).  We should also move this code out of the header so the resource-intensive template implementation is only required within the compilation unit.

Related:  #702 #722

**Comment by mvandeberg** [comment]
Merged
