### ISSUE TITLE
cli_wallet command `get_account` doesn't return `witness_votes` list after HF16

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#730]
After HF16, the cli_wallet command `get_account` doesn't return `witness_votes` list, as well as some other data.

Possible reason: in [this commit](https://github.com/steemit/steem/commit/39cf5f7329a44af34622084bec985e8eecd2509d#diff-f2a7dbde405ff1b84094db5f33fb1557R192), return type of `get_account` command is changed from `extended_account` to `account_api_obj`.

**Comment by mvandeberg** [comment]
I don't think this is an issue any longer.
