### ISSUE TITLE
Remove Posting Limit

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#732]
Currently there is a 4-post per day soft limit on posts.  This limit should be removed as part of an overall simplification plan.

**Comment by mvandeberg** [comment]
This issue usurps #733

**Comment by bitcoinparadise** [comment]
Would this not allow lower quality content? It could turn into a numbers game and people could try to pump out posts as much as possible to see what percentage of their posts they created. 

This can make it confusing and even harder to find REAL content when I find it hard as it as already.

**Comment by 3beanzz** [comment]
Is it a good thing or a bad thing if somebody powers up a lot more than [this user](https://steemit.com/@tamim) did in order to post more than 4 times and upvote himself?  How would we address the issue of spam if this were a user who powered up a lot more SP?

**Comment by mvandeberg** [comment]
This has been merged.
