### ISSUE TITLE
Simplify the Protocol in Preparation for Scalability Enhancements

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#733]
The Steem protocol has gotten overly complex as we sought to counter various kinds of perceived abuses. Moving forward we would like to simplify the protocol so that everyone can understand how it works and we can more easily expand it.

- [ ] Remove 4 Post Limit
- [ ] Remove Bandwidth Rate Limiting from Consensus (use soft fork controlled by block producers)
- [ ] Remove Comment Depth Limit
   - [ ] Payout Comments on schedule independent of Parent Post

**Comment by mvandeberg** [comment]
I am breaking up this issue into individual issues for easier tracking and relying on the github milestone to track the checklist.
