### ISSUE TITLE
Group Operations by Future Fiber (sidechain)

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#734]
Future scalability of Steem is designed around a fabric of chains.  It is desirable to enforce rules today that are in line with the future grouping so that app developers understand the kinds of restrictions that they will face once full side chains are implemented.

Groups:
1. Voting
2. Transfer SBD
3. Transfer STEEM
4. Witness Voting and Steem Power / Power Up/Down
5. Market Operations (limit order create / cancel)
6. Posting / Updating 
7. Account Authority 

This will involve the following:
1. A visitor on operations that returns which future fiber they will be a part of
2. A validator on transactions that enforces all operations within transaction belong to the same fiber
3. A validator on blocks that enforces all transactions are sorted by fiber
            
All of these changes can be implemented as a soft-fork without requiring any existing nodes to upgrade.

**Comment by mvandeberg** [comment]
Closing, won't fix.
