### ISSUE TITLE
Market operations charge bandwidth based on tx size

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#736]
Basically [this loop](https://github.com/steemit/steem/blob/01027e087b01a131c1ca75e29551377f14475065/libraries/chain/database.cpp#L3245-L3251) charges `n^2` bandwidth for transactions that combine `n` market operations.

For example if the tx header + sig is 60 bytes and each market order is 10 bytes, a 160-byte transaction which combines 10 market operations will be charged for 1600 bytes, because each of the 10 ops results in a 160 byte charge.

But putting them into 10 different 70-byte transactions, while indisputably much more resource intensive (consuming 700 bytes of blockchain space and requiring 10 times as many signature checks), will be charged for 700 bytes.

This code is heavily modified by #563.  Bandwidth checks will become soft by #563.  Market will eventually be moved to its own fiber, see #733.  So this ticket will likely be obsolete in a few months.

**Comment by bytemaster** [comment]
Apparently you didn't fully comprehend the code.  It breaks after detecting the first market operation. Therefore, it will only charge once.

**Comment by theoreticalbts** [comment]
Oops.  Yeah, you're right.
