### ISSUE TITLE
Login method of the login_api() returns always true

### ISSUE THREAD

**Issue by marvin-we** [steemit/steem#739]
Hello together,

I am currently writing an api wrapper in Java and faced an issue: No matter what username and password I provide, the login method of the login_api returns true (even empty Strings work). I used several different nodes and endpoints but the behavior is the same.

The only way to check, if the login was successful is to see if the get_api_for_name("network_broadcast_api") returns an error (==> Not logged in) or not (==> logged in).

Could you have a look at it?

**Comment by abitmore** [comment]
You need to configure `api-user` for `steemd` (for example in `config.ini`) to enable username/password authentication. Please check [this document](https://github.com/steemit/steem/blob/v0.16.0/doc/api-notes.md) for more info.

**Comment by marvin-we** [comment]
Hmm ... According to the documentation of [api.hpp](https://github.com/steemit/steem/blob/develop/libraries/app/include/steemit/app/api.hpp) 

> @return True if logged in successfully; false otherwise

The login method should at least return false if the user / password combination is wrong.

The second point is that I connect to a public node like "wss://node.steem.ws" and I am not able to access the "network_broadcast_api" until I login with my own credentials. As I am pretty sure that no one defined my user data for this public node, there has to be something more.

**Comment by abitmore** [comment]
I think `network_broadcast_api` is enabled implicitly. With "wss://node.steem.ws" you can login with empty strings and it will work.

**Comment by marvin-we** [comment]
Ouh man, you are right - That one cost me some hours of my life :D Thanks a lot!
