### ISSUE TITLE
Allow users to disable replies and payouts on posts (Proposal)

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#74]
There are many applications that could benefit from being able to post a comment without the ability for others to reply and or receive a payout.

A post that can receive a payout or have a reply that is capable of receiving a payout is a post that cannot be hidden from the users. By allowing authors to disable the potential for payouts new applications can be built that give front end developers the ability to hide (or reinterpret) content.

Examples include:
1. posting proposed edits 
2. meta-actions such as simulating an issue tracking system

In theory many of these meta-features could be implemented via custom operations, but custom operations do not have the potential for a "graceful fallback" in user interfaces that do not know about the feature.

Implementation Approach
1. Define a new operation that allows the author to enable, but not disable this feature. 
2. If a post has this feature enabled, then the cashout method ignores the theoretical pending payout.
3. users can still vote, but no rshares will accumulate to posts with this flag.

**Comment by arhag** [comment]
> In theory many of these meta-features could be implemented via custom operations, but custom operations do not have the potential for a "graceful fallback" in user interfaces that do not know about the feature.

Should they though? How graceful is that fallback anyway?

The downside (as discussed in my moderation proposal which you implied with your response that custom operations would be a smarter way of implementing it, which I agree with!) is that the nested comment limit means that replies as a mechanism for proposed edits or meta-actions cannot work on a comment at `depth == 5`. 

If you do choose to continue with this approach, at least allow a comment to be posted with `depth == 6` only if they enable this flag.

**Comment by mvandeberg** [comment]
Addressed in #85
