### ISSUE TITLE
Disable Curation Rewards  - Proposed Change

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#75]
Experience gained from the current curation rewards algorithm has taught me several things:

1. People spend more time trying to game the rewards than they do trying to curate 
2. Most people would curate with or without rewards 
3. Curation is it's own reward. As a curator you have the power to pay others with a simple vote. 

The original idea was to encourage people to read new submissions and upvote them so that we could have rapid discovery of quality content. Instead people are thinking about how every vote they cast lowers their potential curation payouts. Result: less voting. 

Complex games will detract from the system and cause people to question whether upvotes are legitimate or done for the sole purpose of gaining a payout.

Implementation
----------------------
All votes prior to the hardfork qualify for curation rewards.
All votes after the hardfork do not qualify for curation rewards

**Comment by arhag** [comment]
Don't throw the baby out with the bathwater. Curation rewards may be salvageable. Let's work through the possibilities. I think blinded votes with grace periods, changing the payout function (not rshares^3 / total_abs_rshares^2), and giving boosts to votes for underdogs can potentially deal with a lot of these games and perverse incentives.

**Comment by killerstorm** [comment]
Less voting might actually be a good thing:

1. People will upvote things which they believe are actually important. A corollary to that is that stupid shit and memes will get fewer votes.
2. You can actually gauge post importance by sampling few opinions, thus encouraging everyone to vote for everything they like is a waste of blockchain space. Imagine if every frontpage vote will get 10k+ upvotes, that might be somewhat of a problem.

But payout function Steem uses now is really bad, I've proposed a better one in this post: https://steemit.com/steem/@killerstorm/why-steem-curation-reward-is-needlessly-unfair-and-how-to-fix-it

**Comment by mvandeberg** [comment]
Addressed in #101
