### ISSUE TITLE
Incorrect total_payouts for `tags` in get_state

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#751]
![image](https://cloud.githubusercontent.com/assets/5168676/21616219/48dcd3b0-d1a6-11e6-8d23-505a8a5a1f51.png)

```
>>> get_state "xxxxxxxxxxxx"
...
  "tags": {
...
    "steemit": {
      "name": "steemit",
      "total_children_rshares2": "200039810295173886873591931589",
      "total_payouts": "295800102.592 SBD",
      "net_votes": 920150,
      "top_posts": 22429,
      "comments": 83806
    },
```

**Comment by mvandeberg** [comment]
Upon investigation of where this data is calculated in the tags plugin, correcting the issue is not a simple fix given the structure of the tags plugin. Is this data used anywhere besides this view and how important is it that we maintain this view?

**Comment by mvandeberg** [comment]
Disregard the previous comment. I think I have a way to do it.

**Comment by mvandeberg** [comment]
Closing as this was merged.
