### ISSUE TITLE
Remove Bandwidth Rate Limiting from Consensus

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#766]
Bandwidth only needs to be used to filter transactions by witnesses and can safely be implemented as a soft fork outside of consensus. There will still be a supported method by which to calculate bandwidth.

This issue usurps #733

**Comment by theoreticalbts** [comment]
Contains partial revert of #176

**Comment by mvandeberg** [comment]
The branch contains code for #732 as well. I knocked them both out at the same time and needed the hardfork constants. If you would rather, we can merge #732, rebase #766 on master and then merge #766.

**Comment by mvandeberg** [comment]
Merged
