### ISSUE TITLE
Node hang with `Host not found (authoritative)`

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#77]
One of my nodes hang with these messages:
```
3057412ms ntp        ntp.cpp:98                    request_now          ] 0 exception: unspecified
process exited with: Host not found (authoritative)
    {"message":"Host not found (authoritative)"}
    asio  asio.cpp:88 resolve_handler

    {}
    ntp  asio.cpp:160 resolve
```
Perhaps caused by temporary networking problem. The process didn't exit, but hang.

Same issue was reported by this user as well https://steemit.com/steemhelp/@hannixx42/error-when-pushing-block-3080000-unlinkableblockexception-unlinkable-block

**Comment by abitmore** [comment]
Most likely the NTP error is not the cause. There are messages afterwards:
```
3357454ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to -249 us
957491ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to -594 us
3057554ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to 3037 us
```

**Comment by abitmore** [comment]
Too old. Closing.

**Comment by alenn-m** [comment]
I have the similar problem. Is there any fix for this:

`------------------------------------------------------

            STARTING STEEM NETWORK

------------------------------------------------------
initminer public key: STM8GC13uCZbP44HzMLV6zPZGwVQ8Nt4Kji8PapsPiNq1BK153XTX
chain id: 0000000000000000000000000000000000000000000000000000000000000000
blockchain version: 0.19.10
------------------------------------------------------
618083ms main.cpp:121                  main                 ] Backtrace on segfault is enabled.
618083ms webserver_plugin.cpp:361      plugin_startup       ] Waiting for chain plugin to start
618083ms chain_plugin.cpp:394          plugin_startup       ] Starting chain with shared_file_size: 17179869184 bytes
618083ms chain_plugin.cpp:503          plugin_startup       ] Opening shared memory from /var/lib/steemd/blockchain
618084ms chain_plugin.cpp:526          plugin_startup       ] Started on blockchain with 0 blocks
618084ms webserver_plugin.cpp:122      operator()           ] start processing ws thread
618084ms webserver_plugin.cpp:135      operator()           ] start listending for http requests
618084ms webserver_plugin.cpp:138      operator()           ] start listening for ws requests
618085ms node.cpp:4583                 load_configuration   ] generating new private key for this node
618087ms p2p_plugin.cpp:644            operator()           ] Configuring P2P to listen at 0.0.0.0:2001
618087ms p2p_plugin.cpp:650            operator()           ] P2P adding seed node 52.207.85.82:2001
618087ms p2p_plugin.cpp:650            operator()           ] P2P adding seed node 52.207.85.82:2001
90003 already_connected_to_requested_peer: already connected to requested peer
already connected to requested endpoint 52.207.85.82:2001
    {"endpoint":"52.207.85.82:2001"}
    node.cpp:4775 connect_to_endpoint
619156ms webserver_plugin.cpp:310      plugin_initialize    ] configured with 256 thread pool size
619163ms webserver_plugin.cpp:319      plugin_initialize    ] configured http to listen on 0.0.0.0:8090
619163ms webserver_plugin.cpp:328      plugin_initialize    ] configured ws to listen on 0.0.0.0:8090
619187ms p2p_plugin.cpp:614            plugin_initialize    ] caught exception 0 exception: unspecified
process exited with: Host not found (authoritative) 
    {"message":"Host not found (authoritative)"}
    asio.cpp:88 resolve_handler

    {}
    asio.cpp:168 resolve

    {"endpoint_string":"seed.blackrift.net:2001"}
    p2p_plugin.cpp:72 resolve_string_to_ip_endpoints while adding seed node seed.blackrift.net:2001
619195ms witness_plugin.cpp:639        plugin_initialize    ] Initializing witness plugin
`

I'm using the Steem docker image.

**Comment by abitmore** [comment]
@alenn-m please submit a new issue. IMHO it's a new bug introduced with appbase, although similar behavior to the OP one.

**Comment by abitmore** [comment]
@TimCliff this is a new bug and should get fixed. If @alenn-m didn't create a new issue for it, please help do so. Thanks.

**Comment by alenn-m** [comment]
#2594 Please update the issue with additional information if needed, I'm not sure if the report is correct
