### ISSUE TITLE
Permanent Editting

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#772]
Comments should be editable forever.

**Comment by Team-Steem** [comment]
Like it was mentioned in the comment, there need to be a security measure to protect from defacing when the posting key gets compromised. I feel like the security measure should even protect from whatever keys being compromised.

**Comment by Team-Steem** [comment]
Also a neat feature would be to be able to create post that's can't be edited after x amount of time. 

I know it's already the case that posts aren't edited but I'm thinking that this feature could be use to make prediction in the future and people would be easily be able to point out the posted wasn't edited.

**Comment by Team-Steem** [comment]
Also I think it would be neat to be able to make some post un-editable.

**Comment by mvandeberg** [comment]
Here is the proposal to add some security to comment editing.

All comments are editable within the first 24 hours. After that they are "soft" locked. An account can temporarily unlock editing of their content using their active authority. The operation would include an end time. If a user wanted all of their content to be editable for all time, they could specify a very long expiration date for the permission.

``` c++
struct enable_comment_editiing_operation
{
   account_name_type account;
   time_point_sec    expiration;
};
```

This would be implemented using a custom operation and a soft-fork so that only block producers need to pay attention to the status of comment locking.

Effectively the policy becomes for all witnesses to reject edits after 24 hours as a security measure unless you tell the witnesses you want to edit using an elevated authority.

**Comment by mvandeberg** [comment]
Merged
