### ISSUE TITLE
Comment Reward Beneficiaries

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#773]
As a comment option, authors should be able to specify a number of beneficiaries to receive a percentage of the rewards and the percent of the potential liquid rewards to receive as Steem Power. Unallocated rewards by default go to the author as they currently do.

**Comment by 21xhipster** [comment]
Should work for comments also. Especially if #774 will be implemented. Comments to the same post can be published from different apps. Developers should be rewarded for all efforts.

**Comment by mvandeberg** [comment]
Yes. All content will be eligible for this.

**Comment by mvandeberg** [comment]
The `comment_options_operation` extension field can contain a vector of pairs of account names and weights to specify the comment beneficiaries. 

```
struct comment_payount_beneficiaries
{
   vector< std::pair< account_name_type, uint16_t > > beneficiaries;

   void validate();
};
```

Beneficiaries can be set when there are no votes on a comment. Setting options of any kind should be done in the same transaction that the comment is created in.

**Comment by mvandeberg** [comment]
Testing is waiting on #659 to be merged.

**Comment by mvandeberg** [comment]
Merged
