### ISSUE TITLE
Proposal: Specifying Vesting Withdrawal Destination

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#78]
Currently when a vesting withdrawal is processed, the STEEM is deposited in the account on which the vesting withdraw was processed. There is desire within the dev team to be able to immediately vest those funds in a different account which can currently be done through a transfer_to_vesting_operation. However, the conversion from VESTS to STEEM back to VESTS will lose value on the conversions and a bot must be ran to submit the operation immediately to minimize value lose from inflation. This use case is common enough that it would be a useful blockchain operation.

Thus, I am proposing adding a set_withdraw_vesting_destination_operation. The operation itself would simply specify destinations for vesting withdrawals as a percent of the account's current vesting withdraw rate with the option to automatically vest. If the funds would be automatically vested, it would simply transfer the vests to eliminate value loss. The operation could be specified multiple times for multiple different accounts so long as the percentage did not exceed 100%. An op with a percent of 0% would remove the destination. Any percentage not accounted for with the operation would be deposited into the origin account as is done currently.

What would the op actually look like and what supporting data structures do we need to support it?

``` c++
struct set_withdraw_vesting_destination_operation : public base_operation
{
   string from_account;
   string to_account;
   uint16_t percent;
   bool auto_vest;

   void validate()const;
   void get_required_active_authorities( flat_set< string >& a )const { a.insert( from_account ); }
}
```

The op itself is pretty straightforward. The from_account is the account doing the withdrawal. The to_account is the destination fora percent of the funds after the withdrawal. Finally, there is the option to automatically vest the funds in the new account after the withdrawal.

``` c++
struct vesting_withdraw_destination
{
   account_id_type from_account;
   account_id_type to_account;
   uint16_t percent;
   bool auto_vest;
}
```

The supplemental database object would contain the same information. From an implementation viewpoint, we can store the account's as account ID's as this does not need to be exposed directly through an API. A suitable API call would be best to contain a list of all destinations and it would be simple enough to resolve account IDs to names then. This object would be indexed on a composite key of from_account and to_account.

The vesting withdraw logic would remain the same except that the VESTS would be divided up by the vesting withdraw destinations. Changing the withdraw amount of account would not have an effect of the destinations and they would persist after vesting withdraws stop.

This solution solves the original problem and then some. It allows an account to specify multiple destinations, some receiving STEEM and some receiving VESTS to receive it's vesting withdrawals with the addition of only a single operation and one more database object.

This can all be done with a bot, but as stated earlier, a bot would cause loss of value. A bot also needs to monitor the blockchain the create the transaction to allocate funds properly. The bot also needs the account's private key in memory to create the transactions. It could also be done in a plugin. This would remove the `set_vesting_withdraw_destination` operation from the core protocol and make the `vesting_withdraw_destination` object optional in the database. However, to do the transfers, the plugin would need to create a transaction the same as the bot and also would require access to the private key of the account. Adding this to the core protocol is the only way to maintain value on the transfers and only requires the private key in the CLI wallet as we currently require.

The real question here is, "Is the core chain the right place to place this functionality?"

**Comment by arhag** [comment]
Along these same lines, it would great if the operation was later augmented to allow a third option other than convert withdrawal to STEEM or keep withdrawal as VEST. That third option would be for the blokchain to automatically convert that portion of the VEST into SBD (by converting VEST to STEEM and then using the internal market to trade the STEEM for SBD) before depositing the SBD to the `to_account`. Perhaps the operation could even specify a limit price and any STEEM not successfully converted at time of withdraw would be given to the `to_account` as STEEM.

This enhacement to your proposed enhancement, along with a reverse feature to automatically trade SBD for STEEM and autovest the proceeds and the fact that the internal market is expected to be highly liquid, means that regular users would almost never need to deal with the inflationary STEEM asset. They can vest their Steem Dollars into Steem Power, and set their Steem Power to withdraw automatically into Steem Dollars.They would later be able to trade Steem Dollars for BTC or USD in exchanges as well. From their perspective, there would only be two tokens in the system.

**Comment by jcalfee** [comment]
We might need one of these on a per-post or per-comment level.  Any-time says: the proceeds for this post will go to someone else, this would be the case to use that.  That someone else just need to make a steemit account.

**Comment by jcalfee** [comment]
It is almost as if you could extend this operation and add an optional destination {to_account, auto_vest}.

**Comment by arhag** [comment]
> We might need one of these on a per-post or per-comment level. Any-time says: the proceeds for this post will go to someone else, this would be the case to use that.

+1 Great idea.

**Comment by mvandeberg** [comment]
Merged into develop
