### ISSUE TITLE
Refactor reward computation to do threshold check based on STEEM rather than SBD

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#785]
[This check](https://github.com/steemit/steem/blob/ddc577351294213aa7dacd982d1dab854f1fcfa0/libraries/chain/database.cpp#L2482) should be done based on checking the STEEM amount against a `min_payout_steem` variable instead, which is computed once per block based on the exchange rate.

**Comment by theoreticalbts** [comment]
For purposes of this discussion, define the following checks:

```
dust(payout) = (to_sbd(payout) < STEEMIT_MIN_PAYOUT_SBD)
```

There must be some maximum value `x` such that `dust(x) == true`.  We are tempted to say `x = to_steem(STEEMIT_MIN_PAYOUT)` but this is not necessarily true due to rounding.  Let's figure out the rounding exactly.

So the Steem/SBD price is `P = current_median_history`.  Let `P.sbd` be whichever of `{P.base, P.quote}` is priced in SBD.

First of all, if `P.is_null()` then `dust(z)` is false for all `z`, I'll say here that `x = -1`, but we'll talk more about this below.

Now let's cover the case where `P` is not null. Since `dust(x)` and not `dust(x+1)`, it follows that:

```
dust(x) -> x * P.sbd / P.steem < STEEMIT_MIN_PAYOUT_SBD
!dust(x+1) -> (x+1) * P.sbd / P.steem >= STEEMIT_MIN_PAYOUT_SBD
```

from this follows:

```
x < STEEMIT_MIN_PAYOUT_SBD * P.steem / P.sbd
x >= STEEMIT_MIN_PAYOUT_SBD * P.steem / P.sbd - 1
```

So we now know `x`:

```
x = ceil(STEEMIT_MIN_PAYOUT_SBD * P.steem / P.sbd - 1)
```

**Comment by mvandeberg** [comment]
This was changed many months back.
