### ISSUE TITLE
Groups for Steem

### ISSUE THREAD

**Issue by samupaha** [steemit/steem#791]
One of the most important features that Steem currently lacks is **groups**. We are now more like a publishing platform rather than a social network. If we want to see more meaningful discussions in Steem, we need to give users better tools to make it happen.

What we actually need? What are the essential features to have a useful group functionality? I've tried to keep in mind the KISS principle and reduced the essential features to two:
- Users need to be able to join to a group (depending on a system it can be also called subscribe or follow). If there is no "official" way to join a community, it will be very fragile – users have to make an effort everyday to check what is happening in the community. When they forget to do that, the community will die. In the case of Steem, users should have possibility to subscribe to the posts that are published in the community.
- Spammers, trolls and other unwanted users have to be excluded. There can't be a community if anybody can stay as a member even when they don't have any respect for other members. In the case of Steem, there must be a way to prevent users posting to the community. If there is no moderation, the group will be eventually ruined by spammers. We have seen this happening in the internet many, many times.

Why do we need group functionality? It will be an answer to few problems:
- There is too much noise in Steem currently. Users see too much posts they are really not interested in. Steem can't grow if it's not possible for users to find interesting content and like-minded people. Most people will find Steem unusable and leave it because it requires too much effort to find something actually enjoyable reading. I think "too much noise" is one of the most underestimated problems of Steem. People don't stay on the platform if the signal-to-noise-ratio is bad.
- There are no ways to build meaningful communities. Without group functionality in the blockchain, users can't create real communities. If a community is born, but there is no actual way to join in and exclude people from it, it will stay very shallow and disintegrate very easily. Most communities will be short-term fads.
- Newbies need to get their voices heard. Currently we see lots and lots of new users who post a few times, do not get any meaningful response and decide that "Steemit is not for me" and leave the platform. This is really bad thing. If we can't get newbies stay, Steem will stay small forever.
- Quality of posts will be better. Group owners/moderators want to make sure their community is great so they try to encourage good posts and discourage bad ones.
- Depending on how much the group creation fee is, this can also create more demand for steem and remove it from circulation. It won't be a huge factor, but it's still something. One big reason for steem price being very low is that there are very few ways to use steem (or steem dollars). There is nothing you can buy with them. Instead people cash out the money they earn by blogging which creates constant selling pressure. Buying a group is one real way of spending steem.
- Strong communities create loyalty. Loyalty creates long-term success. With group functionality Steem will build loyal userbase.

Technical details:
- I'm not a blockchain dev, so feel free to implement groups as you see best. But my suggestion is that it can be implemented as ownable tags. Anybody can buy a tag and decide who can post using it. This can be done with blacklisting and whitelisting. And users should be able to follow these tags. This will satisfy the minimum requirements for groups: join (with following the tag) and exclude (with blacklisting and whitelisting).
- There should be special tag for this. If normal tags can be bought, it will cause lots of dissatisfied users. Of course it can be called something else than tag. My suggestion is *steemroom*.
- Group creation fee should be destroyed to decrease the amount of liquid steem. My suggestion is that the fee should be relatively expensive (something like 25-100 dollars worth of steem).
- It's not enough if the group functionality is on the UI. It has to be on the blockchain so that groups will work same way in all UIs.

Additional features:
- Groups can be a first step towards mutual aid societies. If you add multisig account to an ownable tag, you have a group with a "bank account". That could be used as an insurance account for group members so the group would be a basic version of MAS.
- Groups could be traded in auction style in the internal exchange.

**Comment by abitmore** [comment]
https://github.com/steemit/condenser/wiki/Community-Spec-%5BDRAFT%5D

**Comment by samupaha** [comment]
> https://github.com/steemit/condenser/wiki/Community-Spec-%5BDRAFT%5D

Looking good!

**One suggestion for community parameters:**

> `language`: primary language. `en`, `es`, `ru`, etc

Better use a proper standard to avoid unclear language definitions. [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) has all the spoken languages and it's intended to be used as metadata in the internet. It's best for our needs, too.

**From todo:**

> sharing of post revenue with community account

So basically this means that communities can own currencies just like other accounts? This is a great feature and it should be promoted when communities are ready for use. I can imagine lots of usecases for it.

**And one important point to be discussed:**

How much a community should cost?

- It can't be free or almost free because users will hoard all the cool names and bloat the blockchain.
- It can't be too expensive because then the feature will be underutilized.

Steem that is used to create a community should be destroyed. That will create a real natural demand for steem and, at the same time, decrease the amount of liquid steem which will help the price in the long term (double-win, hooray!). Maybe the best way to look at price setting is to ask: **What the price should be so that we can get as much steem burned as possible?** Basically same question that businesses ask when they price their products. Too low price and there will be less profits, too high price and there will be less customers.

**Comment by mvandeberg** [comment]
Because communities are going to be handled by condenser, not steemd, I am closing the issue here.
