### ISSUE TITLE
Wrong assert for STEEMIT_OWNER_UPDATE_LIMIT

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#794]
Getting:
`Owner authority can only be updated once a minute.` from `STEEMIT_HARDFORK_0_11`
instead of 
`Owner authority can only be updated once an hour.` from `STEEMIT_HARDFORK_0_12`

Of course:
`#define STEEMIT_OWNER_UPDATE_LIMIT                          fc::minutes(60)`

**Comment by abitmore** [comment]
This has been reported in #413, should have been fixed.. still there?

**Comment by abitmore** [comment]
Perhaps other messages reported in #413 hasn't been fixed as well.

**Comment by mvandeberg** [comment]
The message was correct at [steem_evaluator.cpp:1828](https://github.com/steemit/steem/blob/master/libraries/chain/steem_evaluator.cpp#L1828) but not at [steem_evaluator.cpp:195](https://github.com/steemit/steem/blob/master/libraries/chain/steem_evaluator.cpp#L195)
