### ISSUE TITLE
Check for recursive locking

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#797]
According to [the Boost docs](http://www.boost.org/doc/libs/1_57_0/doc/html/interprocess/synchronization_mechanisms.html#interprocess.synchronization_mechanisms.mutexes):

 """
A mutex can also be recursive or non-recursive:

- Recursive mutexes can be locked several times by the same thread. To fully unlock the mutex, the thread has to unlock the mutex the same times it has locked it.
- Non-recursive mutexes can't be locked several times by the same thread. If a mutex is locked twice by a thread, the result is undefined, it might throw an error or the thread could be blocked forever.
"""

That means we should do one of the following:

- Use recursive mutexes
- Update the lock checking code to ensure the mutex only locks once

**Comment by mvandeberg** [comment]
This was implemented.
