### ISSUE TITLE
Unable to delete a comment that use to have a reply

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#80]
Create a comment, make a reply, delete the reply using the delete_comment operation, then try to delete the comment:
```
TransactionSaga	broadcast Error: 10 assert_exception: Assert Exception
comment.children == 0: comment cannot have any replies
```

**Comment by abitmore** [comment]
Good to record it on Github. I reported this 2 weeks ago in Slack, thought it's solved already, but apparently it's not (my bad to haven't check it again).
Need a `parent_comment.children--` in `delete_comment_evaluator::do_apply`

**Comment by abitmore** [comment]
Fix of this issue need a hard fork.

**Comment by abitmore** [comment]
For `LOW_MEMORY_NODE`, need to do `parent_comment.children--` *once*; for full node, need to recursively do `parent_comment.children--` to the root.

**Comment by abitmore** [comment]
Need to re-tally `children` of all posts at the hard fork time.
