### ISSUE TITLE
Refactor adjust_rshares2 to be non-recursive

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#803]
`adjust_rshares2` does two separate things:

- (A) Update the `children_rshares2` method of the current comment and all ancestors
- (B) Update the `total_reward_shares2` of `dynamic_global_properties`

Address this with the following strategy:

- Refactor (A) into its own function called `update_children_rshares2()`
- Refactor `update_children_rshares2()` to use a `while` loop instead of recursion
- Have `adjust_rshares2()` call `update_children_rshares2()`

Related:  #801 #774

**Comment by theoreticalbts** [comment]
Added to HF17 because this blocks #774.

**Comment by mvandeberg** [comment]
Merged
