### ISSUE TITLE
Possible inconsistent `virtual_supply`

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#82]
1. `virtual_supply` hasn't always been updated accordingly after `update_median_feed()` is called, which will cause assertion failure while checking invariant consistency at https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L3153-L3154. `virtual_supply` is only re-calculated in `adjust_supply(SBD)` and `update_global_dynamic_data()`, the former is called only when content payout happens, the latter is called before `update_median_feed()` (see https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2230-L2244). 

2. https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L1891 and https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2844 will likely cause rounding issues.

These issues need to be fixed before the first payout which will happen on July 4th.

**Comment by mvandeberg** [comment]
I believe this is no longer an issue?

**Comment by abitmore** [comment]
Should have been fixed. Closing for now.
