### ISSUE TITLE
REGISTRATION DOES NOT WORK!!!!

### ISSUE THREAD

**Issue by dacom-dark-sun** [steemit/steem#820]
I have tried it 1 week ago and now too. I cannot complete registration for account with Russian and Sweden phone number. Error is same: Unfortunately, we don't yet have support to send SMS to your carrier, please try again later. CONTINUE

IF YOU WANT THAT NEW MEMBER JOIN TO COMMUNITY -- SOLVE IT IMMEDIATELY!

**Comment by taoteh1221** [comment]
They might want a highly visible link on the registration page to a support desk to retain new signups manually. @dacom-dark-sun, this issue may apply more to the steemit.com repo, not the steem repo.

**Comment by mvandeberg** [comment]
This is a problem with steemit.com, not the Steem Blockchain. I will forward this to our web dev team. Closing this ticket as it is not relevant to this repo.

**Comment by cheetahfm** [comment]
Could you give a link to the forwarded issue? I'm having the same problem at the moment and could not find that issue elsewhere.
