### ISSUE TITLE
Fix compiler warnings due to ASCII art

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#823]
My tree diagrams in `basic_tests.cpp` have lines ending with backslash in a `/* */` style comment, and this is causing `g++` to spit out warnings.  Let's fix this.

**Comment by mvandeberg** [comment]
This looks complete but does not have PR

**Comment by theoreticalbts** [comment]
Created PR.

**Comment by mvandeberg** [comment]
Merged
