### ISSUE TITLE
Read Only Nodes Not Reading Block Log

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#842]
Read Only nodes are not opening the block log and cannot serve requests for irreversible blocks.

All access to the block log should be done within the same `with_read_lock` code blocks and all writes to the block log should be done within `with_write_lock` code blocks. To prevent corruption of the block log, it is already opened in append or read only mode for what is needed.

A read write/read only flag should be send to the block log on instantiation to enable/disable various functionality as one more layer of protection.

The block log location is implied by the location of the data dir. As the block log needs to be shared among nodes and it is possible to have multiple data dirs pointing to the same shared memory file, the block log location should be configurable in the same way that the shared memory file is.

**Comment by mvandeberg** [comment]
There is some strange OS level behavior regarding file state when opening and closing the block log that prevents the current implementation from being useful. Removing this from HF 17 and we will address it shortly after the hardfork has been released.

**Comment by theoreticalbts** [comment]
OK, on looking at the code we have a problem.  The `std::fstream` class is *buffered* which means *the C++ standard library* is allowed to buffer some data about the file.  Basically `std::fstream` assumes *no other process will access the file*.  This is what's broken, and here's my advice:

- The fastest fix is probably to have read nodes never open the block log, and instead delegate `get_block()` calls to the write node.
- Another possibility is to have readers create a new `fstream` or `close()/open()` the file every time a block is produced.
- A better fix may be to change the implementation from `fstream` to a memory-mapped file, which is correctly shared between processes.

**Comment by mvandeberg** [comment]
I have tried closing and opening the file after each read and each write on both the read and write nodes and this does not solve the problem. I am alright with this being a buffered stream. A delay of 1 second when reading a block is not problematic. However, changes to the file never being reflected outside of the process when close is explicitly called is a problem.

I was toying with the idea of making this a memory mapped file but was vetoed by Dan. The point of the block log is to be an independent source of validity for the blockchain. If the block log is stored in a memory mapped file then it is no longer easily readable by other applications.

I am not opposed to making those calls forward to a write node as well, but I want to spend more time refining this code that implements the call forwarding. It works* for the network broadcast API but I know it is fragile.

**Comment by abitmore** [comment]
Can we route `get_block` API to the correct node at the reverse proxy layer (HA-proxy or nginx)? @sneak

**Comment by jredbeard** [comment]
While forwarding `get_block` calls to the write-node is a short-term fix that makes read-only mode theoretically usable, it isn't the long-term fix we're looking for. In the case of SBDS (which makes a large amount of get_block calls especially upon initial sync), we'd be restricting it to only one thread.

**Comment by mvandeberg** [comment]
This is a rather large change that needs a full spec associated with it. Postponing the issue until we can get a spec written.
