### ISSUE TITLE
Steem Installation - Suggestion to correct and help novice users (building.md)

### ISSUE THREAD

**Issue by theghost1980** [steemit/steem#849]
Would be possible to add some extra lines about swapping units?
Some days ago I was fighting to get Steem installed on a Virtual machine under ubuntu 16.04 lts. I was getting some errors, so after some research, the following steps helped me to install it.

- sudo dd if=/dev/zero of=swapfile bs=1M count=3000
(count represents the capacity of the file, to help with the swap during the installation. 3000 = 3G)
- sudo mkswap swapfile
(Now change the file created to a swap file with the command above)
- sudo swapon swapfile
(in the second line we turn on the swap file)

After this the installation should runs smoothly.
So my suggestions is to add this comments in the same file "building.md" (I could do it by myself, but I'm a newbie user so I prefer to ask and suggest first)
Thanks!

(this commands can be studied deeper in the following [link](https://digitizor.com/create-swap-file-ubuntu-linux/))

**Comment by mvandeberg** [comment]
What were the specs of the VM you were trying to build on?

This is more of a system configuration problem than part of the build process. We have stated some minimum system requirements in blog posts, but they should be included in the readme.

**Comment by theghost1980** [comment]
Basically I'm using virtual box with Ubuntu 16 as OS. I was following the tutorial of @pcste from steem it, specifically [this one](https://steemit.com/mining/@pcste/up-to-date-mining-steem-tutorial-for-newbies-windows-or-linux)  Then I discovered the swap file, in order to install it. It looks like it needs a lot of memory. Now what I think it may be is the capacity of the HDD machine. I have it set at 30GB. In the steem.chat @pfunk told me something about the witness mode.

Do you think is related to low hdd storage?

Some specs of the Virtual machine:
Ubuntu 16.04
1024 GB ram memory
30 GB HDD

Thanks for your time!

**Comment by theghost1980** [comment]
HI there is it possible to mine with MAC OS?

Im trying to install it. So after trying to build steem, I get this:

CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindOpenSSL.cmake:385 (find_package_handle_standard_args)
  libraries/fc/CMakeLists.txt:152 (find_package)

**Comment by mvandeberg** [comment]
> CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
>   OPENSSL_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindOpenSSL.cmake:385 (find_package_handle_standard_args)
>   libraries/fc/CMakeLists.txt:152 (find_package)

The build instructions for OSX cover the environment setup needed to avoid this error.

As for the swap file, it is because you are running with 1 GB or RAM in the VM. The linking step of the build process uses a decent amount of memory. In my testing 4 GB seems to be sufficient, which appears to have fixed your problem as well (1 GB RAM + 3 GB SWAP). I would highly recommend upping the RAM in your VM to 4GB. Also, if you don't want to have to build manually, you can set up docker and docker-machine on OS X and it will handle the build for you.

Yes, you can mine on OS X. However, in the next hardfork, we are planning on removing mining altogether.

**Comment by theghost1980** [comment]
Hi Michael thanks for answer.
So there will be no more mining, I guess only by using the platform would
be possible to create steem. Also may I ask, are you moving to PoS as well?

**Comment by mvandeberg** [comment]
Being rewarded by using the platform or becoming a witness are the ways to earn STEEM.

Steem is already DPoS. We have been running a hybrid PoW/DPoS scheduling algorithm and are moving to pure DPoS.

**Comment by mvandeberg** [comment]
This looks like it is not a problem. Closing
