### ISSUE TITLE
Add operation to allow author to decline payment above threshold 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#85]
- ~~allow author to specify a beneficiary~~
- allow author to specify auto conversion to steem power (no Steem Dollars) this may help some people with tax implications.
- allow author to enable / disable curation rewards on their post
- allow author to disable replies to their post
- allow author to disable voting on their post

This should be added as a new operation that gets included in the same transaction (right after creating a post).

Maximum payout can be lowered but not increased after there is a pending payout.

**Comment by mvandeberg** [comment]
Merged into develop
