### ISSUE TITLE
get_discussions_by_blog stops short in some cases

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#852]
Reported in https://github.com/steemit/steemit.com/issues/1109 -- it appears that in some cases it is impossible to load all of an author's posts. For instance, when loading https://steemit.com/@papa-pepper, the last post shown is "THE EDIBLE OUTDOORS 2 - Lamb's Quarters". 

---

Here is the API call to reproduce the issue. It returns only 7 posts, when there are certainly more.

`get_discussions_by_blog({limit:20,start_author:"papa-pepper",start_permlink:"how-the-steemit-payouts-just-might-be-what-i-was-looking-for",tag:"papa-pepper"})`

**Comment by jnordberg** [comment]
I'm also seeing this. Seems to happen if `start_permlink` is too long.

**Comment by mvandeberg** [comment]
Closing, won't fix
