### ISSUE TITLE
Platform-independent state save/load

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#854]
To deal with reindex times, we should allow platform-independent state saving.

Some requirements:

- Support both JSON and binary formats
- Include a schema #683 and fail loading if schema mismatches
- Should include compile-time settings that affect DB content, e.g. `LOW_MEMORY_NODE` and `CLEAR_VOTES`
- Should have an interface for plugins to specify settings relevant to the DB (e.g. bucket size)
- Allow periodic saving, e.g. every 100,000 blocks starting at block 3,000,000
- Periodic saving should occur as blocks become irreversible

**Comment by theoreticalbts** [comment]
As @mvandeberg notes in #855, periodic saving of irreversible state is a difficult problem.  Saving of *current* state is a much more trivial problem.  So I propose the following strategy to implement periodic saving of irreversible state:

- Save *current* state at the prescribed interval -- e.g. `(head_block_num() % 100000 == 0)  && (head_block_num() >= 3000000)`.  Save under a temporary file, along with some metadata indicating the height and head_block_id.
- When the LIB advances, check all metadata for files at heights which have just become irreversible.
- If a temporary file matches the block ID at its now-irreversible height, finalize the temporary file by using `mv` to rename the temporary file to its permanent name.
- If a temporary file doesn't match the block ID at its now-irreversible height, finalize the temporary file by deleting it.

Instead of dumping the data to a file, let's dump it to a socket and have some out-of-process script handle it, this lets us do fancy things like compress it before it hits the disk, or stream it to S3.

**Comment by theoreticalbts** [comment]
I haven't written any code for this, so I'm removing my assignment.

**Comment by youkaicountry** [comment]
This has been moved to #3085 and #3084.
