### ISSUE TITLE
Proposal suggestion for steem

### ISSUE THREAD

**Issue by snowflake11** [steemit/steem#860]
I’ve seen some suggestions here 
https://github.com/steemit/steem/issues/690 

So hopefully it isn’t inappropriate to post mine here.

The purpose of this proposal is to re-align incentives with the vast majority of steem users, create a more scalable design,  fuel demand for the steem token and make steem more fun and engaging.

The idea of the proposal is very simple. 

Create 2 types of users : Curators and moderators.

Accounts > $8000 can only downvote ( moderators)
Accounts < $8000 can upvote/downvote (curators)

- Create incentives for users to chose moderation over curation ( moderation rewards, moderation fund,etc..)

- Hide downvotes and payout information from the interface until it’s paid out. The only info visible during voting period would be upvotes and how much one’s own vote added to the payout at the time of the vote. 

- Create a report button to facilitate moderation on a large scale

The idea was well received by the community and I would like to hear what the steem devs think about it which is why I am posting here.

For a more complete view of the proposal 

https://steemit.com/steem/@snowflake/guardian-of-the-steem-universe-a-different-take-on-the-role-of-whales-within-steem-ecosystem

**Comment by sneak** [comment]
Please constrain the issues here to technical issues with the code in the steemd implementation. This is not the right place to discuss the direction of the platform.

**Comment by snowflake11** [comment]
Sorry about that. Do you know where is the best place to discuss this please?

**Comment by TimCliff** [comment]
The best place for the discussions is in Steemit posts. If there are well thought out ideas that seem to have a lot of support, you can email them to @sneak (sneak at steemit.com) and he will review in behalf of the dev team. The devs also read a lot of the posts too, so if it received a lot of attention there is a good chance they saw it.
