### ISSUE TITLE
get_account_history API pagination does not work.

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#861]
Limit is treated like a delta, but the assertion `from >= limit` treats limit like a bound. This make pagination on the API to the beginning of account history problematic.

**Comment by roadscape** [comment]
I haven't had any issues with pagination. It's not the most straightforward but works fine.

**Comment by xeroc** [comment]
Same here .. the pysteem libraries work great and allow to go back until the very first (account_create) operation

**Comment by mvandeberg** [comment]
This was user error.
