### ISSUE TITLE
Reblogged_by array request

### ISSUE THREAD

**Issue by feruzm** [steemit/steem#873]
Not sure if this was reported.

Can we get `reblogged_by` array on `get_discussions_by_trending/hot/created/etc.` ?

Currently objects have `reblogged_by` but it is empty array.

`get_state` is being used by steemit.com for first page, pagination doesn't have reblog since above functions doesn't return value. Same goes to eSteem, `get_state` is rarely used due it's being huge request for mobile phones/network.

**Comment by mvandeberg** [comment]
The monolithic database_api that we have today is in end of life. We are going to stop supporting get_state and a lot of the APIs created for that purpose. (Don't worry, we have plans on making that information easily available). However, this is a good idea for an expansion of the follow plugin API (pass in an author permlink pair and return total reblogs).

**Comment by mvandeberg** [comment]
Closing, won't fix.
