### ISSUE TITLE
Something is broken and a lot of sites are not responding.  *FIRE!*

### ISSUE THREAD

**Issue by williambanks** [steemit/steem#878]
Getting this error from ALOT of nodes...
{"code":1,"message":"0 exception: unspecified\n10 assert_exception: Assert Exception\n!check_max_block_age( _max_block_age ): \n

Pushing block to fork database that failed to link: 0091184c5cf842096b0663623242d62f7dc09fca, 9508940

@someguy123 and @jesta are triaging the issue right now in steemit.chat #witness
The following nodes are confirmed as having this issue...
steem.ws
steemit.ws

Please check your nodes

**Comment by williambanks** [comment]
https://steemit.com/witness-category/@someguy123/witness-price-feed-disruption-most-feeds-offline

**Comment by williambanks** [comment]
We were able to isolate the cause as being a failure of monitoring to connect to a live node.  Closing the issue, apologies for the disruption.

**Comment by sneak** [comment]
Please use http://steemd.steemit.com if you require a high availability node.

**Comment by sneak** [comment]
Or wss://steemd.steemit.com
