### ISSUE TITLE
Potential overflow in recent_rshares2 computation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#883]
[Here](https://github.com/steemit/steem/blob/27c0c6c432f51fc00218f4b598a784229b521693/libraries/chain/database.cpp#L1734) we have intermediates that may overflow 128 bits, this needs to either be checked or upcast to 256-bit.

**Comment by theoreticalbts** [comment]
It seems [here](https://github.com/steemit/steem/pull/870/files#diff-778ae4a84a14457ed12b22337048d2bfR1749) that when we update it, we assert it's less than 64-bit.

**Comment by mvandeberg** [comment]
This was fixed in intermediary commits.
