### ISSUE TITLE
get_content returns empty active_votes

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/steem#892]
When called on old posts, `get_content` returns an empty array for `active_votes`

ex: `get_content "arcange", "steemsql-a-public-sql-database-with-all-blockchain-data-new-language-detection"`

If called on a more recent post, return value contains votes detail.

ex: `get_content "arcange" "steemitboard-google-chrome-extension-update1"`

This behavior, if normal, prevents to compute statistics that need to include older information. 
Any workaround?

**Comment by abitmore** [comment]
Try build with `-DCLEAR_VOTES=Off`?

**Comment by mvandeberg** [comment]
I am closing this issue. It has been dead for three weeks and we have not been able to replicate the issue internally.
