### ISSUE TITLE
Modify Dockerfile to enforce config.hpp constants are exposed via get_config.cpp

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#897]
The constants in [config.hpp](https://github.com/steemit/steem/blob/372b21f9e427656fd272803f567c115352fc52fd/libraries/protocol/include/steemit/protocol/config.hpp) should all be exposed in [get_config.cpp](https://github.com/steemit/steem/blob/372b21f9e427656fd272803f567c115352fc52fd/libraries/protocol/get_config.cpp).  However, frequently constants are added to `config.hpp` but don't make it into `get_config.cpp`.  So let's make CI fail so such patches can't get into `master`.

**Comment by mvandeberg** [comment]
Good call. I am guilty of this. Best way to make this a habit is to require it.

**Comment by theoreticalbts** [comment]
[Here](https://adm1.steem.house/job/Steem-multibranch/job/897-ci-get-config/1/console) is a failing CI build which shows that it fails if there's a diff.  I'll fix the diff and make a PR for the passing version.

**Comment by mvandeberg** [comment]
Merged
