### ISSUE TITLE
Issues in 0.5.0

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#90]
This is a re-post of https://github.com/steemit/steem/issues/54#issuecomment-222043305 

Issues found in 0.5.0:
* [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2924) reads from a negative array index if the program is started with a new database, however it's already there for a long time but didn't make trouble so far.
* [this assertion](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2926) will fail when a hard fork is delayed due to insufficient participation rate. It can be get around by starting with `--replay`
* [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L773) will cause another `array index out of bound` issue when trying to downgrade from 0.6.x to 0.5.0. In addition in [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L771), the condition after `||` is redundant with [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L767)
* [this check](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L1110) doesn't guarantee 75% participation rate, in case when the miner and the runner up witness and 15 elected witnesses are upgraded, this check will return `true`, but participation rate in next rounds is 15/21=71.4%

**Comment by mvandeberg** [comment]
1. The negative array index only occurs if you run a node that knows of no hardforks and has no hardforks. That is not the case with currently supported version of steemd. I view it as a non-issue. If a user runs into that problem it is because they modified the source themselves.

2. The assertion can be removed.

3. I need to redo that code block.

4. I had originally meant to not count the mining witness, which would guarantee 75%. We can either leave it as is, or change in the next hardfork.

**Comment by abitmore** [comment]
> 1. The negative array index only occurs if you run a node that knows of no hardforks and has no hardforks. That is not the case with currently supported version of steemd. I view it as a non-issue. If a user runs into that problem it is because they modified the source themselves.

It occurs when the node has no hard fork applied, no matter how many hard forks it knows. Here are logs when started with `--resync` (I added some logging before [the line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2924) for testing):
```
3046294ms th_a       database.cpp:2923             init_hardforks       ] hardforks: {"id":"2.20.0","processed_hardforks":["2016-03-24T16:00:00"],"last_hardfork":0,"current_hardfork_version":"0.0.0","next_hardfork":"0.0.0","next_hardfork_time":"1970-01-01T00:00:00"}
3046295ms th_a       database.cpp:2924             init_hardforks       ] hardforks.last_hardfork - 1: -1
3046295ms th_a       database.cpp:2925             init_hardforks       ] _hardfork_times[ hardforks.last_hardfork - 1 ]: 1970-01-01T00:00:00
```
Obviously `hardforks.last_hardfork` is initialized with `0`, so the node tried to read `_hardfork_times[-1]` which results in undefined behavior. 

It's probably OK to view it as a non-issue, as I already mentioned "it's already there for a long time but didn't make trouble so far". But it has nothing to do with whether "user modified the source".

**Comment by abitmore** [comment]
Using `STEEMIT_BLOCKCHAIN_VERSION` instead of `STEEMIT_NUM_HARDFORKS ` in commit 56461684c9adf9e61c1d2ba539c903d8acf0d58c is not suitable:
* when there is a minor version upgrade, for example 0.6.0 -> 0.6.1, [Line 767](https://github.com/steemit/steem/commit/56461684c9adf9e61c1d2ba539c903d8acf0d58c#diff-778ae4a84a14457ed12b22337048d2bfR767) will return true, if binary doesn't know a new hard fork, it will raise "array index out of bound" error at [Line 768~770](https://github.com/steemit/steem/commit/56461684c9adf9e61c1d2ba539c903d8acf0d58c#diff-778ae4a84a14457ed12b22337048d2bfR768);
* Assuming hard fork versions are always x.y.0, [Line 773](https://github.com/steemit/steem/commit/56461684c9adf9e61c1d2ba539c903d8acf0d58c#diff-778ae4a84a14457ed12b22337048d2bfR773) causes unable to downgrade to a version other than x.y.0 (for example 0.6.0 -> 0.5.1).
