### ISSUE TITLE
YAVAP - yet another voting algorithm proposal

### ISSUE THREAD

**Issue by dragosroua** [steemit/steem#903]
1. Each upvote will contain a tip equal to the amount of Steem allocated from the reward pool.

Ex: if I upvote and my vote is worth 10 cents, the post will receive 20 cents: 10 from the reward pool, 10 from my liquid Steem account. For each vote, I will pay something from my own account and put skin in the game (or, in other words, I will make use of my stake).

2. Each downvote will incur a CBP (contract breaching penalty) from the downvoter, equal to the amount of Steem taken from the post.

Ex: if a downvote takes out 10 cents from what a post already received, the downvoter will also have to pay 10 cents in Steem from his liquid Steem account. The total amount will be redistributed as follows: 50% will be sent to the upvoters accounts, as a form of compensation (remember, they also paid with liquid Steem from their own accounts) and 50% back to the reward pool (just as it is right now). The amount sent to upvoters will be distributed equally among all upvoters, regardless of their contribution.

Details and benefits here:  https://steemit.com/steemit/@dragosroua/yavap-yet-another-voting-algorithm-proposal-or-what-i-actually-understand-by-proof-o-stake

**Comment by dragosroua** [comment]
Seems I'm not a developer, looks like I'm not qualified to open issues or make proposals, so I'll just close this. Cheers!

**Comment by sneak** [comment]
This is an interesting proposal, but should be discussed on steemit.com first before any GitHub issues are created.
