### ISSUE TITLE
`get_key_references` not working on steemd.steemit.com

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#904]
For some reason, the steemd.steemit.com API does not return the account names that carry a specific public key:
```
2017-03-05 17:58:07,388 - grapheneapi.graphenewsrpc - DEBUG - {"params": [2, "get_key_references", [["STM6xpuUdyoRkRJ1GQmrHeNiVC3KGadjrBayo25HaTyBxBCQNwG3j"]]], "jsonrpc": "2.0", "method": "call", "id": 7}
2017-03-05 17:58:07,513 - grapheneapi.graphenewsrpc - DEBUG - "{\"id\":7,\"result\":[[]]}"
```
The key `STM6xpuUdyoRkRJ1GQmrHeNiVC3KGadjrBayo25HaTyBxBCQNwG3j` is part of `xeroc` as posting key.

**Comment by mvandeberg** [comment]
I am not sure why the error message for this is not being returned. This API is deprecated.

```c++
/**
 *  @return all accounts that referr to the key or account id in their owner or active authorities.
 */
vector<set<string>> database_api_impl::get_key_references( vector<public_key_type> keys )const
{
   FC_ASSERT( false, "database_api::get_key_references has been deprecated. Please use account_by_key_api::get_key_references instead." );
   vector< set<string> > final_result;
   return final_result;
}
```

**Comment by dacom-dark-sun** [comment]
Have a same issue!

**Comment by xeroc** [comment]
@mvandeberg I am using get_key_references from the account_by_key_api .. 

```
2017-03-07 09:25:49,292 - grapheneapi.graphenewsrpc - DEBUG - {"id": 5, "method": "call", "params": [1, "get_api_by_name", ["account_by_key_api"]], "jsonrpc": "2.0"}
2017-03-07 09:25:49,317 - grapheneapi.graphenewsrpc - DEBUG - "{\"id\":5,\"result\":2}"
```

Thus, API id is `2` which is used in the call above

**Comment by theoreticalbts** [comment]
Thanks for the report.  It looks like we didn't reindex with the account_by_key plugin, so those records weren't created.  This is a configuration issue on our internal infrastructure, not an actual steemd issue.

We're about to do a new tag, at that point steemd.steemit.com will be reindexed.  The issue should be fixed then.

[This ticket](https://github.com/steemit/steem/issues/285), planned for 17.1, will make this kind of misconfiguration harder.

**Comment by xeroc** [comment]
Thanks, Ben!
I'll keep the ticket open to not confuse any of your issue tracking procedures.

**Comment by mvandeberg** [comment]
On our dev server the API call works. Closing this as it will be resolved on production servers in the next release.
