### ISSUE TITLE
Could not create account due to insufficient fund

### ISSUE THREAD

**Issue by lightingghost** [steemit/steem#906]
10 assert_exception: Assert Exception creator.balance >= o.fee: Insufficient balance to create account. {"creator.balance":"23.310 STEEM","required":"35.000 STEEM"} th_a steem_evaluator.cpp:116 do_apply {"op":["account_create",{"fee":"35.000 STEEM","creator":"steem","new_account_name":"lightingghost","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8G4dWQvsCQCe2s3MKAJvMamKDP78aDVAojBN2WnLyLbZmYeeRn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6vNS4TDgXSwBkJDaVatGwVo8GoU1uxAw5DaVLqhBFTZVbKqvAw",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7oajqkotePFnDfyWqCNStXx5YxBuzXU1rxHuZ8GNMh1Zw3dVYN",1]]},"memo_key":"STM8fd7pJg7SXuxHEYcJorwSfsfwgetz25iqrXkXUL2k54R6fdJUn","json_metadata":""}]} th_a database.cpp:3309 _apply_transaction {"trx":{"ref_block_num":48418,"ref_block_prefix":2777151087,"expiration":"2017-03-06T19:09:21","operations":[["account_create",{"fee":"35.000 STEEM","creator":"steem","new_account_name":"lightingghost","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8G4dWQvsCQCe2s3MKAJvMamKDP78aDVAojBN2WnLyLbZmYeeRn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6vNS4TDgXSwBkJDaVatGwVo8GoU1uxAw5DaVLqhBFTZVbKqvAw",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7oajqkotePFnDfyWqCNStXx5YxBuzXU1rxHuZ8GNMh1Zw3dVYN",1]]},"memo_key":"STM8fd7pJg7SXuxHEYcJorwSfsfwgetz25iqrXkXUL2k54R6fdJUn","json_metadata":""}]],"extensions":[],"signatures":["2042ce8cf47603aac3cd5f4a64c2c6fd38be9c64557e6a955aeceee5a6b33d6d37245da3b9f2fac16e2c30c34f1d77147f3349991cf8ab9d198a49cf913471461f"]}} th_a database.cpp:3313 _apply_transaction {"trx":{"ref_block_num":48418,"ref_block_prefix":2777151087,"expiration":"2017-03-06T19:09:21","operations":[["account_create",{"fee":"35.000 STEEM","creator":"steem","new_account_name":"lightingghost","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8G4dWQvsCQCe2s3MKAJvMamKDP78aDVAojBN2WnLyLbZmYeeRn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6vNS4TDgXSwBkJDaVatGwVo8GoU1uxAw5DaVLqhBFTZVbKqvAw",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7oajqkotePFnDfyWqCNStXx5YxBuzXU1rxHuZ8GNMh1Zw3dVYN",1]]},"memo_key":"STM8fd7pJg7SXuxHEYcJorwSfsfwgetz25iqrXkXUL2k54R6fdJUn","json_metadata":""}]],"extensions":[],"signatures":["2042ce8cf47603aac3cd5f4a64c2c6fd38be9c64557e6a955aeceee5a6b33d6d37245da3b9f2fac16e2c30c34f1d77147f3349991cf8ab9d198a49cf913471461f"]}} th_a database.cpp:727 push_transaction {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[938,{"ref_block_num":48418,"ref_block_prefix":2777151087,"expiration":"2017-03-06T19:09:21","operations":[["account_create",{"fee":"35.000 STEEM","creator":"steem","new_account_name":"lightingghost","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8G4dWQvsCQCe2s3MKAJvMamKDP78aDVAojBN2WnLyLbZmYeeRn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6vNS4TDgXSwBkJDaVatGwVo8GoU1uxAw5DaVLqhBFTZVbKqvAw",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7oajqkotePFnDfyWqCNStXx5YxBuzXU1rxHuZ8GNMh1Zw3dVYN",1]]},"memo_key":"STM8fd7pJg7SXuxHEYcJorwSfsfwgetz25iqrXkXUL2k54R6fdJUn","json_metadata":""}]],"extensions":[],"signatures":["2042ce8cf47603aac3cd5f4a64c2c6fd38be9c64557e6a955aeceee5a6b33d6d37245da3b9f2fac16e2c30c34f1d77147f3349991cf8ab9d198a49cf913471461f"]}]]} th_a websocket_api.cpp:124 on_message digest d8a5ca3d2fd8602f807b982bf000e4f884e981e089dd3bf9faaaae5db86b3bfe transaction 22bd6ff687a5e1b3bd580109b88800000000000003535445454d000005737465656d0d6c69676874696e6767686f737401000000000103bc12f78a1318693efddc9a74b04b3f26905f99549ed13227cdc544592c0f68520100010000000001030ba999625d8b0e0820daa34b18feade8d51d9f5e674c8dc30973295ee27696b70100010000000001037ff22e76333b82fa78bafdb887784518e6744b088141a68f98cc66a9a0a33b22010003f191fd15fcb0b685588b6b2c94017a1ba1875857327e945984065b97c6a4391b0000012042ce8cf47603aac3cd5f4a64c2c6fd38be9c64557e6a955aeceee5a6b33d6d37245da3b9f2fac16e2c30c34f1d77147f3349991cf8ab9d198a49cf913471461f {"ref_block_num":48418,"ref_block_prefix":2777151087,"expiration":"2017-03-06T19:09:21","operations":[["account_create",{"fee":"35.000 STEEM","creator":"steem","new_account_name":"lightingghost","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8G4dWQvsCQCe2s3MKAJvMamKDP78aDVAojBN2WnLyLbZmYeeRn",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6vNS4TDgXSwBkJDaVatGwVo8GoU1uxAw5DaVLqhBFTZVbKqvAw",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7oajqkotePFnDfyWqCNStXx5YxBuzXU1rxHuZ8GNMh1Zw3dVYN",1]]},"memo_key":"STM8fd7pJg7SXuxHEYcJorwSfsfwgetz25iqrXkXUL2k54R6fdJUn","json_metadata":""}]],"extensions":[],"signatures":["2042ce8cf47603aac3cd5f4a64c2c6fd38be9c64557e6a955aeceee5a6b33d6d37245da3b9f2fac16e2c30c34f1d77147f3349991cf8ab9d198a49cf913471461f"]}

CREATE ACCOUNT

**Comment by mvandeberg** [comment]
We are aware the account is low on funds. Closing this as this is not a development issue.

**Comment by jcalfee** [comment]
I sent 500 STEEM
