### ISSUE TITLE
User in China can't sign up https://steemit.com

### ISSUE THREAD

**Issue by cxgreat2014** [steemit/steem#908]
Hi, yesterday, [a question in china Quora](https://www.zhihu.com/question/48976357) is viewed by 71 thousands of people, many people want to sign up to https://steemit.com , but in Phone verification, it always show "Unfortunately, we don't yet have support to send SMS to your carrier, please try again later.", 

![image](https://cloud.githubusercontent.com/assets/15062548/23640988/e03ff7c6-032b-11e7-828a-3827fba888c0.png)

hope deal this problem soon

**Comment by abitmore** [comment]
This is an UI issue which belongs to https://github.com/steemit/condenser/issues/

**Comment by abitmore** [comment]
Re-posted here: https://github.com/steemit/condenser/issues/1225

**Comment by cxgreat2014** [comment]
wow~Thank you very much. @abitmore
