### ISSUE TITLE
Revert Curve Change

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#913]
>There has been lots of discussion of new reward curves (e.g. n; modified super linear n) that could be introduced via hardfork to replace the current n^2 algorithm.  There are many slated changes for the upcoming hardfork, 17.  Some of which interplay potenitally significantly with rewards distribution, such as delegated voting. As such, we would like to allow for more time of the rewards curve discussions and move along to HF 17 without changes to those specific algorithms. To conclude, we'll make a blog post proposing HF 17 shortly

-Ned

The new curve needs to be reverted in master.

We are not against changing the curve but believe at this point in time that the changes in HF17 outweigh delaying the hardfork further to due the diligence required by this level of change.

**Comment by clayop** [comment]
As blocktrades suggested in slack, why don't you add comments(with decline payout option if possible) for each option: 1) Keeping `n^2`, 2) Changing to flatter curve. 
I think the issue we had was on whether full linear or partially linear, not superlinear or linear. The details (full vs partial) will be more discussed, determined, and applied in future hardforks IMHO.

**Comment by kopasi** [comment]
왜 이런글은 스티밋 사이트가 아닌 깃허브에서 보아야 합니까?
스티밋 재단은 @steemblog 라는 소통 계정을 가지고 있습니다. 왜 그 계정을 사용해 소통하지 않습니까?
그리고 이미 대다수의 사용자는 17 포크에서 세미선형으로 보상곡선이 수정되는것으로 알고 있습니다. 1주일도 남지 않은 현 시점에서 이것을 뒤집는것은 사용자들의 신뢰를 떨어트리는 행위입니다.

**Comment by kopasi** [comment]
경영자로서의 현재의 의사결정이 타당하다고 해도 이미 토론 과정에서 언급되었어야 하며 현재의 방식은 시기적으로 매우 좋지 않습니다. 스티밋 재단이 사용자들의 요구사항을 반영한다고 생각하면서 생겼던 사용자 신뢰를 무너트리는 결정입니다. 보상곡선의 수정 시점을 좀 더 미룬다면 얻을 수 있는 것은 없지만 잃는것은 많아지게 됩니다.

**Comment by mvandeberg** [comment]
Merged
