### ISSUE TITLE
0.17.0rc1: the first paid reply will get all rewards from the reply reward pool

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#915]
The `recent_claims` of reply reward pool is `0` before HF time.

At HF17 time, reply reward pool will be filled with 38% of total unpaid rewards.

When paying the first reply after HF17, assume there is only one reply:
```
+         rfo.recent_claims -= ( rfo.recent_claims * ( head_block_time() - rfo.last_update ).to_seconds() ) / STEEMIT_RECENT_RSHARES_DECAY_RATE.to_seconds();
// still 0
...
+      rf_ctx.recent_claims = itr->recent_claims;
// still 0
+      rf_ctx.reward_balance = itr->reward_balance;
// it's all funds in the pool
...
+            funds[ rf.id._id ].recent_claims += util::calculate_claims( current->net_rshares.value, rf );
// recent_claims now equals to the claim of that one reply
...
+         ctx.total_reward_shares2 = funds[ fund_id ].recent_claims;
+         ctx.total_reward_fund_steem = funds[ fund_id ].reward_balance; 
// local context set
+         funds[ fund_id ].steem_awarded += cashout_comment_helper( ctx, *current );
// all funds in the pool be paid out
```

**Comment by abitmore** [comment]
> The recent_claims of reply reward pool is 0 before HF time.

It's caused by [this code](https://github.com/steemit/steem/blob/v0.17.0rc1/libraries/chain/database.cpp#L1799-L1803) in `process_comment_cashout` of *database.cpp*:
```
            if( funds.size() )
            {
               const auto& rf = get_reward_fund( *current );
               funds[ rf.id._id ].recent_claims += util::calculate_claims( current->net_rshares.value, rf );
            }
```

Because `*current` will always be root posts before HF17, so `recent_claims` of the reply reward pool won't change. Instead, `recent_claims` of root post reward pool has been amplified by several times.

**Comment by mvandeberg** [comment]
*current needs to be changed to *itr. Easy fix.

**Comment by abitmore** [comment]
No, change it to `comment`, both line. `*itr* has advanced when entering the loop.

**Comment by mvandeberg** [comment]
Yes, my mistake for quickly glancing at the code. Still an easy fix.

**Comment by abitmore** [comment]
@mvandeberg I said both line.

**Comment by abitmore** [comment]
Or perhaps I should say both LINES.

**Comment by mvandeberg** [comment]
Merged
