### ISSUE TITLE
0.17.0rc1: Unclaimed reward VESTS receive no interest

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#919]
The "interest" is 15% of newly created STEEMs added to vesting funds.

In `process_vesting_withdrawals()` and `clear_null_account_balance()`, while VESTS getting destroyed, STEEMs are deducted from vesting pool using `get_vesting_share_price()` which ignores unclaimed VESTS, so the amount will be higher than the global ratio, which effectively means unclaimed VESTS earn no interest.

Is it by design?

**Comment by abitmore** [comment]
It seems unclaimed SBD will get no interest as well.

**Comment by mvandeberg** [comment]
This is intentional. One reason behind this addition is to allow the modularization of the blockchain. This is the first step towards a multi-chain fabric. An exchange might not want to keep track of all of the content and votes. As is, you are required to know who votes on what with what weight to know how much each post gets and to know the breakdown of the rewards. Placing rewards in reward balances creates an OP that is verifiable by anyone running that module but explicitly states property rights for those not running the module. We might be able to pay interest on SBD, but having the vesting steem fund be aware of the vesting reward balances defeats the purpose of the change.

**Comment by abitmore** [comment]
@mvandeberg it seems we were talking about different things.

I'm aware of the reasons behind individual reward balances. It's fine, no need to change how they're being handled. This issue is not about individual reward VESTS balances, but the total.

This issue is about individual powering downs and the `null` emptying, they're being paid too much.

**Comment by abitmore** [comment]
If people can't get the interest automatically, they'll set bots / services to collect the interest. So it will lead to more spamming to the blockchain and defeats some purpose.

Just recalled that SP is bonded to other use e.g. witness voting / content voting / bandwith, so perhaps people will claim them asap anyway.

**Comment by mvandeberg** [comment]
There is around 65.5k STEEM in the reward fund right now and around 197 million STEEM in the vesting fund. That equates to 0.033% Let's say that nobody claims their reward balance for a month (unlikely) and that 100% of the rewards are vested. Then the reward balances account for around 1% of the vesting fund. Those VESTS not in vesting balances are getting about 1% more per month than they should in an unlikely scenario. I think the amount of time it would take without anybody claiming their rewards balance for there to be a meaningful difference is acceptable.

Putting this in terms of real value. Based on the current inflation rate of 9.38%, 15% of inflation going to the vesting fund, and the current vesting fund size, over the course of a year it ends up being a difference of 432031.339 STEEM. While this seems like a lot, it only ends of being a yield of 0.219% per STEEM vested at today's vesting rate. The difference in return is less than a US savings account.

If the vesting STEEM fund were at the equilibrium value of 15% virtual supply (the point where VESTS break even with inflation) then the yield become 1.113%.

Again, all of this assuming that nobody claims their reward balances for an entire year.

**Comment by abitmore** [comment]
I agree it's not a big deal when there are much more funds in vesting pool than in reward balances. Also the interest rate is low.

By the way I found newly created VESTS by manually powering up are calculated with `get_vesting_share_price()` as well. Also witness pay.

**Comment by mvandeberg** [comment]
Yes, we are aware of the change this makes to the price of vesting shares and were comfortable with the small inconsistencies. We believe the gains are going to be so small and actions unpredictable enough that it won't be gamed.
