### ISSUE TITLE
Feature request: minimal VESTS required for posting/commenting

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#921]
Currently in the code, there is a hard-coded limit on voting: to be able to vote, people need to have at least 50,000,000 rshares aka 10,000 VESTS or a little less than 5 SP according to current ratio.

But there is no limitation for posting except bandwidth.

When registration fee get reduced and registration process get simplified, there will be more content spamming.

**Comment by mvandeberg** [comment]
I think this is a fairly minor issue, but changing the dust amount to a function of the current vesting share price and account creation fee may be a wise move.

**Comment by abitmore** [comment]
It's not about rewards but low value contents and chain bloat.

**Comment by mvandeberg** [comment]
What we should do is change how transaction bandwidth is calculated. All forum ops are 10x cheaper than everything else. A transfer only adds data to the chain itself, but not active state. A comment is significantly cheaper (per byte) and adds data to the chain and active state. We could probably use a finer grained bandwidth model to prevent cheap abuse.

**Comment by mvandeberg** [comment]
There are many changes that have been added that should fix this.
