### ISSUE TITLE
[API] Requesting new call to list reward payouts of an author/permlink tuple

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#934]
I would like to see an API call that can list the author_reward and curation_reward payouts associated with a post.

**Comment by mvandeberg** [comment]
This would require development of a new plugin and data structure to manage the mapping as we only track op history by impacted accounts, not impacted content. The SBDS may be able to handle a query of this type.

I am going to leave this open for now until we can confirm the data is accessible through another service.

**Comment by mvandeberg** [comment]
Closing, won't fix.
