### ISSUE TITLE
Unvoting affects reputation score

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#946]
When an account with 25 rep score showing on steemit.com is upvoting, it adds 0 rep; however, if it unvote later, it will harm the author's rep.

Related code is [here](https://github.com/steemit/steem/blob/v0.16.3/libraries/plugins/follow/follow_plugin.cpp#L96).

Similarly, while a downvote may not decrease an author's rep score, a following unvote will increase the author's rep score.

**Comment by mvandeberg** [comment]
This is actually occurring whenever an account with a smaller rep than the author downvotes.

Unless we want to have a comment vote object for every rep change as well (we don't) there will be one case that still can cause problems, but I think it is less likely to occur. 

If an account with less rep downvotes, then gets voted to a higher rep, and then removes the downvote, the original author with receive an upvote's worth of rep. This happens right now, but the much more common case can be easily solved.
