### ISSUE TITLE
Add steem to the list of currencies used for promotion.

### ISSUE THREAD

**Issue by williambanks** [steemit/steem#947]
>Give me a reason to buy steem here.  If I can use it for promoting content on steem, then I have an incentive to buy it.  Otherwise if I want to deal in the steem ecosystem the only currency that makes sense is Steem Dollars.  This powering up thing doesn't make sense because I don't have time to track individual customer's activity and upvote them.

Heard that from someone the other day when I was trying to encourage them to come to steemit and power up a bunch of steem.

Basically this feature request is asking for the ability to burn steem when promoting posts.
Don't make it a hidden feature, or something that requires the command line etc.  
Just put it right there in the steemit UI as an option.

It will also have the effect of pushing the price of steem up because it would reduce the supply rapidly.

I'm making a blog post about this as well.  Will update with a link here shortly so you can see my reasoning.

**Comment by Tadasu85** [comment]
Was your mind changed on this Mr. Banks? Because I think this is a good idea as well.

**Comment by mvandeberg** [comment]
Closing, won't fix.
