### ISSUE TITLE
Vote count for high voted post showing negative value on trending page

### ISSUE THREAD

**Issue by dnotestein** [steemit/steem#950]
This post: https://steemit.com/life/@hanshotfirst/emotion-vs-logic-this-town-is-big-enough-for-the-both-of-us is displaying as a negative vote count value on the trending page, although it shows a positive count when you view the vote count on the page itself.

**Comment by mvandeberg** [comment]
This is steemit.com issue. `get_state` returns an array of the active votes for each piece of content.
