### ISSUE TITLE
Update git-guildelines.md

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#973]
This is out of date.  New policy is briefly outlined [here](https://steemit.com/steem/@steemitblog/4b7tnh-steem-tech-advisory-repository-branches-to-be-renamed).

We may make some changes to avoid issues backporting things to `stable`.

**Comment by theoreticalbts** [comment]
One tricky issue is that GH branch protections, you have a dichotomy:  Either force-push is enabled, or the branch is completely unprotected.  So any scheme involving e.g. a bot that does some automated checks, followed by a force-push if the checks pass, is a non-starter (unless we want the branch to be pushable by everyone with commit privileges to the repo).

**Comment by mvandeberg** [comment]
@goldibex Is handling git rules and documentation of said rules
