### ISSUE TITLE
Follow API methods are not available through RPC

### ISSUE THREAD

**Issue by Nemo1369** [steemit/steem#979]
Follow API methods are not available through RPC even if it is mentioned in config.ini in public-api list. 

Confirmation: curl --data-binary '{"id":1,"method":"call","params":[0,"get_follow_count",["dantheman"]]}' -H 'content-type: text/plain;' https://steemd.steemit.com

The output lists all the available API methods, but there are no any follow_api methods in list.

**Comment by mvandeberg** [comment]
The first argument of the params array is the API you are querying. It should read `"params":["follow_api","get_follow_count",["dantheman"]]`
