### ISSUE TITLE
Good Questions

### ISSUE THREAD

**Issue by RongxinZhang** [steemit/steem#98]
Hi @revflash,

Love to learn more about steemit:

- How many total nodes are in the system right now?
- How many total users are there?
- Are you guys working on this full time?
- Would you guys consider proposing something on the DAO, e.g: funding the platform?

**Comment by jcalfee** [comment]
Do you mind joining our slack group?  I think you'll probably get some answers sooner there..  

http://steem.herokuapp.com/

**Comment by mvandeberg** [comment]
Closing as this isn't an issue...
