### ISSUE TITLE
Price constructor should be explicit

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#991]
A root cause of the bug in #987 was caused by am implicit conversions from `asset` to `price`. We should define the `price` constructor as explicit to fail complication on other.

**Comment by mvandeberg** [comment]
After changing the constructor to explicit, this bug shows up in the cli wallet as well.

**Comment by mvandeberg** [comment]
We want to also remove the default args from the price constructor and prevent prices from being created with a quote of 0. However, those changes are more invasive and have unintended side-effects. We will do more investigating and testing before implementing those changes.

**Comment by theoreticalbts** [comment]
Needs updated PR and possibly hardfork check.

**Comment by vogel76** [comment]
I propose to add static method:
static price nullPrice();
and use it in inital assignment in all places where directly default constructor is used.
