### ISSUE TITLE
Update price struct

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#996]
The price constructor currently specifies default values for base and quote. Prices should only be created with an explicit base and quote.

A price should not be allowed to have a base or quote of 0.

These changes should be investigated for unintended side-effects and if determined to be safe, implemented.

**Comment by mvandeberg** [comment]
Logic to handle the absence of a price feed before the first payout relied on the default "null" constructor of price. Refactoring this around these new constraints would be tedious.

I am still in favor of making the price constructor explicit to prevent any future unintended conversion to price.

**Comment by theoreticalbts** [comment]
Closing, duplicate of #991
