### ISSUE TITLE
Using account_create_with_delegation with 0 delegation creates unnecessary objects

### ISSUE THREAD

**Issue by arhag** [steemit/steem#997]
There needs to be a check for `o.delegation > 0` around [these lines](https://github.com/steemit/steem/blob/v0.18.0/libraries/chain/steem_evaluator.cpp#L268-L274).

As the code exists right now, it is inefficiently allowing unnecessary `vesting_delegation_object`s to be created. And furthermore because the `vesting_shares` of that unnecessary object would be 0, [this branch](https://github.com/steemit/steem/blob/v0.18.0/libraries/chain/steem_evaluator.cpp#L2290) of the code is activated rather than the else branch, making it difficult for the user to directly remove that object (they can still remove it indirectly by first adding more steem power to the delegation and then removing it).

If you leave this fix for a future hard fork, you will need to make sure to iterate through the `vesting_delegation_index` when the hardfork is applied and erase any objects with a `vesting_shares` field equal to 0.

It is tempting to think that this can be done as a change in v0.18.1 (with a reindex) without causing hardforks. But I believe a hardfork could theoretically be possible if someone adds a small amount (larger than `min_update` but smaller than `min_delegation`) to such a 0 `vesting_shares` object. In fact, the timing differences of `min_delegation_time` alone could cause a fork issue.

**Comment by mvandeberg** [comment]
I tend to agree with you on the fix for this. Better to do it as a hardfork and be safe then try it as a softfork and fork the blockchain.
